### PR TITLE
ceph_test_rados_api_tier: add ListSnap test

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Xuehan Xu <xuxuehan@360.cn>

### CODE REVIEW

**Comment by liewegas** [comment]
@xuxuehan this is just your test, which we'll include in master too

**Comment by xxhdx1985126** [comment]
@liewegas Hi, thanks:-)
Is the problem that this test case failed in previous QA tests solved?
As our key emphasis in work is to test cephfs of luminous recently, I can only work on this late at night and I haven't find why this case failed in the previous qa test.  If this haven't been solved, I'll try to make more time to work on this. I'm really sorry for the delay.

**Comment by liewegas** [comment]
I was just slow to review and test, and then realized that we want the test is master too (though the bug is already fixed there).  This should go in shortly. Thanks for your work on this! Writing the test to reproduce the issue makes everything *so* much easier.  :)

**Comment by xxhdx1985126** [comment]
@liewegas You're welcome:-) I'm very glad that I can help, and have been looking forward to making more contributions as my understanding of the architecture of ceph increases.:-) 
So, I guess this case passed the QA test finally, right? If so, could you tell which PR fixed the problem? Thanks:-)

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-09-14_12:06:50-rados-wip-kefu-testing-2017-09-14-1846-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-09-15_05:21:49-rados-wip-kefu-testing-2017-09-14-1846-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-09-15_10:57:17-rados-wip-kefu-testing-2017-09-14-1846-distro-basic-mira/

**Pull request merged**
