### PR TITLE
[luminous] Backport recent prometheus exporter changes

### PR DESCRIPTION
**Pull request by b-ranto**
I have cherry-picked a couple of commits that we have already merged upstream to get the prometheus exporter in luminous more on par with what we have in master.

This also resolves https://tracker.ceph.com/issues/23167

### CODE REVIEW

**Comment by b-ranto** [comment]
FYI: I have cherry-picked a couple more comments that got merged in the mean-time.

**Comment by jan--f** [comment]
@b-ranto thx, I was going to propose those commits for backport as well. In light of the recent discussion on metrics stability within one majour release: We should probably amend 5ecb66c to not remove the mon_quorum_count metric or add a commit on top of this set. I'd be happy to provide one...

**Comment by b-ranto** [comment]
@jan--f IIRC, the original agreement was that we will stabilize the mimic prometheus module and get luminous on par with mimic so I don't think that we need to do that at the moment.

**Comment by b-ranto** [comment]
@smithfarm Did you manage to schedule any tests against this branch so that we could merge this?

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-03-27-1535-luminous](https://trello.com/c/0zxXqm9m/281-wip-yuri5-testing-2018-03-27-1535-luminous)

**Comment by yuriw** [comment]
@b-ranto @jan--f @jcsp 

@jdurgin and I suspect this caused this regression https://tracker.ceph.com/issues/23483

Pls tag "needs-qa" after examining

**Comment by yuriw** [comment]
@b-ranto pls rebase

--- pr 20642 --- pulling https://github.com/b-ranto/ceph.git branch wip-mgr-prom-luminous
remote: Counting objects: 84, done.
remote: Total 84 (delta 60), reused 60 (delta 60), pack-reused 24
Unpacking objects: 100% (84/84), done.
From https://github.com/b-ranto/ceph
 * branch            wip-mgr-prom-luminous -> FETCH_HEAD
Auto-merging src/pybind/mgr/prometheus/module.py
CONFLICT (content): Merge conflict in src/pybind/mgr/prometheus/module.py
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by b-ranto** [comment]
@yuriw Done.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-04-05-1940-luminous](https://trello.com/c/5vAerhWC/286-wip-yuri3-testing-2018-04-05-1940-luminous)

**Pull request merged**
