### PR TITLE
osd: remove redundant code

### PR DESCRIPTION
**Pull request by shinobu-x**
Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
retest this please

**Comment by shinobu-x** [comment]
test this please

**Comment by tchaikov** [comment]
retest this please.

**Pull request closed without merging**
