### PR TITLE
nautilus: ceph.spec.in: build on el8

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
tested at https://shaman.ceph.com/builds/ceph/nautilus-el8-kefu1/7ab89e989fbe690a10cb447bf68b9a25fe639cde/default/212216/

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
changelog

- cherry-pick d301137bb16d4e530745172624ed9800a9b4c5ae as well

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
changelog

- rebased against nautilus branch.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-06-17-2053-nautilus](https://trello.com/c/0XYxPi46/938-wip-yuri8-testing-2020-06-17-2053-nautilus)

**Pull request merged**
