### PR TITLE
ceph-volume correctly normalize mount flags

### PR DESCRIPTION
**Pull request by alfredodeza**
Fixes: https://tracker.ceph.com/issues/23080

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by alfredodeza** [comment]
@smithfarm @theanalyst @yuriw once this gets merged (after all functional tests pass) we will start the backport to Luminous for 12.2.4

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm all

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm xenial-filestore-create

**Comment by andrewschoen** [comment]
jenkins test ceph-volume lvm xenial-bluestore-create

**Comment by smithfarm** [comment]
@alfredodeza Cool. Ping us in the backport then?

**Pull request merged**
