### PR TITLE
mgr/dashboard: Stop polling summary on failure

### PR DESCRIPTION
**Pull request by Devp00l**
Fixes: https://tracker.ceph.com/issues/38936
Signed-off-by: Stephan Müller <smueller@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
What happens when the backend comes back? With the current implementation the service never get started automatically again, a reload of the page is necessary.

What about increasing the poll time everytime an error occurs? So the number of error notifications will decrease over time and when the backend comes back again, the refresh period can be restored to the default value => the service will be working again automatically after the first successful response.

**Comment by epuertat** [comment]
I'm with @votdev here. If the back-end becomes unreachable, it won't be polled again, right?. Will the user notice that situation or they'll have a frozen dashboard with the last fetched data?

**Comment by ricardoasmarques** [comment]
What about showing an alert message like this?

Screenshot from 2019-04-01 12-20-56

**Comment by Devp00l** [comment]
@votdev I've implemented it this way but while testing I came to the conclusion that it's not that helpful to only apply this to this case. As some services won't refetch on an error and others do, we should make sure that all requests are handled equally.

The second step would be to silence the notifications if they are repeating them self.

@epuertat  @ricardoasmarques  @votdev What do you think about that idea?

**Comment by epuertat** [comment]
> ... As some services won't refetch on an error and others do, we should make sure that all requests are handled equally.

I fully agree with that, it's something I've been thinking for a while. We should standardize the way front-end and back-end interact with each other, to avoid uneven behaviours.

**Comment by Devp00l** [comment]
I've updated the issue to reflect the discussion ->  https://tracker.ceph.com/issues/38936

**Pull request closed without merging**
