### PR TITLE
common/options: make "blue{fs,store}_allocator" LEVEL_DEV

### PR DESCRIPTION
**Pull request by tchaikov**
See-also: http://tracker.ceph.com/issues/20660
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
fyi, @shangzhong

**Comment by xiexingguo** [comment]
may restrict bluestore_allocator for LEVEL_DEV too

**Comment by tchaikov** [comment]
@xiexingguo updated and repushed.

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/16489 does the bluestore one.. didn't cover bluefs yet

**Pull request merged**
