### PR TITLE
jewel: cephfs: ceph-fuse does not recover after lost connection to MDS

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19677

### CODE REVIEW

**Comment by smithfarm** [comment]
@jcsp I brought in the master version of doc/cephfs/client-config-ref.rst but I'm not sure if all the options mentioned there are relevant for jewel?

**Comment by jcsp** [comment]
I've had a quick scan through it and I didn't notice anything that doesn't make sense for Jewel, so I think it's fine to merge.

**Comment by smithfarm** [comment]
@jcsp This passed a rados run at http://tracker.ceph.com/issues/19538#note-49

It also went through an fs run with the following result: http://tracker.ceph.com/issues/19538#note-57 (I ruled that a "pass" - in my own mind - since the only reproducible failure is in the libcephfs-java workunit)

Please merge or :thumbsup: if you agree this testing result is sufficient.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@jcsp Ping, could you please respond to https://github.com/ceph/ceph/pull/14698#issuecomment-297804817

**Pull request merged**
