### PR TITLE
librados: list pool cursor

### PR DESCRIPTION
**Pull request by yehudasa**
add the ability to retrieve and seek to a specific position in a rados pool listing.

### CODE REVIEW

**Comment by yehudasa** [comment]
@liewegas you suggested that I added serialize/deserialize cursor functions in librados. Not sure if it's really needed; functions to get and set cursor (as a string) that work on current listing position should be enough. However, let me know if you think that need to add serialize from oid + locator.

**Comment by liewegas** [comment]
On Thu, 8 Dec 2016, Yehuda Sadeh wrote:
> @liewegas you suggested that I added serialize/deserialize cursor functions in librados. Not sure
> if it's really needed; functions to get and set cursor (as a string) that work on current listing
> position should be enough. However, let me know if you think that need to add serialize from oid +
> locator.

Yeah,a s long as teh set position takes the ioctx locator key into 
consideration so that it effectively is providing all fields of the 
hobject_t (pool and key from ioctx, name as arg.  snapid from ioctx too i 
guess).

**Comment by yehudasa** [comment]
@liewegas yeah, the cursor is made out of all of these (through hobject_t) and num pgs in pool

**Comment by liewegas** [comment]
So, I went on a cleanup spree in Objecter and librados to remove the current_pg hackery so that we were using a simple hobject_t as a cursor, and ended up removing the entirety of the older list_objects API.

..and in the process realized that there is a *third* version of the object listing, 

    ObjectCursor object_list_begin();
    ObjectCursor object_list_end();

that is already cursor based.  All that is missing is a pair of get/set methods for ObjectCursor (and rados_object_list_cursor for the C API) and we should be good to go.  That means switching rgw to use the new API, but it's cleaner anyway, and will mean we can deprecate the nobjects one....

**Comment by yehudasa** [comment]
closing this one in favor of #13323

**Pull request closed without merging**
