### PR TITLE
infernalis: [ FAILED ] TestLibRBD.SnapRemoveViaLockOwner

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/14199

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
@dachary Is the bot down? it didn't run for this PR

**Comment by dachary** [comment]
@Abhishekvrshny the bot is down. Alfredo posted an annoucement about it (ceph-devel). I don't know when it will be back.

**Comment by dachary** [comment]
@jdurgin this backport look good to merge ? It passed a run of the infernalis rbd suite ( see http://tracker.ceph.com/issues/13750#note-18 for details ). Note that all valgrind tests in these suites fail because of an environmental problem ( http://tracker.ceph.com/issues/14664 ).

**Comment by jdurgin** [comment]
lgtm

**Pull request merged**
