### PR TITLE
cephadm: fix apparmor profiles with spaces in the names

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Fixes: https://tracker.ceph.com/issues/66389

Update the host_facts class kernel_security method to correctly read apparmor profile names that have spaces in them. 

Add test to verify this functionality.

Clean up the formatting and rename the test file.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-06-12_15:11:26-orch:cephadm-wip-adk-testing-2024-06-12-0810-distro-default-smithi/

Failures were

- `in cluster log` stuff
- mds_upgrade_sequence
- staggered upgrade with the agent on
- rados_api_tests cleanup failure
- some failures installing kernel stuff pre-test

**Comment by adk3798** [comment]
jenkins test make check

**Comment by sivehost** [comment]
If on ubuntu 24 and apparmor profile MongoDB is the only profile with space in its name you can just do the following to work around this, especially on the node with the issue, but probably good to apply to all nodes for consistency.

#1 check profiles with spaces: sudo nano /sys/kernel/security/apparmor/profiles , do not edit, just read, do not mind the (unconfined), the space in between it and the profile does not count.

~> sudo systemctl disable apparmor
~>sudo systemctl stop apparmor;sudo systemctl status apparmor
~> sudo mkdir /etc/apparmor.d/disabled/
~> sudo mv /etc/apparmor.d/MongoDB_Compass /etc/apparmor.d/disabled/

Then reboot and check whether the issue is solved. If it is Not, probably wise to reverse the action by:
~> sudo mv  /etc/apparmor.d/disabled/MongoDB_Compass /etc/apparmor.d/

And then the below you do either way, whether solved or not (unless you want to keep apparmor disabled and risk the consequences):
~> sudo systemctl enable apparmor
~> sudo systemctl start apparmor;sudo systemctl status apparmor
Then reboot and check whether everything is still functional.

**Comment by webash** [comment]
Would you expect this fix to be in the latest 19.2.0 package available on Ubuntu 24.04's `noble-updates` universe repo and also in the equivalent container images? Because I'm still experiencing this issue

**Comment by phlogistonjohn** [comment]
I just checked git history. The backport of this apparently did not make into the squid branch in time for v19.2.0. I expect it should be available when the next squid version is released.
```
$ git branch --contains ad50f20e9ff6e09674934ad60c5085a5334e8d66
  squid
$ git tag --contains ad50f20e9ff6e09674934ad60c5085a5334e8d66
$ 
$ git show -q ad50f20e9ff6e09674934ad60c5085a5334e8d66
commit ad50f20e9ff6e09674934ad60c5085a5334e8d66
Author: John Mulligan <jmulligan@redhat.com>
Date:   Mon Jun 10 14:30:31 2024 -0400

    cephadm: update hosts_facts to read apparmor profile names with spaces
    
    Fixes: https://tracker.ceph.com/issues/66389
    
    Update the host_facts class kernel_security method to correctly read
    apparmor profile names that have spaces in them. Update the test to
    verify this functionality.
    
    Original-version-by: Sebastian Marsching <sebastian.marsching-git-2016@aquenos.com>
    Signed-off-by: John Mulligan <jmulligan@redhat.com>
    (cherry picked from commit d40fe10b8a75402d518fb54f58c689331c854778)

```

**Comment by webash** [comment]
Oof, OK. Thanks for checking. Is there a way to be able to utilise this fix easily anyway? Since its 'just' a python script?

**Comment by phlogistonjohn** [comment]
@webash cephadm is built as a python zipapp that is then included as part of the ceph container image. the cephadm binary that the mgr uses to make changes on remote systems is copied from the container image onto the hosts.

In other words, yes, but you're going to have to get into the business of building ceph yourself.

**Comment by webash** [comment]
The complexity and layers of modern computing is something else! Thanks @phlogistonjohn for taking the time out here. Definitely beyond my current skill/time. Down to `reef` (and maybe also 22.04) I go!

**Pull request merged**
