### PR TITLE
doc/mgr/orchestrator: Add Architecture Image

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
jenkins render docs

**Comment by sebastian-philipp** [comment]
jenkins render docs

**Comment by sebastian-philipp** [comment]
jenkins render docs

**Comment by tchaikov** [comment]
thanks for visualizing the sandwich!

the methods docstring does not render quite right, see http://docs.ceph.com/ceph-prs/26321/mgr/orchestrator_modules/#host-management for an example. so i tweaked it a little bit at #26331.

**Comment by sebastian-philipp** [comment]
replaced by #26331

**Pull request closed without merging**
