### PR TITLE
mgr/cephadm: use host shortname for osd memory autotuning

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/55841

Signed-off-by: Adam King <adking@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
Thoughts? Is it worth trying to get the real name? Should we just always assume the shortname is correct?

**Comment by rkachach** [comment]
> Thoughts? Is it worth trying to get the real name? Should we just always assume the shortname is correct?

Not sure what are we using internally in cephadm but I'd go with FQDN if possible. This way, if at some point we start using names instead of ips we already have already the FQDNs. For places where we interact with crush we would need to translate fqdn to short names (until crush starts using fqdns also...but not sure if this will happen in the future or not).

I think right now there're trackers/issues related to this problem:
```
https://tracker.ceph.com/issues/50776
https://tracker.ceph.com/issues/47127
https://tracker.ceph.com/issues/48260
```
I don't know if you fix address them all or not but it would be good to try to fix the root cause so we fix all of these issues at once. WDYT?

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-06-03_05:20:20-orch:cephadm-wip-adk-testing-2022-06-02-2217-distro-default-smithi/

1 odd failure deploying an nfs cluster. Did 10 reruns of the test_nfs test that failed and all passed so I think we're okay

https://pulpito.ceph.com/adking-2022-06-03_12:57:33-orch:cephadm-wip-adk-testing-2022-06-02-2217-distro-default-smithi
https://pulpito.ceph.com/adking-2022-06-03_12:56:58-orch:cephadm-wip-adk-testing-2022-06-02-2217-distro-default-smithi

**Comment by mgfritch** [comment]
> Thoughts? Is it worth trying to get the real name? Should we just always assume the shortname is correct?

I think using the shortname would be correct.

see also: https://docs.ceph.com/en/octopus/cephadm/concepts/#fully-qualified-domain-names-vs-bare-host-names

**Comment by adk3798** [comment]
jenkins test make check

**Review by guits — APPROVED** [review]

**Review by rkachach — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test dashboard cephadm

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2022-06-07_15:52:19-orch:cephadm-wip-adk-testing-2022-06-07-0930-distro-default-smithi/

4 failures due to infra/teuthology issues

- `Command failed on smithi125 with status 1: 'sudo fuser -v /var/lib/dpkg/lock-frontend'`
- `Failed to connect to the host via ssh: ssh: connect to host smithi125.front.sepia.ceph.com port 22: No route to host`
- `Stale jobs detected, aborting.`
- `Error reimaging machines: 'ssh_keyscan smithi125.front.sepia.ceph.com' reached maximum tries (5) after waiting for 5 seconds`

1 failure with agent on test_nfs test. Did 5 rerun of the test, 4 passed and the other failued with another teuthology/infra issue 

- `Failed to update apt cache: unknown reason`

I think there might be a legitimate sporadic failure with that test_nfs test, but I don't think it's caused by any PRs in this run

**Pull request merged**
