### PR TITLE
SCA fixes

### PR DESCRIPTION
**Pull request by dalgaaf**
Fixes for:
- fix potential null-deref's
- prefer ++operator for non-primitive iter
- use static_cast instead of c-style cast
- fix sprintf specifier
- add missing asserts to check return values
- reduce scope of variables
- init vars in constructor
- don't assign value to function parameters (if the assignment has no effect outside function)

### CODE REVIEW

**Comment by dalgaaf** [comment]
Changed the assert calls and rebased.

**Comment by tchaikov** [comment]
sorry, i have not finished the review.

**Comment by tchaikov** [comment]
looks good in general, except for the return code of radosgw. and not very sure about the cppcheck issue, as i am also seeing some other places are assigning value to the function parameter. and i think it's okay.

**Comment by dalgaaf** [comment]
changed error code in rgw_main.cc to EIO

**Comment by dalgaaf** [comment]
the cherry-pick makes sense, but may also  4e9ca71

**Comment by tchaikov** [comment]
@dalgaaf Danny, sorry for the delay, i just wanted to have more eyes on the fix. could you rebase the change ? and i will merge it. thanks.

**Comment by dalgaaf** [comment]
rebased on master as requested

**Pull request merged**
