### PR TITLE
reef: use raw_cluster_cmd instead of run_ceph_cmd

### PR DESCRIPTION
**Pull request by vshankar**
Due to https://github.com/ceph/ceph/pull/50569 not being backported

@rishabh-d-dave FYI

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
Backport is under testing - https://github.com/ceph/ceph/pull/50569/commits/f8f2154e54e202996b24904162da6022081e9d93

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by vshankar** [comment]
> Backport is under testing - [2d6f55b#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58](https://github.com/ceph/ceph/commit/2d6f55bd513998f49428d7ef7a1d3219321a8c94#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58)

Could you please link the backport PR here @rishabh-d-dave ?

Also, could you check https://github.com/ceph/ceph/pull/52924 please?

**Comment by rishabh-d-dave** [comment]
> > Backport is under testing - [2d6f55b#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58](https://github.com/ceph/ceph/commit/2d6f55bd513998f49428d7ef7a1d3219321a8c94#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58)
> 
> Could you please link the backport PR here @rishabh-d-dave ?
> 

The commit should've automatically link the backport PR here. Anyways, here's the link #54945. If this backport had been we wouldn't have hit this issue.

**Comment by vshankar** [comment]
> > > Backport is under testing - [2d6f55b#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58](https://github.com/ceph/ceph/commit/2d6f55bd513998f49428d7ef7a1d3219321a8c94#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58)
> > 
> > 
> > Could you please link the backport PR here @rishabh-d-dave ?
> 
> The commit should've automatically link the backport PR here. Anyways, here's the link #54945. If this backport had been we wouldn't have hit this issue.

It was just the commit diff. Anyway, so I found that its been included in tests here - https://trello.com/c/EFc26rW0/1961-wip-yuri6-testing-2024-02-16-1141-reef

Given the nature of changes, would you mind reviewing that run? I'll tag you on trello (just fyi - we might need a rebase and rerun once https://trello.com/c/Bsx3NLo9/1962-wip-vshankar-testing1-reef-2024-02-19-2138 is merged).

**Comment by rishabh-d-dave** [comment]
> > > > Backport is under testing - [2d6f55b#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58](https://github.com/ceph/ceph/commit/2d6f55bd513998f49428d7ef7a1d3219321a8c94#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58)
> > > 
> > > 
> > > Could you please link the backport PR here @rishabh-d-dave ?
> > 
> > 
> > The commit should've automatically link the backport PR here. Anyways, here's the link #54945. If this backport had been we wouldn't have hit this issue.
> 
> It was just the commit diff. Anyway, so I found that its been included in tests here - https://trello.com/c/EFc26rW0/1961-wip-yuri6-testing-2024-02-16-1141-reef
> 
> Given the nature of changes, would you mind reviewing that run? 

Sure, sure. Even if you want me to test that backport myself, please let me know. I originally was going for it but then we decided that it's better to ask Yuri to do it.

I see the testing branch for it is [being built](https://trello.com/c/EFc26rW0/1961-wip-yuri6-testing-2024-02-16-1141-reef#comment-65cfc20c8d25fe5fae4f18e3), should I wait for new run or [review this one](https://trello.com/c/EFc26rW0/1961-wip-yuri6-testing-2024-02-16-1141-reef#comment-65d3b892e17757b68d60d7b9)?

> I'll tag you on trello (just fyi - we might need a rebase and rerun once https://trello.com/c/Bsx3NLo9/1962-wip-vshankar-testing1-reef-2024-02-19-2138 is merged).

Okay, I'll keep that in mind.

**Comment by vshankar** [comment]
> > > > > Backport is under testing - [2d6f55b#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58](https://github.com/ceph/ceph/commit/2d6f55bd513998f49428d7ef7a1d3219321a8c94#diff-1c6c246ba42f343603d7174198dd1fb9c2654b6c883594d1a0891096b7a35875R58)
> > > > 
> > > > 
> > > > Could you please link the backport PR here @rishabh-d-dave ?
> > > 
> > > 
> > > The commit should've automatically link the backport PR here. Anyways, here's the link #54945. If this backport had been we wouldn't have hit this issue.
> > 
> > 
> > It was just the commit diff. Anyway, so I found that its been included in tests here - https://trello.com/c/EFc26rW0/1961-wip-yuri6-testing-2024-02-16-1141-reef
> > Given the nature of changes, would you mind reviewing that run?
> 
> Sure, sure. Even if you want me to test that backport myself, please let me know. I originally was going for it but then we decided that it's better to ask Yuri to do it.
> 
> I see the testing branch for it is [being built](https://trello.com/c/EFc26rW0/1961-wip-yuri6-testing-2024-02-16-1141-reef#comment-65cfc20c8d25fe5fae4f18e3), should I wait for new run or [review this one](https://trello.com/c/EFc26rW0/1961-wip-yuri6-testing-2024-02-16-1141-reef#comment-65d3b892e17757b68d60d7b9)?
> 
> > I'll tag you on trello (just fyi - we might need a rebase and rerun once https://trello.com/c/Bsx3NLo9/1962-wip-vshankar-testing1-reef-2024-02-19-2138 is merged).
> 
> Okay, I'll keep that in mind.

Yeh, I left a note on the trello board - we probably need a rebase and rerun once the above is merged.

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Reef#5th-March-2024

**Comment by vshankar** [comment]
Reviewed-by: Venky Shankar <vshankar@redhat.com>

**Pull request merged**
