### PR TITLE
nautilus: mds: output lock state in format dump

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/39670

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
The make check failure was an instance of https://tracker.ceph.com/issues/39995

**Comment by tchaikov** [comment]
retest this please.

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-06-17-2042-nautilus](https://trello.com/c/4seSG4a2/646-wip-yuri-testing-2019-06-17-2042-nautilus)

**Pull request merged**
