### PR TITLE
doc: 16.2.5 Release Notes

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Review by liewegas — APPROVED** [review]

**Comment by idryomov** [comment]
Added a msgr2 notable change.

**Comment by djgalloway** [comment]
Ughhhh sorry I don't know how to get that file out of this PR

**Comment by idryomov** [comment]
@djgalloway I'll do it.

**Comment by djgalloway** [comment]
> @djgalloway I'll do it.

I figured it out.  Sorry.  Please re-add your Notable Change.

**Comment by idryomov** [comment]
There was some mild confusion caused by intended target branch (master vs pacific).  All fixed up now in coordination with David.

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
@neha-ojha Re: removing the mgr/autoscaler note, is https://github.com/ceph/ceph/pull/39833 the follow on fix which this functionality depends on?  Since it hasn't seen any activity for almost two months, should we drop the note from PendingReleaseNotes to avoid it being picked up for the next release again?

**Comment by neha-ojha** [comment]
> @neha-ojha Re: removing the mgr/autoscaler note, is #39833 the follow on fix which this functionality depends on? Since it hasn't seen any activity for almost two months, should we drop the note from PendingReleaseNotes to avoid it being picked up for the next release again?

I hadn't realized that the old note made it back until https://github.com/ceph/ceph/pull/41005#pullrequestreview-701227510. The autoscaler logic is being reworked and I don't think the previous details are relevant, I will create a PR to remove them from PendingReleaseNotes again.

**Pull request merged**
