### PR TITLE
pybind/rbd: fix mirror_image_get_status

### PR DESCRIPTION
**Pull request by Dorthu**
When retrieving the status of a mirrored image from the Python rbd
library, a TypeError is raised.

### To Reproduce:

Set up two Ceph clusters for block storage, and configure image
mirroring between their pools.  Create a least one image with mirroring
enabled, then run the following script on either cluster (once the image
exists everywhere):

```python
import rados, rbd

CONF_PATH = "YOUR-CONF-PATH"
POOL_NAME = "YOUR-POOL-NAME"
IMAGE_LABEL = "YOUR-IMAGE-LABEL"

with rados.Rados(conffile=CONF_PATH) as cluster:
  with cluster.open_ioctx(POOL_NAME) as ioctx:
    with rbd.Image(ioctx, IMAGE_LABEL) as image:
      image.mirror_image_get_status()
```

This will result in the following stack trace:

```
Traceback (most recent call last):
  File "repo-bug.py", line 10, in <module>
    image.mirror_image_get_status()
  File "rbd.pyx", line 3363, in rbd.requires_not_closed.wrapper
  File "rbd.pyx", line 5209, in rbd.Image.mirror_image_get_status
TypeError: list indices must be integers or slices, not str
```

Fixes: https://tracker.ceph.com/issues/51867

Signed-off-by: Will Smith <wsmith@linode.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Comment by idryomov** [comment]
Looks good to me!  I have filed https://tracker.ceph.com/issues/51867 to track backports to octopus and pacific releases, could you please add `Fixes: https://tracker.ceph.com/issues/51867` right before the Signed-off-by line in the commit message?

**Comment by Dorthu** [comment]
Thank you!  Commit message amended to reference that issue

**Comment by idryomov** [comment]
Added a fix for a related issue described in the tracker ticket.

**Review by trociny — APPROVED** [review]

**Review by trociny — APPROVED** [review]
LGTM

**Review by idryomov — APPROVED** [review]

**Pull request merged**
