### PR TITLE
mimic: multisite: bucket full sync does not handle delete markers

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/38078

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-02-05-1730-mimic](https://trello.com/c/3UT78K8S/531-wip-yuri5-testing-2019-02-05-1730-mimic)

**Comment by yuriw** [comment]
@pdvian @cbodley add tags when ready

**Comment by smithfarm** [comment]
@cbodley @yuriw Did this cause tests to fail? And, if so, which ones?

**Comment by cbodley** [comment]
this failed its own `test_suspended_delete_marker_full_sync`. there are some more related fixes in [wip-yuri6-testing](https://github.com/ceph/ceph/pulls?q=is%3Aopen+is%3Apr+label%3Awip-yuri6-testing), so i'd like to try this one again after those merge

**Comment by smithfarm** [comment]
@cbodley @yuriw Any update on the `wip-yuri6-testing` run ?

**Comment by smithfarm** [comment]
@cbodley It looks to me like those PRs you referred to have all been merged, so I'm returning this into the pool to mimic PRs to be tested.

**Comment by yuriw** [comment]
[wip-yuri2-testing-2019-05-02-2259-mimic](https://trello.com/c/ZIBIbboi/605-wip-yuri2-testing-2019-05-02-2259-mimic)

**Pull request merged**
