### PR TITLE
mds: add dump inode command

### PR DESCRIPTION
**Pull request by taodd**
dump inode with an specific inode number
this is useful when we only known the inode number.

Signed-off-by: dongdong tao <tdd21151186@gmail.com>

### CODE REVIEW

**Comment by taodd** [comment]
ceph daemon mds.a dump inode 1099511627777
{
    "path": "/a/aa",
    "ino": 1099511627777,
    "rdev": 0,
    "ctime": "2018-06-15 13:19:39.397133",
    "btime": "2018-06-15 13:19:34.077105",
    "mode": 16877,

**Comment by batrick** [comment]
Adding this to the broader testing. We can test your QA test separately.

**Comment by taodd** [comment]
@batrick test case added, please take a look, not sure if it's correct. 
 I don't know how to test these qa test cases ?

**Comment by batrick** [comment]
@taodd I just realized after merging it that this doesn't accept hexadecimal inode numbers. Dongdong, can you also add that with a test-case, please?

**Comment by taodd** [comment]
yeah, I was thinking about whether we need to support hexadecimal, 
if we support, what would be the command look like ? do you have any preference ?

**Comment by batrick** [comment]
Same command. It should just parse integers as in C, i.e. try to parse as hex (`0xXXXX...`), then try decimal (`dddd...`). Hex already does not work with your command so adding parsing for hex integers doesn't break anything.

**Comment by taodd** [comment]
Thank you.
I understand, currently, the argument is captured as a int64 ,  I need to make it as a string.

**Comment by smithfarm** [comment]
@batrick This feature was earmarked for backport to luminous, but the backport is apparently non-trivial. Is this feature really needed in luminous at this stage of its lifecycle?

**Comment by batrick** [comment]
let's skip it for luminous

**Pull request merged**
