### PR TITLE
squid: mgr/dashboard: fix bucket get for s3 account owned bucket 

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/68686

---

backport of https://github.com/ceph/ceph/pull/60399
parent tracker: https://tracker.ceph.com/issues/68622

verified manually in squid

https://github.com/user-attachments/assets/165b86fc-cad0-4439-b862-3ca201e42028

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by cloudbehl** [comment]
jenkins test api
jenkins test make check

**Review by afreen23 — APPROVED** [review]

**Comment by afreen23** [comment]
```
ERROR: /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/dashboard/controllers/rgw.py Imports are incorrectly sorted and/or formatted.
```

**Comment by afreen23** [comment]
@nizamial09 can we fix these and take it ? Thanks

**Comment by nizamial09** [comment]
> @nizamial09 can we fix these and take it ? Thanks

sorry for the delay, updated it now.

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Pull request merged**
