### PR TITLE
DNM: infernalis: mds: fix stray purging in 'stripe_count > 1' case

### PR DESCRIPTION
**Pull request by ukernel**
http://tracker.ceph.com/issues/15057

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary I went ahead and staged the infernalis backport issue http://tracker.ceph.com/issues/15057

**Comment by dachary** [comment]
@ukernel could you please **git cherry-pick -x 99ec183973e0f4686673d93df02e5381543be51f** instead so that it has a reference to the commit that was merged in master ?

**Comment by ukernel** [comment]
Sorry for the delay.

Correspond code was modified a lot and was moved to different file. But I can add "cherry picked from ..." to the commit message

**Comment by dachary** [comment]
infernalis has been EOL for a few months now, there does not seem to be a need for another release, even for upgrade purposes

**Pull request closed without merging**
