### PR TITLE
octopus: rgw: resolve empty ordered bucket listing results w/ CLS filtering *and* bucket index list produces incorrect result when non-ascii entries

### PR DESCRIPTION
**Pull request by dvanders**
backport tracker: https://tracker.ceph.com/issues/52076

---

backport of https://github.com/ceph/ceph/pull/42125 and https://github.com/ceph/ceph/pull/42404 and https://github.com/ceph/ceph/pull/44562
parent tracker: https://tracker.ceph.com/issues/51462 and https://tracker.ceph.com/issues/51429

### CODE REVIEW

**Comment by dvanders** [comment]
This includes the single commit from https://github.com/ceph/ceph/pull/44858.

**Comment by cbodley** [comment]
https://pulpito.ceph.com/yuriw-2022-02-24_22:51:58-rgw-wip-yuri10-testing-2022-02-24-1329-octopus-distro-default-smithi/ shows 3 jobs failing in `ceph_test_cls_rgw`:
```
[ RUN      ] cls_rgw.bi_list
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] cls_rgw.bi_list (83 ms)
```
the exception is thrown in the cls_rgw_client code (not the cls_rgw part running in the osd). in the past, i've seen `bad_alloc` errors from logic errors in decode, like when it tries to decode a string, finds a really big length prefix, and tries to allocate that much memory. but i don't see any obvious mistakes in `rgw_cls_list_ret` here

**Comment by dvanders** [comment]
@cbodley do we need this? https://github.com/ceph/ceph/commit/1bf058199a13783e227c0e87ea6f3244f3560cfd

**Comment by dvanders** [comment]
jenkins retest this please

**Comment by cbodley** [comment]
thanks @dvanders, worth a shot!

i tried reproducing this in an old focal vm, but the test passes consistently there. so i guess it's somehow specific to centos?

**Comment by dvanders** [comment]
jenkins test api

**Comment by GillesMocellin** [comment]
Argh ! v15.2.16 is just released, and this PR is not in ;-(

**Comment by cbodley** [comment]
> Argh ! v15.2.16 is just released, and this PR is not in ;-(

@GillesMocellin i'm afraid that Ceph no longer have much of a backport team, and rgw has not been getting timely backports as a result. if you're interested in getting involved, you can find some resources in https://tracker.ceph.com/projects/ceph-releases/wiki and https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst

(and thanks to @dvanders for working on this one)

**Comment by dvanders** [comment]
@ivancich added the missing commit from https://github.com/ceph/ceph/pull/42836 here now too.
The logging changes don't apply cleanly so I'll leave them out unless you insist.

**Comment by cbodley** [comment]
@yuriw sorry, i had requested a rerun of this PR but a new commit was added since then. this applies to https://github.com/ceph/ceph/pull/45087 also

**Comment by ivancich** [comment]
> @ivancich I have added the missing commit from #42836 here now too. The logging changes don't apply cleanly so I'll leave them out unless you insist.

I agree, the logging changes are not that important. Thank you, @dvanders !

**Comment by dvanders** [comment]
jenkins test api

**Pull request merged**
