### PR TITLE
client: fix wrong lock logic of ll_read_block() method

### PR DESCRIPTION
**Pull request by xiexingguo**
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by jcsp** [comment]
This looks correct, but perhaps when cleaning this up you could simplify it further by replacing the C_SafeCond with a C_SaferCond, so that the done/cond vars are no longer needed?  Currently we use a mixture, but when doing cleanup it is nice to replace things with SaferCond where possible

**Comment by xiexingguo** [comment]
Done and label this one as "needs-qa".
Thanks for the review!

**Comment by jcsp** [comment]
Reviewed-by

**Comment by jcsp** [comment]
http://pulpito.ceph.com/jspray-2016-06-14_01:19:46-fs-wip-jcsp-testing-20160610-distro-basic-mira/

**Pull request merged**
