### PR TITLE
osd: add override in headers files

### PR DESCRIPTION
**Pull request by Liuchang0812**
Signed-off-by: liuchang0812 <liuchang0812@gmail.com>

:rofl:  I missed this branch.

### CODE REVIEW

**Comment by tchaikov** [comment]
please rebase, and it does not compile, see https://jenkins.ceph.com/job/ceph-pull-requests/20176/consoleFull#4163024962a811ea2-3e7b-466b-84b4-d13df7e35809

**Comment by Liuchang0812** [comment]
thanks, I'm working on this

2017-03-15 12:25 GMT+08:00 Kefu Chai <notifications@github.com>:

**Comment by Liuchang0812** [comment]
changlog:

1. rebase forward to master
2. repushed


Let's wait for test result.

**Comment by Liuchang0812** [comment]
jenkins test this please

**Comment by liewegas** [comment]
rebase please?

**Comment by Liuchang0812** [comment]
ok


发自我的 iPhone

**Comment by Liuchang0812** [comment]
it has been rebased.

**Pull request merged**
