### PR TITLE
To notify remote watcher to release rbd cache when rbd snap rollback complete.

### PR DESCRIPTION
**Pull request by flywayway**
I create an image and use it by target. RBD cache mode is writeback and target cache is off。
1. I store a file A in initiate and use sync command to flush file system cache。
2. I create a rbd snap snap1 for this image.
3. I add a file B in initiate and use sync command to flush file system cache。
4. I create a rbd snap snap2 for this image.
5. Then I rollback this image to snap1.
6. Then I redo recovery and login and mount this rbd device in initiate . Then I find this image not rollback to snap1. The data is belong to snap2.
This bug will not appear when RBD cache is off.
The remote watcher is not release RBD cache when rbd snap rollback complete.
To notify remote watcher to release rbd cache when rbd snap rollback complete.

### CODE REVIEW

**Comment by flywayway** [comment]
We found the data is not change after rbd snap rollback, because the client is not release RBD cache when rbd snap rollback complete in another client.

**Comment by jdurgin** [comment]
The rbd cache isn't intended to be coherent across multiple clients - it's expected that if you use rbd from multiple clients, you don't use caching, or you use something that can manage the caching correctly on top of or instead of rbd, like ocfs2 on rbd, or cephfs instead of rbd.

Invalidation after rollback isn't sufficient to get an updated picture of an image - rollback is not atomic, so partial state is exposed throughout the process, and if another client is writing to the image your second cache will definitely not be up to date.

There are cases where you could have enough control of the environment to know when you need to invalidate caches - for these it seems like an admin socket command that triggered cache invalidation would be useful (http://tracker.ceph.com/issues/2468).

**Comment by flywayway** [comment]
I use one client to read and write data, and via the 'rbd snap rollback' commands to do rollback, does that mean I use multiple clients?

**Comment by jdurgin** [comment]
Kind of, but I did misunderstand your test scenario. I think I see what you mean now. It sounds like:

1) process A has an image without the exclusive-lock feature open, does some i/o
2) 'rbd snap create'
3) process A does some more i/o
4) 'rbd snap rollback' - this performs the rollback from the cli tool since the exclusive-lock feature isn't used
5) process A still has old data in its cache

In this case, 'rbd snap rollback' is effectively acting as a 2nd client, by doing the rollback itself.

If you use the exclusive-lock feature, 'rbd snap rollback' will ask process A to do the rollback, and that process' rbd cache will be invalidated as part of that. This may be best for your use case.

In general, rollback while an image is in use is tricky to get right. It often depends on other layers clearing caches too, and the image being unused while rollback is happening, so I don't think we should try to invalidate the cache like for clients not doing the rollback within librbd.

Another layer needs to ensure that other caches are dropped, and the device isn't in use, so that layer could use an admin socket command to invalidate the rbd cache as well. In general it'd be simpler to detach/close and reattach/open the image rather than making sure no i/o happens and clearing all levels of caches (for krbd for example there's no way to clear just the cache for a particular device, you'd need to drop the whole page cache).

**Comment by flywayway** [comment]
Thank you for your reply. Now I use the  exclusive-lock feature, but 'rbd snap rollback' don't ask process A to do the rollback, just return 'rollback failed'.

**Comment by jdurgin** [comment]
What error does it give?

**Comment by flywayway** [comment]
root@vm02:~# rbd snap rollback --image foo --snap foo_s01
Rolling back to snapshot: 0% complete...failed.
rbd: rollback failed: (30) Read-only file system

This function is not implemented at present?
Code is as follows:
  int snap_rollback(ImageCtx *ictx, const char *snap_name,
		    ProgressContext& prog_ctx)
  {
          if (ictx->image_watcher->is_lock_supported() &&
	  !ictx->image_watcher->is_lock_owner()) {
	return -EROFS;
          }
  }

**Comment by flywayway** [comment]
@jdurgin When we use the exclusive-lock feature, should we ask the locker owner to do rollback? Can I modify the code and to add this process?

**Comment by dillaman** [comment]
@flywayway This was by design as we couldn't think of a valid use case where you would have a VM holding the exclusive lock while using 'rbd snap rollback' on the image.

**Comment by flywayway** [comment]
@dillaman Should we add the process for this use case now?

**Comment by dillaman** [comment]
@flywayway Still trying to understand your use-case.  You have tgtd using librbd as the backing store?  You will only have a single initiator connected to this target and you will ensure that *all* IO is stopped while 'rbd snap rollback' is executing?

**Comment by flywayway** [comment]
@dillaman Yes, tgtd using librbd as the backing store, I only have a single initiator connected to this target, and all IO is stopped while 'rbd snap rollback' is executing.

**Comment by jdurgin** [comment]
@flywayway how do you ensure that the iscsi initiator, and whatever is using it, has no data in caches?

**Comment by flywayway** [comment]
@jdurgin @dillaman 
When I use the exclusive-lock feature, my test case like this:
1)I have tgtd using librbd as the backing store, and only have a single initiator connected to this target
2)In the iscsi initiator I 'mkfs.ext /dev/sdx' to the discovered device and mount it before do i/o
3)'rbd snap create'
4)The iscsi initiator does some more i/o
5)Then I umount the device and logout to the target  in the iscsi initiator before 'rbd snap rollback'
6)  rbd: rollback failed
Is this for design than I can't  'rbd snap rollback' while another client holding the exclusive lock ?
In this case，how can I rollback?

If we don't use exclusive-lock feature we can do 'rbd snap rollback' successfully , but tgtd still has old data in its rbd cache. In this case, how can I to invalidation rbd cache? Can I use an admin socket command that triggered cache invalidation and how to use this command? Thank you very much!

**Comment by jdurgin** [comment]
@flywayway what I'm unsure of in your use case is why you want to rollback without unsharing the rbd image from tgt, rolling back, then resharing it with tgt again? You're already doing several steps on the initiator side to reset things, why not on the target side too?

There's no admin socket command for invalidating the rbd cache right now, but it's easy to add.

**Comment by flywayway** [comment]
Although it can be performed by the upper layer to clean cache after rollback, the rbd at least should ensure that the correct operation of it's own layer. So in rbd layer we can notify other watchers to invalidation cache when one watcher operate rollback completely to ensure the cache is clean in rbd.

**Comment by jdurgin** [comment]
I don't think it's worth handling this directly in librbd's rollback. It's too easy to get wrong, and a higher-level is necessary to make sure the device isn't in use and higher-level caches are flushed. 

Adding an admin socket command to do the cache flush seems like a better path forward.

**Comment by trociny** [comment]
Hi, I have created a PR that adds admin socket commands to invalidate or flush the cache:
https://github.com/ceph/ceph/pull/6453

**Pull request closed without merging**
