### PR TITLE
luminous: rgw: reject encrypted object COPY before supported

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23346

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri2-testing-2018-03-19-1611-luminous](https://trello.com/c/kE38rmT3/276-wip-yuri2-testing-2018-03-19-1611-luminous)

**Comment by yuriw** [comment]
test this please

**Comment by bangmingcheng** [comment]
Do we have any plan to  implemente the encrypted object copy function? Any progress or pipeline now?

**Comment by bangmingcheng** [comment]
> test this please

Do we have any plan to implemente the encrypted object copy function? Any progress or pipeline now? Thank you

**Comment by cbodley** [comment]
hi @bangmingcheng, thanks for the reminder. there's a tracker issue for this feature at http://tracker.ceph.com/issues/23264

**Pull request merged**
