### PR TITLE
cmake: set $PATH for tests using jsonnet tools

### PR DESCRIPTION
**Pull request by tchaikov**
otherwise there is chance that `lint-jsonnet.sh` cannot find
`jsonnetfmt`, when it is called by the `run-tox-jsonnet-check` and
`run-tox-jsonnet-lint`.

this change addresses a regression introduced by
8ff1e6b39976ea5e857b6575934d1a42302c6a0f

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by MrFreezeex — APPROVED** [review]
Thanks, sorry I thought this was implicit... Also we should be able to get rid in the future of the new version requirements of jsonnet (and thus the need to build it) with this https://github.com/ceph/ceph/pull/47147 as well.

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
> Thanks, sorry I thought this was implicit... Also we should be able to get rid in the future of the new version requirements of jsonnet (and thus the need to build it) with this #47147 as well.

thanks for the info. that'd be even better!

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Pull request merged**
