### PR TITLE
mds: let can_read=XCL when filelock's state is LOCK_EXCL or LOCK_EXCL…

### PR DESCRIPTION
**Pull request by candychencan**
…_XSYN

https://tracker.ceph.com/issues/48148
Signed-off-by: chencan <chen.can2@zte.com.cn>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by candychencan** [comment]
retest please

**Comment by candychencan** [comment]
jenkins retest this please

**Comment by candychencan** [comment]
jenkins retest this please

**Comment by ukernel** [comment]
```
SimpleLock {
  ...
  bool can_read(client_t client) const {
    return get_sm()->states[state].can_read == ANY ||
      (get_sm()->states[state].can_read == AUTH && parent->is_auth()) ||
      (get_sm()->states[state].can_read == XCL && client >= 0 && get_xlock_by_client() == client);
  }
  ...
}
```

filelock can not be xlocked in either states.

**Pull request closed without merging**
