### PR TITLE
osd/ReplicatedPG: minor fixes and cleanups

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Move the osd relevant changes into this pr. 
Really simple changes, though.

**Comment by xiexingguo** [comment]
@liewegas  And this one:-)

**Comment by liewegas** [comment]
Looks good, except I'm not sure what the motivation for the max_name_len patch is.  I'm not sure it's a good idea not to have a well-defined limit.  Backends may vary between OSD, so i'm not sure when we would want to have behavior be ambiguous...

**Comment by xiexingguo** [comment]
Thanks for the explanation. Dropped that change.

**Pull request merged**
