### PR TITLE
Wip dma latency

### PR DESCRIPTION
**Pull request by yuyuyu101**
Lots of sleep/wakeup threads are existed in ceph, but current cpu always try
    to use powersave or balance model to run application. If we use SSD, these
    sleep/wakeup latency is expensive and we should reduce them via close powersave
    for ceph process.
    
    A bit more fine-grained control of the power management features, is to use the
    Power Management Quality of Service interface (PM QOS). The file
    /dev/cpu_dma_latency is the interface which when opened registers a
    quality-of-service request for latency with the operating system. So we
    open /dev/cpu_dma_latency, write 0 means the lowest response time and then keep
    the file descriptor open while low-latency operation is desired.
    
    This option can greatly decrease op latency for ssd backend if your cpu idle
    driver is "intel_idle" or higher. If you already use "acpi_idle" or lower
    driver, this option can't help more.
    
    You can get your cpu idle driver by
    "cat /sys/devices/system/cpu/cpuidle/current_driver)"
    
    Also you can append boot option to grub.cfg like
    "intel_idle.max_cstate=0 processor.max_cstate=0 idle=poll"

### CODE REVIEW

**Comment by yuyuyu101** [comment]
I can improve 1 iodepth for ssd osd from 900 iops to 2000iops via this

**Comment by XinzeChi** [comment]
@yuyuyu101, This patch is similar to "service cpuspeed stop"?

**Comment by branch-predictor** [comment]
Even if this option is disabled by default, enabling it will have system-wide effects which some might find undesireable. I don't think we should mess with whatever is outside of our scope - and setting DMA  latency is definitely out of our scope.

**Comment by markhpc** [comment]
Unless I am missing something, this can just as easily be tweaked via init scripts or other mechanisms right?  I'm also very wary that we shouldn't be adding configuration options into Ceph that are OS dependent.

**Comment by xiaoxichen** [comment]
Usually some customer will disable the cstate at all...
I agree this is a system wide tuning, we would be better to put this as known best practice than manipulate it in the ceph code.

Also the test data is not solid enough, we need more test to make sure it will not hurt other part(Although it shouldn't other than using more power).

**Pull request closed without merging**
