### PR TITLE
hammer: osd: use GMT time for the object name of hitsets

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/13288

### CODE REVIEW

**Comment by tchaikov** [comment]
will add a workaround to address the crc error, instead of disabling the upgrade tests of osd->mon

**Comment by tchaikov** [comment]
changelog 

- rebased against master
- add the workaround to encode pg_pool_t if GMT feature bit does not exist in the `inc.encode_features`.

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-03-04_08:56:56-upgrade-wip-12848-hammer---basic-multi/

**Comment by dachary** [comment]
great ! it will be in the next integration branch :-)

**Comment by tchaikov** [comment]
that would be great! thanks.

**Comment by tchaikov** [comment]
changelog

- remove corpus change. it was added by mistake.
```
--- a/ceph-object-corpus
+++ b/ceph-object-corpus
@@ -1 +1 @@
-Subproject commit 47fbf8c6ae1fb4fca171ac86e98821a67fd32031
+Subproject commit ef8a3bd8f5d358bdb40a8d61abd25b24b033ed5b
```

**Comment by dachary** [comment]
Ah, thanks for catching that. The integration tests are stalled (test infrastructure problems), no harm done :-)

**Comment by dachary** [comment]
It passed the hammer upgrade suite ( http://tracker.ceph.com/issues/14692#note-52 ) and the rados suite http://tracker.ceph.com/issues/14692#note-51).

**Pull request merged**
