### PR TITLE
[DNM] jewel: mon: force_create_pg could leave pg stuck in creating state

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/19182

### CODE REVIEW

**Comment by shinobu-x** [comment]
reest please

**Comment by shinobu-x** [comment]
jenkins test this please

**Comment by shinobu-x** [comment]
retest this please

**Comment by shinobu-x** [comment]
retest this please

**Comment by shinobu-x** [comment]
retest this please

**Comment by smithfarm** [comment]
@jdurgin This is a backport of #12539 . . . at first glance, it appears to be backporting too much.

**Comment by jdurgin** [comment]
@smithfarm I agree, this is backporting too much. We really just want the minimal way to fix this issue, even if it's not a clean cherry-pick and needs some extra editing for jewel.

**Pull request closed without merging**
