### PR TITLE
osd,mon: increase mon_max_pg_per_osd to 250

### PR DESCRIPTION
**Pull request by neha-ojha**
Fixes: https://tracker.ceph.com/issues/25112
Signed-off-by: Neha Ojha <nojha@redhat.com>

### CODE REVIEW

**Comment by neha-ojha** [comment]
updated.

**Comment by smithfarm** [comment]
Can we have a discussion about this, first? I noticed that `mon_max_pg_per_osd` was originally set to 300 and was reduced to 200 by b7fa440a9802005c167f854e1d19f9dd4fa8dfff

The 200 figure is mentioned in https://ceph.com/community/new-luminous-pg-overdose-protection/ which is a widely-read document, so if we're going to revert to 300 that blog post should be updated as well.

The bug this is fixing says "The Ceph PG calculator can generate recommendations for pool PG counts that will conflict with the osd_max_pgs_per_osd parameter." Have we considered fixing the PG calculator, instead?

**Comment by liewegas** [comment]
I think we should *also* change the pg calculator.  The idea here is that there are already clusters out there that have this many PGs due to following the recommendation and they now generate health warnings, which is kind of lame.  I'm happy to update the blog post to match this.

**Comment by smithfarm** [comment]
(Where does the PG Calculator code live? I couldn't find it in the Ceph repo.)

**Comment by smithfarm** [comment]
It seems like @liewegas must have reduced it from 300 for a reason - presumably because it helps prevent the dire scenario described in the blog post? If so, I would argue that the warnings - troublesome as they may be - are serving a useful purpose.

If 200 is too low, have we considered changing it to x, where `200 < x < 300` ?

**Comment by smithfarm** [comment]
According to the downstream bug:

```
(512+32768+32768+4096)*3 = 70144*3 = 210432

Compare to mon_max_pgs_per_osd * 1000 OSDs = 200 * 1000 = 200000
```

It would be enough to increase mon_max_pgs_per_osd to, e.g., 220 or 230 to fix this.

**Comment by neha-ojha** [comment]
@tchaikov removing your testing label and marking needs-qa, since we changed the value in the PR.

**Pull request merged**
