### PR TITLE
nautilus: qa: add upgrade test for volume upgrade from legacy

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
backport tracker: https://tracker.ceph.com/issues/44487

---

backport of https://github.com/ceph/ceph/pull/33636
parent tracker: https://tracker.ceph.com/issues/42723

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by bk201** [comment]
The Dashboard test error had been fixed after octopus, it needs to be backported to nautilus.
https://tracker.ceph.com/issues/42812

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-05-15-1542-nautilus](https://trello.com/c/TS49Avh1/907-wip-yuri3-testing-2020-05-15-1542-nautilus)

**Comment by ajarr** [comment]
```
 File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-yuri3-testing-2020-05-15-1542-nautilus/qa/tasks/ceph_fuse.py", line 141, in task
    info["mount"].mount(mountpoint=mountpoint, mount_path=mount_path)
```

Has caused fs-suite to fail in  Yuri's run
http://pulpito.ceph.com/yuriw-2020-05-15_19:08:10-fs-wip-yuri3-testing-2020-05-15-1542-nautilus-distro-basic-smithi/

**Comment by Vicente-Cheng** [comment]
@ajarr thanks for exploring the root cause.
Nautilus missing commit `48a95d00ba19e4ffa10a950444073135e83517bd`, I introduce with this backport pr.

@yuriw could you run fs-suite again?  sorry for missing the above commit.

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-05-27-1545-nautilus](https://trello.com/c/pGaluHjs/915-wip-yuri3-testing-2020-05-27-1545-nautilus)

**Comment by Vicente-Cheng** [comment]
Sorry for missing some setup function of property, I will update soon

**Comment by Vicente-Cheng** [comment]
jenkins retest this please

**Comment by Vicente-Cheng** [comment]
hi @yuriw, I already update the mountpoint related commits.
Could I run the test-suite again instead of on your batch test?

**Comment by Vicente-Cheng** [comment]
Hi @yuriw, it looks that passed the upgrade test-suite as following:
https://pulpito.ceph.com/kchai-2020-07-03_04:29:21-fs:upgrade-master-distro-basic-smithi/

thanks @tchaikov for scheduling a run!

**Comment by Vicente-Cheng** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-07-17-1802-nautilus](https://trello.com/c/1PohEipx/968-wip-yuri3-testing-2020-07-17-1802-nautilus)

**Comment by Vicente-Cheng** [comment]
@ajarr , thanks for helping to found the root cause!

I am happy to see the test run pass : )

**Pull request merged**
