### PR TITLE
luminous: cls/rbd: remove incompatible group features from partial implementation

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: https://tracker.ceph.com/issues/22676
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-01-15-1705](https://trello.com/c/xAZk8tY7/228-wip-yuri-testing-2018-01-15-1705)

**Comment by yuriw** [comment]
@dillaman FYI http://pulpito.ceph.com/yuriw-2018-01-15_18:21:31-upgrade:luminous-x-wip-yuri-testing-2018-01-15-1705-distro-basic-smithi/

**Comment by dillaman** [comment]
@yuriw The upgrade test installs the "luminous" branch so this PR would either need to be already merged to luminous or the test needs to be updated to pull the base branch from your CI branch.

**Comment by yuriw** [comment]
@dillaman copy my mistake , its one of those cases when tests need to be modified.  I just wanted to help testing it.  Will wait :+1:

**Comment by trociny** [comment]
@dillaman Shouldn't the title have "luminous" prefix?

**Comment by dillaman** [comment]
**upgrade:luminous-x**
http://pulpito.ceph.com/jdillaman-2018-01-17_16:13:37-upgrade:luminous-x-wip-yuri-testing-2018-01-15-1705-distro-basic-smithi/

**upgrade:luminous-x -- point-to-point patch**
http://pulpito.ceph.com/jdillaman-2018-01-17_17:24:23-upgrade:luminous-x-wip-yuri-testing-2018-01-15-1705-distro-basic-smithi/

**rbd**
http://pulpito.ceph.com/jdillaman-2018-01-17_17:30:36-rbd-wip-22676-luminous-distro-basic-smithi/

**Pull request merged**
