### PR TITLE
luminous: rgw: catch exceptions from librados::NObjectIterator 

### PR DESCRIPTION
**Pull request by cbodley**
http://tracker.ceph.com/issues/37475

---

staging backport to test compilation

### CODE REVIEW

**Comment by cbodley** [comment]
backport tracker http://tracker.ceph.com/issues/37475

**Comment by smithfarm** [comment]
@cbodley Compilation looks good - shall we remove DNM?

**Comment by cbodley** [comment]
yep thanks @smithfarm

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-01-03-1654-luminous](https://trello.com/c/vFwbW3TH/497-wip-yuri3-testing-2019-01-03-1654-luminous)

**Pull request merged**
