### PR TITLE
 ceph.spec.in: do not install Ceph RA on systemd platforms

### PR DESCRIPTION
**Pull request by smithfarm**
The ceph-resource-agents package consists of two RAs: the "Ceph RA" (which includes RAs for OSD, MON, and MDS) and the "RBD RA". Since the Ceph RA wraps the Ceph sysvinit script, it cannot be used on systemd-based platforms. The RBD RA is OK on systemd.

http://tracker.ceph.com/issues/14828 Fixes: #14828

### CODE REVIEW

**Comment by smithfarm** [comment]
Continuation of #7810

**Comment by smithfarm** [comment]
I manually tested this by building a package in OBS and installing it on openSUSE Tumbleweed. Confirmed that only the RBD RA is installed.

**Comment by tserong** [comment]
Looks good to me

**Comment by smithfarm** [comment]
@ktdreyer Who should I ask to review this? The issue it is fixing is as follows: the Ceph Resource Agents are useless on systemd platforms because they wrap `/etc/init.d/ceph`.

**Comment by smithfarm** [comment]
`upgrade/infernalis-x` running now at http://149.202.162.67:8081/ubuntu-2016-03-15_07:45:21-upgrade:infernalis-x-wip-14828---basic-openstack/

**Comment by smithfarm** [comment]
Tore down that run after looking at  http://pulpito.ovh.sepia.ceph.com:8081/?branch=jewel and seeing that it would be affected by http://tracker.ceph.com/issues/15123 which is fixed by https://github.com/ceph/ceph/pull/8073 

Rolled a new wip branch including the fix for this issue. New upgrade/infernalis-x run in OVH:

```
cw ceph-qa-suite --verbose --suite upgrade/infernalis-x --suite-branch master --ceph wip-14828-with-fsmap-fix --ceph-git-url https://github.com/SUSE/ceph
```

http://149.202.190.143:8081/ubuntu-2016-03-15_08:53:39-upgrade:infernalis-x-wip-14828-with-fsmap-fix---basic-openstack/

**Comment by liewegas** [comment]
lgtm in principle; feel free to merge once you're satisfied with the testing.

**Comment by smithfarm** [comment]
@dachary This passed the `upgrade:infernalis-x/parallel/{4-jewel.yaml 0-cluster/start.yaml 1-infernalis-install/infernalis.yaml 2-workload/{ec-rados-default.yaml rados_api.yaml rados_loadgenbig.yaml test_rbd_api.yaml test_rbd_python.yaml} 3-upgrade-sequence/upgrade-all.yaml 5-final-workload/{rados-snaps-few-objects.yaml rados_loadgenmix.yaml rados_mon_thrash.yaml rbd_cls.yaml rbd_import_export.yaml rgw_swift.yaml} distros/centos_7.2.yaml}` test here:

* http://149.202.190.143:8081/ubuntu-2016-03-16_08:55:41-upgrade:infernalis-x-wip-14828-with-fsmap-fix---basic-openstack/

Do you think that is sufficient to demonstrate that it doesn't break anything?

**Pull request merged**
