### PR TITLE
nautilus: mgr/dashboard: Manager should complain about wrong dashboard certificate

### PR DESCRIPTION
**Pull request by s0nea**
http://tracker.ceph.com/issues/39346

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
[OT] we need #26741 and #27035 for test_rgw_reshard_wait test failure.

**Comment by s0nea** [comment]
> [OT] we need #26741 and #27035 for addressing test_rgw_reshard_wait test failure.
> #27721 for addressing doc build failure.

Thanks for the hint @tchaikov . Should I open new backports for each of the PRs you mentioned or include all commits here? - Creating three backport PRs would be the right way I guess.

**Comment by tchaikov** [comment]
@s0nea i'd suggest create two tracker ticket for test_rgw_reshard_wait and doc build failure respectively. one should cover the #26741 and #27035, the other #27721 .

**Comment by s0nea** [comment]
jenkins test docs

**Comment by s0nea** [comment]
jenkins test docs

**Comment by s0nea** [comment]
Needs to be merged after https://github.com/ceph/ceph/pull/27779

**Comment by smithfarm** [comment]
> Needs to be merged after #27779

#27779 was merged.

**Comment by smithfarm** [comment]
Hm, I wonder if the "Unmodified submodules" Jenkins test is failing because this PR contains a commit that touches a file `src/pybind/mgr/dashboard/module.py` which contains the string "module"???

**Comment by smithfarm** [comment]
jenkins test unmodified submodules

**Comment by smithfarm** [comment]
jenkins test Unmodified Submodules

**Comment by tchaikov** [comment]
@smithfarm we don't have a trigger phrase for unmodified submodule check yet =(

see https://github.com/ceph/ceph-build/blob/08b60c8aa0f0c9bb47b193690db3dfef5db57e8c/ceph-pr-submodules/config/definitions/ceph-pr-commits.yml#L30

jenkins, retest this please

**Comment by smithfarm** [comment]
@tchaikov Thanks! I was too lazy to go looking for that. Here's the PR: https://github.com/ceph/ceph-build/pull/1306

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-06-07-1600-nautilus](https://trello.com/c/fYD3krdU/633-wip-yuri4-testing-2019-06-07-1600-nautilus)

**Pull request merged**
