### PR TITLE
librbd: potential double-unwatch of watch handle upon error

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: http://tracker.ceph.com/issues/17210
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by dillaman** [comment]
Still hitting an issue: http://pulpito.ceph.com/jdillaman-2016-09-04_16:08:56-rbd-wip-jd-testing---basic-smithi/400108

**Comment by dillaman** [comment]
@trociny update pushed that recognizes that any errors from a rewatch imply the watch is unregistered

**Comment by trociny** [comment]
retest this please

**Comment by trociny** [comment]
lgtm

**Pull request merged**
