### PR TITLE
pybind/mgr/prometheus: big changes

### PR DESCRIPTION
**Pull request by jan--f**
This PR changes the prometheus plugin significantly. It'll now export basic cluster stats and a selected list of perf counters. This should provide roughly equal functionality like the [ceph_exporter](https://github.com/digitalocean/ceph_exporter), though the two are not at all interchangeable. Metric and label naming is handled very differently.

Some things that still require some work, like:

- When the cluster is unavailable, the plugin will report the last state (like HEALTH_OK). Needs to be addressed in the mgr.
- Add more metrics/metadata.
- Improve cluster metric descriptions.
- Collection for the metadata metrics is awkward.
- I have seen sporadic Exceptions when the module seems to race with serving the metrics and module init. The next request will however work fine. Needs more investigation.

### CODE REVIEW

**Comment by jcsp** [comment]
Looking at this and https://github.com/ceph/ceph/pull/16999 together, I think it would be useful to have a new function or two for retrieving all the performance counters that are `>=` a particular priority level: that way both plugins could just call that, and avoid having some partially-overlapping lists of which counters they export.  I hope to have time to work on adding that this week

**Comment by jan--f** [comment]
@jcsp Sounds good to me. Would this also make sense for the cluster wide stats? Yields the same benefits, but would add yet another function the the mgr api that exports already exported data.

Are you talking about #16699? Happy to help!

**Comment by liewegas** [comment]
@jan--f @jcsp ping

**Comment by jcsp** [comment]
See also https://github.com/ceph/ceph/pull/17735

**Comment by liyichao** [comment]
I think it may be better for ceph to concentrate on the one plugin (for example, prometheus plugin) to expose the metric, which the core value the ceph plugin provides.For Zabbix，influxdb or many more others, there are already solutions, for example, using collectd's prometheus and influxdb plugin, data can be collected using prometheus and sent to influxdb. 

Currently we are looking forward to ceph's prometheus plugin to be more mature, and provide more data to look at. For example, ceph's health status is not available for now. It may be better for ceph to focus on one plugin, make it better, usable, before doing things that convert from one protocol to another, or making the plugin general.

**Comment by jcsp** [comment]
Merged with https://github.com/ceph/ceph/pull/17735

**Pull request closed without merging**
