### PR TITLE
mon: show legacy health warning in `status` output

### PR DESCRIPTION
**Pull request by jcsp**
Previously you only got the text of this if you were
either looking at "health detail" or if you had
already set the preluminous_compat setting (in which
case you presumably were already aware so the message
isn't doing much).

Signed-off-by John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by xiexingguo** [comment]
The `Signed-off-by` is not right, missing `:` ...

**Comment by jcsp** [comment]
Thanks, fixed message + a compile error.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-09-29_18:35:33-rados-wip-sage-testing-2017-09-29-1154-distro-basic-smithi/

**Pull request merged**
