### PR TITLE
doc: fix cephadm link

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: 8fe460e7562b28e007179eeb533ef68a3e99b4c8
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by liewegas** [comment]
Maybe better to use :ref:`cephadm` throughout?

**Comment by smithfarm** [comment]
> Maybe better to use :ref:`cephadm` throughout?

Like this?

**Comment by sebastian-philipp** [comment]
jenkins render docs

**Comment by smithfarm** [comment]
run-tox-mgr failed because of:

```
E   AttributeError: 'list' object has no attribute 'pretty_print'
```

**Comment by smithfarm** [comment]
jenkins test make check

**Pull request merged**
