### PR TITLE
buffer: put inlined memcpy into a header; x86_64 only

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@stevecapperlinaro Will a similar optimization help on ARM64?  The unwound memcpy is about 80% faster on my x86_64 box for 1/2/4/8 byte copies.

**Comment by stevecapperlinaro** [comment]
Thanks @liewegas, yes I would imagine it would help ARM64 too (even though the glibc memcpy is optimised for small sizes, I think it would be advantageous to avoid the function call if possible). I am back in the office next week and will be able to confirm when I run the unit test.

**Comment by liewegas** [comment]
@yehudasa your change had no effect on x86_64, so looks good to me!  I switched around the ifdefs so that mem_is_zero is still x86_64 only.. look ok?

**Comment by yehudasa** [comment]
@liewegas lgtm

**Comment by stevecapperlinaro** [comment]
Hi @liewegas , @yehudasa , sorry about the late reply (I was sleeping off conference jetlag). I have taken a look at the code.

I'm a little concerned about the use of packed structs as it's not 100% clear to me what they should do; my understanding is that they will mostly fall back to byte copies on platforms that don't like misaligned accesses.

For the call sites, do we have expected memcpy sizes at all? Another strategy would be to do something like:
```
if (size == expected_size)
    memcpy(dest, src, expected_size);
else
    memcpy(dest, src, size);
```
If the call site has a mode memcpy size that is small, then the compiler will automatically inline the small memcpy and produce very good code. Indeed anything that can help the compiler know a memcpy size at compile time *should* give us the most optimal code.

This above could be generalised even further to something like:
```#define maybe_inline_memcpy(W, X, Y, Z) memcpy (W, X, f(Y, Z))```
Where ```f(Y,Z)``` is an inline expression that can return a size to the real memcpy.
(thanks to a colleague for suggesting this generalisation)

So perhaps an idea would be to place uprobes (or something similar) on the call sites that cause the hotspots, get the mode memcpy sizes and then let the compiler know what the expected sizes are for these spots so it can do the in-lining itself?

**Comment by liewegas** [comment]
Yeah, perhaps changing all of the pointer copies with calls to __builtin_memcpy() will have the desired effect... The question, though, is whether an inline expression will optimize as well as the explicit switch.  It also won't capture the cases like '6' that are current a u32 + u16.  (Not that those probably occur in practice anyway.. it's really the 1, 2, 4, and 8 byte cases that dominate.

Either way, it'll need some benchmarking.  I don't want to let something that works get hung up on finding the perfect generalization, though.  Do we agree that this series is an improvement over the version currently in master?

**Comment by stevecapperlinaro** [comment]
Sorry for dragging this on but why not something like?
```
void *maybe_inline_memcpy(void *dest, const void *src, size_t l)
{
  switch (l) {
  case 8:
    return memcpy(dest, src, 8);
  case 4:
    return memcpy(dest, src, 4);
  case 3:
    return memcpy(dest, src, 3);
  case 2:
    return memcpy(dest, src, 2);
  case 1:
    return memcpy(dest, src, 1);
  }

  return memcpy(dest, src, l);
}
```
It looks slightly silly at first, but will give optimal safe implementations for l = 1,2,3,4,8 as the compiler will inline those memcpy function calls:
```
0000000000000000 <maybe_inline_memcpy>:
   0:   d1000443        sub     x3, x2, #0x1
   4:   f1001c7f        cmp     x3, #0x7
   8:   54000068        b.hi    14 <maybe_inline_memcpy+0x14>
   c:   71001c7f        cmp     w3, #0x7
  10:   54000049        b.ls    18 <maybe_inline_memcpy+0x18>
  14:   14000000        b       0 <memcpy>
  18:   90000004        adrp    x4, 0 <maybe_inline_memcpy>
  1c:   91000084        add     x4, x4, #0x0
  20:   38634883        ldrb    w3, [x4,w3,uxtw]
  24:   10000064        adr     x4, 30 <maybe_inline_memcpy+0x30>
  28:   8b238883        add     x3, x4, w3, sxtb #2
  2c:   d61f0060        br      x3
  30:   f9400021        ldr     x1, [x1]
  34:   f9000001        str     x1, [x0]
  38:   d65f03c0        ret
  3c:   b9400021        ldr     w1, [x1]
  40:   b9000001        str     w1, [x0]
  44:   d65f03c0        ret
  48:   79400022        ldrh    w2, [x1]
  4c:   79000002        strh    w2, [x0]
  50:   39400821        ldrb    w1, [x1,#2]
  54:   39000801        strb    w1, [x0,#2]
  58:   d65f03c0        ret
  5c:   79400021        ldrh    w1, [x1]
  60:   79000001        strh    w1, [x0]
  64:   d65f03c0        ret
  68:   39400021        ldrb    w1, [x1]
  6c:   39000001        strb    w1, [x0]
  70:   d65f03c0        ret
```

Or do we get a big speed boost for the  8 < l < inline_len, case in your patch?

**Comment by liewegas** [comment]
@stevecapperlinaro How about this?

**Pull request merged**
