### PR TITLE
rgw: fix get bucket policy s3 compatible issue

### PR DESCRIPTION
**Pull request by ZVampirEM77**
In AWS S3 get bucket policy should return 404 error code when bucket policy does not exist like following:

Response: {'status': 404, 'headers': {'x-amz-id-2': 'Gncp2wjrOy2Juy0RFbuyWjGFCFNSQd8vXIi8sbxhSdR7bi4VmjSlbmRKkUr3dK3+tmewATJSwZw=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'x-amz-request-id': 'D3F18909B654014A', 'date': 'Thu, 25 May 2017 03:28:35 GMT', 'content-type': 'application/xml'}, 'reason': 'Not Found', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>NoSuchBucketPolicy</Code><Message>The bucket policy does not exist</Message><BucketName>em-111</BucketName><RequestId>D3F18909B654014A</RequestId><HostId>Gncp2wjrOy2Juy0RFbuyWjGFCFNSQd8vXIi8sbxhSdR7bi4VmjSlbmRKkUr3dK3+tmewATJSwZw=</HostId></Error>'}

Now RGW return is:

Response: {'status': 404, 'headers': {'date': 'Thu, 25 May 2017 06:38:48 GMT', 'content-length': '270', 'x-amz-request-id': 'tx00000000000000000000e-0059267bf8-1013-default', 'content-type': 'application/xml', 'accept-ranges': 'bytes'}, 'reason': 'Not Found', 'data': '<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchBucketPolicy</Code><Message>The bucket policy does not exist</Message><BucketName>111</BucketName><RequestId>tx00000000000000000000e-0059267bf8-1013-default</RequestId><HostId>1013-default-default</HostId></Error>'}

Signed-off-by: Enming Zhang <enming.zhang@umcloud.com>

### CODE REVIEW

**Comment by cbodley** [comment]
passed rgw suite: http://pulpito.ceph.com/cbodley-2017-06-06_14:33:04-rgw-wip-cbodley-testing-distro-basic-mira/

@ZVampirEM77 can you rebase to resolve the conflict please?

**Comment by ZVampirEM77** [comment]
@cbodley OK, I have done it~

**Comment by cbodley** [comment]
jenkins test this please

**Comment by cbodley** [comment]
jenkins test this please

**Pull request merged**
