### PR TITLE
MonitorDBStore : make monitor transaction more readable

### PR DESCRIPTION
**Pull request by xinxinsh**
Signed-off-by: xinxin shu <xinxin.shu@intel.com>

### CODE REVIEW

**Comment by xinxinsh** [comment]
it seems that failure is not related to this PR

**Comment by dachary** [comment]
@xinxinsh you can ignore the false negative: it is because jenkins does not handle rebasing very well.

**Comment by xinxinsh** [comment]
@liewegas , can you review this?

**Comment by liewegas** [comment]
I'm not sure offhand whether the Formatter will behave if you do flush with an open array section, but assuming you've tested that nad it works, looks good to me.  @jecluis ?

**Comment by xinxinsh** [comment]
@liewegas @jecluis ， below is a smaple output

 {
        "ops": [
            {
                "op_num": 0,
                "type": "ERASE",
                "prefix": "mkfs",
                "key": "monmap"
            }
        ],
        "num_keys": 1,
        "num_bytes": 10
    }
,
    {
        "ops": [
            {
                "op_num": 0,
                "type": "PUT",
                "prefix": "monitor",
                "key": "election_epoch",
                "length": 8,
                "bl": "0000 : 02 00 00 00 00 00 00 00                         : ........\n"
            }
        ],
        "num_keys": 1,
        "num_bytes": 29
    }

**Comment by jecluis** [comment]
this looks good to me, but the commit title is a bit misleading; I initially thought I was going to look to something that would make transactions more readable on dump; looks like it's the transaction code that ought to be more readable.

**Comment by xinxinsh** [comment]
@jecluis , update commit message

**Comment by xinxinsh** [comment]
@liewegas , @jecluis , can you help review

**Comment by xinxinsh** [comment]
@liewegas @jecluis , pls help review

**Comment by jecluis** [comment]
I think this looks okay, but I'm pretty sure this will break ceph-monstore-tool -- especially because it expects a binary file while this is having the dump file being plain text json.

I think this will have to have both, maybe adding an option to whether dump in plain text or a proper trace file. Breaking ceph-monstore-tool with this would be really crappy :(

**Comment by xinxinsh** [comment]
@jecluis , thanks for your comment, i will take a look

**Comment by xinxinsh** [comment]
@jecluis , updated, pls help review

**Comment by xinxinsh** [comment]
@jecluis ， updated

**Comment by jecluis** [comment]
looks good. I'll test it this week.

**Comment by xinxinsh** [comment]
@jecluis , any update?

**Comment by xinxinsh** [comment]
@jecluis , any update

**Comment by xinxinsh** [comment]
@jecluis , @liewegas , any progress?

**Comment by athanatos** [comment]
This passed a wip-sam-testing run.  @jecluis, you can just merge if you are happy with it.

**Comment by xinxinsh** [comment]
@jecluis , can you help merge

**Pull request merged**
