### PR TITLE
qa: disable metrics on kernel client during upgrade

### PR DESCRIPTION
**Pull request by batrick**
## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests
- Teuthology
  - [x] Completed teuthology run
  - [ ] No teuthology test necessary (e.g., documentation)

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by djgalloway** [comment]
Does this also fix https://tracker.ceph.com/issues/53288?

**Comment by batrick** [comment]
> Does this also fix https://tracker.ceph.com/issues/53288?

I assume 53288 is for fixing teuthology/qa so this type of failure does not result in a 12 hour dead job.

**Review by lxbsz — APPROVED** [review]
LGTM.

@batrick @vshankar @jtlayton 

BTW, will it also make sense in MDS add one flag or a version flag about which metrics has been supported, then in kclient it will only send the metrics the MDS supported ?

**Comment by jtlayton** [comment]
Honestly, this all seems like a lot of workaround for something that's just a bug in the MDS. It should have never asserted on unknown messages. Why not just fix the MDS and move on? I know it's already fixed in later versions, so why are we testing something that we know is broken?

**Comment by batrick** [comment]
> Honestly, this all seems like a lot of workaround for something that's just a bug in the MDS. It should have never asserted on unknown messages. Why not just fix the MDS and move on? I know it's already fixed in later versions, so why are we testing something that we know is broken? Maybe it'd be easier to just avoid testing metrics with an MDS this old?

Yes, that's the crux of the problem. The reason I'm testing v16.2.4 is that the upgrade procedure changed in v16.2.5 due to changes in the MDSMap. I need to verify v16.2.4 (and older) can still upgrade.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2021-11-19_16:32:48-fs:upgrade-wip-pdonnell-testing-20211119.143151-distro-basic-smithi/

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
Made a small change by adding a comment: https://github.com/ceph/ceph/pull/43974/files#diff-2b38621f9773a577e0bb07983016de246cb8ec0c936b75e7135e9218632ac20dR6

this is ready to merge IMO when tests pass

**Review by jtlayton — APPROVED** [review]

**Pull request merged**
