### PR TITLE
pacific: osd, tools, kv: non-aggressive, on-line trimming of accumulated dups

### PR DESCRIPTION
**Pull request by rzarzynski**
This is a pacific version of https://github.com/ceph/ceph/pull/47046.

https://github.com/ceph/ceph/commit/c916f568aa9776f4cd864114670fef769f56fdab hasn't been backported as pacific lacks `TEST_trim_max_entries_with_dups`.

```
[rzarzynski@o06 build]$ grep -r TEST_trim_max_entries_with_dups ../qa
[rzarzynski@o06 build]$ echo $?
1
rzarzynski@o06 build]$ git describe 
v16.2.10-717-g9e707c1de85

```

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
jenkins test api

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
```
Installing collected packages: pip
  Attempting uninstall: pip
In file included from crc/../os/os.h:38,
                 from crc/crc32c-arm64.c:2:
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
```

**Comment by rzarzynski** [comment]
```
CMake Error at cmake/modules/Distutils.cmake:81 (message):
  Unable to tell python extension's suffix: Traceback (most recent call
  last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig' from 'distutils'
  (/usr/lib/python3.8/distutils/__init__.py)
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
jenkins test api

**Comment by rzarzynski** [comment]
```
CMake Error at cmake/modules/Distutils.cmake:81 (message):
  Unable to tell python extension's suffix: Traceback (most recent call
  last):

    File "<string>", line 1, in <module>

  ImportError: cannot import name 'sysconfig' from 'distutils'
  (/usr/lib/python3.8/distutils/__init__.py)

Call Stack (most recent call first):
  src/pybind/rados/CMakeLists.txt:1 (distutils_add_cython_module)
```

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by rzarzynski** [comment]
```
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:372: crc/crc32c-arm64.o] Error 1
make[4]: *** Waiting for unfinished jobs....
In file included from crc/../os/os.h:38,
                 from crc/test.c:9:
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
In file included from crc/../os/os.h:38,
                 from crc/sha3.c:17:
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by rzarzynski** [comment]
jenkins retest this please

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by neha-ojha** [comment]
jenkins test api

**Comment by rzarzynski** [comment]
@neha-ojha: updated the PR's description. In short: pacific lacks `TEST_trim_max_entries_with_dups`.

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
```
In file included from crc/../os/os.h:38,
                 from crc/crc32c-arm64.c:2:
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
jenkins test api

**Comment by rzarzynski** [comment]
```
	 11 - run-rbd-unit-tests-0.sh (Failed)
	 12 - run-rbd-unit-tests-1.sh (Failed)
	 13 - run-rbd-unit-tests-61.sh (Failed)
	 14 - run-rbd-unit-tests-109.sh (Failed)
	 15 - run-rbd-unit-tests-127.sh (Failed)
```

**Comment by rzarzynski** [comment]
jenkins test make check

**Comment by rzarzynski** [comment]
@neha-ojha: huh, this PR somehow (automagically...) got closed.

**Comment by neha-ojha** [comment]
> @neha-ojha: huh, this PR somehow (automagically...) got closed.

wow! no idea how that happened, GH sorcery? :D

**Comment by rzarzynski** [comment]
I bet a GH's bug with a magic wand ;-).

@yuriw: are we ready to go with this?

**Comment by ljflores** [comment]
Hey @rzarzynski, I created a tracker for a new crash I saw in the OSD code: https://tracker.ceph.com/issues/57628

It doesn't look related to this PR, but could you please verify?

If that looks good, then this PR is rados approved. I'm pasting the summary below, in case it gets used:

https://pulpito.ceph.com/?branch=wip-yuri2-testing-2022-09-06-1007-pacific

https://tracker.ceph.com/issues/57628 -- new Tracker; need to verify

Failures, unrelated:
    1. https://tracker.ceph.com/issues/54071
    2. https://tracker.ceph.com/issues/57386
    3. https://tracker.ceph.com/issues/53827
    4. https://tracker.ceph.com/issues/49287
    5. https://tracker.ceph.com/issues/57269
    6. https://tracker.ceph.com/issues/56573

Details:
    1. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    2. cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did - Ceph - Mgr - Dashboard
    3. cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Infrastructure - Sepia
    4. podman: setting cgroup config for procHooks process caused: Unit libpod-$hash.scope not found - Ceph - Orchestrator
    5. rook: unable to read URL "https://docs.projectcalico.org/manifests/tigera-operator.yaml" - Ceph - Orchestrator
    6. test_cephadm.sh: KeyError: 'TYPE' - Ceph - Orchestrator

**Pull request merged**
