### PR TITLE
client: fix mount timeout

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #10041
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Hmm, I think this works. But I don't think we can get any requests prior to a successful mount except for the single root inode lookup, so is there some reason we can't do this via a special-case timer?

I normally prefer general solutions, but I'm worried that this looks general but probably won't work if we try and abort ops in other situations.
Also: how'd you test? ;)

**Comment by ukernel** [comment]
yes, it does not work for other situations. we can use special-case timer to kill ceph-fuse. but we want make_request() return proper error code instead. I can't see how can special-case timer make code clear.

**Comment by gregsfortytwo** [comment]
Okay. How'd you test?

**Comment by ukernel** [comment]
mount while no mds is running

**Pull request merged**
