### PR TITLE
doc/releases/schedule: Add Luminous 12.2.8

### PR DESCRIPTION
**Pull request by badone**
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by badone** [comment]
Jenkins render docs

**Comment by badone** [comment]
@smithfarm mind taking a look mate?

**Comment by smithfarm** [comment]
@badone Thanks, LGTM, just one unrelated request:

According to [1], Mimic 13.2.0 was released on June 1, 2018, but the intersection of the "First release" row and the "Mimic" column shows "May 2018". Could you fix this to show the correct value "June 2018"? (It happens to be the first column and row in the table.)

[1] https://ceph.com/releases/v13-2-0-mimic-released/

**Comment by badone** [comment]
@smithfarm see https://github.com/ceph/ceph/pull/24099

**Pull request merged**
