### PR TITLE
quincy: librbd: make diff-iterate in fast-diff mode aware of encryption

### PR DESCRIPTION
**Pull request by idryomov**
backport tracker: https://tracker.ceph.com/issues/66745

---

backport of https://github.com/ceph/ceph/pull/58201
parent tracker: https://tracker.ceph.com/issues/66570

### CODE REVIEW

**Comment by idryomov** [comment]
Temporarily based on https://github.com/ceph/ceph/pull/58210 to avoid conflicts in `src/test/librbd/test_librbd.cc`.

**Review by ajarr — APPROVED** [review]

**Comment by idryomov** [comment]
> Conflicts:
>	src/test/librbd/test_librbd.cc [ commit https://github.com/idryomov/ceph/commit/4a5a0a5dd82be9266064631dfee352a96e4061ca ("librbd:
>	  add cloned images encryption API") not in quincy

Sigh, I forgot that `ImageArea` support isn't in quincy either.  The fix would essentially need to be rewritten from scratch...

I'll try to look into it, but might choose leaving this unfixed in quincy given that it's almost EOL.

**Comment by idryomov** [comment]
jenkins test api

**Comment by yuriw** [comment]
ref: https://tracker.ceph.com/issues/66072#change-268609

**Comment by idryomov** [comment]
Rebased after https://github.com/ceph/ceph/pull/58210 merged.

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
> ref: https://tracker.ceph.com/issues/66072#change-268609

Tests actually passed -- this just needed a rebase.

**Pull request merged**
