### PR TITLE
normalize and verify the erasure code profile

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11663

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
run: 47: TEST_rados_put_get_shec testdir/test-erasure-code
TEST_rados_put_get_shec: 198: local dir=testdir/test-erasure-code
TEST_rados_put_get_shec: 200: local poolname=pool-shec
TEST_rados_put_get_shec: 201: local profile=profile-shec
TEST_rados_put_get_shec: 203: ./ceph osd erasure-code-profile set profile-shec plugin=shec k=2 m=1 c=1 ruleset-failure-domain=osd
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
2015-05-17 22:26:26.240301 7fcba833d700 -1 WARNING: the following dangerous and experimental features are enabled: shec
2015-05-17 22:26:26.270111 7fcba833d700 -1 WARNING: the following dangerous and experimental features are enabled: shec
2015-05-17 22:26:26.272102 7fcba833d700 -1 WARNING: the following dangerous and experimental features are enabled: shec
WARNING: experimental feature 'shec' is enabled
TEST_rados_put_get_shec: 207: ./ceph osd pool create pool-shec 12 12 erasure profile-shec
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
2015-05-17 22:26:26.674325 7f2b5fd2a700 -1 WARNING: the following dangerous and experimental features are enabled: shec
2015-05-17 22:26:26.705688 7f2b5fd2a700 -1 WARNING: the following dangerous and experimental features are enabled: shec
2015-05-17 22:26:26.707928 7f2b5fd2a700 -1 WARNING: the following dangerous and experimental features are enabled: shec
Error ENOENT: failed to load plugin using profile profile-shec
TEST_rados_put_get_shec: 208: return 1
</pre>

**Comment by dachary** [comment]
<pre>
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
{}

TEST_crush_rule_create_erasure: 116: grep 'profile default set' testdir/osd-crush/mon.a.log
TEST_crush_rule_create_erasure: 116: return 1
</pre>
the debug message has changed

**Comment by dachary** [comment]
<pre>
Error EINVAL: load: example factory profile {directory=.libs,key=value,plugin=example} != get_profile() {}
TEST_set: 55: return 1
</pre>

**Comment by dachary** [comment]
@apeters1971 if you feel like it, this one is a lot simpler :-)

**Comment by dachary** [comment]
<pre>
./virtualenv/bin/teuthology-suite --subset $(expr $RANDOM % 18)/18 --priority 101 --suite rados/thrash-erasure-code --suite-branch master --machine-type plana,burnupi,mira --distro ubuntu --email loic@dachary.org --ceph wip-11663-verify-erasure-code-profile
2015-06-01 23:40:59,860.860 INFO:teuthology.suite:Passed subset=0/18
</pre>
http://pulpito.ceph.com/loic-2015-06-01_23:40:59-rados:thrash-erasure-code-wip-11663-verify-erasure-code-profile---basic-multi/

**Comment by dachary** [comment]
verify LRC separately: not merged yet
<pre>
./virtualenv/bin/teuthology-suite --subset $(expr $RANDOM % 18)/18 --priority 101 --suite rados/thrash-erasure-code-big --suite-branch wip-11666-erasure-code-lrc --machine-type plana,burnupi,mira --distro ubuntu --email loic@dachary.org --ceph wip-11663-verify-erasure-code-profile
2015-06-02 08:32:37,242.242 INFO:teuthology.suite:Passed subset=9/18
</pre>
http://pulpito.ceph.com/loic-2015-06-02_08:32:37-rados:thrash-erasure-code-big-wip-11663-verify-erasure-code-profile---basic-multi/

**Comment by dachary** [comment]
@apeters1971 it passed integration tests, except for shec which does not have them yet.

**Comment by apeters1971** [comment]
Hi Loic, looks ok. The only ugly part is that "goto reply" and "goto wait" in the OSDMonitor code, but they were there probably before ...

**Comment by dachary** [comment]
@apeters1971 yeah, I did not invent this goto, they are all over the place. You get used to it though ;-)

**Pull request merged**
