### PR TITLE
octopus: cephadm batch backport September (2)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #36800, #36894, #36929, #36995, #36946, #36432, #36903, #36766, #37046, #37071, #36980, #36935, #36822, #37094, #36936, #35543, #35945, #37115, #36898, #37141, #36969, #37135, #36890, #37059, #37245, #37218, #37216, #37213, #37206, #37106, #37133, #37186, #37236

conflicts:

src/pybind/mgr/module.py
src/pybind/mgr/dashboard/frontend/src/app/ceph/cluster/services/service-form/service-form.component.ts

@votdev See https://github.com/ceph/ceph/pull/36969/files#diff-e3133928fba916e94711f74b234ccb24R200-R203

### CODE REVIEW

**Comment by mgfritch** [comment]
jenkins test make check

**Review by mgfritch — APPROVED** [review]

**Comment by ricardoasmarques** [comment]
This backport will introduce the `cephadm bootstrap --container-init` option ( https://github.com/ceph/ceph/pull/36822 ) which will not work without the following fix: https://github.com/ceph/ceph/pull/37500

**Comment by smithfarm** [comment]
The `Docs: build check` failure looks like https://tracker.ceph.com/issues/47628 the fix for which is being backported to octopus via https://github.com/ceph/ceph/pull/37142

(but you could cherry-pick the two commits from https://github.com/ceph/ceph/pull/33888 into the PR as well - I believe they will apply without conflicts, and in that case there is no harm in having duplicate commits)

**Comment by smithfarm** [comment]
@jschmid1 Please drop #36995 from this PR. It is not needed in octopus. (Dropping it here will ease the pain of reverting it.)

**Comment by jschmid1** [comment]
jenkins test docs

**Comment by jschmid1** [comment]
looks like this:

```
/home/jenkins-build/build/workspace/ceph-pr-docs/build-doc/virtualenv/lib/python3.6/site-packages/sphinx/util/docutils.py:287: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephadm/drivegroups.rst:13: WARNING: Unknown directive type "prompt".

.. prompt:: bash [monitor.1]#

  ceph orch daemon add osd *<host>*:*<path-to-device>*
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephadm/drivegroups.rst:39: WARNING: Unknown directive type "prompt".

.. prompt:: bash [monitor.1]#

  ceph orch apply osd -i /path/to/osd_spec.yml
/home/jenkins-build/build/workspace/ceph-pr-docs/doc/cephadm/drivegroups.rst:52: WARNING: Unknown directive type "prompt".

.. prompt:: bash [monitor.1]#
```

is the issue

**Comment by smithfarm** [comment]
@jschmid1 Regarding the `Docs: build check` failure, please see https://github.com/ceph/ceph/pull/37436#issuecomment-702799383

**Comment by jschmid1** [comment]
> @jschmid1 Regarding the `Docs: build check` failure, please see [#37436 (comment)](https://github.com/ceph/ceph/pull/37436#issuecomment-702799383)

Oh, got it.

**Comment by smithfarm** [comment]
Changelog:

* dropped `8e697037454 rpm: on SUSE, podman is required for cephadm to work`
* cherry-picked `admin/build-doc: use "ceph" for prefix of functions defined by libcephfs`
* cherry-picked `admin/build-doc: pass -rpath to linker`

**Comment by smithfarm** [comment]
@tchaikov It looks like cherry-picking https://github.com/ceph/ceph/pull/36879 into this PR might address the `Docs: build check` failure. Do you think we need all 11 commits from that PR, or just a subset?

**Comment by tchaikov** [comment]
@smithfarm i think 7ca85e77d040e990fc60d7fe99447d3fb1e7f69e would suffice.

**Comment by jschmid1** [comment]
@tchaikov or @djgalloway could anybody of you please schedule a test run on this PR?

**Comment by smithfarm** [comment]
@tchaikov Thanks, did the trick.

**Comment by tchaikov** [comment]
> @tchaikov or @djgalloway could anybody of you please schedule a test run on this PR?

@jschmid1 sepia is open to community contributors, please feel free to schedule a run after [applying an account](https://ceph.github.io/sepia/adding_users/).

**Comment by jschmid1** [comment]
@tchaikov notice the labels on this pullrequest :) I tried it several times myself, but for some reason I can't schedule runs for this pullrequest. Is the process any different when scheduling PRs that are targeting `master` as opposed to `octopus`?

**Comment by smithfarm** [comment]
@jschmid1 teuthology run is scheduled: http://pulpito.ceph.com:80/smithfarm-2020-10-08_15:23:59-rados:cephadm-wip-jschmid1-testing1-2020-10-07-1000-distro-basic-smithi/

**Comment by smithfarm** [comment]
Here is the reason why it isn't possible to schedule a rados/cephadm run: https://tracker.ceph.com/issues/47796

**Comment by smithfarm** [comment]
> @jschmid1 teuthology run is scheduled: http://pulpito.ceph.com:80/smithfarm-2020-10-08_15:23:59-rados:cephadm-wip-jschmid1-testing1-2020-10-07-1000-distro-basic-smithi/

PASSED

**Review by smithfarm — APPROVED** [review]

**Pull request merged**
