### PR TITLE
bluestore/NVMEDevice: fix the bug in write function

### PR DESCRIPTION
**Pull request by optimistyzy**
NVMEDevice: fix the write bug
This patch can solve the write issue when we use spdk nvme driver to handle I/Os from db bdev in the future.

Signed-off-by: Ziye Yang <optimistyzy@gmail.com>
Signed-off-by: Pan Liu <wanjun.lp@alibaba-inc.com>

### CODE REVIEW

**Comment by optimistyzy** [comment]
@liupan1111

**Comment by liupan1111** [comment]
I tried locally and it works well.

**Comment by liupan1111** [comment]
Jenkins, retest this please

**Comment by liupan1111** [comment]
Jenkins, retest this please

**Comment by liupan1111** [comment]
Jenkins, retest this please

**Pull request merged**
