### PR TITLE
os/bluestore/NVMEDevice: fix the compilation issue for collect_metadata

### PR DESCRIPTION
**Pull request by optimistyzy**
Signed-off-by: optimistyzy <optimistyzy@gmail.com>

### CODE REVIEW

**Comment by optimistyzy** [comment]
@liupan1111 @yuyuyu101  tested with workload, it solves the issue.

**Comment by liupan1111** [comment]
LGTM!

@liewegas This is a polish for your commit https://github.com/ceph/ceph/commit/c4316637b15285c2ae7e1ba81fdebc60f21bbbfa

Could you help double check?

**Comment by liewegas** [comment]
Thanks! 

Speaking of which, I think @ifed01 was having some trouble getting SPDK to compile the other day.  Since DPDK and SPDK are now both submodules, perhaps we can enable the build by default?  (We can always disable it in the package builds if we don't want to ship it.)

**Comment by liupan1111** [comment]
@liewegas,

In current code,  we could find spdk is controlled by a macro "HAVE_SPDK":

```
#if defined(HAVE_SPDK)
  if (type == "ust-nvme") {
    return new NVMEDevice(cct, cb, cbpriv);
  }
#endif
```
And HAVE_SPDK will be defined only when "WITH_SPDK" is on when run cmake.

In my opinion, we could set "WITH_SPDK" to on as default(maybe off when ship), and add an new option in config_opt.h(maybe osd_device_type?), when set "userspace", NVMEDevice(spdk) will be used, otherwise, "kernel", KernelDevice will be used.

@yuyuyu101, do you agree?

**Pull request merged**
