### PR TITLE
doc: fix invalid hyperlink of `Hardware Recommendations` in ceph-conf

### PR DESCRIPTION
**Pull request by zealoussnow**
Signed-off-by: Leo Zhang <nguzcf@gmail.com>

### CODE REVIEW

**Comment by zealoussnow** [comment]
When I read the online document in http://docs.ceph.com/docs/master/rados/configuration/ceph-conf/, I found this problem.

**Comment by zealoussnow** [comment]
@tchaikov

**Comment by tchaikov** [comment]
http://docs.ceph.com/docs/master/architecture/#summary has a dead link. maybe you can help fix it also ?

**Comment by zealoussnow** [comment]
@tchaikov fixed dead link, wait for your review:)

**Comment by tchaikov** [comment]
@zealoussnow could you please squash these two commits into a single one?

**Pull request closed without merging**
