### PR TITLE
osd/PGLog: preserve original_crt to check rollbackability

### PR DESCRIPTION
**Pull request by neha-ojha**
Fixes: https://tracker.ceph.com/issues/21174
Signed-off-by: Neha Ojha <nojha@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by neha-ojha** [comment]
No related failures in rados run: http://pulpito.ceph.com/nojha-2019-03-26_00:22:37-rados-wip-21174-2-distro-basic-smithi/

Trying to see if I can reproduce http://tracker.ceph.com/issues/36598, which looks like a similar bug.

**Comment by neha-ojha** [comment]
> No related failures in rados run: http://pulpito.ceph.com/nojha-2019-03-26_00:22:37-rados-wip-21174-2-distro-basic-smithi/
> 
> Trying to see if I can reproduce http://tracker.ceph.com/issues/36598, which looks like a similar bug.

Does not reproduce http://pulpito.ceph.com/nojha-2019-03-26_19:04:14-kcephfs:thrash-master-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> Looks good! Shall we close #26347?

Done!

**Comment by Aran85** [comment]
do we need revert #26996 ?

**Comment by neha-ojha** [comment]
> do we need revert #26996 ?

I don't think so. https://github.com/ceph/ceph/pull/26996#issuecomment-476298088 still holds

**Comment by LiumxNL** [comment]
#https://github.com/ceph/ceph/pull/29590

**Pull request merged**
