### PR TITLE
mon: destroy-new -> purge-new

### PR DESCRIPTION
**Pull request by liewegas**
What we actually want is a purge, not a destroy.  Destroy leaves the OSD ID in place and allows it to be recreated.  What ceph-volume wants is to purge all trace of the failed OSD setup.

### CODE REVIEW

**Comment by alfredodeza** [comment]
Tested this manually, works as expected with ceph-volume. The osd count doesn't go up, and the ID gets picked back up again on subsequent iterations. Thanks sage!

    [root@node2 vagrant]# ceph -s
    ...
      services:
        mon: 1 daemons, quorum node2
        mgr: no daemons active
        osd: 7 osds: 1 up, 1 in
    
    $ ceph-deploy osd create --data /dev/sdh node9
    ...
    [node9][INFO  ] Running command: sudo /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [node9][WARNIN] -->  RuntimeError: command returned non-zero exit status: 5
    [node9][DEBUG ] Running command: /usr/bin/ceph-authtool --gen-print-key
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 3e173782-3b19-4ae9-96f2-3bd6598ad41e
    [node9][DEBUG ] Running command: /sbin/vgcreate --force --yes ceph-aeb90b72-1c77-42b0-a1fe-97979b1e8cca /dev/sdh
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Physical volume '/dev/sdh' is already in volume group 'ceph-6ea3112a-dd47-478d-bbf7-6977de447fbe'
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Unable to add physical volume '/dev/sdh' to volume group 'ceph-aeb90b72-1c77-42b0-a1fe-97979b1e8cca'.
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ] --> Was unable to complete a new OSD, will rollback changes
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.7 --yes-i-really-mean-it
    [node9][DEBUG ]  stderr: purged osd.7
    [node9][ERROR ] RuntimeError: command returned non-zero exit status: 1
    [ceph_deploy.osd][ERROR ] Failed to execute command: /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs
    
    $ ceph-deploy osd create --data /dev/sdh node9
    ...
    [node9][INFO  ] Running command: sudo /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [node9][WARNIN] -->  RuntimeError: command returned non-zero exit status: 5
    [node9][DEBUG ] Running command: /usr/bin/ceph-authtool --gen-print-key
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 3c9d71b7-bfb8-4b49-bf7e-d18798ece41e
    [node9][DEBUG ] Running command: /sbin/vgcreate --force --yes ceph-2c849aaa-211a-481d-8777-80f4c77bd2da /dev/sdh
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Physical volume '/dev/sdh' is already in volume group 'ceph-6ea3112a-dd47-478d-bbf7-6977de447fbe'
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ]  stderr: Unable to add physical volume '/dev/sdh' to volume group 'ceph-2c849aaa-211a-481d-8777-80f4c77bd2da'.
    [node9][DEBUG ]  stderr:
    [node9][DEBUG ] --> Was unable to complete a new OSD, will rollback changes
    [node9][DEBUG ] Running command: /usr/bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring osd purge-new osd.7 --yes-i-really-mean-it
    [node9][DEBUG ]  stderr: purged osd.7
    [node9][ERROR ] RuntimeError: command returned non-zero exit status: 1
    [ceph_deploy.osd][ERROR ] Failed to execute command: /usr/sbin/ceph-volume --cluster ceph lvm create --bluestore --data /dev/sdh
    [ceph_deploy][ERROR ] GenericError: Failed to create 1 OSDs
    
    [root@node2 vagrant]# ceph -s
    ...
      services:
        mon: 1 daemons, quorum node2
        mgr: no daemons active
        osd: 7 osds: 1 up, 1 in

**Comment by alfredodeza** [comment]
@liewegas I am a bit lost here, it seems this was never backported. And there is no issue tracker. Is this supposed to be in Mimic, Luminous? ceph-volume backported the calls to Mimic, but skipped on Luminous

**Comment by liewegas** [comment]
@alfredodeza whoops.  yeah, let's backport it.  Does that mean that ceph-volume in mimic is broken, or only broken in the case where something goes wrong and it tries to clean up?

**Comment by alfredodeza** [comment]
The latter. Only broken if something goes wrong and it tries to clean up

**Pull request merged**
