### PR TITLE
os/bluestore: inline immutable small object with onode

### PR DESCRIPTION
**Pull request by yanghonggang**
Fixes: https://tracker.ceph.com/issues/41417
Signed-off-by: Yang Honggang <yanghonggang@umcloud.com>

### CODE REVIEW

**Comment by markhpc** [comment]
@yanghonggang Igor was playing around with something similar a while back.  I think there's a good chance that we'll end up switching to a 4K min alloc size at the very least.  I think we're going to need to do a lot of testing to see if inlining smaller objects in the onode is actually a good idea.  We might be trading space amplification for much higher write amplification (I can see 22x+ on KV data with very large object counts).  It's quite possible that Adam's sharding work will mitigate some of that.  It's just going to require quite a bit of testing.

**Comment by xiexingguo** [comment]
FYI: Igor's version https://github.com/ceph/ceph/pull/23208

**Comment by yanghonggang** [comment]
> FYI: Igor's version #23208
ok, thank you

**Comment by ifed01** [comment]
as an author of the competing PR (#23208)  I wouldn't make final decision which approach is better. Will just provide their smoke comparison:
This PR (referred below as (I) - the **whole** object payload is inlined with onode and  hence is kept in a single KV record. 
My PR (#23208, referred below as (O)) - each tiny blob(extent) payload is kept as a standalone KV record.
- **PRO (I)** is simpler to implement.
- **PRO (I)** allows object metadata and payload retrieval from KV in a single shot.
- **CON (I)** keeping object payload along with onode makes caching less effective due to larger onode memory footprint.
- **CON (I)** needs special care (immutable flag specification) from the caller to enable the feature.
+ **PRO (O)** allows many "tiny" blobs, e.g. to support sparse object. Mixture of regular and tiny blobs is supported as well which allows better space utilization for e.g. unaligned objects.
+ **PRO (O)** allows partial overwrites and appends. (I) supports full overwrite only.

**Comment by yanghonggang** [comment]
@ifed01 @xiexingguo 

I think my PR(#30056) is a good solution to the problem of rgw small object space amplification :) :
- Inline small objects to db is not free, it will consume more cpu and memory, so only do it when really necessary
- We don't need to inline rbd object or those objects which will be appended later
- We should not transparently inline every objects that currently appears to be a small object
- Our original intention is to solve the rgw small object space amplification problem

I did a performance test with rados bench command, and the results are as follows:

object size(KB) |   | user data/disk space | IOPS avg 
-- | -- | -- | -- 
1 | default | 1.56% | 848 |  
1 | inline | 65.7% | 3720 | 
2 | default | 3.12% | 846 |  
2 | inline | 81.4% | 2978 |  
4 | default | 6.24% | 845 | 
4 | inline | 88.34% | 2554 | 
8 | default | 12.5% | 818 |  
9 | inline | 96.44% | 1687 |  
16 | default | 24.88% | 758 |  
16 | inline | 99.68% | 1036 |  
32 | default | 49.98% | 689 |  
32 | inline | 98.64% | 662 | 
64 | default | 99.3% | 2592 | 
64 | inline | 98.92% | 351 |

**Comment by yanghonggang** [comment]
> @yanghonggang How many objects did you test? One concern I have is that rocksdb write amplification grows significantly as the size of the DB grows. I'm a little concerned that we may see very good results with small OSDs but much larger ones may have significant problems (though Adam's sharding work might help here).
> 
> Has potential, but is going to need a significant amount of testing and should be compared with Igor's approach.

@markhpc 
For each object size, I ran a 900 seconds rados bench.
I rebuilt the ceph cluster before each test.
1024~1027M is space used after a cluster is newly created.

default:
`rados bench -p datapool -b {1024/2048/4096/8192/16384/32768/65536} -t 256 900 write --no-cleanup > def.log 2>&1 &`
inline:
`rados bench -p datapool -b {1024/2048/4096/8192/16384/32768/65536} -t 256 900 write --inline --no-cleanup > inline.log 2>&1 &`

object size(KB) |   | user data/disk space(MB) | total num of objs| IOPS avg
-- | -- | -- | -- | --
1 | default | 746/(48775-1027) = 1.56% |763904 | 848
1 | inline | 3370/(6157-1027) = 65.7% |3450880 | 3720
2 | default |1487/(48633-1027) = 3.12% |761344 |846
2 | inline | 5235/(7462-1027) = 81.4%| 2680320 |2978
4 | default | 2976/(48656-1027) = 6.24% |761856| 845
4 | inline | 8983/(11195-1027) = 88.34% | 2299648 |2554
8 | default | 5761/(47126-1027) = 12.5% |737408 |818
8 | inline | 11870/(13334-1027) = 96.44% |1519360 |1687
16 | default | 10780/(44357-1027) = 24.88% |689920| 758
16 | inline | 14584/(15657-1027) = 99.68% |933376| 1036
32 | default | 19449/(39943-1027) = 49.98% |622368| 689
32 | inline | 18635/(19918-1027) = 98.64% |596320| 662
64 | default | 142000/(144000-1027) = 99.3% |2272000| 2592
64 | inline | 19784/(21027-1027) = 98.92% |316544| 351

**Comment by markhpc** [comment]
Interesting to see those test results!  Any chance you could run a 4K or smaller test but instead of time based fill up a certain number of objects and then post the rados bench log so we can see how performance changes over time?  I typically run these kinds of tests with 64M objects, but that would take at least a couple of days to run on your setup, so maybe more like 16M (though that might not show the effect in full).

**Comment by yanghonggang** [comment]
@markhpc 

Actually I did the benchmark above with the ceph v12.2.5(**not ceph master**) with this patch applied about one year ago. This is a very time consuming test. Luckly I recorded the information you were concerned about.  

As you can see below, inline is expensive. It consumes more cpu and memory. 
So disable inline by default. Enable inline only when you more concerned about the disk space or you want a good performance.

And if your osd is one SSD, the performance of inline is low than default.

BW:

图片

CPU usage:

图片

Memory usage:

图片

Disk util of osd:

图片

**Pull request closed without merging**
