### PR TITLE
seastar: re-enable gate debug and fix race

### PR DESCRIPTION
**Pull request by NitzanMordhai**
Moving seastar sha1 to wip-nitzan-seastar-reenable-gate-debug

Fixes: https://tracker.ceph.com/issues/64332

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by Matan-B** [comment]
Ref: https://github.com/ceph/seastar/commits/wip-nitzan-seastar-reenable-gate-debug/

**Comment by cyx1231st** [comment]
I suppose the problematic gate is in AlienStore:
https://github.com/ceph/ceph/blob/42ecd4c8d767bd66a8ea331ddb0089de19e0ef95/src/crimson/os/alienstore/alien_store.h#L116

I think it is not approprite to add `std::mutex` into `seastar::gate`, the gate is not supposed be shared across seastar shards (refer to the shared-nothing design). How about introducing an `op_gate` for each seastar reactor in AlienStore, instead?

CC @tchaikov @athanatos

**Comment by NitzanMordhai** [comment]
> I suppose the problematic gate is in AlienStore:
> 
> https://github.com/ceph/ceph/blob/42ecd4c8d767bd66a8ea331ddb0089de19e0ef95/src/crimson/os/alienstore/alien_store.h#L116
> 
> I think it is not approprite to add `std::mutex` into `seastar::gate`, the gate is not supposed be shared across seastar shards (refer to the shared-nothing design). How about introducing an `op_gate` for each seastar reactor in AlienStore, instead?
> 
> CC @tchaikov @athanatos

that can work for the race condition as well, I'll create another PR with that suggestion and we can decide, thanks!

**Comment by NitzanMordhai** [comment]
closing as https://github.com/ceph/ceph/pull/58986 open to address it in different way

**Pull request closed without merging**
