### PR TITLE
rocksdb: sync with upstream

### PR DESCRIPTION
**Pull request by tchaikov**
to pick up
- bug fixes since 5.8.0
- crc32c_3way introduced in 5.9.0 for better performance on platforms
with PCLMULQDQ support.
- the fixes for silencing the fallthrough warnings when compiling with
GCC-7

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-11_11:18:50-rados-wip-kefu-testing-2018-04-11-1705-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2018-04-10_16:21:36-rados-wip-kefu-testing-2018-04-10-2058-distro-basic-mira/

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
assumine make check passes, lgtm

**Comment by tchaikov** [comment]
the -ENOSYS failures are known issues, see http://tracker.ceph.com/issues/23517.

will continue tracking down the nasty "make check" failures later on.

**Pull request merged**
