### PR TITLE
nautilus: global: ensure CEPH_ARGS is decoded before early arg processing

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/43997
* https://tracker.ceph.com/issues/44080

---

backport of 

- [x] https://github.com/ceph/ceph/pull/32830
- [x] https://github.com/ceph/ceph/pull/33187
- [x] https://github.com/ceph/ceph/pull/33219
- [x] https://github.com/ceph/ceph/pull/33243

parent trackers:

* https://tracker.ceph.com/issues/43795
* https://tracker.ceph.com/issues/44066

this backport was staged using ceph-backport.sh version 15.1.0.437
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
Will cherry-pick https://github.com/ceph/ceph/pull/33243 once it gets merged...

**Comment by smithfarm** [comment]
@dillaman I could not figure out how to cherry pick 1cb9e3b56932a1b00850b9cce4c65f8681dcc3cc from #33261 - OK to omit it?

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/PoolReplayer.cc: In member function 'void rbd::mirror::PoolReplayer<ImageCtxT>::start()':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/PoolReplayer.cc:660:7: error: 'm_default_namespace_replayer' was not declared in this scope
   if (m_default_namespace_replayer) {
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dillaman** [comment]
@smithfarm It's part of tracker ticket 41812.

@trociny Given that Octopus is due soon and backporting namespace support to rbd-mirror is non-trivial, does SUSE have any needs for that backport? If not, it's probably safer to just drop it.

**Comment by trociny** [comment]
> @trociny Given that Octopus is due soon and backporting namespace support to rbd-mirror is non-trivial, does SUSE have any needs for that backport? If not, it's probably safer to just drop it.

There is no any particular need. I just thought it would be nice to have so the "namespace" feature is entirely complete in Nautilus.  And I have not had a chance to start working on the backport yet. So I am ok with dropping it.

**Comment by dillaman** [comment]
> [1cb9e3](https://github.com/ceph/ceph/commit/1cb9e3b56932a1b00850b9cce4c65f8681dcc3cc)

This one would be master-unique since it's part of the new snapshot-based mirroring. OK to skip.

**Comment by smithfarm** [comment]
@dillaman Thanks - but #33243 is still open. I was going to cherry pick it, too, once it merges.

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-03-19-1610-nautilus](https://trello.com/c/LrERphRb/847-wip-yuri7-testing-2020-03-19-1610-nautilus)

**Pull request merged**
