### PR TITLE
rgw: added the interface to list objects by shard

### PR DESCRIPTION
**Pull request by liudan66ds**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by liudan66ds** [comment]
hi @cbodley do you mind help review this?

**Comment by cbodley** [comment]
thanks @liudan66ds. can you share more about the use case for this? the commit says something about lifecycle?

in general i think we'd prefer to *hide* bucket sharding from s3's view. there's no way for an s3 client to know how many shards there are, and the sharding scheme could change at any time

there are already a couple of ways that a system user (a user created with the `--system` flag) can list a specific shard:
* by adding the header `rgwx-shard-id: {shard-id}`: https://github.com/ceph/ceph/blob/9f0440e/src/rgw/rgw_rest_s3.cc#L1606-L1608
* by adding the query parameter `?rgwx-bucket-instance={bucket}:{instance-id}:{shard-id}`: https://github.com/ceph/ceph/blob/9f0440e/src/rgw/rgw_op.cc#L463-L466

outside of the REST API, you can also use `radosgw-admin bi list --bucket= --shard-id=` to list a specific shard. adding support for `--shard-id` to `radosgw-admin bucket list` would be easy to do as well

**Comment by liudan66ds** [comment]
Thank @cbodley. lifecycle deletion efficiency may sometimes be inadequate. If an lifecycle script is attached to assist deletion, this interface can improve efficiency.

**Comment by mattbenjamin** [comment]
hi @liudan66ds ;  The reason we want to avoid exposing bucket sharding to ordinary tooling, is that in future we might very well have indexing strategies that do not use sharding.  In terms of efficiency related to sharding as we have today, internal lc processing already operates on unordered listing, which enumerates object names in shard order.  It does this when you run "radosgw-admin lc process" as well as if RGW schedules lc internally.  If what you mean to do is delete or move objects by hand using the S3 api, you can still take advantage of unordered listing (add --allow-unordered to bucket list command, and there's even a header option you can add to S3 bucket listing to allow unordered).

**Pull request closed without merging**
