### PR TITLE
rgw: skip add empty multipart chain to gc in abort_multipart_upload

### PR DESCRIPTION
**Pull request by tianshan**
Fixes: https://tracker.ceph.com/issues/41953

Signed-off-by: Tianshan Qu <tianshan@xsky.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
Error: 

      72 |     });
      73 | 
    > 74 |     it('current active status of tabs should not change when selection is same with previour selection', () => {
         |     ^
      75 |       fixture.detectChanges();
      76 |       const tabs = poolDetailsComponent.tabsetChild.tabs;
      77 |       expect(tabs[0].active).toBeTruthy();
```

https://tracker.ceph.com/issues/41814

retest this please.

**Comment by cbodley** [comment]
@tianshan could you please rebase?

**Comment by cbodley** [comment]
@tianshan ping, please rebase

**Comment by tianshan** [comment]
@cbodley  sorry for late reply, rebase done.

**Comment by ivancich** [comment]
QA Results:
http://pulpito.ceph.com/ivancich-2020-05-08_18:24:50-rgw-wip-eric-testing-distro-basic-smithi/
http://pulpito.ceph.com/ivancich-2020-05-08_18:25:10-rgw-wip-eric-testing-distro-basic-smithi/

Any failures  are from other sources and do not represent regressions.

**Comment by ivancich** [comment]
@tianshan You did not list any backports on the tracker. So I marked it as "Resolved". If it needs backports please update the tracker and change the status to "Pending backport".

@mattbenjamin , @cbodley including you both in in case you have an opinion here.

**Comment by mattbenjamin** [comment]
@ivancich octopus and nautilus?

**Pull request merged**
