### PR TITLE
luminous: mgr/telemetry: critical backports and fixes

### PR DESCRIPTION
**Pull request by yaarith**
backport trackers:

* https://tracker.ceph.com/issues/44485
* https://tracker.ceph.com/issues/44504

---

This patch fixes several bugs in telemetry module in Luminous:

- catch exception during requests.put
  (backported: https://github.com/ceph/ceph/pull/33070)
- force --license when sending while opted-out
  (backported: https://github.com/ceph/ceph/pull/33747)
- wrong syntax of getting / setting config options, which caused 'ceph telemetry on' not to work, among other things.
- 'ceph telemetry off' now reset revision, hence when re-opting-in the license has to be re-agreed to.

Fixes: https://tracker.ceph.com/issues/44563
Signed-off-by: Yaarit Hatuka yaarit@redhat.com

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yaarith** [comment]
jenkins render docs

**Comment by l-mb** [comment]
LGTM!

**Comment by smithfarm** [comment]
Please consider adding a brief sentence to the two non-cherry-picked commits explaining why they cannot be cherry-picked from master?

**Comment by yaarith** [comment]
Thanks for the feedback!
@smithfarm sure, I amended the commits messages; sorry I forgot to update in a comment here.

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-04-20-1406-luminous](https://trello.com/c/emNHbbw6/874-wip-yuri8-testing-2020-04-20-1406-luminous)

**Comment by jecluis** [comment]
@yuriw did this PR end up going through a successful run?

**Comment by smithfarm** [comment]
luminous EOL

**Pull request closed without merging**
