### PR TITLE
WIP:  common: parse according to code_env and alias format for rados-cli

### PR DESCRIPTION
**Pull request by theanalyst**
Not completely sure whether this is the way yet.. here for review

The force option seems to be unused at the moment, removing it, also
this allows us to use the short flag alias `-f` for format, however since `-f` was already used by `foreground` by global_init this could be honored by moving global init after we parse arguments?

_EDIT_ Make description less confusing than it already is

### CODE REVIEW

**Comment by theanalyst** [comment]
In IRC @tchaikov suggested that we do this by making config.cc's `parse_argv` take up a code_env as well and we parse args like daemon/foreground etc only for the respective flag..

**Comment by theanalyst** [comment]
Added one more commit to do that.. Let me know if there are better ways of doing this .. (or if this is not relevant)  :)

**Comment by liewegas** [comment]
@theanalyst ping

**Comment by theanalyst** [comment]
I think this is outdated, the initial motivation was that we overrode a few flags like `-f`, `-d` and this wasn't relevant to tools like rados or rgw-admin for eg. , not sure whether this is still relevant

**Pull request closed without merging**
