### PR TITLE
[DNM] pacific: Update fio in pacific branch to fix make check failures

### PR DESCRIPTION
**Pull request by tchaikov**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Based on https://github.com/ceph/ceph/pull/47793/commits/5c73933c61e6f4b93499920a5a14412208394f9d, which was created to help with errors like:
```
	install -d debian/.debhelper/generated/python3-cephfs-dbg
dh_install: warning: Cannot find (any matches for) "usr/lib/python3*/site-packages/ceph_argparse.py" (tried in ., debian/tmp)

dh_install: warning: python3-ceph-argparse missing files: usr/lib/python3*/site-packages/ceph_argparse.py
dh_install: warning: Cannot find (any matches for) "usr/lib/python3*/site-packages/ceph_daemon.py" (tried in ., debian/tmp)

dh_install: warning: python3-ceph-argparse missing files: usr/lib/python3*/site-packages/ceph_daemon.py
dh_install: error: missing files, aborting
	install -d debian/.debhelper/generated/python3-ceph-argparse
	install -d debian/.debhelper/generated/python3-ceph-common
	install -d debian/.debhelper/generated/libcephfs-java
	install -d debian/.debhelper/generated/libcephfs-jni
	install -d debian/.debhelper/generated/rados-objclass-dev
	install -d debian/.debhelper/generated/cephfs-shell
	install -d debian/.debhelper/generated/cephfs-top
	install -d debian/.debhelper/generated/ceph-grafana-dashboards
	install -d debian/.debhelper/generated/ceph-prometheus-alerts
make: *** [debian/rules:61: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

It looks like we need to backport https://github.com/ceph/ceph/commit/c6c260f15beec0f3669d611892d1d7e579a819f0, or the whole PR it was part of: https://github.com/ceph/ceph/pull/42465

**Comment by ljflores** [comment]
@tchaikov originally built this branch here:  https://shaman.ceph.com/builds/ceph/wip-pacific-update-fio-kefu/5c73933c61e6f4b93499920a5a14412208394f9d/

I am rebuilding it here, since there were a number of build issues and I want to make sure they are reproducible: https://shaman.ceph.com/builds/ceph/tchaikov-wip-pacific-update-fio/44f3f2ab19d779641dcf5a58cd93cb37bf23985d/

**Comment by ljflores** [comment]
Here's what I'm seeing so far:

Focal (https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=focal,DIST=focal,MACHINE_SIZE=gigantic/65031/consoleFull#1394045954fa534114-2506-4c16-be9c-09c932a5aa49)
- Failed due to `dh_install: warning: Cannot find (any matches for) "usr/lib/python3*/dist-packages/ceph_volume_client.py" (tried in ., debian/tmp)`
- Should be fixed by backporting https://github.com/ceph/ceph/pull/42465

Bionic (https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=bionic,DIST=bionic,MACHINE_SIZE=gigantic/65031/consoleFull#1039243474ed6e825c-5772-40cc-ba3e-4f4430b3e036)
- Failed due to `CMakeFiles/Makefile2:9982: recipe for target 'src/tools/ceph-dencoder/CMakeFiles/ceph-dencoder.dir/all' failed`
- We have already tracked that failure here (https://tracker.ceph.com/issues/38629), which we deduced as a resource problem on one of the machines.
- Should be fixed by marking that machine down, for now

**Comment by ljflores** [comment]
I cherrypicked all 8 commits from https://github.com/ceph/ceph/pull/42465 onto a new branch, https://github.com/ljflores/ceph/tree/tchaikov-wip-pacific-update-fio-ceph-volume.

Trying out a build for that here: https://shaman.ceph.com/builds/ceph/tchaikov-wip-pacific-update-fio-ceph-volume/674d97b3c575bf9afdbb4e0f869fd72ec9d68d7a/

**Comment by ljflores** [comment]
> I cherrypicked all 8 commits from #42465 onto a new branch (@tchaikov it is based on your branch here), https://github.com/ljflores/ceph/tree/tchaikov-wip-pacific-update-fio-ceph-volume.
> 
> Trying out a build for that here: https://shaman.ceph.com/builds/ceph/tchaikov-wip-pacific-update-fio-ceph-volume/674d97b3c575bf9afdbb4e0f869fd72ec9d68d7a/

Even with the cherry-picks from #42465, we are still running into issues with ceph volume python packages:
```
dh_install: warning: python3-cephfs missing files: usr/lib/python3*/dist-packages/ceph_volume_client.py
	install -d debian/.debhelper/generated/python3-rgw
	install -d debian/.debhelper/generated/python3-rgw-dbg
	install -d debian/.debhelper/generated/python3-cephfs
	install -d debian/.debhelper/generated/python3-cephfs-dbg
dh_install: error: missing files, aborting
	install -d debian/.debhelper/generated/python3-ceph-argparse
	install -d debian/.debhelper/generated/python3-ceph-common
	install -d debian/.debhelper/generated/libcephfs-java
	install -d debian/.debhelper/generated/libcephfs-jni
	install -d debian/.debhelper/generated/rados-objclass-dev
	install -d debian/.debhelper/generated/cephfs-shell
	install -d debian/.debhelper/generated/cephfs-top
	install -d debian/.debhelper/generated/ceph-grafana-dashboards
	install -d debian/.debhelper/generated/ceph-prometheus-alerts
make: *** [debian/rules:40: binary] Error 25
```

@tchaikov any ideas?

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-pacific-update-fio-kefu-2/2735261e5158712fb2c421f567541fe0e9b98ee6/default/315431/

```
/build/ceph-16.2.10-678-g2735261e/src/osd/osd_types.h: In member function 'void object_ref_delta_t::mut_ref(const hobject_t&, int)':
/build/ceph-16.2.10-678-g2735261e/src/osd/osd_types.h:5551:35: warning: unused variable '_' [-Wunused-variable]
     [[maybe_unused]] auto [iter, _] = ref_delta.try_emplace(hoid, 0);
                                   ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
```
stopped by an ICE.

**Comment by tchaikov** [comment]
closing as #47696 includes all these changes.

**Pull request closed without merging**
