### PR TITLE
ceph-volume: show RBD devices as not available

### PR DESCRIPTION
**Pull request by mgfritch**
Avoid running `blkid` on RBD devices and ensure they don't appear as
an available device during `ceph-volume inventory`.

Fixes: https://tracker.ceph.com/issues/53846
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
jenkins test make check

**Review by tserong — APPROVED** [review]
LGTM, and works in my testing (in a vstart cluster, running `sudo ./ceph-volume-virtualenv/bin/ceph-volume inventory` with a couple of RBD devices mapped).

Note that we're still showing the devices in the inventory, we're just forcing them to appear unavailable. There might be an argument for not listing the devices at all, because they're not really devices in the sense of disks that are physically present in the system. OTOH, they _are_ devices in that the OS sees them as block devices, so from that perspective they're part of the inventory. I'm not sure I have a strong opinion either way.

**Comment by sebastian-philipp** [comment]
I mean given that ceph-volume also hides non-physical devices like loopback devices, we could argue for hiding them completely.

**Comment by guits** [comment]
@mgfritch what about the following change in `get_devices()` ?

```diff
diff --git a/src/ceph-volume/ceph_volume/util/disk.py b/src/ceph-volume/ceph_volume/util/disk.py
index 88db0513817..4b586224c69 100644
--- a/src/ceph-volume/ceph_volume/util/disk.py
+++ b/src/ceph-volume/ceph_volume/util/disk.py
@@ -759,7 +764,7 @@ def get_devices(_sys_block_path='/sys/block'):
     for block in block_devs:
         devname = os.path.basename(block[0])
         diskname = block[1]
-        if block[2] not in ['disk', 'mpath']:
+        if block[2] not in ['disk', 'mpath'] or is_ceph_rbd(block[0]):
             continue
         sysdir = os.path.join(_sys_block_path, devname)
         metadata = {}
```

**Comment by mgfritch** [comment]
@guits yeah that's much cleaner, I've updated the PR to simply exclude rbd devices from the inventory

**Review by guits — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
FYI for these make check runs: The first one had 

The following tests FAILED:
	 16 - run-tox-mgr-dashboard-openapi (Failed)
	 31 - run-rbd-unit-tests-1.sh (Failed)

The second one had:

The following tests FAILED:
	 53 - unittest_bufferlist (Failed)

so not even the same tests failing. Just have to keep rerunning I guess.

**Comment by adk3798** [comment]
jenkins test make check

**Comment by mgfritch** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test ceph api

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume tox

**Comment by RDominique** [comment]
I'm using quincy.

I still find rdb devices in the inventory.

Was this fix droped?

root@hvs001:/# ceph versions
{
    "mon": {
        "ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)": 3
    },
    "mgr": {
        "ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)": 2
    },
    "osd": {
        "ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)": 6
    },
    "mds": {
        "ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)": 2
    },
    "overall": {
        "ceph version 17.2.3 (dff484dfc9e19a9819f375586300b3b79d80034d) quincy (stable)": 13
    }
}

root@hvs001:/# rbd --pool libvirt-pool map --image PCVIRTdra
/dev/rbd0
root@hvs001:/# ceph-volume inventory

Device Path               Size         rotates available Model name
/dev/rbd0                 140.00 GB    False   False
/dev/sda                  894.25 GB    False   False     MZILS960HEHP/007
/dev/sdb                  894.25 GB    False   False     MZILS960HEHP/007

**Pull request merged**
