### PR TITLE
mgr/dashboard: CRUSH map viewer RFE

### PR DESCRIPTION
**Pull request by familyuu**
Fixes: http://tracker.ceph.com/issues/37794

Signed-off-by: familyuu <guodan1@lenovo.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by julienlim** [comment]
Thanks @familyuu for making these changes.  I added my comments at http://tracker.ceph.com/issues/37794.

**Comment by LenzGr** [comment]
Before:

peek 2019-01-28 16-01

After:

peek 2019-01-28 16-02

Looks good to me, thank you! Per our discussion on the tracker issue, please keep the object's status before the object name in the tree view.

**Comment by votdev** [comment]
Is it possible to expand/collapse a node on double click?

**Comment by votdev** [comment]
> > Is it possible to expand/collapse a node on double click?
> 
> No, do we need this feature?

I think this is a nice to have.

**Comment by LenzGr** [comment]
jenkins run make check

**Comment by LenzGr** [comment]
retest this please

**Pull request merged**
