### PR TITLE
mgr/dashboard: Module dashboard.services.ganesha has several lint issues

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/38267

Signed-off-by: Volker Theile <vtheile@suse.com>

- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test ceph dashboard tests

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
3 Jobs failed with different errors: http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/

**Comment by votdev** [comment]
> @callithea
> 
>     * [http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590819](http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590819/) -> could possibly be fixed by rerun
> 
>     * [http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590820](http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590820/) -> same here
> 
>     * [http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590821](http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590821/) -> http://tracker.ceph.com/issues/38265

Maybe we can skip QA because this PR contains only of adding comments, changing a typo in a string and a syntactical change how a set is defined in Python.

**Comment by callithea** [comment]
http://pulpito.ceph.com/laura-2019-02-15_11:37:35-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/
- the error of the failed job is not related to this PR

**Comment by callithea** [comment]
> @callithea
> 
>     * http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590819/ -> could possibly be fixed by rerun
> 
>     * http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590820/ -> same here
> 
>     * http://pulpito.ceph.com/laura-2019-02-14_10:59:29-rados:mgr-wip-lpaduano-testing-26378-distro-basic-mira/3590821/ -> http://tracker.ceph.com/issues/38265

@s0nea  the error message of ``Test failure: test_standby (tasks.mgr.test_dashboard.TestDashboard)`` is a bit different from the one within the tracker issue:
``ConnectionError: HTTPSConnectionPool(host='mira083.front.sepia.ceph.com', port=7791): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f70a36fdb50>: Failed to establish a new connection: [Errno 111] Connection refused',))``  - I'll create a new tracker issue for it.

**Pull request merged**
