### PR TITLE
pacific: python-common: improve OSD spec error messages

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #42905

### CODE REVIEW

**Review by mgfritch — APPROVED** [review]
Do we care to backport #42727 and it's dependent PRs before this PR to avoid losing track of these lines?

https://github.com/ceph/ceph/blob/24aab16cd065b39efb0ba7ff92d256e32593610b/src/python-common/ceph/deployment/drive_group.py#L336-L343

otherwise, lgtm!

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2022-01-18_15:34:53-rados:cephadm-wip-swagner2-testing-2022-01-18-1242-pacific-distro-default-smithi/

* nvme. fixed by Guillaume
* dashboard e2e

**Comment by sebastian-philipp** [comment]
> Do we care to backport #42727 and it's dependent PRs before this PR to avoid losing track of these lines?

I personally don't really care about raw osds in pacific. Do you?

**Comment by sebastian-philipp** [comment]
changelog:

* fixed trivial import conflicts

**Pull request merged**
