### PR TITLE
erasure-code: add --erased option to ceph_erasure_code_benchmark

### PR DESCRIPTION
**Pull request by dachary**
The --erased option specifies which chunks are erased when running the
decode workload. It is useful to precisely measure the code path
involved by a given recovery strategy. If only one chunk is missing
the code path won't be the same as if two chunks are missing.

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
It can be tested manually as follows:
<pre>
$ cd src ; make -j4 ceph_erasure_code_benchmark && ./ceph_erasure_code_benchmark --plugin isa --parameter directory=.libs --workload decode --verbose --parameter technique=reed_sol_van --parameter k=4 --parameter m=2 --erased 1 --erased 2
chunks  0  (1) (2)  3   4   5  (X) is an erased chunk
0.000217	1024
</pre>

**Comment by dachary** [comment]
@apeters1971 if it's not too much asking :-)

**Comment by apeters1971** [comment]
I am working on that ;-)

**Comment by dachary** [comment]
@apeters1971 thanks a lot :-)

**Comment by apeters1971** [comment]
So, this works ok, but you can give any numerical parameter and nobody complains "--erased 1000" "--erased -2". Maybe a detail.

**Comment by dachary** [comment]
@apeters1971 it's a developer tool, I guess it's not too bad if it's error detection capabilities are limited.

**Pull request merged**
