### PR TITLE
Remove some 'using namespace std' lines that crept back into headers

### PR DESCRIPTION
**Pull request by adamemerson**
Since a good bit of work was done to get them out, let's keep them out.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
could you add a "`Signed-off-by`" line at the end of your commit message? "git commit -s" will do the trick for you. see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#sign-your-work

**Comment by adamemerson** [comment]
Thanks. Sorry about that.

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
as long as this change is pushed to ceph-ci, and compiles, i think it's good to merge.

**Comment by adamemerson** [comment]
@tchaikov  https://shaman.ceph.com/builds/ceph/wip-no-using-namespace-std/636ea2382e83bee182c1aa76a5461cd83d001b5f/

Looks like everything builds fine except arm64.

But the arm64 failure looks like the same one that's happening for master (and looks to be broken packaging adjacent stuff, rather than a compilation failure.)

**Pull request merged**
