### PR TITLE
cls/cls_rbd: pass string by reference

### PR DESCRIPTION
**Pull request by lzhng2000**
Hi fellows,

This is my first contribution to Ceph and started by some low hanging fruits. I've run cppcheck to analysis the code.

This PR is trying to pass const std::string by its reference.

Hope that will match your quality criteria.

Signed-off-by: Jeffrey Lu <lzhng2000@hotmail.com>

### CODE REVIEW

**Comment by lzhng2000** [comment]
The PR is not as clean as possible for there are unnecessary merges. Maybe I'd try again in a branch instead of master

**Comment by liewegas** [comment]
Simply doing 'git rebase origin/master' should clear out the merge commits.

Also, note that your second commit doesn't have a Signed-off-by: line.

Also, please prefix the first line with the subsystem or module you are changing.  For example,

 cls/cls_rbd: pass string by reference
 
 Signed-off-by: ..

**Comment by lzhng2000** [comment]
@liewegas thanks for your insight. I have changed it.

**Comment by tchaikov** [comment]
lgtm.

**Pull request merged**
