### PR TITLE
qa/distros: pass --allowerasing --nobest when installing container-tools

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/57771

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-02-21_05:38:18-orch:cephadm-wip-adk-testing-2023-02-20-1650-distro-default-smithi/

failed/dead job reruns: https://pulpito.ceph.com/adking-2023-02-24_17:44:54-orch:cephadm-wip-adk-testing-2023-02-20-1650-distro-default-smithi/

After reruns, 3 failures and 1 dead job

- dead job was failure pulling a podman package
```
Failed to download packages: podman-docker-3:4.3.1-2.module_el8.8.0+1254+78119b6e.noarch:
  Cannot download, all mirrors were already tried without success
 ```
   Another instance of this test passed in original run so didn't bother with another rerun

- 2 failures were staggered upgrade test issue tracked by https://tracker.ceph.com/issues/58535
- last failure was in currently flaky test_nfs task test. Passed when I tried an interactive rerun for debugging

Overall, nothing to block merging. Will note initial version of basic monitoring stack test passed.

**Review by phlogistonjohn — APPROVED** [review]
Approved.

Nitpick: while it is great to include the tracker link, it can also be nice to include a short line inthe commit message explaining why. For example: "Works around a package conflict on rhel/centos 8"

**Comment by rkachach** [comment]
It seems that the solution [1] to this issue is to exclude `container-selinux-2:2.189.0`. I thinking by "forcing" the instalation may endup with broken packges. WDYT? Is this something Infra people can fix?


[1] https://bugs.launchpad.net/tripleo/+bug/1990810
[2] https://review.opendev.org/c/openstack/tripleo-quickstart/+/859213

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-03-06_16:09:09-orch:cephadm-wip-adk-testing-2023-03-04-1231-distro-default-smithi/

Failed/dead jobs reruns: https://pulpito.ceph.com/adking-2023-03-06_21:04:02-orch:cephadm-wip-adk-testing-2023-03-04-1231-distro-default-smithi/

After reruns, 6 failed, 2 dead jobs:

- 2 dead jobs were teuthology/infra issues (`Could not get lock /var/lib/dpkg/lock-frontend`, `SSH connection to smithi038 was lost`)
- 1 job failed installing a kernel `[Errno 2] No such file or directory: '/var/cache/dnf/CentOS-BaseOS-7c3d8b2bb640713c/packages/kernel-4.18.0-448.el8.x86_64.rpm'` unrelated to our tests
- 2 instances of https://tracker.ceph.com/issues/58535
- 3 jobs failed due to changes made to `ceph nfs cluster create` command in another PR in the run

Overall, should only block merging for PRs related to nfs

**Comment by adk3798** [comment]
jenkins test make check

**Pull request merged**
