### PR TITLE
qa/tests: added mimic-x-singleton suite to rados as symlink

### PR DESCRIPTION
**Pull request by yuriw**
to qa/upgrades/mimix-x-singleton
removed luminous-x-singleton

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
@yuriw see #27112

**Comment by yuriw** [comment]
I added `qa/releases/octopus.yaml`, assuming we will have it:
```
tasks:
- exec:
    osd.0:
      - ceph osd require-osd-release octopus
      - ceph osd set-require-min-compat-client octopus
- ceph.healthy:

```

**Comment by yuriw** [comment]
scheduling as:

CEPH_QA_MAIL="ceph-qa@lists.ceph.com"; MACHINE_NAME=smithi; CEPH_BRANCH=master

teuthology-suite -v --ceph-repo https://github.com/ceph/ceph.git --suite-repo https://github.com/yuriw/ceph.git  -c $CEPH_BRANCH -m $MACHINE_NAME -s rados/upgrade -k distro -p 90 -e $CEPH_QA_MAIL

http://pulpito.front.sepia.ceph.com:80/yuriw-2019-03-22_15:53:40-rados:upgrade-master-distro-basic-smithi/

**Comment by yuriw** [comment]
https://github.com/ceph/ceph/pull/27112 related

**Comment by badone** [comment]
jenkins test make check

**Comment by yuriw** [comment]
Replaced by https://github.com/ceph/ceph/pull/27253

**Pull request closed without merging**
