### PR TITLE
osd: trivial cleanup

### PR DESCRIPTION
**Pull request by dragonylffly**
Signed-off-by: Li Wang <li.wang@kylin-cloud.com>

### CODE REVIEW

**Comment by dragonylffly** [comment]
@tchaikov updated, with space added. According to PGBackend::be_select_auth_object(), even a
object such that auth.size != be_get_ondisk_size(auth_oi.size), it may still be selected as the 
authoritative object. Similarly, it happens on omap_digest and data_digest

**Comment by tchaikov** [comment]
@dragonylffly you are right, that's what we have for FIXME at https://github.com/ceph/ceph/blob/master/src/osd/PGBackend.cc#L493 .

**Comment by dragonylffly** [comment]
@tchaikov updated, with commit message revised

**Comment by tchaikov** [comment]
apart from a nit, lgtm.

**Comment by dragonylffly** [comment]
@tchaikov updated, with space added

**Pull request merged**
