### PR TITLE
Add mapping for ernno:13 and adding path in error msg in opendir()/cephfs.pyx

### PR DESCRIPTION
**Pull request by Sarthak0702**
CEPHFS_EACCES enum (Ernno:13) mapped to `PermissionDenied`  in `errno_to_exception` in cephfs.pyx.
`opendir()` now shows the path of file/folder in error message in cephfs.pyx.

Fixes: https://tracker.ceph.com/issues/54237
Signed-off-by: Sarthak0702 <sarthak.0702@gmail.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Sarthak0702** [comment]
jenkins test api

**Comment by Sarthak0702** [comment]
jenkins test api

**Review by batrick — APPROVED** [review]

**Review by pereman2 — APPROVED** [review]

**Review by avanthakkar — APPROVED** [review]

**Review by kotreshhr — APPROVED** [review]

**Comment by mchangir** [comment]
@Sarthak0702 could you paste the URL to the teuthology test run executed towards Developer Testing of this PR

**Comment by Sarthak0702** [comment]
teuthology URL: https://pulpito.ceph.com/vshankar-2022-03-14_08:09:40-fs-wip-vshankar-testing1-20220314-103400-testing-default-smithi/

**Comment by vshankar** [comment]
Haven't gone through the entire run, but libcephfs python binding test runs passed - https://pulpito.ceph.com/vshankar-2022-03-14_08:09:40-fs-wip-vshankar-testing1-20220314-103400-testing-default-smithi/6735978/

**Pull request merged**
