### PR TITLE
Crumb from STS/civetweb update (new title!)

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
[ not specifically related to STS but was tested with it.  Spin-off. All ceph related changes here; the civetweb used here comes from https://github.com/mdw-at-linuxbox/civetweb wip-easy1 ]

This links to a newer version of upstream civetweb (~v1.7 as of 2016-02-07).  There are patches on top of that to produce ceph required behavior, in a way that is hopefully can also be acceptable to upstream civetweb. ]

Updated version of civetweb.

### CODE REVIEW

**Comment by oritwas** [comment]
lgtm

**Comment by yehudasa** [comment]
@mdw-at-linuxbox need to get this through teuthology

**Comment by cbodley** [comment]
@mdw-at-linuxbox @pritha-srivastava regarding failures with chunked encoding, i looked at the civetweb branch (https://github.com/mdw-at-linuxbox/civetweb/commits/wip-easy1) and didn't see these related commits from our fork:
```
commit c39d732637a813ab5d4386a6167444dd6a235e82
Author: Yehuda Sadeh <yehuda@redhat.com>
Date:   Fri Aug 15 21:36:52 2014 -0700

    fix chunked transfer initialization

commit 2cd3759f97d3392fba64d1f999b1d2433a96bff8
Author: Ulrich Kramer <u.kramer@sap.com>
Date:   Fri Aug 15 11:36:47 2014 -0700

    [PATCH] Transfer encoding chunked
```
it may help to compare those with the upstream civetweb's implementation

**Comment by yehudasa** [comment]
@cbodley @pritha-srivastava looking at the civetweb code this branch is based on, I do see  chunked transfer support (looks like it's based on the same code we were using).

**Comment by mdw-at-linuxbox** [comment]
I've updated this PR.  Since most of the civetweb stuff went in, this crumb was left (in STS).  Adam originally did this to fix a problem (or warning) building civetweb.  I don't know if it's still useful or necessary.  So, I assigned some people - discuss!

**Comment by yehudasa** [comment]
@mdw-at-linuxbox not sure about the commit itself, but please make a more descriptive title to this PR

**Comment by cbodley** [comment]
would prefer not to add this unless it's absolutely necessary. touching that header forces a complete rebuild, which would be a major inconvenience when switching between branches

**Comment by mdw-at-linuxbox** [comment]
I talked with Adam on this.  He created this patch because, at the time, something related to .c or civetweb was pulling in the wrong assert.h and failing to build.  According to him, if it builds, this patch is not necessary.  This may have been related to old automake logic which we don't have anymore.  And certainly the other other ceph PR's I pushed at the same time of this which don't have this build.  So, it seems clear this is no longer necessary, so I'm going to close this (& remove the patch out of my STS work.)

**Pull request closed without merging**
