### PR TITLE
rgw: set default objecter_inflight_ops = 24576

### PR DESCRIPTION
**Pull request by mattbenjamin**
Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
Matt would you please open a tracker.ceph.com ticket so we ensure this is backported to luminous?

**Comment by ktdreyer** [comment]
Whoops, I see it's http://tracker.ceph.com/issues/25109 :)

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by mattbenjamin** [comment]
@cbodley requests verification that these defaults override mon-stored defaults

**Pull request merged**
