### PR TITLE
mgr/dashboard: fix unmanaged service creation

### PR DESCRIPTION
**Pull request by nizamial09**
Fixes
1. Ingress unmanaged service creation
2. iSCSI unmanaged service creation
3. snmp unmanaged service creation

the following snipped is the error from backend

```
 File "/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 698, in _from_json_impl
                                                  _cls.validate()
                                                File "/lib/python3.6/site-packages/ceph/deployment/service_spec.py", line 1058, in validate
                                                  'Cannot add ingress: No frontend_port specified')
                                              ceph.deployment.hostspec.SpecValidationError: Cannot add ingress: No frontend_port specified
```

It looks like even if we set unmanaged flag, we need to input the
backend_service, frontend_port, monitor_port and virtual_ip, because there is a
validation going for that in the backend.

https://github.com/ceph/ceph/blob/main/src/python-common/ceph/deployment/service_spec.py#L1050

AFTER
**INGRESS**
scrnli_24_08_2022_12-33-44
scrnli_24_08_2022_12-33-15

**ISCSI**
scrnli_24_08_2022_15-16-40

**SNMP-v3**
scrnli_24_08_2022_15-17-02

**SNMP-v2c**
scrnli_24_08_2022_15-17-23

Fixes: https://tracker.ceph.com/issues/57284
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
@avanthakkar pointed it out to me that apart from the ingress services like iscsi and snmp-gateway faces this issue. so adding the fixes for them too.

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Review by aaSharma14 — APPROVED** [review]

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by aaSharma14** [comment]
jenkins test dashboard cephadm

**Comment by epuertat** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test windows

**Comment by nizamial09** [comment]
the applitools is failing after several retries and accepting https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/11648/
```
Error: Eyes-Cypress detected diffs or errors during execution of visual tests. See details at: https://eyes.applitools.com/app/batches/00000251739600734755/00000251739600734614?accountId=hCTedwnSTUWSCZlXPqua0g~~
       Passed - 4 tests
         ✓ Login Component Check [1920x1080]
         ✓ Login Component Check [1920x1080]
         ✓ Login Component Check [800x600]
         ✓ Login Component Check [800x600]
       Diffs detected - 4 tests
         ⚠ Dashboard Component [1920x1080]
         ⚠ Dashboard Component [1920x1080]
         ⚠ Dashboard Component [800x600]
         ⚠ Dashboard Component [800x600]

       See details at: https://eyes.applitools.com/app/batches/00000251739600734755/00000251739600734614?accountId=hCTedwnSTUWSCZlXPqua0g~~


    at /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/@applitools/eyes-cypress/src/plugin/waitForBatch.js:26:13
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.handler (/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/src/pybind/mgr/dashboard/frontend/node_modules/@applitools/eyes-cypress/src/plugin/hooks.js:35:7)
```

**Pull request merged**
