### PR TITLE
mgr/insights: use dedicated tox working dir

### PR DESCRIPTION
**Pull request by noahdesu**
Avoids conflicting with other test environments.

Signed-off-by: Noah Watkins <nwatkins@redhat.com>

### CODE REVIEW

**Comment by noahdesu** [comment]
@jmolmo this look ok?

**Comment by jmolmo** [comment]
> @jmolmo this look ok?

Yes.The modfication is the same i did with ansible... but it seems that it will be needed to apply the same "patch" to dashboard. Not too much information about what is the error. Can you add the same modification to the dashboard tox working dir?

**Comment by jmolmo** [comment]
jenkins retest this please

**Comment by noahdesu** [comment]
@LenzGr the little one line patch in this PR sets the tox testing for the insights manager module to use a dedicated directory. we discovered this need when running tests for the orchestrator module that needed to avoid conflicts between the testing environments.

both of these cases are much simpler than the testing setup used by the dashboard. do you see much issue with adding a similar patch to dashboard?

**Comment by tchaikov** [comment]
@noahdesu i am merging this change. because currently dashboard's tox envs are using a different naming scheme: they have `-cov` and `-lint` postfixes.

so they are not likely to have name conflict with other tox envs used in Ceph. but it'd be ideal if we do not rely on this fact and have dedicated envs for different `tox.ini` if they are not intended to be shared.

**Comment by LenzGr** [comment]
> both of these cases are much simpler than the testing setup used by the dashboard. do you see much issue with adding a similar patch to dashboard?

@noahdesu I don't think this would cause any issue, but let me add @sebastian-philipp and @rjfd to comment on that.

**Comment by sebastian-philipp** [comment]
I'd be :+1: for adding this to the dashboard as well.

**Comment by LenzGr** [comment]
> I'd be +1 for adding this to the dashboard as well.

Thanks, @sebastian-philipp - I created https://tracker.ceph.com/issues/37405 to track this.

**Comment by LenzGr** [comment]
#25290 contains the dashboard change.

**Pull request merged**
