### PR TITLE
qa/upgrade: rgw multisite upgrade test excludes ceph-volume

### PR DESCRIPTION
**Pull request by cbodley**
> E: Unable to locate package ceph-volume

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
tests pending in https://pulpito.ceph.com/cbodley-2021-11-05_18:00:23-upgrade:octopus-x:rgw-multisite-wip-cbodley-testing-distro-basic-smithi/

**Comment by neha-ojha** [comment]
> https://pulpito.ceph.com/cbodley-2021-11-05_18:00:23-upgrade:octopus-x:rgw-multisite-wip-cbodley-testing-distro-basic-smithi/

@cbodley These seems to be failing :( but I also noticed you force-pushed, are the tests passing now?

**Comment by cbodley** [comment]
thanks for the reminder, i don't think i retested that. pending in https://pulpito.ceph.com/cbodley-2021-11-17_18:39:53-upgrade:octopus-x:rgw-multisite-wip-cbodley-testing-distro-basic-smithi/

**Comment by cbodley** [comment]
ok, its working after i excluded it from the install.upgrade task too

https://pulpito.ceph.com/cbodley-2021-11-17_19:38:38-upgrade:octopus-x:rgw-multisite-wip-cbodley-testing-distro-basic-smithi/

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
@neha-ojha @yuriw may i kindly ask your approval on this? ❤️

**Comment by cbodley** [comment]
this just needs an approval to merge. the teuthology results in https://pulpito.ceph.com/cbodley-2021-11-17_19:38:38-upgrade:octopus-x:rgw-multisite-wip-cbodley-testing-distro-basic-smithi/ show that we're getting the normal multisite failures, instead of failing the install with `Unable to locate package ceph-volume`

**Review by ivancich — APPROVED** [review]

**Pull request merged**
