### PR TITLE
qa/tasks: use list comprehension for checking the length

### PR DESCRIPTION
**Pull request by tchaikov**
instead of using filter(), use list comprehension for checking its
length, as in Python3, `filter()` actually returns a `filter` object
instead of a list.

in this change, `filter()` calls are replaced with list comprehension
for Python3 compatibility.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change addresses the failure of 
```
2020-04-30T09:31:47.348 INFO:teuthology.orchestra.run.smithi081.stderr:2020-04-30 09:31:47.342 7f981256f700  1 -- 172.21.15.81:0/4130337808 wait complete.
2020-04-30T09:31:47.354 ERROR:tasks.mds_thrash.fs.[cephfs]:exception:
Traceback (most recent call last):
  File "/home/teuthworker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/mds_thrash.py", line 229, in _run
    self.do_thrash()
  File "/home/teuthworker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/mds_thrash.py", line 414, in do_thrash
    status = self.wait_for_stable(rank, gid)
  File "/home/teuthworker/src/github.com_tchaikov_ceph_nautilus-py3/qa/tasks/mds_thrash.py", line 297, in wait_for_stable
    if not bool(self.config.get('thrash_while_stopping', False)) and len(stopping) > 0:
TypeError: object of type 'filter' has no len()
2020-04-30T09:31:48.459 INFO:teuthology.orchestra.run.smithi081:> true
```

the test was performed with nautilus-py3 branch. see #34171. but the same issue also exists on master.

**Comment by tchaikov** [comment]
changelog

- updated per @kshtsk 's suggestion at #34171

**Comment by kshtsk** [comment]
@tchaikov you forgot to replace: `len(stopping)` with `stopping` and `len(actives)` with `active`.

**Comment by tchaikov** [comment]
> @tchaikov you forgot to replace: `len(stopping)` with `stopping` and `len(actives)` with `active`.

@kshtsk thanks. fixed and repushed.

**Comment by batrick** [comment]
@tchaikov is there not a tracker ticket for this?

**Comment by tchaikov** [comment]
@batrick no, not yet. i expected to fix these py3 related issues in a stealth mode -- quietly and quickly. but was stalled by things like labour day, ubuntu/focal upgrade, teuthology regressions (yeah, i stepped onto my own toes this time).

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-05-13_02:18:33-fs-wip-kefu-testing-2020-05-05-1333-distro-basic-smithi/

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2020-05-13_03:08:27-multimds-octopus-distro-basic-smithi/

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2020-05-13_03:09:43-multimds-octopus-distro-basic-smithi/

**Comment by tchaikov** [comment]
at least 2 tests in http://pulpito.ceph.com/pdonnell-2020-05-13_03:09:43-multimds-octopus-distro-basic-smithi/ passed. the failed ones are tracked by https://tracker.ceph.com/issues/45438

**Pull request merged**
