### PR TITLE
squid: client: check mds down status before getting mds_gid_t from mdsmap   

### PR DESCRIPTION
**Pull request by YiteGu**
backport tracker: https://tracker.ceph.com/issues/64606

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by joscollin — CHANGES_REQUESTED** [review]
There are no backport trackers for this. Can't do QA for this PR. Please fix it.

**Comment by YiteGu** [comment]
> There are no backport trackers for this. Can't do QA for this PR. Please fix it.

This PR had tracker(https://tracker.ceph.com/issues/64606), How to let QA know it?

**Comment by joscollin** [comment]
> > There are no backport trackers for this. Can't do QA for this PR. Please fix it.
> 
> This PR had tracker(https://tracker.ceph.com/issues/64606), How to let QA know it?

You need to update the trackers appropriately. Look at other PRs how it's done. 
I think this PR needs a dashboard QA rather than fs suite.

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
> I think this PR needs a dashboard QA rather than fs suite.

we rely mostly on the jenkins dashboard e2es for approving the PR. If that passes then I don't have any issues with merging this one.

Btw @YiteGu you'll need to update the descriptions with proper trackers. You can check [these examples](https://github.com/ceph/ceph/pull/58337) on how it look like. There's also [a guide that describes](https://github.com/ceph/ceph/blob/main/SubmittingPatches-backports.rst) the process which says about a `ceph-backport.sh` script that kind of automates everything for you.

**Comment by YiteGu** [comment]
> > I think this PR needs a dashboard QA rather than fs suite.
> 
> we rely mostly on the jenkins dashboard e2es for approving the PR. If that passes then I don't have any issues with merging this one.
> 
> Btw @YiteGu you'll need to update the descriptions with proper trackers. You can check [these examples](https://github.com/ceph/ceph/pull/58337) on how it look like. There's also [a guide that describes](https://github.com/ceph/ceph/blob/main/SubmittingPatches-backports.rst) the process which says about a `ceph-backport.sh` script that kind of automates everything for you.

created new backport PR by `ceph-backport.sh`, close this.

**Pull request closed without merging**
