### PR TITLE
[DNM] jewel: RGW: fix a bug about inconsistent unit of comparison

### PR DESCRIPTION
**Pull request by mattbenjamin**
Fixes：http://tracker.ceph.com/issues/21590

Signed-off-by: gaosibei <gaosb@inspur.com>
(cherry picked from commit cb39f065d6eba87cf1fc2e99334322bf63092df3)
Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test this please

**Comment by smithfarm** [comment]
Build failure:

```
In file included from rgw/rgw_formats.cc:18:0:
./rgw/rgw_formats.h: In constructor ‘RGWFormatter_Plain::RGWFormatter_Plain(bool)’:
./rgw/rgw_formats.h:59:8: warning: ‘RGWFormatter_Plain::wrote_something’ will be initialized after [-Wreorder]
   bool wrote_something;
        ^
./rgw/rgw_formats.h:57:10: warning:   ‘size_t RGWFormatter_Plain::min_stack_level’ [-Wreorder]
   size_t min_stack_level;
          ^
rgw/rgw_formats.cc:24:1: warning:   when initialized here [-Wreorder]
 RGWFormatter_Plain::RGWFormatter_Plain(const bool ukv)
 ^
  CXX      rgw/librgw_la-rgw_loadgen.lo
  CXX      rgw/librgw_la-rgw_log.lo
  CXX      rgw/librgw_la-rgw_metadata.lo
  CXX      rgw/librgw_la-rgw_multi.lo
  CXX      rgw/librgw_la-rgw_multi_del.lo
  CXX      rgw/librgw_la-rgw_auth_s3.lo
  CXX      rgw/librgw_la-rgw_period_history.lo
  CXX      rgw/librgw_la-rgw_period_puller.lo
  CXX      rgw/librgw_la-rgw_period_pusher.lo
  CXX      rgw/librgw_la-rgw_realm_reloader.lo
  CXX      rgw/librgw_la-rgw_realm_watcher.lo
  CXX      rgw/librgw_la-rgw_sync.lo
  CXX      rgw/librgw_la-rgw_data_sync.lo
  CXX      rgw/librgw_la-rgw_object_expirer_core.lo
  CXX      rgw/librgw_la-rgw_op.lo
  CXX      rgw/librgw_la-rgw_os_lib.lo
  CXX      rgw/librgw_la-rgw_policy_s3.lo
  CXX      rgw/librgw_la-rgw_process.lo
  CXX      rgw/librgw_la-rgw_quota.lo
  CXX      rgw/librgw_la-rgw_rados.lo
  CXX      rgw/librgw_la-rgw_replica_log.lo
  CXX      rgw/librgw_la-rgw_request.lo
rgw/rgw_quota.cc: In member function ‘virtual bool RGWQuotaCache<T>::can_use_cached_stats(RGWQuotaInfo&, RGWStorageStats&)’:
rgw/rgw_quota.cc:110:22: error: ‘struct RGWStorageStats’ has no member named ‘size_rounded’
     if (cached_stats.size_rounded  >= (uint64_t)quota.max_size_soft_threshold) {
                      ^
rgw/rgw_quota.cc:112:25: error: ‘struct RGWStorageStats’ has no member named ‘size_rounded’
         << cached_stats.size_rounded << " >= " << quota.max_size_soft_threshold << dendl;
                         ^
Makefile:24781: recipe for target 'rgw/librgw_la-rgw_quota.lo' failed
```

**Comment by smithfarm** [comment]
@mattbenjamin Can you look at the build failure above?

**Comment by mattbenjamin** [comment]
@smithfarm there's no trivial version of this change on Jewel;  I think this PR should just be closed.

**Pull request closed without merging**
