### PR TITLE
cephadm: init config and keyring with None

### PR DESCRIPTION
**Pull request by mgfritch**
and we should not assume that both `config` and `keying` are specified
when calling this method. because, for instance, `create_daemon_dirs()`
does handle the case where `config` and/or `keyring` is not specified.

this is a follow-up fix of 245d6a5cec9cc0f299613b8cc0415e494a4c3ac5

Signed-off-by: Kefu Chai <kchai@redhat.com>
Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
fixes traceback when no config/keyring specified:

```
Traceback (most recent call last):
  File "/root/cephadm", line 4247, in <module>
    r = args.func()
  File "/root/cephadm", line 935, in _infer_fsid
    return func()
  File "/root/cephadm", line 2603, in command_ceph_volume
    (config, keyring) = get_config_and_keyring()
  File "/root/cephadm", line 1358, in get_config_and_keyring
    if not config:
UnboundLocalError: local variable 'config' referenced before assignment
```

**Comment by sebastian-philipp** [comment]
#34102

**Comment by bk201** [comment]
tested locally and works, no longer see the referenced before assignment issue.

**Comment by sebastian-philipp** [comment]
Backport depends on #34168

**Pull request merged**
