### PR TITLE
cephadm: Don't call prepare-host from bootstrap

### PR DESCRIPTION
**Pull request by sebastian-philipp**
bootstrapping the cluster and installing rpms on the host are two dfferent things.

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

Fixes:

```
Traceback (most recent call last):
  File "/usr/sbin/cephadm", line 3395, in <module>
    r = args.func()
  File "/usr/sbin/cephadm", line 1654, in command_bootstrap
    command_prepare_host()
  File "/usr/sbin/cephadm", line 2627, in command_prepare_host
    pkg = create_packager()
  File "/usr/sbin/cephadm", line 2948, in create_packager
    raise Error('Distro %s version %s not supported' % (distro, version))
__main__.Error: Distro opensuse-leap version 15.2 not supported
```

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Can we get this in, and then later fix the issue properly?

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/33443

**Comment by mgfritch** [comment]
> Instead, I think we should fix prepare_host to not create the Packager unless it will need it.

Seems like there is merit in adding a cmdline flag to turn this behavior on if/when desired. 

For me it makes more sense for bootstrap to fail with a contextual message and let me choose which package I want to install -- for example maybe I prefer ntp over chrony ...

**Comment by bk201** [comment]
+1 for this change.
Allow users calling `prepare_host` only when needed.
On some systems, the user might already prepare repos and installe required packages beforehand.

**Comment by liewegas** [comment]
I think a --skip-prepare-host flag or similar makes sense.  I think it should prepare by default, though, or else we're needlessly adding another step to the install process.

**Pull request closed without merging**
