### PR TITLE
ceph-volume: update functional testing

### PR DESCRIPTION
**Pull request by guits**
various changes for fixing ceph-volume functional testing:

### CODE REVIEW

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test ceph-volume lvm centos-bluestore-dmcrypt

**Comment by guits** [comment]
jenkins test windows

**Comment by guits** [comment]
jenkins test ceph-volume all

**Comment by guits** [comment]
jenkins test ceph-volume all

**Review by Svelar — APPROVED** [review]
LGTM

**Pull request merged**
