### PR TITLE
luminous: rgw: add support for Swift's per storage policy statistics

### PR DESCRIPTION
**Pull request by rzarzynski**
http://tracker.ceph.com/issues/21460
http://tracker.ceph.com/issues/21649

This is the luminous backport of PR #12704. It incorporates commits from the backport #17834 as dependencies.

### CODE REVIEW

**Comment by smithfarm** [comment]
@rzarzynski Instead of duplicating commits between backport PRs, we typically just merge the interdependent backports into a single PR. But this should be fine as it is.

**Comment by rzarzynski** [comment]
Teuthology run: http://pulpito.ceph.com/rzarzynski-2017-09-20_14:57:33-rgw-wip-swift-testing-luminous---basic-smithi.

**Comment by smithfarm** [comment]
Quoting from the tracker:

> this feature caused a regression in multisite sync - please don't merge this backport without a corresponding fix for http://tracker.ceph.com/issues/21506

**Comment by cbodley** [comment]
thanks @smithfarm. the fix for http://tracker.ceph.com/issues/21506 is merged to master and ready for luminous backport

**Comment by smithfarm** [comment]
@cbodley So @rzarzynski could just cherry-pick 3f4f760a85f162262c5b419e9cf78966c7299f0a into this PR?

**Comment by cbodley** [comment]
> So @rzarzynski could just cherry-pick 3f4f760 into this PR?

yes please!

**Comment by rzarzynski** [comment]
@cbodley, @smithfarm: cherry-picked. :-)

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by smithfarm** [comment]
> I can't merge cleanly due to the doc build failure

This PR doesn't touch any doc code, though?

**Comment by cbodley** [comment]
jenkins build docs

**Comment by cbodley** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
@alfredodeza @tchaikov Any idea what to do about the following Jenkins doc test failure?

```
+ ./admin/build-doc
Traceback (most recent call last):
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/gen_state_diagram.py", line 205, in <module>
    RENDERER.read_input(INPUT_GENERATOR)
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/gen_state_diagram.py", line 87, in read_input
    self.get_event(line)
  File "/home/jenkins-build/build/workspace/ceph-pr-docs/doc/scripts/gen_state_diagram.py", line 139, in get_event
    raise "no context at line: " + line
TypeError: exceptions must be old-style classes or derived from BaseException, not str
Build step 'Execute shell' marked build as failure
```

**Comment by smithfarm** [comment]
Just a wild guess . . . the Jenkins doc test for luminous appears to has been failing since around the time https://github.com/ceph/ceph/pull/18167 was merged?

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
@smithfarm no. it's more likely https://github.com/ceph/ceph/commit/27e14504f6c4b7a8e06b038fc396c40e8e6c1456. anyway, could you help test/review #18339?

**Pull request merged**
