### PR TITLE
doc: Remove redundant words in docs

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: mooncake <xcoder@tenxcloud.com>

Remove redundant words in doc

- [ ] References tracker ticket
- [-] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by batrick** [comment]
@mooncak the new title is fine but you need to amend your commit message too.

**Comment by mooncak** [comment]
> @mooncak the new title is fine but you need to amend your commit message too.

ok, done.

**Comment by joscollin** [comment]
@mooncak 

Please see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work. `mooncake <xcoder@tenxcloud.com>` looks like a pseudonym.

**Comment by joscollin** [comment]
@mooncak You just need to update as `Real Name <xcoder@tenxcloud.com>` in 'Signed-off-by:`

**Pull request closed without merging**
