### PR TITLE
qa/standalone/mon: Fix mkfs  test & TEST_LOG failures

### PR DESCRIPTION
**Pull request by kamoltat**
Fixing various failures in MON standalone test, e.g.,

test case involving mkfs command
and monitor + journal logs.

Fixes: https://tracker.ceph.com/issues/63784

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by kamoltat** [comment]
Running the job with:

```
teuthology-suite -v --ceph main --ceph-repo https://github.com/ceph/ceph-ci.git --suite-repo https://github.com/kamoltat/ceph.git --suite-branch wip-ksirivad-fix-63784 --rerun yuriw-2024-06-20_13:41:02-rados-wip-yuri11-testing-2024-06-19-1425-distro-default-smithi --filter-all "rados/standalone/{supported-random-distro$/{centos_latest} workloads/mon}" -S 4d5b2cdc1652f11ae8427a46b6b5f82112c34208 --machine-type smithi --priority 50 --force-priority
```

https://pulpito.ceph.com/ksirivad-2024-06-27_19:24:56-rados-main-distro-default-smithi/7776583/

**Comment by kamoltat** [comment]
Looked like with the new fix, we were able to get pass the part that threw the error

```
7T19:50:45.188 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:34: setup:  mkdir mkfs
2024-06-27T19:50:45.189 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:183: run:  auth_cephx_key
2024-06-27T19:50:45.189 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:122: auth_cephx_key:  '[' -f /etc/ceph/keyring ']'
2024-06-27T19:50:45.190 INFO:tasks.workunit.client.0.smithi159.stderr://home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:127: auth_cephx_key:  ceph-authtool --gen-print-key
2024-06-27T19:50:45.206 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:127: auth_cephx_key:  local key=AQCVwn1mJ9ikDBAAKxsDG6FaMCB2NhZs+ZTGiA==
2024-06-27T19:50:45.206 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:129: auth_cephx_key:  mon_mkfs '--key=corrupted key'
2024-06-27T19:50:45.207 INFO:tasks.workunit.client.0.smithi159.stderr://home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:43: mon_mkfs:  uuidgen
2024-06-27T19:50:45.207 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:43: mon_mkfs:  local fsid=59fc0e56-c05c-4aa8-91d8-4f618213b713
2024-06-27T19:50:45.207 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:46: mon_mkfs:  ceph-mon --id a --fsid 59fc0e56-c05c-4aa8-91d8-4f618213b713 --mkfs --mon-data=mkfs/a --mon-initial-members=a --mon-host=127.0.0.1:7110 '--key=corrupted key'
2024-06-27T19:50:45.587 INFO:tasks.workunit.client.0.smithi159.stderr:2024-06-27T19:50:45.592+0000 7f7c4e83ab00 -1 mon.a@-1(???) e0 error decoding keyring [mon.]
2024-06-27T19:50:45.587 INFO:tasks.workunit.client.0.smithi159.stderr:  key = corrupted key
2024-06-27T19:50:45.587 INFO:tasks.workunit.client.0.smithi159.stderr:  caps mon = "allow *"
2024-06-27T19:50:45.587 INFO:tasks.workunit.client.0.smithi159.stderr:: error setting modifier for [mon.] type=key val=corrupted key: Malformed input [buffer:3]
2024-06-27T19:50:45.587 INFO:tasks.workunit.client.0.smithi159.stderr:2024-06-27T19:50:45.592+0000 7f7c4e83ab00 -1 ceph-mon: error creating monfs: (22) Invalid argument
2024-06-27T19:50:45.588 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:132: auth_cephx_key:  rm -fr mkfs/a
2024-06-27T19:50:45.589 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:135: auth_cephx_key:  mon_mkfs --key=AQCVwn1mJ9ikDBAAKxsDG6FaMCB2NhZs+ZTGiA==
2024-06-27T19:50:45.589 INFO:tasks.workunit.client.0.smithi159.stderr://home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:43: mon_mkfs:  uuidgen
2024-06-27T19:50:45.590 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:43: mon_mkfs:  local fsid=1df7b65a-90f6-49a3-b279-1cae22df4c30
2024-06-27T19:50:45.590 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:46: mon_mkfs:  ceph-mon --id a --fsid 1df7b65a-90f6-49a3-b279-1cae22df4c30 --mkfs --mon-data=mkfs/a --mon-initial-members=a --mon-host=127.0.0.1:7110 --key=AQCVwn1mJ9ikDBAAKxsDG6FaMCB2NhZs+ZTGiA==
2024-06-27T19:50:46.043 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:137: auth_cephx_key:  '[' -f mkfs/a/keyring ']'
2024-06-27T19:50:46.043 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:138: auth_cephx_key:  grep AQCVwn1mJ9ikDBAAKxsDG6FaMCB2NhZs+ZTGiA== mkfs/a/keyring
2024-06-27T19:50:46.043 INFO:tasks.workunit.client.0.smithi159.stdout:  key = AQCVwn1mJ9ikDBAAKxsDG6FaMCB2NhZs+ZTGiA==
2024-06-27T19:50:46.044 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:140: auth_cephx_key:  mon_run
2024-06-27T19:50:46.044 INFO:tasks.workunit.client.0.smithi159.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mkfs.sh:58: mon_run:  ceph-mon --id a --chdir= --mon-osd-full-ratio=.99 --mon-data-avail-crit=1 --mon-data=mkfs/a --log-file=mkfs/a/log --mon-cluster-log-file=mkfs/a/log --run-dir=mkfs/a --pid-file=mkfs/a/pidfile --public-addr 127.0.0.1:7110
```

**Comment by kamoltat** [comment]
Basically we failed here:

```
    ceph osd set noup
    ceph osd down osd.0
    ceph osd unset noup
    TIMEOUT=60 wait_for_osd up 0 || return 1
    search_str="cluster [[]WRN[]] Health check failed: noup flag(s) set (OSDMAP_FLAGS)"
    grep -q "$search_str" $dir/log
    return_code=$?
    if [ $return_code -ne 0 ]; then
      echo "Failed : No WRN entries found in the cluster log file"
      ERRORS=$(($ERRORS + 1))
    fi

    ceph osd out 0
    ceph osd in 0
    WAIT_FOR_CLEAN_TIMEOUT=60 wait_for_clean
    search_str="cluster [[]INF[]] Client client.admin marked osd.0 out, while it was still marked up"
    ceph log last 1000 | grep -q "$search_str" || return 1
    TIMEOUT=60 wait_for_string $dir/log "$search_str"
    grep -q "$search_str" $dir/log
    return_code=$?
    if [ $return_code -eq 0 ]; then
      echo "Failed : Found INF log in the cluster log file"
      ERRORS=$(($ERRORS + 1))
    fi

```

**Comment by kamoltat** [comment]
ERROR 1:

```
2024-06-28T21:31:19.218 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:134: TEST_journald_cluster_log_level:  search_str='1.0 deep-scrub'
2024-06-28T21:31:19.218 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:135: TEST_journald_cluster_log_level:  TIMEOUT=60
2024-06-28T21:31:19.218 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:136: TEST_journald_cluster_log_level:  sleep 60
2024-06-28T21:32:19.220 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:137: TEST_journald_cluster_log_level:  journalctl _COMM=ceph-mon CEPH_CHANNEL=cluster PRIORITY=7 --output=json-pretty --since '60 seconds ago'
2024-06-28T21:32:19.221 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:137: TEST_journald_cluster_log_level:  jq .MESSAGE
2024-06-28T21:32:19.223 INFO:tasks.workunit.client.0.smithi162.stderr:No journal files were opened due to insufficient permissions.
2024-06-28T21:32:19.224 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:138: TEST_journald_cluster_log_level:  grep -q '1.0 deep-scrub' td/mon-cluster-log/journal.log
2024-06-28T21:32:19.226 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:139: TEST_journald_cluster_log_level:  return_code=1
2024-06-28T21:32:19.226 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:140: TEST_journald_cluster_log_level:  '[' 1 -ne 0 ']'
2024-06-28T21:32:19.226 INFO:tasks.workunit.client.0.smithi162.stdout:Failed : Could not find DBG log in the journalctl log file
2024-06-28T21:32:19.227 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:141: TEST_journald_cluster_log_level:  echo 'Failed : Could not find DBG log in the journalctl log file'
2024-06-28T21:32:19.227 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:142: TEST_journald_cluster_log_level:  ERRORS=1
2024-06-28T21:32:19.227 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:145: TEST_journald_cluster_log_level:  ceph osd down 0
2024-06-28T21:32:19.731 INFO:tasks.workunit.client.0.smithi162.stderr:osd.0 is already down.
```

ERROR 2:
```
2024-06-28T21:32:20.278 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:149: TEST_journald_cluster_log_level:  grep -q 'osd.0.*boot' td/mon-cluster-log/journal.log
2024-06-28T21:32:20.279 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:150: TEST_journald_cluster_log_level:  return_code=1
2024-06-28T21:32:20.280 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:151: TEST_journald_cluster_log_level:  '[' 1 -ne 0 ']'
2024-06-28T21:32:20.280 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:152: TEST_journald_cluster_log_level:  echo 'Failed : Could not find INF log in the journalctl log file'
2024-06-28T21:32:20.280 INFO:tasks.workunit.client.0.smithi162.stdout:Failed : Could not find INF log in the journalctl log file
2024-06-28T21:32:20.280 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:153: TEST_journald_cluster_log_level:  ERRORS=2
2024-06-28T21:32:20.280 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:156: TEST_journald_cluster_log_level:  ceph config set mon.a mon_cluster_log_level info
2024-06-28T21:32:20.780 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:157: TEST_journald_cluster_log_level:  ceph pg deep-scrub 1.1
2024-06-28T21:32:21.153 INFO:tasks.workunit.client.0.smithi162.stderr:instructing pg 1.1 on osd.0 to deep-scrub
2024-06-28T21:32:21.164 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:158: TEST_journald_cluster_log_level:  TIMEOUT=60
2024-06-28T21:32:21.165 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:159: TEST_journald_cluster_log_level:  sleep 60
2024-06-28T21:33:21.167 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:160: TEST_journald_cluster_log_level:  search_str='1.1 deep-scrub'
2024-06-28T21:33:21.168 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:161: TEST_journald_cluster_log_level:  journalctl _COMM=ceph-mon CEPH_CHANNEL=cluster PRIORITY=7 --output=json-pretty --since '60 seconds ago'
2024-06-28T21:33:21.168 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:161: TEST_journald_cluster_log_level:  jq .MESSAGE
2024-06-28T21:33:21.170 INFO:tasks.workunit.client.0.smithi162.stderr:No journal files were opened due to insufficient permissions.
2024-06-28T21:33:21.170 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:162: TEST_journald_cluster_log_level:  grep -q '1.1 deep-scrub' td/mon-cluster-log/journal.log
2024-06-28T21:33:21.172 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:163: TEST_journald_cluster_log_level:  return_code=1
2024-06-28T21:33:21.172 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:164: TEST_journald_cluster_log_level:  '[' 1 -eq 0 ']'
2024-06-28T21:33:21.172 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:169: TEST_journald_cluster_log_level:  ceph config set mon.a mon_cluster_log_level warn
2024-06-28T21:33:21.639 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:170: TEST_journald_cluster_log_level:  ceph osd set noup
2024-06-28T21:33:22.229 INFO:tasks.workunit.client.0.smithi162.stderr:noup is set
2024-06-28T21:33:22.240 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:171: TEST_journald_cluster_log_level:  ceph osd down osd.0
```
Error 3:

```
024-06-28T21:33:54.050 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:175: TEST_journald_cluster_log_level:  journalctl _COMM=ceph-mon CEPH_CHANNEL=cluster PRIORITY=4 --output=json-pretty --since '60 seconds ago'
2024-06-28T21:33:54.050 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:175: TEST_journald_cluster_log_level:  jq .MESSAGE
2024-06-28T21:33:54.053 INFO:tasks.workunit.client.0.smithi162.stderr:No journal files were opened due to insufficient permissions.
2024-06-28T21:33:54.053 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:176: TEST_journald_cluster_log_level:  grep -q 'Health check failed: noup flag(s) set (OSDMAP_FLAGS)' td/mon-cluster-log/journal.log
2024-06-28T21:33:54.054 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:177: TEST_journald_cluster_log_level:  return_code=1
2024-06-28T21:33:54.054 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:178: TEST_journald_cluster_log_level:  '[' 1 -ne 0 ']'
2024-06-28T21:33:54.054 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:179: TEST_journald_cluster_log_level:  echo 'Failed : No WRN entries found in the journalctl log file'
2024-06-28T21:33:54.055 INFO:tasks.workunit.client.0.smithi162.stdout:Failed : No WRN entries found in the journalctl log file
2024-06-28T21:33:54.055 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:180: TEST_journald_cluster_log_level:  ERRORS=3
2024-06-28T21:33:54.055 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:183: TEST_journald_cluster_log_level:  ceph osd out 0
2024-06-28T21:33:54.689 INFO:tasks.workunit.client.0.smithi162.stderr:osd.0 is already out.
2024-06-28T21:33:54.699 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:184: TEST_journald_cluster_log_level:  ceph osd in 0
2024-06-28T21:33:55.220 INFO:tasks.workunit.client.0.smithi162.stderr:osd.0 is already in.
2024-06-28T21:33:55.231 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:185: TEST_journald_cluster_log_level:  WAIT_FOR_CLEAN_TIMEOUT=60
2024-06-28T21:33:55.231 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/mon/mon-cluster-log.sh:185: TEST_journald_cluster_log_level:  wait_for_clean
2024-06-28T21:33:55.231 INFO:tasks.workunit.client.0.smithi162.stderr:/home/ubuntu/cephtest/clone.client.0/qa/standalone/ceph-helpers.sh:1642: wait_for_clean:  local cmd=
```

**Comment by kamoltat** [comment]
Basically now I'm dealing with journalctl permissions

**Comment by kamoltat** [comment]
https://pulpito.ceph.com/ksirivad-2024-07-01_18:59:17-rados-main-distro-default-smithi/7781814/

**Comment by kamoltat** [comment]
https://pulpito.ceph.com/ksirivad-2024-07-01_20:28:30-rados-main-distro-default-smithi/

**Review by ljflores — APPROVED** [review]
LGTM once the api test is fixed.

**Review by ljflores — APPROVED** [review]
It was decided that the user privilege issue will be handled separately.

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
Waiting on the api test to pass.

**Comment by rzarzynski** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Comment by kamoltat** [comment]
After reviewing other branches (e.g., squid, reef etc) I didn't find a similar issue, therefore, there is no backport for the PR

**Pull request merged**
