### PR TITLE
QEMU hangs after creating snapshot and stopping VM

### PR DESCRIPTION
**Pull request by Abhishekvrshny**
http://tracker.ceph.com/issues/13756

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
@dillaman this backport passed the rbd suite (http://tracker.ceph.com/issues/13750#note-10), do you think it can be merged ?

**Comment by Abhishekvrshny** [comment]
@dillaman this backport passed the rbd suite (http://tracker.ceph.com/issues/13750#note-10), do you think it can be merged ?

**Comment by dillaman** [comment]
:+1: from me -- needs @jdurgin confirmation

**Comment by jdurgin** [comment]
lgtm

**Pull request merged**
