### PR TITLE
ReplicatedPG::hit_set_trim osd/ReplicatedPG.cc: 11006: FAILED assert(obc)

### PR DESCRIPTION
**Pull request by tchaikov**
http://tracker.ceph.com/issues/12848
http://tracker.ceph.com/issues/13288

### CODE REVIEW

**Comment by dachary** [comment]
@tchaikov is there an upgrade test that verifies the gmt feature ? I guess what we want is to check that hammer-x with this patch in hammer will upgrade well to infernalis.

**Comment by tchaikov** [comment]
@dachary i am testing the upgrade test at http://pulpito.ceph.com/kchai-2015-09-06_03:41:25-upgrade:hammer-x-master---basic-vps/ . will update this pr with the test result.

**Comment by tchaikov** [comment]
@dachary the test passed. but the test was designed so that hammer without bitwise sort and gmt fix can be upgraded to specified branch (with sortbitwise and gmt fix). i will remove following code and post a pull request to ceph-qa-suite/master
```shell
          ceph set pool set cache-pool use_gmt_hitset true 2>&1 | grep "not all OSDs support GMT hit set"
```
after this pr is merged.

if hammer branch supports gmt hitset, the hitset archives will be upgraded to infernalis naturally.

i will also prepare a test for firefly => hammer upgrade as suggested by @athanatos at http://tracker.ceph.com/issues/9732#note-11 .

**Comment by dachary** [comment]
@tchaikov that makes sense, thanks for the detailed explanation :-)

**Comment by tchaikov** [comment]
the tests is posted at https://github.com/ceph/ceph-qa-suite/pull/554

**Comment by tchaikov** [comment]
please hold until #5837 is merged. and then we will backport that pr, and put it into this one.

**Comment by tchaikov** [comment]
added the backport from #5837

**Comment by tchaikov** [comment]
rebased against ceph.git/hammer, and pushed to ceph.git/wip-12848-hammer to test using the upgrade test suite

**Comment by dachary** [comment]
@tchaikov when merged with https://github.com/ceph/ceph/pull/6147 it fails because the prototype changed. I think it would make sense to merge #6147 into this series. If I'm not mistaken, it happens before and will reduce the number of conflicts you had to resolve. What do you think ?

**Comment by tchaikov** [comment]
@dachary let me give it a try: merge #6147 into this pr.

**Comment by dachary** [comment]
@tchaikov ack :-)

**Pull request merged**
