### PR TITLE
jewel: librbd: new API method to force break a peer's exclusive lock

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/17134
http://tracker.ceph.com/issues/18453

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman This PR passed an RBD suite at http://tracker.ceph.com/issues/17851#note-41 
with a single failure [1] that was not reproducible in a subsequent run.

[1] The failure was a reoccurrence of http://tracker.ceph.com/issues/17695
which was supposed to have been fixed in jewel by https://github.com/ceph/ceph/pull/11644

**Comment by smithfarm** [comment]
@dillaman I usually ask folks to drop merge commits from their backport PRs, though I realize it's harmless.

**Comment by smithfarm** [comment]
@dillaman Given the one failed job described at https://github.com/ceph/ceph/pull/12890#issuecomment-275889595 are you OK to merge this now? It appears quite a few other backports are waiting for it.

**Comment by dillaman** [comment]
@smithfarm The test failure was exposed by this PR (it is a different code path from the tracker ticket 17695 but same basic failure of not holding the correct lock). I will work on this first thing tomorrow morning.

**Comment by dillaman** [comment]
@smithfarm I rebased the branch which removed the merge commit. The last commit should fix the assertion failure that you hit during testing.

**Comment by smithfarm** [comment]
Jenkins re-test this please (timeout on unittest_throttle.log)

**Comment by smithfarm** [comment]
Updated PR description to reflect that #11972 is contained in this PR.

**Comment by smithfarm** [comment]
@dillaman This passed an RBD suite at http://tracker.ceph.com/issues/17851#note-59 and a rados suite at http://tracker.ceph.com/issues/17851#note-53

The upgrade suites still have some failures, but none of them appear to be caused by this PR. Do you think it can be merged now?

**Comment by dillaman** [comment]
@smithfarm 👍

**Pull request merged**
