### PR TITLE
tools/rbd: make rbd info display dirty-cache feature

### PR DESCRIPTION
**Pull request by hualongfeng**
Rbd info cannot show dirty-cache feature when it
is enable. So complete `ImageFeatures::FEATURE_MAPPING`
to show the dirty-cache feature.

Signed-off-by: Feng Hualong <hualong.feng@intel.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by hualongfeng** [comment]
jenkins retest

**Comment by hualongfeng** [comment]
jenkins test it again

**Comment by hualongfeng** [comment]
jenkins test ceph API tests

**Comment by hualongfeng** [comment]
jenkins retest this please

**Review by ideepika — APPROVED** [review]

**Comment by ideepika** [comment]
https://pulpito.ceph.com/ideepika-2021-11-21_11:18:44-rbd-wip-deepika3-testing-2021-11-20-0100-distro-basic-smithi/
https://pulpito.ceph.com/ideepika-2021-11-20_11:04:50-rbd-wip-deepika3-testing-2021-11-20-0100-distro-basic-smithi/

**Pull request merged**
