### PR TITLE
ceph.in: add ceph ping mon.* for ping all monitor

### PR DESCRIPTION
**Pull request by XinzeChi**
Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
@XinzeChi could you add a minimal test for this ? https://github.com/ceph/ceph/blob/master/qa/workunits/cephtool/test.sh is probably easiest.

**Comment by XinzeChi** [comment]
@dachary, we must merge the patch https://github.com/ceph/ceph/pull/3559 to master, otherwise the test case will fail.

**Comment by dachary** [comment]
thanks for clarifying the dependency with https://github.com/ceph/ceph/pull/3559

**Comment by XinzeChi** [comment]
@dachary , please review. Thanks

**Comment by dachary** [comment]
It looks good to me. I added the needs-qa label so that it goes thru the next round of integration tests that Samuel Just does on a regular basis.

**Comment by liewegas** [comment]
can you please rebase on current master?

**Comment by XinzeChi** [comment]
@liewegas , rebase already.

**Comment by tchaikov** [comment]
also looks good to me, other than some minor suggestions.

**Pull request merged**
