### PR TITLE
Add upstart files for Ceph REST API

### PR DESCRIPTION
**Pull request by leseb**
Partially solves: #7459 (http://tracker.ceph.com/issues/7459)

Signed-off-by: Sébastien Han <sebastien.han@enovance.com>

### CODE REVIEW

**Comment by dachary** [comment]
@leseb please ignore the false negative from the bot

**Comment by leseb** [comment]
@dachary sure

**Comment by dachary** [comment]
@leseb it looks like this feature was rejected, any idea why ?

**Comment by leseb** [comment]
Hum not really we continued the discussion with Sage here: https://github.com/ceph/ceph/pull/1034
I didn't seem to be against it.

**Comment by liewegas** [comment]
IIRC the concern was that it would confuse ppl to have this rest API and also the calamari one.

Generally feeling is that we should focus on making this work right with systemd and not worry about upstart.  That said, this looks ok to me, as long as the /var/lib/ceph/restapi path is okay (that's all we're really enshrining here).

**Comment by liewegas** [comment]
@leseb what do you think.. is this worth merging?  the next ubuntu won't have upstart anyway, but trusty will be around a while.. but almost nobody runs the rest api.. but ... :)

**Comment by leseb** [comment]
haha but but but :)
Well, the only person I know that uses the rest API is @dmsimard

I don't have much opinion on this one, I created this so I could easily deploy it with ceph-ansible instead of running it from the CLI.

**Comment by hunter** [comment]
If you'd like another data point, we also use the REST API but had containerized it a while ago so now have no need for upstart. It was a little tricky to get running in the early days so it may be worth including if anyone does have need in trusty.

**Comment by leseb** [comment]
One other thing is that people haven't started to build ceph dashboard based on this API. 
@hunter Speaking about containerized rest api PR #4191 should help on that.

**Comment by hunter** [comment]
Nice work @leseb. Will be handy when it lands!

FWIW we do have a Dashboard built around the API so there is at least 1 user of it. We'd started on it pre-calamari days so a fair bit of history there.

**Comment by liewegas** [comment]
Going to skip this.  We can consider doing it later, but let's do systemd first!  Also, the id in the /var/lib/ceph/restapi dir should not include the client. prefix so that it matches what we did with radosgw.

**Pull request closed without merging**
