### PR TITLE
librbd: aio calls may block

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/11770

### CODE REVIEW

**Comment by dachary** [comment]
@dillaman would you mind adding an explanation of how you resolved the conflict at  	9fa3039, adf7d70, 3e157fd, 24c0e08, 5331b2f ? I found that to be quite helpful. Of course the always is the possibility of comparing the diffs to see what have changed, but except for trivial conflicts knowing can help.

**Comment by dillaman** [comment]
@dachary Do you have a good example of this?  Since these changes were basically to correct overzealous code insertions from git and not logic changes, I am struggling to figure out how to properly describe the changes.

**Comment by dachary** [comment]
@dillaman if that's trivial I would just mention **trivial rebase** and the reader knows there is nothing to worry about in the conflict zone. e1d57730ddfc92b17562080b10bc22fceb86539a has an example of non trivial resolution comment. c0cfd6e56ca9d17241da159295bcee7cf44c9ba3 a comment that could have been **trivial rebase** but I started at the difference for a few minutes before seeing the ++ inversion so I felt the need to mention it ;-)

**Comment by dachary** [comment]
or **trivial resolution** instead of **trivial rebase** maybe ?

**Comment by dillaman** [comment]
Passed RBD teuthology suite

**Comment by theanalyst** [comment]
This pr has passed the first run of integration tests for hammer-backports tracked at http://tracker.ceph.com/issues/11990#rbd. @dachary / @dillaman Do you think it is ready to merge

**Comment by dillaman** [comment]
:+1:

**Pull request merged**
