### PR TITLE
luminous: rocksdb: fixes early metadata spill over to slow device in

### PR DESCRIPTION
**Pull request by ifed01**
bluefs.

Fixes http://tracker.ceph.com/issues/22264

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

### CODE REVIEW

**Comment by markhpc** [comment]
Hi Igor,

In the past I think we've updated to the newer version of rocksdb, though perhaps this is a special case.

**Comment by ifed01** [comment]
We have updated rocksdb in the master (along with this fix) but luminous still suffer from the issue - hence need the patch for luminous only.

**Comment by liewegas** [comment]
@markhpc theres risk associated with making big changes to rocksdb (like just fast-forwarding to the latest), so we'll just cherry-pick the fix we need.  master is fast forwarded and will get lots of testing leading up to mimic.

**Comment by liewegas** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by ifed01** [comment]
retest this please

**Comment by shinobu-x** [comment]
@ifed01 Can you update submodule?

**Comment by ifed01** [comment]
@shinobu-x - could you please elaborate what's wrong at the moment and what should I do?

**Comment by shinobu-x** [comment]
@ifed01 sorry i thought you need to do `git submodule update` then push your branch again.

**Comment by ifed01** [comment]
@smithfarm - mind to run QA suits for that once available?

**Comment by smithfarm** [comment]
@ifed01 This is properly staged. We'll try to get it into 12.2.3.

**Comment by ifed01** [comment]
@smithfarm  - thanks!

**Comment by yuriw** [comment]
[luminous => wip-yuri5-testing-2018-01-19-1609](https://trello.com/c/yut3EByt/236-luminous-wip-yuri5-testing-2018-01-19-1609)

**Comment by liewegas** [comment]
@ifed01 is master also fixed? (presumably a fast-forward on the rocksdb commit?)

**Comment by ifed01** [comment]
@liewegas  - master already has more fresh rocksdb embedded where the issue's fixed.

**Comment by dovefi** [comment]
@ifed01 hi，ifed01  does this bug fix already merge to branch 12.2.5?

**Comment by smithfarm** [comment]
@dovefi This patch went into v12.2.3 - see https://ceph.com/releases/v12-2-3-luminous-released/ (search for the PR title)

**Comment by ifed01** [comment]
@dovefi - yes

**Pull request merged**
