### PR TITLE
luminous: ceph-kvstore-tool: use unique_ptr<> manage the lifecycle of bluestore…

### PR DESCRIPTION
**Pull request by ifed01**
… and db

ceph-kvstore-tool segfaults while running against bluestore-kv without this patch.

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 8dc100d3f334cc90f6ef879a33eea34807c0184f)

 Conflicts:
	src/tools/ceph_kvstore_tool.cc

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@ifed01 I retriggered make check, but I don't know the current status - i.e. whether Jenkins is still able to successfully run "make check" on luminous.

**Comment by smithfarm** [comment]
According to Jenkins, this does not compile:

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/ceph_kvstore_tool.cc: In constructor 'StoreTool::StoreTool(std::string, const string&, bool)':
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/ceph_kvstore_tool.cc:62:87: error: no matching function for call to 'std::unique_ptr<KeyValueDB, StoreTool::Deleter>::unique_ptr()'
```

**Comment by tchaikov** [comment]
@ifed01 and @smithfarm i created #39711 to address the FTBFS.

**Comment by ifed01** [comment]
Closing in favor of https://github.com/ceph/ceph/pull/39711

**Pull request closed without merging**
