### PR TITLE
os/filestore: print out the error if do_read_entry() fails

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit 42e85fe35d2fe8f3e99bd110021fd5157cf589d7)

### CODE REVIEW

**Comment by tchaikov** [comment]
@smithfarm this is not a bug fix, but it helps us to understand the root cause of journal corruption issues. so i'd like to backport it to luminous if possible.

**Comment by xiexingguo** [comment]
It does help!

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/crushtool/build.t: failed
--- /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/crushtool/build.t
+++ /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/crushtool/build.t.err
@@ -14,12 +14,6 @@
 # display a warning if there is more than one root
 #
   $ crushtool --outfn "$map" --build --num_osds 5 node straw 2 rack straw 1 
-  .* The crush rulesets will use the root rack0 (re)
-  and ignore the others.
-  There are 3 roots, they can be
-  grouped into a single root by appending something like:
-    root straw 0
-  
 #
 # crush rulesets are generated using the OSDMap helpers
 #
```

**Comment by tchaikov** [comment]
@smithfarm it's tracked by http://tracker.ceph.com/issues/21758

**Comment by smithfarm** [comment]
> it's tracked by http://tracker.ceph.com/issues/21758

Thanks! Backport staged at https://github.com/ceph/ceph/pull/18398

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-10-20_12:22:00-rados-wip-sage-testing-2017-10-19-2129-distro-basic-smithi/

**Pull request merged**
