### PR TITLE
mgr/volumes: Inherit file quota attr to clone

### PR DESCRIPTION
**Pull request by kotreshhr**
The file quota attribute 'ceph.quota.max_files'
is not inherited to the cloned subvolume. This
patch fixes the same.
    
Fixes: https://tracker.ceph.com/issues/54121
Signed-off-by: Kotresh HR <khiremat@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by kotreshhr** [comment]
jenkins test api

**Comment by kotreshhr** [comment]
jenkins test api

**Review by mchangir — COMMENTED** [review]
looks okay

**Review by vshankar — APPROVED** [review]
LGTM

**Comment by kotreshhr** [comment]
Converting this to draft. Needs additional testing.

**Comment by kotreshhr** [comment]
QA Run:
http://pulpito.front.sepia.ceph.com/khiremat-2022-02-11_12:11:43-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/

**Comment by kotreshhr** [comment]
> QA Run Scheduled: http://pulpito.front.sepia.ceph.com/khiremat-2022-02-11_12:11:43-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/

Failure looks unrelated. While I investigate it further, here is the QA re-run scheduled for failed jobs:
http://pulpito.front.sepia.ceph.com/khiremat-2022-02-14_13:49:58-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/

**Comment by kotreshhr** [comment]
> > QA Run Scheduled: http://pulpito.front.sepia.ceph.com/khiremat-2022-02-11_12:11:43-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/
> 
> Failure looks unrelated. While I investigate it further, here is the QA re-run scheduled for failed jobs: http://pulpito.front.sepia.ceph.com/khiremat-2022-02-14_13:49:58-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/

Failure is related. It's because the subvolume is created with restricted mode and I/O is failing with permission denied.

**Comment by kotreshhr** [comment]
QA run scheduled after fixing the issue:
http://pulpito.front.sepia.ceph.com/khiremat-2022-02-15_10:06:47-fs:volumes-wip-khiremat-44854-44873-testing-1-distro-default-smithi/

**Comment by ajarr** [comment]
> > > QA Run Scheduled: http://pulpito.front.sepia.ceph.com/khiremat-2022-02-11_12:11:43-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/
> > 
> > 
> > Failure looks unrelated. While I investigate it further, here is the QA re-run scheduled for failed jobs: http://pulpito.front.sepia.ceph.com/khiremat-2022-02-14_13:49:58-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/
> 
> Failure is related. It's because the subvolume is created with restricted mode and I/O is failing with permission denied.

sorry, missed this. What's this restricted mode?

**Review by ajarr — APPROVED** [review]
LGTM. The tests passed. The failures at http://pulpito.front.sepia.ceph.com/khiremat-2022-02-15_10:06:47-fs:volumes-wip-khiremat-44854-44873-testing-1-distro-default-smithi/ look unrelated

**Comment by kotreshhr** [comment]
> > > > QA Run Scheduled: http://pulpito.front.sepia.ceph.com/khiremat-2022-02-11_12:11:43-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/
> > > 
> > > 
> > > Failure looks unrelated. While I investigate it further, here is the QA re-run scheduled for failed jobs: http://pulpito.front.sepia.ceph.com/khiremat-2022-02-14_13:49:58-fs:volumes-wip-khiremat-44854-44873-testing-0-distro-default-smithi/
> > 
> > 
> > Failure is related. It's because the subvolume is created with restricted mode and I/O is failing with permission denied.
> 
> sorry, missed this. What's this restricted mode?

The subvolume was created with default mode with which the `self._do_subvolume_io` complains writing I/O.

**Comment by kotreshhr** [comment]
QA Run:
http://pulpito.front.sepia.ceph.com/khiremat-2022-02-16_10:23:29-fs:volumes-wip-khiremat-44854-44873-testing-2-distro-default-smithi/

Failures looks un-related. @vshankar PTAL

**Pull request merged**
