### PR TITLE
qa/tasks/qemu: Fix OS version comparison

### PR DESCRIPTION
**Pull request by zmc**
See: https://sentry.ceph.com/share/issue/21ed88d705854238bdafbf6711e795ee/ 
They're not floats.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by idryomov** [comment]
Is this caused by https://github.com/ceph/teuthology/pull/1953?  Asking because nothing in the commit message indicates that it's something recent and yet it worked just a couple of days ago:

https://qa-proxy.ceph.com/teuthology/dis-2024-06-10_19:09:24-rbd-wip-dis-testing-distro-default-smithi/7748383/teuthology.log

**Review by idryomov — COMMENTED** [review]
> They're not floats.

They were until
```
-        version = cls._get_value(str_, 'VERSION_ID')
+        elif name == 'centos':
+            if parse_version(version) >= Version("8.0"):
+                version = f"{version}.stream"
```
in https://github.com/ceph/teuthology/commit/e1d3a972ad5c8e5d750db8bd74e44c5b44734e9f, right?  Could you please mention that in the commit message, file a tracker ticket add include `Fixes` tag with the link in the commit message?  The tracker ticket would be needed for backporting all the way to quincy.

**Comment by idryomov** [comment]
Looks like this is not quite there:
```
2024-06-15T06:09:58.415 ERROR:teuthology.contextutil:Saw exception from nested tasks
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_teuthology_052f8db984c35627d88561260ced2e5d9140e0bf/teuthology/contextutil.py", line 30, in nested
    vars.append(enter())
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/teuthworker/src/github.com_idryomov_ceph_4617fdc2a8724543afd07dcba492aa9768a127c4/qa/tasks/qemu.py", line 499, in run_qemu
    Version(remote.os.version.lower().removesuffix(".stream")) >= Version(8)
  File "/home/teuthworker/src/git.ceph.com_teuthology_052f8db984c35627d88561260ced2e5d9140e0bf/virtualenv/lib/python3.10/site-packages/packaging/version.py", line 198, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
https://qa-proxy.ceph.com/teuthology/dis-2024-06-15_05:49:47-rbd-wip-dis-testing-squid-distro-default-smithi/7757497/teuthology.log

**Comment by idryomov** [comment]
@zmc Ping -- this is blocking the RBD suite in all releases...

**Comment by zmc** [comment]
@idryomov Apologies for the delayed response! I can't reply to your comments for some reason, but:
- Yes, the changes are necessary because of that PR - I updated the commit message to reflect that
- Versions weren't and aren't floats - they're strings - e.g. "13.2.1" != "13.2.10".
- In my haste I did indeed forget quotes around the `8` in the original commit. 🫣

**Comment by idryomov** [comment]
jenkins test make check

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
`make check` keeps failing on `flap.sh` -- obviously unrelated.

**Comment by idryomov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
> Could you please mention that in the commit message, file a tracker ticket add include Fixes tag with the link in the commit message? The tracker ticket would be needed for backporting all the way to quincy.

This wasn't done but I'm merging as is to avoid blocking on `make check` again.  Backports will be done manually.

**Pull request merged**
