### PR TITLE
jewel: rgw: rgw_file: fix size and (c|m)time unix attrs in write_finish

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19720

### CODE REVIEW

**Comment by smithfarm** [comment]
```
rgw/rgw_file.cc: In member function ‘virtual int rgw::RGWWriteRequest::exec_finish()’:
rgw/rgw_file.cc:1292:47: error: no match for ‘operator*’ (operand type is ‘ceph::real_time {aka std::chrono::time_point<ceph::time_detail::real_clock>}’)
                                  (delete_at ? *delete_at : real_time()),
                                               ^
In file included from /usr/include/c++/5/mutex:39:0,
                 from rgw/rgw_lib.h:6,
                 from rgw/rgw_file.cc:9:
/usr/include/c++/5/chrono:424:7: note: candidate: template<class _Rep1, class _Rep2, class _Period> constexpr std::chrono::duration<typename std::chrono::__common_rep_type<_Rep2, _Rep1>::type, _Period> std::chrono::operator*(const _Rep1&, const std::chrono::duration<_Rep, _Period>&)
       operator*(const _Rep1& __s, const duration<_Rep2, _Period>& __d)
       ^
/usr/include/c++/5/chrono:424:7: note:   template argument deduction/substitution failed:
rgw/rgw_file.cc:1292:48: note:   candidate expects 2 arguments, 1 provided
                                  (delete_at ? *delete_at : real_time()),
                                                ^
In file included from /usr/include/c++/5/mutex:39:0,
                 from rgw/rgw_lib.h:6,
                 from rgw/rgw_file.cc:9:
/usr/include/c++/5/chrono:414:7: note: candidate: template<class _Rep1, class _Period, class _Rep2> constexpr std::chrono::duration<typename std::chrono::__common_rep_type<_Rep1, _Rep2>::type, _Period> std::chrono::operator*(const std::chrono::duration<_Rep1, _Period1>&, const _Rep2&)
       operator*(const duration<_Rep1, _Period>& __d, const _Rep2& __s)
       ^
/usr/include/c++/5/chrono:414:7: note:   template argument deduction/substitution failed:
rgw/rgw_file.cc:1292:48: note:   ‘ceph::real_time {aka std::chrono::time_point<ceph::time_detail::real_clock>}’ is not derived from ‘const std::chrono::duration<_Rep1, _Period1>’
                                  (delete_at ? *delete_at : real_time()),
                                                ^
Makefile:24910: recipe for target 'rgw/librgw_la-rgw_file.lo' failed
make[3]: *** [rgw/librgw_la-rgw_file.lo] Error 1
```

**Comment by smithfarm** [comment]
merge conflict

**Comment by mattbenjamin** [comment]
@smithfarm is there an actionable issue here?  I was able to merge with the command line instructions.

**Comment by smithfarm** [comment]
@mattbenjamin No, you're fine. I'm trying to populate the integration branch - this PR is in conflict with some of the other jewel PRs. Once I identify which ones they are, we'll have to reconcile them somehow.

**Comment by smithfarm** [comment]
@mattbenjamin Found the conflict - it was #14659 which has now been merged. Please rebase.

**Comment by smithfarm** [comment]
This passed an rgw suite at http://tracker.ceph.com/issues/20613#note-43

**Pull request merged**
