### PR TITLE
librbd: generic internal API for computing snapshot deltas

### PR DESCRIPTION
**Pull request by dillaman**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dillaman** [comment]
jenkins test api

**Comment by dillaman** [comment]
https://pulpito.ceph.com/jdillaman-2020-09-21_10:51:33-rbd-wip-jd-testing-distro-basic-smithi/

**Comment by dillaman** [comment]
jenkins test api

**Comment by dillaman** [comment]
https://pulpito.ceph.com/jdillaman-2020-09-22_18:26:57-rbd-wip-jd-testing-distro-basic-smithi/

**Comment by dillaman** [comment]
@ceph/dashboard API test failure (https://jenkins.ceph.com/job/ceph-api/3634/)

**Comment by dillaman** [comment]
jenkins test api

**Review by trociny — COMMENTED** [review]
LGTM

**Comment by trociny** [comment]
@dillaman I saw failures in TestDeepCopy.Stress [1] and TestMigration.Stress2 [2] which might be related (the branch includes this PR and #37286).

[1] http://qa-proxy.ceph.com/teuthology/trociny-2020-09-25_10:35:55-rbd-wip-mgolub-testing-1-distro-basic-smithi/5467201/teuthology.log
[2] http://qa-proxy.ceph.com/teuthology/trociny-2020-09-25_10:35:55-rbd-wip-mgolub-testing-1-distro-basic-smithi/5467214/teuthology.log

**Comment by dillaman** [comment]
Hmm -- I think github is having issues right now since it doesn't even show that branch `wip-mgolub-testing-1` exists

**Comment by trociny** [comment]
`wip-mgolub-testing-1` is in ceph-ci repo only

**Comment by dillaman** [comment]
> `wip-mgolub-testing-1` is in ceph-ci repo only

Right -- it's just not showing up for me on github right now (none of your mgolub nor my wip-jd-testing are either)

**Comment by trociny** [comment]
Indeed. It could be accessed by the sha though:

https://github.com/ceph/ceph-ci/commits/77353dd1f6d5b75cf8e65d2f708538c0bc00752c

**Comment by dillaman** [comment]
Looks like it's sometimes incorrectly issuing a `ZERO` op instead of a `TRUNCATE` op when it has a parent and it's all zeroes, so the verification read gets an ENOENT and incorrectly reads from the parent.

**Comment by dillaman** [comment]
Looks like the only failure was the quiesce issue now [1]

[1] https://pulpito.ceph.com/jdillaman-2020-09-27_17:40:38-rbd-wip-jd-testing-distro-basic-smithi/

**Review by trociny — APPROVED** [review]
LGTM

**Pull request merged**
