### PR TITLE
nautilus: mgr/dashboard: fix perf. issue when listing large amounts of buckets

### PR DESCRIPTION
**Pull request by alfonsomthd**
NOTE: Due to base code divergence between master (pacific) & nautilus,
This is a dedicated fix for nautilus related to:

Backport of https://github.com/ceph/ceph/pull/37244
Parent backport tracker: https://tracker.ceph.com/issues/47543

Fixes: https://tracker.ceph.com/issues/47618
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by epuertat** [comment]
jenkins test api

**Comment by epuertat** [comment]
jenkins test make check

**Comment by epuertat** [comment]
@alfonsomthd rgw-bucket-details changes are still missing, right?

**Comment by alfonsomthd** [comment]
> @alfonsomthd rgw-bucket-details changes are still missing, right?

@epuertat rgw-bucket-details changes do not apply on nautilus as there is no versioning, locking, etc in nautilus,
so no need to request bucket full info as it comes in the 1st request.

**Comment by alfonsomthd** [comment]
jenkins test api

**Comment by callithea** [comment]
Is the tracker issue link missing in the commit?
And are you going to add the "Conflicts [...]" section to the commit message as well?

**Comment by alfonsomthd** [comment]
> Is the tracker issue link missing in the commit?
> And are you going to add the "Conflicts [...]" section to the commit message as well?

@callithea Sure, I'll add the tracker issue link.
I didn't add a Conflicts section because it's a dedicated fix for nautilus due to base code divergence between nautilus & master (as I explained in the PR description).

**Comment by callithea** [comment]
> > Is the tracker issue link missing in the commit?
> > And are you going to add the "Conflicts [...]" section to the commit message as well?
> 
> @callithea Sure, I'll add the tracker issue link.

@alfonsomthd thanks!

> I didn't add a Conflicts section because it's a dedicated fix for nautilus due to base code divergence between nautilus & master (as I explained in the PR description).

I would suggest to add this note to the commit message as well to make it clear why this backport does not contain a cherry-pick from master.

**Comment by alfonsomthd** [comment]
> I would suggest to add this note to the commit message as well to make it clear why this backport does not contain a cherry-pick from master.

@callithea Sure! Done.

**Review by epuertat — APPROVED** [review]
👍🏼 thanks @alfonsomthd !

**Comment by alfonsomthd** [comment]
jenkins test docs

**Review by callithea — APPROVED** [review]
lgtm, thanks @alfonsomthd!

**Comment by yuriw** [comment]
[wip-yuri8-testing-2020-09-25-1117-nautilus](https://trello.com/c/dN77beV0/1022-wip-yuri8-testing-2020-09-25-1117-nautilus)

**Pull request merged**
