### PR TITLE
DNM: jewel: exclusive_lock::AcquireRequest doesn't handle -ERESTART on image::RefreshRequest

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17340

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
 CXX      test/librbd/object_map/unittest_librbd-test_mock_SnapshotCreateRequest.o
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc: In member function ‘virtual void librbd::exclusive_lock::TestMockExclusiveLockAcquireRequest_RefreshLockDisabled_Test::TestBody()’:
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:352:3: error: ‘MockTestImageCtx’ was not declared in this scope
   MockTestImageCtx mock_image_ctx(*ictx);
   ^
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:352:20: error: expected ‘;’ before ‘mock_image_ctx’
   MockTestImageCtx mock_image_ctx(*ictx);
                    ^
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:353:3: error: ‘MockRefreshRequest’ was not declared in this scope
   MockRefreshRequest mock_refresh_request;
   ^
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:353:22: error: expected ‘;’ before ‘mock_refresh_request’
   MockRefreshRequest mock_refresh_request;
                      ^
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:354:24: error: ‘mock_image_ctx’ was not declared in this scope
   expect_op_work_queue(mock_image_ctx);
                        ^
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:357:37: error: ‘expect_prepare_lock’ was not declared in this scope
   expect_prepare_lock(mock_image_ctx);
                                     ^
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:361:34: error: ‘mock_refresh_request’ was not declared in this scope
   expect_refresh(mock_image_ctx, mock_refresh_request, -ERESTART);
                                  ^
test/librbd/exclusive_lock/test_mock_AcquireRequest.cc:367:53: error: ‘expect_handle_prepare_lock_complete’ was not declared in this scope
   expect_handle_prepare_lock_complete(mock_image_ctx);
                                                     ^
make[4]: *** [test/librbd/exclusive_lock/unittest_librbd-test_mock_AcquireRequest.o] Error 1
make[4]: *** Waiting for unfinished jobs....
</pre>
MockImageCtx should be MockImageTestCtx or something, introduced after this commit but backported before it

**Comment by dachary** [comment]
rebased

**Comment by dachary** [comment]
repushed with s/MockImageCtx/MockTestImageCtx/ assuming the only issue is class renaming, not class behavior

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
jenkins test this please (no log)

**Comment by dachary** [comment]
genuine error at https://jenkins.ceph.com/job/ceph-pull-requests/14308/

**Comment by dillaman** [comment]
Covered by PR #11972

**Comment by dillaman** [comment]
Merged via alternative PR

**Pull request closed without merging**
