### PR TITLE
crush/mapper: fix divide-by-0 in straw2

### PR DESCRIPTION
**Pull request by liewegas**
If the item weight is 0 we don't want to divide; instead draw a minimal 
value.

Fixes: #11357 Reported-by: Yann Dupont <yd@objoo.org> Tested-by: Yann Dupont
<yd@objoo.org> Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
:+1: as soon as the bot confirms

**Comment by dachary** [comment]
it makes sense that a weight of zero means a minimum value. what confuses me is that ln / w will be larger if w is smaller, until it becomes zero and then becomes the minimum value. I'm missing something in the formulas.

**Comment by liewegas** [comment]
the ln result is negative

**Comment by dachary** [comment]
the second failure (ubuntu it a false negative, ignored)

**Pull request merged**
