### PR TITLE
cephadm: Fix Python formating issues

### PR DESCRIPTION
**Pull request by votdev**
Fix obvious Python formating errors reported by my IDE.

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@votdev could you be more specific in the commit message that these are mostly formatting changes?

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by votdev** [comment]
> @votdev could you be more specific in the commit message that these are mostly formatting changes?

Done

**Comment by votdev** [comment]
jenkins test dashboard backend

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-10_14:43:26-rados-wip-kefu-testing-2020-07-10-1523-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-11_05:07:55-rados-wip-kefu-testing-2020-07-11-1109-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-11_08:56:15-rados-wip-kefu-testing-2020-07-11-1458-distro-basic-smithi/

**Pull request merged**
