### PR TITLE
librbd: do not use ceph::allocator<>

### PR DESCRIPTION
**Pull request by tchaikov**
ceph::allocator was originally introduced to address
https://tracker.ceph.com/issues/39703, so that if tcmalloc < 2.6.2
detected, the homebrew allocator is used. otherwise std::allocator would
use the aligned_alloc() function which was not implemented by tcmalloc <
2.6.2. but the fix in tcmalloc implementing aligned_alloc() was
introduced in https://github.com/gperftools/gperftools/commit/d406f228.
that fix was included since gperftools 2.6.2.

- CentOS/RHEL8 includes gperftools 2.7,
- fedora 33 includes gperftools 2.8,
- ubuntu/focal comes with libgoogle-perftools-dev 2.7
- ubuntu/bionic ships libgoogle-perftools-dev 2.5. but since we
  detect libtcmalloc 2.6.2, when building on bionic, JeMalloc
  or libc allocator is used as fallback.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-ceph-allocator-kefu/8b19c0aef7a11f5d9ef87042e8524be435e2de1d/

**Comment by tchaikov** [comment]
build failure on bionic is addressed by https://github.com/ceph/ceph-build/pull/1811

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by idryomov** [comment]
Can you retrigger the bionic build now that https://github.com/ceph/ceph-build/pull/1811 is merged?

**Comment by tchaikov** [comment]
@idryomov turns out ceph/ceph-build#1811  does not work. i created https://github.com/ceph/ceph-build/pull/1814 to address the issue.

after deploying https://github.com/ceph/ceph-build/pull/1814, i pushed https://shaman.ceph.com/builds/ceph/wip-ceph-allocator-kefu-4/8590b65aba61549e07a3d20ad804ea5fc636cf8d/

**Comment by tchaikov** [comment]
on bionic:
```
-- Could NOT find gperftools: Found unsuitable version "2.5", but required is at least "2.6.2" (found /usr/include)
-- Could NOT find JeMalloc (missing: JEMALLOC_LIBRARIES JEMALLOC_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:363 (message):
  tcmalloc and jemalloc not found, falling back to libc
```

on focal
```
-- Found gperftools: /usr/include (found suitable version "2.7", minimum required is "2.6.2") 
```

**Comment by tchaikov** [comment]
pacific: https://shaman.ceph.com/builds/ceph/pacific-kefu/de0c5c6612c58ecf1a96d1e9aa21b4e88f8762dd/

**Review by idryomov — APPROVED** [review]

**Comment by idryomov** [comment]
Please get it through rados suite, I'll get it through rbd suite next week.

**Comment by tchaikov** [comment]
sure.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-05-15_10:00:36-rados-wip-kefu-testing-2021-05-15-1545-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-16_04:30:13-rados-wip-kefu-testing-2021-05-16-1043-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-05-16_15:20:21-rados-wip-kefu-testing-2021-05-16-2048-distro-basic-smithi/

failures tracked by 

- https://tracker.ceph.com/issues/50830

**Pull request merged**
