### PR TITLE
pacific: Wip min hardware typo pacific backport 2022 05 19

### PR DESCRIPTION
**Pull request by zdover23**
The minimum hardware recommendations said that we
recommended a minimum of "24GB+ per daemon".

I changed this to read "2-4GB+ per daemon".

Reddit actually caught this one:
https://www.reddit.com/r/ceph/comments/q14ey2/cephs_mon_minimum_requirements/

Signed-off-by: Zac Dover <zac.dover@gmail.com>
(cherry picked from commit 14151f2abe93e265e98c6db23dae68b7a530db6f)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by anthonyeleven** [comment]
cf [#37587]
That was deliberate on my part, a result of having seen the RAM that `ceph-mon` and especially `ceph-mgr` consume in real life.

**Review by anthonyeleven — CHANGES_REQUESTED** [review]
cf [https://github.com/ceph/ceph/pull/37587]

The 24GB was deliberate on my part, a result of having seen the RAM that `ceph-mon` and especially `ceph-mgr` consume in real life.

**Comment by jdurgin** [comment]
> cf [#37587] That was deliberate on my part, a result of having seen the RAM that `ceph-mon` and especially `ceph-mgr` consume in real life.

That seems like a bug - rather than what we should document as minimums

**Comment by anthonyeleven** [comment]
> > cf [#37587] That was deliberate on my part, a result of having seen the RAM that `ceph-mon` and especially `ceph-mgr` consume in real life.
> 
> That seems like a bug - rather than what we should document as minimums

What would you suggest as an alternative value?  I've often seen 6+ GB resident.

**Comment by zdover23** [comment]
@anthonyeleven Would you give us an approval on this so that we can get it backported?

**Comment by anthonyeleven** [comment]
> @anthonyeleven Would you give us an approval on this so that we can get it backported?

What's it worth to you?  ;)

Seriously, I'd thought for some reason that this had already been merged.

**Comment by zdover23** [comment]
> > @anthonyeleven Would you give us an approval on this so that we can get it backported?
> 
> What's it worth to you? ;)

Everything that I can think of to say in response that seems clever is also so awful that I can't say it ex cathedra. So: dang it.

> Seriously, I'd thought for some reason that this had already been merged.

**Pull request merged**
