### PR TITLE
rgw: dbstore: add mechanism to signal gc_worker to exit

### PR DESCRIPTION
**Pull request by mattbenjamin**
This addresses a trivial hang on shutdown.

Fixes: https://tracker.ceph.com/issues/55431

Signed-off-by: Matt Benjamin <mbenjamin@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by soumyakoduri — APPROVED** [review]

**Comment by mattbenjamin** [comment]
jenkins test make check

**Comment by mattbenjamin** [comment]
@cbodley what qa does this currently need?

**Comment by cbodley** [comment]
> @cbodley what qa does this currently need?

oops, i just tagged this out of habit

> 217/277 Test #251: unittest_dbstore_tests ....................   Passed    1.86 sec

good to merge then 👍

**Comment by tchaikov** [comment]
@mattbenjamin   hi Matt, in future, could you please add "Reviewed-by" lines in the merge commit when merging pull requests?

**Comment by mattbenjamin** [comment]
> @mattbenjamin hi Matt, in future, could you please add "Reviewed-by" lines in the merge commit when merging pull requests?
Isn't that something we can rely on github for?

**Pull request merged**
