### PR TITLE
nautilus: test/admin_socket_output: Don't invalidate 'target' iterator

### PR DESCRIPTION
**Pull request by badone**
Fixes: https://tracker.ceph.com/issues/48204

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by badone** [comment]
4825072720b fixed this in master but is not a straightforward backport so creating a fix for just the invalidated iterator crash.

**Review by ideepika — APPROVED** [review]
thanks! :+1:

**Comment by badone** [comment]
jenkins test make check

**Comment by badone** [comment]
Thanks @ideepika @smithfarm

**Pull request merged**
