### PR TITLE
mon/PGMap: Increase size, and add check if erasure or not

### PR DESCRIPTION
**Pull request by shinobu-x**
In case of size=3 and min_size=2, nobody wants to reduce min_size to 1.

Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
it is still helpful to reduce min_size to 1 in many cases, and i don't think teh erasure vs non-erasure part matters?

**Comment by shinobu-x** [comment]
@liewegas the **main** purpose of this pr is **not** entirely min_size. frankly speaking i don't care about that. however i do care about description in `doc/rados/operations/pg-states.rst`

`In the case of an erasure coded pool temporarily reducing min_size may allow recovery.`

do you see confusion? even using replicated, you will see `may help; search ceph.com/docs for 'incomplete')`

**Comment by liewegas** [comment]
Ah, I see.

For EC pools, temporarily reducing min_size may allow recovery, yes.  Replicated is smart enough to recover regardless of min_size.  *But* @gregsfortytwo is in the process of fixing this so that *both* will recovery regardless of min_size.

So probably we want to drop the message entirely?  (I'm assuming Greg's fix will land soon.)

I also didn't understand why 1 changed to 2.. but I think it's a moot point in any case!

**Comment by shinobu-x** [comment]
@liewegas Thanks for your understanding! Since our ultimate goal is auto healing, any manual changes (in case of unhealthy objects appearing to us) needs to be prevented as much as possible (at least to me)?

In case that we do need any kind of manual change, we should explicitly suggest some with intently prepared option (e.g., `osd_find_best_info_ignore_history_les`).

**Pull request closed without merging**
