### PR TITLE
pacific: cephfs-shell: move source to separate subdirectory

### PR DESCRIPTION
**Pull request by tserong**
backport tracker: https://tracker.ceph.com/issues/56977

---

backport of https://github.com/ceph/ceph/pull/47202
parent tracker: https://tracker.ceph.com/issues/56658

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by tchaikov** [comment]
the test failure should be fixed by #47484

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Review by tchaikov — APPROVED** [review]

**Review by nmshelke — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tserong** [comment]
Rebased (let's see if that fixes those checks)

**Comment by tchaikov** [comment]
```
[ RUN      ] TestMockMigrationHttpClient.IssuePipelined
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssuePipelined (67 ms)
[ RUN      ] TestMockMigrationHttpClient.IssuePipelinedRestart
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssuePipelinedRestart (60 ms)
[ RUN      ] TestMockMigrationHttpClient.ShutdownInFlight
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.ShutdownInFlight (56 ms)
[ RUN      ] TestMockMigrationHttpClient.GetSize
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.GetSize (54 ms)
[ RUN      ] TestMockMigrationHttpClient.GetSizeError
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.GetSizeError (54 ms)
[ RUN      ] TestMockMigrationHttpClient.Read
unknown file: Failure
C++ exception with description "bind: Address already in use [system:98]" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.Read (54 ms)
[----------] 17 tests from TestMockMigrationHttpClient (1147 ms total)
```

```
The following tests FAILED:
	 13 - run-rbd-unit-tests-61.sh (Failed)
	 14 - run-rbd-unit-tests-109.sh (Failed)
	 15 - run-rbd-unit-tests-127.sh (Failed)
```

**Comment by tserong** [comment]
Looks like https://github.com/ceph/ceph/pull/47460 has the same(?) set of failures. There's also a bunch of weird stuff like:

Failed to load class: cas (/home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cas.so): /home/jenkins-build/build/workspace/ceph-pull-requests/build/lib/libcls_cas.so: undefined symbol: _Z26cls_get_manifest_ref_countPvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

I don't know what's going on here, sorry :-/

**Comment by kotreshhr** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
@tserong @tchaikov @kotreshhr it can't be merged
Is anybody looking into this?

**Comment by tserong** [comment]
The latest `make check` failure appears to be:

```
In file included from crc/../os/os.h:38,
                 from crc/crc32c-arm64.c:2:
crc/../os/os-linux.h:17:10: fatal error: linux/raw.h: No such file or directory
   17 | #include <linux/raw.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:369: crc/crc32c-arm64.o] Error 1
make[3]: *** [CMakeFiles/fio_ext.dir/build.make:86: fio_ext-prefix/src/fio_ext-stamp/fio_ext-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:3667: CMakeFiles/fio_ext.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

I'm struggling to see how this is related to anything in the current PR.

**Comment by tserong** [comment]
Looks like the pacific build uses fio-315 (https://github.com/ceph/ceph/blob/pacific/cmake/modules/BuildFIO.cmake#L18) which doesn't include https://github.com/axboe/fio/commit/382975557e632efb506836bc1709789e615c9094. So either Pacific's fio is too old, or the CI's kernel is too new :-/

**Comment by tchaikov** [comment]
> We can probably fix this by cherry-picking [d777100](https://github.com/ceph/ceph/commit/d7771002ef9a455390aadbcc84287dd9b738c629) into pacific. @tchaikov, is there any reason _not_ to do that? (It will pull in a newer fio). Assuming that's OK, shall I do it here, or would you prefer a separate PR given it's unrelated?

@tserong hey Tim, i cannot think of a reason why we don't do this. i am fine either way. but i'd create another PR to address this issue.

**Comment by tserong** [comment]
Thanks @tchaikov - new PR coming up...

**Comment by ljflores** [comment]
Rados suite review: https://pulpito.ceph.com/?branch=wip-yuri3-testing-2022-08-11-0809-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/55443
    2. https://tracker.ceph.com/issues/53939
    3. https://tracker.ceph.com/issues/53827
    4. https://tracker.ceph.com/issues/52321
    5. https://tracker.ceph.com/issues/57207 -- created a new Tracker; unrelated to PRs in this run
    6. https://tracker.ceph.com/issues/56573
    7. https://tracker.ceph.com/issues/53501
    8. https://tracker.ceph.com/issues/54071
    9. https://tracker.ceph.com/issues/54603
    10. https://tracker.ceph.com/issues/49727 -- pending Pacific backport

Details:
    1. "SELinux denials found.." in rados run - Ceph - Infrastructure
    2. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    3. cephadm exited with error code when creating osd: Input/Output error. Faulty NVME? - Ceph - Orchestrator
    4. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Rook
    5. AssertionError: Expected to find element: `cd-modal .badge:not(script,style):cy-contains('/^foo$/'), cd-modal .badge[type='submit'][value~='/^foo$/']`, but never found it. - Ceph - Mgr - Dashboard
    6. test_cephadm.sh: KeyError: 'TYPE' - Ceph - Orchestrator
    7. Exception when running 'rook' task. - Ceph - Orchestrator
    8. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
    9. Valgrind reports memory "Leak_IndirectlyLost" errors on ceph-mon. - Ceph - RADOS
    10. lazy_omap_stats_test: "ceph osd deep-scrub all" hangs - Ceph - RADOS

**Comment by ljflores** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by tserong** [comment]
Rebased to get `make check` done

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
Ugh, this thing again:

```
[ RUN      ] TestMockMigrationHttpClient.OpenCloseHttp
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenCloseHttp (114 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenCloseHttps
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenCloseHttps (100 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenHttpsHandshakeFail
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenHttpsHandshakeFail (97 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenInvalidUrl
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenInvalidUrl (107 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenResolveFail
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenResolveFail (90 ms)
[ RUN      ] TestMockMigrationHttpClient.OpenConnectFail
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.OpenConnectFail (69 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueHead
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueHead (99 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueGet
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueGet (97 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueSendFailed
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueSendFailed (73 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueReceiveFailed
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueReceiveFailed (76 ms)
[ RUN      ] TestMockMigrationHttpClient.IssueResetFailed
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssueResetFailed (68 ms)
[ RUN      ] TestMockMigrationHttpClient.IssuePipelined
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssuePipelined (98 ms)
[ RUN      ] TestMockMigrationHttpClient.IssuePipelinedRestart
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.IssuePipelinedRestart (69 ms)
[ RUN      ] TestMockMigrationHttpClient.ShutdownInFlight
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.ShutdownInFlight (81 ms)
[ RUN      ] TestMockMigrationHttpClient.GetSize
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.GetSize (116 ms)
[ RUN      ] TestMockMigrationHttpClient.GetSizeError
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.GetSizeError (112 ms)
[ RUN      ] TestMockMigrationHttpClient.Read
unknown file: Failure
C++ exception with description "bind: Address already in use" thrown in SetUp().
[  FAILED  ] TestMockMigrationHttpClient.Read (139 ms)
[----------] 17 tests from TestMockMigrationHttpClient (1606 ms total)
```

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
Ah, those failures will be https://tracker.ceph.com/issues/57116.

**Comment by tserong** [comment]
jenkins test make check

**Pull request merged**
