### PR TITLE
doc: clarify upmap balancer documentation

### PR DESCRIPTION
**Pull request by ljflores**
In https://github.com/ceph/ceph/pull/51499, some language was added that refers to the upmap balancer as the "capacity" balancer, but we don't want to insinuate that there is anything "new" that was added or changed. It should be clear that this section refers to the existing upmap balancer, which has existed for several releases.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by anthonyeleven — APPROVED** [review]

**Comment by ljflores** [comment]
Hey @neha-ojha, you mentioned that some of the changes made in https://github.com/ceph/ceph/pull/51499 should be changed so it's not implying that we added anything new to the upmap balancer. I started some changes in this PR, but can you let me know what other parts should be modified?

See https://github.com/ceph/ceph/pull/51499, the first read balancer documentation PR, for all the new stuff that was added.

**Review by anthonyeleven — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Comment by zdover23** [comment]
@ljflores: Is this ready for merge and backporting?

**Comment by ljflores** [comment]
@zdover23 yes, it's ready!

**Comment by zdover23** [comment]
@ljflores Qapla!

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/53004 - Reef backport

**Comment by zdover23** [comment]
@ljflores: Should this be backported to Quincy? It looks to me like doc/dev/balancer-design.rst is new in main and reef.

**Comment by ljflores** [comment]
@zdover23 it should only be backported as far as reef.

**Pull request merged**
