### PR TITLE
pacific: cephadm: pin flake8 to 5.0.4

### PR DESCRIPTION
**Pull request by idryomov**
Backport https://github.com/ceph/ceph/pull/49040 to pacific.

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Comment by idryomov** [comment]
jenkins test api

**Comment by idryomov** [comment]
Hrm, there seems to be an additional, pacific-only unused import:
```
cephadm/services/exporter.py:11:5: F401 'cephadm.module.CephadmOrchestrator' imported but unused
1     F401 'cephadm.module.CephadmOrchestrator' imported but unused
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-pull-requests/src/pybind/mgr/.tox/flake8/bin/flake8 --config=tox.ini cephadm cli_api nfs orchestrator prometheus (exited with code 1)
```

**Comment by idryomov** [comment]
Pushed an additional pacific-only change:
```
diff --git a/src/pybind/mgr/cephadm/services/exporter.py b/src/pybind/mgr/cephadm/services/exporter.py
index d6bef885bc2f..ac1d5b38a161 100644
--- a/src/pybind/mgr/cephadm/services/exporter.py
+++ b/src/pybind/mgr/cephadm/services/exporter.py
@@ -17,8 +17,8 @@ class CephadmExporterConfig:
     required_keys = ['crt', 'key', 'token', 'port']
     DEFAULT_PORT = '9443'
 
-    def __init__(self, mgr, crt="", key="", token="", port=""):
-        # type: (CephadmOrchestrator, str, str, str, str) -> None
+    def __init__(self, mgr: CephadmOrchestrator, crt: str = "", key: str = "",
+                 token: str = "", port: str = "") -> None:
         self.mgr = mgr
         self.crt = crt
         self.key = key
```

**Comment by idryomov** [comment]
jenkins test api

**Review by tchaikov — APPROVED** [review]

**Comment by ljflores** [comment]
Rados suite review by @amathuria:

https://pulpito.ceph.com/?branch=wip-yuri10-testing-2022-11-28-1042-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/53501 - Failure: [Errno 2] Cannot find file on the remote 'ubuntu@smithi187.front.sepia.ceph.com': 'rook/cluster/examples/kubernetes/ceph/operator.yaml'
    2. https://tracker.ceph.com/issues/44595 - src/test/osd/RadosModel.h: 1942: ceph_abort_msg("abort() called")
    3. https://tracker.ceph.com/issues/58114 - mon: FAILED ceph_assert(rank == new_rank)
    4. https://tracker.ceph.com/issues/58097 - qa/workunits/post-file.sh: kex_exchange_identification: read: Connection reset by peer
    5. https://tracker.ceph.com/issues/58046 - qa/workunits/rados/test_librados_build.sh: specify redirect in curl command
    6. https://tracker.ceph.com/issues/51372 - pacific: libcephsqlite: segmentation fault
    7. https://tracker.ceph.com/issues/54071 - rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
    8. https://tracker.ceph.com/issues/58130 -- rados_api_tests: HEALTH_WARN: Degraded data redundancy: 1/5 objects degraded (20.000%), 1 pg degraded - Ceph - RADOS

**Pull request merged**
