### PR TITLE
Allow custom cluster name

### PR DESCRIPTION
**Pull request by aalba6675**
Source for a custom cluster name:
E.g. /etc/{sysconfig,default}/ceph

cluster=mycluster

### CODE REVIEW

**Comment by smithfarm** [comment]
That looks like a sensible thing to do in the init script. Could you squash those two commits together? https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by aalba6675** [comment]
Yes will do..and resubmit.

**Comment by smithfarm** [comment]
Just a reminder that you don't need to close the pull request (PR). When you force-push your branch (`aalba6675-patch-2`), the PR will automatically update itself.

**Comment by smithfarm** [comment]
Superseded by #6732

**Pull request closed without merging**
