### PR TITLE
[DNM TEST FAILURES] nautilus: qa: ignore logrotate state rename error

### PR DESCRIPTION
**Pull request by smithfarm**
backport trackers:

* https://tracker.ceph.com/issues/47660
* https://tracker.ceph.com/issues/47820

---

backport of:

* https://github.com/ceph/ceph/pull/37266
* https://github.com/ceph/ceph/pull/37441

parent trackers:

* https://tracker.ceph.com/issues/42433
* https://tracker.ceph.com/issues/47677

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-10-26-0802-nautilus](https://trello.com/c/aTkrbBpe/1046-wip-yuri7-testing-2020-10-26-0802-nautilus)

**Comment by ideepika** [comment]
http://pulpito.front.sepia.ceph.com/ideepika-2020-12-11_19:23:47-rados-wip-deepika-testing-2020-12-08-2006-nautilus-distro-basic-smithi/

**Comment by ideepika** [comment]
@ajarr can you review, if it's relevant

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/47660#note-5

**Pull request closed without merging**
