### PR TITLE
doc/radosgw/swift: Fix repeated word

### PR DESCRIPTION
**Pull request by Gaoweinan**
Word repetition in swift API

fix:https://tracker.ceph.com/issues/58124

Signed-off-by: gaoweinan <gaoweinan@inspur.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
the title of the commit message reads like a bug report. ideally, the title of the commit message should use the imperative mood. see also https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes . please use `git commit --amend`  and `git push -f` for revising the commit message and its title.

**Comment by Gaoweinan** [comment]
> 

Thank you. I have finished the modification and committed again.

**Comment by Gaoweinan** [comment]
Thanks. I have finished the modification and committed again.
















At 2022-11-30 20:45:29, "anthonyeleven" ***@***.***> wrote:

Should be doc/radosgw/swift: Fix repeated word

**Review by anthonyeleven — APPROVED** [review]

**Comment by anthonyeleven** [comment]
Great!   I see that the pull request checklist is failing. Each of the 4 sections in the checklist in the description needs to have a box checked.  I edited this for you this time and will merge when the test completes.  For future contributions please fill that out when you create the PR for faster approval.

**Comment by Gaoweinan** [comment]
Thank you very much! I will pay attention to this next time.
















At 2022-12-01 09:49:21, "anthonyeleven" ***@***.***> wrote:

Great! I see that the pull request checklist is failing. Each of the 4 sections in the checklist in the description needs to have a box checked. I edited this for you this time and will merge when the test completes. For future contributions please fill that out when you create the PR for faster approval.

**Pull request merged**
