### PR TITLE
osd/OSDMap: add osdmap epoch info when printing info summary

### PR DESCRIPTION
**Pull request by shun-s**
add osdmap epoch info when printing info summary

Signed-off-by: shun-s <song.shun3@zte.com.cn>

### CODE REVIEW

**Comment by shun-s** [comment]
@xiexingguo  sometime needs to know latest osdmap epoch, but it isn't really quite straight to acquire.
so i hope that osdmap epoch show in `ceph -s` just like what previous ceph version does.
```
services:
    mon: 3 daemons, quorum a,b,c
    mgr: x(active)
    mds: cephfs_a-1/1/1 up  {0=a=up:replay}
    osd: 3 osds: 3 up, 2 in; epoch: e96; 64 remapped pgs
```

**Comment by liewegas** [comment]
perhaps we should put this in 'ceph osd stat' instead of ceph -s?

**Comment by jcsp** [comment]
Removing the osdmap epoch (and other epochs) from "ceph status" was intentional: most ordinary users do not need to deal with the concept of a cluster map epoch most of the time.  It's still accessible in "ceph osd dump".

Adding it back in "ceph osd stat" would be fine too

**Comment by xiexingguo** [comment]
I must confess that removing the osdmap epoch from "ceph status" keeps annoying me, especially when you have to switch from "ceph -s" to "ceph osd dump" to figure it out.



> most ordinary users do not need to deal with the concept of a cluster map epoch most of the time

I am afraid those who really care about the outputs of "ceph -s" are non-ordinary users and I don't think it will be easier to understanding other concepts such as quorum, remapped whatever for them.

So +1 for this change (and for myself).

**Comment by shun-s** [comment]
@jcsp i gratelly approved with your intentional idea, but  i think maintenance cli commands were mostly used by  professional users.  for orinary people, visiting with web to mgr is better, which is more comfortable and stright.  

the other way  may show with less literals, which  take away less focus for users who don't care.

before:
```
osd: 3 osds: 3 up, 2 in; 64 remapped pgs
```
after
```
osd: 3 osds: 3 up, 2 in, e96; 64 remapped pgs
```

@liewegas  @jcsp  would that make sense?

**Comment by jcsp** [comment]
Perhaps I'm missing what typical workflow requires knowing the osdmap epoch?

**Comment by xiexingguo** [comment]
The map version is the most intuitive way of observing a change of configuration, the cluster topology, OSD status whatever. Also it is the most frequently consulted parameter each time I try to bring a broken cluster back into normal.

**Comment by jcsp** [comment]
In the case of a broken cluster, I think it's fine that you have to use an extra command to get the epoch: the "ceph status" command is meant to tell you the condition of the cluster, not everything you need to fix the cluster.

In the case of observing changes, the epoch only indicates a change to if the person has memorised the previous epoch number, and can notice the difference.  This seems like a strange way of using the command, especially when epoch numbers are large: I know that when I see a large epoch number, I don't instantly recognise whether it has recently incremented.  Also, we have the cluster log for telling you what changed: the status command is only telling you about the situation at that present moment.

I still think sage's suggestion of putting the epoch in the "ceph osd stat" output is a good compromise here: it makes it easy to access find for people who want it.

**Comment by jcsp** [comment]
Another thought: I would be okay with having a "power" version of some commands, which could include as much extra info as you wanted.  Is there anything in addition to the epoch that you would add, if we had a power-user status command?

**Comment by xiexingguo** [comment]
> I still think sage's suggestion of putting the epoch in the "ceph osd stat" output is a good compromise here: it makes it easy to access find for people who want it.

I am fine with that too:-) @jcsp 


> I would be okay with having a "power" version of some commands, which could include as much extra info as you wanted. Is there anything in addition to the epoch that you would add, if we had a power-user status command?

How many clients are  currently connected, perhaps? Also I'd be happier if there is a way of telling the detail information of these clients, e.g., IP address.

**Comment by liewegas** [comment]
Another thought: I would really like to see an 'age' value for some of the information information we present. For example, it would be helpful to see that the mon quorum in "3d" vs "12m" old.

**Comment by shun-s** [comment]
i will make osdmap epoch show just in `ceph osd stat`, which is one of the candidae 'power' command for osd services. @jcsp 
if other imformation imformation needs to show, then goes to `ceph osd/mon stat`, but now they are not clear to me. so i'd like to do later. @liewegas 
thank you all

**Comment by shun-s** [comment]
@jcsp ping

**Comment by xiexingguo** [comment]
http://pulpito.ceph.com/xxg-2018-02-03_15:38:21-rados-wip-xxg-testing-2018-02-03-distro-basic-smithi/

**Pull request merged**
