### PR TITLE
radosgw-admin: fix error message of OPT::LC_RESHARD_FIX

### PR DESCRIPTION
**Pull request by Huber-ming**
OPT::LC_RESHARD_FIX's error message is inappropriate, so fix it.

Signed-off-by: Huber-ming <zhangsm01@inspur.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by Huber-ming** [comment]
jenkins test make check arm64

**Review by yangruifeng — APPROVED** [review]
mistake
ignore

**Comment by Huber-ming** [comment]
jenkins test make check arm64

**Comment by Huber-ming** [comment]
hi, @yangruifeng why "Could not resolve host: github.com" in `make check (arm64)`?

**Review by dang — APPROVED** [review]

**Comment by dang** [comment]
jenkins test make check arm64

**Pull request merged**
