### PR TITLE
rgw: fix RGWUserInfo decode current version

### PR DESCRIPTION
**Pull request by liuchang0812**
Signed-off-by: Chang Liu <liuchang0812@gmail.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liuchang0812** [comment]
@cbodley mind taking a look?

**Comment by ivancich** [comment]
@liuchang0812 Would you mind attaching a tracker to this pr, so we know which, if any, backports are needed?

**Comment by liuchang0812** [comment]
> @liuchang0812 Would you mind attaching a tracker to this pr, so we know which, if any, backports are needed?

done , add "Fixes: https://tracker.ceph.com/issues/43167" into the commit message

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2020-01-21_20:23:35-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
