### PR TITLE
Squid: mgr/dashboard: service form hosts selection only show up to 10 entries 

### PR DESCRIPTION
**Pull request by nmunet**
backport tracker: https://tracker.ceph.com/issues/68042

backport of: https://github.com/ceph/ceph/pull/59576

parent tracker: https://tracker.ceph.com/issues/67413

<hr style="border: 2px solid #eeeeee" />

exposed new UIRouter API to get all hosts

Fixes: https://tracker.ceph.com/issues/67413

Signed-off-by: Naman Munet <nmunet@redhat.com>
(cherry picked from commit ec3e4abeeb7feebd996681a7d8d4e950de5cf518)

 Conflicts:
	src/pybind/mgr/dashboard/frontend/src/app/ceph/cephfs/cephfs-form/cephfs-form.component.ts (resolved conflicts)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by afreen23 — APPROVED** [review]

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
Some env issue for dashboard tests failure:
```
** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
2024-09-13T09:35:40.451+0000 7fc3722cd640 -1 WARNING: all dangerous and experimental features are enabled.
2024-09-13T09:35:40.483+0000 7fc3722cd640 -1 WARNING: all dangerous and experimental features are enabled.
RGW credentials configured
+ ceph2 dashboard set-rgw-credentials
+ /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/build/../src/mrun 2 ceph dashboard set-rgw-credentials
*** DEVELOPER MODE: setting PATH, PYTHONPATH and LD_LIBRARY_PATH ***
2024-09-13T09:35:57.282+0000 7f07a6c5c640 -1 WARNING: all dangerous and experimental features are enabled.
2024-09-13T09:35:57.314+0000 7f07a6c5c640 -1 WARNING: all dangerous and experimental features are enabled.
Error EINVAL: No RGW credentials found, please consult the documentation on how to enable RGW for the dashboard.
Build step 'Execute shell' marked build as failure
```

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by nmunet** [comment]
jenkins test dashboard

**Comment by nmunet** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
Cephadm tests are broken for a known reason.
Dashboard tests failure:
```
[Test Result](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/) (32 failures / +7)
[should create image.Images page create, edit & delete image test should create image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/should%20create%20image/Images_page_create__edit___delete_image_test_should_create_image/)
[should edit image.Images page create, edit & delete image test should edit image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/should%20edit%20image/Images_page_create__edit___delete_image_test_should_edit_image/)
[should delete image.Images page create, edit & delete image test should delete image](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/should%20delete%20image/Images_page_create__edit___delete_image_test_should_delete_image/)
["before all" hook for "should move the image to the trash".Images page move to trash, restore and purge image tests "before all" hook for "should move the image to the trash"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/%22before%20all%22%20hook%20for%20%22should%20move%20the%20image%20to%20the%20trash%22/Images_page_move_to_trash__restore_and_purge_image_tests__before_all__hook_for__should_move_the_image_to_the_trash_/)
["after all" hook for "should move the image to the trash".Images page move to trash, restore and purge image tests "after all" hook for "should move the image to the trash"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/%22after%20all%22%20hook%20for%20%22should%20move%20the%20image%20to%20the%20trash%22/Images_page_move_to_trash__restore_and_purge_image_tests__after_all__hook_for__should_move_the_image_to_the_trash_/)
["after each" hook for "should logout when clicking the button".Login page "after each" hook for "should logout when clicking the button"](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/%22after%20each%22%20hook%20for%20%22should%20logout%20when%20clicking%20the%20button%22/Login_page__after_each__hook_for__should_logout_when_clicking_the_button_/)
[should create pool and check audit logs reacted.Logs page audit logs respond to pool creation and deletion test should create pool and check audit logs reacted](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/should%20create%20pool%20and%20check%20audit%20logs%20reacted/Logs_page_audit_logs_respond_to_pool_creation_and_deletion_test_should_create_pool_and_check_audit_logs_reacted/)
[should delete pool and check audit logs reacted.Logs page audit logs respond to pool creation and deletion test should delete pool and check audit logs reacted](https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/16266/testReport/junit/(root)/should%20delete%20pool%20and%20check%20audit%20logs%20reacted/Logs_page_audit_logs_respond_to_pool_creation_and_deletion_test_should_delete_pool_and_check_audit_logs_reacted/)
```

**Pull request merged**
