### PR TITLE
mgr/prometheus: s/pkg_resources.packaging/packaging/

### PR DESCRIPTION
**Pull request by tchaikov**
instead of relying on the internal implementation of pkg_resources, let's import packaging directly.

in this change, we also add the dependency to the packaging module in the packaging recipes.

See also https://github.com/pypa/setuptools/issues/4385

Fixes https://tracker.ceph.com/issues/66201
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@petrutlucian94 hi Lucian, could you please take a look on the failure at https://jenkins.ceph.com/job/ceph-windows-pull-requests/40812/consoleFull#212386344640526d21-3511-427d-909c-dd086c0d1034 ? the tests on windows are failing quite frequently recently.

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
jenkins test windows

**Comment by tchaikov** [comment]
@rkachach and @pereman2 hi Redouane and Pere, i see you were updating this module recently. could you help review this change at your convenience?

**Comment by petrutlucian94** [comment]
@tchaikov one of the recently introduced tests is flaky: https://github.com/ceph/ceph/pull/55008/files#r1613349863

It fails on Linux as well, it's just that the Windows job runs it and the Linux "make check" job does not.

I'm thinking about skipping it on Windows.

**Comment by tchaikov** [comment]
@petrutlucian94 hi Lucian, thank you for looking into this and the prompt workaround.

**Comment by rkachach** [comment]
> @rkachach and @pereman2 hi Redouane and Pere, i see you were updating this module recently. could you help review this change at your convenience?

@tchaikov the change LGTM as `pkg_resources` seems to be deprecated https://discuss.python.org/t/will-setuptools-remove-pkg-resource-module-in-the-future/27182 and the alternative you provide gets the same functionality without depending on it.

**Review by rkachach — APPROVED** [review]
LGTM

**Comment by tchaikov** [comment]
@rkachach thank you for your review. i will get it tested with teuthology. just to make sure the change compile, and does not introduce any regressions.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-mgr-prometheus-packaging-kefu/61fb73804d44d13d543a188b407762dcf76c6293/

**Comment by zdover23** [comment]
@tchaikov, Can we get this backported to S, R, and Q so that the docs will build on R and Q?

**Comment by zdover23** [comment]
https://github.com/ceph/ceph/pull/58623 - Squid backport
https://github.com/ceph/ceph/pull/58624 - Reef backport
https://github.com/ceph/ceph/pull/58627 - Quincy backport

**Pull request merged**
