### PR TITLE
qa/suites/upgrade/pacific-x/rgw-multisite: specify distro

### PR DESCRIPTION
**Pull request by tchaikov**
instead of using the default / existing distro, specify the distro for
testing. this change prevents us from using bionic for testing the
builds. this has two consequences:

* so we are one step closer to a non-bionic world.
* avoid building packages with PPA repo which *might* introduce runtime
  dependencies on 3rd party runtimes provided by PPA repo.

see also: https://tracker.ceph.com/issues/50218

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
$ teuthology-suite  --ceph wip-kefu-testing-2021-04-12-0057 --machine-type gibba --suite rados:upgrade:pacific-x:rgw-multisite --suite-repo https://github.com/tchaikov/ceph.git --suite-branch wip-50218 --limit 20  --filter ubuntu_latest.yaml --dry-run
...
2021-04-12 07:25:26,533.533 INFO:teuthology.suite.run:Suite rados:upgrade:pacific-x:rgw-multisite in /home/kchai/src/github.com_tchaikov_ceph_wip-50218/qa/suites/rados/upgrade/pacific-x/rgw-multisite generated 2 jobs (not yet filtered)
2021-04-12 07:25:26,549.549 INFO:teuthology.suite.run:Suite rados:upgrade:pacific-x:rgw-multisite in /home/kchai/src/github.com_tchaikov_ceph_wip-50218/qa/suites/rados/upgrade/pacific-x/rgw-multisite scheduled 0 jobs.
```

hmm, i am not able to schedule a ubuntu run...

**Review by cbodley — COMMENTED** [review]
thanks @tchaikov. can you please make the same change under suites/rgw/multisite/ ?

**Comment by cbodley** [comment]
we're seeing crashes in other rgw subsuites too. i'll raise a pr that fixes up the distro configurations

**Comment by cbodley** [comment]
i opened https://github.com/ceph/ceph/pull/40821 for this but it'll need some testing

**Comment by cbodley** [comment]
thanks @tchaikov! this merged with https://github.com/ceph/ceph/pull/40821

**Pull request closed without merging**
