### PR TITLE
mds/MDSRank: report state to mgr as mds id, not rank

### PR DESCRIPTION
**Pull request by liewegas**
Introduced by 625dffe65c0f8001b3b6ca6d0b12732a1a103849, which added
periodic scrub stats reporting.

Fixes: https://tracker.ceph.com/issues/42494
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@vshankar is there a reason this was using the rank instead of name to report state to the mgr?

**Comment by batrick** [comment]
Ah, I was about to test this same fix for https://tracker.ceph.com/issues/41525

I'll let you know if it works.

**Comment by batrick** [comment]
Also: `Fixes: https://tracker.ceph.com/issues/41525`

**Comment by batrick** [comment]
ping @ceph/dashboard

**Comment by tspmelo** [comment]
This fixes the problems I was having in the dashboard.

**Comment by batrick** [comment]
I'm working on tests for this PR, DNM.

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2019-10-30_18:44:51-fs-wip-pdonnell-testing-20191029.221350-distro-basic-smithi/

**Comment by batrick** [comment]
jenkins test make check

**Pull request merged**
