### PR TITLE
jewel: rgw: radosgw-admin data sync run crash

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/20715

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins re-test this please (`fatal: unable to access 'https://github.com/ceph/ceph.git/': Could not resolve host: github.com`)

**Comment by smithfarm** [comment]
Re-did the cherry-pick to resolve conflict with a recently merged PR.

**Comment by yehudasa** [comment]
@smithfarm lgtm

**Comment by smithfarm** [comment]
This passed an rgw suite at http://tracker.ceph.com/issues/20613#note-63

**Pull request merged**
