### PR TITLE
mds: remove snap past parents compat code

### PR DESCRIPTION
**Pull request by ukernel**
snap format change was introduced in Mimic release. It's long enough to
remove compat code.

Signed-off-by: "Yan, Zheng" <zyan@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
What happens if someone did not run the upgrade procedure for Mimic that scrubs the file system? Do we have a test to check for the old format and go damaged? What would be the suggested resolution if an operator accidentally does that?

**Comment by ukernel** [comment]
> What happens if someone did not run the upgrade procedure for Mimic that scrubs the file system? Do we have a test to check for the old format and go damaged? What would be the suggested resolution if an operator accidentally does that?

past parent snapshots get lost silently.  old format does not cause damage

**Comment by batrick** [comment]
> > What happens if someone did not run the upgrade procedure for Mimic that scrubs the file system? Do we have a test to check for the old format and go damaged? What would be the suggested resolution if an operator accidentally does that?
> 
> past parent snapshots get lost silently. old format does not cause damage

Alright, fine. Please note this in the commit message and add a release note warning.

**Comment by batrick** [comment]
jenkins test make check

**Comment by batrick** [comment]
@ukernel still has compile errors

**Review by batrick — DISMISSED** [review]
Fails QA:

````
2020-09-02T07:01:38.133 INFO:tasks.workunit:Stopping ['fs/snaps'] on client.0...
2020-09-02T07:01:38.134 INFO:teuthology.orchestra.run.smithi200:> sudo rm -rf -- /home/ubuntu/cephtest/workunits.list.client.0 /home/ubuntu/cephtest/clone.client.0
2020-09-02T07:01:43.126 INFO:tasks.ceph.mds.a.smithi200.stderr:  what():  std::bad_alloc
2020-09-02T07:01:43.127 INFO:tasks.ceph.mds.a.smithi200.stderr:*** Caught signal (Aborted) **
2020-09-02T07:01:43.127 INFO:tasks.ceph.mds.a.smithi200.stderr: in thread 7f10c9b58700 thread_name:MR_Finisher
2020-09-02T07:02:02.593 INFO:teuthology.orchestra.run.smithi060:> sudo logrotate /etc/logrotate.d/ceph-test.conf
2020-09-02T07:02:35.339 DEBUG:tasks.ceph:Missed logrotate, SSHException
2020-09-02T07:02:35.935 INFO:tasks.ceph.mon.a.smithi200.stderr:2020-09-02T07:02:35.598+0000 7f739c83a700 -1 mon.a@1(probing) e1 get_health_metrics reporting 54 slow ops, oldest is log(1 entries from seq 70 at 2020-09-02T06:38:08.114925+0000)
2020-09-02T07:02:36.655 INFO:tasks.ceph.mds.a.smithi200.stderr: ceph version 16.0.0-5036-g4542efba881 (4542efba881dc9884e38abfbf1a77991f6dda0e6) pacific (dev)
2020-09-02T07:02:36.656 INFO:tasks.ceph.mds.a.smithi200.stderr: 1: (()+0x128a0) [0x7f10d75578a0]
2020-09-02T07:02:36.656 INFO:tasks.ceph.mds.a.smithi200.stderr: 2: (gsignal()+0xc7) [0x7f10d664ff47]
2020-09-02T07:02:36.656 INFO:tasks.ceph.mds.a.smithi200.stderr: 3: (abort()+0x141) [0x7f10d66518b1]
2020-09-02T07:02:36.657 INFO:tasks.ceph.mds.a.smithi200.stderr: 4: (()+0x8c957) [0x7f10d7044957]
2020-09-02T07:02:36.657 INFO:tasks.ceph.mds.a.smithi200.stderr: 5: (()+0x92ae6) [0x7f10d704aae6]
2020-09-02T07:02:36.657 INFO:tasks.ceph.mds.a.smithi200.stderr: 6: (()+0x92b21) [0x7f10d704ab21]
2020-09-02T07:02:36.657 INFO:tasks.ceph.mds.a.smithi200.stderr: 7: (()+0x92d54) [0x7f10d704ad54]
2020-09-02T07:02:36.657 INFO:tasks.ceph.mds.a.smithi200.stderr: 8: (()+0x1424b) [0x7f10d777824b]
2020-09-02T07:02:36.658 INFO:tasks.ceph.mds.a.smithi200.stderr: 9: (tc_new()+0x283) [0x7f10d7799943]
2020-09-02T07:02:36.658 INFO:tasks.ceph.mds.a.smithi200.stderr: 10: (MDCache::do_realm_invalidate_and_update_notify(CInode*, int, bool)+0x21a) [0x55a17f60fd6a]
2020-09-02T07:02:36.658 INFO:tasks.ceph.mds.a.smithi200.stderr: 11: (Server::_mksnap_finish(boost::intrusive_ptr<MDRequestImpl>&, CInode*, SnapInfo&)+0xf2) [0x55a17f59ee72]
2020-09-02T07:02:36.658 INFO:tasks.ceph.mds.a.smithi200.stderr: 12: (MDSContext::complete(int)+0x52) [0x55a17f7f1232]
2020-09-02T07:02:36.658 INFO:tasks.ceph.mds.a.smithi200.stderr: 13: (MDSIOContextBase::complete(int)+0x233) [0x55a17f7f16e3]
2020-09-02T07:02:36.659 INFO:tasks.ceph.mds.a.smithi200.stderr: 14: (MDSLogContextBase::complete(int)+0x40) [0x55a17f7f1c50]
2020-09-02T07:02:36.659 INFO:tasks.ceph.mds.a.smithi200.stderr: 15: (Finisher::finisher_thread_entry()+0x195) [0x7f10d7c96085]
2020-09-02T07:02:36.659 INFO:tasks.ceph.mds.a.smithi200.stderr: 16: (()+0x76db) [0x7f10d754c6db]
2020-09-02T07:02:36.659 INFO:tasks.ceph.mds.a.smithi200.stderr: 17: (clone()+0x3f) [0x7f10d6732a3f]
````

From: /ceph/teuthology-archive/pdonnell-2020-09-02_03:56:20-fs-wip-pdonnell-testing-20200902.014855-distro-basic-smithi/5398797/teuthology.log

and a test failed doing subvolume flag configuration:

/ceph/teuthology-archive/pdonnell-2020-09-02_03:56:20-fs-wip-pdonnell-testing-20200902.014855-distro-basic-smithi/5398802/teuthology.log

Please do an fs run when you're done fixing.

**Comment by ukernel** [comment]
https://pulpito.ceph.com/zyan-2020-09-17_00:31:56-fs-wip-mds-snap-past-parents-testing-basic-smithi/

**Comment by ukernel** [comment]
jenkins retest this please

**Comment by ukernel** [comment]
jenkins test api

**Comment by ukernel** [comment]
jenkins retest this please

**Review by batrick — APPROVED** [review]

**Review by batrick — CHANGES_REQUESTED** [review]
I'm seeing this new failure:

````
2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5895-ge3a9554f/rpm/el8/BUILD/ceph-16.0.0-5895-ge3a9554f/src/include/interval_set.h: In function 'void interval_set<T, C>::insert(T, T, T*, T*) [with T = snapid_t; C = mempool::osdmap::flat_map]' thread 7ff272e82700 time 2020-09-24T20:53:22.245927+0000
2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5895-ge3a9554f/rpm/el8/BUILD/ceph-16.0.0-5895-ge3a9554f/src/include/interval_set.h: 495: FAILED ceph_assert(p->first > start+len)
2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr: ceph version 16.0.0-5895-ge3a9554f (e3a9554f85f926ca9d6cf59545ac390783fe8fc5) pacific (dev)
2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x158) [0x7ff2a5e585a8]
2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 2: ()
2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 3: ()
2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 4: ()
2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 5: ()
2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 6: (DispatchQueue::entry()+0x126a) [0x7ff2a6081b1a]
2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 7: (DispatchQueue::DispatchThread::entry()+0x11) [0x7ff2a6130d31]
2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 8: ()
2020-09-24T20:53:22.249 INFO:tasks.ceph.mgr.x.smithi073.stderr: 9: clone()
````

From: /ceph/teuthology-archive/pdonnell-2020-09-24_08:08:06-multimds-wip-pdonnell-testing-20200924.050041-distro-basic-smithi/5465521/teuthology.log

**Comment by ukernel** [comment]
> I'm seeing this new failure:
> 
> ```
> 2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5895-ge3a9554f/rpm/el8/BUILD/ceph-16.0.0-5895-ge3a9554f/src/include/interval_set.h: In function 'void interval_set<T, C>::insert(T, T, T*, T*) [with T = snapid_t; C = mempool::osdmap::flat_map]' thread 7ff272e82700 time 2020-09-24T20:53:22.245927+0000
> 2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-5895-ge3a9554f/rpm/el8/BUILD/ceph-16.0.0-5895-ge3a9554f/src/include/interval_set.h: 495: FAILED ceph_assert(p->first > start+len)
> 2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr: ceph version 16.0.0-5895-ge3a9554f (e3a9554f85f926ca9d6cf59545ac390783fe8fc5) pacific (dev)
> 2020-09-24T20:53:22.247 INFO:tasks.ceph.mgr.x.smithi073.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x158) [0x7ff2a5e585a8]
> 2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 2: ()
> 2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 3: ()
> 2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 4: ()
> 2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 5: ()
> 2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 6: (DispatchQueue::entry()+0x126a) [0x7ff2a6081b1a]
> 2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 7: (DispatchQueue::DispatchThread::entry()+0x11) [0x7ff2a6130d31]
> 2020-09-24T20:53:22.248 INFO:tasks.ceph.mgr.x.smithi073.stderr: 8: ()
> 2020-09-24T20:53:22.249 INFO:tasks.ceph.mgr.x.smithi073.stderr: 9: clone()
> ```
> 
> From: /ceph/teuthology-archive/pdonnell-2020-09-24_08:08:06-multimds-wip-pdonnell-testing-20200924.050041-distro-basic-smithi/5465521/teuthology.log

this is mgr crash, and is likely triggered by mgr/rbd_support/trash_purge_schedule. Nothing do with this PR

**Comment by ukernel** [comment]
no above issue

https://pulpito.ceph.com/zyan-2020-09-27_03:25:24-multimds-wip-mds-snap-past-parents-testing-basic-smithi/

**Comment by batrick** [comment]
I'll retest w/ #36004

**Comment by batrick** [comment]
Failures unrelated: https://pulpito.ceph.com/?branch=wip-pdonnell-testing-20200929.022151

**Review by batrick — APPROVED** [review]

**Pull request merged**
