### PR TITLE
mgr/dashboard:Update encryption and tags in bucket form

### PR DESCRIPTION
**Pull request by afreen23**
Fixes https://tracker.ceph.com/issues/65110

- renamed Security to Encryption
- aligned security fieldset with rest of the form using `cd-help-text` and aligning it with object locking in UX
- aligned security fieldset top use `cd-help-text`
- changed help text of Tags

[Screencast from 2024-03-25 14-14-23.webm](https://github.com/ceph/ceph/assets/25664409/4bb1d39f-6805-4848-a541-1964ed1fb1c1)

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by nizamial09 — APPROVED** [review]
There is a bug there, when I click on the Encryption checkbox, I'd expect atleast one of the item there to be selected by default, preferably the SSE-S3. But that's a separate issue.

**Comment by afreen23** [comment]
> There is a bug there, when I click on the Encryption checkbox, I'd expect atleast one of the item there to be selected by default, preferably the SSE-S3. But that's a separate issue.

The behavior I am seeing is that if no credentials are present then both of them are disabled.
Once I create one of the creds, they get selected by default

**Comment by afreen23** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test dashboard cephadm

**Comment by afreen23** [comment]
jenkins test dashboard cephadm

**Pull request merged**
