### PR TITLE
qa/tests: added --filter-out="ubuntu_14.04"

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
Won't this skip valuable unit tests?

**Comment by yuriw** [comment]
@djgalloway don't about nit tests.  Other option is to push the suite to `mimic`, but then I think we'll have to backport `luminous` related changes and I'd like to be using latest `luminous` bits

Let's get @jdurgin 's take

**Comment by djgalloway** [comment]
I guess, now that I've thought about it, we wouldn't support upgrading from any release to mimic on Trusty anyway so this makes sense.

**Comment by dillaman** [comment]
@yuriw I think your tracker ticket # is incorrect. What test is in the mimic or master branch is asking for Ubuntu 14.04?

**Comment by yuriw** [comment]
@dillaman removed tracker.  It's not tests it if you use line

`teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-luminous -k distro -e $CEPH_QA_EMAIL --suite-branch luminous"`

`teuthology-suite` is checking for builds for and cant find trusty and fails to schedule runs   https://pastebin.com/HFSApPD1
That's my understanding.

**Comment by yuriw** [comment]
as a mater of fact, this fix is needed for all `client-upgrade-*` suites, so added

**Comment by dillaman** [comment]
Is there any active release of Ceph that doesn't support Xenial? I wonder if we can just change the OS defaults in teuthology [1] (assuming that is the issue)?

[1] https://github.com/ceph/teuthology/blob/master/teuthology/suite/util.py#L142

**Comment by yuriw** [comment]
I think changing the OS defaults in teuthology is good idea @zmc FYI and ?

**Comment by tchaikov** [comment]
retest this please

**Comment by liewegas** [comment]
hrm where is 14.04 coming from? is teuthology randomly doing it, or is there a $ item in the suite that includes it?  (if its the latter, let's fix that...)

**Comment by yuriw** [comment]
I think $ is not in play here

**Comment by zmc** [comment]
I am also curious why we wouldn't just remove trusty from the yaml facets

**Comment by dillaman** [comment]
@zmc There aren't any -- this is just teuthology only checking for the existence of Trusty packages when determining which build to use.

**Comment by zmc** [comment]
@dillaman it doesn't do that for no reason:
```
$ grep -R 14.04 .
./luminous-client-x/basic/supported/ubuntu_14.04.yaml:os_version: "14.04"
./luminous-client-x/rbd/supported/ubuntu_14.04.yaml:os_version: "14.04"
```

**Comment by dillaman** [comment]
@zmc I suggest re-running your grep under the mimic branch since this change is talking about mimic build testing (although I agree trusty should be dropped from the master branch):

> [suites] $ git grep "14.04"
> buildpackages/any/tasks/release.yaml:# --suite buildpackages/any --ceph v10.0.1 --filter centos_7,ubuntu_14.04
> buildpackages/tests/tasks/release.yaml:# --suite buildpackages/tests --ceph v10.0.1 --filter centos_7.2,ubuntu_14.04

**Comment by dillaman** [comment]
Ah -- I didn't realize this was pulling suites from older branches

**Comment by zmc** [comment]
@dillaman in @yuriw's example, he's using `--suite-branch luminous`, maybe that's the actual issue?

**Comment by yuriw** [comment]
@zmc we made decision awhile ago to run client upgrades from respective named branches, this is true for all `client-upgrade-*` suites.
Here is how it look in `crontab`:

```
45 01 * * *  CEPH_BRANCH=mimic; MACHINE_NAME=ovh; /home/teuthology/bin/cron_wrapper teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-hammer -k distro -e $CEPH_QA_EMAIL --suite-branch hammer
47 01 * * *  CEPH_BRANCH=mimic; MACHINE_NAME=ovh; /home/teuthology/bin/cron_wrapper teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-jewel -k distro -e $CEPH_QA_EMAIL --suite-branch jewel
50 01 * * *  CEPH_BRANCH=mimic; MACHINE_NAME=ovh; /home/teuthology/bin/cron_wrapper teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-kraken -k distro -e $CEPH_QA_EMAIL --suite-branch kraken
50 01 * * *  CEPH_BRANCH=mimic; MACHINE_NAME=ovh; /home/teuthology/bin/cron_wrapper teuthology-suite -v -c $CEPH_BRANCH  -n 7 -m $MACHINE_NAME -s upgrade/client-upgrade-luminous -k distro -e $CEPH_QA_EMAIL --suite-branch luminous
```

IIRC  we used to have issues installing packages for older versions if we did not do that.
So that was a reason to run them like this.

**Comment by yuriw** [comment]
We still may have a problem I am afraid :(
So say we have on luminous branch for example this:

```
lrwxrwxrwx 1 yuriw yuriw   22 May 14 09:27 centos_latest.yaml -> ../all/centos_7.3.yaml
lrwxrwxrwx 1 yuriw yuriw   24 May 14 09:17 ubuntu_14.04.yaml -> ../all/ubuntu_14.04.yaml
lrwxrwxrwx 1 yuriw yuriw   24 May 11 08:53 ubuntu_latest.yaml -> ../all/ubuntu_16.04.yaml
```

then we filter out `ubuntu_14.04`, but in fact testing `mimic` we really want have more + `bionic`.

So @zmc I am thinking will it work if we instead of  `--filter-out="ubuntu_14.04` use a yaml fragment something like `os_mimic.yaml` and you it as extra argument with `teuthology-suite`.  Will it work better ?

**Comment by yuriw** [comment]
no @dillaman

**Comment by tchaikov** [comment]
@yuriw @dillaman luminous should have bionic build. and it builds on bionic now.

cc @alfredodeza .

**Pull request merged**
