### PR TITLE
mgr/dashboard: fix RBD namespace validation

### PR DESCRIPTION
**Pull request by navinbarnwal**
mgr/dashboard: fix RBD namespace validation

Just adding autocomplete: "off" prevented incorrect suggestions in Firefox.

Screenshot from 2021-04-23 14-44-55

Fixes: https://tracker.ceph.com/issues/46369
Signed-off-by: Navin Barnwal <knbarnwal@gmail.com>

### CODE REVIEW

**Comment by pereman2** [comment]
@navinbarnwal You should change the title to what the PR is trying to accomplish instead of the issue title and I'll remove `[Dashboard - Bug #46369] (Resolved)` since that does not follow the guidelines. Furthermore, you can check with `git log` examples. 

Other than that looks good. :+1:

**Comment by epuertat** [comment]
@navinbarnwal and don't forget to amend the [commit title too](https://github.com/ceph/ceph/pull/41008/commits): 
```diff
- [Dashboard - Bug #46369] (Resolved) mgr/dashboard: RBD namespace crea…
+ mgr/dashboard: fix RBD namespace validation
```

**Comment by navinbarnwal** [comment]
> @navinbarnwal You should change the title to what the PR is trying to accomplish instead of the issue title and I'll remove `[Dashboard - Bug #46369] (Resolved)` since that does not follow the guidelines. Furthermore, you can check with `git log` examples.
> 
> Other than that looks good.

Thank you for the advice. I updated the title as suggested by @epuertat .

**Comment by navinbarnwal** [comment]
> @navinbarnwal and don't forget to amend the [commit title too](https://github.com/ceph/ceph/pull/41008/commits):
> 
> ```diff
> - [Dashboard - Bug #46369] (Resolved) mgr/dashboard: RBD namespace crea…
> + mgr/dashboard: fix RBD namespace validation
> ```

Amend done, as asked !!

**Review by pereman2 — COMMENTED** [review]
@navinbarnwal Hey you should fix the git history, leaving only your changes. You could accomplish this by rebasing from master.

**Pull request closed without merging**
