### PR TITLE
mgr: fix crash due to multiple sessions from daemons with same name

### PR DESCRIPTION
**Pull request by trociny**
Don't assume perf counter instances are stable. If there are
multiple sessions from daemons reporting the same name (e.g. rgws),
the instances are cleared in DaemonServer::handle_open.
If the daemons have different counter names (for counters like
"objecter-0x55b6f4f1a630.op_active") it will throw out_of_range in
DaemonPerfCounters::update when accessing the instance removed by
another session.

The regression was introduced when adding avgcount support.

Fixes: https://tracker.ceph.com/issues/36244
Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by rjfd** [comment]
@trociny I think the solution for this problem should be different from your implementation. 

The reason why we're getting perf counter instance types that were not previously declared is because there are two different service instances (for instance, two RGW daemons) that use the same cephx client to connect to the cluster, and both services are registered into the same entry in the service map because the key in the service map is built from the service name and the client id.

I think we should prevent the registration of a second service instance if there is already one instance with the same key registered, or change the way we generate the service key to avoid this conflicts when services use the same cephx client to connect.

**Comment by trociny** [comment]
@rjfd Agreed than in log term we should fix mgr to prevent the registration of a second service instance if there is already one instance with the same key registered.

But please note, in the dc415f1ae the decision was made to allow mgr to work (not crash) when there are multiple sessions with the same name. And it was stated there that the solution was until  we prevent such multiple sessions. But in 1164ef2f32 a regression was introduced that made it crash again. So consider it just as a fixup for 1164ef2f32 (which is also backported to luminuos).

As for your proposal, I will be glad if someone implement this and we will be able to get rid off this workaround, but I did not have plans to work on this right now. The fact that we had 1164ef2f32 instead of just preventing multiple sessions suggested to me that it was not trivial. Probably the problem is how to recognize that the open comes from a new service and not it is not just reopen by the same service?

**Comment by rjfd** [comment]
@trociny thanks for your explanation! In that case, disregard my comment.

And yes, I also think that preventing multiple sessions is not trivial.

**Comment by trociny** [comment]
The comment added.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-01-01_02:34:49-rados-wip-kefu2-testing-2019-01-01-0117-distro-basic-smithi/

**Pull request merged**
