### PR TITLE
cmake: find GIT_VER variables if there is no .git dir

### PR DESCRIPTION
**Pull request by alimaredia**
find CEPH_GIT_VER & CEPH_GIT_NICE_VER if there is no
ceph/.git dir by parsing ceph/src/.git_version.

scenario is for building from source tarballs generated
by make-dist, since make-dist generates .git_version
by running make_version, and then packs .git_version
into the tarball.

Signed-off-by: Ali Maredia <amaredia@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
lgtm

**Comment by alfredodeza** [comment]
@alimaredia this looks like it could just be cherry-picked since it was already merged into kraken? ( c5c6b59f296f0ace3a6cfd939027118e82ab50a4 )

**Comment by alimaredia** [comment]
@alfredodeza i just cherry-picked that commit onto master and made this branch. Isn't that what you're suggesting?

**Comment by alfredodeza** [comment]
cherry-picked into master (eab4664287ed8f8013b488d7a71e11ee70a7d4d1)

**Pull request closed without merging**
