### PR TITLE
qa/tasks/vstart_runner: fix unicode decode error

### PR DESCRIPTION
**Pull request by lxbsz**
Traceback (most recent call last):
  File "../qa/tasks/vstart_runner.py", line 1544, in <module>
    exec_test()
  File "../qa/tasks/vstart_runner.py", line 1405, in exec_test
    if mount.is_mounted():
  File "/data/ceph/qa/tasks/cephfs/fuse_mount.py", line 191, in is_mounted
    proc.wait()
  File "../qa/tasks/vstart_runner.py", line 179, in wait
    out, err = out.decode(), err.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 46: ordinal not in range(128)

Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
another approach is probably https://github.com/kshtsk/ceph/pull/1, which is (presumably) a part of https://github.com/ceph/ceph/pull/32262 . .

**Comment by kshtsk** [comment]
> another approach is probably [kshtsk#1](https://github.com/kshtsk/ceph/pull/1), which is (presumably) a part of #32262 . .

yeh, the patch https://github.com/ceph/ceph/pull/32262/commits/98d788c7e94f57da14115afc4fa25698a773d5f3 is supposed to address this issue:

**Comment by lxbsz** [comment]
> > another approach is probably [kshtsk#1](https://github.com/kshtsk/ceph/pull/1), which is (presumably) a part of #32262 . .
> 
> yeh, the patch [98d788c](https://github.com/ceph/ceph/commit/98d788c7e94f57da14115afc4fa25698a773d5f3) is supposed to address this issue:

That's cool :-)
Thanks

**Comment by tchaikov** [comment]
@lxbsz does 49592af4005808db4ed5301e9072525bd709f44a address your issue ?

**Comment by lxbsz** [comment]
> @lxbsz does [49592af](https://github.com/ceph/ceph/commit/49592af4005808db4ed5301e9072525bd709f44a) address your issue ?

Yeah, it works for my test case. Will close it.
Thanks,

**Pull request closed without merging**
