### PR TITLE
rbd: specify the snap_name during image open if needed

### PR DESCRIPTION
**Pull request by yangdongsheng**
Signed-off-by: Dongsheng Yang <dongsheng.yang@easystack.cn>

### CODE REVIEW

**Comment by dillaman** [comment]
lgtm

**Comment by dillaman** [comment]
http://qa-proxy.ceph.com/teuthology/jdillaman-2016-11-07_00:13:39-rbd-wip-jd-testing-distro-basic-smithi/528491/teuthology.log

With this change, running "rbd info image@<missing snapshot name>" no longer returns a nice error message about a missing snapshot. Instead, it states that the image is missing. This results in a test failure.

**Comment by yangdongsheng** [comment]
@dillaman Okey, the error message of ```rbd info --snap snap image1``` changed from ```error setting snap ``` to ```error opening image```.

There is an idea to pass a callback to open() to get the state of opening state machine, then give user a better message. But that means we have to make OpenRequest and rbd tool to share a enum of opening states. I am afraid this is not a good thing. And I don't think that's worthy for a cleanup. 

Or, just change the unittest for the new manner?

Or, close this patch, just keep what it was? I think this option is good enough now. it works well currently.

What's your suggestion?

**Comment by trociny** [comment]
May be just change the open error message
```
std::cerr << "rbd: error opening image " << image_name << ...
```
to something like
```
std::cerr << "rbd: error opening " << image_name << (snap_name.empty() ? "" : "@" + snap_name) << ... 
```
?

**Comment by yangdongsheng** [comment]
Yes, this was an option to me, but I am not sure  is this unittest 
introduced to ensure some backward compatibility.
If application is relaying on this kind of output of rbd command, we 
will break it.

**Comment by trociny** [comment]
I don't think this check was a backward compatibility test (so just update the test accordingly). I think the main point is to have a useful and not confusing message.

And sure let's wait for Jason opinion.

**Comment by yangdongsheng** [comment]
Yes, Mykola, agree with you. ;-)

**Comment by dillaman** [comment]
@yangdongsheng I'm fine w/ the change so long as the error message isn't confusing. I also think there was an librbd-internal error message being printed to the console, so that message would need to get downgraded from a ```lderr``` to an ```ldout```

**Comment by yangdongsheng** [comment]
@dillaman error message updated. But about the lderr downgrading, do you mean this one? https://github.com/ceph/ceph/blob/master/src/librbd/image/OpenRequest.cc#L471

If yes, I think this error is printed in log and there is exactly an error happend in setting snap, so I think we can keep it as lderr.

although there is already a similar error printed in console, this kind of error message in ceph.log can help us to find more details about addressing the problem. and lderr can make sure this message will not be missed by user. That means, I think the error message printed in console should not affect the messages in ceph.log. @dillaman @trociny What's you opinion?

**Comment by dillaman** [comment]
@yangdongsheng Yes, that is probably the one. The issue is that std::cout/cerr and lderr will get intermingled on the console and it's a terrible user experience for issues that are very likely to occur (like fat fingering an image or snapshot name).

**Comment by yangdongsheng** [comment]
@dillaman Okey, sounds a general problem about std::cerr in rbd tool and lderr in librbd. But if we change the lderr in librbd to ldout, this would affect other api for librbd, such as python-binding. can we prevent lderr in console by some means?

**Comment by dillaman** [comment]
@yangdongsheng ... or we just take the approach that this cleanup is causing more work than is worthwhile

**Comment by yangdongsheng** [comment]
@dillaman  Haha, yes, it's just a cleanup ;-)

**Pull request closed without merging**
