### PR TITLE
mon: consider pool size when creating pool

### PR DESCRIPTION
**Pull request by songbaisen**
Mon: When create pool use the crush rule we should consider the pool size

Fixes: #14509
Signed-off-by: song baisen song.baisen@zte.com.cn

### CODE REVIEW

**Comment by liewegas** [comment]
Can you please add a simple test to one of the scripts in test/ that verifies this works as expected?

**Comment by songbaisen** [comment]
@tchaikov Thanks for your reply.I have remove the prefix i.But in our code we like use the prefix like i,f,d,s.m_...

**Comment by songbaisen** [comment]
@liewegas  Thank you! I will add it later.

**Comment by songbaisen** [comment]
@liewegas Hi! I have upload the test script.Please review it.Thandk you!

**Comment by liewegas** [comment]
This doesn't compile.. *ss instead of ss, at least.

Please make sure this builds and passes 'make check'.  Thanks!

**Comment by songbaisen** [comment]
@liewegas. sorry,It is may be the reason my code is 0.94 not the new node.I have check it ok in 0.94。After the spring day I will do it in the new code.

**Comment by songbaisen** [comment]
@liewegas  Hi! The ceph code change is really day and night quickly.I have update my code to the new one. @branch-predictor  Hi! Do you know why  in here  this function change '&' to '*'.In my eyes use '&' is more better than '*'.Thank you!

**Pull request merged**
