### PR TITLE
mon/OSDMonitor: skip prime_pg_temp if mapping is prior to osdmap

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by xiexingguo** [comment]
lgtm

**Comment by xiexingguo** [comment]
We(@runsisi  together with me) spent whole day to figure it out, sigh...

**Comment by tchaikov** [comment]
@xiexingguo yeah. but the upside is, we nailed it down before going to production!

**Comment by runsisi** [comment]
LGTM

**Comment by yuriw** [comment]
ready for merge

http://pulpito.ceph.com/yuriw-2017-04-27_22:07:22-rados-wip-yuri-testing_2017_4_28_2-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-04-27_22:07:22-rados-wip-yuri-testing_2017_4_28_2-distro-basic-smithi/

**Pull request merged**
