### PR TITLE
qa/tests: Wip ceph deploy upgrade

### PR DESCRIPTION
**Pull request by vasukulkarni**
for the master branch upgrade from jewel(stable) -> luminous(stable) -> master

### CODE REVIEW

**Comment by liewegas** [comment]
@vasukulkarni what's teh status of this?

**Comment by vasukulkarni** [comment]
@liewegas will retest and update.

**Comment by vasukulkarni** [comment]
Seeing 2 genuine issues : 

a) CentOS transaction error http://tracker.ceph.com/issues/22304
b)  kraken -> luminous mgr upgrade issue: http://tracker.ceph.com/issues/21122

**Comment by yuriw** [comment]
@vasukulkarni did you run tests ?

**Comment by tchaikov** [comment]
@vasukulkarni could you add a "Reviewed-by" line when merging approved PRs next time? thanks.

**Pull request merged**
