### PR TITLE
debian systemd support; /etc/{sysconfig,default}/ceph; easy jemalloc enablement

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@javacruft Is this sane?

**Comment by ktdreyer** [comment]
I think the tarball generation scripts are going to exclude this new top-level "`etc`" directory? Can we just put this new sysconfig file into the top-level "`systemd`" directory?

**Comment by liewegas** [comment]
On Fri, 4 Sep 2015, Ken Dreyer wrote:
> I think the tarball generation scripts are going to exclude this new top-level "etc" directory? Can we just put this new sysconfig file into the
> top-level "systemd" directory?

You mean make_dist.sh?  It won't ignore it..

Note that there is already stuff in etc (for suse firewall).  My hope was 
to move to having the files where they actually live, but there's still a 
ton of stuff that's scattered in strange places so we're a long way away 
from that...

**Comment by ktdreyer** [comment]
Oh, ok, good deal.

**Comment by liewegas** [comment]
you're right, missing from current tarball.. fixed

**Comment by liewegas** [comment]
it works!

**Comment by liewegas** [comment]
@dachary can you review please?

**Comment by dachary** [comment]
@ktdreyer could you take a look ? That's a lot of RPM packaging related changes and I don't feel confortable reviewing this on my own.

@liewegas could you add the URL of the job that passed ? Or was it manual testing ?

**Comment by liewegas** [comment]
I did both manual tests and ceph-deploy:

http://pulpito.ceph.com/sage-2015-09-10_16:33:52-ceph-deploy-wip-debian-systemd---basic-vps/

**Comment by ktdreyer** [comment]
Other than changing `%config` to `%config(noreplace)`, looks good to me!

**Comment by ktdreyer** [comment]
"ceph.spec: install /etc/sysconfig/ceph" is missing the `%config` line altogether?

**Comment by liewegas** [comment]
oops, https://github.com/ceph/ceph/pull/5896

**Pull request merged**
