### PR TITLE
nautilus: mgr/dashboard: edit/clone/copy rbd image after its data is received

### PR DESCRIPTION
**Pull request by alfonsomthd**
backport tracker: https://tracker.ceph.com/issues/42589

---

Fixes: https://tracker.ceph.com/issues/42561
 Signed-off-by: Alfonso Martínez <almartin@redhat.com>
 (cherry picked from commit da72765d8eda4d24c265658295f959423d2c657e)

---

updated using ceph-backport.sh version 15.0.0.6612

### CODE REVIEW

**Comment by callithea** [comment]
@tspmelo: The dashboard tests failed with:
`[08:19:18] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 76`
I've seen this on other backport PRs as well, not sure if some dev dependencies need an update?

**Comment by alfonsomthd** [comment]
> @tspmelo: The dashboard tests failed with:
> `[08:19:18] E/launcher - session not created: This version of ChromeDriver only supports Chrome version 76`
> I've seen this on other backport PRs as well, not sure if some dev dependencies need an update?

https://tracker.ceph.com/issues/42607#note-2

**Comment by LenzGr** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
jenkins test dashboard

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by smithfarm** [comment]
@LenzGr feel free to add "needs-qa" and "nautilus-batch-1" once this passes the ceph dashboard tests

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
QA run [WIP]:
- http://pulpito.ceph.com/laura-2019-11-18_15:26:14-rados:dashboard-wip-laura-testing-dashboard-nautilus-batch-4-distro-basic-mira/

**Pull request merged**
