### PR TITLE
mgr/deepsea: return ganesha and iscsi endpoint URLs

### PR DESCRIPTION
**Pull request by tserong**
This updates describe_service() to include nfs and iscsi services
(deepsea internally refers to these as "ganesha" and "igw" roles).
Additionally, if deepsea sets any of container_id, service, version,
rados_config_location, service_url, status or status_desc, these will
come through now too.

This relies on https://github.com/SUSE/DeepSea/pull/1606 for the new
functionality, but if run against an older version of deepsea, it will
continue to operate as it did before, it just won't include
rados_config_location or service_url data.

Signed-off-by: Tim Serong <tserong@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tserong** [comment]
@rjfd, do you mind trying this out, in conjunction with https://github.com/SUSE/DeepSea/pull/1606? It's enough to copy srv/modules/runners/mgr_orch.py from the DS PR, and deepsea/module.py from this PR, to a live system, then restart ceph-mgr. You can verify the lower layers are working as follows:

```# salt-run mgr_orch.describe_service  --out=json
{
   [...]
    "data4.ceph": {
        "igw": {
            "service_instance": "data4",
            "service_url": "http://admin:admin@172.16.1.24:5000"
        },
        "ganesha": {
            "service_instance": "data4",
            "rados_config_location": "rados://cephfs_data/ganesha/conf-data4"
        }
    },
    [...]
}
```

```# ceph orchestrator service ls
iscsi data4 data4.ceph None None None
[...]
nfs data4 data4.ceph None None rados://cephfs_data/ganesha/conf-data4
```

The `ceph orchestrator service ls` output only includes radosgw_config_url, not service_url, hence nothing interesting being shown for the iSCSI Gateway.

If this all works, try the Dashboard. I've run into three problems myself:

1) It's hideously slow; each call the dashboard makes to describe_service means a salt runner invocation, so if I go to the iSCSI page, then click the Targets tab, it fifteen seconds for the empty list of targets to apper, then another 15 seconds for the list to populate. Clearly I need to add some form of caching to the orchestrator module, or this is going to be unusable.

2) You may need to also apply this patch to the dashboard:

```diff --git a/src/pybind/mgr/dashboard/services/iscsi_config.py b/src/pybind/mgr/dashboard/services/iscsi_config.py
index df6537c0c5..657503214b 100644
--- a/src/pybind/mgr/dashboard/services/iscsi_config.py
+++ b/src/pybind/mgr/dashboard/services/iscsi_config.py
@@ -85,7 +85,7 @@ class IscsiGatewaysConfig(object):
             config = {'gateways': {}}
             instances = OrchClient.instance().list_service_info("iscsi")
             for instance in instances:
-                config['gateways'][instance.nodename] = {
+                config['gateways'][instance.service_instance] = {
                     'service_url': instance.service_url
                 }
         return config```

Without that change, I get a 500 internal server error on the iSCSI screen, and the following in ceph-mgr's log:

```Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cptools.py", line 237, in wrap
    return self.newhandler(innerfunc, *args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 88, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/__init__.py", line 649, in inner
    ret = func(*args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/__init__.py", line 842, in wrapper
    return func(*vpath, **params)
  File "/usr/share/ceph/mgr/dashboard/controllers/iscsi.py", line 106, in list
    target = IscsiTarget._config_to_target(target_iqn, config)
  File "/usr/share/ceph/mgr/dashboard/controllers/iscsi.py", line 462, in _config_to_target
    ips = IscsiClient.instance(gateway_name=host).get_ip_addresses()['data']
  File "/usr/share/ceph/mgr/dashboard/services/iscsi_client.py", line 31, in instance
    gateways_config = IscsiGatewaysConfig.get_gateway_config(gateway_name)
  File "/usr/share/ceph/mgr/dashboard/services/iscsi_config.py", line 97, in get_gateway_config
    raise IscsiGatewayDoesNotExist(name)
dashboard.services.iscsi_config.IscsiGatewayDoesNotExist: iSCSI gateway 'data4' does not exist
```

It's possible this is due to my /etc/hosts config, which includes `172.16.1.24     data4-public data4 data4.ceph`, so it may be confusion between short hostnames and FQDNs.

3) If I go to the NFS screen, I get a 500 internal server error and the following in ceph-mgr's log:

```Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python3.6/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cptools.py", line 237, in wrap
    return self.newhandler(innerfunc, *args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/services/exception.py", line 88, in dashboard_exception_handler
    return handler(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/__init__.py", line 649, in inner
    ret = func(*args, **kwargs)
  File "/usr/share/ceph/mgr/dashboard/controllers/__init__.py", line 842, in wrapper
    return func(*vpath, **params)
  File "/usr/share/ceph/mgr/dashboard/controllers/nfsganesha.py", line 257, in list
    for daemon_id in status_dict[cluster_id]
UnboundLocalError: local variable 'cluster_id' referenced before assignment```

I have no idea what's up with that. Is there something the orchestrator should be returning that it's not doing? Or has this code path in the dashboard not been exercised before?

**Comment by sebastian-philipp** [comment]
Fixes: http://tracker.ceph.com/issues/39095

**Comment by tserong** [comment]
Thanks for the reminder stalebot :-) This depends on #28213

**Comment by tserong** [comment]
OK, I think we're looking pretty good now. The dashboard patch I mentioned in a previous comment isn't necessary, and the `UnboundLocalError: local variable 'cluster_id' referenced before assignment` thing was fixed by 4de6aa51df

**Comment by sebastian-philipp** [comment]
http://pulpito.front.sepia.ceph.com/swagner-2019-07-26_06:59:31-rados:mgr-wip-swagner-testing-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
QA successful:

http://pulpito.ceph.com/swagner-2019-07-29_20:08:15-rados:mgr-wip-swagner-testing-distro-basic-smithi/

Known issues: #28840

**Pull request merged**
