### PR TITLE
ceph-volume/tests: update ansible environment variables in tox

### PR DESCRIPTION
**Pull request by dsavineau**
- update ANSIBLE_SSH_ARGS environment variable
- set ANSIBLE_CONFIG environment variable
- use pytest rerunfailures
- use ansible_facts

Fixes: https://tracker.ceph.com/issues/51849

Those changes should improve the overall ansible performance.

Signed-off-by: Dimitri Savineau <dsavinea@redhat.com>

### CODE REVIEW

**Comment by dsavineau** [comment]
jenkins test ceph-volume all

**Review by guits — CHANGES_REQUESTED** [review]
I think you need to update deploy.yml to use `ansible_facts`

**Comment by dsavineau** [comment]
> I think you need to update deploy.yml to use `ansible_facts`

yeah I saw that in the CI logs

**Comment by dsavineau** [comment]
jenkins test ceph-volume all

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Comment by dsavineau** [comment]
jenkins test make check

**Comment by dsavineau** [comment]
jenkins test ceph-volume lvm centos8-bluestore-dmcrypt

**Review by guits — APPROVED** [review]

**Pull request merged**
