### PR TITLE
bluestore, NVMEDEVICE: Specify the max io completion in conf

### PR DESCRIPTION
**Pull request by optimistyzy**
I do not think that 4 is meaninful. If a value needs to be determined,
it should be configured in the configuration file.

Signed-off-by: optimistyzy <optimistyzy@gmail.com>

### CODE REVIEW

**Comment by optimistyzy** [comment]
@yuyuyu101 @liupan1111

**Comment by liupan1111** [comment]
@optimistyzy , the default value is 0??

**Comment by optimistyzy** [comment]
Yes, default is 0. It means that let SPDK determine the max io completion number.

**Comment by liupan1111** [comment]
@optimistyzy I prefer you add a comment for this default 0... users maybe puzzled..

**Comment by optimistyzy** [comment]
@liupan1111 done

**Comment by optimistyzy** [comment]
@liupan1111 @yuyuyu101  Can this patch be merged?

**Pull request merged**
