### PR TITLE
DNM: jewel: object-map: batch updates during trim operation

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17843

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (general jenkins failure)

**Comment by dachary** [comment]
jenkins test this please (asok too long...)

**Comment by dachary** [comment]
@dillaman does this backport look good to merge ? It passed the rbd suite http://tracker.ceph.com/issues/17851#note-2 . Please note that it will not be in 10.2.4, reason why the target branch is jewel-next.

**Comment by dillaman** [comment]
While it looks good, can we hold this one for a little bit so that it gets more test time on master?

**Comment by dachary** [comment]
@dillaman thanks for the review, marking DNM. Will three weeks be enough ?

**Comment by dillaman** [comment]
Yeah, should be fine.

**Pull request closed without merging**
