### PR TITLE
mgr/cephadm: removing double quotes from the generated nvmeof config

### PR DESCRIPTION
**Pull request by rkachach**
Fixes: https://tracker.ceph.com/issues/62838

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
jenkins test windows

**Review by phlogistonjohn — APPROVED** [review]
I'm not sure if/how the nvmeof process intends to parse extra args with spaces in them as I assume the fix makes it difficult to know if a particular whitespace char is meant to be part of an option or a delimiter.
But since they don't currently parse JSON it seems like an OK fix to me... for now.

**Comment by rkachach** [comment]
> I'm not sure if/how the nvmeof process intends to parse extra args with spaces in them as I assume the fix makes it difficult to know if a particular whitespace char is meant to be part of an option or a delimiter. But since they don't currently parse JSON it seems like an OK fix to me... for now.

@phlogistonjohn yeah, that's right. Actually right now the nvmeof config file for other fields such as `transport_tcp_options` they use python dictionaries to get the parameters but in this case I think they just get what this field has and they pass it to a binary as input.

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2023-09-22_21:58:46-orch:cephadm-wip-adk-testing-2023-09-22-1218-distro-default-smithi/

reruns of failed/dead jobs: https://pulpito.ceph.com/adking-2023-09-23_15:59:19-orch:cephadm-wip-adk-testing-2023-09-22-1218-distro-default-smithi/

Failures:

- https://tracker.ceph.com/issues/59704, known issue
- https://tracker.ceph.com/issues/62958, known issue
- https://tracker.ceph.com/issues/62870, known issue

Nothing to block merging

**Pull request merged**
