### PR TITLE
rgw/cloud-transition: Fix issues with MCG endpoint

### PR DESCRIPTION
**Pull request by soumyakoduri**
Few s3 endpoints (like Noobaa MCG or AWS) may return BucketAlreadyOwned or BucketAlreadyExists error if the target path (configured for cloud transition) already exists. Do not fail transition in those cases.

Also fixed below issues -
* with racing lc threads, when one lc thread is trying to check and create the target bucket, others may go ahead with the object transition assuming target path exists.
* initialize few fields to avoid setting wrong content_len during transition

Fixes: https://tracker.ceph.com/issues/57979

Signed-off-by: Soumya Koduri <skoduri@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by soumyakoduri** [comment]
@cbodley @mattbenjamin I have included the fix for https://tracker.ceph.com/issues/57980 as well in this PR . Kindly review the changes.

**Comment by cbodley** [comment]
> These attributes' names cannot contain any special character ('-') if the target is to be stored on Azure backend (via s3 MCG).

@soumyakoduri this cloud transition feature targets s3, so i'd prefer not to change our data format based on noobaa's limitations with other cloud services. if we do eventually want to support azure, we wouldn't be using these x-amz-meta- headers

cloud transition was released in quincy, so users may have already written lots of objects to s3 with x-amz-meta- headers in the existing format. this change would break backward compatibility

**Comment by soumyakoduri** [comment]
> > These attributes' names cannot contain any special character ('-') if the target is to be stored on Azure backend (via s3 MCG).
> 
> @soumyakoduri this cloud transition feature targets s3, so i'd prefer not to change our data format based on noobaa's limitations with other cloud services. if we do eventually want to support azure, we wouldn't be using these x-amz-meta- headers
> 
> cloud transition was released in quincy, so users may have already written lots of objects to s3 with x-amz-meta- headers in the existing format. this change would break backward compatibility

Thanks Casey for raising it. I haven't thought about it. Also now I wonder that this issue may arise within MCG as well for the objects (with metadata keys containing special characters) being replicated/migrated from AWS(s3) stores to Azure. So it may better be handled by Noobaa.

**Comment by soumyakoduri** [comment]
http://pulpito.front.sepia.ceph.com/soumyakoduri-2022-11-22_17:04:48-rgw-wip-skoduri-cloudtier-fixes-distro-default-smithi/

**Comment by soumyakoduri** [comment]
jenkins test make check

**Comment by soumyakoduri** [comment]
jenkins test make check arm64

**Comment by soumyakoduri** [comment]
jenkins test windows

**Comment by soumyakoduri** [comment]
jenkins test windows

**Pull request merged**
