### PR TITLE
mgr/dashboard: rm nvmeof conf based on its daemon name

### PR DESCRIPTION
**Pull request by nizamial09**
don't remove an entire entry of a service from the config if only the daemon is removed, instead just remove the entry of that particular daemon. and once all the entry are succesfully removed, remove the entry for service

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by adk3798 — APPROVED** [review]

**Comment by adk3798** [comment]
@VallariAg can you include this in one of your nvmeof runs? I'm also going to schedule an orch run for this PR.

**Comment by adk3798** [comment]
> @adk3798, sure! I'm testing a fix for nvmeof suite so I can simply reuse your shaman build which includes this PR, please let me know how I can find it. thanks!

okay, I won't likely push a build until later today. I'll leave a link to it on this PR when I do. Note that it will include some other orch/cephadm PRs in the build

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test api

**Review by afreen23 — APPROVED** [review]
Works fine, tested the fix.

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Comment by afreen23** [comment]
jenkins test api

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-10-30_03:37:52-orch:cephadm-wip-adk-testing-2024-10-29-1832-distro-default-smithi/

Failures:
- 3x SMB ctdb test stray daemon / SELinux denial, known issue
- 2x failures on new tests for mgmt-gateway, caused by PR adding those new tests
- 3x mds_upgrade_sequence failures, known issue
- 1x staggered upgrade with agent failure, known issue

Dead Jobs:
- 1x `Error reimaging machines`, infra/teuthology issue
- 1x rgw-ingress test timeout, known issue
- 1x test_iscsi_container timeout. I've seen this before but thought it had been fixed. Will need to investigate.

Results should only block merging for PRs related to iscsi or mgmt-gateqay/oauth2-proxy. Otherwise, run was okay.

**Comment by adk3798** [comment]
@nizamial09 does this need a squid backport?

**Comment by nizamial09** [comment]
thanks for merging it @adk3798. opened the backport: https://github.com/ceph/ceph/pull/60604.

**Pull request merged**
