### PR TITLE
luminous: Change default upmap_max_deviation to 5

### PR DESCRIPTION
**Pull request by dzafman**
Backport
#32247

Tracker
https://tracker.ceph.com/issues/43532

Parent Tracker
https://tracker.ceph.com/issues/43312

## Checklist
- [x] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by dzafman** [comment]
@yuriw @neha-ojha If make check passes here, we are ready to go.

**Comment by neha-ojha** [comment]
@yuriw this is ready for you to test

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-01-10-1615-luminous](https://trello.com/c/0HhcTjYl/801-wip-yuri5-testing-2020-01-10-1615-luminous)

**Comment by neha-ojha** [comment]
@dzafman we should modify https://github.com/ceph/ceph/blob/luminous/PendingReleaseNotes#L252

**Pull request merged**
