### PR TITLE
nautilus: qa/standalone/misc/ok-to-stop: improve test

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/43772

---

NOTE: the second commit is in the process of being backported via https://github.com/ceph/ceph/pull/32844 but that should not be a problem.

---

backport of https://github.com/ceph/ceph/pull/32738
parent tracker: https://tracker.ceph.com/issues/43721

this backport was staged using ceph-backport.sh version 15.0.0.6950
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by dzafman** [comment]
Nautilus diverged, so this needs a rebase.

**Comment by jdurgin** [comment]
@dzafman it's just temporary while 14.2.7 is being cut as a hotfix - the branch will be restored afterwards and the many nautilus prs that now show conflicts will not need a rebase

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-02-08-1638-nautilus](https://trello.com/c/WGSzqecu/820-wip-yuri-testing-2020-02-08-1638-nautilus)

**Comment by yuriw** [comment]
@smithfarm Per @dzafman this needs corrections, pls add tags when done

**Comment by smithfarm** [comment]
closing in favor of https://github.com/ceph/ceph/pull/32844

**Pull request closed without merging**
