### PR TITLE
osd/ECTransaction: cleanup the redundant check which works in overwrite IO context

### PR DESCRIPTION
**Pull request by jimmyway**
Signed-off-by: tang.jin <tang.jin@istuary.com>

### CODE REVIEW

**Comment by jimmyway** [comment]
retest please

**Comment by jimmyway** [comment]
please retest

**Comment by jimmyway** [comment]
retest this please

**Comment by yuriw** [comment]
test this

**Comment by jimmyway** [comment]
@liewegas , I don't know what's difference between"arm64 make check" and "make check", please give me some advices about how to fix this kind of failed case. Should I learn all code related to test case?

**Comment by liewegas** [comment]
You can ignore the arm make check issues (it's new and not entirely 
stable).

**Comment by jimmyway** [comment]
@liewegas  OK ,thank you

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-26_14:37:54-rados-wip-sage-testing2-distro-basic-smithi/

**Pull request merged**
