### PR TITLE
mon/OSDMonitor: set Jewel, Kraken and Luminous flags in batch 

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@jecluis Thanks. 

Care to take a look again?

**Comment by jecluis** [comment]
@xiexingguo While this addresses the second point from my previous comment, do you mind walking us through why this is required considering 1. ?

**Comment by xiexingguo** [comment]
> do you mind walking us through why this is required considering 1. ?

Sorry, the previous commit message is wrong.
The only benefit from these changes is to keep pace with others.
Feel free to close if you don't think so....

**Comment by liewegas** [comment]
this will be obsoleted by https://github.com/ceph/ceph/pull/15068

**Pull request closed without merging**
