### PR TITLE
debian: let ceph-mgr depend on python-influxdb

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
this change should address http://pulpito.ceph.com/kchai-2018-04-23_07:38:14-rados-wip-kefu-testing-2018-04-23-1357-distro-basic-smithi/2430354/

**Comment by jcsp** [comment]
I don't mind adding the dependency for platforms where installing the influx module is easy, but the test is meant to pass without the dependency (module selftest shouldn't have dependencies).

Since we're now rejecting "enable" for can_run=false modules, we should update the test to pass --force to enable so that it can run selftest even if dependencies are missing.

**Comment by jcsp** [comment]
retest this please (jenkins)

Something went wrong in a pip download

**Comment by liewegas** [comment]
btw still see an error after this,
<pre>
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:======================================================================
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:ERROR: test_influx (tasks.mgr.test_module_selftest.TestModuleSelftest)
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-04-23-0831/qa/tasks/mgr/test_module_selftest.py", line 43, in test_influx
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:    self._selftest_plugin("influx")
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-04-23-0831/qa/tasks/mgr/test_module_selftest.py", line 29, in _selftest_plugin
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:    self.mgr_cluster.mon_manager.raw_cluster_cmd(module_name, "self-test")
2018-04-23T18:14:50.070 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-04-23-0831/qa/tasks/ceph_manager.py", line 1134, in raw_cluster_cmd
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:    stdout=StringIO(),
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/remote.py", line 193, in run
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 423, in run
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:    r.wait()
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 155, in wait
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:    self._raise_for_status()
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 177, in _raise_for_status
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:    node=self.hostname, label=self.label
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:CommandFailedError: Command failed on smithi149 with status 124: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph influx self-test'
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:
2018-04-23T18:14:50.071 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:Ran 1 test in 147.604s
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:FAILED (errors=1)
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:======================================================================
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:ERROR: test_influx (tasks.mgr.test_module_selftest.TestModuleSelftest)
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-04-23-0831/qa/tasks/mgr/test_module_selftest.py", line 43, in test_influx
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:    self._selftest_plugin("influx")
2018-04-23T18:14:50.072 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-04-23-0831/qa/tasks/mgr/test_module_selftest.py", line 29, in _selftest_plugin
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:    self.mgr_cluster.mon_manager.raw_cluster_cmd(module_name, "self-test")
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-sage3-testing-2018-04-23-0831/qa/tasks/ceph_manager.py", line 1134, in raw_cluster_cmd
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:    stdout=StringIO(),
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/remote.py", line 193, in run
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 423, in run
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:    r.wait()
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 155, in wait
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:    self._raise_for_status()
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_git_teuthology_master/teuthology/orchestra/run.py", line 177, in _raise_for_status
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:    node=self.hostname, label=self.label
2018-04-23T18:14:50.073 INFO:tasks.cephfs_test_runner:CommandFailedError: Command failed on smithi149 with status 124: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph influx self-test'
</pre>
/a/sage-2018-04-23_15:07:57-rados-wip-sage3-testing-2018-04-23-0831-distro-basic-smithi/2430983

expected?

**Comment by jcsp** [comment]
This isn't working because PyModuleRegistry skips starting modules when can_run=false.

I'll open a PR that tweaks the behaviour to get us back the ability to run the selftest bits.

**Comment by liewegas** [comment]
Should this get merged as a partial fix, or wait?

**Comment by jcsp** [comment]
See https://github.com/ceph/ceph/pull/21607

**Pull request closed without merging**
