### PR TITLE
qa/suites/rados/thrash-old-clients: update supported releases and distro

### PR DESCRIPTION
**Pull request by ljflores**
thrash-old-clients tests should only support N-3 releases. To fix this for
main, I have removed all releases < quincy and have added squid.

Also, we are fully switching to centos.9_stream packages/containers after
the centos.8_stream end of life, so I changed the distro from centos.8_stream
to centos.9_stream.

*** Note: If this commit is backported, it should be done in such a way that
only releases >= quincy reference centos.9_stream. For instance, if backporting to squid,
a reef/squid thrash test is okay to make references to centos.9_stream since both reef and
squid support this, but a pacific/squid test will have to take a different approach
since pacific does not support centos.9_stream.

Fixes: https://tracker.ceph.com/issues/66398

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins retest this please

**Comment by ljflores** [comment]
Before: https://pulpito.ceph.com/lflores-2024-06-07_17:38:05-rados:thrash-old-clients-main-distro-default-smithi/
After: https://pulpito.ceph.com/lflores-2024-06-07_17:41:06-rados:thrash-old-clients-main-distro-default-smithi/

**Comment by ljflores** [comment]
Before: https://pulpito.ceph.com/lflores-2024-06-07_17:38:05-rados:thrash-old-clients-main-distro-default-smithi/
After: https://pulpito.ceph.com/lflores-2024-06-10_22:43:28-rados:thrash-old-clients-main-distro-default-smithi/

**Review by athanatos — APPROVED** [review]
LGTM

**Comment by ljflores** [comment]
squid backport would look a little different; something like this:

https://github.com/ceph/ceph/compare/squid...ljflores:ceph:wip-tracker-66398-squid
https://pulpito.ceph.com/lflores-2024-06-11_01:32:14-rados:thrash-old-clients-squid-distro-default-smithi/

**Comment by ljflores** [comment]
jenkins test api

**Review by neha-ojha — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
Quincy backport handled in #58520

**Pull request merged**
