### PR TITLE
Done data pool

### PR DESCRIPTION
**Pull request by julpark-rh**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rakeshgm** [comment]
@julpark-rh can you paste the test logs that are passing

**Comment by julpark-rh** [comment]
RHEL 8.1

http://magna002.ceph.redhat.com/julpark-2020-02-26_18:35:10-krbd:rbd-nomount-nautilus-distro-basic-clara/361564/teuthology.log

**Comment by rakeshgm** [comment]
> RHEL 8.1
> 
> http://magna002.ceph.redhat.com/julpark-2020-02-26_18:35:10-krbd:rbd-nomount-nautilus-distro-basic-clara/361564/teuthology.log

I suggest you check on RHEL 7.7 also

**Comment by julpark-rh** [comment]
Okay I will check on RHEL 7.7 and will update it

**Comment by julpark-rh** [comment]
RHEL 7.7 Passed,

http://magna002.ceph.redhat.com/julpark-2020-03-06_17:23:25-krbd:rbd-nomount-nautilus-distro-basic-argo/362208/teuthology.log

**Pull request merged**
