### PR TITLE
luminous: PendingReleaseNotes: add note about upgrading MDS

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/23414

### CODE REVIEW

**Comment by smithfarm** [comment]
@theanalyst Do we use PendingReleaseNotes from luminous? I thought we only used it in master (even for stable branches)

**Comment by smithfarm** [comment]
I know release-notes.rst is only used in master. . . maybe it makes sense to have separate PendingReleaseNotes for luminous.

**Comment by theanalyst** [comment]
@smithfarm it is all adhoc right now, I use pendingrelease notes for major announcements in backport releases as well. Though in this particular case editing the existing blog for 12.2.4 and adding an announcement in 12.2.5 mail makes sense I guess

**Comment by pdvian** [comment]
@smithfarm added new section 12.2.5 with new release note

**Pull request merged**
