### PR TITLE
ceph.spec.in: fix mgr-cephadm CherryPy requirement for SUSE builds

### PR DESCRIPTION
**Pull request by tserong**
Commit 78983ad0d0c added cherrypy to ceph-mgr-cephadm's Requires,
but this needs to be split out into distro-specific sections due
to subtle/irritating naming differences.

Signed-off-by: Tim Serong <tserong@suse.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [x] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tserong** [comment]
(I'm just waiting for an openSUSE build to double-check I've got this right, hence the DNM tag)

**Comment by tserong** [comment]
Yup, that works.

**Review by smithfarm — APPROVED** [review]
Yeah, we already use the same construct for BuildRequires and for the `ceph-mgr-dashboard` package. This was just an oversight. Thanks for fixing it!

**Comment by smithfarm** [comment]
nit: please consider adding a Fixes line as follows:

```
Fixes: 78983ad0d0cce422da32dc4876ac186f6d32c3f5
```

**Review by mgfritch — APPROVED** [review]

**Review by adk3798 — APPROVED** [review]

**Comment by tserong** [comment]
> nit: please consider adding a Fixes line to the commit message as follows:
> 
> ```
> Fixes: 78983ad0d0cce422da32dc4876ac186f6d32c3f5
> ```

Done!

**Pull request merged**
