### PR TITLE
jewel: Enable/Disable of features is allowed even the features are already enabled/disabled

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17482

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please (unittest_throttle failed and does not seem to be related to this pr)

**Comment by dachary** [comment]
jenkins test this please (src/test/cli/osdmaptool/test-map-pgs.t: failed)

**Comment by dachary** [comment]
@dillaman does this backport look good to merge ? It passed the rbd suite http://tracker.ceph.com/issues/17487#note-17 (except for two dead nbd jobs)

**Comment by dillaman** [comment]
👍

**Pull request merged**
