### PR TITLE
qa: fs:upgrade test starts with pacific 16.2.5

### PR DESCRIPTION
**Pull request by vshankar**
Not sure if this test really needs to start an upgrade from v16.2.4 (there
is nothig in commit history that mentions it), but running with a distro
kernel which probably does not understand `disable_send_metrics=on' will
result in MDS crash as v16.2.4 MDS aborts with

           ceph version 16.2.4 (3cbe25cde3cfa028984618ad32de9edc4c1eaed0) pacific (stable)
           1: (ceph::__ceph_abort(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xe5) [0x7fc7327f0cdc]
           2: (operator<<(std::ostream&, ClientMetricType const&)+0x10e) [0x7fc732a7542e]
           3: (MClientMetrics::print(std::ostream&) const+0x1a1) [0x7fc732a75601]
           4: (DispatchQueue::pre_dispatch(boost::intrusive_ptr<Message> const&)+0x710) [0x7fc732a28c30]
           5: (DispatchQueue::entry()+0xdeb) [0x7fc732a2a69b]
           6: (DispatchQueue::DispatchThread::entry()+0x11) [0x7fc732adab71]
           7: /lib64/libpthread.so.0(+0x814a) [0x7fc73159214a]
           8: clone()

when the MDS does not understand a certain metric type.

Fixes: http://tracker.ceph.com/issues/54459
Signed-off-by: Venky Shankar <vshankar@redhat.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ljflores** [comment]
jenkins retest this please

**Review by ajarr — COMMENTED** [review]
If there are kclients that don't understand 'disable_send_metrics=on', then there is no way to upgrade from 16.2.4 to the latest version of Ceph?

Is upgrade testing of v16.2.5 a special case of upgrade testing from pacific to latest? I understand that upgrading from v16.2.4 is special because v16.2.4 MDS crashes if kclient doesn't disable metrics.  If v16.2.5 is not a special case, why not rely on "0-from/pacific.yaml", and just remove "0-from/v16.2.4.yaml" ?

**Comment by vshankar** [comment]
> If there are kclients that don't understand 'disable_send_metrics=on' and MDS encounters unknown metric type, then there is no way to upgrade from 16.2.4 to the latest version of Ceph?
> 
> Is upgrade testing of v16.2.5 a special case of upgrade testing from pacific to latest? I understand that upgrading from v16.2.4 is special because v16.2.4 MDS crashes if kclient doesn't disable metrics. If v16.2.5 is not a special case, why not rely on "0-from/pacific.yaml", and just remove "0-from/v16.2.4.yaml" ?

That's the reason I mention in the commit message that there is isn't a reason mentioned anywhere (in commit history) why upgrading from 16.2.4 was added. The fix to disable sending metrics was added as a follow up commit when upgrading from 16.2.4 crashes the mds. If testing this particular case (crashing the mds) was the objective to add the the upgrade test, then disabling metrics _should_ have been added earlier.

**Comment by vshankar** [comment]
IOW, if anyone can point me to some commit (or a discussion) that prompted adding upgrade from 16.2.4 for testing that the mds does not crash, I'll be happy to remote this yaml.

**Comment by ajarr** [comment]
> > If there are kclients that don't understand 'disable_send_metrics=on' and MDS encounters unknown metric type, then there is no way to upgrade from 16.2.4 to the latest version of Ceph?
> > Is upgrade testing of v16.2.5 a special case of upgrade testing from pacific to latest? I understand that upgrading from v16.2.4 is special because v16.2.4 MDS crashes if kclient doesn't disable metrics. If v16.2.5 is not a special case, why not rely on "0-from/pacific.yaml", and just remove "0-from/v16.2.4.yaml" ?
> 
> That's the reason I mention in the commit message that there is isn't a reason mentioned anywhere (in commit history) why upgrading from 16.2.4 was added. 

Spent some time investigation further... Upgrade test from v16.2.4 was added to test the following 2 issues, 

```
If a v16.2.4 or older MDS fails and rejoins, the compat set assigned to it is the empty set (because it sends no compatset in its beacons). This prevents cephadm upgrade process from proceeding because the mons can do no replacement.

See: /ceph/teuthology-archive/sage-2021-11-03_12:41:33-orch:cephadm:mds_upgrade_sequence-wip-sage3-testing-2021-11-02-1033-distro-basic-smithi/6481266/teuthology.log
```
Source: https://tracker.ceph.com/issues/53150

and
```
MDSMonitor: assertion during upgrade to v16.2.5+ 
```
Source: https://tracker.ceph.com/issues/53155

So there is significance around testing upgrade from pre v16.2.5 releases. 

> The fix to disable sending metrics was added as a follow up commit when upgrading from 16.2.4 crashes the mds. If testing this particular case (crashing the mds) was the objective to add the the upgrade test, then disabling metrics _should_ have been added earlier.

The issue around kernel client crashing v16.2.4 MDS if metrics wasn't disabled for the client was discovered later https://tracker.ceph.com/issues/53293 , and hence fixed later with https://github.com/ceph/ceph/commit/dcda5cb9ce52. The fix was to set this on kclient 
```
sudo modprobe ceph disable_send_metrics=on
```
But as per your findings, there seem to be kclients that don't understand the above. I guess Patrick missed addressing the scenario?

I can only infer that upgrade of file systems with MDS earlier than v16.2.5 will fail if there are kclients that don't understand the option disable_send_metrics=on.

**Comment by ajarr** [comment]
I don't get how introducing upgrading testing from v16.2.5 (https://github.com/ceph/ceph/pull/45242/commits/6451f4eda761fe441e31efc497f01d338d1a6e2c ) fixes the issues around upgrade testing from v16.2.4? Is upgrade testing of v16.2.5 a special case of upgrade testing from pacific to latest?  If v16.2.5 is not a special case, why not rely on "0-from/pacific.yaml", and just remove "0-from/v16.2.4.yaml" ?

**Comment by vshankar** [comment]
> I don't get how introducing upgrading testing from v16.2.5 ([6451f4e](https://github.com/ceph/ceph/commit/6451f4eda761fe441e31efc497f01d338d1a6e2c) ) fixes the issues around upgrade testing from v16.2.4? Is upgrade testing of v16.2.5 a special case of upgrade testing from pacific to latest? If v16.2.5 is not a special case, why not rely on "0-from/pacific.yaml", and just remove "0-from/v16.2.4.yaml" ?

The issue is when upgrading from 16.2.4 is used with distro kernel which *may* not understand disable_send_metrics. That would result in such kclients sending metrics to the MDSs. The MDSs had a bug which would result in a crash iff it received a metric type that it doesn't understand. This was fixed in 16.2.5.

So, it looks like upgrading from 16.2.4 was added for testing another case and not the MDS crash due to the bug I mention above (which was later found).

**Comment by vshankar** [comment]
So, this is boiling down the question of having to test upgrade from a specific release vs using the latest release available.

One reason why we _may_ want to keep upgrading from 16.2.X yaml would be to test the scenario you mention about a bug when upgrading to 16.2.5+. If we want to keep that we could ensure that we do not use the distro kernel, or, drop this test altogether (having a slightly less coverage).

**Comment by ajarr** [comment]
> So, this is boiling down the question of having to test upgrade from a specific release vs using the latest release available.
> 

The question is do we need to test upgrade from v16.2.5 in addition to testing upgrades from latest pacific (which will be a version >= 16.2.7) 

> One reason why we _may_ want to keep upgrading from 16.2.X yaml would be to test the scenario you mention about a bug when upgrading to 16.2.5+. If we want to keep that we could ensure that we do not use the distro kernel, or, drop this test altogether (having a slightly less coverage).

Are you referring to https://tracker.ceph.com/issues/53155 ? If so it happens when upgrading from version earlier than 16.2.5 to a version 16.2.5 or later. So testing upgrade from v16.2.5 won't help?

**Comment by vshankar** [comment]
> Are you referring to https://tracker.ceph.com/issues/53155 ? If so upgrade error happens when upgrading from a version earlier than 16.2.5 to a version >= 16.2.5. So testing upgrade from v16.2.5 won't help?

You are probably correct. The absence of a linked tracker/commit in the PR that added the test confused me. Thanks for the archaeological git dig.

This means we really should preserve testing from 16.2.4 by not testing against a distro kernel.

**Review by batrick — CHANGES_REQUESTED** [review]
Sorry there should be a comment: we really **do** want to test v16.2.4 upgrades as there were a number of bugs (at least 3!) for upgrades spanning v16.2.4 - v16.2.[5+]. This was a result of MDSMap changes so that standbys would no longer need shut down during MDS upgrades.

I'm surprised by

> but running with a distro kernel which probably does not understand `disable_send_metrics=on' will result in MDS crash as v16.2.4 MDS aborts with

That was working well. Maybe @jtlayton has an idea why it no longer continues to do so? Suggest looking at the teuthology log and dmesg output for the kernel client.

**Comment by batrick** [comment]
Also, in general we should be testing upgrades in our QA suite from old versions of a release. For example, I wish we had testing for v16.2.0 to the latest pacific HEAD. Or, v16.2.0 to master.

**Comment by batrick** [comment]
It looks like it never actually ran the `modprobe` command!

```
2022-02-24T04:35:36.988 INFO:teuthology.run_tasks:Running task pexec...
2022-02-24T04:35:37.005 INFO:teuthology.task.pexec:Executing custom commands...
2022-02-24T04:35:37.005 INFO:teuthology.task.pexec:Running commands on host ubuntu@smithi080.front.sepia.ceph.com
2022-02-24T04:35:37.006 DEBUG:teuthology.orchestra.run.smithi080:> TESTDIR=/home/ubuntu/cephtest bash -s
2022-02-24T04:35:37.007 INFO:teuthology.task.pexec:Running commands on host ubuntu@smithi136.front.sepia.ceph.com
2022-02-24T04:35:37.007 DEBUG:teuthology.orchestra.run.smithi136:> TESTDIR=/home/ubuntu/cephtest bash -s
2022-02-24T04:35:37.155 DEBUG:teuthology.parallel:result is None
2022-02-24T04:35:37.224 DEBUG:teuthology.parallel:result is None
```

!! I'm not sure if it's because "clients" doesn't match any role for the `pexec` task. This may be a peculiarity of cephadm with `pexec`?

**Comment by lxbsz** [comment]
@vshankar @batrick @ajarr Just saw this PR, I fixed it in https://github.com/ceph/ceph/pull/45370.

It's because the mgr will mount 2 user space clients during the upgrade, I am still not sure what they are doing. I have add on option in libcephfs to disable sending the metrics during upgrade.

**Comment by lxbsz** [comment]
> It looks like it never actually ran the `modprobe` command!
> 
> ```
> 2022-02-24T04:35:36.988 INFO:teuthology.run_tasks:Running task pexec...
> 2022-02-24T04:35:37.005 INFO:teuthology.task.pexec:Executing custom commands...
> 2022-02-24T04:35:37.005 INFO:teuthology.task.pexec:Running commands on host ubuntu@smithi080.front.sepia.ceph.com
> 2022-02-24T04:35:37.006 DEBUG:teuthology.orchestra.run.smithi080:> TESTDIR=/home/ubuntu/cephtest bash -s
> 2022-02-24T04:35:37.007 INFO:teuthology.task.pexec:Running commands on host ubuntu@smithi136.front.sepia.ceph.com
> 2022-02-24T04:35:37.007 DEBUG:teuthology.orchestra.run.smithi136:> TESTDIR=/home/ubuntu/cephtest bash -s
> 2022-02-24T04:35:37.155 DEBUG:teuthology.parallel:result is None
> 2022-02-24T04:35:37.224 DEBUG:teuthology.parallel:result is None
> ```
> 
> !! I'm not sure if it's because "clients" doesn't match any role for the `pexec` task. This may be a peculiarity of cephadm with `pexec`?

From the new tracker, the modprobe ran:

This are from the `kern.log`

```
2022-02-21T18:58:07.436001+00:00 smithi107 kernel: Key type dns_resolver registered
2022-02-21T18:58:07.481513+00:00 smithi107 kernel: Key type ceph registered
2022-02-21T18:58:07.481568+00:00 smithi107 kernel: libceph: loaded (mon/osd proto 15/24)
2022-02-21T18:58:07.562993+00:00 smithi107 kernel: ceph: loaded (mds proto 32)

```

I didn't see the logs like:

```
Mar 14 14:48:52 lxbceph1 kernel: Key type ceph unregistered
Mar 14 14:48:52 lxbceph1 kernel: Key type dns_resolver unregistered
```

Which will remove the loaded `ceph.ko` and `libceph.ko` before modprobing them with the `disable_send_metrics=on`. That means these two modules were not loaded.

**Comment by vshankar** [comment]
> @vshankar @batrick @ajarr Just saw this PR, I fixed it in #45370.
> 
> It's because the mgr will mount 2 user space clients during the upgrade, I am still not sure what they are doing. I have add one option in libcephfs to disable sending the metrics during upgrade.

That should fix the crash with user-space clients (instances in mgr plugins). In another run (I need to dig the run link) I could see:
```
unknown paramater 'disable_send_metrics'
```

which is really weird.

**Comment by lxbsz** [comment]
> > @vshankar @batrick @ajarr Just saw this PR, I fixed it in #45370.
> > It's because the mgr will mount 2 user space clients during the upgrade, I am still not sure what they are doing. I have add one option in libcephfs to disable sending the metrics during upgrade.
> 
> That should fix the crash with user-space clients (instances in mgr plugins). In another run (I need to dig the run link) I could see:
> 
> ```
> unknown paramater 'disable_send_metrics'
> ```
> 

It should be using old kernel version ? What's the kernel version ?

> which is really weird.

**Comment by vshankar** [comment]
> It should be using old kernel version ? What's the kernel version ?
> 
> With old kernel if we still see this crash, please see how many clients are there ? Maybe also caused by the user space clients from mgr.

I do not have the run link nor can I find it out. It was one of Yuri's run.

The crash _could_ be due to user-space, but the modprobe warning is what's really confusing. We use the testing kernel for teuthology runs so we may not see this, but Yuri uses distro kernels, so there is a good chance we'll run into it again.

**Comment by lxbsz** [comment]
> > It should be using old kernel version ? What's the kernel version ?
> > With old kernel if we still see this crash, please see how many clients are there ? Maybe also caused by the user space clients from mgr.
> 
> I do not have the run link nor can I find it out. It was one of Yuri's run.
> 
> The crash _could_ be due to user-space, but the modprobe warning is what's really confusing. We use the testing kernel for teuthology runs so we may not see this, but Yuri uses distro kernels, so there is a good chance we'll run into it again.

Yeah, since the old kernel won't send the any metric to MDSes, and it also won't support this module parameter. So we need to see what has happened. Today I have checked and test the kclient code in different cases, didn't see any issue with the metric related code yet.

**Comment by vshankar** [comment]
Given that we really need to test with 16.2.4 (@batrick explanation), we should close this pr and see if we run into the crash again in Yuri's run. User-space fixes by Xiubo would cleanup the mds crashes leaving the only possibility that a really old kernel can crash it...

**Pull request closed without merging**
