### PR TITLE
mempool: Add string container to mempools.

### PR DESCRIPTION
**Pull request by allensamuels**
Signed-off-by: Allen Samuels <allen.samuels@sandisk.com>

### CODE REVIEW

**Comment by liewegas** [comment]
@allensamuels can you rebase on master and force push?

**Comment by allensamuels** [comment]
Rebased.

**Comment by jcsp** [comment]
@allensamuels I don't know what happened with your rebase but I think you got a lot more commits than you meant to!

**Comment by allensamuels** [comment]
Yes, I’m a git neophyte and screwed it up. I’ll try to fix it today.

Allen Samuels
SanDisk |a Western Digital brand
2880 Junction Avenue, Milpitas, CA 95134
T: +1 408 801 7030| M: +1 408 780 6416
allen.samuels@SanDisk.com<mailto:allen.samuels@SanDisk.com>

**Comment by tchaikov** [comment]
@allensamuels ping?

**Comment by liewegas** [comment]
https://github.com/ceph/ceph/pull/12651

**Pull request closed without merging**
