### PR TITLE
rgw/multisite: fixes assertion failure during realm reload

### PR DESCRIPTION
**Pull request by smanjara**
This reverts commit 30cbf6691bf2006fae21cb4626b440aec2068659.

https://tracker.ceph.com/issues/62298

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @smanjara. revert commits need your signed-off-by too

**Comment by smanjara** [comment]
the changes from #51772 inadvertently introduced a bug in `RGWRemoteDataLog::finish() `, where invoking http_manager stop() before calling RGWCoroutinesManager::stop() prevented the completion notifiers from shutting down correctly. The backtrace can be found in the tracker attached.

@caisan I haven't been able to reproduce the original issue you have described in #51772. Please consider adding reproducer steps to the pr along with debug enabled logs, so we can try to find a solution for it.

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2023-09-20_13:28:54-rgw-wip-cbodley-testing-distro-default-smithi/; multisite tests failed but didn't crash

**Comment by cbodley** [comment]
good to merge once checks pass

**Comment by cbodley** [comment]
jenkins test api

**Pull request merged**
