### PR TITLE
FileStore: correctly handle the case when getting spill out xattr fails

### PR DESCRIPTION
**Pull request by wonzhq**
Failing to get the spill out xattr doesn't mean xattr is spilled out.

Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
AFAR, the original meaning should be correct. We need to fallback to "spillo out" if we can't find existing "XATTR_SPILL_OUT_NAME".

**Comment by wonzhq** [comment]
If it is true, there still might be a problem. When the return value is -ENODATA, which means we can't find the spill out xattr, we fall back to spill out. But what if chain_fgetxattr returns some other error values?

**Comment by yuyuyu101** [comment]
If other error, current impl is a crude behavior and it's ok to retry I think.

**Comment by liewegas** [comment]
Yeah, we need to make sure we check for spill out if the attr is missing.  Masking other errors should be safe.. i don't think it's worth the code to check for them.

**Pull request closed without merging**
