### PR TITLE
include/rados/librados.h: note that {read,write}_op cannot be reused

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
see also https://github.com/ceph/ceph/blob/1bfdd2c1c2baa364d9b61b5f73775162da787172/src/osdc/Objecter.h#L2973-L2977

**Comment by tchaikov** [comment]
cc @phlogistonjohn

**Review by badone — APPROVED** [review]
LGTM

**Comment by badone** [comment]
jenkins test api

**Comment by phlogistonjohn** [comment]
This is extremely helpful, thanks!

It means a bit more work for me to fix up the go-ceph wrapper for these functions, but it will be worth it. :-)

**Pull request merged**
