### PR TITLE
luminous: osdc/Objecter: update op_target_t::paused in _calc_target

### PR DESCRIPTION
**Pull request by ashishkumsingh**
http://tracker.ceph.com/issues/37553

### CODE REVIEW

**Comment by smithfarm** [comment]
The second commit is cosmetic only? Not needed to fix the bug?

**Comment by ashishkumsingh** [comment]
> The second commit is cosmetic only? Not needed to fix the bug?
@smithfarm yeah, the second commit it mostly added for cosmetic reasons. It was discussed and linked to the master PR, so I cherry-picked here too.

**Comment by xiexingguo** [comment]
> The second commit is cosmetic only? Not needed to fix the bug?

@smithfarm It's good to include the second commit as it makes the code much easier to understand.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-01-10-1638-luminous](https://trello.com/c/ovZAXVnN/506-wip-yuri4-testing-2019-01-10-1638-luminous)

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-01-12-0019-luminous](https://trello.com/c/0HBFzpZq/509-wip-yuri4-testing-2019-01-12-0019-luminous)

**Pull request merged**
