### PR TITLE
pacific: client: buffer the truncate if we have the Fx caps

### PR DESCRIPTION
**Pull request by lxbsz**
backport tracker: https://tracker.ceph.com/issues/55192

---

backport of https://github.com/ceph/ceph/pull/43286
parent tracker: https://tracker.ceph.com/issues/16739

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
jenkins retest this please

**Review by jtlayton — APPROVED** [review]

**Comment by jtlayton** [comment]
jenkins test docs

**Comment by vshankar** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
@lxbsz I suspect this PR broke the build:

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=bionic,DIST=bionic,MACHINE_SIZE=gigantic/63092//consoleFull

`fuse.dir/ceph_fuse.cc.o -c /build/ceph-16.2.9-144-gd8d210f8/src/ceph_fuse.cc
In file included from /build/ceph-16.2.9-144-gd8d210f8/src/messages/MOSDFastDispatchOp.h:8:0,
                 from /build/ceph-16.2.9-144-gd8d210f8/src/messages/MOSDOp.h:21,
                 from /build/ceph-16.2.9-144-gd8d210f8/src/osdc/Objecter.h:56,
                 from /build/ceph-16.2.9-144-gd8d210f8/src/osdc/ObjectCacher.h:17,
                 from /build/ceph-16.2.9-144-gd8d210f8/src/client/Client.h:38,
                 from /build/ceph-16.2.9-144-gd8d210f8/src/ceph_fuse.cc:25:
/build/ceph-16.2.9-144-gd8d210f8/src/osd/osd_types.h: In member function 'void object_ref_delta_t::mut_ref(const hobject_t&, int)':
/build/ceph-16.2.9-144-gd8d210f8/src/osd/osd_types.h:5551:35: warning: unused variable '_' [-Wunused-variable]
     [[maybe_unused]] auto [iter, _] = ref_delta.try_emplace(hoid, 0);
                                   ^
make[4]: Leaving directory '/build/ceph-16.2.9-144-gd8d210f8/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:1438: recipe for target 'src/CMakeFiles/ceph-fuse.dir/all' failed`

**Comment by lxbsz** [comment]
> @lxbsz I suspect this PR broke the build:
> 
> https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=bionic,DIST=bionic,MACHINE_SIZE=gigantic/63092//consoleFull
> 
> `fuse.dir/ceph_fuse.cc.o -c /build/ceph-16.2.9-144-gd8d210f8/src/ceph_fuse.cc In file included from /build/ceph-16.2.9-144-gd8d210f8/src/messages/MOSDFastDispatchOp.h:8:0, from /build/ceph-16.2.9-144-gd8d210f8/src/messages/MOSDOp.h:21, from /build/ceph-16.2.9-144-gd8d210f8/src/osdc/Objecter.h:56, from /build/ceph-16.2.9-144-gd8d210f8/src/osdc/ObjectCacher.h:17, from /build/ceph-16.2.9-144-gd8d210f8/src/client/Client.h:38, from /build/ceph-16.2.9-144-gd8d210f8/src/ceph_fuse.cc:25: /build/ceph-16.2.9-144-gd8d210f8/src/osd/osd_types.h: In member function 'void object_ref_delta_t::mut_ref(const hobject_t&, int)': /build/ceph-16.2.9-144-gd8d210f8/src/osd/osd_types.h:5551:35: warning: unused variable '_' [-Wunused-variable] [[maybe_unused]] auto [iter, _] = ref_delta.try_emplace(hoid, 0); ^ make[4]: Leaving directory '/build/ceph-16.2.9-144-gd8d210f8/obj-x86_64-linux-gnu' CMakeFiles/Makefile2:1438: recipe for target 'src/CMakeFiles/ceph-fuse.dir/all' failed`

Rebased it now.

**Pull request merged**
