### PR TITLE
rgw: add storing and reading total usage information

### PR DESCRIPTION
**Pull request by oshynsong**
There are problems for the current rgw usage data storing and reading implementation:
  1. The usage data will be accumulating to a large amount by time. If we delete the history usage data by the "trim usage" API, we will lost the history data permanently if the usage data of the rgw user or bucket is critical for the application(such as billing each API).
  2. Current rgw usage data is storing in a record and accumulated by each hour, we can not get more details data or even real-time usage data to construct the monitoring facility by prometheus and grafana.
  3. We can also use the current implementation to construct the monitoring facility by sum all each-hour data, but it will generate high overhead if the history data grows too large.
I add the code to store the total usage data in one record, and it can be read by the "read usage" API.

Fixes: https://tracker.ceph.com/issues/35687
Signed-off-by: Oshyn Song dualyangsong@gmail.com

### CODE REVIEW

**Comment by oshynsong** [comment]
I implement the `radosgw_exporter`(see here https://github.com/oshynsong/radosgw_exporter), and it depends on the total usage data of rgw.

**Comment by mattbenjamin** [comment]
unstale me

**Comment by oshynsong** [comment]
@mattbenjamin I am the author of this pull request, and I have used this feature in my product to monitor the radosgw service along with the `radosgw_exporter`(see https://github.com/oshynsong/radosgw_exporter). Can ask you for a code review?

**Comment by theanalyst** [comment]
@oshynsong Can you create this PR against master. Normally features/bug fixes are first developed and applied on master first before they can be backported to other release branches.

**Comment by oshynsong** [comment]
@theanalyst I change the PR against the master branch, but there are some conflicts need to resolve.

**Pull request closed without merging**
