### PR TITLE
crimson/os/seastore/async_cleaner: avoid trimming backrefs when reclaiming space

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Fixes: https://tracker.ceph.com/issues/56535
Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by cyx1231st** [comment]
IIUC there are 3 reasons leading to the record-size-exceed-max issue when try to trim the alloc buffers in cache:
1. Reclaim potentially needs to trim the alloc tail beyond the target `get_backref_tail()` -- even may near to the journal head.
2. The control `config.rewrite_backref_bytes_per_cycle` cannot be applied in reclaiming.
3. The upper-hard-limit of the alloc tail is the dirty tail, which is too long if 1. wants to trim the alloc-tail near to the journal head.

I'm not sure whether 1. and 2. can be addressed easily. But if not, probably introducing a `max_backref_inflight_segments` just like `max_journal_segments` can be simpler. What do you think @xxhdx1985126 @athanatos ?

**Comment by xxhdx1985126** [comment]
> I'm not sure whether 1. and 2. can be addressed easily. But if not, probably introducing a `max_backref_inflight_segments` just like `max_journal_segments` can be simpler. What do you think @xxhdx1985126 @athanatos ?

This PR resolves 1.

I think users may not be able to set `max_backref_inflight_segments` to a correct value easily, as that involves carefully calculating. I think a configuration item shouldn't work in such a way that, once not set appropriately, the system crashes.

And I'm not quite sure whether we should add another block point for io transactions, in addtion to journal trimming and space reclaiming.

I'll try to add more comments to the code, so it's more readable.

**Comment by xxhdx1985126** [comment]
After a second thought, I think `max_backref_inflight_segments` might be necessary to limit the size of the backref cache, since we have to set `max_journal_segments` to a large value to lower the conflict rate.

But I still think this PR is necessary to fix the issue once and for all.

**Comment by xxhdx1985126** [comment]
Sorry, it seems that merging backrefs may not have to be mandate for reclaiming space any longer, I'll try to drop the backref merge in space reclamation

**Comment by xxhdx1985126** [comment]
@cyx1231st I changed the strategy to completely avoid trimming backrefs when reclaiming space, this should resolve the issue thoroughly.

**Comment by xxhdx1985126** [comment]
jenkins test make check

**Comment by xxhdx1985126** [comment]
jenkins test make check

**Comment by xxhdx1985126** [comment]
Done:-)

**Pull request merged**
