### PR TITLE
cmake: bump project version to 18.0.0 for reef

### PR DESCRIPTION
**Pull request by cbodley**
just to get the ball rolling for reef. i see that Sage did this last year for quincy in https://github.com/ceph/ceph/pull/39039, along with lots of additional changes

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by neha-ojha — APPROVED** [review]

**Comment by cbodley** [comment]
i added another commit that should make 'ceph version' identify itself as reef

**Comment by cbodley** [comment]
this prevents vstart.sh from coming up:
```
Populating config ...
2022-04-12T13:52:01.057+0000 7fec85348700  0 monclient(hunting): authenticate timed out after 300
...
[errno 110] RADOS timed out (error connecting to the cluster)
```
not sure where the gap is (ceph-mon or messenger?), so i'll close this until someone has a chance to work through the issues

**Comment by leseb** [comment]
@cbodley is it worth re-opening and rebasing this to see if CI passes? Thanks

**Comment by cbodley** [comment]
same failure from 'ceph API tests':
```
...
2022-05-18T16:16:11.301+0000 7f4dd357e700  0 monclient(hunting): authenticate timed out after 300
[errno 110] RADOS timed out (error connecting to the cluster)
```
trying without the second librados commit

**Review by jdurgin — APPROVED** [review]

**Comment by travisn** [comment]
@cbodley Is this ready for merge? Thanks!

**Comment by cbodley** [comment]
> @cbodley Is this ready for merge? Thanks!

i'm not sure, i don't think it's been tested. does this PR do what rook needs it to?

**Comment by travisn** [comment]
> > @cbodley Is this ready for merge? Thanks!
> 
> i'm not sure, i don't think it's been tested. does this PR do what rook needs it to?

All rook needs is to detect the reef v18. Looking at the history it looks like the last update for pacific in #39039 also included a lot of other CI work, but I assume that's not necessary for the basic version update.

**Comment by jdurgin** [comment]
jenkins test api

**Comment by travisn** [comment]
> still seeing these failures:
> 
> ```
> 2022-06-22T04:43:06.036+0000 7f1a6bfff700  0 monclient(hunting): authenticate timed out after 300
> [errno 110] RADOS timed out (error connecting to the cluster)
> ```

@cbodley Could it be an intermittent failure or it's consistent?

**Comment by cbodley** [comment]
> @cbodley Could it be an intermittent failure or it's consistent?

i believe we saw it pass at least once

**Comment by travisn** [comment]
> > @cbodley Could it be an intermittent failure or it's consistent?
> 
> i believe we saw it pass at least once

Does that mean it's not a blocker to get this merged? Or shall we run it again for more peace of mind? Just hoping to get this merged soon.

**Comment by cbodley** [comment]
> Does that mean it's not a blocker to get this merged? Or shall we run it again for more peace of mind? Just hoping to get this merged soon.

i've never seen those `RADOS timed out` failures from vstart, so this PR must be breaking something important. it needs debugging

**Comment by travisn** [comment]
@rzarzynski Thanks for taking a look

**Comment by rzarzynski** [comment]
Just sent #47458 which includes the commits from this PR.

**Comment by cbodley** [comment]
thanks @rzarzynski! :heart:

**Pull request closed without merging**
