### PR TITLE
quincy: mgr/cephadm: support for regex based host patterns

### PR DESCRIPTION
**Pull request by adk3798**
Backport of https://github.com/ceph/ceph/pull/53803

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by phlogistonjohn — APPROVED** [review]

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-07-24_12:36:52-orch:cephadm-wip-adk5-testing-2024-07-23-1249-quincy-distro-default-smithi/

run of iscsi tests after additional patch was added: https://pulpito.ceph.com/adking-2024-07-25_11:07:08-orch:cephadm-wip-adk5-testing-2024-07-23-1249-quincy-distro-default-smithi/

Not counting the failed iscsi test that passed with the additional patch, failures were:

- 1 `test_non_existent_cluster ` failure, known issue, just missing a backport to update the test
- All other failures were test_cephadm, test_cephadm_repos, or mds_upgrade_sequence. All failed trying to pull packages that did not exist. This is mostly fallout of the move to centos 9. These tests are trying to do things like pull pacific packages for centos 9, or main branch builds on ubuntu focal, which don't exist. Unfortunate, but not worth blocking merging PRs in the run. The issues are more so with the tests than the ceph build itself.

**Comment by adk3798** [comment]
jenkins retest this please

**Comment by adk3798** [comment]
jenkins test make check

**Comment by adk3798** [comment]
jenkins test make check

**Pull request merged**
