### PR TITLE
mgr/dashboard: fix error when typing existing paths in the Ganesha form

### PR DESCRIPTION
**Pull request by bk201**
- The `CephFS.ls_dir()` implementation in the backend had changed, the code in the
      UI endpoint `/ui-api/nfs-ganesha/lsdir` needs to adapt.
- Add fs_name as resource_id in `/ui-api/nfs-ganesha/lsdir/<fs_name>` to distinguish FS.
- Add more checks and unit tests.

Fixes: https://tracker.ceph.com/issues/47372
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by LenzGr** [comment]
> The `CephFS.ls_dir()` implementation in the backend had changed

Just wondering: could you identify what exactly changed and when? Any PR/commit ID that introduced the change?

**Comment by bk201** [comment]
> > The `CephFS.ls_dir()` implementation in the backend had changed
> 
> Just wondering: could you identify what exactly changed and when? Any PR/commit ID that introduced the change?

Sure, it's introduced in this #32552. I also updated the tracker issue.
(https://github.com/ceph/ceph/commit/e753d987e5a1a5ccd9b4989801a00c4b4ad75fc2#diff-fcc3f3566305de26b32e1383cae5388fR86-R88)

**Comment by callithea** [comment]
jenkins test dashboard

**Review by Devp00l — APPROVED** [review]
LGTM

**Comment by bk201** [comment]
jenkins test api

**Comment by bk201** [comment]
jenkins test api

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-10-03_09:43:24-rados-wip-kefu-testing-2020-10-03-1611-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-10-04_04:38:32-rados-wip-kefu-testing-2020-10-03-1611-distro-basic-smithi/

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-36449-37064-37375/) [WIP]
- QA run [PENDING]

**Comment by callithea** [comment]
- [New pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-36449-37064-37375-37449/)
- [QA run](https://pulpito.ceph.com/laura-2020-10-08_09:25:00-rados:dashboard-wip-laura-testing-36449-37064-37375-37449-distro-basic-smithi/)

**Review by callithea — APPROVED** [review]

**Pull request merged**
