### PR TITLE
[DNM] Rgw socket backlog for hammer

### PR DESCRIPTION
**Pull request by diluga**
(cherry picked from commit d56bdf93ced6b80b07397d57e3fa68fe68304432)

    RGW: add socket backlog setting for via ceph.conf
    http://tracker.ceph.com/issues/16406

### CODE REVIEW

**Comment by smithfarm** [comment]
@diluga No, this is not correct. First, wait until #9891 is merged into master. Then the backport will be done by cherry-picking the commit from #9891 into a wip branch based on jewel.

Anyway, it's too early to do a backport because we don't know when, or in what form, the master commit will be merged.

**Comment by diluga** [comment]
sorry，but this commit is only for hammer(not jewel),so i cherry-picking with branch (hammer 0.94.7).

**Comment by smithfarm** [comment]
I understand. But we don't cherry-pick the branch. We make a new branch based on the `hammer` branch and then cherry-pick the master commit (3e4df83 in this case) **into** the working branch and then open a PR against `hammer`. But we don't do this until the master PR has been merged, OK?

**Comment by diluga** [comment]
get it! thx!

**Pull request closed without merging**
