### PR TITLE
rgw: check for timestamp for s3 keystone auth

### PR DESCRIPTION
**Pull request by dachary**
backport of https://github.com/ceph/ceph/pull/2993

### CODE REVIEW

**Comment by theanalyst** [comment]
@dachary probably 8b3dfc9472022ea45ad24e02e0aa21dfdad798f8 should be superseded by the commit cbf0691b4a57574d7e8d2cfc61a6b40af3a99e93 which fixes an issue introduced by the commit. So that should also make the backport

**Comment by valerytschopp** [comment]
I agree with @theanalyst the commit  cbf0691 should be used, it fixes all the issues.

**Comment by dachary** [comment]
@theanalyst @valerytschopp thanks for the quick review :-) I'll close this one since http://tracker.ceph.com/issues/10698 is the better solution( also added a note at http://tracker.ceph.com/issues/10062#note-14 )

**Comment by theanalyst** [comment]
@dachary I guess cherry picking PRs #2993 and #3551 should close the entire thing

**Comment by dachary** [comment]
I'll keep https://github.com/ceph/ceph/pull/2993 in this pull request. @theanalyst will you create a new pull request with https://github.com/ceph/ceph/pull/3551 backport ?

**Comment by theanalyst** [comment]
sure, will do

**Comment by theanalyst** [comment]
@dachary created #3966 to backport #3551

**Pull request merged**
