### PR TITLE
tests - Added yaml fragmet to cover testing

### PR DESCRIPTION
**Pull request by yuriw**
... for http://tracker.ceph.com/issues/21660#note-17

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-10-09_21:25:22-upgrade:kraken-x:parallel-wip-yuriw-21660-luminous-distro-basic-smithi/

**Comment by dillaman** [comment]
Tests failed w/ "error: unknown option 'pool init test'" -- that command only exists in >= Luminous rbd CLI releases. Does the upgrade test need to go into the kraken or jewel branch instead?

**Comment by yuriw** [comment]
@dillaman yes I did change branch to be kraken, see latest tests passed.

**Comment by dillaman** [comment]
Ah -- I clicked the link in my email which was for the original, failed tests.

**Pull request merged**
