### PR TITLE
luminous: mgr/dashboard_v2: #2 - dashboard_v1 replacement

### PR DESCRIPTION
**Pull request by epuertat**
This PR includes the dashboard_v2 as per #23271 and adds the necessary commits to reach the point where dashboard_v1 was replaced by dashboard_2.

Fixes: http://tracker.ceph.com/issues/24788 # wip-dashboard_v2-luminous
Fixes: http://tracker.ceph.com/issues/34319

Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

### CODE REVIEW

**Comment by epuertat** [comment]
Jenkins: retest this please

**Comment by epuertat** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
hey @epuertat the dashboard v2 changes are not backported yet. did you close this PR on purpose?

**Comment by epuertat** [comment]
@tchaikov, yes, this was intended. These 4 backporting PRs are accumulative: the 3rd one (#24026) already contains all the changes of #23271 and #23804, and the 4th one was never meant to hit luminous (as it went beyond mimic parity). We were tidying up the dashboard PR queue, so this will help!

**Pull request closed without merging**
