### PR TITLE
osd/PG: re-write of _update_calc_stats and improve pg degraded state

### PR DESCRIPTION
**Pull request by dzafman**
Fixes: http://tracker.ceph.com/issues/20059

### CODE REVIEW

**Comment by dzafman** [comment]
Replacing pull request from ceph/ceph#19327

**Comment by dzafman** [comment]
@liewegas @jdurgin Need to figure out the rados suite failures.  Also, there are intermittent (timing?) test failures in the new qa/standalone/osd/osd-*-stats.sh tests.

**Comment by liewegas** [comment]
@dzafman I just noticed the error injection is broken on bluestore in master.  See https://github.com/ceph/ceph/pull/19866

**Comment by dzafman** [comment]
Test results

dzafman-2018-01-11_21:21:49-rados-wip-calc-stats-distro-basic-smithi (—filter standalone -N 10)
2063205 qa/standalone/mon/misc.sh TEST_mon_features failed to get quorum

dzafman-2018-01-11_21:37:33-rados:thrash-wip-calc-stats-distro-basic-smithi
2063344 Bug #22656 scrub mismatch on bytes
2063430 ceph_test_rados core dump (need to get stack trace from core dump)
2063422 Clock sync
2063432 Clock sync
2063457 Clock sync

**Comment by dzafman** [comment]
Tests passed 38 runs of each of osd-backfill-stats.sh and osd-recovery-stats.sh using run-standalone.sh

**Comment by dzafman** [comment]
@liewegas You approved the previous version but there have been slight changes including
d09bcfd, 
d44f30b

Merge comment should include:

Fixes: http://tracker.ceph.com/issues/20059

**Comment by dzafman** [comment]
dzafman-2018-01-15_15:34:02-rados-wip-zafman-testing-distro-basic-smithi
2076708	Error ETIMEDOUT: crush test failed with -110: timed out during smoke test (5 seconds) doing ceph osd pool create fast_eviction 1 1
2076717	rbd failures
2076765	clocks not sync'ed
2076870 test.sh cal_raw_used_size != raw_used_size
2076953 test.sh cal_raw_used_size != raw_used_size
2076985 Need test case adjustment 1 osd out marked misplaced

Job 2076985 fixed by 9f103f0

**Comment by dzafman** [comment]
PASSED with correction 9f103f0
dzafman-2018-01-16_10:53:54-rados-wip-zafman-testing-distro-basic-smithi/2079354

**Pull request merged**
