### PR TITLE
crimson/seastore: enforce per-collection transaction ordering

### PR DESCRIPTION
**Pull request by athanatos**
Adds a mutex to SeastoreCollection to enforce transaction ordering per collection.  Note that no ordering is enforced between transactions on different collections (different pgs), so conflicts aren't really less likely.

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by athanatos** [comment]
Should address https://tracker.ceph.com/issues/51358 @xuxuehan

**Review by liu-chunmei — APPROVED** [review]
verified, osdmap.#  issue not be reproduced.

**Comment by xxhdx1985126** [comment]
@athanatos IIUC, this pr ensures the per-collection transaction ordering by restricting the number of each collection's concurrent transactions to be one. And in the future, we can optimize this by making the procedure from transaction creation to transaction wait_throttle pipelined. Is this right?

**Comment by athanatos** [comment]
The restriction only lasts until submission to the device -- a pg can still have multiple pipelined IOs submitted to the journal.  If this proves to be a problem, we can add pipe lining provided that we correctly deal with retries, but I don't really anticipate this being necessary.

**Review by cyx1231st — APPROVED** [review]
LGTM.

A question not relate to this PR @athanatos : Why is `retired_extent_gate_t` still needed after implementing interruptive-future-based transaction invalidation?

**Review by xxhdx1985126 — APPROVED** [review]

**Comment by athanatos** [comment]
@cyx1231st Yeah, that may no longer be necessary since reads will now also reliably be invalidated.

**Pull request merged**
