### PR TITLE
erasure code: shec performance optimization by decoding cache

### PR DESCRIPTION
**Pull request by t-miyamae**
added shec's performance optimization
- decoding cache

### CODE REVIEW

**Comment by dachary** [comment]
@t-miyamae could you please rebase so it uses the SIMD code and validates with it ?

**Comment by t-miyamae** [comment]
@dachary we have completed the rebase. Could you check it again?

**Comment by t-miyamae** [comment]
@dachary A week has passed since the last rebase. Could you tell us if you have any ideas we should handle right now?

**Comment by dachary** [comment]
Now in ceph.com/gitbuilder.cgi under the branch t-miyamae-wip-mshec-fixlogic4. After that I'll run a test suite. Please ping me again if I do not act within a day or two.

**Comment by dachary** [comment]
@t-miyamae I need to run a test suite on monday. Please ping me on wednesday if I did not.

**Comment by t-miyamae** [comment]
@dachary I must ping you. Has the test suite on last monday already finished?

**Comment by dachary** [comment]
@t-miyamae it failed for unrelated reasons (environmental noise). I scheduled it again at http://pulpito.ceph.com/loic-2015-08-17_18:18:30-upgrade:hammer-x:stress-split-erasure-code-wip-10887-shec---basic-multi/

**Comment by t-miyamae** [comment]
@dachary Could you let us share the status of this pull request? Has the re-scheduled test already finished?

**Comment by tchaikov** [comment]
@t-miyamae you can find the the test results at the link posted by @dachary : http://pulpito.ceph.com/loic-2015-08-17_18:18:30-upgrade:hammer-x:stress-split-erasure-code-wip-10887-shec---basic-multi/ .

i took a look at them. seems all of them were waiting for more test machines in despair, and gave up at the end. the ansible-playbook returned because it failed to parse the failure log, and the failure was due to not enough nodes for the test.

because of the nature of these tests, they need 5+3 nodes to perform the test, but the most close try was 7 nodes, see http://qa-proxy.ceph.com/teuthology/loic-2015-08-17_18:18:30-upgrade:hammer-x:stress-split-erasure-code-wip-10887-shec---basic-multi/1018760/teuthology.log.

**Comment by markhpc** [comment]
Yes, one of the things we noticed when we looked at teuthology stats was that jobs that request many nodes get starved by jobs that request only a few nodes and time out after 48 hours.  See:

http://nhm.ceph.com/community/Ceph_Community_Lab_Performance_Investigation.pdf

**Comment by t-miyamae** [comment]
@dachary Do we have to test on such a large numbers of nodes this time?

**Comment by dachary** [comment]
<pre>
teuthology-suite --priority 101 --machine-type vps --suite rados/thrash-erasure-code-shec --suite-branch master --ceph t-miyamae-wip-mshec-fixlogic4 --email loic@dachary.org
</pre>

running at http://pulpito.ceph.com/loic-2015-09-03_15:07:07-rados:thrash-erasure-code-shec-t-miyamae-wip-mshec-fixlogic4---basic-vps/

**Comment by dachary** [comment]
@t-miyamae if you feel there does not need to be as many OSDs to run the suite, feel free to send a pull request for ceph-qa-suite reducing them. Are you able to run the rados/thrash-erasure-code-shec suite on your cluster ?

**Comment by t-miyamae** [comment]
@dachary Your latest test seemed to fail because of experimental feature flag. We will rebase soon.

**Comment by dachary** [comment]
@t-miyamae thanks ! It would be nice if you could then run the same test on your teuthology cluster to confirm.

**Comment by dachary** [comment]
Now in ceph.com/gitbuilder.cgi under the branch t-miyamae-wip-mshec-fixlogic4. After that I'll run a test suite.

**Comment by dachary** [comment]
<pre>
teuthology-suite --priority 101 --machine-type vps --suite rados/thrash-erasure-code-shec --suite-branch master --ceph t-miyamae-wip-mshec-fixlogic4 --email loic@dachary.org
</pre>

running at http://pulpito.ceph.com/loic-2015-09-08_12:34:28-rados:thrash-erasure-code-shec-t-miyamae-wip-mshec-fixlogic4---basic-vps/

**Comment by dachary** [comment]
@t-miyamae thanks for your (almost) infinite patience ;-)

**Comment by t-miyamae** [comment]
@dachary we were preparing teuthology on our cluster, but have not made it yet because of problems during Ceph's build process in our environment. I appreciate your double check which boosted our pull request as a result!

**Comment by dachary** [comment]
@t-miyamae you're welcome. It would be great if you could run a few extra teuthology jobs when your cluster is ready and let us know how it goes.

**Pull request merged**
