### PR TITLE
mon: drop multifs as experimental

### PR DESCRIPTION
**Pull request by joscollin**
Dropped the warning and updated the error messages that shows multi fs as an experimental feature.

Issue for discussion: http://tracker.ceph.com/issues/22477

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by joscollin** [comment]
@ukernel I did one more update. Please revisit. Thanks.

**Comment by batrick** [comment]
Issue for discussion: http://tracker.ceph.com/issues/22477

**Comment by joscollin** [comment]
Pushed `experimental-features.rst` changes too.

**Comment by joscollin** [comment]
@gregsfortytwo Yes, we've decided to keep this `Pending Discussion` with [tracker](http://tracker.ceph.com/issues/22477)

**Comment by batrick** [comment]
I'm going to close this since the PR is trivial and we're a ways off from being able to declare multifs stable.

**Comment by joscollin** [comment]
@batrick ok no problem. I don't want to keep it opened for a long time too.

**Pull request closed without merging**
