### PR TITLE
doc/releases: Update releases to August '18

### PR DESCRIPTION
**Pull request by badone**
Mimic    13.2.1
Luminous 12.2.5, 12.2.6, 12.2.7
Jewel    10.2.11

Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

### CODE REVIEW

**Comment by badone** [comment]
Jenkins render docs

**Comment by gregsfortytwo** [comment]
Hmm is this automatically generated? Those line diffs are kinda large ;)

**Comment by theanalyst** [comment]
@gregsfortytwo I believe rst tables  are the reason for the large diff

**Comment by badone** [comment]
@gregsfortytwo I had to modify the width of complete columns which changes every line in the table.

**Pull request merged**
