### PR TITLE
rgw: crash on multipart upload to bucket with policy

### PR DESCRIPTION
**Pull request by ofriedma**
crash on multipart upload to bucket with policy
Fixes: https://tracker.ceph.com/issues/50556

Signed-off-by: Or Friedmann <ofriedma@redhat.com>
s3-tests: https://github.com/ceph/s3-tests/pull/393

### CODE REVIEW

**Review by dang — COMMENTED** [review]
Hmm... I'm not sure I like the shotgun solution to this.  Maybe we should set this in rgw_build_bucket_policies(), when s->bucket is created?

**Comment by mattbenjamin** [comment]
> 
> 
> Hmm... I'm not sure I like the shotgun solution to this. Maybe we should set this in rgw_build_bucket_policies(), when s->bucket is created?

that sounds nicer

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
thanks @ofriedma! in the bug scrub, an s3test case was requested

**Comment by tahajahangir** [comment]
This is a very annoying bug, makes RGW totally unusable for public buckets. We are waiting for commit of this patch in `pacific` branch.

**Comment by tahajahangir** [comment]
In the meanwhile, I suggest committing the patch in a `wip-*` branch, so others can use a built / docker-image version.

**Comment by wtayyeb** [comment]
we have same problem. we try to build this PR but its too complicated to build it for pacific.

**Comment by ofriedma** [comment]
https://pulpito.ceph.com/ofriedma-2021-05-19_08:41:16-rgw-wip-ofriedma-segfault-bucket-policy-distro-basic-smithi/

**Pull request merged**
