### PR TITLE
mgr/DaemonServer.cc: add 'is_valid=false' when decode caps error

### PR DESCRIPTION
**Pull request by gmayyyha**
Signed-off-by: Yanhu Cao <gmayyyha@gmail.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Since this is a bug fix we'd want to backport, could you please create a ticket on tracker.ceph.com, and update the commit message here to have a "Fixes: " line referring to it?

**Comment by joscollin** [comment]
@jcsp @gmayyyha 

You can create one tracker for all the related PRs: https://github.com/ceph/ceph/pull/16978, https://github.com/ceph/ceph/pull/16891. I think there is one more ?

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-08-11_16:55:13-rados-wip-yuri-testing3_2017_8_12-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-08-11_22:48:56-rados-wip-yuri-testing3_2017_8_12-distro-basic-smithi/

**Comment by yuriw** [comment]
@liewegas pls comment

**Pull request merged**
