### PR TITLE
luminous: backoff causes out of order op

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21794

### CODE REVIEW

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-11-07_15:13:35-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2017-11-06_02:23:20-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-11-08_06:05:18-rados-wip-kefu-testing-2017-11-06-0102-distro-basic-mira/

the failed tests are addressed by #18675

**Comment by yuriw** [comment]
test this pleadr

**Comment by tchaikov** [comment]
@yuriw i think i've tested this PR, and the tests passed. the only blocker was the blessing from the PTO. since we have it now, i guess we can just merge this PR.

**Comment by yuriw** [comment]
@tchaikov Yes I retested it too, but need more rights to overwrite `make check` status.

**Pull request merged**
