### PR TITLE
rgw: bucket index not syncing when rados cluster abnormally

### PR DESCRIPTION
**Pull request by fangyuxiangGL**
Fixes: http://tracker.ceph.com/issues/20211

Signed-off-by: fang yuxiang fang.yuxiang@eisoo.com

### CODE REVIEW

**Comment by fangyuxiangGL** [comment]
@cbodley 

Hi casey

I reopen this pr after long time thinking. 
Could you have a look and ping more people for RFC? 
Since bucket index logic and multisite syncing are a bit complicated.
Thanks!

**Comment by cbodley** [comment]
hi @fangyuxiangGL, it's not clear to me exactly what this is trying to fix. and in the general case, it adds an extra rados request that will slow down sync

**Comment by fangyuxiangGL** [comment]
@cbodley 
1. rados cluster abnormally lead bucket index add op failed in fetch remote object, but the object's data was put successfully
2. because step 1, that object can be download but will not be in s3 ListBucket results
3. That object will never be in s3 ListBucket results if it is not modified later, even we triger a new full sync
4. Surely, that object will be in s3 ListBucket if it is modified later.

I consider that rados cluster abnormal is very usual.  Losts of objects will be "half syncing" state(they have whole data but don't have index), and they will stay same if not be modified in source site even we triger a new full sync using radosgw-admin, why? let's have a look at the code:

  if (copy_if_newer) { /* always 'True' in syncing object */
    /* need to get mtime for destination */
    ret = get_obj_state(&obj_ctx, dest_obj, &dest_state, false); /* will success for object data is whole */
    if (ret < 0)
      goto set_err_state;

    if (!real_clock::is_zero(dest_state->mtime)) {
      dest_mtime_weight.init(dest_state);
      pmod = &dest_mtime_weight.mtime;
    }
  }

 
  ret = conn->get_obj(user_id, info, src_obj, pmod, unmod_ptr,
                      dest_mtime_weight.zone_short_id, dest_mtime_weight.pg_ver,
                      true /* prepend_meta */, true /* GET */, false /* rgwx-stat */,
                      &cb, &in_stream_req);
  if (ret < 0) { /* will fail for object is not modified in source site and we just copy if newer, will get ERR_NOT_MODIFIED */
    goto set_err_state;
}

**Comment by fangyuxiangGL** [comment]
@cbodley 

i think it will not slow down new object syncing, and it really bring one more rados op that will slow down a bit. 

But I also think the one more rados op is a local op and has latency less than 10ms? 
Consider the network latency between two sites, is it so insignificant?
but, it is just my personal opinion and may be ill-considered.  ^_^

**Comment by zhangsw** [comment]
I've also encountered this problem when testing the data sync. 
http://tracker.ceph.com/issues/18260
And If we have only one rgw each zone and set rgw_num_rados_handles=1, it seems that this won't happen.

**Comment by fangyuxiangGL** [comment]
> Seems that we have totally different goal

**Pull request closed without merging**
