### PR TITLE
tools: improved bash completion for ceph CLI

### PR DESCRIPTION
**Pull request by aclamk**
Improved bash completion. 
New: ceph --help is source of tips for autocomplete.
New: options "--" can be tipped anywhere in command.

### CODE REVIEW

**Comment by liewegas** [comment]
@dmick mind looking at this?  I'm guessing that we might be better off making a ceph -h output mode that has more structured output and avoids some of the hackery here?

**Comment by dmick** [comment]
I'm so sorry, I completely missed this request to have a look at this.  I've wished to finish the work on ceph --completion forever, but that's what that was intended for.  @aclamk, did you see that at all?

**Comment by aclamk** [comment]
Hi Mick,

If you have any bash-completion in progress, please share with me.

Best regards,
Adam Kupczyk

**Comment by dmick** [comment]
Well, as I mentioned, there's --completion partially implemented in the ceph command itself, designed to be called from the bash completion code...but it hasn't been changed in years.  See https://github.com/ceph/ceph/blob/master/src/ceph.in#L459 et. seq.

-- Dan

**Comment by liewegas** [comment]
@aclamk can you update this to use the --completion function?

**Comment by dmick** [comment]
(the --completion function will need some love, but I think it's the righter direction)

**Comment by tchaikov** [comment]
superseded by #7693

**Pull request closed without merging**
