### PR TITLE
nautilus: tools: ceph-objectstore-tool can't remove head with bad snapset

### PR DESCRIPTION
**Pull request by pdvian**
https://tracker.ceph.com/issues/41596

### CODE REVIEW

**Comment by dzafman** [comment]
@pdvian Please run ../qa/run-standalone.sh ceph_objectstore_tool.py to make sure the test passes.

**Comment by pdvian** [comment]
@dzafman all ceph_objectstore_tool.py test passed and no failure for removeall test.

**Comment by dzafman** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri5-testing-2019-10-28-2037-nautilus](https://trello.com/c/X9giKuk1/733-wip-yuri5-testing-2019-10-28-2037-nautilus)

**Pull request merged**
