### PR TITLE
qa/rgw: add librgw_file unit tests to rgw/verify task

### PR DESCRIPTION
**Pull request by cbodley**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@cbodley should have done this a long time ago!  I don't promise these will work w/o some setup stuff, but let's see

**Review by dang — APPROVED** [review]

**Comment by cbodley** [comment]
> /home/ubuntu/cephtest/clone.client.0/qa/workunits/rgw/test_librgw_file.sh: line 3: ceph_test_librgw_file: command not found

these tests weren't being packaged. i added a cmake commit that adds install() directives

**Comment by cbodley** [comment]
> ceph_test_librgw_file no AWS credentials, exiting

it looks like the tests need some configuration?

**Comment by dang** [comment]
Looks like the test takes --access --secret and (optionally?) --uid.  test_rgw_orphan_list.sh creates user with a known access/secret key, and uses that for the test.  Probably this test needs to do that too.

**Comment by cbodley** [comment]
@mattbenjamin creating the user helps and gets through most of the first test, but it hangs on shutdown:

> [ RUN      ] LibRGW.SHUTDOWN                                                   
2020-09-22T10:37:13.537-0400 7f3cdf1569c0 -1 shutting down                     
2020-09-22T10:37:13.537-0400 7f3c3cff1700 -1 received  signal: User defined signal 1, si_code : -6, si_value (int): 0, si_value (ptr): 0, si_errno: 0, si_pid : 3453602, si_uid : 1000, si_addr0x3e80034b2a2, si_status0

**Comment by mattbenjamin** [comment]
> @mattbenjamin creating the user helps and gets through most of the first test, but it hangs on shutdown:

I assume this hang is resolved by the framework?  If so, we can just create an issue.

**Comment by mattbenjamin** [comment]
@dang see update

**Comment by mattbenjamin** [comment]
@dang I've added a commit that fixes rgw_rename(), added a comment in one location and to the commit msg;  I'll clean those up, but would like to discuss in more detail first

**Review by dang — APPROVED** [review]

**Comment by dang** [comment]
jenkins test make check

**Comment by mattbenjamin** [comment]
@dang could you take another look?  I've added a commit that fixes file paths in RGWWriteRequest, and so fixes various
enumeration tests in librgw_file_nfsns and librgw_file_marker.

**Review by dang — APPROVED** [review]

**Comment by mattbenjamin** [comment]
@dang can you review...again? :)
I added another commit that addresses a couple of issues in librgw_file_gp.cc.
That said, while I can run the entire test driver to completion from the command line without failures -most- of the time, there are intermittent failures affecting multiple tests.  I linked you to one.  Another reproduces as (a random test fails with):
unknown file: Failure
C++ exception with description "End of buffer" thrown in the test body.
[  FAILED  ] LibRGW.BAD_DELETES_DIRS1 (11 ms)
Matt

**Comment by dang** [comment]
I believe I've reviewed the most recent code.

**Comment by mattbenjamin** [comment]
thanks, @dang

**Comment by mattbenjamin** [comment]
will update with the qa unit changes only

**Comment by mattbenjamin** [comment]
@dang can you take a look at the perm_state_base change?
@cbodley this now runs reliably with arbitrary re-runs, from the cmdline, should pass in suite as well

**Comment by mattbenjamin** [comment]
https://pulpito.ceph.com/mbenjamin-2021-01-13_16:21:47-rgw-wip-qa-librgw-distro-basic-smithi/

**Review by dang — APPROVED** [review]

**Comment by mattbenjamin** [comment]
https://pulpito.ceph.com/mbenjamin-2021-01-18_07:13:16-rgw:verify-wip-qa-librgw7-distro-basic-gibba/
still failing, but now key should be correct:
radosgw-admin user creation has succeeded, then:
'''
2021-01-18T12:34:06.858 INFO:tasks.workunit.client.0.gibba029.stdout:phase 1.1
2021-01-18T12:34:06.858 INFO:tasks.workunit.client.0.gibba029.stdout:ceph_test_librgw_file_nfsns -k /etc/ceph/ceph.client.0.keyring --hier1 --dirs1 --create --rename --verbose
2021-01-18T12:34:06.858 INFO:tasks.workunit.client.0.gibba029.stdout:cat /etc/ceph/ceph.client.0.keyring
2021-01-18T12:34:06.859 INFO:tasks.workunit.client.0.gibba029.stdout:[client.0]
2021-01-18T12:34:06.859 INFO:tasks.workunit.client.0.gibba029.stdout:	key = AQDgfgVgGOVfGxAAEPqE8wNa5kyGmF4ktAFEFA==
2021-01-18T12:34:06.870 INFO:tasks.workunit.client.0.gibba029.stdout:[==========] Running 24 tests from 1 test suite.
2021-01-18T12:34:06.871 INFO:tasks.workunit.client.0.gibba029.stdout:[----------] Global test environment set-up.
2021-01-18T12:34:06.871 INFO:tasks.workunit.client.0.gibba029.stdout:[----------] 24 tests from LibRGW
2021-01-18T12:34:06.871 INFO:tasks.workunit.client.0.gibba029.stdout:[ RUN      ] LibRGW.INIT
2021-01-18T12:34:06.878 INFO:tasks.workunit.client.0.gibba029.stderr:ignoring --setuser ceph since I am not root
2021-01-18T12:34:06.878 INFO:tasks.workunit.client.0.gibba029.stderr:ignoring --setgroup ceph since I am not root
2021-01-18T12:34:06.879 INFO:tasks.workunit.client.0.gibba029.stderr:2021-01-18T12:34:06.878+0000 7fadb092d700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2021-01-18T12:34:06.880 INFO:tasks.workunit.client.0.gibba029.stderr:failed to fetch mon config (--no-mon-config to skip)
2021-01-18T12:34:06.881 DEBUG:teuthology.orchestra.run:got remote process result: 1
2021-01-18T12:34:06.881 INFO:tasks.workunit:Stopping ['cls/test_cls_lock.sh', 'cls/test_cls_log.sh', 'cls/test_cls_refcount.sh', 'cls/test_cls_rgw.sh', 'cls/test_cls_cmpomap.sh', 'cls/test_cls_2pc_queue.sh', 'rgw/test_rgw_gc_log.sh', 'rgw/test_rgw_obj.sh', 'rgw/test_rgw_throttle.sh', 'rgw/test_librgw_file.sh'] on client.0...
2021-01-18T12:34:06.882 DEBUG:teuthology.orchestra.run.gibba029:> sudo rm -rf -- /home/ubuntu/cephtest/workunits.list.client.0 /home/ubuntu/cephtest/clone.client.0
2021-01-18T12:34:07.061 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
'''

**Comment by dang** [comment]
Failure to fetch mon config is definitely fatal (it immediately calls _exit(1)), unless you pass --no-mon-config.

**Comment by mattbenjamin** [comment]
Now this is looking like the rgw cluster maybe isn't fully initialized?
'''
2021-01-18T16:49:59.965 INFO:tasks.workunit.client.0.gibba023.stdout:phase 1.1
2021-01-18T16:49:59.977 INFO:tasks.workunit.client.0.gibba023.stdout:[==========] Running 24 tests from 1 test suite.
2021-01-18T16:49:59.977 INFO:tasks.workunit.client.0.gibba023.stdout:[----------] Global test environment set-up.
2021-01-18T16:49:59.978 INFO:tasks.workunit.client.0.gibba023.stdout:[----------] 24 tests from LibRGW
2021-01-18T16:49:59.978 INFO:tasks.workunit.client.0.gibba023.stdout:[ RUN      ] LibRGW.INIT
2021-01-18T16:49:59.985 INFO:tasks.workunit.client.0.gibba023.stderr:ignoring --setuser ceph since I am not root
2021-01-18T16:49:59.985 INFO:tasks.workunit.client.0.gibba023.stderr:ignoring --setgroup ceph since I am not root
2021-01-18T16:49:59.987 INFO:tasks.workunit.client.0.gibba023.stderr:2021-01-18T16:49:59.987+0000 7f7d7b7fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2021-01-18T16:49:59.988 INFO:tasks.workunit.client.0.gibba023.stdout:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/16.0.0-8704-g204669cc/rpm/el8/BUILD/ceph-16.0.0-8704-g204669cc/src/test/librgw_file_nfsns.cc:186: Failure
2021-01-18T16:49:59.988 INFO:tasks.workunit.client.0.gibba023.stdout:Expected equality of these values:
2021-01-18T16:49:59.988 INFO:tasks.workunit.client.0.gibba023.stdout:  ret
2021-01-18T16:49:59.989 INFO:tasks.workunit.client.0.gibba023.stdout:    Which is: -5
2021-01-18T16:49:59.989 INFO:tasks.workunit.client.0.gibba023.stdout:  0
2021-01-18T16:49:59.989 INFO:tasks.workunit.client.0.gibba023.stdout:[  FAILED  ] LibRGW.INIT (10 ms)
2021-01-18T16:49:59.989 INFO:tasks.workunit.client.0.gibba023.stdout:[ RUN      ] LibRGW.MOUNT
2021-01-18T16:49:59.990 INFO:tasks.workunit.client.0.gibba023.stderr:2021-01-18T16:49:59.988+0000 7f7d9e75f200 -1 Couldn't init storage provider (RADOS)
2021-01-18T16:49:59.990 INFO:tasks.workunit.client.0.gibba023.stderr:*** Caught signal (Segmentation fault) **
2021-01-18T16:49:59.990 INFO:tasks.workunit.client.0.gibba023.stderr: in thread 7f7d9e75f200 thread_name:ceph_test_librg
2021-01-18T16:49:59.991 INFO:tasks.workunit.client.0.gibba023.stderr: ceph version 16.0.0-8704-g204669cc (204669cc8eb19c91e16ac1f4922aa6b2865ae814) pacific (dev)
2021-01-18T16:49:59.991 INFO:tasks.workunit.client.0.gibba023.stderr: 1: /lib64/libpthread.so.0(+0x12dc0) [0x7f7d94298dc0]
2021-01-18T16:49:59.991 INFO:tasks.workunit.client.0.gibba023.stderr: 2: (rgw::RGWLibFS::authorize(rgw::sal::RGWRadosStore*)+0x44) [0x7f7d9daa2a44]
2021-01-18T16:49:59.992 INFO:tasks.workunit.client.0.gibba023.stderr: 3: rgw_mount2()
2021-01-18T16:49:59.992 INFO:tasks.workunit.client.0.gibba023.stderr: 4: (LibRGW_MOUNT_Test::TestBody()+0x4b) [0x55959e1e179b]
2021-01-18T16:49:59.992 INFO:tasks.workunit.client.0.gibba023.stderr: 5: (void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x4e) [0x55959e225cbe]
2021-01-18T16:49:59.992 INFO:tasks.workunit.client.0.gibba023.stderr: 6: (testing::Test::Run()+0xcb) [0x55959e21a8eb]
2021-01-18T16:49:59.993 INFO:tasks.workunit.client.0.gibba023.stderr: 7: (testing::TestInfo::Run()+0x135) [0x55959e21aa55]
2021-01-18T16:49:59.993 INFO:tasks.workunit.client.0.gibba023.stderr: 8: (testing::TestSuite::Run()+0xb5) [0x55959e21ab35]
2021-01-18T16:49:59.993 INFO:tasks.workunit.client.0.gibba023.stderr: 9: (testing::internal::UnitTestImpl::RunAllTests()+0x425) [0x55959e21aff5]
2021-01-18T16:49:59.993 INFO:tasks.workunit.client.0.gibba023.stderr: 10: (bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x4e) [0x55959e22622e]
2021-01-18T16:49:59.993 INFO:tasks.workunit.client.0.gibba023.stderr: 11: (testing::UnitTest::Run()+0xa0) [0x55959e21b2a0]
2021-01-18T16:49:59.994 INFO:tasks.workunit.client.0.gibba023.stderr: 12: main()
2021-01-18T16:49:59.994 INFO:tasks.workunit.client.0.gibba023.stderr: 13: __libc_start_main()
2021-01-18T16:49:59.994 INFO:tasks.workunit.client.0.gibba023.stderr: 14: _start()
2021-01-18T16:49:59.994 INFO:tasks.workunit.client.0.gibba023.stderr:2021-01-18T16:49:59.989+0000 7f7d9e75f200 -1 *** Caught signal (Segmentation fault) **
2021-01-18T16:49:59.994 INFO:tasks.workunit.client.0.gibba023.stderr: in thread 7f7d9e75f200 thread_name:ceph_test_librg
2021-01-18T16:49:59.995 INFO:tasks.workunit.client.0.gibba023.stderr:
2021-01-18T16:49:59.995 INFO:tasks.workunit.client.0.gibba023.stderr: ceph version 16.0.0-8704-g204669cc (204669cc8eb19c91e16ac1f4922aa6b2865ae814) pacific (dev)
2021-01-18T16:49:59.995 INFO:tasks.workunit.client.0.gibba023.stderr: 1: /lib64/libpthread.so.0(+0x12dc0) [0x7f7d94298dc0]
2021-01-18T16:49:59.995 INFO:tasks.workunit.client.0.gibba023.stderr: 2: (rgw::RGWLibFS::authorize(rgw::sal::RGWRadosStore*)+0x44) [0x7f7d9daa2a44]
2021-01-18T16:49:59.995 INFO:tasks.workunit.client.0.gibba023.stderr: 3: rgw_mount2()
2021-01-18T16:49:59.996 INFO:tasks.workunit.client.0.gibba023.stderr: 4: (LibRGW_MOUNT_Test::TestBody()+0x4b) [0x55959e1e179b]
2021-01-18T16:49:59.996 INFO:tasks.workunit.client.0.gibba023.stderr: 5: (void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x4e) [0x55959e225cbe]
2021-01-18T16:49:59.996 INFO:tasks.workunit.client.0.gibba023.stderr: 6: (testing::Test::Run()+0xcb) [0x55959e21a8eb]
2021-01-18T16:49:59.996 INFO:tasks.workunit.client.0.gibba023.stderr: 7: (testing::TestInfo::Run()+0x135) [0x55959e21aa55]
2021-01-18T16:49:59.996 INFO:tasks.workunit.client.0.gibba023.stderr: 8: (testing::TestSuite::Run()+0xb5) [0x55959e21ab35]
2021-01-18T16:49:59.997 INFO:tasks.workunit.client.0.gibba023.stderr: 9: (testing::internal::UnitTestImpl::RunAllTests()+0x425) [0x55959e21aff5]
2021-01-18T16:49:59.997 INFO:tasks.workunit.client.0.gibba023.stderr: 10: (bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x4e) [0x55959e22622e]
2021-01-18T16:49:59.997 INFO:tasks.workunit.client.0.gibba023.stderr: 11: (testing::UnitTest::Run()+0xa0) [0x55959e21b2a0]
2021-01-18T16:49:59.997 INFO:tasks.workunit.client.0.gibba023.stderr: 12: main()
2021-01-18T16:49:59.998 INFO:tasks.workunit.client.0.gibba023.stderr: 13: __libc_start_main()
2021-01-18T16:49:59.998 INFO:tasks.workunit.client.0.gibba023.stderr: 14: _start()
2021-01-18T16:49:59.998 INFO:tasks.workunit.client.0.gibba023.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2021-01-18T16:49:59.998 INFO:tasks.workunit.client.0.gibba023.stderr:
2021-01-18T16:49:59.998 INFO:tasks.workunit.client.0.gibba023.stderr:   -14> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2021-01-18T16:49:59.999 INFO:tasks.workunit.client.0.gibba023.stderr:    -1> 2021-01-18T16:49:59.988+0000 7f7d9e75f200 -1 Couldn't init storage provider (RADOS)
2021-01-18T16:49:59.999 INFO:tasks.workunit.client.0.gibba023.stderr:     0> 2021-01-18T16:49:59.989+0000 7f7d9e75f200 -1 *** Caught signal (Segmentation fault) **
2021-01-18T16:49:59.999 INFO:tasks.workunit.client.0.gibba023.stderr: in thread 7f7d9e75f200 thread_name:ceph_test_librg
2021-01-18T16:49:59.999 INFO:tasks.workunit.client.0.gibba023.stderr:
2021-01-18T16:49:59.999 INFO:tasks.workunit.client.0.gibba023.stderr: ceph version 16.0.0-8704-g204669cc (204669cc8eb19c91e16ac1f4922aa6b2865ae814) pacific (dev)
2021-01-18T16:50:00.000 INFO:tasks.workunit.client.0.gibba023.stderr: 1: /lib64/libpthread.so.0(+0x12dc0) [0x7f7d94298dc0]
2021-01-18T16:50:00.000 INFO:tasks.workunit.client.0.gibba023.stderr: 2: (rgw::RGWLibFS::authorize(rgw::sal::RGWRadosStore*)+0x44) [0x7f7d9daa2a44]
2021-01-18T16:50:00.000 INFO:tasks.workunit.client.0.gibba023.stderr: 3: rgw_mount2()
2021-01-18T16:50:00.000 INFO:tasks.workunit.client.0.gibba023.stderr: 4: (LibRGW_MOUNT_Test::TestBody()+0x4b) [0x55959e1e179b]
2021-01-18T16:50:00.000 INFO:tasks.workunit.client.0.gibba023.stderr: 5: (void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x4e) [0x55959e225cbe]
2021-01-18T16:50:00.001 INFO:tasks.workunit.client.0.gibba023.stderr: 6: (testing::Test::Run()+0xcb) [0x55959e21a8eb]
2021-01-18T16:50:00.001 INFO:tasks.workunit.client.0.gibba023.stderr: 7: (testing::TestInfo::Run()+0x135) [0x55959e21aa55]
2021-01-18T16:50:00.001 INFO:tasks.workunit.client.0.gibba023.stderr: 8: (testing::TestSuite::Run()+0xb5) [0x55959e21ab35]
2021-01-18T16:50:00.001 INFO:tasks.workunit.client.0.gibba023.stderr: 9: (testing::internal::UnitTestImpl::RunAllTests()+0x425) [0x55959e21aff5]
2021-01-18T16:50:00.001 INFO:tasks.workunit.client.0.gibba023.stderr: 10: (bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x4e) [0x55959e22622e]
2021-01-18T16:50:00.002 INFO:tasks.workunit.client.0.gibba023.stderr: 11: (testing::UnitTest::Run()+0xa0) [0x55959e21b2a0]
2021-01-18T16:50:00.002 INFO:tasks.workunit.client.0.gibba023.stderr: 12: main()
2021-01-18T16:50:00.002 INFO:tasks.workunit.client.0.gibba023.stderr: 13: __libc_start_main()
2021-01-18T16:50:00.002 INFO:tasks.workunit.client.0.gibba023.stderr: 14: _start()
2021-01-18T16:50:00.003 INFO:tasks.workunit.client.0.gibba023.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2021-01-18T16:50:00.003 INFO:tasks.workunit.client.0.gibba023.stderr:
2021-01-18T16:50:00.003 INFO:tasks.workunit.client.0.gibba023.stderr:  -100> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
2021-01-18T16:50:00.003 INFO:tasks.workunit.client.0.gibba023.stderr:   -99> 2021-01-18T16:49:59.988+0000 7f7d9e75f200 -1 Couldn't init storage provider (RADOS)
2021-01-18T16:50:00.003 INFO:tasks.workunit.client.0.gibba023.stderr:   -98> 2021-01-18T16:49:59.989+0000 7f7d9e75f200 -1 *** Caught signal (Segmentation fault) **
2021-01-18T16:50:00.004 INFO:tasks.workunit.client.0.gibba023.stderr: in thread 7f7d9e75f200 thread_name:ceph_test_librg
2021-01-18T16:50:00.004 INFO:tasks.workunit.client.0.gibba023.stderr:
2021-01-18T16:50:00.004 INFO:tasks.workunit.client.0.gibba023.stderr: ceph version 16.0.0-8704-g204669cc (204669cc8eb19c91e16ac1f4922aa6b2865ae814) pacific (dev)
2021-01-18T16:50:00.004 INFO:tasks.workunit.client.0.gibba023.stderr: 1: /lib64/libpthread.so.0(+0x12dc0) [0x7f7d94298dc0]
2021-01-18T16:50:00.005 INFO:tasks.workunit.client.0.gibba023.stderr: 2: (rgw::RGWLibFS::authorize(rgw::sal::RGWRadosStore*)+0x44) [0x7f7d9daa2a44]
2021-01-18T16:50:00.005 INFO:tasks.workunit.client.0.gibba023.stderr: 3: rgw_mount2()
2021-01-18T16:50:00.005 INFO:tasks.workunit.client.0.gibba023.stderr: 4: (LibRGW_MOUNT_Test::TestBody()+0x4b) [0x55959e1e179b]
2021-01-18T16:50:00.005 INFO:tasks.workunit.client.0.gibba023.stderr: 5: (void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x4e) [0x55959e225cbe]
2021-01-18T16:50:00.006 INFO:tasks.workunit.client.0.gibba023.stderr: 6: (testing::Test::Run()+0xcb) [0x55959e21a8eb]
2021-01-18T16:50:00.006 INFO:tasks.workunit.client.0.gibba023.stderr: 7: (testing::TestInfo::Run()+0x135) [0x55959e21aa55]
2021-01-18T16:50:00.006 INFO:tasks.workunit.client.0.gibba023.stderr: 8: (testing::TestSuite::Run()+0xb5) [0x55959e21ab35]
2021-01-18T16:50:00.006 INFO:tasks.workunit.client.0.gibba023.stderr: 9: (testing::internal::UnitTestImpl::RunAllTests()+0x425) [0x55959e21aff5]
2021-01-18T16:50:00.006 INFO:tasks.workunit.client.0.gibba023.stderr: 10: (bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*)+0x4e) [0x55959e22622e]
2021-01-18T16:50:00.007 INFO:tasks.workunit.client.0.gibba023.stderr: 11: (testing::UnitTest::Run()+0xa0) [0x55959e21b2a0]
2021-01-18T16:50:00.007 INFO:tasks.workunit.client.0.gibba023.stderr: 12: main()
2021-01-18T16:50:00.007 INFO:tasks.workunit.client.0.gibba023.stderr: 13: __libc_start_main()
2021-01-18T16:50:00.007 INFO:tasks.workunit.client.0.gibba023.stderr: 14: _start()
2021-01-18T16:50:00.008 INFO:tasks.workunit.client.0.gibba023.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2021-01-18T16:50:00.008 INFO:tasks.workunit.client.0.gibba023.stderr:
2021-01-18T16:50:00.013 INFO:tasks.workunit.client.0.gibba023.stderr:/home/ubuntu/cephtest/clone.client.0/qa/workunits/rgw/test_librgw_file.sh: line 24: 41966 Segmentation fault      (core dumped) ceph_test_librgw_file_nfsns ${K} --hier1 --dirs1 --create --rename --verbose
2021-01-18T16:50:00.013 DEBUG:teuthology.orchestra.run:got remote process result: 139
2021-01-18T16:50:00.014 INFO:tasks.workunit:Stopping ['cls/test_cls_lock.sh', 'cls/test_cls_log.sh', 'cls/test_cls_refcount.sh', 'cls/test_cls_rgw.sh', 'cls/test_cls_cmpomap.sh', 'cls/test_cls_2pc_queue.sh', 'rgw/test_rgw_gc_log.sh', 'rgw/test_rgw_obj.sh', 'rgw/test_rgw_throttle.sh', 'rgw/test_librgw_file.sh'] on client.0...
'''

**Comment by mattbenjamin** [comment]
@badone hey brad:  @cbodley mentioned that you might have some insight into scenarios where mon startup fails with "monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]";  We now have a consistent reproducer for this--albeit, I don't know what "this" really is.  Here, our teuthology task has set up an rgw cluster, and now we're trying to run a librgw (embedded rgw) unit test from the teuthology task--not something we've done before.  As above, it's not happy.

**Comment by mattbenjamin** [comment]
link to teuthology run: http://qa-proxy.ceph.com/teuthology/mbenjamin-2021-01-18_11:29:49-rgw:verify-wip-qa-librgw8-distro-basic-gibba/5799734/teuthology.log

**Comment by badone** [comment]
@mattbenjamin The message is bogus but the question I think is how did you end up in handle_auth_bad_method() in the first place? Maybe turn up ms and monc debugging and try again? At the moment this is what is in the log (./remote/gibba023/log/ceph-client.admin.41966.log.gz) which tells us you are getting 'Operation not permitted' but not why.

```
   -20> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 10 monclient(hunting): get_auth_request method 2 preferred_modes [2,1]
   -19> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 10 monclient(hunting): _init_auth method 2
   -18> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 10 monclient(hunting): handle_auth_reply_more payload 9
   -17> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 10 monclient(hunting): handle_auth_reply_more payload_len 9
   -16> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 10 monclient(hunting): handle_auth_reply_more responding with 2 bytes
   -15> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 10 monclient(hunting): handle_auth_bad_method old_auth_method 2 result (1) Operation not permitted allowed_methods [2]
   -14> 2021-01-18T16:49:59.987+0000 7f7d7b7fe700 -1 monclient(hunting): handle_auth_bad_method server allowed_methods [2] but i only support [2]
```

**Comment by badone** [comment]
Just looked at the monitor end. It's issuing "failed to decode CephXAuthenticate" which makes me wonder about the keyring you are using?

**Comment by mattbenjamin** [comment]
@badone hrm, ok!

**Comment by mattbenjamin** [comment]
http://qa-proxy.ceph.com/teuthology/mbenjamin-2021-01-22_17:58:01-rgw:verify-wip-qa-librgw10-distro-basic-gibba/5817595/teuthology.log

**Comment by mattbenjamin** [comment]
http://qa-proxy.ceph.com/teuthology/mbenjamin-2021-01-22_17:58:01-rgw:verify-wip-qa-librgw10-distro-basic-gibba/5817596/teuthology.log

**Comment by mattbenjamin** [comment]
@cbodley looks like it's passing now:
https://pulpito.ceph.com/mbenjamin-2021-01-25_20:37:27-rgw:verify-wip-qa-librgw11-distro-basic-gibba/

**Comment by mattbenjamin** [comment]
jenkins make check

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Comment by cbodley** [comment]
great! merge when ready

**Review by mattbenjamin — APPROVED** [review]
lgtm

**Comment by mattbenjamin** [comment]
jenkins retest this please

**Pull request merged**
