### PR TITLE
os/bluestore: simplify Onode pin/unpin logic.

### PR DESCRIPTION
**Pull request by ifed01**
This patch makes pin/unpin logic more straightforward and
hopefully safe in multi-threading.

Also it eliminates Onode's pin_list as one doesn't need it to track
pinned Onodes.

OnodeCacheShard reference has been removed from onode too.

cached/pinned flags have been introduced. They're accessed under cache lock
hence original race has been totally addressed.

Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
This looks great!  I think it's strictly better than the current master.

Reviewing this made me realize one thing though that I missed before: currently (and with this PR), if you have an onode somewhere in the middle of the LRU, and you take and release a reference, we forget its LRU position.  I'm not sure offhand if we have any really important callers that behave that way, but certainly things like scrub come to mind.

I think what we want is something a bit more targetted at trimming: if trim encounters a pinned inode, only then does it change it to the pinned state.  That way, when we put(), we can safely put it back at the tail of the LRU.  And/or, we could even make _touch set a flag so that the unpin step puts it at the LRU top instead.  What do you think?  (Perhaps for later?)

**Comment by markhpc** [comment]
@ifed01 I haven't looked closely at this yet, but after a quick skim, does this go back to scanning the entire onode list again?  That was exactly the problem the original PR was trying to address (though I question if it's worth the complexity).

**Comment by ifed01** [comment]
> @ifed01 I haven't looked closely at this yet, but after a quick skim, does this go back to (potentially) scanning the entire onode list again during trim? That was exactly the problem the original PR was trying to address (though I question if it's worth the complexity at this point).

@markhpc - no, this PR 'physically' removes pinned onode from cache while logically (i.e. corresponding 'cached' flag in onode is set) it's still their. And doesn't put pinned onode into pin_list but marks it with pinned flag instead.
Hence trim doesn't see pinned onodes

**Comment by jdurgin** [comment]
@liewegas I think we'd be better off addressing scrub or other background/single-use callers specifically by making them not cache (https://trello.com/c/3OZ417Si/516-bluestore-prevent-scrub-from-polluting-onode-cache)

It'd be good to run this through some perf tests anyway to see if there's any detectable difference (I'm not sure whether the lack of lru position will matter in practice)

**Comment by ifed01** [comment]
Marking DNM/WIP as I can still see some occasional failures.

**Comment by markhpc** [comment]
> > @ifed01 I haven't looked closely at this yet, but after a quick skim, does this go back to (potentially) scanning the entire onode list again during trim? That was exactly the problem the original PR was trying to address (though I question if it's worth the complexity at this point).
> 
> @markhpc - no, this PR 'physically' removes pinned onode from cache while logically (i.e. corresponding 'cached' flag in onode is set) it's still their. And doesn't put pinned onode into pin_list but marks it with pinned flag instead.
> Hence trim doesn't see pinned onodes

Oh, getting them out of the cache entirely is quite clever!  I will try to look at this more closely next week but that sounds excellent.

**Comment by ifed01** [comment]
This passed ceph_test_objectstore tests, so looks ready for final review.

**Comment by liewegas** [comment]
```
2020-02-01T23:27:11.523 INFO:tasks.ceph.osd.1.smithi037.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/huge/release/15.1.0-157-g6c94e43/rpm/el8/BUILD/ceph-15.1.0-157-g6c94e43/src/os/bluestore/BlueStore.cc: In function 
'void BlueStore::_flush_cache()' thread 14800700 time 2020-02-01T23:27:11.520837+0000
2020-02-01T23:27:11.523 INFO:tasks.ceph.osd.1.smithi037.stderr:/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/huge/release/15.1.0-157-g6c94e43/rpm/el8/BUILD/ceph-15.1.0-157-g6c94e43/src/os/bluestore/BlueStore.cc: 15293: FAILE
D ceph_assert(i->empty())
2020-02-01T23:27:11.576 INFO:tasks.ceph.osd.1.smithi037.stderr: ceph version 15.1.0-157-g6c94e43 (6c94e430dfa71cec909b03cd5b299abfbf1a3943) octopus (rc)
2020-02-01T23:27:11.576 INFO:tasks.ceph.osd.1.smithi037.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x156) [0x614444]
2020-02-01T23:27:11.576 INFO:tasks.ceph.osd.1.smithi037.stderr: 2: (()+0x50c65e) [0x61465e]
2020-02-01T23:27:11.576 INFO:tasks.ceph.osd.1.smithi037.stderr: 3: (BlueStore::_flush_cache()+0xe1c) [0xbdb5ac]
2020-02-01T23:27:11.576 INFO:tasks.ceph.osd.1.smithi037.stderr: 4: (BlueStore::umount()+0x294) [0xbfaa54]
2020-02-01T23:27:11.576 INFO:tasks.ceph.osd.1.smithi037.stderr: 5: (OSD::shutdown()+0xe44) [0x7087e4]
2020-02-01T23:27:11.577 INFO:tasks.ceph.osd.1.smithi037.stderr: 6: (OSD::handle_signal(int)+0x14c) [0x70905c]
2020-02-01T23:27:11.577 INFO:tasks.ceph.osd.1.smithi037.stderr: 7: (SignalHandler::entry()+0x783) [0xcfa513]
2020-02-01T23:27:11.577 INFO:tasks.ceph.osd.1.smithi037.stderr: 8: (()+0x82de) [0xc23a2de]
2020-02-01T23:27:11.577 INFO:tasks.ceph.osd.1.smithi037.stderr: 9: (clone()+0x43) [0xd4d54b3]
2020-02-01T23:27:11.581 INFO:tasks.ceph.osd.1.smithi037.stderr:*** Caught signal (Aborted) **
```
/a/sage-2020-02-01_20:59:41-rados-wip-sage-testing-2020-02-01-1055-distro-basic-smithi/4725021

**Comment by liewegas** [comment]
also from ObjectStore/StoreTest.AttrSynthetic/2
/a/sage-2020-02-01_20:59:41-rados-wip-sage-testing-2020-02-01-1055-distro-basic-smithi/4725032

**Comment by tchaikov** [comment]
```
    -1> 2020-02-05T10:39:56.105+0000 14810700 -1 /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/huge/release/15.1.0-181-g717c438/rpm/el8/BUILD/ceph-15.1.0-181-g717c438/src/os/bluestore/BlueStore.cc: In function 'void BlueStore::_flush_cache()' thread 14810700 time 2020-02-05T10:39:56.022224+0000
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/huge/release/15.1.0-181-g717c438/rpm/el8/BUILD/ceph-15.1.0-181-g717c438/src/os/bluestore/BlueStore.cc: 15293: FAILED ceph_assert(i->empty())

 ceph version 15.1.0-181-g717c438 (717c43834d5ad0d3fd3e2d657b30c09054234929) octopus (rc)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x156) [0x617a84]
 2: (()+0x50fc9e) [0x617c9e]
 3: (BlueStore::_flush_cache()+0xe1c) [0xbe3acc]
 4: (BlueStore::umount()+0x294) [0xc01a54]
 5: (OSD::shutdown()+0xe44) [0x70d994]
 6: (OSD::handle_signal(int)+0x14c) [0x70e20c]
 7: (SignalHandler::entry()+0x783) [0xd022b3]
 8: (()+0x82de) [0xc24a2de]
 9: (clone()+0x43) [0xd4e54b3]
```

/a/kchai-2020-02-05_09:40:13-rados-wip-kefu-testing-2020-02-03-1702-distro-basic-smithi/4734759

**Comment by ifed01** [comment]
@tchaikov - would you give this another QA try, please?

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-07_06:01:29-rados-wip-kefu-testing-2020-07-07-1058-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-08_03:24:15-rados-wip-kefu-testing-2020-07-07-1058-distro-basic-smithi/

after dropping this changeset:

- https://pulpito.ceph.com/kchai-2020-07-08_11:24:04-rados-wip-kefu-testing-2020-07-08-0840-distro-basic-smithi/

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
@tchaikov - honestly I don't understand what's broken in scrubbing if any. But I've made some changes so could you please give this PR another try?

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2020-07-10_14:43:26-rados-wip-kefu-testing-2020-07-10-1523-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-11_05:07:55-rados-wip-kefu-testing-2020-07-11-1109-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2020-07-11_08:56:15-rados-wip-kefu-testing-2020-07-11-1458-distro-basic-smithi/

failures tracked by

- https://tracker.ceph.com/issues/46442

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
