### PR TITLE
nautilus: pybind/mgr/volumes: idle connection drop is not working

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/43137

### CODE REVIEW

**Comment by batrick** [comment]
First attempted backport: https://github.com/ceph/ceph/pull/32076

That one was fine except it was missing https://github.com/ceph/ceph/commit/98e3b7efe8bc92d88f161c892ce91a7fff67052c

We were going to backport the PR which adds that commit but it cannot really be done: https://tracker.ceph.com/issues/43139#note-6

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-02-09-2110-nautilus](https://trello.com/c/hLcgQLuF/822-wip-yuri4-testing-2020-02-09-2110-nautilus)

**Comment by yuriw** [comment]
Note : this is being tested by @ajarr

**Comment by ajarr** [comment]
http://pulpito.ceph.com/rraja-2020-02-11_15:38:34-fs-wip-ajarr-mgr-volumes-features-py2-fix-nautilus-distro-basic-smithi/

**Pull request merged**
