### PR TITLE
Python 3 compatibility of Ceph CLI

### PR DESCRIPTION
**Pull request by BlaXpirit**
This replaces tabs with whitespace, fixes syntax and builtins (most controversial change would be `.iteritems()` -> `.items()` but should be fine).

There was also one bug with the validity check that was undetected on Python 2.

Compatibility down to Python 2.6 remains.

### CODE REVIEW

**Comment by BlaXpirit** [comment]
What happened to the check? I don't see what went wrong from the output.

**Comment by jdurgin** [comment]
The check failure is unrelated - it's one that snuck in recently and appears in the bot sometimes but has eluded manual reproduction so far.

**Comment by jdurgin** [comment]
The changes look good, nice and straightforward. Pushed to wip-ceph-argparse-py3 and will run that through the rados suite once it's built.

**Comment by BlaXpirit** [comment]
Don't merge yet, I've discovered other needed changes when porting the `ceph` script. Maybe it should be one bigger pull request?

**Comment by jdurgin** [comment]
alright, sounds like a good idea to make a larger pr since the ceph_argparse tests don't cover as much as the cli tests do

**Comment by BlaXpirit** [comment]
I continued in this pull request. 

This QA suite finished successfully for me, ran like this (from *src*):

```console
$ PATH="$PATH:$(readlink -f .)" PYTHON=python3 ../qa/workunits/cephtool/test.sh --asok-does-not-need-root
```

It doesn't work from just the default environment, because it also needs *rados* and *cephfs* bindings built for Python 3 specifically (I put their *.py/.so* files right inside *pybind* but there is probably a better way).

**Comment by jdurgin** [comment]
lgtm, as discussed on irc we can merge this now since it doesn't break python 2, and fix any remaining python3 issues once we get python3 integration tests working

**Pull request merged**
