### PR TITLE
os: fix potential null pointer access

### PR DESCRIPTION
**Pull request by xiexingguo**
Fixes: #14204
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas Could you take a look at this? Thanks:))

**Comment by liewegas** [comment]
@xiexingguo can you please rebase on top of wip-bluestore?  thanks!

**Comment by liewegas** [comment]
and target teh PR at wip-bluestore?

**Comment by xiexingguo** [comment]
Obsoleted, reopen at https://github.com/ceph/ceph/pull/7090.

**Pull request closed without merging**
