### PR TITLE
python-common: allow generic alias assignment for drivegroup keys

### PR DESCRIPTION
**Pull request by jschmid1**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jschmid1** [comment]
from __________________ TestCephadm.test_daemon_check_extra_config __________________

```
        if expected != actual:
            cause = expected if isinstance(expected, Exception) else None
>           raise AssertionError(_error_message()) from cause
E           AssertionError: Expected call: _run_cephadm('test', 'mon.test', 'deploy', ['--name', 'mon.test', '--config-json', '-', '--reconfig'], stdin='{"config": "\\n\\n[mon]\\nk=v\\n", "keyring": ""}')
E           Actual call: _run_cephadm('test', 'mon.test', 'deploy', ['--name', 'mon.test', '--reconfig', '--config-json', '-'], image='', stdin='{"config": "\\n\\n[mon]\\nk=v\\n", "keyring": ""}')

```

**Comment by jschmid1** [comment]
@ceph/dashboard 

ceph api tests fail with:

```
dashboard.exceptions.DashboardException: Config option public_bind_addr, public_network is/are not updatable at runtime
```

**Comment by smithfarm** [comment]
@epuertat @callithea Any ideas why the ceph API tests failed like @jschmid1 described in https://github.com/ceph/ceph/pull/37230#issuecomment-700638082 ?

**Comment by smithfarm** [comment]
jenkins test api

**Comment by jschmid1** [comment]
@ceph/orchestrators review pls

**Comment by sebastian-philipp** [comment]
thing is, I actually **don't want** to introduce generic alias assignment for drivegroup keys.

**Pull request closed without merging**
