### PR TITLE
Removed unnecessary inclusion of iostream in several files

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek <stiopa@gmail.com>

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
CXXLD    ceph_test_rados_striper_api_striping
/usr/bin/ld: ./.libs/libcommon.a(Crypto.o): undefined reference to symbol 'PK11_GetBestSlot@@NSS_3.2'
/usr/bin/ld: note: 'PK11_GetBestSlot@@NSS_3.2' is defined in DSO /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libnss3.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libnss3.so: could not read symbols: Invalid operation
</pre>
You should be able to reproduce this error on CentOS 7. If you have docker you can setup an environment with:
<pre>
cd src ; test/docker-test.sh --os-type centos --os-version 7 --shell
</pre>

**Comment by stiopaa1** [comment]
@dachary 
>cd src ; test/docker-test.sh --os-type centos --os-version 7 --shell

This still seem to build fine on my machine (assuming that I've done it correctly).

**Comment by dachary** [comment]
@stiopaa1 would you mind doing **git commit --amend** (just for the purpose of changing the hash of your last commit) followed by a **git push --force** (just for the sake of running the bot again). If the bot shows the exact same error, it will be helpful if you can upload the output of your run. 

Just to avoid any misunderstanding, when you run **cd src ; test/docker-test.sh --os-type centos --os-version 7 --shell** it just gives you a shell on a centos machine, with your latest commit, in the ceph tree. From there it's up to you to **./run-make-check.sh**. Is it what you did ?

**Comment by stiopaa1** [comment]
@dachary after running cd src ; test/docker-test.sh --os-type centos --os-version 7 --shell, I did(in ceph-centos-7-stiopa directory): 
./autogen.sh
./configure
make -j 8
make check

**Comment by dachary** [comment]
@stiopaa1 the ./run-make-check.sh script is run by the bot and does not use the same compilation flag. It's likely you will run into the same problem.

**Comment by dachary** [comment]
<pre>
  CXXLD    ceph_test_rados_api_c_read_operations
/usr/bin/ld: ./.libs/libcommon.a(Crypto.o): undefined reference to symbol 'PK11_GetBestSlot@@NSS_3.2'
/usr/bin/ld: note: 'PK11_GetBestSlot@@NSS_3.2' is defined in DSO /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libnss3.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libnss3.so: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
</pre>

**Comment by stiopaa1** [comment]
@dachary 
so after running  ./run-make-check.sh i'm getting:
configure: error: C compiler cannot create executables

here is the full log:
http://hastebin.com/qapojepuqu.coffee

**Comment by smithfarm** [comment]
Just noticed in the pasted log:

```
    Installed /tmp/easy_install-uQ8jd5/linecache2-1.0.0/pbr-0.11.0-py2.7.egg
      File "build/bdist.linux-x86_64/egg/linecache2/tests/inspect_fodder2.py", line 102
        def keyworded(*arg1, arg2=1):
                                ^
    SyntaxError: invalid syntax
    
      File "/home/stiopa/development/cephStiopa/ceph-centos-7-stiopa/install-deps-python2.7/build/unittest2/linecache2-1.0.0-py2.7.egg/linecache2/tests/inspect_fodder2.py", line 102
        def keyworded(*arg1, arg2=1):
                                ^
    SyntaxError: invalid syntax
```

**Comment by dachary** [comment]
> http://hastebin.com/qapojepuqu.coffee

the config.log file should have more information about why it failed.

**Comment by stiopaa1** [comment]
@dachary, thanks I managed to reproduce it locally - hopefully will work now:)

**Comment by dachary** [comment]
@stiopaa1 that's great. It makes me worried there could problems with other compilation flags. What was the problem ?

**Comment by stiopaa1** [comment]
@dachary 
>It makes me worried there could problems with other compilation flags

The flag that made it fail was --with-debug - without it the file(src/test/cls_rbd/test_cls_rbd.cc) causing the problem wasn't being compiled.


>What was the problem ?

I think(!) that following happened:
The problem was being caused by moving the inline functions from buffer.h to buffer.cc.

The following line was causing the error:
/bin/bash ../libtool  --tag=CXX   --mode=link g++ -I/usr/include/nss -I/usr/include/nspr    -Wall -Wtype-limits -Wignored-qualifiers -Winit-self -Wpointer-arith -Werror=format-security -fno-strict-aliasing -fsigned-char -rdynamic -ftemplate-depth-1024 -Wnon-virtual-dtor -Wno-invalid-offsetof   -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free  -Wstrict-null-sentinel -I../src/gmock/include -I../src/gmock/include -I../src/gmock/gtest/include -I../src/gmock/gtest/include -g -O2 -Wl,--as-needed -latomic_ops  -o ceph_test_cls_rbd test/cls_rbd/ceph_test_cls_rbd-test_cls_rbd.o librados.la libcls_rbd_client.la libcls_lock_client.la libcommon.la ../src/gmock/lib/libgmock_main.la ../src/gmock/lib/libgmock.la ../src/gmock/gtest/lib/libgtest.la -lpthread libradostest.la -lboost_system 

Before the inline functions were moved to buffer.cc, the above didnt't require libcommon library and even though the library is listed it wasn't being linked against. When we move inline functions to buffer.cc(and remove inline) the libcommon is linked against, but is then missing libnss3 library(in Crypto.o), hence the error:
 
/usr/bin/ld: ./.libs/libcommon.a(Crypto.o): undefined reference to symbol 'PK11_GetBestSlot@@NSS_3.2'
/usr/bin/ld: note: 'PK11_GetBestSlot@@NSS_3.2' is defined in DSO /usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libnss3.so so try adding it to the linker command line
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/../../../../lib64/libnss3.so: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status

**Comment by dachary** [comment]
that makes sense. It also deserves explaining in the commit message. Also the main commit does not just remove unused iostream. It deserves a detailed explanation of why it is a good thing. Why moving functions from buffer.h to buffer.cc is beneficial ?

**Comment by dachary** [comment]
And the two commits can be squashed together I think. Apart from the commit message the change looks great.

**Comment by dachary** [comment]
I think the most important thing to explain is why performances won't be negatively affected by having the functions not inline anymore.

**Comment by stiopaa1** [comment]
@dachary 
Hope that's enough:)

**Comment by dachary** [comment]
@stiopaa1 buffer.cc being used extensively throughout the code base, there needs to be certainty that it won't affect performances. Can you make an extra effort to verify and explain ? I think you're right and it would probably not matter as much if it was not in such a central place.

**Comment by dachary** [comment]
@stiopaa1 the rest of the explaining is good enough. I even think you should merge the two commits together because the first won't even link without the second.

**Comment by stiopaa1** [comment]
@dachary 
>buffer.cc being used extensively throughout the code base, there needs to be certainty that it won't affect performances. Can you make an extra effort to verify and explain ?

I'll have a look into that

**Comment by stiopaa1** [comment]
@dachary 
std::ostream& operator<<(std::ostream& out, buffer::error& e);
is only called in one place (mds/CInode.cc ln 1080 _fetched function), making this function not inline definitely won't make a difference to _fetched function.

As for
std::ostream& operator<<(std::ostream& out, const buffer::ptr& bp)
std::ostream& operator<<(std::ostream& out, const buffer::list& bl);

,even if those are inlined, I don't see how one additional function call would change anything in such a big functions.

Also all of the above functions use streams, which are pretty slow.

**Comment by dachary** [comment]
@gregsfortytwo I'd like a second opinion on this one. I don't have actual first hand experience about moving functions from inline to not inline.

**Comment by tchaikov** [comment]
sorry for chiming in, i tend to agree with @stiopaa1 , the `inline` specifier is more of a hint to the compiler. would better to just let the compiler to make the call to inline small functions. `-O2` enables this option. see https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html .

**Comment by dachary** [comment]
@tchaikov I'm probably over cautious because I don't know this topic.

**Comment by gregsfortytwo** [comment]
@dachary luckily it looks like we're only moving the ostream operators for bufferlists, and we don't care about the performance of those as far as I know even if it were a problem. Which it probably shouldn't be although if this were a performance patch I would want confirmation. :)

I'll try and poke @jdurgin about this just in case there's something weird about test_cls_rbd (shouldn't be) but this is good to merge as far as I can tell. Thanks @stiopaa1!
@tchaikov was that a Reviewed-by: from you? I was mostly skimming.

**Comment by gregsfortytwo** [comment]
Yep, Josh says we can do whatever we want with the test linkage. ;)

**Comment by tchaikov** [comment]
> @tchaikov was that a Reviewed-by: from you? I was mostly skimming.

@gregsfortytwo the changes look good except the newly added `CEPH_GLOBAL`. CEPH_GLOBAL is for those binaries who are referencing global variables like `g_conf`, `g_ceph_context`, and `global_*` functions.

@stiopaa1 probably we can add $(CRYPTO_LIBS) and $(EXT

**Comment by gregsfortytwo** [comment]
Okay, you can shepherd it if that's an issue. :)

**Comment by stiopaa1** [comment]
>@stiopaa1 probably we can add $(CRYPTO_LIBS) and $(EXTRALIBS) instead of$(CEPH_GLOBAL). but i am also fine if you want to stick with the later, as you may already noticed, some other tests are also linking agaist it

@tchaikov I have replaced CEPH_GLOBAL with CRYPTO_LIBS and EXTRALIBS as suggested.

**Comment by tchaikov** [comment]
@stiopaa1 thank you Michal! i am pushing your changes to ceph.git/wip-4707. once it is confirmed by the builders, will merge it.

**Comment by tchaikov** [comment]
@stiopaa1 , the build failed at http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-rpm-centos6-5-amd64-basic/log.cgi?log=68c3ac2bef13214263bf7b47567978e8ceb52249
```
CXX test/osd/Object.o
CXX test/osd/RadosModel.o
test/osd/Object.cc: In member function 'bool ObjectDesc::check(ceph::bufferlist&)':
error: test/osd/Object.cc:169: 'cout' is not a member of 'std'
error: test/osd/Object.cc:173: 'cout' is not a member of 'std'
error: test/osd/Object.cc:180: 'cout' is not a member of 'std'
```

Michal, could you also `#include <iostream>` in `test/osd/Object.cc` to fix this also? thanks =)

**Comment by stiopaa1** [comment]
@tchaikov 
I've included iostream in Object.cc

Any idea why the build first failed and then succeeded?

**Comment by dachary** [comment]
@tchaikov @stiopaa1 you can ignore https://github.com/ceph/ceph/pull/4707#issuecomment-110266924 this is a false negative

**Pull request merged**
