### PR TITLE
[wip] os: improve a little performance by less If judgment

### PR DESCRIPTION
**Pull request by shun-s**
improve a little performance by less If judgment

Signed-off-by: shun-s song.shun3@zte.com.cn

### CODE REVIEW

**Comment by shun-s** [comment]
@markhpc 
this pr has been proposed for a long time, could you merge it?
or whether there are some modifications needed?
if that's the case,i'd like to modify, thanks

**Comment by yuyuyu101** [comment]
I don't think this related to performance optimization. It's just moving "if else" to another place.

**Comment by shun-s** [comment]
@yuyuyu101 
Originally,  ' if (bmax) ' and 'if (eleft)' are separatelly to be run many times in the while loop, likely 8 times in my running 4k random write. 
but after modification, only once needs before while loop.
so i think it can have a little benefit to the performance.

**Comment by markhpc** [comment]
I guess the question I have is whether or not this actually shows a measurable difference in any tests?  Ultimately this is Sam's call, but generally we've been rather picky about making sure changes to filestore show clear improvement before merging them.

**Pull request closed without merging**
