### PR TITLE
cephfs-top: add version in header

### PR DESCRIPTION
**Pull request by joscollin**
## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by joscollin** [comment]
jenkins test make check

**Comment by joscollin** [comment]
jenkins test api

**Review by dparmar18 — APPROVED** [review]
LGTM

**Comment by joscollin** [comment]
@vshankar Any thoughts on this?

**Comment by joscollin** [comment]
jenkins test api

**Comment by joscollin** [comment]
jenkins test windows

**Comment by vshankar** [comment]
> @vshankar Any thoughts on this?

What's the rationale behind adding the version?

**Comment by vshankar** [comment]
@joscollin Please hold back merging PRs (even if they are approved) as it _may_ require a broader discussion.

**Comment by joscollin** [comment]
> > @vshankar Any thoughts on this?
> 
> What's the rationale behind adding the version?

The user can see which version it is.

**Comment by joscollin** [comment]
> @joscollin Please hold back merging PRs (even if they are approved) as it _may_ require a broader discussion.

I've been instructed to do so. I also don't want to wait for something that blocks my work.

**Comment by vshankar** [comment]
> > > @vshankar Any thoughts on this?
> > 
> > 
> > What's the rationale behind adding the version?
> 
> The user can see which version it is.

Doesn't `cepfs-top --version` give the required info?

**Comment by vshankar** [comment]
> > @joscollin Please hold back merging PRs (even if they are approved) as it _may_ require a broader discussion.
> 
> I've been instructed to do so. I also don't want to wait for something that blocks my work.

Instructed by whom?

**Comment by joscollin** [comment]
> > > > @vshankar Any thoughts on this?
> > > 
> > > 
> > > What's the rationale behind adding the version?
> > 
> > 
> > The user can see which version it is.
> 
> Doesn't `cepfs-top --version` give the required info?

There is no --version, afaik.

**Comment by vshankar** [comment]
> There is no --version, afaik. Many discussions about cephfs-top and 'perf stats' came across `which version` in the user list. I think this would be informative to the user.

You could add `--version` arg, isn't it?

**Comment by joscollin** [comment]
> > There is no --version, afaik. Many discussions about cephfs-top and 'perf stats' came across `which version` in the user list. I think this would be informative to the user.
> 
> You could add `--version` arg, isn't it?

It could be done as a new PR. But the need for `--version` is different, especially if the other tools need to access it for some reason. I don't see any such requirement while creating this PR.

**Comment by vshankar** [comment]
> > > There is no --version, afaik. Many discussions about cephfs-top and 'perf stats' came across `which version` in the user list. I think this would be informative to the user.
> > 
> > 
> > You could add `--version` arg, isn't it?
> 
> It could be done as a new PR. But the need for `--version` is different, especially if the other tools need to access it for some reason. I don't see any such requirement while creating this PR.

Which tools? And there are tools out there that need this bit of information, `--version` is scriptable.

**Comment by joscollin** [comment]
> > > > There is no --version, afaik. Many discussions about cephfs-top and 'perf stats' came across `which version` in the user list. I think this would be informative to the user.
> > > 
> > > 
> > > You could add `--version` arg, isn't it?
> > 
> > 
> > It could be done as a new PR. But the need for `--version` is different, especially if the other tools need to access it for some reason. I don't see any such requirement while creating this PR.
> 
> Which tools? And there are tools out there that need this bit of information, `--version` is scriptable.

Please create a tracker. It's a new requirement.

**Pull request merged**
