### PR TITLE
rados: list objects in snapshots

### PR DESCRIPTION
**Pull request by xinxinsh**
Fixes: http://tracker.ceph.com/issues/17929

Signed-off-by: xinxin shu <shuxinxin@chinac.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I take it from the passing unit tests that the OSD-side does implement this snapshot handling correctly @athanatos?
The client-side bits here LGTM.

**Comment by liewegas** [comment]
It does, but IIRC it is not efficient... we have to load teh object_info_t 
for every object to determine whether it belongs to the snapshot.

**Comment by athanatos** [comment]
This doesn't actually seem like a good idea.  It gives the impression that the scan is efficient, but will actually iterate over all objects in the pool.  It seems to me that any application designed to actually use this would inevitably fail at scale and would end up having to maintain a look-aside index anyway.

**Comment by xinxinsh** [comment]
should i reopen this pr after a look-aside index is implemented?

**Comment by liewegas** [comment]
Yeah.. if we decide to do a look-aside index.  I'm not sure if it's 
worthwhile.  Do you have a use case that needs it?

**Comment by xinxinsh** [comment]
@liewegas , yes , we do have a use case that need list objects of specific object

**Comment by athanatos** [comment]
@xinxinsh Sorry, I don't mean a look-aside index built into the OSD.  I mean you can build an application level index perhaps using omap objects like radosgw (though make sure no single object gets larger than a few MB).  I'm closing this for now.

**Pull request closed without merging**
