### PR TITLE
qa: ignore variation of PG_DEGRADED health warning

### PR DESCRIPTION
**Pull request by batrick**
Fixes: https://tracker.ceph.com/issues/65700

## Checklist
- Component impact
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
jenkins test api

**Review by leonid-s-usov — APPROVED** [review]

**Review by vshankar — APPROVED** [review]
These are super irritating in our test runs :/

**Comment by batrick** [comment]
This PR is under test in [https://tracker.ceph.com/issues/65771](https://tracker.ceph.com/issues/65771).

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/65771#note-3

**Pull request merged**
