### PR TITLE
rgw multisite: avoid writing bilog entries on PREPARE and CANCEL

### PR DESCRIPTION
**Pull request by cbodley**
in data sync, `RGWBucketShardIncrementalSyncCR` skips any bilog entries whose `op == CLS_RGW_OP_CANCEL` or `state != CLS_RGW_STATE_COMPLETE`, so we should avoid writing these bilog entries in the first place

### CODE REVIEW

**Comment by cbodley** [comment]
@yehudasa we had discussed this as a multisite optimization a while ago. can you please help with review?

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2019-03-29_19:48:48-rgw-wip-cbodley-testing-distro-basic-smithi/

lots of ceph-mon valgrind issues from http://tracker.ceph.com/issues/38827, otherwise clean

**Comment by ivancich** [comment]
I think this may have broken some testing in test_cls_rgw.cc in TEST_F(cls_rgw, bi_log_trim) . Currently looking into it.

**Comment by tchaikov** [comment]
thanks @ivancich ! as the test failure is reproduciable when running rados suite. i filed https://tracker.ceph.com/issues/41722 and assigned it to you. so ppl can be aware that this issue is under investigation.

**Comment by cbodley** [comment]
thanks guys, i have a fix in https://github.com/ceph/ceph/pull/30268

**Pull request merged**
