### PR TITLE
tools:remove the local file when get map failed

### PR DESCRIPTION
**Pull request by caibo2014**
you can see more info here:
http://tracker.ceph.com/issues/13078

### CODE REVIEW

**Comment by tchaikov** [comment]
@caibo2014 , could you describe what you fixed in title, instead of putting the symptom?

**Comment by caibo2014** [comment]
@tchaikov updated

**Comment by tchaikov** [comment]
@caibo2014 you might want to update the commit message of https://github.com/caibo2014/ceph/commit/bb172dd89aefa0d585a8badee838ae1a0042bc09 ?

**Comment by caibo2014** [comment]
@tchaikov updated. ^-^

**Comment by caibo2014** [comment]
@tchaikov could you review this request?
thanks!

**Pull request merged**
