### PR TITLE
os/bluestore: fix 'unused' calculation

### PR DESCRIPTION
**Pull request by ifed01**
This is an alternative solution to https://github.com/ceph/ceph/pull/30444.
The latter seems to need unused bitmap extension to cover maximum blob length.
Hence suggesting more simpler fix for the original issue.

Fixes: https://tracker.ceph.com/issues/41901
Signed-off-by: Igor Fedotov <ifedotov@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@xiexingguo ping?

**Comment by xiexingguo** [comment]
It looks to me like this will fix the unused calculation for new-allocated blob only. How about the existing ones? @ifed01

**Comment by ifed01** [comment]
@xiexingguo - right! This doesn't fix existing blobs. And I'm not sure if such a fix is doable.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-03-29_08:38:08-rados-wip-kefu-testing-2020-03-29-1503-distro-basic-smithi/

failures are not related.

**Pull request merged**
