### PR TITLE
  mon/MonClient: fix error in 'ceph ping mon.id'

### PR DESCRIPTION
**Pull request by hjwsm1989**
Fixes: #12442

  Signed-off-by: huangjun <hjwsm1989@gmail.com>

### CODE REVIEW

**Comment by hjwsm1989** [comment]
@tchaikov i'am not so sure why after the monclient called build_initial_monmap, the monmap.mon_addr use the 'noname-ID' but not mon.ID

**Comment by tchaikov** [comment]
@hjwsm1989, neither do i. imho, we might want to root cause the "noname-ID" issue before trying to cover it up with this fix.

**Comment by hjwsm1989** [comment]
there are two places to do monmap.rename() in ceph_mon.cc  main() function and Monitor::handle_probe_reply(), so we get the raw monmap in MonClient::build_initial_monmap,
which we should get current monmap instead.

**Comment by tchaikov** [comment]
@hjwsm1989 iiuc, what you mean is:

1. there are chances that the mon names are changed after they are originally created, as you point out.
1. the `MonClient` is still using the one, say the `noname-<monid>`, created by `MonClient::build_initial_monmap()`, which could be changed already.
1. so we should check the mon-id against the current monmap instead.

**Comment by hjwsm1989** [comment]
yes,

**Comment by tchaikov** [comment]
but if the mon name is changed, how can we find its address with this new name by looking it up in the outdated monmap? as without this heuristic, we can hardly figure out the right mon name. so probably, that's a chicken or the egg dilemma. hence we should stick with your approach: to add the prefix if the mon name is not in mon map.

**Comment by hjwsm1989** [comment]
yes, you are right, if there is no 'mon host' and no mon section in local ceph.conf, all cmd 'ceph ' will failed, cause we can not find mon to connect.

**Comment by tchaikov** [comment]
@hjwsm1989 this fix does address the issue where the monitor could remove the "noname-" prefix from its name when it starts up. we might want to wait for more opinions before LGTM.

@gregsfortytwo , @jecluis what do you think?

**Comment by gregsfortytwo** [comment]
I don't think this is something we want generally...it looks like a workaround for one specific user misconfiguration (in http://tracker.ceph.com/issues/12442 it looks like they used host names in one monitor location, and IPs in another, and they aren't matched in the hostname lookup).

But I don't remember all the details of the monitor name mapping, and ceph ping might bypass some of them, so best to have @jecluis check it out.

**Comment by tchaikov** [comment]
i don't think it's due to user misconfiguration, but caused by the monitor rename after it is launched. see ceph_mon.cc

```c++
	// is a local address listed without a name?  if so, name myself.
	list<entity_addr_t> ls;
	monmap.list_addrs(ls);
	entity_addr_t local;

	if (have_local_addr(g_ceph_context, ls, &local)) {
	  string name;
	  monmap.get_addr_name(local, name);

	  if (name.find("noname-") == 0) {
	    cout << argv[0] << ": mon." << name << " " << local
		 << " is local, renaming to mon." << g_conf->name.get_id() << std::endl;
	    monmap.rename(name, g_conf->name.get_id());
	  } else {
	    cout << argv[0] << ": mon." << name << " " << local
		 << " is local, but not 'noname-' + something; not assuming it's me" << std::endl;
	  }
	}
```

and the MonClient builds up the mon map in this way:
```c++
  if (!conf->mon_host.empty()) {
    int r = build_from_host_list(conf->mon_host, "noname-");
    if (r < 0) {
      errout << "unable to parse addrs in '" << conf->mon_host << "'"
             << std::endl;
      return r;
    }
    return 0;
  }
```
where the "noname-" prefix is added.

**Comment by dachary** [comment]
@hjwsm1989 could you please add tests that demonstrate the problem and verify this fixes it ?

**Comment by jecluis** [comment]
I think the patch fixes the appropriate issue.

The 'noname-a' spit out by MonMap:build_initial() is a placeholder for the monitor name when we don't really have said names. The ceph_mon does populate the map somewhat appropriately using 'mon initial members' and by knowing its own id. We don't really get to do that on the clients, because then we would have to force ordering the addresses and the 'members' to match 1:1, and I don't think it actually solves the issue.

The real issue here is that 'ping' (via MonClient::ping_monitor()) short-circuits the Client's typical discovery mechanisms. The client will usually authenticate with a monitor from the initial build momnap, without regard for the monitor name -- it will just care for its ip address, given any monitor will do --, and it will then get a full monmap from the monitors.

MonClient::ping_monitor() is, by design, skipping auth. This is because auth only happens when there's a quorum, and the ping is meant to let the client know whether a given monitor is alive or not, even in the absence of quorum. Again, this means skipping authentication. No authentication, no brand new monmap. And the bug here lies with assuming a fully populated monmap exists.

This would easily be fixed by monitor-specific sections in the conf, but that's really just a workaround; not a fix.

I agree with @hjwsm1989's fix. I think the patch could be a little bit better, but that will be commented on the patch instead. I believe the solution is sound, and it doesn't touch any other portion of the monclient code. MonClient::ping_monitor() is an exception, and fixing it like this, exceptionally, is okay.

**Comment by hjwsm1989** [comment]
@jecluis i changed the fix,  can you review it?

**Comment by jecluis** [comment]
lgtm

it would be nice to have a test for this though, but given our tests are all based on vstart.sh -- and vstart will populate the mon sections of ceph.conf -- I'm not sure how we can generate a configuration in which this would happen. @dachary any ideas?

**Comment by dachary** [comment]
https://github.com/ceph/ceph/blob/infernalis/src/test/mon/osd-crush.sh can be copied into mon-ping.sh or something. Each test runs a mon (run_mon) and can provide arguments that override the default conf. See https://github.com/ceph/ceph/blob/infernalis/qa/workunits/ceph-helpers.sh#L239 for the documentation of the run_mon function.

**Comment by tchaikov** [comment]
@hjwsm1989 ping?

**Comment by jecluis** [comment]
I've got a test for this in #5859. This pull request must go in first though. If no one objects, I'll merge this later today.

**Comment by tchaikov** [comment]
:+1: with the test!

**Comment by jecluis** [comment]
Test will be merged shortly after. Needs a rebase on top of this and an okay from the make check bot for peace of mind ;)

**Pull request merged**
