### PR TITLE
nautilus: debian/control: fix Build-Depends

### PR DESCRIPTION
**Pull request by badone**
it's a regression introduced by 5d6d770e

Fixes: https://tracker.ceph.com/issues/50040

Signed-off-by: Kefu Chai <kchai@redhat.com>
(cherry picked from commit f6d7fd28afc3173f023fc290ad57fbcd9e0f3789)

 Conflicts:
	debian/control: Additional package in HEAD

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by badone** [comment]
The 'make check' is failing on mk-build-deps but it's not at all clear why and it works on Bionic for me. Running install-deps.sh on focal seems to indicate the problem may be with a failed install of uuid-runtime due to a missing /run/uuidd directory?

**Comment by badone** [comment]
I need to better understand this.

**Review by tchaikov — APPROVED** [review]

**Comment by badone** [comment]
Seems build failure is a known issue.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
superseded by #40485

**Pull request closed without merging**
