### PR TITLE
doc/man/ceph-volume.rst: Typo in documentation

### PR DESCRIPTION
**Pull request by fastener85**
Removing of the typo in the ceph-volume documentation.

Signed-off-by: Pawel Szweminski <pszwemin@gmail.com>

- [ ] References tracker ticket
- [X] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by alfredodeza** [comment]
The change looks good but you need to sign the commit and update the message. These steps are described here: https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#signing-contributions

Hope you can make the updates!

**Comment by fastener85** [comment]
Now everything should be OK.

**Comment by neha-ojha** [comment]
@fastener85 You'll need to `git commit --amend` to add your `Signed-off-by:` in your commit message.

**Comment by neha-ojha** [comment]
> Add additional commit.
> 
> Signed-off-by: Pawel Szweminski [pszwemin@gmail.com](mailto:pszwemin@gmail.com)

You do not need to add a comment here. You need to add a `Signed-off-by:` to your existing git commit. 

git log should show something like this:

```
Update ceph-volume.rst
Typo in documentation.

Signed-off-by: Pawel Szweminski pszwemin@gmail.com
```

hope that helps!

**Comment by fastener85** [comment]
abandon

**Pull request closed without merging**
