### PR TITLE
journal: optimize object overflow detection

### PR DESCRIPTION
**Pull request by trociny**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman with this change it seems `guard_append` is not needed. Didn't I missed something?

Also, I am aware of aligned appends optimization you proposed [1] and actually would like to work on this too, but it seems to be orthogonal to this PR.

[1] https://tracker.ceph.com/issues/39968

**Comment by dillaman** [comment]
@trociny There is a (maybe?) long-term goal of supporting multiple images writing to the same journal. If that's the case, we won't actually know how populated the current object is since another process/image might also append to it. That was the only real rationale for the guard -- was to protect this possible future case scenario.

**Comment by dillaman** [comment]
... but technically, we can probably yank the ```guard_append``` for now since we only have a single journal mode.

**Comment by trociny** [comment]
Ah, potential multiple writes. Then I am fine with dropping my second commit as I suppose sending `append_guard` would not hurt. And then I will update `TestObjectRecorder.Overflow` to actually test this possible scenario.

**Comment by trociny** [comment]
@dillaman updated

**Comment by tchaikov** [comment]
retest this please.

**Pull request merged**
