### PR TITLE
rpm,cmake: s/WITH_LIBZBD/WITH_ZBD/ and enable ZBD on demand

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by jdurgin — APPROVED** [review]

**Review by neha-ojha — APPROVED** [review]

**Comment by agayev** [comment]
@tchaikov following here from the email thread.  The symptom it is not working, is that I get the following error message during vstart:

2020-10-27T23:18:18.164-0400 7efdb46d5d80 -1 Allocator::create unknown alloc type zoned

which means the following code in src/os/bluestore/Allocator.cc does not get compiled in, because HAVE_LIBZBD is undefined

#ifdef HAVE_LIBZBD
  } else if (type == "zoned") {
    return new ZonedAllocator(cct, size, block_size, name);
#endif

**Comment by agayev** [comment]
@tchaikov I verified that HAVE_LIBZBD isn't getting defined.  If I remove the above #ifdef and compile, then I do not get Allocator::create error.

Does the following set HAVE_LIBZBD only during the compilation of HMSMRDevice.cc?  If yes, then that explains.


if(WITH_ZBD)                                                                                                                      
  find_package(zbd REQUIRED)                                                                                                      
  set(HAVE_LIBZBD ${ZBD_FOUND})                                                                                                   
  list(APPEND libblk_srcs                                                                                                         
    zoned/HMSMRDevice.cc)                                                                                                         
endif()

**Comment by agayev** [comment]
@tchaikov the following patch, on top of what you have here, is one way to fix it -- I verified that it works.  Can you please update your PR with it or some variant of it that you think makes sense?  Thanks!

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 994f86888f..6603a5a700 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -186,6 +186,10 @@ if(WITH_BLUESTORE)
   if(LINUX)
     find_package(aio)
     set(HAVE_LIBAIO ${AIO_FOUND})
+    if(WITH_ZBD)
+      find_package(zbd)
+      set(HAVE_LIBZBD ${ZBD_FOUND})
+    endif()
   elseif(FREEBSD)
     # POSIX AIO is integrated into FreeBSD kernel, and exposed by libc.
     set(HAVE_POSIXAIO ON)
diff --git a/src/blk/CMakeLists.txt b/src/blk/CMakeLists.txt
index bbbe62ff13..0022cf6d5e 100644
--- a/src/blk/CMakeLists.txt
+++ b/src/blk/CMakeLists.txt
@@ -20,9 +20,7 @@ if(WITH_SPDK)
     spdk/NVMEDevice.cc)
 endif()
 
-if(WITH_ZBD)
-  find_package(zbd REQUIRED)
-  set(HAVE_LIBZBD ${ZBD_FOUND})
+if(HAVE_LIBZBD)
   list(APPEND libblk_srcs
     zoned/HMSMRDevice.cc)
 endif()
diff --git a/src/os/CMakeLists.txt b/src/os/CMakeLists.txt
index e4920f0c8b..375811a680 100644
--- a/src/os/CMakeLists.txt
+++ b/src/os/CMakeLists.txt
@@ -37,7 +37,7 @@ if(WITH_BLUESTORE)
   )
 endif(WITH_BLUESTORE)
 
-if(WITH_ZBD)
+if(HAVE_LIBZBD)
   list(APPEND libos_srcs
     bluestore/zoned_types.cc
     bluestore/ZonedFreelistManager.cc

```

**Comment by tchaikov** [comment]
@agayev eureka! think the root cause is that it's too late to define `HAVE_LIBZBD` -- we need to set it before executing
```cmake
configure_file(
  ${CMAKE_SOURCE_DIR}/src/include/config-h.in.cmake
  ${CMAKE_BINARY_DIR}/include/acconfig.h
)
```
as the lexical scope of `HAVE_LIBZBD` in existing code failed to enable the statement above "see" it.

i will update this PR with a new commit to address this. `

**Comment by tchaikov** [comment]
@agayev could you help test the latest revision?

**Comment by agayev** [comment]
> @agayev could you help test the latest revision?

@tchaikov it worked, thanks!

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2020-10-30_02:27:32-rados-wip-kefu-testing-2020-10-29-2343-distro-basic-smithi/

**Pull request merged**
