### PR TITLE
ceph-disk: CentOS 7 is systemd

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/12786 Fixes: #12786

Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
@trhoden does that look like a good enough solution until a more general way to converge ceph-deploy and ceph-detect-init is found ?

**Comment by trhoden** [comment]
Hmm, I guess I"m still slightly confused on where we are going with this.  Why just CentOS (what about RHEL and Fedora?).  And why not base it on the `ceph.target` file like ceph-deploy did?

**Comment by dachary** [comment]
@trhoden ceph-detect-init ships with Ceph, hence it does not need to guess which version of Ceph is running. Reason why it was decided to rely on ceph-detect-init for ceph-deploy to figure out which init system is supposed to be supported on a given host (i.e. instead of guessing via the existence of a file which is fragile, it could call ceph-detect-init instead).

**Comment by liewegas** [comment]
we should do the same for rhel.  otherwise lgtm?

**Comment by dachary** [comment]
Fedora >= 22 is also systemd ?

**Comment by dachary** [comment]
Hum I guess that should be against infernalis really.

**Pull request closed without merging**
