### PR TITLE
mgr/BaseMgrModule: tolerate Int or Long for health 'count'

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
```
<batrick> sage: " -1 ceph_set_health_checks check RECENT_CRASH count value not long" in multimds but not fs/kcephfs ; I don't see a particular reason why multimds would be seeing those errors and not fs/kcephfs
```

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
looks like failures relating ot the failure injection:

    "assert_condition": "g_conf()->mds_kill_mdstable_at != 4",

**Comment by batrick** [comment]
> looks like failures relating ot the failure injection: "assert_condition": "g_conf()->mds_kill_mdstable_at != 4",

Right, but the warnings should be disabled because of https://github.com/ceph/ceph/commit/90f04775fc5e3162001290b4f4edb5f5e8b420b7

**Comment by wjwithagen** [comment]
@liewegas
Looks like this will not work when using Python 3.6.
My master36 builder complains:
```
/home/jenkins/workspace/ceph-master36/src/mgr/BaseMgrModule.cc:308:13: error: use of undeclared identifier 'PyInt_Check'
        } else if (PyInt_Check(v)) {
                   ^
1 error generated.
```
But looks like `PyLong_Check` would also work for ints on 3.6:
  https://docs.python.org/3.6/c-api/long.html?highlight=pylong_check
```
int PyLong_Check(PyObject *p)
    Return true if its argument is a PyLongObject or a subtype of PyLongObject.
```

**Comment by tchaikov** [comment]
@wjwithagen we are aware of this, see #29831 and #29825.

**Comment by wjwithagen** [comment]
@tchaikov
Did not check the outstanding PRs, will have to do that more.

**Pull request merged**
