### PR TITLE
octopus: mgr/dashboard: Show table details inside the datatable 

### PR DESCRIPTION
**Pull request by callithea**
backport tracker: https://tracker.ceph.com/issues/45232

---

backport of https://github.com/ceph/ceph/pull/32747
parent tracker: https://tracker.ceph.com/issues/40702

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test dashboard

**Comment by bk201** [comment]
Many tables' detail row is collapsed after table is refreshed, for example Pools page. It doesn't seem to happen in master.

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
> Many tables' detail row is collapsed after table is refreshed, for example Pools page. It doesn't seem to happen in master.

Hey @bk201, how exactly did you refresh the page? Did you switch between pages or did you reload the page or do you mean when switching e.g. between the "tab" let's say "Pools List" and "Overall Performance" ?

**Comment by bk201** [comment]
I rebased and re-build, the problem is gone. Sorry for the noise! 
> Hey @bk201, how exactly did you refresh the page? Did you switch between pages or did you reload the page or do you mean when switching e.g. between the "tab" let's say "Pools List" and "Overall Performance" ?

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by tspmelo** [comment]
[page-helper.po.ts#L193](https://github.com/ceph/ceph/blob/octopus/src/pybind/mgr/dashboard/frontend/cypress/integration/page-helper.po.ts#L193) needs to be restored to the code we have in master: [page-helper.po.ts#L188](https://github.com/ceph/ceph/blob/master/src/pybind/mgr/dashboard/frontend/cypress/integration/page-helper.po.ts#L188)

**Pull request merged**
