### PR TITLE
cephadm: make bootstrap default to "global" section for public_network setting

### PR DESCRIPTION
**Pull request by adk3798**
Fixes: https://tracker.ceph.com/issues/68212

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by adk3798** [comment]
https://pulpito.ceph.com/phlogistonjohn-2024-10-15_13:29:56-orch:cephadm-wip-adk-testing-2024-10-14-1530-distro-default-smithi/

Failures:
- 3x failures in smb ctdb tests due to either stray daemon warnings or selinux denials, known issue
- 3x misc. infra/teuthology failures
- 3x mds_upgrade sequence timeouts or cluster log warnings, known issue
- 2x rgw ingress test timeouts, known issue
- mgr-nfs-upgrade failure, looks like it tried to check all the daemons were upgraded while only the first mgr had been upgraded. It looks like maybe something went wrong with the check to make sure the upgrade had completed.

Would maybe hold off on merging upgrade related PRs, but everything else should be okay.

**Comment by adk3798** [comment]
jenkins test make check

**Review by rkachach — APPROVED** [review]
LGTM

**Review by phlogistonjohn — COMMENTED** [review]
I went to review but did not understand why/what this is actually fixing. Reading the issue doesn't reveal that much more either. The code looks fine but I don't know what it's accomplishing.

**Comment by adk3798** [comment]
> I went to review but did not understand why/what this is actually fixing. Reading the issue doesn't reveal that much more either. The code looks fine but I don't know what it's accomplishing.

basically cephadm does a `ceph config set <section> public_network <network>` during bootstrap. We had been defaulting `<section>` to `mon` but we have been told having the mon but not the OSD section having this setting can lead to some issues so we're making the default the `global` section. The end goal after this PR is merges is that users can specify the `public_network` in either the `mon` or `global` section in a provided conf and we'll respect that, but if they just provide the ip through `--mon-ip` or the whole network through `--public-network` rather than through a config file, we'll by default include that setting in the `global` section

**Comment by adk3798** [comment]
https://pulpito.ceph.com/adking-2024-10-30_03:37:52-orch:cephadm-wip-adk-testing-2024-10-29-1832-distro-default-smithi/

Failures:
- 3x SMB ctdb test stray daemon / SELinux denial, known issue
- 2x failures on new tests for mgmt-gateway, caused by PR adding those new tests
- 3x mds_upgrade_sequence failures, known issue
- 1x staggered upgrade with agent failure, known issue

Dead Jobs:
- 1x `Error reimaging machines`, infra/teuthology issue
- 1x rgw-ingress test timeout, known issue
- 1x test_iscsi_container timeout. I've seen this before but thought it had been fixed. Will need to investigate.

Results should only block merging for PRs related to iscsi or mgmt-gateqay/oauth2-proxy. Otherwise, run was okay.

**Pull request merged**
