### PR TITLE
nautilus: build/ops: make patch build dependency explicit

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/40270

---

backport of https://github.com/ceph/ceph/pull/28414
parent tracker: https://tracker.ceph.com/issues/40175

this backport was staged using https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-11-12-2351-nautilusyuriw](https://trello.com/c/BBf5fA8p/758-wip-yuri-testing-2019-11-12-2351-nautilusyuriw)

**Pull request merged**
