### PR TITLE
rgw: Redimension bucket sync cache to include optional generation

### PR DESCRIPTION
**Pull request by adamemerson**
The alternative would be to compare generations and throw out older
generation/no generation if we have a (newer) one.

But if we have the potential for older generations and blank
generations coming up on error retry, then we have to keep them
around.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by cbodley** [comment]
i took this commit into https://github.com/ceph/ceph/pull/45417 with an additional change, can you please review?

**Comment by mattbenjamin** [comment]
Where do blank generations come from?  In discussion w/Yuval, the topic of generation "reset" also came up--is that actually needed?

**Comment by cbodley** [comment]
> Where do blank generations come from?

empty generations come from 'data full sync', which walks through a listing of remote bucket metadata and tries to run sync on each. it doesn't get any information about log generations from that list of bucket metadata keys, so it passed an 'empty' generation number into bucket sync

in `RGWSyncBucketCR` (https://github.com/ceph/ceph/blob/wip-rgw-multisite-reshard/src/rgw/rgw_data_sync.cc#L5368-L5383) we treat an empty generation as a request for the 'current' generation of that bucket's sync status - just because that's the only generation that 'bucket incremental sync' can ever make progress on

> In discussion w/Yuval the topic of generation "reset" also came up--is that actually needed?

not sure what this means

**Comment by cbodley** [comment]
> In discussion w/Yuval, the topic of generation "reset" also came up--is that actually needed?

@yuvalif was that related to bucket sync disable/enable? do you suspect there's a problem with empty gen vs. gen=0 there?

**Comment by cbodley** [comment]
> was wondering about the case where we have incremental sync with some gen going on, and then we disable+enable sync. this results in a full sync with no generation

let's be careful to differentiate between 'bucket full sync' and 'data full sync'. bucket sync disable/enable is cycling through the `Incremental -> Init -> Full -> Incremental` states of bucket sync, not data sync

remember [this logic](https://github.com/ceph/ceph/blob/wip-rgw-multisite-reshard/src/rgw/rgw_data_sync.cc#L5243-L5247) in the `Init` state that fetches the remote's latest log generation and markers, and records them as the position where `Incremental` should resume after `Full`. so bucket sync uses this sync status object to keep track of which generation it's on

**Comment by cbodley** [comment]
merged into wip-rgw-multisite-reshard, thanks @adamemerson

**Pull request closed without merging**
