### PR TITLE
pacific: cephadm Batch backport Febrary (2)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
#39259 #39238 #39261 #38897 #39193 #38695 #39266 #39350 #39153 #37729 #39361 #38505 #39398 #39364 #39058 #38883 #38549 #39385 #39458 #39424 #39473 #39430 #39323 #39490 #39464 #39467 #39330 #38881 #39472

```
    Conflicts:
            src/cephadm/cephadm  # due to pacific-devel-master container image
            doc/dev/cephadm/index.rst  # due to missing doc/dev backport
            src/pybind/mgr/tox.ini # due to unrelated flake8 changes not backported 
            src/pybind/mgr/rook/module.py # due to type annotations for mgr/rook not backported
```

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jmolmo** [comment]
I think that we need to add:
39355 doc/install: cephadm is the successor of DeepSea
39384 Revert "qa/tasks/cephadm: use cluster.sh and remote.sh for better readibility"
39404 qa/suites/upgrade/octopus-x/stress-split: cephadm-based stress-split upgrade
39496 mgr/cephadm: fix host refresh
39131 mgr/rook: disallow_untyped_defs = True


And for this one we decide not to merge. it is correct?
39381 mgr/cephadm: based sleep interval on configured intervals/timeouts

**Comment by sebastian-philipp** [comment]
changelog:

* Removed selinux commits as they are now in #39623
* fixed missing import in rook/module.py

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/

1 failed: (bug not related)
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/5911668/
https://tracker.ceph.com/issues/49456

2 dead: (seems to be environment creation issues)
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/5911671/
https://pulpito.ceph.com/swagner-2021-02-24_09:34:13-rados:cephadm-wip-swagner2-testing-2021-02-23-1116-pacific-distro-basic-smithi/5911703/

**Review by jmolmo — APPROVED** [review]

**Comment by sebastian-philipp** [comment]
regression: #39649

**Pull request merged**
