### PR TITLE
tool/ceph-dedup-tool: perform dedup on snapshotted object during sample dedup

### PR DESCRIPTION
**Pull request by myoungwon**
Perform dedup on snapshotted object during sample dedup work if snapshot option is enabled

Signed-off-by: Myoungwon Oh <myoungwon.oh@samsung.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by athanatos — APPROVED** [review]

**Comment by myoungwon** [comment]
@athanatos Is there remaining works to merge this PR into main?

**Comment by athanatos** [comment]
Should have tagged with needs-qa.  This should probably go in with https://github.com/ceph/ceph/pull/52171

**Comment by athanatos** [comment]
jenkins test api

**Comment by myoungwon** [comment]
To solve a racing problem---multiple threads can change a snapshot context by snap_set_read()---under the snapshot test, I made a small change from the last updates as the following line. 
`    snap(snap) {
      this->io_ctx.dup(io_ctx);
}`
This line is added to the constructor of the SampleDedupWorkerThread.

With this change, it seems like the test results have no related issues.
https://pulpito.ceph.com/myoungwon-2023-10-15_06:36:14-rados-wip-ceph-dedup-tool-snap-add-distro-default-smithi/
https://pulpito.ceph.com/myoungwon-2023-10-23_00:47:41-rados-wip-ceph-dedup-tool-snap-add-distro-default-smithi/

**Comment by myoungwon** [comment]
@athanatos Please see the result above.

**Comment by myoungwon** [comment]
@athanatos ping.

**Comment by athanatos** [comment]
jenkins test make check arm64

**Comment by athanatos** [comment]
jenkins test windows

**Pull request merged**
