### PR TITLE
cleanup function sync_filesystem.

### PR DESCRIPTION
**Pull request by majianpeng**
@tchaikov . Because only filestore use sync_filesystem and in detect_feature, it detect the filestorebackend whether implement syncfs and FileStoreBackend has own syncfs function which call sync_filesystem. So we can move sync_filesystem into GenericFileStoreBackend::syncfs. 

Have you time review this? Thanks!

### CODE REVIEW

**Comment by tchaikov** [comment]
@majianpeng i love your idea of consolidating the code. but still have some concerns mentioned in the inline comment.

**Comment by majianpeng** [comment]
@liewegas . What's your opinion?

**Comment by liewegas** [comment]
@majianpeng the idea was to hide the gory os details from FileStore.  Unless this is fixing a problem, I'm inclined to leave it that way and not make the FileStore code uglier than it has to be :)

**Comment by majianpeng** [comment]
Ok, i'll close this. Thanks very much.

**Pull request closed without merging**
