### PR TITLE
Doc: Add Nautilus 14.2.2 to schedule and releases

### PR DESCRIPTION
**Pull request by jgalvez**
"""
Doc: Add Nautilus 14.2.2 to releases.

The releases and schedule documentation needed to be updated
to include the Nautilus 14.2.2 release.

Fixes: http://tracker.ceph.com/issues/40988
Signed-off-by: JuanJose Galvez <juanjose.galvez@gmail.com>
"""
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by jgalvez** [comment]
> Please sign your commits. See also [1]. This is required for your PR to be merged.
> 
> [1] https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work

Thanks, I've gone ahead and signed off on each commit.

**Comment by neha-ojha** [comment]
> > Please sign your commits. See also [1]. This is required for your PR to be merged.
> > [1] https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work
> 
> Thanks, I've gone ahead and signed off on each commit.

It think the check is still failing because it expects this format: 
`Signed-off-by:  JuanJose Galvez <juanjose.galvez@gmail.com>`

**Comment by jgalvez** [comment]
> > > Please sign your commits. See also [1]. This is required for your PR to be merged.
> > > [1] https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#1-sign-your-work
> > 
> > 
> > Thanks, I've gone ahead and signed off on each commit.
> 
> I think the check is still failing because it expects this format:
> `Signed-off-by: JuanJose Galvez <juanjose.galvez@gmail.com>`

Thanks @neha-ojha, looks like that check passed.

**Comment by neha-ojha** [comment]
jenkins build docs

**Comment by neha-ojha** [comment]
jenkins render docs

**Comment by neha-ojha** [comment]
@batrick this should be ready to merge now

**Pull request merged**
