### PR TITLE
nautilus: mgr/dashboard: SSL certificate upload command throws deprecation warning 

### PR DESCRIPTION
**Pull request by s0nea**
http://tracker.ceph.com/issues/40786

### CODE REVIEW

**Comment by yuriw** [comment]
@s0nea pls rebase:

--- pr 29065 --- pulling https://github.com/s0nea/ceph.git branch wip-40786-nautilus
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Total 12 (delta 10), reused 10 (delta 10), pack-reused 2
Unpacking objects: 100% (12/12), done.
From https://github.com/s0nea/ceph
 * branch            wip-40786-nautilus -> FETCH_HEAD
Auto-merging src/pybind/mgr/dashboard/module.py
CONFLICT (content): Merge conflict in src/pybind/mgr/dashboard/module.py
Auto-merging doc/mgr/dashboard.rst
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 62, in <module>
    assert not r
AssertionError

**Comment by s0nea** [comment]
> @s0nea pls rebase:

@yuriw thanks for the reminder - done

**Comment by tspmelo** [comment]
jenkins test dashboard

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-08-14-1905-nautilus](https://trello.com/c/tuSXFHdO/689-wip-yuri6-testing-2019-08-14-1905-nautilus)

**Pull request merged**
