### PR TITLE
jewel: librbd: is_exclusive_lock_owner API should ping OSD

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/19468

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman Thanks for impeccably following backporting protocol. Just one question: where did the commit 6737dd99be82aab6d50bc4e5872c3673e5add9a9 come from? I fetched ceph/ceph.git but get do not have that commit:

```
smithfarm@wilbur:~/src/ceph/smithfarm/ceph> git show 6737dd99be82aab6d50bc4e5872c3673e5add9a9
fatal: bad object 6737dd99be82aab6d50bc4e5872c3673e5add9a9
```

**Comment by dillaman** [comment]
@smithfarm See the associated kraken branch PR

**Comment by smithfarm** [comment]
@dillaman Thanks. So, the way I see it, we can either mark this DNM until #14480 is merged or you could simply drop the second "(cherry picked from . . . )" line.

**Comment by dillaman** [comment]
@smithfarm I don't think it's a good idea to drop the cherry-pick history.

**Comment by smithfarm** [comment]
OK, marking DNM until #14480 is merged.

**Comment by smithfarm** [comment]
Looks good; will include in next round of integration testing.

**Comment by smithfarm** [comment]
@dillaman This passed a rados run at http://tracker.ceph.com/issues/19538#note-49 and an rbd run at http://tracker.ceph.com/issues/19538#note-57

OK to merge?

**Pull request merged**
