### PR TITLE
mds: replacing bootstrap session only if handle client session message

### PR DESCRIPTION
**Pull request by Mer1997**
Fixes: https://tracker.ceph.com/issues/56116
Signed-off-by: Mer Xuanyi <xuanyi.meng@xtaotech.com>

### Checklist
---
+ Tracker (select at least one)
  - [x] References tracker ticket
+ Component impact
  - [x] No impact that needs to be tracked
+ Documentation (select at least one)
  - [x] No doc update is appropriate
+ Tests (select at least one)
  - [x] No tests

### CODE REVIEW

**Comment by vshankar** [comment]
@Mer1997 Did you think about waiting for the session to be open before marking MDCache as ready?

**Comment by Mer1997** [comment]
> @Mer1997 Did you think about waiting for the session to be open before marking MDCache as ready?

Yes, mdcache needs to wait for two conditions before ready (mds' state is active and the new session is already open)

**Comment by vshankar** [comment]
> > @Mer1997 Did you think about waiting for the session to be open before marking MDCache as ready?
> 
> Yes, mdcache needs to wait for two conditions before ready (mds' state is active and the new session is already open)

And your change implements this by ensuring that the session is only imported when CEPH_MSG_CLIENT_SESSION message is received and not for other request IIUC?

**Comment by Mer1997** [comment]
> > > @Mer1997 Did you think about waiting for the session to be open before marking MDCache as ready?
> > 
> > 
> > Yes, mdcache needs to wait for two conditions before ready (mds' state is active and the new session is already open)
> 
> And your change implements this by ensuring that the session is only imported when CEPH_MSG_CLIENT_SESSION message is received and not for other request IIUC?

Oh sorry, I just misunderstand your meaning. So your meaning is we can stop mds handle_client_session before mdcache is ready?
 I think we just need an assurance to make sure the replacing between bootstrap session and imported only works for the session message.

**Comment by Mer1997** [comment]
> > > > @Mer1997 Did you think about waiting for the session to be open before marking MDCache as ready?
> > > 
> > > 
> > > Yes, mdcache needs to wait for two conditions before ready (mds' state is active and the new session is already open)
> > 
> > 
> > And your change implements this by ensuring that the session is only imported when CEPH_MSG_CLIENT_SESSION message is received and not for other request IIUC?
> 
> Oh sorry, I just misunderstand your meaning. So your meaning is we can stop mds handle_client_session before mdcache is ready? I think we just need an assurance to make sure the replacing between bootstrap session and imported only works for the session message.



> > > > @Mer1997 Did you think about waiting for the session to be open before marking MDCache as ready?
> > > 
> > > 
> > > Yes, mdcache needs to wait for two conditions before ready (mds' state is active and the new session is already open)
> > 
> > 
> > And your change implements this by ensuring that the session is only imported when CEPH_MSG_CLIENT_SESSION message is received and not for other request IIUC?
> 
> Oh sorry, I just misunderstand your meaning. So your meaning is we can stop mds handle_client_session before mdcache is ready? I think we just need an assurance to make sure the replacing between bootstrap session and imported only works for the session message.

In #21996 , patrick said these code is for a race exists be

**Comment by Mer1997** [comment]
Sorry, wrong click, how to re-open it?

**Comment by Mer1997** [comment]
jenkins test api

**Comment by vshankar** [comment]
> Oh sorry, I just misunderstand your meaning. So your meaning is we can stop mds handle_client_session before mdcache is ready?

Nope, the other way around. Defer MDCache processing before a session is "fully" open.

> I think we just need an assurance to make sure the replacing between bootstrap session and imported only works for the session message.

Right. That kind of guarantees that the session won't be replaced for client requests. 

BTW, I commented on the tracker ticket - do you have a workload that reproduces this crash?

**Comment by vshankar** [comment]
> BTW, I commented on the tracker ticket - do you have a workload that reproduces this crash?

never mind - https://tracker.ceph.com/issues/56116#note-4

**Comment by Mer1997** [comment]
jenkins test api

**Comment by Mer1997** [comment]
jenkins test make check

**Comment by Mer1997** [comment]
jenkins test windows

**Comment by vshankar** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-July-04

I did not see any failures in the test run, however, I wasn't able to run the entire fs suite due to this issue: https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/JSZQFUKVLDND4W33PXDGCABPHNSPT6SS/

I'm going to run this through the entire fs suite this week. Will keep you updated @Mer1997

**Comment by Mer1997** [comment]
> https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-July-04
> 
> I did not see any failures in the test run, however, I wasn't able to run the entire fs suite due to this issue: https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/JSZQFUKVLDND4W33PXDGCABPHNSPT6SS/
> 
> I'm going to run this through the entire fs suite this week. Will keep you updated @Mer1997

thanks, and [here](https://mer1997.notion.site/Reproducer-of-56116-95fba4330def44cf8706a20f85eeeebe) is an entire record of this bug, maybe can give you some help (cephfs built by `vstart.sh`)

**Comment by vshankar** [comment]
> > https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-July-04
> > I did not see any failures in the test run, however, I wasn't able to run the entire fs suite due to this issue: https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/JSZQFUKVLDND4W33PXDGCABPHNSPT6SS/
> > I'm going to run this through the entire fs suite this week. Will keep you updated @Mer1997
> 
> thanks, and [here](https://mer1997.notion.site/Reproducer-of-56116-95fba4330def44cf8706a20f85eeeebe) is an entire record of this bug, maybe can give you some help (cephfs built by `vstart.sh`)

FYI - test run: https://pulpito.ceph.com/vshankar-2022-07-05_17:37:39-fs-wip-vshankar-testing1-20220705-144105-testing-default-smithi/

**Comment by Mer1997** [comment]
What is the status of this pull request now? need more test? @vshankar

**Comment by vshankar** [comment]
> What is the status of this pull request now? need more test? @vshankar

I'm going through the test runs today (was on PTO for sometime).

No failures are seen so this will get merged today :)

**Comment by Mer1997** [comment]
> > What is the status of this pull request now? need more test? @vshankar
> 
> I'm going through the test runs today (was on PTO for sometime).
> 
> No failures are seen so this will get merged today :)

ok, thank you :)

**Review by vshankar — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#2022-Aug-12

**Pull request merged**
