### PR TITLE
mailmap for hammer / master 2nd batch

### PR DESCRIPTION
**Pull request by dupont-y**
Work in progress, do not merge tight now.

2nd batch -up to date for master as of 2015 03 23, so far none of these patches has been selected for hammer-

Email verification to be sent.

### CODE REVIEW

**Comment by dachary** [comment]
LGTM, ready to send the mails :-)

**Comment by dupont-y** [comment]
Le 23/03/2015 22:48, Loic Dachary a écrit :
>
> LGTM, ready to send the mails :-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ceph/ceph/pull/4149#issuecomment-85211953>.
>
Fired !

**Comment by dupont-y** [comment]
Mail sent for this batch too.

**Comment by dachary** [comment]
@dupont-y is it good to merge ?

**Comment by dupont-y** [comment]
I suppose it is, as I didn't get answers from authors. Just have to add Reviewed-by: on the ones you reviewed.

**Comment by dupont-y** [comment]
Reviewed-by: added on the ones you reviewed.
Ok to merge

**Pull request merged**
