### PR TITLE
nautilus: mon/OSDMonitor: Use generic priority cache tuner for mon caches

### PR DESCRIPTION
**Pull request by sseshasa**
https://tracker.ceph.com/issues/41238

### CODE REVIEW

**Comment by smithfarm** [comment]
Build failure:

```
[ 38%] Building CXX object src/rgw/CMakeFiles/rgw_common.dir/rgw_keystone.cc.o
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MDSMonitor.cc:23:0:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/OSDMonitor.h:231:34: error: 'Manager' is not a member of 'PriorityCache'
   std::shared_ptr<PriorityCache::Manager> pcm = nullptr;
                                  ^~~~~~~
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/OSDMonitor.h:231:41: error: template argument 1 is invalid
   std::shared_ptr<PriorityCache::Manager> pcm = nullptr;
                                         ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/OSDMonitor.h:231:49: error: cannot convert 'std::nullptr_t' to 'int' in initialization
   std::shared_ptr<PriorityCache::Manager> pcm = nullptr;
                                                 ^~~~~~~
src/mon/CMakeFiles/mon.dir/build.make:206: recipe for target 'src/mon/CMakeFiles/mon.dir/MDSMonitor.cc.o' failed
make[3]: *** [src/mon/CMakeFiles/mon.dir/MDSMonitor.cc.o] Error 1
```

**Comment by sseshasa** [comment]
This has a dependency on the latest changes of priority cache manager being available in nautilus. @markhpc @neha-ojha is there a corresponding backport created for https://github.com/ceph/ceph/pull/27381 and other subsequent improvements to pcm? I can add them as dependencies to this PR on the tracker ticket.

**Comment by neha-ojha** [comment]
> This has a dependency on the latest changes of priority cache manager being available in nautilus. @markhpc @neha-ojha is there a corresponding backport created for #27381 and other subsequent improvements to pcm? I can add them as dependencies to this PR on the tracker ticket.

I don't think so. Yeah, adding references to master PRs/commits should be fine.

**Comment by sseshasa** [comment]
I will open a new branch to track this backport PR as there a lot more commits to be picked from master. Closing this PR.

**Pull request closed without merging**
