### PR TITLE
mon: MonitorDBStore: get_next_key() only if prefix matches

### PR DESCRIPTION
**Pull request by jecluis**
http://tracker.ceph.com/issues/12484

### CODE REVIEW

**Comment by dachary** [comment]
@smithfarm could you add the command line you used to reproduce the problem ? It'll be useful to verify it's fixed.

**Comment by jecluis** [comment]
I've got a patch that fixes this. Just need to figure out why it doesn't break in master first.

**Comment by dachary** [comment]
Also cherry-pick https://github.com/ceph/ceph/pull/5834 to make it work

**Comment by jecluis** [comment]
patch to be cherry-picked is 70d31082fd3dc8c7857994104577f1a3631c678c

**Comment by jecluis** [comment]
I cherry-picked it myself. Feel free to run this through firefly integration tests.

**Comment by dachary** [comment]
@jecluis thanks !

**Pull request merged**
