### PR TITLE
pacific: pybind/mgr: ceph osd status crash with ZeroDivisionError

### PR DESCRIPTION
**Pull request by NitzanMordhai**
backport tracker: https://tracker.ceph.com/issues/54281

---

backport of https://github.com/ceph/ceph/pull/44752
parent tracker: https://tracker.ceph.com/issues/53538

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by NitzanMordhai** [comment]
jenkins test make check

**Comment by k0ste** [comment]
@NitzanMordhai please rebase to trigger CI

**Review by Matan-B — APPROVED** [review]
Note: c09802b65179143558f9436eb7a918d8ba8b9a7b is not part of the original backport. However, it is a (logical) dependency of the bug fix. To avoid any manual conflicts - I think we should backport both commits.

CC: @rzarzynski

**Comment by NitzanMordhai** [comment]
Rados approved
[PACIFIC - RADOS - Ceph](https://tracker.ceph.com/projects/rados/wiki/PACIFIC#httpstrellocomcVTd0dfag1914-wip-yuri7-testing-2023-12-27-1008-pacific-old-wip-yuri7-testing-2023-12-20-0808-pacific)

**Pull request merged**
