### PR TITLE
client: check rdonly file handle on truncate

### PR DESCRIPTION
**Pull request by batrick**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
I'm certainly no expert in this area but I noticed that the _write method has the check expressed as:
```
  if ((f->mode & CEPH_FILE_MODE_WR) == 0)
    return -EBADF;
```
which seems a bit more readable to me, but I may be overlooking a difference.

**Comment by batrick** [comment]
> I'm certainly no expert in this area but I noticed that the _write method has the check expressed as:
> 
> ```
>   if ((f->mode & CEPH_FILE_MODE_WR) == 0)
>     return -EBADF;
> ```
> 
> which seems a bit more readable to me, but I may be overlooking a difference.

Ya, that's simpler. Thanks for the suggestion.

**Comment by batrick** [comment]
https://pulpito.ceph.com/pdonnell-2020-11-14_20:11:02-fs-wip-pdonnell-testing-20201114.181737-distro-basic-smithi/

failures known.

**Comment by batrick** [comment]
@ceph/cephfs ping

**Review by jtlayton — APPROVED** [review]

**Pull request merged**
