### PR TITLE
mgr/dashboard: Use ModalComponent in all modals

### PR DESCRIPTION
**Pull request by tspmelo**
Also append "Modal" to all modal components names.

Fixes: https://tracker.ceph.com/issues/44547

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tspmelo** [comment]
@epuertat for reference, here is the issue that talks about your suggestion:
https://tracker.ceph.com/issues/38765

**Comment by epuertat** [comment]
> @epuertat for reference, here is the issue that talks about your suggestion:
> https://tracker.ceph.com/issues/38765

That's it. Thanks a lot, @tspmelo !

**Comment by votdev** [comment]
> I think we already discussed about this in a daily/biweekly meeting long ago, but I think it makes sense to bring this in one more time: have we explored the possibility of using [schema/JSON-driven forms/components](https://angular2-json-schema-form.firebaseapp.com/)? I see lots of HTML code that could be easily inferred from structure data. This could eventually allow us to enforce data type safety from the back-end (where the data comes from).
> 
> Additionally, duplicate/similar code could be de-duplicated, and form/UI behaviours could be "easily" unified. The following is just an example, but there are others that could quickly benefit from this:
> 
> ...
> 
> My point is: with a codebase of more than 100,000 lines of code (80% of which are front-end, and growing 20-50k from one release to another: 20,000 more than in Nautilus and 70,000 more than in Mimic), we should start looking for ways of reducing code redundancy as much as possible. I have to admit that every time you undertake an Angular, Bootstrap, Rxjs, or any other of cross-project tool upgrade, I really really feel sorry for the amount of code you need to change (and multiple times when rebases are needed). Fortunately, Angular is highly structured and modular and that softens the issue, but I'm not sure if this is gonna be sustainable in the mid/long-term.

I think about something like [formly](https://formly.dev/). But be careful, i implemented something similar on my own in my private OSS project using Angular Material and it is great, but you are way more limited in how to implement forms than right at the moment. I think it is not possible to use such a framework everywhere in our UI, but it will help to reduce a huge amount of code.

**Comment by epuertat** [comment]
Thanks for sharing your experience, @votdev ! Yup, I'm aware that this move would imply trading off some of our UI quirks in favor less code to maintain (yet duller).

Nevertheless, when doing the nav menu conversion from HTML to JSON (#33375) I realized that we have coded many ad-hoc 'decorations' that may add some value but complicate a lot reusing components (e.g.: 'Block' menu turns red when some issue happens at RBD level, while the same not happens at other components; the 'hearbeat' icon in the 'dashboard' menu; hiding some menu entries when some services are not available, but not doing the same for other services when it happens the same, ...).

Besides, if needed, those customizations can be implemented in reusable components (e.g.: in that same PR, I kept the badges used for RBD mirroring, so they can easily be attached to other menu entries).

**Pull request merged**
