### PR TITLE
build/ops: run "npm ci" with a one-hour timeout

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://tracker.ceph.com/issues/40645
Signed-off-by: Nathan Cutler <ncutler@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tspmelo** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
@tspmelo If the command hangs in an interactive session, the user can press CTRL-C. The purpose of the timeout is not to estimate how long the command should take, but rather to ensure that the command completes in non-interactive environments. So I think whether we set the timeout to 30m, 1h, 3h, or 6h is of no consequence - any value will do.

**Comment by smithfarm** [comment]
```
[ 49%] dashboard frontend dependencies are being installed
timeout: invalid option -- 'v'
Try 'timeout --help' for more information.
src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-deps.dir/build.make:60: recipe for target '../src/pybind/mgr/dashboard/frontend/node_modules' failed
```

Looks like the `timeout` in whatever-OS-that-is does not have the `-v` option. I'll drop it.

**Comment by smithfarm** [comment]
> It takes 30s to run the cmd in my machine.

Your Internet connection is really fast :-)

**Comment by smithfarm** [comment]
```
[  8%] dashboard frontend dependencies are being installed
timeout: failed to run command 'npm': No such file or directory
make[3]: *** [../src/pybind/mgr/dashboard/frontend/node_modules] Error 127
make[2]: *** [src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-deps.dir/all] Error 2
```

Odd

**Comment by tspmelo** [comment]
Haven't seen that erro for a long time.
It usually only happens when you have cache problems or old files cause a problem.
Since this is a clean system it should not be happening...

**Comment by smithfarm** [comment]
Same in "make check":

```
[ 42%] dashboard frontend dependencies are being installed
timeout: failed to run command 'npm': No such file or directory
src/pybind/mgr/dashboard/CMakeFiles/mgr-dashboard-frontend-deps.dir/build.make:60: recipe for target '../src/pybind/mgr/dashboard/frontend/node_modules' failed
make[3]: *** [../src/pybind/mgr/dashboard/frontend/node_modules] Error 127
```

The error "timeout: failed to run command 'npm': No such file or directory" indicates that "npm" is not found in the PATH in the environment where cmake runs the command.

**Comment by smithfarm** [comment]
"ceph dashboard tests" failure is unrelated

**Comment by ricardoasmarques** [comment]
jenkins test dashboard

**Pull request merged**
