### PR TITLE
hammer: boost uuid makes valgrind complain

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/16343

### CODE REVIEW

**Comment by smithfarm** [comment]
@liewegas This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

Do you think this PR is OK to merge?

**Comment by smithfarm** [comment]
@liewegas @athanatos This PR passed a /200 rados run on Ubuntu. None of the failures were reproducible. For details see http://tracker.ceph.com/issues/15895#note-18

Do you think it's OK to merge?

**Comment by athanatos** [comment]
@smithfarm Sorry, I think the first one is ok, but I don't know what the implications of the second are.

**Comment by smithfarm** [comment]
@liewegas This one has passed two rados runs. Sam is OK with the first commit, but unsure about the second. Do you think it's OK to merge?

**Comment by liewegas** [comment]
I don't think the new dependency will be an issue.. @ktdreyer ?  It's there in jewel...

**Comment by ktdreyer** [comment]
Sure, looks good to me, thanks

**Comment by smithfarm** [comment]
Reverted by #10913

**Pull request merged**
