### PR TITLE
mon: MonOpRequest destruct without call remove_session leading to assert failed.

### PR DESCRIPTION
**Pull request by cxwshawn**
Fixes: #13262

Signed-off-by: Xiaowei Chen <chen.xiaowei@h3c.com>

### CODE REVIEW

**Comment by liewegas** [comment]
How did this come up?

- I don't think a static Monitor * is the right approach here.. statics are generally evil.
- I think we should jsut remove_session when we get the messenger callback (ms_handle_reset).  This should be totally separate from the session lifecycle... i.e., it should be ok to get a reset, remove_session, and only later drop the last session ref.  Or, we could drop the last (op) ref, then remove_session and drop the last session ref.  Either way needs to be safe.

What assert did you hit?

**Comment by liewegas** [comment]
oh, 13262.  I think teh problem here is that we dropped all session refs but the sub_map wasn't empty.  That means that remove_session wasn't called and there is a ref counting bug, *or* it means that it was called, but then we added more subs *after* that... which means that handle_subscribe and friends should have a check to only register sub_map items if the session is still registered.

**Comment by jecluis** [comment]
I'm not fond of making the Monitor class a singleton, the most prominent reason being that it will make for lazy programmers that will just end up relying on Monitor::get_instance() for pretty much anything requiring the Monitor, regardless of scope.

Also, even if this is the root cause for the bug, I don't think the MonOpRequest should be responsible for calling remove_session() at all.

**Comment by liewegas** [comment]
I think this is the right fix: https://github.com/ceph/ceph/pull/6105

**Pull request closed without merging**
