### PR TITLE
msg/Messenger.cc: add std::move

### PR DESCRIPTION
**Pull request by stiopaa1**
Signed-off-by: Michal Jarzabek stiopa@gmail.com

### CODE REVIEW

**Comment by tchaikov** [comment]
@stiopaa1  needs rebase.

**Comment by liewegas** [comment]
please rebase!

**Comment by stiopaa1** [comment]
@liewegas 
rebased

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-01-04_05:03:43-rados-wip-kefu-testing---basic-mira/
- http://pulpito.ceph.com/kchai-2017-01-03_09:59:57-rados-wip-kefu-testing---basic-mira/

failed job tracked by http://tracker.ceph.com/issues/17417

**Pull request merged**
