### PR TITLE
rgw: user accounts implementation

### PR DESCRIPTION
**Pull request by theanalyst**
Draft PR, not ready for review yet

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by theanalyst** [comment]
unstale me

**Comment by mattbenjamin** [comment]
hi @theanalyst

**Comment by cbodley** [comment]
@alimaredia i'll start working through this rebase

**Comment by cbodley** [comment]
rebased in https://github.com/ceph/ceph/pull/46373

**Pull request closed without merging**
