### PR TITLE
kraken: rgw: Realm set does not create a new period

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18499

### CODE REVIEW

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/cephtool/test.sh:1801: test_mon_crushmap_validation:  expect_false ceph osd setcrushmap -i /tmp/cephtool.Bey/map
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/cephtool/test.sh:31: expect_false:  set -x
/home/jenkins-build/build/workspace/ceph-pull-requests/qa/workunits/cephtool/test.sh:32: expect_false:  ceph osd setcrushmap -i /tmp/cephtool.Bey/map
2017-04-13 18:39:04.390789 7f83311ef700 -1 WARNING: the following dangerous and experimental features are enabled: *
2017-04-13 18:39:04.398400 7f83311ef700 -1 WARNING: the following dangerous and experimental features are enabled: *
Error EINVAL: Failed crushmap test: /tmp/cephtool.Bey/crushtool: exit status: 1
```

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by tchaikov** [comment]
@smithfarm the crushtool timeout recurs occasionally. it's a known issue. but we haven't managed to root cause it yet.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@yehudasa @mattbenjamin @oritwas @cbodley This PR passed an rgw suite at http://tracker.ceph.com/issues/19009#note-60 and, provided there are no objections, I'll merge it as soon as it gets a positive review from one of you.

**Pull request merged**
