### PR TITLE
os: batch fixes to bluestore

### PR DESCRIPTION
**Pull request by xiexingguo**

### CODE REVIEW

**Comment by xiexingguo** [comment]
@liewegas I find some more small fixes/cleanups through code inspection which might be helpful. Hope you wouldn't mind :-)

**Comment by liewegas** [comment]
A few of the other patches are already cherry-picked into my wip-bluestore branch.  Let's rebase this as soon as that merges

**Comment by liewegas** [comment]
Thanks!

**Comment by liewegas** [comment]
can you rebase this on current master please?  thanks!

**Comment by xiexingguo** [comment]
@liewegas Sure. Rebased and also drop the change that you still have doubt in.

**Comment by liewegas** [comment]
@xiexingguo thanks, will run this though QA.  Do you mind seeing which of these also need to be fixed in os/kstore/KStore.cc as well?

**Comment by xiexingguo** [comment]
Of course not. I' ll do it tomorrow:-)

**Comment by liewegas** [comment]
error: os/bluestore/BlueStore.cc:1346:1: jump to label ‘free_bluefs’ [-fpermissive]
free_bluefs:
^
error: os/bluestore/BlueStore.cc:1254:12: from here [-fpermissive]
goto free_bluefs;
^
error: os/bluestore/BlueStore.cc:1326:16: crosses initialization of ‘std::stringstream err’
stringstream err;
^
error: os/bluestore/BlueStore.cc:1322:10: crosses initialization of ‘std::string options’
string options;
^
error: os/bluestore/BlueStore.cc:1346:1: jump to label ‘free_bluefs’ [-fpermissive]
free_bluefs:
^
error: os/bluestore/BlueStore.cc:1229:14: from here [-fpermissive]
goto free_bluefs;

and other errors

**Comment by liewegas** [comment]
http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-trusty-amd64-basic/log.cgi?log=41db6a502dff254c32f17507801e883cb496993d

**Comment by xiexingguo** [comment]
@liewegas My apology for the mindlessness. I have done compiling locally and three more commits are appended to this PR for killing warnings and saving performance a little bit. The updated commits are as below(as you may concern about):
https://github.com/xiexingguo/ceph/commit/a0112a2171a47cbb6d0f5b858f51728f785798e6(It is this one that causes noise from compiler)
https://github.com/xiexingguo/ceph/commit/d3395549e8273922b3f30856d3b4540ef8c27413(kill warnings)
https://github.com/xiexingguo/ceph/commit/c8aae0c10847072da45c8b065a4ca1734be0bb29(decrease list number from 5 to 1 if we try to check whether or not a coll is empty)
https://github.com/xiexingguo/ceph/commit/a987fc3a377f6cd8c25cfebdb18eec43815dfc50(same as above)

And you may need to remerge this PR and run the test again.  

BTW,  when shall the i-Bot be ready for work again? I do miss him:-)

**Pull request merged**
