### PR TITLE
qa: Pass omit_sudo flag through CephFSMount::run_shell

### PR DESCRIPTION
**Pull request by gregsfortytwo**
Fixes:  https://tracker.ceph.com/issues/44904

Signed-off-by: Greg Farnum <gfarnum@redhat.com>

### CODE REVIEW

**Comment by ukernel** [comment]
this is original run_shell
```
    def run_shell(self, args, wait=True, stdin=None, check_status=True,
                  omit_sudo=True):
        if isinstance(args, str):
            args = args.split()

        args = ["cd", self.mountpoint, run.Raw('&&'), "sudo"] + args
        return self.client_remote.run(args=args, stdout=StringIO(),
                                      stderr=StringIO(), wait=wait,
                                      stdin=stdin, check_status=check_status,
                                      omit_sudo=omit_sudo)

```

It always run command with sudo.  I think lots of tests rely on that, for example https://github.com/ceph/ceph/blob/master/qa/tasks/cephfs/test_cap_flush.py#L51

**Comment by gregsfortytwo** [comment]
This did not succeed at its goal.

**Comment by rishabh-d-dave** [comment]
@gregsfortytwo @ukernel 
> this is original run_shell
> 
> ```
>     def run_shell(self, args, wait=True, stdin=None, check_status=True,
>                   omit_sudo=True):
>         if isinstance(args, str):
>             args = args.split()
> 
>         args = ["cd", self.mountpoint, run.Raw('&&'), "sudo"] + args
>         return self.client_remote.run(args=args, stdout=StringIO(),
>                                       stderr=StringIO(), wait=wait,
>                                       stdin=stdin, check_status=check_status,
>                                       omit_sudo=omit_sudo)
> ```
> 
> It always run command with sudo. I think lots of tests rely on that, for example https://github.com/ceph/ceph/blob/master/qa/tasks/cephfs/test_cap_flush.py#L51
> 
> we should set omit_sudo to false by default or fix all callers of run_shell()

Oh, okay. I failed to see this while moving methods from vstart_runner.py to cephfs/mount.py: run_shell() would run all commands with `sudo` but vstart_runner.py would omit sudo in all commands. See https://github.com/ceph/ceph/commit/3e0a1361f78452d79c283f70b5dc2b865d62cb61#diff-0bfa62124ab75596476e1cfdf1a851a3L241; I still have no idea why was that the case originally. 

I think the fix is to merge the modification made here and write patches on top of that to -
* prepend all commands passed to run_shell() with sudo, as it used to be
* and then optionally,
    + get rid of the code that removes sudo from the command in vstart_runner.py
    + and then get rid of `omit_sudo` parameter too from vstart_runner.py and teuthology's codebase as well.

**Comment by gregsfortytwo** [comment]
That sounds fine, Rishabh, but we did a quick revert just to get things going safely again.

**Pull request closed without merging**
