### PR TITLE
cmake/modules/GetGitRevisionDescription: update to work with git-worktree

### PR DESCRIPTION
**Pull request by liewegas**
Found this here: https://phabricator.kde.org/D9172

### CODE REVIEW

**Comment by liewegas** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
Hallelujah it works!

**Comment by liewegas** [comment]
@gregsfortytwo want to approve the pr?

**Comment by gregsfortytwo** [comment]
I left it since I can't really read cmake but I guess that doesn't matter much.

**Pull request merged**
