### PR TITLE
[DNM] kraken: rbd: Enabling mirroring for a pool wiht clones may fail

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19227

### CODE REVIEW

**Comment by smithfarm** [comment]
Jenkins retest this please

```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rbd_mirror/test_ImageReplayer.cc:423: Failure
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageReplayer.cc: In function 'rbd::mirror::ImageReplayer<ImageCtxT>::~ImageReplayer() [with ImageCtxT = librbd::ImageCtx]' thread 7fbbf6c85ac0 time 2017-04-13 22:15:38.826132
/home/jenkins-build/build/workspace/ceph-pull-requests/src/tools/rbd_mirror/ImageReplayer.cc: 299: FAILED assert(m_event_preprocessor == nullptr)
```

**Comment by smithfarm** [comment]
@trociny @dillaman I cherry-picked a commit to accommodate the change in `src/test/rbd_mirror/test_ImageReplayer.cc` but it looks like that introduces a build failure.

Looking at it a second time, I think the change in `src/test/rbd_mirror/test_ImageReplayer.cc` can simply be dropped from the backport. Do you agree?

**Comment by trociny** [comment]
@smithfarm Your first commit is not right: it just adds tests that demonstrate the issue but does not add the fix itself. The fix will require some work due to the code divergence. If you agree please assign the ticket to me and I will work on the backport.

**Comment by smithfarm** [comment]
@trociny OK, 👍 to that

**Comment by smithfarm** [comment]
http://tracker.ceph.com/issues/19227 re-assigned to @trociny

**Pull request closed without merging**
