### PR TITLE
pacific: os/bluestore: Fix collision between BlueFS and BlueStore deferred writes

### PR DESCRIPTION
**Pull request by aclamk**
Fixes: https://tracker.ceph.com/issues/56669

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [x] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by aclamk** [comment]
jenkins test make check

**Comment by aclamk** [comment]
I think make check needs: https://github.com/ceph/ceph/pull/47295

**Review by ifed01 — APPROVED** [review]
LGTM, make check failures look irrelevant indeed.

**Comment by ljflores** [comment]
jenkins test api

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
Rados suite review:

https://pulpito.ceph.com/?branch=wip-yuri8-testing-2022-07-27-1303-pacific
https://pulpito.ceph.com/yuriw-2022-08-01_22:43:42-rados-wip-yuri8-testing-2022-08-01-1413-pacific-distro-default-smithi/

Failures, unrelated:
    1. https://tracker.ceph.com/issues/52321
    2. https://tracker.ceph.com/issues/56652
    3. https://tracker.ceph.com/issues/53501
    4. https://tracker.ceph.com/issues/53939
    5. https://tracker.ceph.com/issues/56573
    6. https://tracker.ceph.com/issues/54992
    7. https://tracker.ceph.com/issues/54071
    8. https://tracker.ceph.com/issues/37808

Details:
    1. qa/tasks/rook times out: 'check osd count' reached maximum tries (90) after waiting for 900 seconds - Ceph - Rook
    2. cephadm/test_repos.sh: rllib.error.HTTPError: HTTP Error 504: Gateway Timeout - Ceph - Orchestrator
    3. Exception when running 'rook' task. - Ceph - Orchestrator
    4. ceph-nfs-upgrade, pacific: Upgrade Paused due to UPGRADE_REDEPLOY_DAEMON: Upgrading daemon osd.0 on host smithi103 failed - Ceph - Orchestrator
    5. test_cephadm.sh: KeyError: 'TYPE' - Ceph - Orchestrator
    6. cannot stat '/etc/containers/registries.conf': No such file or directory - Ceph - Orchestrator
    7. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>)
    8. osd: osdmap cache weak_refs assert during shutdown - Ceph - RADOS

**Comment by ljflores** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@vumrao this is good to go once make check passes :D

**Comment by neha-ojha** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by yuriw** [comment]
jenkins test make check

**Comment by ljflores** [comment]
@cbodley do you know what's going on with the rgw failure in make check? Seems like it's happening across Pacific PRs.

**Comment by tchaikov** [comment]
@ljflores hi Laura, I think the FTBFS should be fixed by #47295

**Comment by yuriw** [comment]
jenkins test make check

**Pull request merged**
