### PR TITLE
seastar: fix mem leak caused by no maximum memory limit for cpu core

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Signed-off-by: Xuehan Xu <xxhdx1985126@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by cyx1231st — APPROVED** [review]
The fix https://github.com/ceph/seastar/commit/d7ac63fb204b6df26da5855da32ca1ec006db473 looks reasonable to me, looking forward to see it in the seastar upstream.

**Comment by xxhdx1985126** [comment]
> The fix [ceph/seastar@d7ac63f](https://github.com/ceph/seastar/commit/d7ac63fb204b6df26da5855da32ca1ec006db473) looks reasonable to me, looking forward to see it in the seastar upstream.

It's already in seastar's upstream code.

**Comment by xxhdx1985126** [comment]
jenkins test make check

**Comment by xxhdx1985126** [comment]
jenkins test api

**Comment by xxhdx1985126** [comment]
jenkins test submodules

**Comment by tchaikov** [comment]
quote from https://jenkins.ceph.com/job/ceph-pr-submodules/77732/consoleFull#212386344640526d21-3511-427d-909c-dd086c0d1034

```
+ return 1
+ echo 'please include '\''seastar submodule'\'' in your commit message, if this change is intentional.'
please include 'seastar submodule' in your commit message, if this change is intentional.
+ exit 1
```
see also https://github.com/ceph/ceph-build/blob/03496de9e4cd32fa2ad6122151bf3a475ff1b4f2/ceph-pr-submodules/build/build#L54

just wanted to double check with you, which branch did you push to ceph/seastar?

**Comment by xxhdx1985126** [comment]
> quote from https://jenkins.ceph.com/job/ceph-pr-submodules/77732/consoleFull#212386344640526d21-3511-427d-909c-dd086c0d1034
> 
> ```
> + return 1
> + echo 'please include '\''seastar submodule'\'' in your commit message, if this change is intentional.'
> please include 'seastar submodule' in your commit message, if this change is intentional.
> + exit 1
> ```
> 
> see also https://github.com/ceph/ceph-build/blob/03496de9e4cd32fa2ad6122151bf3a475ff1b4f2/ceph-pr-submodules/build/build#L54

Ah, yes, will add it:-)

> 
> just wanted to double check with you, which branch did you push to ceph/seastar?

Here it is: https://github.com/ceph/seastar/commits/seastar_mem_leak_fix

**Comment by tchaikov** [comment]
@xxhdx1985126 i see you are cherry-pick the fix on top of `ceph-reef-22.11.0-31-502f1422`. the purpose of having a dedicated branch is 

1. to keep the code being referenced alive, 
2. and to track the changes

probably you could push to that branch instead if you don't plan to bump up the seastar branch to be in sync with upstream's master HEAD.

**Review by athanatos — APPROVED** [review]
LGTM, though I suspect we probably just want to bump up to seastar HEAD until the reef release.

**Comment by xxhdx1985126** [comment]
> LGTM, though I suspect we probably just want to bump up to seastar HEAD until the reef release.

I tried to bump up to seastar HEAD, but run into some seastar build issue, so I turn to cherry-pick the fixes. I'll tried to fix the seastar build issue in the coming days.:-)

**Comment by xxhdx1985126** [comment]
> @xxhdx1985126 i see you are cherry-pick the fix on top of `ceph-reef-22.11.0-31-502f1422`. the purpose of having a dedicated branch is
> 
> 1. to keep the code being referenced alive,
> 2. and to track the changes
> 
> probably you could push to that branch instead if you don't plan to bump up the seastar branch to be in sync with upstream's master HEAD.

I'll try to bump up to seastar HEAD first, and resort to this way if unsuccessful:-)

**Review by rzarzynski — APPROVED** [review]

**Comment by xxhdx1985126** [comment]
@athanatos @cyx1231st  @rzarzynski @tchaikov Hi, everyone. I think this pr is good to go, please take a final look, thanks:-)

**Comment by tchaikov** [comment]
@xxhdx1985126 please allow me ask the same question, "just wanted to double check with you, which branch did you push to ceph/seastar?"

**Comment by xxhdx1985126** [comment]
> @xxhdx1985126 please allow me ask the same question, "just wanted to double check with you, which branch did you push to ceph/seastar?"

Ah, sorry, still: https://github.com/ceph/seastar/commits/seastar_mem_leak_fix

**Comment by xxhdx1985126** [comment]
jenkins retest this please

**Comment by cyx1231st** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
I'll merge if no further concerns.

**Pull request merged**
