### PR TITLE
nautilus: mgr/telemetry: backport a ton of stuff

### PR DESCRIPTION
**Pull request by liewegas**
- channels
- license when enabling
- revisions and re-opt-in
- config options
- obscure entity_name etc
- device telemetry (smart!)
- balancer and pg_autoscaler status #30871 
- small fix #30854 
- device telemetry to separate endpoint #31225 
- big pile of new telemetry stuff #31226 

It's now almost completely in sync with master.  The only delta is the timestamp parsing, which is different because master/octopus is all-in on ISO format.

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuriw Could you include this in your next nautilus integration run?

**Comment by yuriw** [comment]
@liewegas pls rebase:
--- pr 30849 --- pulling https://github.com/liewegas/ceph.git branch wip-device-telemetry-nautilus
remote: Enumerating objects: 220, done.
remote: Counting objects: 100% (220/220), done.
remote: Total 304 (delta 220), reused 220 (delta 220), pack-reused 84
Receiving objects: 100% (304/304), 37.79 KiB | 7.56 MiB/s, done.
Resolving deltas: 100% (220/220), completed with 30 local objects.
From https://github.com/liewegas/ceph
 * branch                  wip-device-telemetry-nautilus -> FETCH_HEAD
Auto-merging doc/rados/operations/health-checks.rst
Auto-merging doc/mgr/telemetry.rst
Auto-merging PendingReleaseNotes
CONFLICT (content): Merge conflict in PendingReleaseNotes
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in <module>
    assert not r
AssertionError

**Comment by smithfarm** [comment]
This was included in a run containing https://github.com/ceph/ceph/pull/30195 which also changes PendingReleaseNotes, and #30195 was opened before this one.

**Comment by liewegas** [comment]
rebased

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-11-08-1221-nautilus](https://trello.com/c/GKBiDkwL/752-wip-yuri3-testing-2019-11-08-1221-nautilus)

**Comment by yuriw** [comment]
@liewegas needs rebase

--- pr 30849 --- pulling https://github.com/liewegas/ceph.git branch wip-device-telemetry-nautilus
remote: Enumerating objects: 220, done.
remote: Counting objects: 100% (220/220), done.
remote: Total 304 (delta 220), reused 220 (delta 220), pack-reused 84
Receiving objects: 100% (304/304), 44.35 KiB | 11.09 MiB/s, done.
Resolving deltas: 100% (220/220), completed with 30 local objects.
From https://github.com/liewegas/ceph
 * branch                  wip-device-telemetry-nautilus -> FETCH_HEAD
Auto-merging src/pybind/mgr/balancer/module.py
Auto-merging PendingReleaseNotes
CONFLICT (content): Merge conflict in PendingReleaseNotes
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/home/yuriw/wip_master/src/script/build-integration-branch", line 67, in <module>
    assert not r
AssertionError

**Pull request merged**
