### PR TITLE
common/options: Set pacific+ rocksdb column family options.

### PR DESCRIPTION
**Pull request by markhpc**
This PR changes the default bluestore rocksdb column families for pacific to also include separate pgmeta and allocation CFs so that we can more easily tweak per-column family settings.  A variety of tests were performed with different memtable sizes.  First size is the global value, with any specific column family memtable sizes after.  These tests show performance/compaction stats for librbd 4KB random write performance on a single P4510 NVMe on o01 (centos stream, kernel 5.9.1).

Generally we see the same behavior as in previous tests.  Larger memtable sizes results in much lower write-amplification, but also result in higher CPU usage overhead (Which in this case results in lower performance but may not always depending on whether or not we are disk or CPU limited).  Changing specific column family memtable sizes does not yet result in a best-of-both-worlds (low CPU usage, low write-amp) result like we were hoping.  Thus, this PR does not attempt to change the default memtable size pending additional R&D by @benhanokh.

For reference the column families are mapped in master right now to these characters:

```
const string PREFIX_SUPER = "S";       // field -> value
const string PREFIX_STAT = "T";        // field -> value(int64 array)
const string PREFIX_COLL = "C";        // collection name -> cnode_t
const string PREFIX_OBJ = "O";         // object name -> onode_t
const string PREFIX_OMAP = "M";        // u64 + keyname -> value
const string PREFIX_PGMETA_OMAP = "P"; // u64 + keyname -> value(for meta coll)
const string PREFIX_PERPOOL_OMAP = "m"; // s64 + u64 + keyname -> value
const string PREFIX_PERPG_OMAP = "p";   // u64(pool) + u32(hash) + u64(id) + keyname -> value
const string PREFIX_DEFERRED = "L";    // id -> deferred_transaction_t
const string PREFIX_ALLOC = "B";       // u64 offset -> u64 length (freelist)
const string PREFIX_ALLOC_BITMAP = "b";// (see BitmapFreelistManager)
const string PREFIX_SHARED_BLOB = "X"; // u64 offset -> shared_blob_t
const string PREFIX_ZONED_FM_META = "Z";  // (see ZonedFreelistManager)
const string PREFIX_ZONED_FM_INFO = "z";  // (see ZonedFreelistManager)
const string PREFIX_ZONED_CL_INFO = "G";  // (per-zone cleaner metadata
```

512GB prefill + 5 minute test
Stat | Master (256M) | wip (256M) | wip (64M) | wip (16M) | wip (16M, P=256M) | wip (16M, O=256M) | wip (16M, b=256M)
-- | -- | -- | -- | -- | -- | -- | --
fio IOPs | 70567 | 70310 | 79477 | **83659** | 76929 | 77386 | 78569
fio Data Written (GB) | 86.8 | 86.4 | 97.7 | 102.8 | 94.5 | 95.0 | 96.6
Total OSD Log Duration (s) | 561.9 | 541.0 | 550.4 | 565.9 | 547.3 | 550.8 | 572.4
Number of Compaction Events | 82 | 100 | 227 | 714 | 523 | 379 | 687
Avg Compaction Time (s) | 0.83 | 0.63 | 0.56 | 0.45 | 0.50 | **0.37** | 0.44
Total Compaction Time (s) | 68.0 | **62.6** | 127.2 | 320.3 | 263.7 | 140.4 | 305.0
Avg Output Size: (MB) | 170.3 | 141.4 | 154.9 | 162.6 | 190.2 | 90.2 | 168.6
Total Output Size: (MB) | **13966.0** | **14137.2** | 35171.0 | 116105.4 | 99456.3 | 34192.2 | 115820.6
Total Input Records | 164901992 | **149334868** | 241820924 | 481170200 | 374639379 | 301355572 | 436425178
Total Output Records | 58376761 | **45085484** | 95567871 | 312373450 | 238077371 | 164414360 | 282619484
Avg Output Throughput (MB/s) | 240.2 | 221.8 | 267.8 | 343.1 | 365.0 | 243.9 | 358.8
Avg Input Records/s | 1898399 | 2405394 | 1972649 | 1591836 | 1344631 | 2137686 | 1536212
Avg Output Records/s | 757860 | 694818 | 733028 | 969363 | 851176 | 1154035 | 938992
Avg Output/Input Ratio | 0.475 | 0.407 | 0.474 | 0.666 | 0.721 | 0.515 | 0.675
_**DB Overhead (excl. WAL)**_ | _**15.71%**_ | _**15.98%**_ | _35.16%_ | _110.30%_ | _102.78%_ | _35.15%_ | _117.09%_

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by markhpc** [comment]
@benhanokh I didn't want to run full 2 hour tests but I did run some 1 hour tests just to see how much it impacted write-amp.  The result hints at similar results to what you reported in standup.  We do see that the gap closes somewhat with longer running tests, though there is still a large difference between using 256MB write buffers and 64MB and especially 16MB ones.  At least on this platform, there's probably a legitimate argument to drop from 4 256MB buffers to 8 128MB buffers.  The write-amp increase is fairly small (~5%) for a ~6% performance gain.  Once we jump to 64MB the tradeoff becomes less clear imho.  a 21-22% increase in write-amp for a 12% increase in performance.  16MB as a default is unreasonable imho (nearly double the write amp for less than a 15% gain).

Here are the 1 hour test results (roughly 1-1.2TB of 4K random writes):

Stat | Master (256M) | wip (256M) | wip (128M) | wip (64M) | wip (16M)
-- | -- | -- | -- | -- | --
IOPs (fio) | 70197 | 70735 | 74834 | 78707 | **80483**
GB Data Written (fio) | 1036 | 1044 | 1104 | 1160 | 1186
Total OSD Log Duration (s) | 3873 | 3845 | 3869 | 3850 | 3842
Compaction Events | **2044** | 2311 | 2718 | 4130 | 9239
Avg Compaction Time (s) | 0.59 | 0.50 | 0.53 | 0.47 | **0.45**
Total Compaction Time (s) | 1209.1 | **1149.0** | 1429.9 | 1948.4 | 4112.8
Avg Output Size: (MB) | 178.5 | 160.9 | 165.0 | 161.0 | 172.5
Total Output Size: (MB) | **364886** | **371736** | 448568 | 664725 | 1593968
Total Input Records | **2227941104** | **2047110076** | 2386361703 | 3091317757 | 5220472509
Total Output Records | 880195290 | **733265158** | 846267542 | 1273970519 | 3228892470
Avg Output Throughput (MB/s) | 361.5 | 343.9 | 343.1 | 350.9 | 380.0
Avg Input Records/s | 1302241 | 1629380 | 1486286 | 1549763 | 1334166
Avg Output Records/s | 617396 | 601172 | 565483 | 631304 | 782409
Avg Output/Input Ratio | 0.568 | 0.527 | 0.529 | 0.535 | 0.672

Stat | Master (256M) | wip (256M) | wip (128M) | wip (64M) | wip (16M)
-- | -- | -- | -- | -- | --
DB Overhead (excl. WAL) | 34.40% | 34.77% | 39.68% | 55.96% | 131.25%
fio Perf Increase | 0.00% | 0.77% | 6.61% | 12.12% | 14.65%
DB Extra Overhead | 0.00% | 0.38% | 5.28% | 21.57% | 96.85%
_**Perf to Overhead Ratio**_ |   | _**203%**_ | _**125%**_ | _56%_ | _15%_

**Comment by jdurgin** [comment]
discussing with @aclamk this morning, it seems that adapting the resharding tool to handle the b column family safely will take significant effort, for a modest performance gain (<10% for small random write, less for mixed workloads).

If @benhanokh's work on dropping it entirely works out, it will have a much more dramatic effect on performance, and the resharding tool will not need to handle the b column family any more. We can still drop the allocation metadata by prefix while it's in the default column family, and that's a one-time operation so it doesn't have to be super fast.

Thus I'd suggest keeping allocation in the default column family for pacific. We could make the call once we have more data on the speed and thus feasibility of persisting/restoring the allocation metadata.

**Comment by markhpc** [comment]
> discussing with @aclamk this morning, it seems that adapting the resharding tool to handle the b column family safely will take significant effort, for a modest performance gain (<10% for small random write, less for mixed workloads).
> 
> If @benhanokh's work on dropping it entirely works out, it will have a much more dramatic effect on performance, and the resharding tool will not need to handle the b column family any more. We can still drop the allocation metadata by prefix while it's in the default column family, and that's a one-time operation so it doesn't have to be super fast.
> 
> Thus I'd suggest keeping allocation in the default column family for pacific. We could make the call once we have more data on the speed and thus feasibility of persisting/restoring the allocation metadata.

**Comment by markhpc** [comment]
@jdurgin Sounds good, updated to only include the P column family and we can punt on b and pull things out using the prefix once @benhanokh's changes to pull allocation data out are done.

**Review by neha-ojha — APPROVED** [review]

**Comment by neha-ojha** [comment]
being tested with https://github.com/ceph/ceph/pull/37391

**Comment by neha-ojha** [comment]
jenkins retest this please

**Comment by neha-ojha** [comment]
this has been merged as a part of https://github.com/ceph/ceph/pull/37391 by means of https://github.com/ceph/ceph/pull/37391/commits/f44d4566217b091ecfb0c3bd7bca3e096d6cf03d

**Pull request closed without merging**
