### PR TITLE
ThreadPool add/remove work queue methods not thread safe

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13043

### CODE REVIEW

**Comment by dachary** [comment]
@jdurgin does this backport look good to merge ? It passed a run of the firefly rados suite ( see http://tracker.ceph.com/issues/11644#note-110 ). Note that there was a valgrind issues but it is unrelated and fixed by https://github.com/ceph/ceph/pull/6325.

**Comment by jdurgin** [comment]
:+1:

**Comment by funny-falcon** [comment]
Did it affected librados?

**Comment by funny-falcon** [comment]
I repeat my question:
- were it safe to use single rados_ioctx_t from multiple threads before this fix ?

**Comment by smithfarm** [comment]
@funny-falcon I suggest you ask this question on the ceph-devel mailing list [1]. Here in this backport PR you're probably not reaching the right people.

[1] http://ceph.com/resources/mailing-list-irc/

**Pull request merged**
