### PR TITLE
cephadm: change shared_folder directory for prometheus and grafana

### PR DESCRIPTION
**Pull request by nizamial09**
After https://github.com/ceph/ceph/pull/44059 the `monitoring/prometheus`
and `monitoring/grafana/dashboards` directories are changed to
`monitoring/ceph-mixins`. That broke the shared_folders in the cephadm
bootstrap script. See the [failures in the cephadm-dashboard-e2e runs](https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/2521/consoleFull#-85362248744e9240e-b50a-4693-bac0-8a991bac86ac)

Changed all the instances of `monitoring/prometheus` and
`monitoring/grafana/dashboards` to `monitoring/ceph-mixins`

Also, renaming all the instances of `prometheus_alerts.yaml` to
`prometheus_alerts.yml`.

Fixes: https://tracker.ceph.com/issues/54176
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by avanthakkar — APPROVED** [review]
LGTM!

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Review by pereman2 — APPROVED** [review]

**Review by MrFreezeex — APPROVED** [review]

**Review by epuertat — APPROVED** [review]
Everything makes sense to me! Thanks @nizamial09

**Comment by pereman2** [comment]
jenkins test make check

**Pull request merged**
