### PR TITLE
ceph.spec.in: Include and own /usr/lib64/qemu contents in librbd1

### PR DESCRIPTION
**Pull request by scop**
Instead of creating in %post. See also https://bugzilla.redhat.com/show_bug.cgi?id=1483796

### CODE REVIEW

**Comment by b-ranto** [comment]
@smithfarm @ktdreyer I am not completely sure which should own /usr/lib64/qemu, any ideas.comments?

**Comment by smithfarm** [comment]
@scop Could you provide some reasoning why this is needed? I looked for this in both the commit message nor the downstream bug, but came up empty-handed.

@b-ranto AFAIK it's OK for a directory to be owned by multiple packages. Still, I'd like to know what the problem is that this is trying to solve.

**Comment by b-ranto** [comment]
@smithfarm I suppose the reason is that we keep stray files after removal, owning the symlink should fix that.

**Comment by smithfarm** [comment]
@b-ranto Right, but I'd like to see that explicitly stated in the commit message.

**Comment by scop** [comment]
rpm packages should own all the dirs they install files into. And there doesn't seem to be any reason to create the file in `%post` in the first place.

Like currently implemented (before this patch), the affected files fail to produce meaningful output when `rpm -qf` is invoked on them, and they will be left behind when the librbd1 package is removed.

I don't see any reason for any other package besides librbd1 to own these files or dirs.

**Comment by smithfarm** [comment]
@scop Perfect - please put what you just wrote into the commit message.

**Comment by scop** [comment]
Done.

**Comment by ktdreyer** [comment]
@adereis does this look ok to you?

**Comment by adereis** [comment]
Just added this comment to the BZ:

This symlink should not be necessary anymore. QEMU is properly linked to ceph/librbd these days (look at the qemu-block-rbd sub-package in Fedora and the respective package in RHEL).

The symlink was a hack from a time when librbd was distributed and supported by ceph and the rbd driver would be enabled at runtime only when/if the symlink was present.

So the right fix is to actually get rid of the symlink altogether and never touch (much less own) /usr/lib64/qemu.

**Comment by ktdreyer** [comment]
Thanks @adereis. I think you're right that we should delete this symlink bit altogether.

**Comment by smithfarm** [comment]
@aderis 's suggestion implemented at https://github.com/ceph/ceph/pull/17324

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-09-08_07:40:35-rados-wip-kefu-testing-2017-09-08-1043-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-09-08_18:05:34-rados-wip-kefu-testing-2017-09-08-1043-distro-basic-mira/

@dillaman is this change good to merge considering that #17324 has been merged?

**Comment by smithfarm** [comment]
@tchaikov @dillaman #17324 solves the same problem in a different way, so afaict this one is not needed anymore.

**Comment by tchaikov** [comment]
@scop i am closing per @smithfarm 's comment above. please reopen it if you think otherwise. thanks!

**Pull request closed without merging**
