### PR TITLE
tools: ceph-release-notes: prefixes and pep8 compliance

### PR DESCRIPTION
**Pull request by smithfarm**
A variety of cleanups

### CODE REVIEW

**Comment by dachary** [comment]
jenkins test this please

**Comment by theanalyst** [comment]
Looks good, one more improvement, (which need not be in this pr, for later) is to maybe output both the plaintext & rst version to different outfiles, avoids running the same script twice & copy stdout  to create these

**Comment by smithfarm** [comment]
Thanks; I'll run a quick test before merging.

**Comment by smithfarm** [comment]
@theanalyst I'll look at splitting the plaintext and rst output to different files. Thanks!

**Comment by tchaikov** [comment]
@smithfarm is this script tested by our qa suite? i am guessing that we can remove the needs-qa label?

**Comment by theanalyst** [comment]
@smithfarm tested by hand, works for me. We can add the plaintext rst as a different PR IMO.

**Pull request merged**
