### PR TITLE
pybind/mgr: drop unnecessary iterkeys usage to make py-3 compatible

### PR DESCRIPTION
**Pull request by trociny**
Fixes: http://tracker.ceph.com/issues/37581
Signed-off-by: Mykola Golub <mgolub@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Actually: `iterkeys()` is not really required in these cases:
Python 2:
```
➜  ~ ipython
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
In [2]: d = {'key' + str(x):x for x in range(10)}

In [3]: for k in d:
   ...:     print k
   ...:     
key9
key8
key3
key2
key1
key0
key7
key6
key5
key4
```
Python 3:
```➜  ~ ipython3
Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
In [1]: d = {'key' + str(x):x for x in range(10)}

In [2]: for k in d:
   ...:     print(k)
   ...:     
key0
key1
key2
key3
key4
key5
key6
key7
key8
key9
```

My guess would be that the cleanest solution would be just to remove `.iterkeys()`

**Comment by tchaikov** [comment]
thanks @sebastian-philipp , we can leverage the [dict iterator](https://www.python.org/dev/peps/pep-0234/) using the `for ... in`. and it's more concise, and fast.

**Comment by tchaikov** [comment]
@trociny mind updating accordingly?

**Comment by trociny** [comment]
updated

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-12-11_05:52:36-rados-wip-kefu2-testing-2018-12-11-0943-distro-basic-smithi/

**Pull request merged**
