### PR TITLE
nautilus: qa/tests: trying p2p downgrade

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2019-06-05_22:34:16-upgrade:nautilus-p2p:nautilus-p2p-parallel-downgrade-nautilus-distro-basic-smithi/

**Comment by smithfarm** [comment]
@yuriw Are you still intending to work on this?

**Comment by smithfarm** [comment]
@yuriw Ping. I'm closing this now, but feel free to reopen if it's still relevant.

**Comment by yuriw** [comment]
@smithfarm at some point yes :)

**Pull request closed without merging**
