### PR TITLE
osd: combine conditional statements

### PR DESCRIPTION
**Pull request by Yan-waller**
Signed-off-by: Yan Jun <yan.jun8@zte.com.cn>

### CODE REVIEW

**Comment by joscollin** [comment]
@Yan-waller Have you done your work in the latest code ? Is that the reason the Jenkins build failed ? When I checked your changes with the ceph:master manually, I found differences in line numbers. The github diff in this PR doesn't show that for some reason. 

Please check and let me know.

**Comment by Yan-waller** [comment]
@joscollin  thanks for remind me, I did this commit on this morning's code, but the build failed has been seen many times, and it has nothing to do with my changes. I will retest it.

**Comment by Yan-waller** [comment]
retest it please.

**Comment by Yan-waller** [comment]
retest this please

**Comment by gregsfortytwo** [comment]
Doubt this is your fault but if you could put your patch on top of a known-good offset we can make sure. (It's unlikely given the changes you're making, but there are some tests which match against debug output.)

**Comment by joscollin** [comment]
Anyway, I'm going to retest this again and see.

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by xiexingguo** [comment]
This looks like a fine cleanup

**Pull request merged**
