### PR TITLE
jewel: librbd: reacquire lock should update lock owner client id

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/19957

### CODE REVIEW

**Comment by smithfarm** [comment]
@dillaman This passed an rbd suite at http://tracker.ceph.com/issues/20613#note-59 with one failure that passed on rerun.

OK to merge?

**Comment by dillaman** [comment]
@smithfarm lgtm -- I need to investigate that failure since it appears like an OSD crashed and then data became corrupt (unrelated to this PR).

**Comment by ralt** [comment]
Hi,

Should this commit be ported to the kernel client driver too?

**Comment by dillaman** [comment]
@ralt This commit is librbd so it's unrelated to krbd. However, you are correct that krbd should probably re-acquire the lock if the watch is lost.

**Comment by ralt** [comment]
@dillaman sorry, I was indeed asking if the bugfix was relevant to krbd, and if it should be ported.

If that is the case, do you know how I should move forward with this?

**Comment by dillaman** [comment]
I would double-check to see if it's an issue first. I know there are some deltas in how krbd vs librbd handle object watches, so it might just work. If you can mount a krbd image w/ exclusive lock enabled, disable networking / block comms to the OSDs from the krbd host for about a minute, restore, and see if running an "rbd snap create <snap-spec> --debug-rbd=20" shows that it attempted to blacklist a dead client.

**Comment by ralt** [comment]
@dillaman thanks, will do!

**Comment by idryomov** [comment]
From a quick look at the code, the kernel client needs to be fixed too.  I'll put it on my TODO list.

@dillaman I'm rusty on the details -- if the remote peer has the lock and simply acks the "request lock" notify w/o actually queuing the release, wouldn't the requesting side just loop indefinitely?  The lock ower is alive after all...

**Comment by dillaman** [comment]
@idryomov Correct -- the remote peer will keep requesting it until it can acquire the lock. Only if the remote peer notices that the lock owner is not watching the image will it blacklist the client and break the lock.

**Comment by idryomov** [comment]
@dillaman ... and this bug is about lock owners that are watching, right?  I'm picking on your "attempted to blacklist a dead client" above -- I haven't tried it yet, but I would expect "rbd snap create" to loop indefinitely here.  Just want to make I'd be fixing the right bug ;)

**Comment by ralt** [comment]
@idryomov I confirm that the requesting side is indefinitely looping on the lockget command :)

**Comment by ralt** [comment]
@dillaman @idryomov if confirmation is needed, I can confirm that [this](https://github.com/ceph/ceph/pull/17385#issuecomment-351105806) testing scenario reproduced the bug correctly.

**Comment by ralt** [comment]
@idryomov this patch in the kernel fixes the issue, but I'm unsure if there is any unintended consequence:

```
modified   drivers/block/rbd.c
@@ -3884,6 +3884,7 @@ static void rbd_reacquire_lock(struct rbd_device *rbd_dev)
 					   &rbd_dev->lock_dwork, 0);
 	} else {
 		strcpy(rbd_dev->lock_cookie, cookie);
+		queue_work(rbd_dev->task_wq, &rbd_dev->acquired_lock_work);
 	}
 }
```

**Comment by idryomov** [comment]
@ralt That's probably right, mind sending a proper patch to ceph-devel (plain text + sign-off)?  I'll take a deeper look when I get a moment.

**Comment by ralt** [comment]
Sure, will do.

**Comment by ralt** [comment]
@idryomov on top of which branch should I make the patch?

**Comment by idryomov** [comment]
ceph-client/master, or just 4.14 tag -- it doesn't really matter in this case.

**Comment by ralt** [comment]
Done: https://marc.info/?l=ceph-devel&m=151317986316031&w=2

**Comment by ralt** [comment]
@idryomov hi, when can I expect some progress on the patch? A rough idea would be nice :)

Cheers

**Comment by idryomov** [comment]
@ralt It'll be merged into 4.15-rc and backported to appropriate kernels, I just didn't get a chance to try it out with different ceph versions yet.

**Comment by ralt** [comment]
@idryomov alright, thanks!

**Pull request merged**
