### PR TITLE
quincy: mon: avoid exception when setting require-osd-release more than 2

### PR DESCRIPTION
**Pull request by RaminNietzsche**
versions up.

Request for additional confirmation instead.

Fixes: https://tracker.ceph.com/issues/59456

Signed-off-by: RaminNietzsche <Ramin.Najarbashi@gmail.com>

(cherry picked from commit https://github.com/ceph/ceph/commit/9021e57d83d7d35c95a43e13320b13d530453f03)
## Checklist

- Tracker
  - [x] References tracker ticket https://tracker.ceph.com/issues/58156
- Component impact
  - [ ] Affects Dashboard, opened tracker ticket
  - [ ] Affects Orchestrator, opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests
  - [ ] Includes unit test(s)
  - [ ] Includes integration test(s)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ifed01 — APPROVED** [review]

**Comment by ifed01** [comment]
jenkins test make check

**Comment by RaminNietzsche** [comment]
jenkins test api

**Comment by k0ste** [comment]
https://tracker.ceph.com/issues/59456 - backport tracker

**Comment by k0ste** [comment]
Also, seems commit was not cherry-picked correctly

**Review by ifed01 — DISMISSED** [review]

**Comment by ifed01** [comment]
> Also, seems commit was not cherry-picked correctly

yep!

**Comment by ifed01** [comment]
@RaminNietzsche - please use "cherry-pick -x " command for backporting

**Comment by k0ste** [comment]
@RaminNietzsche please make a `cherry-pick -x` for backport. Thanks!

**Pull request merged**
