### PR TITLE
Wip 9981 (proxy write support)

### PR DESCRIPTION
**Pull request by wonzhq**
This is a rebase of the proxy write code on top of the master. The original PR is #3147.

### CODE REVIEW

**Comment by athanatos** [comment]
This needs to be accompanied by enabling this for some teuthology tests.  See ceph-qa-suite.  You'll need to create a pull request against ceph-qa-suite and add the link to that PR in this PR.  I'll then run the test for this with the ceph-qa-suite PR branch included.  You can re-add needs-qa once that PR exists.

**Comment by liewegas** [comment]
I think the existing cache and osdthrashing tests will suffice since this is modifying the existing 'writeback'   mode.

**Comment by liewegas** [comment]
some suggested additions here, but i think the only true blocker for testing this is that we need to block proxied writes once promotion is initiated.

**Comment by wonzhq** [comment]
> some suggested additions here, but i think the only true blocker for testing this is that we need to block proxied writes once promotion is initiated.

@liewegas I think this is already done in this PR following our discussion before. And I've made some updates according to your other comments. As for the change of traversing the in_progress_proxy_ops list, I'll do it in another patch after this one.

**Comment by liewegas** [comment]
You're right, I see it now.  I pushed a branch to build and test against!

**Comment by liewegas** [comment]
this is running up against ops not being idemptotent... see http://tracker.ceph.com/issues/8935

**Comment by wonzhq** [comment]
How is this going? Should I rebase it to the current master? @liewegas

**Comment by liewegas** [comment]
Yeah, please rebase!  Trying to finish off some of the simpler 
stuff before retesting this.

**Comment by wonzhq** [comment]
Rebased on top of latest master.

Also, adding 3 more commits:
1) search the op from the in-progress list in finish_proxy_write, instead of using the front one
2) add the proxy write feature bit support
3) add proxy write perf counter

**Comment by liewegas** [comment]
@wonzhq this is a perfect patch to use to learn how to run things through the test suite. email or #sepia for help.  (also looks like it'll need to get rebased again!)

**Comment by wonzhq** [comment]
@liewegas OK, I'll rebase it and get it running through the test suite once we can access sepia.

**Comment by wonzhq** [comment]
Ran 'make check' locally 3 times, and all of them are successful. So I think the failure reported by the bot is not caused by this PR.

**Comment by dachary** [comment]
@wonzhq I think you are correct and that is a false negative. Re-opened http://tracker.ceph.com/issues/11359#note-8 for further investigation. Sorry for the noise.

**Comment by wonzhq** [comment]
Again the failure reported by the bot is a false negative. The same as in https://github.com/ceph/ceph/pull/3354#issuecomment-103401006

**Comment by wonzhq** [comment]
@liewegas after shooting some bugs, this PR has passed the teuthology test. Is it ok to merge it? You may wanna take a look at the fixes I made for the bugs first.

**Comment by liewegas** [comment]
I'll take a final look.. @athanatos should too.  Can you rebase?

**Comment by wonzhq** [comment]
Rebased already. @liewegas

**Comment by athanatos** [comment]
This no longer merges cleanly.

**Comment by wonzhq** [comment]
Rebased again. Sorry didn't notice the merge conflict at the bottom.

**Comment by wonzhq** [comment]
Conflict again... Rebased.

**Comment by wonzhq** [comment]
Hi @liewegas and @athanatos , just want to check the status on this. Do we have any progress?

**Comment by athanatos** [comment]
There's a bit of a problem.  This implementation depends on using RWORDERED to keep the promote ordered w.r.t. any outstanding writes.  I'd like to not do that.  First, it doesn't completely work due to the fact that RWORDERED reads do not at this time go into the pg log, and this might be reordered w.r.t. writes after a peering event.  Second, rollback can be reordered w.r.t. other writes since the rollback target might be degraded even if the head isn't.  I'd prefer that we actually delay the promote operation until the outstanding writes are completed and not use RWORDERED.

**Comment by athanatos** [comment]
Failing test case due to the above:

ubuntu@teuthology:/a/samuelj-2015-07-21_08:08:12-rados-wip-sam-testing-distro-basic-
multi/982411/remote

**Comment by athanatos** [comment]
I don't want to use blocked_by for rollback.  I've got a branch which will be removing that machinery altogether.  I'd rather it simply be an exception to the ordering.  Because of that, either we cannot rely on RWORDERED to order the copyget after in progress writes, or we must not proxy rollback.

**Comment by athanatos** [comment]
There's also a missing case in _rollback_to which would need to be covered, but blocked_by assumes degraded.

ubuntu@teuthology:/a/samuelj-2015-07-21_08:08:12-rados-wip-sam-testing-distro-basic-multi/982411/remote

**Comment by athanatos** [comment]
Argh, a missing object won't have an objectcontext yet.  I'll need to think a bit more.

**Comment by athanatos** [comment]
Testing https://github.com/athanatos/ceph/tree/wip-sam-proxy-write based on this branch.  Introduces a new map rather than use blocked_by.

**Comment by wonzhq** [comment]
@athanatos thanks for taking a look at this!

> athanatos commented on f566206 3 hours ago
> I don't understand why this is necessary?

The reason I added this commit is because I saw a bug on this during the teuthology run. It's something like this: a write op is proxied, leaving a NULL `ObjectContext` of this object in the cache tier's `object_contexts`. The NULL `ObjectContext` is not destructed until it's removed from the `object_contexts` LRU. If another op operating on a snapshot of this object reaches before it's destructed, a new NULL snapset is created for this object. I can't remember the specifics here. But at the end, the later op failed.

After making this fix, the bug is gone.

**Comment by liewegas** [comment]
see https://github.com/ceph/ceph/pull/5599

**Pull request closed without merging**
