### PR TITLE
rgw: aws4: add AWS4 auth support for S3 Post Object API

### PR DESCRIPTION
**Pull request by rzarzynski**
This pull request is a reincarnation of #13916 rebased on top of:
 * the recently merged auth rework (#12893),
 * the FormPost of Swift API which also significantly changes the `RGWPostObj` (PR #11179).

The branch has been positively (no regression found) tested with Tempest and s3-tests, but AWSv4 feature still needs verification. @jmunhoz, could you please take a look?

The changes from the original PR have been kept minimal.

### CODE REVIEW

**Comment by rzarzynski** [comment]
jenkins test this please

**Comment by rzarzynski** [comment]
@jmunhoz: thanks for the testing and have a nice holiday!

I fixed the issue and verified the feature manually. It looks operational:
```
2017-04-11 17:27:24.614911 7f220dc4f700 20 CONTENT_LENGTH=1793
2017-04-11 17:27:24.614939 7f220dc4f700 20 CONTENT_TYPE=multipart/form-data; boundary=------------------------------57941406004981059681406004981521920
2017-04-11 17:27:24.614943 7f220dc4f700 20 HTTP_ACCEPT=text/html, text/*;q=0.5, image/*, application/*, audio/*, x-scheme-handler/*, inode/*, x-content/*, message/*, video/*, misc/*
2017-04-11 17:27:24.614944 7f220dc4f700 20 HTTP_ACCEPT_ENCODING=gzip, compress, bzip, bzip2, deflate
2017-04-11 17:27:24.614945 7f220dc4f700 20 HTTP_ACCEPT_LANGUAGE=en;q=1.0
2017-04-11 17:27:24.614946 7f220dc4f700 20 HTTP_HOST=127.0.0.1:8000
2017-04-11 17:27:24.614946 7f220dc4f700 20 HTTP_USER_AGENT=w3m/0.5.3+debian-15
2017-04-11 17:27:24.614963 7f220dc4f700 20 REQUEST_METHOD=POST
2017-04-11 17:27:24.614964 7f220dc4f700 20 REQUEST_URI=/test-1-2-1-bucket
2017-04-11 17:27:24.614965 7f220dc4f700 20 SCRIPT_URI=/test-1-2-1-bucket
2017-04-11 17:27:24.614965 7f220dc4f700 20 SERVER_PORT=8000
2017-04-11 17:27:24.614967 7f220dc4f700  1 ====== starting new request req=0x7f220dc49a00 =====
2017-04-11 17:27:24.614996 7f220dc4f700  2 req 3:0.000027::POST /test-1-2-1-bucket::initializing for trans_id = tx000000000000000000003-0058ecf5dc-102c-default
2017-04-11 17:27:24.615009 7f220dc4f700 10 rgw api priority: s3=5 s3website=4
2017-04-11 17:27:24.615011 7f220dc4f700 10 host=127.0.0.1
2017-04-11 17:27:24.615016 7f220dc4f700 20 subdomain= domain= in_hosted_domain=0 in_hosted_domain_s3website=0
2017-04-11 17:27:24.615018 7f220dc4f700 20 final domain/bucket subdomain= domain= in_hosted_domain=0 in_hosted_domain_s3website=0 s->info.domain= s->info.request_uri=/test-1-2-1-bucket
2017-04-11 17:27:24.615052 7f220dc4f700 20 get_handler handler=25RGWHandler_REST_Bucket_S3
2017-04-11 17:27:24.615057 7f220dc4f700 10 handler=25RGWHandler_REST_Bucket_S3
2017-04-11 17:27:24.615059 7f220dc4f700  2 req 3:0.000091:s3:POST /test-1-2-1-bucket::getting op 4
2017-04-11 17:27:24.615063 7f220dc4f700 10 op=22RGWPostObj_ObjStore_S3
2017-04-11 17:27:24.615064 7f220dc4f700  2 req 3:0.000097:s3:POST /test-1-2-1-bucket:post_obj:verifying requester
2017-04-11 17:27:24.615072 7f220dc4f700  2 req 3:0.000105:s3:POST /test-1-2-1-bucket:post_obj:normalizing buckets and tenants
2017-04-11 17:27:24.615074 7f220dc4f700 10 s->object=<NULL> s->bucket=test-1-2-1-bucket
2017-04-11 17:27:24.615078 7f220dc4f700  2 req 3:0.000111:s3:POST /test-1-2-1-bucket:post_obj:init permissions
2017-04-11 17:27:24.615154 7f220dc4f700 20 get_system_obj_state: rctx=0x7f220dc49850 obj=default.rgw.meta:root:test-1-2-1-bucket state=0x7f224798c040 s->prefetch_data=0
2017-04-11 17:27:24.615162 7f220dc4f700 10 cache get: name=default.rgw.meta+root+test-1-2-1-bucket : hit (requested=0x16, cached=0x17)
2017-04-11 17:27:24.615170 7f220dc4f700 20 get_system_obj_state: s->obj_tag was set empty
2017-04-11 17:27:24.615172 7f220dc4f700 20 Read xattr: user.rgw.idtag
2017-04-11 17:27:24.615173 7f220dc4f700 10 cache get: name=default.rgw.meta+root+test-1-2-1-bucket : hit (requested=0x11, cached=0x17)
2017-04-11 17:27:24.615189 7f220dc4f700 20 rgw_get_bucket_info: bucket instance: test-1-2-1-bucket[330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1])
2017-04-11 17:27:24.615212 7f220dc4f700 20 reading from default.rgw.meta:root:.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1
2017-04-11 17:27:24.615217 7f220dc4f700 20 get_system_obj_state: rctx=0x7f220dc49850 obj=default.rgw.meta:root:.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1 state=0x7f224798c380 s->prefetch_data=0
2017-04-11 17:27:24.615222 7f220dc4f700 10 cache get: name=default.rgw.meta+root+.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1 : hit (requested=0x16, cached=0x17)
2017-04-11 17:27:24.615225 7f220dc4f700 20 get_system_obj_state: s->obj_tag was set empty
2017-04-11 17:27:24.615227 7f220dc4f700 20 Read xattr: user.rgw.acl
2017-04-11 17:27:24.615228 7f220dc4f700 20 Read xattr: user.rgw.idtag
2017-04-11 17:27:24.615229 7f220dc4f700 10 cache get: name=default.rgw.meta+root+.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1 : hit (requested=0x11, cached=0x17)
2017-04-11 17:27:24.615252 7f220dc4f700 10 chain_cache_entry: cache_locator=default.rgw.meta+root+test-1-2-1-bucket
2017-04-11 17:27:24.615254 7f220dc4f700 10 chain_cache_entry: cache_locator=default.rgw.meta+root+.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1
2017-04-11 17:27:24.615283 7f220dc4f700 15 decode_policy Read AccessControlPolicy<AccessControlPolicy xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>s3_main</ID><DisplayName>s3_main</DisplayName></Owner><AccessControlList><Grant><Grantee xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="CanonicalUser"><ID>s3_main</ID><DisplayName>s3_main</DisplayName></Grantee><Permission>FULL_CONTROL</Permission></Grant></AccessControlList></AccessControlPolicy>
2017-04-11 17:27:24.615305 7f220dc4f700  2 req 3:0.000338:s3:POST /test-1-2-1-bucket:post_obj:recalculating target
2017-04-11 17:27:24.615308 7f220dc4f700  2 req 3:0.000341:s3:POST /test-1-2-1-bucket:post_obj:reading permissions
2017-04-11 17:27:24.615311 7f220dc4f700  2 req 3:0.000343:s3:POST /test-1-2-1-bucket:post_obj:init op
2017-04-11 17:27:24.615312 7f220dc4f700  2 req 3:0.000344:s3:POST /test-1-2-1-bucket:post_obj:verifying op mask
2017-04-11 17:27:24.615313 7f220dc4f700 20 required_mask= 2 user.op_mask=7
2017-04-11 17:27:24.615313 7f220dc4f700  2 req 3:0.000346:s3:POST /test-1-2-1-bucket:post_obj:verifying op permissions
2017-04-11 17:27:24.615314 7f220dc4f700  2 req 3:0.000347:s3:POST /test-1-2-1-bucket:post_obj:verifying op params
2017-04-11 17:27:24.615316 7f220dc4f700  2 req 3:0.000349:s3:POST /test-1-2-1-bucket:post_obj:pre-executing
2017-04-11 17:27:24.615317 7f220dc4f700  2 req 3:0.000350:s3:POST /test-1-2-1-bucket:post_obj:executing
2017-04-11 17:27:24.615321 7f220dc4f700 20 request content_type_str=multipart/form-data; boundary=------------------------------57941406004981059681406004981521920
2017-04-11 17:27:24.615322 7f220dc4f700 20 request content_type params:
2017-04-11 17:27:24.615323 7f220dc4f700 20  boundary -> ------------------------------57941406004981059681406004981521920
2017-04-11 17:27:24.615324 7f220dc4f700 20 adding bucket to policy env: test-1-2-1-bucket
2017-04-11 17:27:24.615470 7f220dc4f700 20 read part header -- part.name=x-amz-algorithm
2017-04-11 17:27:24.615472 7f220dc4f700 20 field.name=Content-Disposition
2017-04-11 17:27:24.615472 7f220dc4f700 20 field.val=form-data
2017-04-11 17:27:24.615472 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615473 7f220dc4f700 20  name -> x-amz-algorithm
2017-04-11 17:27:24.615481 7f220dc4f700 20 read part header -- part.name=key
2017-04-11 17:27:24.615483 7f220dc4f700 20 field.name=Content-Disposition
2017-04-11 17:27:24.615483 7f220dc4f700 20 field.val=form-data
2017-04-11 17:27:24.615484 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615484 7f220dc4f700 20  name -> key
2017-04-11 17:27:24.615492 7f220dc4f700 20 read part header -- part.name=x-amz-signature
2017-04-11 17:27:24.615493 7f220dc4f700 20 field.name=Content-Disposition
2017-04-11 17:27:24.615494 7f220dc4f700 20 field.val=form-data
2017-04-11 17:27:24.615494 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615495 7f220dc4f700 20  name -> x-amz-signature
2017-04-11 17:27:24.615502 7f220dc4f700 20 read part header -- part.name=x-amz-date
2017-04-11 17:27:24.615504 7f220dc4f700 20 field.name=Content-Disposition
2017-04-11 17:27:24.615504 7f220dc4f700 20 field.val=form-data
2017-04-11 17:27:24.615505 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615505 7f220dc4f700 20  name -> x-amz-date
2017-04-11 17:27:24.615511 7f220dc4f700 20 read part header -- part.name=policy
2017-04-11 17:27:24.615512 7f220dc4f700 20 field.name=Content-Disposition
2017-04-11 17:27:24.615513 7f220dc4f700 20 field.val=form-data
2017-04-11 17:27:24.615513 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615514 7f220dc4f700 20  name -> policy
2017-04-11 17:27:24.615521 7f220dc4f700 20 read part header -- part.name=x-amz-credential
2017-04-11 17:27:24.615522 7f220dc4f700 20 field.name=Content-Disposition
2017-04-11 17:27:24.615524 7f220dc4f700 20 field.val=form-data
2017-04-11 17:27:24.615524 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615524 7f220dc4f700 20  name -> x-amz-credential
2017-04-11 17:27:24.615535 7f220dc4f700 20 read part header -- part.name=file
2017-04-11 17:27:24.615536 7f220dc4f700 20 field.name=Content-Disposition
2017-04-11 17:27:24.615536 7f220dc4f700 20 field.val=form-data
2017-04-11 17:27:24.615537 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615537 7f220dc4f700 20  filename -> OK
2017-04-11 17:27:24.615538 7f220dc4f700 20  name -> file
2017-04-11 17:27:24.615538 7f220dc4f700 20 field.name=Content-Type
2017-04-11 17:27:24.615539 7f220dc4f700 20 field.val=application/octet-stream
2017-04-11 17:27:24.615539 7f220dc4f700 20 field.params:
2017-04-11 17:27:24.615557 7f220dc4f700  0 Signature verification algorithm AWS v4 (AWS4-HMAC-SHA256)
2017-04-11 17:27:24.615630 7f220dc4f700 10 date_k        = f9d27bfcbea67555ebef847023dd70e59053f3a339f571965b06bc53f4cf226b
2017-04-11 17:27:24.615644 7f220dc4f700 10 region_k      = 15cce7c37fda2a8550ada4f187c400ff31c8d7d57821701ea6b7383620500222
2017-04-11 17:27:24.615656 7f220dc4f700 10 service_k     = d78fc476f3682ce56ba594953ef5b979e69da7730f6a1e4a74301824200b7b5c
2017-04-11 17:27:24.615667 7f220dc4f700 10 signing_k     = 8099e148b642bfd91f4e0353acecdea6f2e6936bd6d42123a739422a0fe8b247
2017-04-11 17:27:24.615908 7f220dc4f700 10 signature_k   = 1723fd97327b223992fd6ae9cd8fce7da72557161e6e9cb8bc3df08b17843a5c
2017-04-11 17:27:24.615919 7f220dc4f700 10 new signature = 1723fd97327b223992fd6ae9cd8fce7da72557161e6e9cb8bc3df08b17843a5c
2017-04-11 17:27:24.615921 7f220dc4f700 10 ----------------------------- Verifying signatures
2017-04-11 17:27:24.615922 7f220dc4f700 10 Signature     = 1723fd97327b223992fd6ae9cd8fce7da72557161e6e9cb8bc3df08b17843a5c
2017-04-11 17:27:24.615923 7f220dc4f700 10 New Signature = 1723fd97327b223992fd6ae9cd8fce7da72557161e6e9cb8bc3df08b17843a5c
2017-04-11 17:27:24.615924 7f220dc4f700 10 -----------------------------
2017-04-11 17:27:24.615934 7f220dc4f700  0 Successful Signature Verification!
2017-04-11 17:27:24.615958 7f220dc4f700  0 POST policy: {"conditions": [["starts-with", "$Content-Type", ""], {"bucket": "test-1-2-1-bucket"}, {"key": "345409b779a94dd3bf235f6551b76bd9"}, {"x-amz-algorithm": "AWS4-HMAC-SHA256"}, {"x-amz-credential": "f05e187d8d4f43a7972b03a92681194a/20170411/eu-central-1/s3/aws4_request"}, {"x-amz-date": "20170411T152550Z"}], "expiration": "2017-04-11T16:25:50Z"}
2017-04-11 17:27:24.616131 7f220dc4f700 20 data=["starts-with","$Content-Type",""]
2017-04-11 17:27:24.616132 7f220dc4f700 20 is_object=0
2017-04-11 17:27:24.616134 7f220dc4f700 20 is_array=1
2017-04-11 17:27:24.616140 7f220dc4f700 20 data={"bucket":"test-1-2-1-bucket"}
2017-04-11 17:27:24.616140 7f220dc4f700 20 is_object=1
2017-04-11 17:27:24.616141 7f220dc4f700 20 is_array=0
2017-04-11 17:27:24.616141 7f220dc4f700  0 adding simple_check: bucket : test-1-2-1-bucket
2017-04-11 17:27:24.616142 7f220dc4f700 20 data={"key":"345409b779a94dd3bf235f6551b76bd9"}
2017-04-11 17:27:24.616143 7f220dc4f700 20 is_object=1
2017-04-11 17:27:24.616143 7f220dc4f700 20 is_array=0
2017-04-11 17:27:24.616143 7f220dc4f700  0 adding simple_check: key : 345409b779a94dd3bf235f6551b76bd9
2017-04-11 17:27:24.616144 7f220dc4f700 20 data={"x-amz-algorithm":"AWS4-HMAC-SHA256"}
2017-04-11 17:27:24.616144 7f220dc4f700 20 is_object=1
2017-04-11 17:27:24.616144 7f220dc4f700 20 is_array=0
2017-04-11 17:27:24.616145 7f220dc4f700  0 adding simple_check: x-amz-algorithm : AWS4-HMAC-SHA256
2017-04-11 17:27:24.616145 7f220dc4f700 20 data={"x-amz-credential":"f05e187d8d4f43a7972b03a92681194a/20170411/eu-central-1/s3/aws4_request"}
2017-04-11 17:27:24.616145 7f220dc4f700 20 is_object=1
2017-04-11 17:27:24.616146 7f220dc4f700 20 is_array=0
2017-04-11 17:27:24.616146 7f220dc4f700  0 adding simple_check: x-amz-credential : f05e187d8d4f43a7972b03a92681194a/20170411/eu-central-1/s3/aws4_request
2017-04-11 17:27:24.616147 7f220dc4f700 20 data={"x-amz-date":"20170411T152550Z"}
2017-04-11 17:27:24.616147 7f220dc4f700 20 is_object=1
2017-04-11 17:27:24.616147 7f220dc4f700 20 is_array=0
2017-04-11 17:27:24.616148 7f220dc4f700  0 adding simple_check: x-amz-date : 20170411T152550Z
2017-04-11 17:27:24.616156 7f220dc4f700 20 comparing bucket [test-1-2-1-bucket], test-1-2-1-bucket
2017-04-11 17:27:24.616157 7f220dc4f700 20 comparing key [345409b779a94dd3bf235f6551b76bd9], 345409b779a94dd3bf235f6551b76bd9
2017-04-11 17:27:24.616158 7f220dc4f700 20 comparing x-amz-algorithm [AWS4-HMAC-SHA256], AWS4-HMAC-SHA256
2017-04-11 17:27:24.616159 7f220dc4f700 20 comparing x-amz-credential [f05e187d8d4f43a7972b03a92681194a/20170411/eu-central-1/s3/aws4_request], f05e187d8d4f43a7972b03a92681194a/20170411/eu-central-1/s3/aws4_request
2017-04-11 17:27:24.616160 7f220dc4f700 20 comparing x-amz-date [20170411T152550Z], 20170411T152550Z
2017-04-11 17:27:24.616161 7f220dc4f700  1 policy condition check $Content-Type []  []
2017-04-11 17:27:24.616166 7f220dc4f700 20 canned_acl=
2017-04-11 17:27:24.616177 7f220dc4f700 20 -- Getting permissions begin with perm_mask=50
2017-04-11 17:27:24.616179 7f220dc4f700  5 Searching permissions for identity=RGWDummyIdentityApplier(auth_id=s3_main, perm_mask=15, is_admin=0) mask=50
2017-04-11 17:27:24.616184 7f220dc4f700  5 Searching permissions for uid=s3_main
2017-04-11 17:27:24.616185 7f220dc4f700  5 Found permission: 15
2017-04-11 17:27:24.616186 7f220dc4f700  5 Searching permissions for group=1 mask=50
2017-04-11 17:27:24.616187 7f220dc4f700  5 Permissions for group not found
2017-04-11 17:27:24.616189 7f220dc4f700  5 Searching permissions for group=2 mask=50
2017-04-11 17:27:24.616190 7f220dc4f700  5 Permissions for group not found
2017-04-11 17:27:24.616191 7f220dc4f700  5 -- Getting permissions done for identity=RGWDummyIdentityApplier(auth_id=s3_main, perm_mask=15, is_admin=0), owner=s3_main, perm=2
2017-04-11 17:27:24.616192 7f220dc4f700 10  identity=RGWDummyIdentityApplier(auth_id=s3_main, perm_mask=15, is_admin=0) requested perm (type)=2, policy perm=2, user_perm_mask=2, acl perm=2
2017-04-11 17:27:24.717199 7f220dc4f700 20 get_obj_state: rctx=0x7f220dc49850 obj=test-1-2-1-bucket:345409b779a94dd3bf235f6551b76bd9 state=0x7f22470af5a0 s->prefetch_data=0
2017-04-11 17:27:24.717249 7f220dc4f700 20 get_obj_state: rctx=0x7f220dc49850 obj=test-1-2-1-bucket:345409b779a94dd3bf235f6551b76bd9 state=0x7f22470af5a0 s->prefetch_data=0
2017-04-11 17:27:24.717262 7f220dc4f700 10 setting object write_tag=330c27cf-9288-4af0-ad5e-b368aad077a2.4140.3
2017-04-11 17:27:24.717304 7f220dc4f700 20 reading from default.rgw.meta:root:.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1
2017-04-11 17:27:24.717315 7f220dc4f700 20 get_system_obj_state: rctx=0x7f220dc474c0 obj=default.rgw.meta:root:.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1 state=0x7f224798c1e0 s->prefetch_data=0
2017-04-11 17:27:24.717325 7f220dc4f700 10 cache get: name=default.rgw.meta+root+.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1 : hit (requested=0x16, cached=0x17)
2017-04-11 17:27:24.717334 7f220dc4f700 20 get_system_obj_state: s->obj_tag was set empty
2017-04-11 17:27:24.717339 7f220dc4f700 10 cache get: name=default.rgw.meta+root+.bucket.meta.test-1-2-1-bucket:330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1 : hit (requested=0x11, cached=0x17)
2017-04-11 17:27:24.717361 7f220dc4f700 20  bucket index object: .dir.330c27cf-9288-4af0-ad5e-b368aad077a2.4140.1
2017-04-11 17:27:25.867406 7f220dc4f700  2 req 3:1.252438:s3:POST /test-1-2-1-bucket:post_obj:completing
2017-04-11 17:27:25.867493 7f220dc4f700  2 req 3:1.252525:s3:POST /test-1-2-1-bucket:post_obj:op status=1902
2017-04-11 17:27:25.867495 7f220dc4f700  2 req 3:1.252528:s3:POST /test-1-2-1-bucket:post_obj:http status=204
2017-04-11 17:27:25.867527 7f220dc4f700  1 ====== req done req=0x7f220dc49a00 op status=1902 http_status=204 ======
```

Also retested the branch with Tempest and s3-tests. No regression found.

**Comment by rzarzynski** [comment]
jenkins test this please

**Comment by rzarzynski** [comment]
jenkins test this please (`libec_FAKE.so: cannot open shared object file`)

**Comment by jmunhoz** [comment]
@rzarzynski great! thanks!

**Comment by rzarzynski** [comment]
Rebased due to conflicts with the recently merged encryption branch. Tempest nor s3-tests haven't found a regression here.

**Comment by rzarzynski** [comment]
Merged as a part of https://github.com/ceph/ceph/pull/14885.

**Pull request closed without merging**
