### PR TITLE
seastar: fix makecheck error: missing 'typename'

### PR DESCRIPTION
**Pull request by Matan-B**
update seastar submodule to wip-matanb-seastar-july4  (https://github.com/ceph/seastar/commits/wip-matanb-seastar-july4/)

Reverting https://github.com/scylladb/seastar/commit/8a3dc425dd9bff7a00ffa3345768e01b1a24825f

This revert is pushed to not block all other PRs that are failing make check due to this.
We can probably follow up with a more solid solution afterwards.

Fixes: https://tracker.ceph.com/issues/66834

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@Matan-B could you file an issue against seastar on this?

**Comment by Matan-B** [comment]
> @Matan-B could you file an issue against seastar on this?

Sure, I'll just make sure that CI is green first and no other issues are there

**Review by ronen-fr — APPROVED** [review]

**Comment by Matan-B** [comment]
> @Matan-B could you file an issue against seastar on this?

Looking again, I think it's caused by Clang 14 usage which is not officially supported by Seastar. Is this still relevant?

**Comment by tchaikov** [comment]
@Matan-B i think it's relevant as long as it's not standard[^1] compliant. what do you think?

[^1]: C++20 and up

**Comment by Matan-B** [comment]
> @Matan-B i think it's relevant as long as it's not standard[1](#user-content-fn-1-2dd2ed40323e455fb1617e278296a0c9) compliant. what do you think?
> 
> ## Footnotes
> 1. C++20 and up [↩](#user-content-fnref-1-2dd2ed40323e455fb1617e278296a0c9)

Submitted https://github.com/scylladb/seastar/issues/2327

**Comment by tchaikov** [comment]
> > @Matan-B i think it's relevant as long as it's not standard[1](#user-content-fn-1-2dd2ed40323e455fb1617e278296a0c9) compliant. what do you think?
> > ## Footnotes
> > 
> > 1. C++20 and up [↩](#user-content-fnref-1-2dd2ed40323e455fb1617e278296a0c9)
> 
> Submitted [scylladb/seastar#2327](https://github.com/scylladb/seastar/issues/2327)

thanks!

**Pull request merged**
