### PR TITLE
nautilus: Do not add sensitive information in Ceph log files

### PR DESCRIPTION
**Pull request by neha-ojha**
backport tracker: https://tracker.ceph.com/issues/48614

---

backport of https://github.com/ceph/ceph/pull/38479
parent tracker: https://tracker.ceph.com/issues/37503

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by neha-ojha** [comment]
https://pulpito.ceph.com/nojha-2020-12-16_02:38:49-rados-wip-48614-nautilus-distro-basic-smithi/ - no related failures

**Comment by smithfarm** [comment]
@neha-ojha Please rebase

**Comment by neha-ojha** [comment]
> @neha-ojha Please rebase

there is a release in progress, will do after that.

**Comment by neha-ojha** [comment]
> > @neha-ojha Please rebase
> 
> there is a release in progress, will do after that.

@smithfarm a rebase is not required

**Comment by neha-ojha** [comment]
@smithfarm this does not need any more testing, see https://github.com/ceph/ceph/pull/38614#issuecomment-746572073

**Comment by smithfarm** [comment]
@neha-ojha Lest I be misunderstood, my intention in queuing PRs for integration testing is never to block them or prevent them from being merged. On the contrary, I'm always trying to increase the likelihood that they _will_ get merged in timely fashion.

You're welcome to dequeue before you merge, but from my POV it's not necessary. The worst that could happen is the PR could get included in one of Yuri's integration runs (which I would argue is not inherently a bad thing, even for PRs that have already been through one or more test runs). But even this should not deter the leads from merging the PR if they believe it has been sufficiently tested.

**Comment by neha-ojha** [comment]
@jdurgin ping, this just needs a review

**Review by jdurgin — APPROVED** [review]

**Pull request merged**
