### PR TITLE
jewel: The request lock RPC message might be incorrectly ignored 

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17057

### CODE REVIEW

**Comment by dachary** [comment]
Conflicts with #10869

**Comment by dachary** [comment]
rebased

**Comment by dachary** [comment]
@idryomov does this backport look good to merge ? It passed the rbd suite http://tracker.ceph.com/issues/17851#note-2 . Please note that it will not be in 10.2.4, reason why the target branch is jewel-next.

**Comment by idryomov** [comment]
LGTM

**Pull request merged**
