### PR TITLE
mds: fix assertion caused by system clock backwards

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #11053
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
I've merged the master version of this, we could let it pass some tests before merging backport, although given we're replacing an assertion with an if(), we won't notice the difference unless something was touching the assertion (nothing in our suite does).

**Comment by dachary** [comment]
@jcsp thanks for the update, I see https://github.com/ceph/ceph/pull/3922 is merged indeed. I'll check back in a few days and look for updates at http://tracker.ceph.com/issues/11053, assuming that's where you would report problems, if any.

**Comment by jcsp** [comment]
@dachary this has gone through a fs suite on master without introducing problems, so it's good to go

**Comment by dachary** [comment]
@jcsp cool, feel free to merge then !

**Pull request merged**
