### PR TITLE
jewel: ceph_volume_client: evict client also based on mount path

### PR DESCRIPTION
**Pull request by ajarr**
Evict clients based on not just their auth ID, but also based on the
volume path mounted. This is needed for the Manila use-case, where
the clients using an auth ID are denied further access to a share.

Fixes: http://tracker.ceph.com/issues/15855

Signed-off-by: Ramana Raja <rraja@redhat.com>
(cherry picked from commit 68714b9)

### CODE REVIEW

**Comment by ajarr** [comment]
Tested by https://github.com/ceph/ceph-qa-suite/pull/1010

**Comment by ajarr** [comment]
@gregsfortytwo , Hi! I'm unable to edit the milestone, assignee, and the labels fields. Can you please fix that for this PR and it's test PR? And let me know if that's something that should be able to do myself -- I'm part of the Ceph github group.

**Comment by smithfarm** [comment]
@ajarr Is this commit a cherry-pick? Except in rare cases, all patches to jewel should done using `git cherry-pick -x` . . . this one is missing the "(cherry-picked from . . . )" line so I'm guessing you omitted the `-x` ?

**Comment by ajarr** [comment]
@smithfarm thanks! done.

**Comment by ajarr** [comment]
@gregsfortytwo I'm able to edit the labels now. thanks! I got the required permissions to do so.

**Comment by smithfarm** [comment]
@ajarr Thanks - we in the Backports and Stable Releases team really appreciate your help. Could I ask you try one more time, though? The `Signed-off-by` should show the name of the person who wrote the original commit. To accomplish this, just do:

```
git cherry-pick -x 68714b9
```

That's all. Don't amend the commit unless there is a conflict - and even then only amend to describe how the conflict was resolved.

**Comment by smithfarm** [comment]
@ajarr: Nevermind, I see now that you backported your own commit. Sorry and LGTM!

**Comment by ajarr** [comment]
@smithfarm , Hi! No problem.  I wanted to hasten the backport as it blocks a cephfs_native driver patch in Manila (the OpenStack File Share as a Service project) that depends on jewel release of CephFS. As per the instructions here, http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_backport_commits, it seems like the next step is to run integration tests. Is it okay if I can assign the backport and stable release team to do this? I'm new to this process flow.

**Comment by smithfarm** [comment]
@ajarr Yes, we will include this PR in the `jewel-backports` integration branch and run integration tests on it. You don't have to do that yourself.

**Comment by smithfarm** [comment]
Note: https://github.com/ceph/ceph-qa-suite/pull/1010 should be merged at the same time as this PR.

**Comment by jcsp** [comment]
@ajarr just checking up on this, I see we have jewel-backports runs in the queue so hopefully not much longer to wait.

**Comment by jcsp** [comment]
Merged this as part of https://github.com/ceph/ceph/pull/9430/commits/470605c38f772e5bcc466e71ac232294b41be276

**Pull request closed without merging**
