### PR TITLE
luminous: ceph_detect_init: Add support for ALT Linux

### PR DESCRIPTION
**Pull request by mrandybu**
Support Alt Linux distribution added.

Signed-off-by: Andrey Bychkov <mrdrew@altlinux.org>

### CODE REVIEW

**Comment by shaba** [comment]
merge this commit, please.

**Comment by mrandybu** [comment]
opened for mimic branch #27028

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by smithfarm** [comment]
@yuriw Let's try to get this one into luminous 12.2.13 by:

1. running ceph-disk suite on https://github.com/ceph/ceph/pull/27028 and merge it into mimic assuming it passes
2. let @mrandybu replace the commit in this PR with a cherry-pick from merged 27028
3. run ceph-disk on this PR

**Comment by smithfarm** [comment]
@mrandybu When cherry-picking, please use `git cherry-pick -x` so git adds a line `(cherry picked from ...)` to the commit message. This is required for all cherry-picks.

**Comment by smithfarm** [comment]
luminous EOL

**Pull request closed without merging**
