### PR TITLE
test/librados: avoid residual crush rule after test case execution

### PR DESCRIPTION
**Pull request by zhangbingyi1**
Fixes: http://tracker.ceph.com/issues/40970
Signed-off-by: Bingyi Zhang <zhangbingyi@umcloud.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
@zhangbingyi1 i'd suggest use the prefix of "test/librados". as "qa" is more likely referencing the qa suite under the "qa/" directory.

**Comment by zhangbingyi1** [comment]
> @zhangbingyi1 i'd suggest use the prefix of "test/librados". as "qa" is more likely referencing the qa suite under the "qa/" directory.

 Okay, I'll pay attention next time.

**Comment by tchaikov** [comment]
@zhangbingyi1 could you revise the commit if you please?

**Comment by zhangbingyi1** [comment]
> @zhangbingyi1 could you revise the commit if you please?

@tchaikov I have already revised the commit. Please check it.

**Pull request merged**
