### PR TITLE
hammer: osd/ReplicatedPG: do not proxy read *and* process op locally

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/15171

### CODE REVIEW

**Comment by liewegas** [comment]
rdleblanc confirms this resolves the problem on his cluster.  Need to run it through teuthology next.

**Comment by dzafman** [comment]
lgtm

**Comment by athanatos** [comment]
lgtm

**Comment by ddiss** [comment]
This change looks good to me. Anything holding up the merge here?

**Comment by dachary** [comment]
@ddiss just waiting for the integration tests to pass

**Comment by dachary** [comment]
https://github.com/ceph/ceph-qa-suite/pull/918#issuecomment-203071873 passes

**Comment by liewegas** [comment]
Just needs to go through the usual rados suite, i think

**Pull request merged**
