### PR TITLE
rgw/iam: fix role deletion replication

### PR DESCRIPTION
**Pull request by awojno-bloomberg**
When deleting a role in the primary zone, the delete does not get replicated. This solution addresses https://tracker.ceph.com/issues/63755

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
thanks @awojno-bloomberg. i noticed and addressed this as part of a much larger changeset in https://github.com/ceph/ceph/pull/54777, but i'd love to see this tested/merged in the meantime

i see that we have a multisite test case for [test_role_sync()](https://github.com/ceph/ceph/blob/9cba1f1/src/test/rgw/rgw_multi/tests.py#L1694-L1706) but nothing that covers role delete; would you be willing to add something there?

**Comment by awojno-bloomberg** [comment]
> thanks @awojno-bloomberg. i noticed and addressed this as part of a much larger changeset in #54777, but i'd love to see this tested/merged in the meantime
> 
> i see that we have a multisite test case for [test_role_sync()](https://github.com/ceph/ceph/blob/9cba1f1/src/test/rgw/rgw_multi/tests.py#L1694-L1706) but nothing that covers role delete; would you be willing to add something there?

Added a test case for role delete syncing. Please take another look when you get a chance @cbodley

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
passed qa in https://pulpito.ceph.com/cbodley-2024-01-09_00:24:23-rgw-wip-cbodley-testing-distro-default-smithi/

both multisite jobs failed as usual, but i do see the new test case passing 👍 
> 2024-01-09T02:07:49.745 INFO:tasks.rgw_multisite_tests:rgw_multi.tests.test_role_delete_sync ... ok
> 2024-01-09T02:36:29.588 INFO:tasks.rgw_multisite_tests:rgw_multi.tests.test_role_delete_sync ... ok

**Comment by awojno-bloomberg** [comment]
> passed qa in https://pulpito.ceph.com/cbodley-2024-01-09_00:24:23-rgw-wip-cbodley-testing-distro-default-smithi/
> 
> both multisite jobs failed as usual, but i do see the new test case passing 👍
> 
> > 2024-01-09T02:07:49.745 INFO:tasks.rgw_multisite_tests:rgw_multi.tests.test_role_delete_sync ... ok
> > 2024-01-09T02:36:29.588 INFO:tasks.rgw_multisite_tests:rgw_multi.tests.test_role_delete_sync ... ok

Great, thanks for all the help!

**Pull request merged**
