### PR TITLE
osd: do not send/handle MOSDPGNotify anymore

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: https://tracker.ceph.com/issues/49758

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
jenkins test api

**Review by jdurgin — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test api

**Comment by tchaikov** [comment]
rebased against master

**Review by ronen-fr — APPROVED** [review]
LGTM

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-03-14_09:40:23-rados-wip-kefu-testing-2021-03-14-1612-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-03-15_02:29:57-rados-wip-kefu-testing-2021-03-15-0034-distro-basic-smithi/

failures are not related.

**Pull request merged**
