### PR TITLE
 doc: Adding a link to documentation on admin socket

### PR DESCRIPTION
**Pull request by ltoto2**
We add a link on  "document on admin socket" to redirect on to the page "http://docs.ceph.com/docs/master/man/8/ceph/#daemon".

### CODE REVIEW

**Comment by dachary** [comment]
I don't think this is how links are done in rst. You can check the documentation for examples I think. Also please make sure the structure of the commit messages is as described at https://github.com/ceph/ceph/blob/master/doc/start/documenting-ceph.rst#commit-the-change

**Comment by dachary** [comment]
@ltoto2 could you please squash the commits into one ?

**Comment by ltoto2** [comment]
@dachary, the squash is done !

**Comment by dachary** [comment]
@ltoto2 you still have 2 commits, can you please make it just one ?

**Comment by ltoto2** [comment]
@dachary, it's good now.

**Pull request merged**
