### PR TITLE
pybind/mgr: Remove code duplication

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Introduced in #27512

Found this by investigating http://tracker.ceph.com/issues/40698 

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
@b-ranto also for restful.module.Module#_serve ?

**Comment by callithea** [comment]
``make check`` complains:
``108/178 Test   #5: run-tox-mgr-dashboard ...................***Failed  110.47 sec``

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2019-07-15_07:47:35-rados:mgr-wip-swagner-testing-distro-basic-mira/

**Comment by rjfd** [comment]
@sebastian-philipp please rebase this on top of master so we can merge it

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp please rebase this on top of master so we can merge it

Hehe. 10 minutes ago, I merged another PR that caused this PR to conflict.

**Comment by sebastian-philipp** [comment]
still **needs-qa**:  This needs a dedicated dashboard QA run. @callithea Sorry about that.

**Comment by callithea** [comment]
> still **needs-qa**: This needs a dedicated dashboard QA run. @callithea Sorry about that.

No worries. :)
Thanks for running it through QA again!

> I'm so used to always run `--filter-out dashboard` in my teuthology runs.

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2019-07-18_09:12:08-rados:mgr-wip-swagner-testing-distro-basic-smithi/

**Pull request merged**
