### PR TITLE
release-notes: v10.1.2 release notes

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Did you trim the list or something? The mds option lockouts stuff should probably go in there since it changed some admin commands and behaviors (albeit, not ones that people should generally have been using).

**Comment by dachary** [comment]
@gregsfortytwo the release notes are built from pull requests. Which pull request includes the missing changes ?

**Comment by dachary** [comment]
@gregsfortytwo I see 735f4be Merge remote-tracking branch 'origin/greg-fs-testing-411' into jewel which contains a number of merges. If you'd like to list the lines to add to the release notes, I'll add them. Going via pull requests the next time will help with the release notes.

**Comment by liewegas** [comment]
@gregsfortytwo can you add htem in a follow-on commit?

**Comment by gregsfortytwo** [comment]
@dachary what are the requirements for the script to pull things in?

The problem is that when PRs conflict we need to resolve them manually. And if we're doing stuff down to the wire, it's a lot safer to merge exactly what was tested rather than clicking the "Merge PR" button a bunch and re-resolve the conflicts (possibly differently than we did for integration branches).

**Comment by gregsfortytwo** [comment]
Oh, looks like it's just checking for the "Merge pull request #(\d+).*" to match against. Easy enough to mimic that.

**Comment by dachary** [comment]
@gregsfortytwo as long as the commits in "Merge pull request #1234*" are actually the commits in PR#1234 it's all good. Otherwise it will be massively confusing when and if someone tries to understand what was merged. For backports for instance.

**Pull request merged**
