### PR TITLE
pacific: mgr/dashboard: ensure limit 0 returns 0 images

### PR DESCRIPTION
**Pull request by pereman2**
backport tracker: https://tracker.ceph.com/issues/57357

backport of https://github.com/ceph/ceph/pull/47673
parent tracker: https://tracker.ceph.com/issues/57178

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by pereman2** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test api

**Review by nizamial09 — APPROVED** [review]

**Review by nizamial09 — CHANGES_REQUESTED** [review]
[make-check error](https://jenkins.ceph.com/job/ceph-pull-requests/104001/consoleFull#11084276166733401c-e9d0-4737-9832-6594c5da0afa) looks related 

```
self = <dashboard.tests.test_rbd_service.RbdServiceTest testMethod=test_rbd_pool_list>
rbd_mock = <MagicMock name='RBD' id='139920993505376'>
rbd_image_ref_mock = <MagicMock name='_rbd_image_refs' id='139920993512576'>
rbd_image_stat_mock = <MagicMock name='_rbd_image_stat' id='139920712222176'>
rbd_image_stat_removing_mock = <MagicMock name='_rbd_image_stat_removing' id='139920712034880'>
_ = <class 'dashboard.tests.test_rbd_service.ImageNotFoundStub'>

    @mock.patch('dashboard.services.rbd.rbd.ImageNotFound', new_callable=lambda: ImageNotFoundStub)
    @mock.patch('dashboard.services.rbd.RbdService._rbd_image_stat_removing')
    @mock.patch('dashboard.services.rbd.RbdService._rbd_image_stat')
    @mock.patch('dashboard.services.rbd.RbdService._rbd_image_refs')
    @mock.patch('dashboard.services.rbd.rbd.RBD')
    def test_rbd_pool_list(self, rbd_mock, rbd_image_ref_mock, rbd_image_stat_mock,
                           rbd_image_stat_removing_mock, _):
        time = datetime.utcnow()
    
        ioctx_mock = MagicMock()
        mgr.rados = MagicMock()
        mgr.rados.open_ioctx.return_value = ioctx_mock
    
        rbd_inst_mock = rbd_mock.return_value
        rbd_inst_mock.namespace_list.return_value = []
        rbd_image_ref_mock.return_value = [{'name': 'test_rbd', 'id': '3c1a5ee60a88'}]
    
        rbd_image_stat_mock.side_effect = mock.Mock(side_effect=ImageNotFoundStub(
            'RBD image not found test_pool/3c1a5ee60a88'))
    
        rbd_image_stat_removing_mock.return_value = {
            'id': '3c1a5ee60a88',
            'unique_id': 'test_pool/3c1a5ee60a88',
            'name': 'test_rbd',
            'source': 'REMOVING',
            'deletion_time': '{}Z'.format(time.isoformat()),
            'deferment_end_time': '{}Z'.format(time.isoformat()),
            'pool_name': 'test_pool',
            'namespace': ''
        }
    
        # test with limit 0, it should return a list of pools with an empty list, but
        rbd_pool_list = RbdService.rbd_pool_list(['test_pool'], offset=0, limit=0)
        self.assertEqual(rbd_pool_list, ([], 1))
    
>       self.rbd_inst_mock.namespace_list.return_value = []
E       AttributeError: 'RbdServiceTest' object has no attribute 'rbd_inst_mock'
```

**Comment by pereman2** [comment]
@nizamial09 because this commit is missing https://github.com/ceph/ceph/pull/47636

**Comment by nizamial09** [comment]
jenkins test make check

**Review by nizamial09 — APPROVED** [review]

**Pull request merged**
