### PR TITLE
rgw: don't store empty chains in gc

### PR DESCRIPTION
**Pull request by yehudasa**
Fixes: http://tracker.ceph.com/issues/17897

Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>

### CODE REVIEW

**Comment by oritwas** [comment]
lgtm
cannot merge because of make check failure.

**Comment by dachary** [comment]
jenkins test this please (eio now ignored in master)

**Comment by dachary** [comment]
jenkins test this please (py24 ceph-disk tox issue fixed in master)

**Comment by dachary** [comment]
test this please

**Comment by dachary** [comment]
jenkins test this please (test_objectstore_memstore.sh failed)

**Comment by dachary** [comment]
jenkins test this please (eio now ignored in master)

**Pull request merged**
