### PR TITLE
osdc/ObjectCacher: avoid livelock in maybe_wait_for_writeback()

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #10498
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jdurgin** [comment]
Were you able to reproduce the problem with ObjectCacher logs or gdb to be sure this was causing the hang for #10498?

It seems pretty unlikely to have requests stuck in a cond wait queue for hours.

I'm not sure if we want the cache ballooning so easily...

**Comment by gregsfortytwo** [comment]
I don't know much about the ObjectCacher, take this. :)

Would it be helpful to bump up debugging on the ObjectCacher for the test that spawned that bug? It's new to me but has repeated several times over the last couple weeks.

**Comment by ukernel** [comment]
It's highly likely ObjectCacher::file_write() stuck in maybe_wait_for_writeback() for about 3 hours. See my new comment at http://tracker.ceph.com/issues/10498

**Comment by gregsfortytwo** [comment]
Discussed this briefly with @jdurgin and we're not going to do this. A better solution is probably to order wakeups.

**Pull request closed without merging**
