### PR TITLE
[DNM] rgw: Jewel datacache

### PR DESCRIPTION
**Pull request by maniaabdi**
Date: Wed Jan 26 15:39:00 2017 +0000

    two Level (L1, L2) Data cache to Radosgw

    configurable caches

    Local L1 Cache

    Distributed L2 Cache

    Based on persistent hashing

    Based on persistent storage

[authors: struct get_obj_data moved from rgw_rados.cc to rgw_rados.h]
[authors: struct RGWDataCache added to rgw_cache.h]
[authors: struct DataCache added to rgw_cache.h]
[authors: added rgw_l2_requester.h/cc]
[authors: struct DataCache added to rgw_cache.h]

(Authors: -- Alphabetic order)
Signed-off-by: Mania Abdi abdi.ma@husky.neu.edu
Signed-off-by: Mohammad Hossein Hajkazemi hajkazemi@husky.neu.edu
Signed-off-by: Emine Ugur Kaynar ukaynar@bu.edu

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@maniaabdi ok, this branch needs to be restaged on a clean baseline;  my recommended procedure:
0. create an ordered list of just your commits (redirect git log output to a file and edit, for example)
1. create a new topic branch based on a more recent ceph master
1.1 be on that branch
2. for each of your commits starting with the earliest, use "git cherry-pick -x <sha1>" to bring just that commit onto your new branch
3. do any other cleanup repetitively at this step (e.g., reorder any commits by cherry picking in a new order, maybe squash some if there are ones that really shouldnt be separate)
4. rename your original branch in case you need to re-do anything but then
5. rename the -new- branch to have the same name as this branch had, and
6. replace the branch from which this PR was taken, with "git push <your-repo> <this-branch>:<this-branch> -f
result:  you'll have just the commits containing your work and a clean history

**Comment by mattbenjamin** [comment]
@maniaabdi oh, this is based on jewel;  we want a branch based on master, as above;  the standard upstream procedure is always to review  and merge onto master, then maybe backport to older releases depending on the change--we dont want to start from jewel

**Comment by yehudasa** [comment]
@maniaabdi @mattbenjamin this branch is based off master, but the PR was made against jewel.

**Comment by yehudasa** [comment]
@maniaabdi @mattbenjamin I modified the PR's baseline, so it's targeted against master now.

**Comment by mattbenjamin** [comment]
@yehudasa oh, that's confusing--so it's a master branch but the PR was against (non-default) jewel? wonder how that happened

**Comment by maniaabdi** [comment]
@Matt, @yehudasa

We have to run tests against the master branch. we tested it with Hammer
and Jewel but we haven't test it against master branch.

Mania

**Comment by zhouyuan** [comment]
@maniaabdi It looks like there's some header called `rgw_l2_requester.h` missing here, can you please also add that in your commits?

**Comment by mattbenjamin** [comment]
@maniaabdi, others, closing this as it is superceded by updated PR

**Pull request closed without merging**
