### PR TITLE
doc/index.rst - remove dboard as TOC top-level

### PR DESCRIPTION
**Pull request by zdover23**
This PR removes mgr/dashboard from the list of top-
level TOC entries in doc/index.rst.

Before this PR, the Dashboard documentation appeared
in the mgr documentation (and it still does), and it
also appeared as its own guide as a top-level entry in
the sidebar on the left of the rendered Sphinx documen-
tation.

This led to a curious feeling of deja vu for me as I worked
on the documentation, and I think that the documentation
suite will be clearer to the first-time reader without this
repetition. (I think it seems like it's two different documents,
making a reader feel that they must read both before deciding
which one to use. I can only imagine the irritation at their
realization that they have wasted their time comparing two bodies
of text that turned out to be identical.)

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by zdover23** [comment]
@epuertat: Do you have any objection to the removal of the Dashboard section as a top-level item in the left-pane table of contents? It appears in the /mgr document already here: https://docs.ceph.com/en/quincy/mgr/dashboard/

**Comment by zdover23** [comment]
@epuertat

**Comment by epuertat** [comment]
> @epuertat: Do you have any objection to the removal of the Dashboard section as a top-level item in the left-pane table of contents? It appears in the /mgr document already here: [docs.ceph.com/en/quincy/mgr/dashboard](https://docs.ceph.com/en/quincy/mgr/dashboard/)

@zdover23: just to clarify, you're asking about removing it from here, right?:

image

If that's the case, I'd say no to this change.

Why? Although there might be reasons to remove it from there (e.g.: architecturally it belongs in the Ceph mgr), IMHO it all comes down to what the project long-term strategy & goals are, and how you make those visible to the users: "usability" has consistently been one of the 5 key themes in the Ceph strategy for years, and "Management" and "Monitoring" usually rank within the top-5 concerns of Ceph users.

So I'm not saying that the Ceph Dashboard should be there becase there's a dedicated team for that and a "first-class" (hate this expression) Ceph component, but that both things happened (the dedicated team and the fully-feature component) because of that commitment from the Ceph community on usability and management. And I therefore think that "Ceph Dashboard" should be left there (I'd also be ok if we want to rename it as "Managing Ceph"..., but then I guess the sections "Cephadm", "Ceph Storage Cluster", etc., should probably go in there too).

@nizamial09 what do you think?

**Comment by zdover23** [comment]
> > @epuertat: Do you have any objection to the removal of the Dashboard section as a top-level item in the left-pane table of contents? It appears in the /mgr document already here: [docs.ceph.com/en/quincy/mgr/dashboard](https://docs.ceph.com/en/quincy/mgr/dashboard/)
> 
> @zdover23: just to clarify, you're asking about removing it from here, right?:
> 
> image
> 
> If that's the case, I'd say no to this change.
> 
> Why? Although there might be reasons to remove it from there (e.g.: architecturally it belongs in the Ceph mgr), IMHO it all comes down to what the project long-term strategy & goals are, and how you make those visible to the users: "usability" has consistently been one of the 5 key themes in the Ceph strategy for years, and "Management" and "Monitoring" usually rank within the top-5 concerns of Ceph users.
> 
> So I'm not saying that the Ceph Dashboard should be there becase there's a dedicated team for that and a "first-class" (hate this expression) Ceph component, but that both things happened (the dedicated team and the fully-feature component) because of that commitment from the Ceph community on usability and management. And I therefore think that "Ceph Dashboard" should be left there (I'd also be ok if we want to rename it as "Managing Ceph"..., but then I guess the sections "Cephadm", "Ceph Storage Cluster", etc., should probably go in there too).
> 
> @nizamial09 what do you think?

@epuertat: That is indeed the location of this top-level link that I want to remove. Given your explanation of the strategic purpose of the link in the sidebar and the lack of any other comment over the past week, I will close this pull request.

**Pull request closed without merging**
