### PR TITLE
Ceph-fuse won't start correctly when the option log_max_new in ceph.conf set to zero

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/13593

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
LGTM

**Comment by Abhishekvrshny** [comment]
@gregsfortytwo the integration tests, which included this backport, were run on fs suite (http://tracker.ceph.com/issues/13750#note-12). It was seen that one of the ceph-fuse jobs failed in both the runs (http://158.69.71.40:8081/ubuntu-2015-12-02_06:58:41-fs-infernalis-backports---basic-openstack/43/ and http://158.69.71.40:8081/ubuntu-2015-12-01_17:18:47-fs-infernalis-backports---basic-openstack/40/). Here is the log: http://paste2.org/YCyAtePU. Do you think this backport can be merged?

**Comment by Abhishekvrshny** [comment]
@gregsfortytwo gentle reminder.

**Comment by gregsfortytwo** [comment]
Yeah, looks fine @smithfarm, @Abhishekvrshny

**Pull request merged**
