### PR TITLE
osd/scrub: collecting scrub-related files into a separate directory

### PR DESCRIPTION
**Pull request by ronen-fr**
NOTE - no logic change in this PR. Just moving some source files around.

Cleaning src/osd from scrub implementation files. Triggered by:
- the proliferation of scrub related code files (including multiple that are added in coming PRs);
- the conventions used in Crimson code, as some of the code will be shared;

Signed-off-by: Ronen Friedman <rfriedma@redhat.com>

### CODE REVIEW

**Review by neha-ojha — COMMENTED** [review]
I am fine with this change if it is necessary for crimson, but we should understand this will result in conflicts for scrub backports in future.

**Comment by ronen-fr** [comment]
> I am fine with this change if it is necessary for crimson, but we should understand this will result in conflicts for scrub backports in future.

@neha-ojha,
(I had a discussion about that with @athanatos, who raised the same issue). My view - the latest collection of fixes which are possibly backport candidates is done. This is why I believe now is the time for this change (which is part of my wip changes since April). The code now, even without the proposed PR, has changed so much that I wouldn't create an automatic backport - manual adjustments will be required anyway.

Going forward - I'd vote for having the scrub code structure as compatible as possible between classic & Crimson.

**Review by athanatos — APPROVED** [review]
If backports won't be easy anyway, now is a good time.

**Review by neha-ojha — APPROVED** [review]

**Comment by ronen-fr** [comment]
Tested as part of yuriw-2021-09-24_14:26:25-rados-wip-yuri6-testing-2021-09-23-1208-distro-basic-smithi.

One scrub-related failure: https://pulpito.ceph.com/yuriw-2021-09-24_14:26:25-rados-wip-yuri6-testing-2021-09-23-1208-distro-basic-smithi/6405902 :
test code failure. Opened https://tracker.ceph.com/issues/52737.

The other failures are not related to the scrub file locations change:
6406063 & 6405872 - dashboard 'e2e' issues;
6405822 - MON crash. Seems to be https://tracker.ceph.com/issues/39150
6405823, 6405839 - environment issue (cgroup issues with a remote)

**Pull request merged**
