### PR TITLE
qa/cephfs: add sleep to test_cephfs_shell.py to avoid race

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
There probably is some kind of race condition due to which issue
described in tracker ticket https://tracker.ceph.com/issues/47292 only
reproduces sometimes. This has been the case in tests for "du" command
in cephfs-shell before. Since a sleep was added to those tests, the
error never reproduced again,

Let's add a sleep to this test to. Hopefully, this issue will stop
reproducing altogether.

Maybe Fixes: https://tracker.ceph.com/issues/47292

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
http://pulpito.front.sepia.ceph.com/rishabh-2023-08-04_21:18:22-fs:shell-wip-rishabh-2023aug3-testing-default-smithi/

**Comment by vshankar** [comment]
> There probably is some kind of race condition due to which issue described in tracker ticket https://tracker.ceph.com/issues/47292 only reproduces sometimes. This has been the case in tests for "du" command in cephfs-shell before. Since a sleep was added to those tests, the error never reproduced again,
> 
> Let's add a sleep to this test to. Hopefully, this issue will stop reproducing altogether.

Have you considered the possibility of stale disk usage stats getting reported which _resolves_ itself after the sleep it added (giving it enough time to sync up the stats)?

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-09-04_11:25:31-fs:shell-wip-rishabh-2023aug3-b5-testing-default-smithi/

With sleep of 10 seconds this test is running fine.

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-09-04_14:03:35-fs:shell-wip-rishabh-2023aug3-b5-testing-default-smithi/

**Comment by rishabh-d-dave** [comment]
https://pulpito.ceph.com/rishabh-2023-09-04_15:08:04-fs:shell-wip-rishabh-2023aug3-b5-testing-default-smithi/

**Comment by vshankar** [comment]
@rishabh-d-dave The stale stats can be due to an issue (race) in the mds and introducing a sleep (which makes the test pass) isn't the correct approach till the underlying issue is RCA'd.

**Comment by rishabh-d-dave** [comment]
> @rishabh-d-dave The stale stats can be due to an issue (race) in the mds and introducing a sleep (which makes the test pass) isn't the correct approach till the underlying issue is RCA'd.

Yes, I digging into underlying code that fetches stats.

**Comment by rishabh-d-dave** [comment]
@vshankar 
> @rishabh-d-dave The stale stats can be due to an issue (race) in the mds and introducing a sleep (which makes the test pass) isn't the correct approach till the underlying issue is RCA'd.

Yes, I digging into underlying code that fetches stats.

**Comment by vshankar** [comment]
> > @rishabh-d-dave - https://tracker.ceph.com/issues/47292#note-9
> 
> I don't generally like sleeps in testing, but I also don't think we have any meaningful guarantees around either rstat speed propagation or rados pgstat reports (which are the potential sources of df's data), so this kind of wait seems fine in this context?

My worry is that the failures are being seen recently and I'm not sure if its due to some change that could possibly have made the stat propagation slower.

**Comment by rishabh-d-dave** [comment]
@vshankar 
> > > @rishabh-d-dave - https://tracker.ceph.com/issues/47292#note-9
> > 
> > 
> > I don't generally like sleeps in testing, but I also don't think we have any meaningful guarantees around either rstat speed propagation or rados pgstat reports (which are the potential sources of df's data), so this kind of wait seems fine in this context?
> 
> My worry is that the failures are being seen recently and I'm not sure if its due to some change that could possibly have made the stat propagation slower.

Would it be a nice idea to merge this ticket for now (so that this failure stops showing up in our QA runs) and open a ticket for deeper investigation that can be carried out little later?

**Comment by vshankar** [comment]
> @vshankar
> 
> > > > @rishabh-d-dave - https://tracker.ceph.com/issues/47292#note-9
> > > 
> > > 
> > > I don't generally like sleeps in testing, but I also don't think we have any meaningful guarantees around either rstat speed propagation or rados pgstat reports (which are the potential sources of df's data), so this kind of wait seems fine in this context?
> > 
> > 
> > My worry is that the failures are being seen recently and I'm not sure if its due to some change that could possibly have made the stat propagation slower.
> 
> Would it be a nice idea to merge this ticket for now (so that this failure stops showing up in our QA runs) and open a ticket for deeper investigation that can be carried out little later?

Frankly, I'd rather have the test fail so that it bothers us :)

**Comment by rishabh-d-dave** [comment]
@vshankar
> Frankly, I'd rather have the test fail so that it bothers us :)

I agree but constant failures would block any cephfs-shell PRs from getting merged.

**Comment by vshankar** [comment]
> @vshankar
> > Frankly, I'd rather have the test fail so that it bothers us :)
> 
> I agree but constant failures would block any cephfs-shell PRs from getting merged.

Don't we note the known issues and proceed with merging PRs?

**Comment by rishabh-d-dave** [comment]
@vshankar 
> Don't we note the known issues and proceed with merging PRs?

We do, but, when a failure occurs, the test suite is run only partially. In such a case, a PR is not tested properly and a buggy PR might get merged.

**Comment by vshankar** [comment]
> @vshankar
> 
> > Don't we note the known issues and proceed with merging PRs?
> 
> We do, but, when a failure occurs, the test suite is run only partially. In such a case, a PR is not tested properly and a buggy PR might get merged.

Sure. But this failures ins't seen in each run which mean other tests do run to completion, so we aren't really missing test coverage with other runs, unless this test fails on _every_ run, in which case the severity would be high anyway.

**Review by chrisphoffman — COMMENTED** [review]
Instead of a sleep, what about adding some sort of `wait_until_true` to wait until it is valid or timeout?

**Comment by vshankar** [comment]
@rishabh-d-dave It looks like no progress has been made for this change? esp. this comment: https://github.com/ceph/ceph/pull/52822#issuecomment-1833419103

What's the plan for this?

**Pull request closed without merging**
