### PR TITLE
pybind/mgr/mgr_module: fix get_mgr_ip()

### PR DESCRIPTION
**Pull request by liewegas**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test docs

**Comment by tchaikov** [comment]
jenkins test docs

**Review by adk3798 — APPROVED** [review]

**Comment by liewegas** [comment]
https://pulpito.ceph.com/sage-2021-06-03_18:12:50-rados:cephadm-wip-sage-testing-2021-06-03-1211-distro-basic-smithi/

**Pull request merged**
