### PR TITLE
pybind / cephfs: remove static typing in LibCephFS.chown

### PR DESCRIPTION
**Pull request by vshankar**

### CODE REVIEW

**Comment by vshankar** [comment]
> Needs a tracker ticket.

done.

**Comment by joscollin** [comment]
http://pulpito.front.sepia.ceph.com/jcollin-2019-11-21_22:40:05-fs-mds_removal_ssh_unused_var_static_typing_testing-distro-basic-smithi/

**Comment by joscollin** [comment]
@vshankar The test fails:
```
Failure Reason:

Test failure: test_subvolume_create_with_desired_uid_gid (tasks.cephfs.test_volumes.TestVolumes) 
```

But it is passed in the master:
```
2019-11-22 06:51:30,586.586 INFO:__main__:test_subvolume_create_with_desired_uid_gid (tasks.cephfs.test_volumes.TestVolumes) ... ok
2019-11-22 06:51:30,586.586 INFO:__main__:Stopped test: test_subvolume_create_with_desired_uid_gid (tasks.cephfs.test_volumes.TestVolumes) in 22.426266s
2019-11-22 06:51:30,586.586 INFO:__main__:
2019-11-22 06:51:30,586.586 INFO:__main__:----------------------------------------------------------------------
2019-11-22 06:51:30,586.586 INFO:__main__:Ran 1 test in 22.427s
2019-11-22 06:51:30,587.587 INFO:__main__:
2019-11-22 06:51:30,587.587 INFO:__main__:OK
(myvenv) [jcollin@stratocaster build]$ git branch
* master
```

**Comment by vshankar** [comment]
> @vshankar The test fails:

will take a look.

**Comment by batrick** [comment]
Failure is not related, see also: /ceph/teuthology-archive/pdonnell-2019-11-26_04:58:35-fs-wip-pdonnell-testing-20191126.005014-distro-basic-smithi/4543972/teuthology.log

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/43038

**Comment by vshankar** [comment]
> Failure is not related, see also: /ceph/teuthology-archive/pdonnell-2019-11-26_04:58:35-fs-wip-pdonnell-testing-20191126.005014-distro-basic-smithi/4543972/teuthology.log

thanks @batrick

**Pull request merged**
