### PR TITLE
rgw/s3select: s3select fixes related to Trino/TPCDS benchmark and QE tests

### PR DESCRIPTION
**Pull request by galsalomon66**
the Trino & TPCDS discovered issues related to the push-down s3select statements.
some of the statements had failed the syntax phase, and some had failed on runtime.

fixes for QE test runs on JSON statements discovered fatal issues. 

- https://bugzilla.redhat.com/show_bug.cgi?id=2225434
- https://github.com/ceph/s3select/pull/132
- https://github.com/ceph/s3select/pull/136

continuation of #52186

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-07-27_13:52:09-rgw:verify-trino_tpcds_qe_fixes-distro-default-smithi/

1 dead 
1 failed on valgrind, the messages are not related to s3select changes.

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-08-03_12:00:57-rgw:verify-trino_tpcds_qe_fixes-distro-default-smithi/
5 failures not related to PR changes
the Valgrind issues no related to s3select
the same with `radosgw log is leaking encryption keys`
there are 2 failures upon shell command which are not related to PR changes.

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-08-07_04:06:38-rgw:verify-trino_tpcds_qe_fixes-distro-default-smithi/
23 success 
1 failure, a valgrind issue which is not related to this PR changes

**Comment by galsalomon66** [comment]
https://pulpito.ceph.com/gsalomon-2023-08-10_10:17:39-rgw:verify-trino_tpcds_qe_fixes-distro-default-smithi/
12 runs
5 deads
7 success

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-08-13_14:24:04-rgw:verify-trino_tpcds_qe_fixes-distro-default-smithi/
24 jobs
5 failures: valgrind issues which are NOT related to recent changes.

**Comment by cbodley** [comment]
@galsalomon66 can you please link the full rgw suite run? i only see links to results for rgw/verify. also please squash the commits

i verified that the valgrind issues are known:
* https://tracker.ceph.com/issues/61661 leak in d3n, already fixed
* https://tracker.ceph.com/issues/62141 UninitCondition not fixed yet

**Comment by galsalomon66** [comment]
http://pulpito.front.sepia.ceph.com/gsalomon-2023-08-15_06:11:09-rgw-trino_tpcds_qe_fixes-distro-default-smithi/
63 passed
5 failed
1 dead

**Pull request merged**
