### PR TITLE
[WIP] mon manage client cache info for rwl replication

### PR DESCRIPTION
**Pull request by changchengx**
This PR implements the function to collect client information for some usage, e.g. one client needs to communicate with another client
This is the basic code for technical talk to refine the design.
I started working on this design from Sep-08-2020, I think this could be designed as a generic feature after thinking for long time. All "replica" string should be refined later.

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by changchengx** [comment]
Function development has been stopped temporarily.
I'll refine this PR to pass CI.

**Comment by changchengx** [comment]
The basic framework of this PR:
https://gist.github.com/changchengx/67694841d9559debf5bbf31a16d5bd0d

**Comment by tchaikov** [comment]
@changchengx i'd suggest discuss this in the CDS for Quincy. see https://pad.ceph.com/p/cds-quincy

**Comment by changchengx** [comment]
@tchaikov 
Thanks. I'm adding it into the list.

**Comment by changchengx** [comment]
Close this PR.
I don't have DCPMM now. Intel employees could submit new PR to refine the RWL-Replication implementation.

**Pull request closed without merging**
