### PR TITLE
rgw: Added code for putting Roles under tenants. 

### PR DESCRIPTION
**Pull request by pritha-srivastava**
Added code for putting Roles under tenants. Also added code for other miscellaneous things like input validation for Roles and exposing some interfaces in RGWRole class which will be helpful in STS authentication.

### CODE REVIEW

**Comment by pritha-srivastava** [comment]
@cbodley : As discussed in the stand-up today, about the concerns that you had about passing in a tenant without passing in a userid - I have an alternative way of doing it, i.e., pass in the tenant id only for create role and then the user will be required to pass in role name as tenantname$rolename (like its is done for users), for all other commands, which will be parsed by RGWRole class to extract the tenant and the role name. This will obviate the need to pass in tenant as a parameter to other role commands.

**Comment by cbodley** [comment]
@pritha-srivastava i think it'd be best to support both uses - tenant supplied explicitly with --tenant, and tenant supplied implicitly as part of the role name

**Comment by pritha-srivastava** [comment]
@cbodley : Thanks, i'll add that part.

**Comment by pritha-srivastava** [comment]
@cbodley @adamemerson : Incorporated your review comments.

**Comment by pritha-srivastava** [comment]
@adamemerson @cbodley : I'll run this thru teuthology before this is merged.

**Comment by pritha-srivastava** [comment]
The teuthology results are here: http://pulpito.ceph.com/prsrivas-2017-02-27_05:44:30-rgw-wip-rgw-role-tenant---basic-smithi/

The failures for this branch are the same as that in the master: http://pulpito.ceph.com/teuthology-2017-02-25_17:05:03-rgw-master---basic-smithi/

Something is wrong with the master branch and since I rebased with master, I see the same failures on this branch also. I think it will be better to get a clean run both on master and then on this branch, before the changes are merged.

**Comment by pritha-srivastava** [comment]
@adamemerson : I ran teuthology by filtering out apache tests and the results are here: http://pulpito.ceph.com/prsrivas-2017-03-07_06:51:32-rgw-wip-rgw-role-tenant---basic-mira/. There are 4 valgrind issues and all of them are in the osd logs. I think this PR can be safely merged.

**Pull request merged**
