### PR TITLE
qa/tests: added 'python3-cephfs','python3-rados' to excluded packadges

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by yuriw** [comment]
@jdurgin http://pulpito.ceph.com/yuriw-2019-05-28_21:13:12-upgrade:mimic-p2p-mimic_v13.2.6_QE-distro-basic-smithi/
failing still :(

**Comment by tchaikov** [comment]
@yuriw lemme take a look

**Comment by yuriw** [comment]
@tchaikov pls do, thx !

**Comment by tchaikov** [comment]
@yuriw in `/a/yuriw-2019-05-28_21:13:12-upgrade:mimic-p2p-mimic_v13.2.6_QE-distro-basic-smithi/3984806/teuthology.log`, i found:

```
2019-05-28T22:15:53.697 DEBUG:teuthology.task.install:Package list is: {'deb': ['ceph', 'ceph-mds', 'ceph-mgr', 'ceph-common', 'ceph-fuse', 'ceph-test', 'radosgw', 'python-ceph', 'libcephfs2', 'libcephfs-dev', 'librados2', 'librbd1', 'rbd-fuse', 'python3-cephfs', 'python3-rados'], 'rpm': ['ceph-radosgw', 'ceph-test', 'ceph', 'ceph-mgr', 'ceph-fuse', 'libcephfs2', 'libcephfs-devel', 'librados2', 'librbd1', 'python-ceph', 'rbd-fuse', 'python3-cephfs', 'python3-rados']}
```

and after filtering the packages with `exclude_packages` black list, we translate `python3-*` packages to `python36-*` packages before installing them. that's why they snuck into the package list to be installed. i replaced all `python36-*` changes with `python3-*` in your change.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-05-31_03:20:11-upgrade:mimic-p2p-mimic_v13.2.6_QE-distro-basic-mira/

**Comment by yuriw** [comment]
@tchaikov Wow, thx !

**Comment by djgalloway** [comment]
> we translate `python3-*` packages to `python36-*` packages before installing them

Where is this done?  Just curious.

**Comment by tchaikov** [comment]
@djgalloway https://github.com/ceph/teuthology/blob/0d3b7d68850d9c54c69d7581b510987ca7c56083/teuthology/task/install/rpm.py#L86

**Pull request merged**
