### PR TITLE
hammer: build/ops: make stop.sh more portable

### PR DESCRIPTION
**Pull request by jschmid1**
http://tracker.ceph.com/issues/16918

see tracker issue for backporting rationale

### CODE REVIEW

**Comment by jschmid1** [comment]
@smithfarm

**Comment by smithfarm** [comment]
marked DNM pending release of 0.94.8, then I will remove the DNM

**Comment by smithfarm** [comment]
@jschmid1 Rebase please?

**Comment by jschmid1** [comment]
rebased the 2nd @smithfarm

**Comment by smithfarm** [comment]
This PR passed an upgrade test, see http://tracker.ceph.com/issues/17151#note-18

Although I am uncertain whether the upgrade test actually exercises the code in this PR, at least we can assert that the PR does not completely break the upgrade suite.

**Pull request merged**
