### PR TITLE
jewel: tools: ceph-disk: separate ceph-osd --check-needs-* logs

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/20011

### CODE REVIEW

**Comment by smithfarm** [comment]
@Vicente-Cheng Please rebase.

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by Vicente-Cheng** [comment]
@smithfarm rebase done!

**Comment by Vicente-Cheng** [comment]
retest this please

**Comment by smithfarm** [comment]
This passed a ceph-disk suite at http://tracker.ceph.com/issues/20613#note-30

**Pull request merged**
