### PR TITLE
kraken: cephfs: normalize file open flags internally used by cephfs

### PR DESCRIPTION
**Pull request by jan--f**
http://tracker.ceph.com/issues/19845

### CODE REVIEW

**Comment by smithfarm** [comment]
@jan--f: Please move the conflict resolution description [1] to below the "(cherry-picked from . . .)" line. The part before that line should be a verbatim copy of the original commit message.

[1] these lines:

```
Conflicts:
	src/client/Client.cc - trivial resolution, add
          ceph_flags_sys2wire when flags are logged
```

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by batrick** [comment]
I may have found a bug in the original code. Please delay merging this.

**Comment by batrick** [comment]
http://tracker.ceph.com/issues/19896

**Comment by batrick** [comment]
False alarm, please proceed.

**Comment by smithfarm** [comment]
@jan--f Please rebase on latest jewel; this will get rid of the obsolete Jenkins tests, one of which has an X next to it.

**Comment by jan--f** [comment]
@smithfarm I assume you mean rebase on latest kraken...

on the way.

**Comment by smithfarm** [comment]
@jan--f: Yes, you passed the test! ;-)

**Comment by smithfarm** [comment]
Jenkins re-test this please (kraken "make check" is showing a high incidence of the "Unix Domain socket path too long" failure)

**Comment by smithfarm** [comment]
@jan--f The make check failure has hopefully been fixed by #16069 - could you please rebase to pick it up?

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
@jan--f Nevermind, rebase not necessary (Jenkins merges into latest base branch before starting the test).

**Comment by smithfarm** [comment]
@jcsp This PR passed an fs run at http://tracker.ceph.com/issues/19009#note-57 (there were some failures that required a fix - applied via https://github.com/ceph/ceph/pull/16114). Please review/approve/merge the PR if you agree it can be merged.

**Comment by smithfarm** [comment]
@batrick This PR passed another fs suite at http://tracker.ceph.com/issues/19009#note-67

Please review.

**Pull request merged**
