### PR TITLE
luminous: rgw: set sync_from_all as true when no value is seen

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22183

### CODE REVIEW

**Comment by pdvian** [comment]
@smithfarm @theanalyst

**Comment by smithfarm** [comment]
test this please

**Comment by smithfarm** [comment]
test_objectstore_memstore.sh failed

```
    -1> 2017-11-20 13:47:25.204810 7f6f335a3700 -1 --- buffer lengths mismatch expected 0x0 != actual 0x56f84
     0> 2017-11-20 13:47:25.215532 7f6f335a3700 -1 /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/store_test.cc: In function 'virtual void SyntheticWorkloadState::C_SyntheticOnClone::finish(int)' thread 7f6f335a3700 time 2017-11-20 13:47:25.204848
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/objectstore/store_test.cc: 3412: FAILED assert(bl_eq(state->contents[noid].data, r2))

 ceph version 12.2.1-823-g987d8b3 (987d8b35a29674a223beef7261481a40f12b7b04) luminous (stable)
 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x102) [0x7f6f38149e02]
 2: (SyntheticWorkloadState::C_SyntheticOnClone::finish(int)+0x39a) [0x55b55de8acba]
 3: (Context::complete(int)+0x9) [0x55b55de65aa9]
 4: (Finisher::finisher_thread_entry()+0x460) [0x7f6f38148010]
 5: (()+0x76ba) [0x7f6f4149e6ba]
 6: (clone()+0x6d) [0x7f6f36dde3dd]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by yuriw** [comment]
[wip-yuri4-testing-2018-01-22-2213-luminous](https://trello.com/c/ZyHjeq8C/240-wip-yuri4-testing-2018-01-22-2213-luminous)

**Pull request merged**
