### PR TITLE
mgr/cephadm: replace async_map_completion with a simple wrapper (again)

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Resurrect #34091

Let's see, if we see https://tracker.ceph.com/issues/44990 in the qa run

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
And indeed I see http://pulpito.ceph.com/swagner-2020-05-08_13:52:54-rados-wip-swagner3-testing-2020-05-08-1329-distro-basic-smithi/5034837/ bad luck or real?

**Comment by mgfritch** [comment]
http://pulpito.ceph.com/mgfritch-2020-05-09_01:31:09-rados-wip-mgfritch-testing-2020-05-08-1646-distro-basic-smithi/

Failures:
* https://tracker.ceph.com/issues/45453
* https://tracker.ceph.com/issues/45458

**Comment by sebastian-philipp** [comment]
http://pulpito.ceph.com/swagner-2020-05-11_17:25:18-rados-wip-swagner-testing-2020-05-11-1648-distro-basic-smithi/

**Comment by sebastian-philipp** [comment]
> http://pulpito.ceph.com/swagner-2020-05-11_17:25:18-rados-wip-swagner-testing-2020-05-11-1648-distro-basic-smithi/

* no failures

**Pull request merged**
