### PR TITLE
[DNM] radosgw: Remove the newline from swift errors.

### PR DESCRIPTION
**Pull request by mdw-at-linuxbox**
The current code emits a newline after swift errors, but fails
to account for it when it calculates 'content-length'.  This results in
some clients (go github.com/ncw/swift) producing complaints about the
unsolicited newline such as this,
	Unsolicited response received on idle HTTP channel starting with "\n"; err=<nil>

This patch removes the newline, but only after get_len() was called,
which happens at the end of the request while calculating content-length.
There are other parts of the swift wire protocol that depend on the
newline being emitted, but all that happens before get_len() is called.

Fixes: http://tracker.ceph.com/issues/18473
Signed-off-by: Marcus Watts <mwatts@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@mdw-at-linuxbox: Is this a cherry-pick of #12895 ? If so, could you redo using `git cherry-pick -x` please. Something like this:

```
git checkout $WIP_BRANCH
git fetch ceph
git reset --hard ceph/jewel
git cherry-pick -x $SHA1
git push -f origin $WIP_BRANCH
```

Also, as a general rule, it's better to wait until the master PR is merged, since it might need to be rebased, in which case the cherry-pick will need to be re-done again.

**Comment by mdw-at-linuxbox** [comment]
I'll probably be redoing this after I redo PR#12895.  See comments there https://github.com/ceph/ceph/pull/12895

**Comment by mdw-at-linuxbox** [comment]
I've updated this pull request to match what I currently have for master (https://github.com/ceph/ceph/pull/12895), and also to match what I have hopefully queued up for teuthology.

**Comment by mdw-at-linuxbox** [comment]
I've pushed an update.  This one is rebased on the lastest jewel, and corrects the sha1 to match what really went into master.  Also pushed to ceph-ci in case anyone wants to try teuthology out on it.  I don't expect significant variation from what I had before, unless an unrelated bug crept in.  Patch proper should be identical.

**Comment by smithfarm** [comment]
@mdw-at-linuxbox This seems to have more commits than strictly necessary?

**Comment by smithfarm** [comment]
#13143 also claims to be a backport of the fix for http://tracker.ceph.com/issues/18473

**Comment by smithfarm** [comment]
If #13143 is sufficient, this could be closed.

**Comment by mdw-at-linuxbox** [comment]
Sorry, right, this was the old fix - PR # 13143 replaces and completely supersedes this fix.  I'll close this.

**Pull request closed without merging**
