### PR TITLE
rgw: don't pass log_op into link_olh during PutObject.

### PR DESCRIPTION
**Pull request by smanjara**
17ca50e seems to have introduced a bug by passing log_op=true into set_olh(). the result is we end up enabling bilog ops on versioned objects by default.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
> 17ca50e70421cfe263784e8d65008145221e41c3 seems to have introduced a bug by passing log_op=true into set_olh(). the result is we end up enabling bilog ops on versioned objects by default.

i'm confused, aren't we supposed to log these? are you sure we didn't before https://github.com/ceph/ceph/pull/54759? cc @jzhu116-bloomberg 

data sync has several checks for CLS_RGW_OP_LINK_OLH, including https://github.com/ceph/ceph/blob/bab43e83/src/rgw/driver/rados/rgw_data_sync.cc#L4487-L4499. my recollection is that we rely on these LINK_OLH entries to learn the versioned_epoch (aka olh_epoch) which the source zone doesn't know when it generates the ADD entry. fetch_remote_obj() has a special case in https://github.com/ceph/ceph/blob/bab43e83/src/rgw/driver/rados/rgw_rados.cc#L4496-L4502 to call set_olh() once we get the epoch from LINK_OLH

**Comment by cbodley** [comment]
> the result is we end up enabling bilog ops on versioned objects by default

ohh, 'by default' meaning even when it's not in multisite

**Comment by smanjara** [comment]
> > the result is we end up enabling bilog ops on versioned objects by default
> 
> ohh, 'by default' meaning even when it's not in multisite

sorry, yes without multisite configured

**Comment by jzhu116-bloomberg** [comment]
> > > the result is we end up enabling bilog ops on versioned objects by default
> > 
> > 
> > ohh, 'by default' meaning even when it's not in multisite
> 
> sorry, yes without multisite configured

With this change, isn't the bilog for link_olf skipped for multisite as well?

How about add the following line before https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L7779 in RGWRados::bucket_index_link_olh(...) so it leaves it to need_to_log_data() to decide if link_olh needs to be added to datalog/bilog, just like we are handling RGWRados::Bucket::UpdateIndex::complete()?

`bool log_data_change = log_data_change && store->svc.zone->need_to_log_data();`

**Comment by smanjara** [comment]
> > > > the result is we end up enabling bilog ops on versioned objects by default
> > > 
> > > 
> > > ohh, 'by default' meaning even when it's not in multisite
> > 
> > 
> > sorry, yes without multisite configured
> 
> With this change, isn't the bilog for link_olf skipped for multisite as well?
> 
> How about add the following line before https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L7779 in RGWRados::bucket_index_link_olh(...) so it leaves it to need_to_log_data() to decide if link_olh needs to be added to datalog/bilog, just like we are handling RGWRados::Bucket::UpdateIndex::complete()?
> 
> `bool log_data_change = log_data_change && store->svc.zone->need_to_log_data();`

@jzhu116-bloomberg, yup, I realized that we no longer pass `svc.zone->need_to_log_data()` directly into `cls_rgw_bucket_link_olh() ` anymore. I have added this extra handling just before set_olh() to keep it in line with delete_obj() https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L5660
works as expected in both multisite and non-multisite case.

**Comment by jzhu116-bloomberg** [comment]
> 
> @jzhu116-bloomberg, yup, I realized that we no longer pass `svc.zone->need_to_log_data()` directly into `cls_rgw_bucket_link_olh() ` anymore. I have added this extra handling just before set_olh() to keep it in line with delete_obj() https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L5660 works as expected in both multisite and non-multisite case.

Noticed that there is another place where the set_olh() is called: https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L4508.  If we check `svc.zone->need_to_log_data()`  outside of set_olh(), should we check it here too?

**Comment by smanjara** [comment]
> Noticed that there is another place where the set_olh() is called: https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L4508. If we check `svc.zone->need_to_log_data()` outside of set_olh(), should we check it here too?

@jzhu116-bloomberg, that is part of fetch_remote_obj() that handles syncing of objects. and that line as Casey
said above, is a special case when we are waiting on an olh_epoch after the ADD entry. we should leave it as it is.

**Review by jzhu116-bloomberg — APPROVED** [review]

**Comment by smanjara** [comment]
> > > Noticed that there is another place where the set_olh() is called: https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L4508. If we check `svc.zone->need_to_log_data()` outside of set_olh(), should we check it here too?
> > 
> > 
> > @jzhu116-bloomberg, that is part of fetch_remote_obj() that handles syncing of objects. and that line as Casey said above, is a special case when we are waiting on an olh_epoch after the ADD entry. we should leave it as it is.
> 
> hmm... this piece of code always log `link_olh` which we don't need in, say, non-multisite settings right?

`fetch_remote_obj()` gets called only in a multisite env, when the secondary syncs the object from the remote zone. so this piece of code does not get exercised in non-multisite case. as for the special case here, it is possible that we applied OP_ADD first without a valid olh, and we make an update to the olh at a later stage. we are trying to log that update here.

**Comment by jzhu116-bloomberg** [comment]
> > > > Noticed that there is another place where the set_olh() is called: https://github.com/ceph/ceph/blob/main/src/rgw/driver/rados/rgw_rados.cc#L4508. If we check `svc.zone->need_to_log_data()` outside of set_olh(), should we check it here too?
> > > 
> > > 
> > > @jzhu116-bloomberg, that is part of fetch_remote_obj() that handles syncing of objects. and that line as Casey said above, is a special case when we are waiting on an olh_epoch after the ADD entry. we should leave it as it is.
> > 
> > 
> > hmm... this piece of code always log `link_olh` which we don't need in, say, non-multisite settings right?
> 
> `fetch_remote_obj()` gets called only in a multisite env, when the secondary syncs the object from the remote zone. so this piece of code does not get exercised in non-multisite case. as for the special case here, it is possible that we applied OP_ADD first without a valid olh, and we make an update to the olh at a later stage. we are trying to log that update here.

ah yes you are right. this is only called in multisite

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
https://pulpito.ceph.com/cbodley-2024-02-23_03:36:00-rgw-wip-cbodley-testing-distro-default-smithi/

**Comment by cbodley** [comment]
@smanjara can you please open a squid pr for this? it doesn't need a tracker issue

**Pull request merged**
