### PR TITLE
osd: Add cli upmap command to change the primary OSD of a pg

### PR DESCRIPTION
**Pull request by JoshSalomon**
osd: Add cli upmap command to change the primary OSD of a pg

Add 2 new commands:
ceph osd pg-upmap-primary <pgid> <osdid> and ceph osd rm-pg-upmap-primary <pgid>
These commands work only on pgs of replicated pools and change the primary osd of the pg to be <osdid>.
The command checks that osdid is part of the pg and fails if not. In any case, no data movement is performed, this is metadata-only command. 

These commands are required in order to implement the read balancer. 

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]

**Comment by ljflores** [comment]
Have tested this locally, and it looks good!

**Comment by JoshSalomon** [comment]
jenkins test api

**Comment by ljflores** [comment]
@JoshSalomon I have asked Yuri to put this PR in the next main batch.

**Comment by ljflores** [comment]
@JoshSalomon can you please squash your commits into one? It's fine if there are multiple commits, but I see some that talk about "minor cosmetic changes" or "TODOs" that can probably all be squashed into one commit.

To squash your commits:

1. cd ceph
2. git checkout `chg-primary`
3. git rebase -i HEAD~5 (since there are 5 total commits)

You should see a screen with:
```
pick 60ec1c6ddbe osd: Initial version of the osd pg-upmap-primary and rm-pg-upmap-primary commands.
pick a9be0097280 osd: Set minimal version for pg_upmap_primary command(s) to reef      Added upmap primary dump code (to json and sceen) - not fully tested yet
pick 34d9b6b25ed osd: improved json dump of pg_upmap_primaries
pick 8e1d1c64811 osd: mainly cosmetic changed, removing TODO comments which were      Done. Leaving one TODO item for a non critical task.
pick a8f9e1e5f7a osd: minor change to make refactored error message identicel to original error message.
```

4. Replace the word "pick" with "squash" on all but the top commit, like this:
```
pick 60ec1c6ddbe osd: Initial version of the osd pg-upmap-primary and rm-pg-upmap-primary commands.
squash a9be0097280 osd: Set minimal version for pg_upmap_primary command(s) to reef      Added upmap primary dump code (to json and sceen) - not fully tested yet
squash 34d9b6b25ed osd: improved json dump of pg_upmap_primaries
squash 8e1d1c64811 osd: mainly cosmetic changed, removing TODO comments which were      Done. Leaving one TODO item for a non critical task.
squash a8f9e1e5f7a osd: minor change to make refactored error message identicel to original error message.
```

5. Save the text file (in vim it's `:wq`)

6. You should now see a screen like:
```
# This is a combination of 5 commits.
# This is the 1st commit message:

osd: Initial version of the osd pg-upmap-primary and rm-pg-upmap-primary
commands.

Signed-off-by: Josh Salomon <jsalomon@redhat.com>

# This is the commit message #2:

osd: Set minimal version for pg_upmap_primary command(s) to reef
     Added upmap primary dump code (to json and sceen) - not fully tested yet

Signed-off-by: Josh Salomon <jsalomon@redhat.com>

# This is the commit message #3:

osd: improved json dump of pg_upmap_primaries

Signed-off-by: Josh Salomon <jsalomon@redhat.com>

# This is the commit message #4:

osd: mainly cosmetic changed, removing TODO comments which were
     Done. Leaving one TODO item for a non critical task.

Signed-off-by: Josh Salomon <jsalomon@redhat.com>

# This is the commit message #5:

osd: minor change to make refactored error message identicel to original
error message.

Signed-off-by: Josh Salomon <jsalomon@redhat.com>

... etc
```

6. Modify the file so it has one title and one description that encompasses all your changes, i.e. The lines with a pound sign in front of them are just comments that will be ignored by git, so you can just leave them:
```
osd, mon: add `osd pg-upmap-primary` and `rm-pg-upmap-primary` commands

<Describe all the changes that you did here......>

Signed-off-by: Josh Salomon <jsalomon@redhat.com>

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Author:    Josh Salomon <jsalomon@redhat.com>
# Date:      Wed Nov 2 16:23:28 2022 +0200
#
# interactive rebase in progress; onto aac5bbd1fe9
# Last commands done (5 commands done):
#    squash 8e1d1c64811 osd: mainly cosmetic changed, removing TODO comments which were      Done. Leaving one TODO item for a non critical task.
#    squash a8f9e1e5f7a osd: minor change to make refactored error message identicel to original error message.
# No commands remaining.
# You are currently rebasing branch 'JoshSalomon-chg-primary' on 'aac5bbd1fe9'.
```

7. Save the file (in vim it's `:wq`)
8. Run `git log`, and you should see one large commit that has all your changes now.
9. Since we changed the history, you have to force-push the changes with `git push --force <name of your remote repository> chg-primary`.

Then you're good!

**Comment by ljflores** [comment]
Looks great!

**Pull request merged**
