### PR TITLE
debian: install from site-packages to dist-packages

### PR DESCRIPTION
**Pull request by tchaikov**
this change addresses the regression introduced by
637dd7b40404e644519b1fc3b5ef03f2d18def00

dist-packages is a debian specific directory for holding 3rd party
python modules. so install the pure python packages into it.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by yuriw — APPROVED** [review]

**Comment by tchaikov** [comment]
changlog

- add `/usr/bin/dh-exec` shebang line
- `chmod +x` to the changed `.install` file
- remove the filename component in the path, less repeatings this way.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-python-debian/6404249dd06a37a7aa0a6578d63569f04f40c8f4/

**Comment by vshankar** [comment]
> https://shaman.ceph.com/builds/ceph/wip-python-debian/6404249dd06a37a7aa0a6578d63569f04f40c8f4/

So, ubuntu focal builds are fine, but broke centos build?

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
@vshankar should be fixed in the latest revision.

**Comment by tchaikov** [comment]
https://shaman.ceph.com/builds/ceph/wip-python-debian/e6eee052220e78b09fab04dab27ef7901ffbe8f3/

**Comment by vshankar** [comment]
thx @tchaikov

**Comment by djgalloway** [comment]
The CentOS build failures in this PR look awfully similar to the ones this PR was supposed to fix.

```
RPM build errors:
    File not found: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.0.0-11401-g6404249d/rpm/el8/BUILDROOT/ceph-17.0.0-11401.g6404249d.el8.x86_64/usr/lib/python3.6/site-packages/ceph_argparse.py
    File not found: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.0.0-11401-g6404249d/rpm/el8/BUILDROOT/ceph-17.0.0-11401.g6404249d.el8.x86_64/usr/lib/python3.6/site-packages/__pycache__/ceph_argparse.cpython*.py*
    File not found: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.0.0-11401-g6404249d/rpm/el8/BUILDROOT/ceph-17.0.0-11401.g6404249d.el8.x86_64/usr/lib/python3.6/site-packages/ceph_daemon.py
    File not found: /home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos8/DIST/centos8/MACHINE_SIZE/gigantic/release/17.0.0-11401-g6404249d/rpm/el8/BUILDROOT/ceph-17.0.0-11401.g6404249d.el8.x86_64/usr/lib/python3.6/site-packages/__pycache__/ceph_daemon.cpython*.py*
```

**Comment by djgalloway** [comment]
Sorry, yep.  /me goes to get more coffee.  Thank you Kefu!

**Pull request merged**
