### PR TITLE
[RFC]For bluestore remove onapplied_sync callback function

### PR DESCRIPTION
**Pull request by majianpeng**

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . Could you review this? Thanks!

**Comment by liewegas** [comment]
I think this is a more aggressive variation of this: https://github.com/ceph/ceph/pull/20177

**Comment by liewegas** [comment]
(We should get to rip out pretty much all of this code for *all* ObjectStore backends)

**Comment by majianpeng** [comment]
Review your PR, i think it already contain my. I'll close this. And I have a question.
In PrimaryLogPG::issue_repop: is it need call add_obc function(https://github.com/liewegas/ceph/blob/dc27f5347ab66b14b96bde7f0e16927ee201d3da/src/osd/PrimaryLogPG.cc#L10091).  Search code found only ECBackend use those and repop don't use anymore.   Or am i missing something?

**Comment by liewegas** [comment]
Yeah probably not, haven't started looking at what all can be removed/simplified once this goes away!  I'd welcome patches on top of that branch that remove other unnecessary code!

**Pull request closed without merging**
