### PR TITLE
AsyncConnection: Let receiver ack message ASAP

### PR DESCRIPTION
**Pull request by yuyuyu101**
Currently dispatchers may exists logic requires ack message ASAP in order to
avoid sender resend messages when socket error.

Fix #136666
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
Tested in http://pulpito.ceph.com/haomai-2015-11-10_11:24:27-rados-wip-haomai-testing-distro-basic-multi/.

Failed jobs 1145091 and 1145178 his http://tracker.ceph.com/issues/13767
Failed job 1145207 hits fd limits

**Comment by yuyuyu101** [comment]
ready to merge

**Comment by dachary** [comment]
> Failed job 1145207 hits fd limits

@yuyuyu101 is there a ticket open to fix this ? I'm experiencing the same errors when running tests on hammer.

**Comment by yuyuyu101** [comment]
@dachary http://tracker.ceph.com/issues/13766

**Comment by yuyuyu101** [comment]
@liewegas give a look? It has passed tests.

**Pull request merged**
