### PR TITLE
[DNM BECAUSE NEEDS TEST FIX] octopus: cephadm: fix port_in_use when IPv6 is disabled

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #39421

### CODE REVIEW

**Comment by smithfarm** [comment]
@sebastian-philipp Would be great if you could get all the "required" Jenkins checks green before adding "octopus-branch-1"?

**Comment by sebastian-philipp** [comment]
```
=================================== FAILURES ===================================
________________________ TestCephAdm.test_attempt_bind _________________________

args = (<tests.test_cephadm.TestCephAdm object at 0x7fe2dc0bda20>,)
keywargs = {}

    @wraps(func)
    def patched(*args, **keywargs):
        with self.decoration_helper(patched,
                                    args,
>                                   keywargs) as (newargs, newkeywargs):

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1345: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.6/contextlib.py:81: in __enter__
    return next(self.gen)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1325: in decoration_helper
    arg = exit_stack.enter_context(patching)
/usr/lib/python3.6/contextlib.py:330: in enter_context
    result = _cm_type.__enter__(cm)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1414: in __enter__
    original, local = self.get_original()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mock.mock._patch object at 0x7fe2d8d736d8>

    def get_original(self):
        target = self.getter()
        name = self.attribute
    
        original = DEFAULT
        local = False
    
        try:
            original = target.__dict__[name]
        except (AttributeError, KeyError):
            original = getattr(target, name, DEFAULT)
        else:
            local = True
    
        if name in _builtins and isinstance(target, ModuleType):
            self.create = True
    
        if not self.create and original is DEFAULT:
            raise AttributeError(
>               "%s does not have the attribute %r" % (target, name)
            )
E           AttributeError: <module 'cephadm' from 'cephadm'> does not have the attribute 'logger'

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1388: AttributeError
_________________________ TestCephAdm.test_port_in_use _________________________

args = (<tests.test_cephadm.TestCephAdm object at 0x7fe2d8cd86a0>,)
keywargs = {}

    @wraps(func)
    def patched(*args, **keywargs):
        with self.decoration_helper(patched,
                                    args,
>                                   keywargs) as (newargs, newkeywargs):

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1345: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.6/contextlib.py:81: in __enter__
    return next(self.gen)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1325: in decoration_helper
    arg = exit_stack.enter_context(patching)
/usr/lib/python3.6/contextlib.py:330: in enter_context
    result = _cm_type.__enter__(cm)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1414: in __enter__
    original, local = self.get_original()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mock.mock._patch object at 0x7fe2d83ab278>

    def get_original(self):
        target = self.getter()
        name = self.attribute
    
        original = DEFAULT
        local = False
    
        try:
            original = target.__dict__[name]
        except (AttributeError, KeyError):
            original = getattr(target, name, DEFAULT)
        else:
            local = True
    
        if name in _builtins and isinstance(target, ModuleType):
            self.create = True
    
        if not self.create and original is DEFAULT:
            raise AttributeError(
>               "%s does not have the attribute %r" % (target, name)
            )
E           AttributeError: <module 'cephadm' from 'cephadm'> does not have the attribute 'logger'

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1388: AttributeError
____________________ TestCephAdm.test_check_ip_port_success ____________________

args = (<tests.test_cephadm.TestCephAdm object at 0x7fe2d8c78208>,)
keywargs = {}

    @wraps(func)
    def patched(*args, **keywargs):
        with self.decoration_helper(patched,
                                    args,
>                                   keywargs) as (newargs, newkeywargs):

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1345: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.6/contextlib.py:81: in __enter__
    return next(self.gen)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1325: in decoration_helper
    arg = exit_stack.enter_context(patching)
/usr/lib/python3.6/contextlib.py:330: in enter_context
    result = _cm_type.__enter__(cm)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1414: in __enter__
    original, local = self.get_original()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mock.mock._patch object at 0x7fe2d8d3d1d0>

    def get_original(self):
        target = self.getter()
        name = self.attribute
    
        original = DEFAULT
        local = False
    
        try:
            original = target.__dict__[name]
        except (AttributeError, KeyError):
            original = getattr(target, name, DEFAULT)
        else:
            local = True
    
        if name in _builtins and isinstance(target, ModuleType):
            self.create = True
    
        if not self.create and original is DEFAULT:
            raise AttributeError(
>               "%s does not have the attribute %r" % (target, name)
            )
E           AttributeError: <module 'cephadm' from 'cephadm'> does not have the attribute 'logger'

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1388: AttributeError
____________________ TestCephAdm.test_check_ip_port_failure ____________________

args = (<tests.test_cephadm.TestCephAdm object at 0x7fe2d8c53198>,)
keywargs = {}

    @wraps(func)
    def patched(*args, **keywargs):
        with self.decoration_helper(patched,
                                    args,
>                                   keywargs) as (newargs, newkeywargs):

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1345: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.6/contextlib.py:81: in __enter__
    return next(self.gen)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1325: in decoration_helper
    arg = exit_stack.enter_context(patching)
/usr/lib/python3.6/contextlib.py:330: in enter_context
    result = _cm_type.__enter__(cm)
.tox/py3/lib/python3.6/site-packages/mock/mock.py:1414: in __enter__
    original, local = self.get_original()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <mock.mock._patch object at 0x7fe2d8d3d320>

    def get_original(self):
        target = self.getter()
        name = self.attribute
    
        original = DEFAULT
        local = False
    
        try:
            original = target.__dict__[name]
        except (AttributeError, KeyError):
            original = getattr(target, name, DEFAULT)
        else:
            local = True
    
        if name in _builtins and isinstance(target, ModuleType):
            self.create = True
    
        if not self.create and original is DEFAULT:
            raise AttributeError(
>               "%s does not have the attribute %r" % (target, name)
            )
E           AttributeError: <module 'cephadm' from 'cephadm'> does not have the attribute 'logger'

.tox/py3/lib/python3.6/site-packages/mock/mock.py:1388: AttributeError
=========================== short test summary info ============================
FAILED tests/test_cephadm.py::TestCephAdm::test_attempt_bind - AttributeError...
FAILED tests/test_cephadm.py::TestCephAdm::test_port_in_use - AttributeError:...
FAILED tests/test_cephadm.py::TestCephAdm::test_check_ip_port_success - Attri...
FAILED tests/test_cephadm.py::TestCephAdm::test_check_ip_port_failure - Attri...
========================= 4 failed, 26 passed in 1.07s =========================

**Comment by smithfarm** [comment]
@sebastian-philipp Ping

**Comment by sebastian-philipp** [comment]
I'm still super busy right now. Would be great if someone could take over this backport

**Comment by smithfarm** [comment]
> I'm still super busy right now. Would be great if someone could take over this backport

That person would need to be someone who knows which commit is missing to fix the test failure, though.

**Comment by sebastian-philipp** [comment]
I fear that this is a genuine conflict that needs a custom fix

**Comment by sebastian-philipp** [comment]
I don't have the bandwith to do the backport. cc @smithfarm + @mgfritch + @p-se

**Comment by smithfarm** [comment]
Replaced by #41602

**Pull request closed without merging**
