### PR TITLE
nautilus: mds: drop reconnect message from non-existent session

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/39192

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by smithfarm** [comment]
jenkins test docs

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-05-30-2109-nautilus](https://trello.com/c/EwK5ZFeZ/625-wip-yuri6-testing-2019-05-30-2109-nautilus)

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-06-03-1602-nautilus](https://trello.com/c/QCnClhIT/628-wip-yuri6-testing-2019-06-03-1602-nautilus)

**Pull request merged**
