### PR TITLE
doc/rgw: fix typo, abbreviation error etc.

### PR DESCRIPTION
**Pull request by xiexingguo**
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by xiexingguo** [comment]
@tchaikov Some nit picking, once you are available.

**Comment by theanalyst** [comment]
lgtm

**Comment by xiexingguo** [comment]
@theanalyst Thanks a lot :+1:

**Comment by xiexingguo** [comment]
@tchaikov Would you kindly get this merged? Thanks:-)

**Pull request merged**
