### PR TITLE
mimic: mds: fix infinite loop in Locker::file_update_finish

### PR DESCRIPTION
**Pull request by ukernel**
backport tracker: https://tracker.ceph.com/issues/42156
possibly a backport of https://github.com/ceph/ceph/pull/29902
parent tracker: https://tracker.ceph.com/issues/41434

---

updated using ceph-backport.sh version 15.0.0.6814

### CODE REVIEW

**Comment by smithfarm** [comment]
@ukernel The second commit (the revert) does not have a `Signed-off-by` line. Could you please re-do it with:

```
git cherry-pick -x 06b878c5bbb6e35b8428281fc648bc2316192ae7
```

?

**Comment by smithfarm** [comment]
```
156/157 Test #128: unittest_alloc_bench ....................   Passed  779.63 sec
./run-make-check.sh: line 36: 30926 Terminated              $DRY_RUN ctest $CHECK_MAKEOPTS --output-on-failure
Build step 'Execute shell' marked build as failure
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-02-20-1957-mimic](https://trello.com/c/E7WZUUi0/833-wip-yuri2-testing-2020-02-20-1957-mimic)

**Pull request merged**
