### PR TITLE
jewel: client: release revoking Fc after invalidate cache

### PR DESCRIPTION
**Pull request by pdvian**
http://tracker.ceph.com/issues/22689

### CODE REVIEW

**Comment by pdvian** [comment]
@ukernel @smithfarm

**Comment by smithfarm** [comment]
@batrick @ukernel Could you take a look? (At least one of the commits did not cherry-pick cleanly.)

**Comment by smithfarm** [comment]
This PR is included in the CephFS integration run: http://tracker.ceph.com/issues/21742#note-12

The run looks like it will pass (still waiting on one job). If so, it will be merged unless there are objections.

**Comment by smithfarm** [comment]
CephFS integration run passed at http://tracker.ceph.com/issues/21742#note-12

**Pull request merged**
