### PR TITLE
octopus: mgr/dashboard: add popover list of Stand-by Managers & Metadata Servers (MDS) in landing page

### PR DESCRIPTION
**Pull request by avanthakkar**
backport tracker: https://tracker.ceph.com/issues/44697

---

backport of https://github.com/ceph/ceph/pull/33529
parent tracker: https://tracker.ceph.com/issues/42979

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by avanthakkar** [comment]
jenkins test dashboard backend

**Pull request closed without merging**
