### PR TITLE
tools: cleanup: rip out ceph-rest-api

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/21264
http://tracker.ceph.com/issues/22457

### CODE REVIEW

**Comment by liewegas** [comment]
@dvanders ping

**Comment by dmick** [comment]
Not to be a naysayer, but: does the mgr's REST API allow submitting any ceph CLI command in a supported way?

Supposedly ceph-rest-api does (and it uses the command descriptions from the daemons, so supposedly added new commands as they were added).  I really doubt any large org is depending on this in any meaningful way, but...it's not clear to me that we have an exact replacement.

**Comment by jcsp** [comment]
I don't think there are any detailed docs online for the new rest api :-( so I'm just looking at the code, it looks like the Request.post method is meant to be a passthrough.

ceph-rest-api does have a nice dump of available commands for mistyped URLs, which probably makes it a bit friendlier for people who are really looking for a passthrough.

I'm also a bit concerned that there hasn't been any active development activity on the restful module -- if we are going to maintain something minimal then porting ceph_rest_api forward into a mgr module might make more sense.

**Comment by dvanders** [comment]
@liewegas no problem here. Thx for the ping.

**Comment by liewegas** [comment]
My preference would also be to transplant this into a mgr module, but that takes actual work.  :/

**Comment by b-ranto** [comment]
The restful module does provide a pass through method. It is not properly documented because when the module was introduced it was suggested that it should be difficult to use so that people do not expect too much out of it as they did in case of calamari 'command' endpoint.

We can make it more usable so that it could fully obsolete the ceph-rest-api and it should not be too difficult to achieve.

You are right that we should take a dump of the /doc endpoint and add it to the upstream docs. I'll try to do that in the next couple of days. It is better to have this readily available online as well.

**Comment by LenzGr** [comment]
FWIW, [inkscope](https://github.com/inkscope/inkscope) uses the ceph-rest-api to perform its tasks - it may make sense to ping @A-Dechorgnat on his take on removing this.

**Comment by smithfarm** [comment]
If someone steps forward to convert ceph-rest-api into a mgr module, feel free to close this PR.

If the consensus is to rip it out for mimic, and assuming this PR is still a viable option for doing that, let me know and I'll rebase it.

**Comment by jcsp** [comment]
I'm inclined to proceed with ripping it out, as although people have fairly suggested that it would be nice to port it over to mgr, or to improve the restful module's documentation, I don't think anyone is volunteering to do any work.

Anyone who misses ceph-rest-api has a couple of decent options: use the CLI (this was already just a pass-through CLI wrapper), or move to the restful module.

@liewegas ?

**Comment by liewegas** [comment]
Yeah, as long as we have a specific place in restful to point users toward, I'm fine.

**Comment by b-ranto** [comment]
This should help with regards to the restful documentation. It also explains how to use the pass through method.

https://github.com/ceph/ceph/pull/20717

**Comment by smithfarm** [comment]
OK, rebased and removing DNM

**Comment by smithfarm** [comment]
Will proceed with QA testing after I get one more review?

**Comment by smithfarm** [comment]
Changelog:

* fixed multiple issues in the PendingReleaseNotes commit

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-smithfarm-testing-2018-03-05-1617/

**Comment by smithfarm** [comment]
Oops, found a problem in https://github.com/ceph/ceph/pull/19598 which caused a massive rados failure. Added a commit to fix it.

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-smithfarm-testing-2018-03-05-2213/d4778ca1ef5d0da8b2d9c4b28ae703b2c692fd3f/

**Comment by smithfarm** [comment]
Note to self: need to backport the build/ops (DEB) to luminous fix via http://tracker.ceph.com/issues/22457

**Comment by smithfarm** [comment]
https://shaman.ceph.com/builds/ceph/wip-21264/2d4a404d57f76d4065d80d35e98eb9f3e106da74/

**Pull request merged**
