### PR TITLE
jewel: MDS goes damaged on blacklist (failed to read JournalPointer: -108 ((108) Cannot send after transport endpoint shutdown)

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17478

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
rc/test/cli/osdmaptool/print-nonexistent.t: passed
src/test/cli/osdmaptool/test-map-pgs.t: failed
--- /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/cli/osdmaptool/test-map-pgs.t
+++ ./src/test/cli/osdmaptool/test-map-pgs.t.err
@@ -40,6 +40,7 @@
 # it is almost impossible to get the same stats with random and crush
 # if they are, it most probably means something went wrong somewhere
   $ test "$STATS_CRUSH" != "$STATS_RANDOM"
+  [1]
 #
 # cleanup
 #
src/test/cli/osdmaptool/tree.t: passed
</pre>

**Comment by jcsp** [comment]
@dachary that test failure looks really unlikely to be anything to do with this change

**Comment by dachary** [comment]
jenkins test this please

**Comment by dachary** [comment]
rebased

**Comment by dachary** [comment]
@jcsp does this backport look good to merge ? It passed the fs suite http://tracker.ceph.com/issues/17851#note-5 (except for valgrind failures and one java test failure that also fail on the jewel branch ).

**Pull request merged**
