### PR TITLE
luminous: osd: get loadavg per cpu for scrub load threshold check

### PR DESCRIPTION
**Pull request by dzafman**
https://tracker.ceph.com/issues/36419

### CODE REVIEW

**Comment by dzafman** [comment]
Including ceph/ceph#24532 commits, testing passed:
run-standalone.sh osd-recovery-scrub.sh  osd-scrub-distrust.sh  osd-scrub-repair.sh  osd-scrub-snaps.sh  osd-scrub-test.sh  osd-unexpected-clone.sh
...
6 TESTS PASSED

**Comment by neha-ojha** [comment]
@dzafman let's add the tracker reference here, otherwise looks good!

**Comment by dzafman** [comment]
@neha-ojha I've usually left commit comments generated by cherry-pick alone.  But can't think of a real reason for it.  Do I use the tracker for the original or backport tracker?  Would I add the tracker if the source commit already referenced the original tracker?

**Comment by neha-ojha** [comment]
@dzafman Just adding a reference to https://tracker.ceph.com/issues/36419 in this PR(as a comment) will be useful, I think.

**Comment by yuriw** [comment]
[wip-yuri5-testing-2018-10-19-1535-luminous](https://trello.com/c/D2nF3EqQ/446-wip-yuri5-testing-2018-10-19-1535-luminous)

**Pull request merged**
