### PR TITLE
crush: linear buckets, pool seeds

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
added a simple test.

realized we need to factor in r (at a minimum) but may want to factor in others.  encoding coefficients into the bucket will i think provide the parameterization i was originally aiming for... see top patch. but it still neds to encode/decode and compile/decompile.

**Comment by markhpc** [comment]
Sage: Happy to see pool seeds!  I still think reseeding bad initial distirbutions is a super cheap win for a lot of users (even if it doesn't carry over when the topology changes).

**Comment by dachary** [comment]
@yukohe would you have time to open another pull request after rebasing these commits against the current master ?

**Comment by Jian-Zhang** [comment]
Loic, I will followup this. yukohe has left our team.

**Comment by dachary** [comment]
@Jian-Zhang ah, thanks for the update :-) You will need to re-open a pull request under your name, therefore I'm closing this one.

**Pull request closed without merging**
