### PR TITLE
doc/mgr: name data source in "Man Install & Config"

### PR DESCRIPTION
**Pull request by zdover23**
This PR specifies that the data source must be set to
be "Dashboard1" when you configure Grafana and Prometheus
manually.

This is a fixup of another PR which was created by Dr
Jake Grimmett. This is that PR:

Credit goes to Dr Jake Grimmett of Cambridge.

https://github.com/ceph/ceph/pull/44150/

Signed-off-by: Zac Dover <zac.dover@gmail.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [x] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [x] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by ljflores — APPROVED** [review]
Stylistically, it looks okay to me. Although a +1 from someone like @pcuzner would be ideal to confirm the accuracy.

**Comment by zdover23** [comment]
Jenkins retest this please

**Review by alfonsomthd — APPROVED** [review]

**Comment by ljflores** [comment]
jenkins test dashboard cephadm

**Comment by ljflores** [comment]
@pcuzner does this change look okay to you?

**Comment by zdover23** [comment]
jenkins test dashboard

**Comment by zdover23** [comment]
jenkins retest this please

**Pull request merged**
