### PR TITLE
pybind/mgr/balancer: add type annotations

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by sebastian-philipp — APPROVED** [review]
lgtm

**Comment by tchaikov** [comment]
jenkins test api

**Review by xiexingguo — APPROVED** [review]
I like it

**Comment by tchaikov** [comment]
changelog

- assign an empty list to `allow` set  if `"pool_ids`" is empty. otherwise we'd have `[""]`, and `""` cannot be converted to an `int`.

**Comment by tchaikov** [comment]
changelog

- corrected the command prefix of  `balancer eval`.

**Comment by tchaikov** [comment]
changelog

- change `mode.name` to `mode.value`.

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-02-05_14:59:08-rados-wip-kefu-testing-2021-02-05-1809-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-02-06_12:11:31-rados-wip-kefu-testing-2021-02-06-1838-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-02-07_14:19:29-rados-wip-kefu-testing-2021-02-07-2019-distro-basic-smithi/

reran the failed tests on master

- https://pulpito.ceph.com/kchai-2021-02-08_02:14:21-rados-wip-kefu2-testing-2021-02-08-0023-distro-basic-smithi/

e2e failures tracked by

- https://tracker.ceph.com/issues/49205

**Pull request merged**
