### PR TITLE
tests: drop obsolete Perl scripts

### PR DESCRIPTION
**Pull request by smithfarm**
None of these appear to be used by any tests currently in "master".

Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
```
smithfarm@wilbur:~/src/ceph/SUSE/ceph/qa> git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
smithfarm@wilbur:~/src/ceph/SUSE/ceph/qa> grep -r S3Lib .
./qa_scripts/S3Lib.pm:S3Lib.pm - Perl Module that contains the functions used by S3 test scripts for testing Rados gateway
.
./qa_scripts/S3Lib.pm:package S3Lib;
./qa_scripts/load-bucket-1000-obj.pl:use S3Lib qw(get_hostname get_user_info $rgw_user delete_user _write_log_entry _exit_result);
./qa_scripts/s3-file-test.pl:use S3Lib qw(display_ceph_os_info get_timestamp get_hostname get_user_info $rgw_user delete_user _write_log_entry _exit_result get_status);
smithfarm@wilbur:~/src/ceph/SUSE/ceph/qa> grep -r load-bucket .
smithfarm@wilbur:~/src/ceph/SUSE/ceph/qa> grep -r rgw_install_config .
./qa_scripts/rgw_install_config.pl:rgw_install_config.pl - Script to install and configure the rados gateway on client machine.
./qa_scripts/rgw_install_config.pl:        perl rgw_install_config.pl [--help]
./qa_scripts/rgw_install_config.pl:        perl rgw_install_config.pl
./qa_scripts/rgw_install_config.pl:        perl rgw_install_config.pl  --help
./qa_scripts/rgw_install_config.pl:rgw_install_config.pl takes the following arguments:
smithfarm@wilbur:~/src/ceph/SUSE/ceph/qa> grep -r s3-file-test .
./qa_scripts/s3-file-test.pl:s3-file-test.pl - Script to test the S3 functionality
./qa_scripts/s3-file-test.pl:        perl s3-file-test.pl <test_id> [--help]
./qa_scripts/s3-file-test.pl:        perl s3-file-test.pl <1|2|3|4|5>
./qa_scripts/s3-file-test.pl:        perl s3-file-test.pl  --help
./qa_scripts/s3-file-test.pl:s3-file-test.pl takes the following arguments:
smithfarm@wilbur:~/src/ceph/SUSE/ceph/qa> grep -r sample\.pl .
./qa_scripts/script_gen.pl:my $sample_script = "sample.pl";
smithfarm@wilbur:~/src/ceph/SUSE/ceph/qa> grep -r script_gen .
./qa_scripts/script_gen.pl:script_gen.pl - create a perl wrapper for the teuthology scripts
./qa_scripts/script_gen.pl:     perl script_gen.pl --script_name <script_name> [--help]
./qa_scripts/script_gen.pl:     perl script_gen.pl --script_name abc.pl or
./qa_scripts/script_gen.pl:     perl script_gen.pl --help
./qa_scripts/script_gen.pl:script_gen.pl takes the following arguments:
```

**Comment by smithfarm** [comment]
`[ FATAL ] /home/jenkins-build/build/workspace/ceph-pull-requests/src/googletest/googletest/include/gtest/internal/gtest-port.h:1928:: pthread_mutex_lock(&mutex_)failed with error 22`

Jenkins retest this please

**Comment by tmuthamizhan** [comment]
lgtm

**Comment by dmick** [comment]
I consider @tmuthamizhan to be the expert here; Tamil, if you're good, go ahead and approve/merge

**Pull request merged**
