### PR TITLE
jewel: ceph-disk: Racing between partition creation & device node creation

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19493

### CODE REVIEW

**Comment by smithfarm** [comment]
@ktdreyer @leseb jewel backport is here: https://github.com/ceph/ceph/pull/14329

**Comment by smithfarm** [comment]
Jenkins retest this please

**Comment by leseb** [comment]
Can we go ahead with this?
This fixes a really critical bug.

Thanks!

**Comment by smithfarm** [comment]
@leseb Yes, I will get this into 10.2.8 unless @ktdreyer can somehow get it into 10.2.7

**Comment by ktdreyer** [comment]
I do not expect to pull this into v10.2.7 at this time because we're too close to shipping, and the recent instability with Teuthology is a risk.

**Comment by smithfarm** [comment]
@dachary This passed a ceph-disk suite at http://tracker.ceph.com/issues/19538#note-9 - OK to merge after the v10.2.7 tag gets added to jewel?

**Comment by smithfarm** [comment]
@dachary Ping

**Pull request merged**
