### PR TITLE
os/bluestore/bluefs: make bluefs_preextend_wal_files default is false.

### PR DESCRIPTION
**Pull request by majianpeng**
This make rocksdb log corruption. Before fix, disable this function.

Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . My cluster always met this bug:
40148 2016-12-23 00:09:24.590117 7fed61f8aa40 10 bluefs _read h 0x56294761a600 0x50000~8000 from file(ino 20 size 0x100000 mtime 2016-12-23 00:09:13.077397 bdev 1 extents [1:0x900000+100000])
40149 2016-12-23 00:09:24.590127 7fed61f8aa40 20 bluefs _read left 0xb0000 len 0x8000
40150 2016-12-23 00:09:24.590133 7fed61f8aa40 20 bluefs _read got 32768
40151 2016-12-23 00:09:24.590138 7fed61f8aa40  3 rocksdb: db/000012.log: dropping 743 bytes; Corruption: missing start of fragmented record(2)

I add debug message in rocksb: the type of this fragment is kReclylabelasttype. So this mean rocksb enable log recycling function.

The last flush infos of ino=20 is:
2016-12-23 00:09:14.761784 7f0b1d847700 10 bluefs _flush 0x558649842500 0x4cbfa~1cd7 to file(ino 20 size 0x100000 mtime 2016-12-23 00:09:13.077397 bdev 1 extents [1:0x900000+100000])
2016-12-23 00:09:14.761791 7f0b1d847700 10 bluefs _flush_range 0x558649842500 pos 0x4cbfa 0x4cbfa~1cd7 to file(ino 20 size 0x100000 mtime 2016-12-23 00:09:13.077397 bdev 1 extents [1:0x900000+100000])
2016-12-23 00:09:14.761813 7f0b1d847700 20 bluefs _flush_range file now file(ino 20 size 0x100000 mtime 2016-12-23 00:09:13.077397 bdev 1 extents [1:0x900000+100000])

**Comment by liewegas** [comment]
Can you try wip-log-reader-writer from the ceph/rocksdb repo and 
reproduce?

**Comment by liewegas** [comment]
ca209949be3151168ecf9a3699920b140db58e3e merged manually to kraken branch

**Comment by liewegas** [comment]
Do you have a procedure for reproducing this?

**Pull request closed without merging**
