### PR TITLE
test: Adjust for Jewel quirk caused of differences with master

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by smithfarm** [comment]
@dzafman See the four failed jobs in the description of https://tracker.ceph.com/issues/23006

**Comment by dzafman** [comment]
@smithfarm  I made exclusion of '!= size 1 from shard' to cover all test sizes assuming we always truncate to size 1 in the test.  Also, added "Fixes:..."

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
retest this please

**Comment by smithfarm** [comment]
This passed a rados run at http://tracker.ceph.com/issues/21742#note-15 (with one unrelated failure)

**Pull request merged**
