### PR TITLE
tests : BACKPORT #13210 Fixed broken Makefiles after integration of ttng into rados

### PR DESCRIPTION
**Pull request by sponce**
Targetting http://tracker.ceph.com/issues/13210

### CODE REVIEW

**Comment by tchaikov** [comment]
@sponce, could you add ```Fixes: #13210``` in the commit log, instead of noting it in the title? other than this, lgtm.

a note for myself, the backported commit is part of #4166 .

**Comment by sponce** [comment]
Done

**Comment by tchaikov** [comment]
@dachary can we merge this into hammer? the change looks good to me.

**Comment by dachary** [comment]
@tchaikov ok, will do. we'll merge when v0.94.5 is out, which should be imminent

**Pull request merged**
