### PR TITLE
rgw: Fix bug that policy verify procedure. And action wrong spelling

### PR DESCRIPTION
**Pull request by C2python**
Fixes: http://tracker.ceph.com/issues/21901
There exists logical error in verify_permission function. 
For example:
  s3cmd setpolicy file s3://first 
  s3cmd info s3://first //will return access denied.
There also exists wrong spelling :
  int RGWGetCORS::verify_permission(){} 
In this function, policy evaluates "s3PutBucketCORS" action which should be s3GetBucketCORS.
Signed-off-by: Wen Zhang zhangwen1@unionpay.com

### CODE REVIEW

**Comment by C2python** [comment]
@adamemerson Could you review it? Tks~

**Comment by C2python** [comment]
@cbodley Could you help review it? Tks~

**Comment by mattbenjamin** [comment]
@adamemerson would be a good choice to review this

**Comment by C2python** [comment]
s3cmd mb s3://second
s3cmd info s3://second // Work fine!

s3cmd setpolicy example s3://second 
s3cmd info s3://second // Return 403

Debug found:
in RGWGetBucketLocation::verify_permission():
`s->iam_policy->eval() return rgw::IAM::Pass`
Then return -EACESS
Thus s3cmd info return error

I think it is not reasonable.
Could you review again? Tks~

**Comment by cbodley** [comment]
yeah, let's figure out what amazon does in this case

**Comment by adamemerson** [comment]
Amazon's documentation says:

> This DELETE operation requires the S3:DeleteBucketWebsite permission. By default, only the bucket owner can delete the website configuration attached to a bucket. However, bucket owners can grant other users permission to delete the website configuration by writing a bucket policy granting them the S3:DeleteBucketWebsite permission.

I take this to mean that in the default canned policy that comes with the bucket the owner has the authority to DELETE the website, but that there's no guarantee this is the case in all policies that could be set.

If Amazon S3 actually has the behavior you prefer, I'll be happy to change it.

**Pull request closed without merging**
