### PR TITLE
qa: test pacific to main upgrade with snap_schedule tests

### PR DESCRIPTION
**Pull request by mchangir**
PR to test pacific to main (quincy) upgrade test for snap_schedule test.

Signed-off-by: Milind Changire <mchangir@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by vshankar** [comment]
Looks like this didn't get any attention since the cephfs label wasn't applied. Thanks @ljflores for tagging reviewers.

**Comment by vshankar** [comment]
Added 16.2.15 milestone - thx @ljflores

**Review by ljflores — COMMENTED** [review]
@mchangir I'm seeing a failure that occurs during this upgrade test. PTAL when you can:

https://pulpito.ceph.com/yuriw-2024-01-22_22:03:38-upgrade:pacific-p2p-wip-yuri4-testing-2024-01-18-1257-pacific-distro-default-smithi/7527423/teuthology.log
```
2024-01-23T07:31:47.358 DEBUG:teuthology.orchestra.run.smithi137:> sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph osd down 0
2024-01-23T07:31:47.448 INFO:tasks.ceph.mon.a.smithi137.stderr:2024-01-23T07:31:47.448+0000 7feb1416fcc0 -1 recorded min_mon_release 16 (pacific) is more than two releases older than installed 19 (squid); you can only upgrade 2 releases at a time
2024-01-23T07:31:47.449 INFO:tasks.ceph.mon.a.smithi137.stderr:you should first upgrade to 17 (quincy) or 18 (reef)
2024-01-23T07:31:47.449 INFO:tasks.ceph.mon.a.smithi137.stderr:
2024-01-23T07:31:47.618 INFO:tasks.ceph.mon.a.smithi137.stderr:daemon-helper: command failed with exit status 1
2024-01-23T07:33:47.395 DEBUG:teuthology.orchestra.run:got remote process result: 124
2024-01-23T07:33:47.396 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_teuthology_c856e0f9244dd29a50697123b480d63f16a4ed81/teuthology/run_tasks.py", line 109, in run_tasks
    manager.__enter__()
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_ea310589757b987e8ba9e9ba96dfa9a6f9c1e8ec/qa/tasks/ceph.py", line 1588, in restart
    ctx.managers[cluster].mark_down_osd(id_)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_ea310589757b987e8ba9e9ba96dfa9a6f9c1e8ec/qa/tasks/ceph_manager.py", line 3063, in mark_down_osd
    self.raw_cluster_cmd('osd', 'down', str(osd))
  File "/home/teuthworker/src/github.com_ceph_ceph-c_ea310589757b987e8ba9e9ba96dfa9a6f9c1e8ec/qa/tasks/ceph_manager.py", line 1616, in raw_cluster_cmd
    p = self.run_cluster_cmd(args=args, stdout=stdout, **kwargs)
  File "/home/teuthworker/src/github.com_ceph_ceph-c_ea310589757b987e8ba9e9ba96dfa9a6f9c1e8ec/qa/tasks/ceph_manager.py", line 1609, in run_cluster_cmd
    return self.controller.run(**kwargs)
  File "/home/teuthworker/src/git.ceph.com_teuthology_c856e0f9244dd29a50697123b480d63f16a4ed81/teuthology/orchestra/remote.py", line 523, in run
    r = self._runner(client=self.ssh, name=self.shortname, **kwargs)
  File "/home/teuthworker/src/git.ceph.com_teuthology_c856e0f9244dd29a50697123b480d63f16a4ed81/teuthology/orchestra/run.py", line 455, in run
    r.wait()
  File "/home/teuthworker/src/git.ceph.com_teuthology_c856e0f9244dd29a50697123b480d63f16a4ed81/teuthology/orchestra/run.py", line 161, in wait
    self._raise_for_status()
  File "/home/teuthworker/src/git.ceph.com_teuthology_c856e0f9244dd29a50697123b480d63f16a4ed81/teuthology/orchestra/run.py", line 181, in _raise_for_status
    raise CommandFailedError(
teuthology.exceptions.CommandFailedError: Command failed on smithi137 with status 124: 'sudo adjust-ulimits ceph-coverage /home/ubuntu/cephtest/archive/coverage timeout 120 ceph --cluster ceph osd down 0'
```

Removing "needs-qa" for now, but feel free to re-add it once it's ready to be tested again.

**Comment by ljflores** [comment]
Or, @mchangir & @vshankar since Pacific is about to go EOL, perhaps we should consider closing.

**Comment by ljflores** [comment]
Closing, but it can be reopened if it's a must.

**Comment by vshankar** [comment]
> Or, @mchangir & @vshankar since Pacific is about to go EOL, perhaps we should consider closing.

Ok, yeh. Upgrading from pacific to main is disallowed. Now its good to close for pacific.

**Comment by vshankar** [comment]
@mchangir Would be want something similar for quincy and reef (upgrade to main test)?

**Pull request closed without merging**
