### PR TITLE
mon/FSCommands: Fix 'add_data_pool' command and 'fs new' command

### PR DESCRIPTION
**Pull request by ajarr**
'add_data_pool' and 'fs new' command doesn't set the application metadata 'cephfs' correctly to the filesystem's name if the pool has its application 'cephfs' already enabled.

Fixes: https://tracker.ceph.com/issues/43061
Fixes: https://tracker.ceph.com/issues/43761
Signed-off-by: Ramana Raja <rraja@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
need to add a similar fix for 'fs_new' command

**Comment by gregsfortytwo** [comment]
Hmm make check failure in the class_cas test, try rebasing? :/

**Comment by ajarr** [comment]
No code changes in the `force push`. Changed the commit message as I figured out that the 'Fix `fs new` command' commit fixes https://tracker.ceph.com/issues/43761

**Comment by gregsfortytwo** [comment]
http://pulpito.front.sepia.ceph.com/gregf-2020-04-21_21:12:13-fs-wip-greg-testing-421-1-distro-basic-smithi/ looks good; few infra bugs and known issues

**Pull request merged**
