### PR TITLE
mgr/dashboard: Added breadcrumb and tab tests to Pools menu

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Fixes: https://tracker.ceph.com/issues/37667
Signed-off-by: Nathan Weinberg <nweinber@redhat.com>

### CODE REVIEW

**Comment by s0nea** [comment]
Hey @nathan-weinberg,

LGTM, there are only three smaller linting issues in your code. That's why make check is failing.

```
diff --git a/src/pybind/mgr/dashboard/frontend/e2e/helper.po.ts b/src/pybind/mgr/dashboard/frontend/e2e/helper.po.ts
index 96302bb..7ff26b3 100644
--- a/src/pybind/mgr/dashboard/frontend/e2e/helper.po.ts
+++ b/src/pybind/mgr/dashboard/frontend/e2e/helper.po.ts
@@ -33,11 +33,12 @@ export class Helper {
   }
 
   static getTabText(idx) {
-    return $$('.nav.nav-tabs li').get(idx).getText();
+    return $$('.nav.nav-tabs li')
+      .get(idx)
+      .getText();
   }
 
   static getTabsCount() {
     return $$('.nav.nav-tabs li').count();
   }
-
 }
diff --git a/src/pybind/mgr/dashboard/frontend/e2e/pools/pools.e2e-spec.ts b/src/pybind/mgr/dashboard/frontend/e2e/pools/pools.e2e-spec.ts
index 3fa27c4..647aaa1 100644
--- a/src/pybind/mgr/dashboard/frontend/e2e/pools/pools.e2e-spec.ts
+++ b/src/pybind/mgr/dashboard/frontend/e2e/pools/pools.e2e-spec.ts
@@ -31,5 +31,4 @@ describe('Pools page', () => {
     page.navigateTo();
     expect(Helper.getTabText(1)).toEqual('Overall Performance');
   });
-
 });
```
You can fix it by running ```npm run fix:prettier```. Please check if ```npm run lint``` is successful afterwards.

**Comment by nathan-weinberg** [comment]
Made requested changes; `npm run lint` ran successfully

**Comment by callithea** [comment]
jenkins test dashboard

**Comment by s0nea** [comment]
jenkins test dashboard

**Pull request merged**
