### PR TITLE
osd: For write a non-exist erasure object don't offset > 0.

### PR DESCRIPTION
**Pull request by majianpeng**
Signed-off-by: Jianpeng Ma <jianpeng.ma@intel.com>

### CODE REVIEW

**Comment by majianpeng** [comment]
@liewegas . Have you time review this patch? Thanks

**Comment by liewegas** [comment]
appending on stripe boundaries is allowed...

**Comment by liewegas** [comment]
oh, i see.  @athanatos ... this looks like a reasonable check, unless we already work around this somewhere else?

**Comment by dachary** [comment]
See https://github.com/ceph/ceph/pull/4508 with tests added and a link to the corresponding issue.

**Pull request closed without merging**
