### PR TITLE
qa/suites: Revert "qa/suites: add mon-reweight-min-pgs-per-osd = 4"

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2017-04-17_06:07:58-rados-master---basic-mira/

**Comment by tchaikov** [comment]
we can merge this one once https://github.com/ceph/teuthology/pull/1062 gets merged.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/yuriw-2017-04-19_16:43:52-rados-wip-sage-testing-distro-basic-smithi/

i suspsect this pr; removing for now

**Comment by tchaikov** [comment]
changelog

- clear the python list using the right way (not `clear()` !)

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-04-21_03:04:04-rados-wip-kefu-testing---basic-mira/

**Pull request merged**
