### PR TITLE
Miscellaneous spec file fixes 1

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12925
http://tracker.ceph.com/issues/11732

### CODE REVIEW

**Comment by smithfarm** [comment]
@dachary, @Abhishekvrshny In this PR I have combined several spec file fixes. Hopefully this will reduce the amount of specfile merge conflicts you have to deal with.

**Comment by dachary** [comment]
@ldachary sounds like a nice idea to me :-)

**Comment by smithfarm** [comment]
Just in case anyone is wondering, we had a large number of spec file fixes in master recently. They need to be backported, but backporting them individually is problematic (merge conflicts).

**Comment by dachary** [comment]
@smithfarm clustering them into a single pull request makes a lot of sense, good idea ! You may want to update the pull request title to reflect that.

**Comment by smithfarm** [comment]
@dachary 3 remaining commits moved to #5790

**Pull request closed without merging**
