### PR TITLE
Explanation for 2nd item in CREATE A CLUSTER

### PR DESCRIPTION
**Pull request by InvisibleRain**
Signed-off-by: Valeriy Manzhos <Manzhos.VA@gmail.com>
## Checklist
- [ ] References tracker ticket
- [x] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

### CODE REVIEW

**Review by joscollin — CHANGES_REQUESTED** [review]
Please sign your commit:
https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#id1

**Comment by InvisibleRain** [comment]
jenkins test signed

**Comment by smithfarm** [comment]
@InvisibleRain Normally we don't accept direct fixes in stable branches (this PR is targeting `nautilus`) but in this case it's OK because the file being changed does not exist in `master`.

However, you will need to squash all the commits (currently three) into one. See [this article](https://help.github.com/en/articles/changing-a-commit-message) on GitHub on how to amend commits and update your pull request.

**Comment by smithfarm** [comment]
Also, please prefix the title of the commit message with `doc:`, like this:

`doc: update quick-ceph-deploy.rst to mention loopback interface`

**Comment by InvisibleRain** [comment]
Closed this in favor of https://github.com/ceph/ceph/pull/37466

**Pull request closed without merging**
