### PR TITLE
doc: quick-rbd.rst de-duplicate

### PR DESCRIPTION
**Pull request by Dmole**
Remove code duplication from the dependency.

Signed-off-by: Tim <elatllat@gmail.com>

- `jenkins test docs`
- `jenkins render docs`

### CODE REVIEW

**Comment by dillaman** [comment]
@Dmole Can you tweak the commit subject line to start with the "doc: " prefix and then add a "Signed-of-by: ..." line?

**Comment by dillaman** [comment]
@Dmole ping

**Comment by Dmole** [comment]
@dillaman Thanks for the reminder, please let me know if this PR needs anything else.

**Comment by dillaman** [comment]
jenkins test make check

**Pull request merged**
