### PR TITLE
hammer: Pool quota alarm is not in effect 

### PR DESCRIPTION
**Pull request by renhwztetecs**
http://tracker.ceph.com/issues/15478

### CODE REVIEW

**Comment by renhwztetecs** [comment]
@tchaikov 
close https://github.com/ceph/ceph/pull/8571

**Comment by smithfarm** [comment]
@tchaikov This PR is in the latest round of hammer-backports integration tests, which passed a rados run (the only failures are a valgrind false positive that has since been fixed by https://github.com/ceph/teuthology/pull/915 and http://tracker.ceph.com/issues/15139 which is an infrastructure issue with two of the tests) - for details, see: http://tracker.ceph.com/issues/15895#note-18

Do you think this PR is OK to merge?

**Comment by smithfarm** [comment]
@tchaikov This PR passed a /200 rados run on Ubuntu. None of the failures were reproducible. For details see http://tracker.ceph.com/issues/15895#note-18

Do you think it's OK to merge?

**Comment by smithfarm** [comment]
@tchaikov Ping?

**Comment by tchaikov** [comment]
@smithfarm lgtm.

**Pull request merged**
