### PR TITLE
rocksdb: Updated to v6.1.2

### PR DESCRIPTION
**Pull request by markhpc**
This updates rocksdb to v6.1.2. There are a number of fixes and improvements since 5.17.2, some notable ones that may be relevant for us:

**Bug Fixes**

- Fix handling of corrupt range tombstone blocks such that corruptions cannot cause deleted keys to reappear
- Lock free MultiGet
- Fix incorrect NotFound point lookup result when querying the endpoint of a file that has been extended by a range tombstone.
- Fix a memory leak when files with range tombstones are read in mmap mode and block cache is enabled
- Fix possible LSM corruption when both range deletions and subcompactions are used. The symptom of this corruption is L1+ files overlapping in the user key space.
- Fix in-memory range tombstone truncation to avoid erroneously covering newer keys at a lower level, and include range tombstones in compacted files whose largest key is the range tombstone's start key.
- Fixed Get correctness bug in the presence of range tombstones where merge operands covered by a range tombstone always result in NotFound.
- Fix a deadlock caused by compaction and file ingestion waiting for each other in the event of write stalls.

**New Features**

- Introduce stats history which periodically saves Statistics snapshots and added GetStatsHistory API to retrieve these snapshots.
- Add support for trace sampling.
- Enable properties block checksum verification for block-based tables.
- With level_compaction_dynamic_level_bytes = true, level multiplier may be adjusted automatically when Level 0 to 1 compaction is lagged behind.
- Add xxhash64 checksum support
- Introduced MemoryAllocator, which lets the user specify custom memory allocator for block based table.
- Improved DeleteRange to prevent read performance degradation. The feature is no longer marked as experimental.

Signed-off-by: Mark Nelson <mnelson@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by tchaikov** [comment]
@markhpc could you push the rocksdb branch to ceph-octopus instead of wip-octopus. i am afraid that branch could be overwritten or removed by accident.

**Comment by markhpc** [comment]
@kefu I was thinking the same thing at first, but I wanted to make it clear that this wasn't necessarily the final octopus branch since we might be modifying it to add Igor's upcoming SST file placement work or potentially may update rocksdb again.  Anyway, if you feel strongly I'm ok with changing it.

**Comment by tchaikov** [comment]
@markhpc how about adding a postfix, like `ceph-octopus-v5.8-1435` ? so we can create a new branch with this naming convention if we want to update rocksdb before releasing octopus?
```
ceph/src/rocksdb|(ffed5e685...)|$ git describe
v5.8-1435-gffed5e685
```

**Comment by cbodley** [comment]
> Improved DeleteRange to prevent read performance degradation. The feature is no longer marked as experimental.

that's great. can we turn on `rocksdb_enable_rmrange` by default? that could be a big improvement for omap object deletion

**Comment by markhpc** [comment]
> > Improved DeleteRange to prevent read performance degradation. The feature is no longer marked as experimental.
> 
> that's great. can we turn on `rocksdb_enable_rmrange` by default? that could be a big improvement for omap object deletion

Now would be the time to do it so we can let it bake in master for a while!

**Comment by markhpc** [comment]
retest this please

**Comment by markhpc** [comment]
retest this please

**Comment by markhpc** [comment]
This now includes the cherry-picked commit https://github.com/facebook/rocksdb/commit/18864567c8a1139d2fc83cda24587043d5beaf84 from rocksdb master that should fix the zlib compilation issue seen in stock 6.1.2.  Once 6.3.0+ is released we will likely want to switch to that.

**Comment by markhpc** [comment]
Now hitting an issue with zstd_ext that looks a lot like what was reported here: http://tracker.ceph.com/issues/19271

**Comment by tchaikov** [comment]
```
Cloning into 'ocf'...
fatal: unable to access 'https://github.com/Open-CAS/ocf.git/': The requested URL returned error: 503
fatal: clone of 'https://github.com/Open-CAS/ocf.git' into submodule path 'ocf' failed
Failed to recurse into submodule path 'src/spdk'
```

retest this please.

**Comment by markhpc** [comment]
Teuthology results: http://pulpito.ceph.com/kchai-2019-07-22_16:29:12-rados-wip-kefu-testing-2019-07-22-1948-distro-basic-mira/

**Pull request merged**
