### PR TITLE
jewel: aarch64: Compiler-based detection of crc32 extended CPU type is broken

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/17575

### CODE REVIEW

**Comment by smithfarm** [comment]
@agraf: Please review.

**Comment by smithfarm** [comment]
[Upstream aarch64 bugfix](https://trello.com/c/nQYhVAMG/2068-upstream-aarch64-bugfix)

**Comment by dachary** [comment]
@tchaikov does this backport look good to merge ? It passed the rados (http://tracker.ceph.com/issues/17487#note-19) suite except for two jobs that are, I believe unrelated. It also passed the upgrade/jewel-x and upgrade/hammer-x (http://tracker.ceph.com/issues/17487#note-22) suites.

**Comment by tchaikov** [comment]
@dachary it's good to merge.

**Pull request merged**
