### PR TITLE
qa/suites/rados: remove rook coverage from the rados suite

### PR DESCRIPTION
**Pull request by ljflores**
The rook team relies on a daily CI system to validate rook changes. It doesn't seem that the teuthology tests are maintained, so it makes sense to remove them from the rados suite.

By removing this symlink, rook test coverage will remain in the orch suite, and coverage will only be removed from the rados suite.

Workaround for: https://tracker.ceph.com/issues/58585
Signed-off-by: Laura Flores <lflores@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [x] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by ljflores** [comment]
Hey @travisn, see what you think of this PR. We've had rook tests failing for quite awhile in the rados suite, but I think your team relies on a different set of tests for rook validation.

Are these tests maintained? If not, we should consider removing them.

**Comment by travisn** [comment]
> Hey @travisn, see what you think of this PR. We've had rook tests failing for quite awhile in the rados suite, but I think your team relies on a different set of tests for rook validation.
> 
> Are these tests maintained? If not, we should consider removing them.

Correct, Rook relies on github actions in its own repo, such as the daily actions that can be seen [here](https://github.com/rook/rook/actions/workflows/daily-nightly-jobs.yml). I don't even recall who created the rook tests for teuthology, but if they are not being maintained, sounds good to remove them.

**Review by rzarzynski — APPROVED** [review]
Let's remove then.

**Comment by ljflores** [comment]
The only way to test this is to schedule a teuthology suite and check that any rook jobs have been added. I did this with rados and orch dry runs.

In rados, no more rook tests appear: https://paste.centos.org/view/5fb90a24

In orch, the rook tests are still there: https://paste.centos.org/view/8269c4c6

These can be removed from the orch suite as well, but I will leave it to cephadm folks to decide on that.

**Pull request merged**
