### PR TITLE
client: Fixes for missing consts SEEK_DATA and SEEK_HOLE on alpine linux

### PR DESCRIPTION
**Pull request by StefftheEmperor2**
client: missing const SEEK_DATA and SEEK_HOLE on ALPINE LINUX

On Alpine Linux, the non posix conform consts SEEK_HOLE and SEEK data are not present. Therefore, usages in the code must be wrapped by #ifdef blocks.

Fixes: https://tracker.ceph.com/issues/42602
Signed-off-by: Stefan Bischoff <stefan.bischoff@lw-rulez.de>

### CODE REVIEW

**Comment by batrick** [comment]
otherwise LGTM!

**Comment by jtlayton** [comment]
ACK. Changes seem fine to me too.

**Comment by batrick** [comment]
jenkins test make check

**Comment by StefftheEmperor2** [comment]
Uh, what happened now? I Opened a new pull request ..
https://github.com/ceph/ceph/pull/33104

**Comment by batrick** [comment]
> Uh, what happened now? I opened a new pull request .. for this issue
> #33104

Some kind of Github bug. I don't know...

**Pull request closed without merging**
