### PR TITLE
mgr: clean up daemon start process

### PR DESCRIPTION
**Pull request by jcsp**

### CODE REVIEW

**Comment by jcsp** [comment]
Rebased

**Comment by jcsp** [comment]
Mangled this in the rebase, updated.

**Comment by jcsp** [comment]
Rebased

**Comment by liewegas** [comment]
Five instances of this in my run:
<pre>
[WRN] Manager daemon x is unresponsive. No standby daemons available." in cluster log
</pre>
http://pulpito.ceph.com/sage-2017-07-03_15:41:59-rados-wip-sage-testing-distro-basic-smithi/

**Comment by jcsp** [comment]
Investigating the failures -- looking like this is the new logging making it more obvious that a mgr is failing, rather than a new bug.  We had issues like this with the MDS equivalent log change, where things were failing out on laggy mon clusters.

**Comment by jcsp** [comment]
Pretty sure the test failures are just MgrMonitor not handling laggy mon clusters properly: http://tracker.ceph.com/issues/20629

**Comment by jcsp** [comment]
@liewegas I think this is good to merge?

**Pull request merged**
