### PR TITLE
doc: delete duplicate empty blanks

### PR DESCRIPTION
**Pull request by daixiang0**
Delete all duplicate empty blanks in docs with below cmd:
sed -i 's/[ \t]*$//' $file

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
any input?

**Comment by daixiang0** [comment]
any input?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
@batrick hi, any input?

**Comment by daixiang0** [comment]
@batrick hi, any input?

**Comment by daixiang0** [comment]
@batrick hi, any input?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
any update? @batrick

**Comment by daixiang0** [comment]
any update? @batrick

**Comment by batrick** [comment]
Please use "doc: " as the commit message prefix. What tool did you use to find and fix these? Please include that information in the commit message.

**Comment by daixiang0** [comment]
@batrick done

**Comment by daixiang0** [comment]
@batrick mind have a look?

**Comment by tchaikov** [comment]
@daixiang0 i'd suggest avoid massive reformatting changes like this. my opinion also applies to document and code. i think, it'd be better if you could accompany the formatting changes with more significant changes like typo/syntax fixes, bug fixes, performance improvement, code cleanup/refactories or new features.

**Pull request closed without merging**
