### PR TITLE
doc/rbd: iSCSI spelling, capitalization, punctuation

### PR DESCRIPTION
**Pull request by anthonyeleven**
doc/rbd: iSCSI spelling, capitalization, punctuation 

Signed-off-by: Anthony D'Atri <anthony.datri@gmail.com>

### CODE REVIEW

**Comment by anthonyeleven** [comment]
jenkins test make check

**Comment by zdover23** [comment]
I removed an unnecessary comma. As soon as this passes the five tests, it'll be ready to merge.

**Comment by zdover23** [comment]
...and of course editing directly in the github browser window breaks the signed-off by check.

**Comment by zdover23** [comment]
Note to posterity and other Ceph admins: can we alter this behavior, so that these commits by default are signed? Can we avoid this kind of situation where a helpful, friendly edit ends up stalling a good PR?

**Comment by anthonyeleven** [comment]
How's about I update my first commit, remove yours, and enter a tracker?

**Comment by zdover23** [comment]
jenkins build docs

**Comment by anthonyeleven** [comment]
This got messy, closing and resubmitting.

**Pull request closed without merging**
