### PR TITLE
mimic: msg: challenging authorizer messages appear at debug_ms=0

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/35717

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick Full disclosure: I cherry-picked this from your luminous backport - there were no conflicts.

**Comment by batrick** [comment]
np

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-10-02-1639-mimic](https://trello.com/c/aDL8Gcgu/427-wip-yuri3-testing-2018-10-02-1639-mimic)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-10-04-2213-mimic](https://trello.com/c/SGjCogfD/436-wip-yuri3-testing-2018-10-04-2213-mimic)

**Pull request merged**
