### PR TITLE
luminous: rgw: beast frontend can listen on multiple endpoints

### PR DESCRIPTION
**Pull request by cbodley**
backport tracker http://tracker.ceph.com/issues/22937

### CODE REVIEW

**Comment by theanalyst** [comment]
when we move to boto3 hopefully these sort of things are caught already :)

**Comment by cbodley** [comment]
> when we move to boto3 hopefully these sort of things are caught already :)

are you referring to https://github.com/ceph/ceph/pull/21569? that one was caught with boto3 by @vasukulkarni

**Comment by theanalyst** [comment]
> are you referring to #21569? that one was caught with boto3 by @vasukulkarni
oops yeah, sorry I thought I was commenting on that

**Comment by tchaikov** [comment]
retest this please.

**Comment by cbodley** [comment]
jenkins test make check

**Comment by yuriw** [comment]
[wip-yuri3-testing-2018-04-30-2145-luminous](https://trello.com/c/AuFS1qjo/302-wip-yuri3-testing-2018-04-30-2145-luminous)

**Comment by yuriw** [comment]
@cbodley this PR is suspect breaking build:

[ 98%] Built target radosgw-object-expirer
[ 98%] Built target unittest_rgw_iam_policy
/home/jenkins-build/build/workspace/ceph-dev-new-build/ARCH/x86_64/AVAILABLE_ARCH/x86_64/AVAILABLE_DIST/centos7/DIST/centos7/MACHINE_SIZE/huge/release/12.2.5-20-g8863111/rpm/el7/BUILD/ceph-12.2.5-20-g8863111/src/rgw/rgw_asio_frontend.cc:241:30: error: 'string_view' is not a member of 'boost::asio'

see full log https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=huge/11309//consoleFull

**Comment by cbodley** [comment]
hmm, the jenkins 'make check' for the pr succeeded, but the log here shows that it didn't actually build the radosgw target, so it didn't catch the issue with rgw_asio_frontend.cc. 'make check' on master does build radosgw, so i'm curious what's going on here (any ideas @tchaikov?)

but on to the actual issue - looking at the boost::asio sources, they want at least gcc 4.9 for a `std::experimental::string_view`, and the build logs show 4.8.5. they provide a `BOOST_ASIO_STRING_VIEW_PARAM` define that falls back to `const std::string&`, so i've updated the commit to use that (and documented the conflict in the commit message)

**Comment by tchaikov** [comment]
@cbodley in master we have a029d20b86c7d64626baf14bf0217c142e5e17cf, but in luminous, the "tests" target does not depend on radosgw or radosgw-admin.

**Comment by cbodley** [comment]
@tchaikov oh yeah! i'll pull that into this branch

**Pull request merged**
