### PR TITLE
cephadm: use pyfakefs during test_create_daemon_dirs_prometheus

### PR DESCRIPTION
**Pull request by mgfritch**
convert test to use the `cephadm_fs` fixture

Signed-off-by: Michael Fritch <mfritch@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by mgfritch** [comment]
avoids teuthology failures such as: https://github.com/ceph/ceph/pull/42028#pullrequestreview-697767669

**Comment by mgfritch** [comment]
jenkins test make check

**Review by p-se — APPROVED** [review]
lgtm

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-07-20_13:35:25-rados:cephadm-wip-swagner-testing-2021-07-20-1243-distro-basic-smithi/

**Pull request merged**
