### PR TITLE
common: always stop timer's thread when it is suspended

### PR DESCRIPTION
**Pull request by wp389**
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

ticket:
https://tracker.ceph.com/issues/37766
signoff: wp389@126.com

### CODE REVIEW

**Comment by wp389** [comment]
ceph::timer had may had some bug.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-01-01_02:34:49-rados-wip-kefu2-testing-2019-01-01-0117-distro-basic-smithi/

the failures are caused / tracked by 

- http://tracker.ceph.com/issues/37773
- #25672

**Comment by tchaikov** [comment]
@wp389 ping

**Comment by tchaikov** [comment]
reposting this PR at #26469 to address the comment

**Pull request closed without merging**
