### PR TITLE
pacific: client: make sure only to update dir dist from auth mds

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/51977

### CODE REVIEW

**Comment by ajarr** [comment]
@batrick  could this new failure https://tracker.ceph.com/issues/52487 be related to this PR? If not, please request @yuriw to merge this PR in the trello card https://trello.com/c/2djzuDQp/1324-wip-yuri8-testing-2021-08-30-0930-pacific-old-wip-yuri8-testing-2021-08-26-1210-pacific

**Comment by batrick** [comment]
> @batrick could this new failure https://tracker.ceph.com/issues/52487 be related to this PR? If not, please request @yuriw to merge this PR by updating in the trello card https://trello.com/c/2djzuDQp/1324-wip-yuri8-testing-2021-08-30-0930-pacific-old-wip-yuri8-testing-2021-08-26-1210-pacific

No this is a different issue. The test was using the kernel client and this PR only affects libcephfs/ceph-fuse.

I think the test is broken -- I will try to fix.

**Review by yuriw — APPROVED** [review]
Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>

**Comment by ajarr** [comment]
> > @batrick could this new failure https://tracker.ceph.com/issues/52487 be related to this PR? If not, please request @yuriw to merge this PR by updating in the trello card https://trello.com/c/2djzuDQp/1324-wip-yuri8-testing-2021-08-30-0930-pacific-old-wip-yuri8-testing-2021-08-26-1210-pacific
> 
> No this is a different issue. The test was using the kernel client and this PR only affects libcephfs/ceph-fuse.
> 

Missed this :-(

> I think the test is broken -- I will try to fix.

Thanks!

**Pull request merged**
