### PR TITLE
LibRadosTwoPools[EC]PP.PromoteSnap failure

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/12015

### CODE REVIEW

**Comment by smithfarm** [comment]
I see now that 53cbd79 depends on a03f85a8e7fab296ea2df70a929a1c5e4aa0f7fb , which deprecates `ObjectIterator` in favor of `NObjectIterator`.

**Comment by smithfarm** [comment]
cherry-picked d7a8148 to expose `RadostTest::nspace`

**Comment by smithfarm** [comment]
@liewegas I have gotten quite bogged down in this attempt to backport http://tracker.ceph.com/issues/10052 and am beginning to think https://github.com/ceph/ceph/pull/2926 uses too much post-firefly stuff. What do you think?

**Comment by liewegas** [comment]
lgtm

**Comment by smithfarm** [comment]
\o/

**Pull request merged**
