### PR TITLE
mon: remove duplicated NVMeofGwMap.h

### PR DESCRIPTION
**Pull request by cbodley**
commit 8d402e31f5eaadfefe0afe909f5ad3bc5a907e18 added a duplicate copy of ceph/src/mon/NVMeofGwMap.h at ceph/NVMeofGwMap.h

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-pull-requests/143490/
https://jenkins.ceph.com/job/ceph-api/81754/
> OSError: [Errno 101] Network is unreachable

**Comment by cbodley** [comment]
jenkins test api

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
shaman builds are green: https://shaman.ceph.com/builds/ceph/wip-rm-nvmeof-header/b360419f5f0beda0236cc590e261fb9fd7bff8e1/

shouldn't need qa

**Comment by cbodley** [comment]
https://jenkins.ceph.com/job/ceph-api/81843/
> Identified problems ???

**Comment by cbodley** [comment]
jenkins test api

**Pull request merged**
