### PR TITLE
qa: the default CEPH_ASOK_DIR is asok/ now

### PR DESCRIPTION
**Pull request by lxbsz**
Or the find_admin_socket() couldn't find the correct asok path.

Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
  - [x] QA fix 
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] QA fix
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by joscollin — APPROVED** [review]

**Comment by dparmar18** [comment]
@lxbsz With currently existing dir i.e. `out/`, did it fail in any runs?

**Comment by lxbsz** [comment]
> @lxbsz With currently existing dir i.e. `out/`, did it fail in any runs?

Yeah, I got this:

```
2022-09-13 14:39:14,188.188 INFO:tasks.cephfs.fuse_mount:Found client admin socket at 
2022-09-13 14:39:14,193.193 INFO:__main__:Stopped test: test_getattr_caps (tasks.cephfs.test_misc.TestMisc) in 35.660968s
2022-09-13 14:39:14,194.194 INFO:__main__:test_getattr_caps (tasks.cephfs.test_misc.TestMisc) ... ERROR
2022-09-13 14:39:14,194.194 INFO:__main__:
2022-09-13 14:39:14,195.195 INFO:__main__:======================================================================
2022-09-13 14:39:14,195.195 INFO:__main__:ERROR: test_getattr_caps (tasks.cephfs.test_misc.TestMisc)
2022-09-13 14:39:14,195.195 INFO:__main__:----------------------------------------------------------------------
2022-09-13 14:39:14,195.195 INFO:__main__:Traceback (most recent call last):
2022-09-13 14:39:14,195.195 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/cephfs_test_case.py", line 183, in setUp
2022-09-13 14:39:14,195.195 INFO:__main__:    self.mounts[i].mount_wait()
2022-09-13 14:39:14,196.196 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/mount.py", line 453, in mount_wait
2022-09-13 14:39:14,196.196 INFO:__main__:    self.mount(**kwargs)
2022-09-13 14:39:14,196.196 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/fuse_mount.py", line 52, in mount
2022-09-13 14:39:14,196.196 INFO:__main__:    return self._mount(mntopts, check_status)
2022-09-13 14:39:14,196.196 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/fuse_mount.py", line 68, in _mount
2022-09-13 14:39:14,196.196 INFO:__main__:    retval = self._run_mount_cmd(mntopts, check_status)
2022-09-13 14:39:14,196.196 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 693, in _run_mount_cmd
2022-09-13 14:39:14,196.196 INFO:__main__:    self._set_fuse_daemon_pid(check_status)
2022-09-13 14:39:14,197.197 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 724, in _set_fuse_daemon_pid
2022-09-13 14:39:14,197.197 INFO:__main__:    sock).group(1))
2022-09-13 14:39:14,197.197 INFO:__main__:AttributeError: 'NoneType' object has no attribute 'group'
2022-09-13 14:39:14,197.197 INFO:__main__:

```

**Review by mchangir — APPROVED** [review]

**Review by dparmar18 — APPROVED** [review]

**Comment by dparmar18** [comment]
> > @lxbsz With currently existing dir i.e. `out/`, did it fail in any runs?
> 
> Yeah, I got this:
> 
> ```
> 2022-09-13 14:39:14,188.188 INFO:tasks.cephfs.fuse_mount:Found client admin socket at 
> 2022-09-13 14:39:14,193.193 INFO:__main__:Stopped test: test_getattr_caps (tasks.cephfs.test_misc.TestMisc) in 35.660968s
> 2022-09-13 14:39:14,194.194 INFO:__main__:test_getattr_caps (tasks.cephfs.test_misc.TestMisc) ... ERROR
> 2022-09-13 14:39:14,194.194 INFO:__main__:
> 2022-09-13 14:39:14,195.195 INFO:__main__:======================================================================
> 2022-09-13 14:39:14,195.195 INFO:__main__:ERROR: test_getattr_caps (tasks.cephfs.test_misc.TestMisc)
> 2022-09-13 14:39:14,195.195 INFO:__main__:----------------------------------------------------------------------
> 2022-09-13 14:39:14,195.195 INFO:__main__:Traceback (most recent call last):
> 2022-09-13 14:39:14,195.195 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/cephfs_test_case.py", line 183, in setUp
> 2022-09-13 14:39:14,195.195 INFO:__main__:    self.mounts[i].mount_wait()
> 2022-09-13 14:39:14,196.196 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/mount.py", line 453, in mount_wait
> 2022-09-13 14:39:14,196.196 INFO:__main__:    self.mount(**kwargs)
> 2022-09-13 14:39:14,196.196 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/fuse_mount.py", line 52, in mount
> 2022-09-13 14:39:14,196.196 INFO:__main__:    return self._mount(mntopts, check_status)
> 2022-09-13 14:39:14,196.196 INFO:__main__:  File "/data/ceph/qa/tasks/cephfs/fuse_mount.py", line 68, in _mount
> 2022-09-13 14:39:14,196.196 INFO:__main__:    retval = self._run_mount_cmd(mntopts, check_status)
> 2022-09-13 14:39:14,196.196 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 693, in _run_mount_cmd
> 2022-09-13 14:39:14,196.196 INFO:__main__:    self._set_fuse_daemon_pid(check_status)
> 2022-09-13 14:39:14,197.197 INFO:__main__:  File "../qa/tasks/vstart_runner.py", line 724, in _set_fuse_daemon_pid
> 2022-09-13 14:39:14,197.197 INFO:__main__:    sock).group(1))
> 2022-09-13 14:39:14,197.197 INFO:__main__:AttributeError: 'NoneType' object has no attribute 'group'
> 2022-09-13 14:39:14,197.197 INFO:__main__:
> ```

ACK

**Review by rishabh-d-dave — APPROVED** [review]
https://tracker.ceph.com/projects/cephfs/wiki/Main#10-Oct-2022

**Pull request merged**
