### PR TITLE
qa/tasks/cephfs: refactor test_volumes

### PR DESCRIPTION
**Pull request by ajarr**
... into smaller test classes. This enables breaking up the volumes yaml
into smaller yaml fragments

Fixes: https://tracker.ceph.com/issues/47160
Signed-off-by: Ramana Raja <rraja@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
Tested one of the yaml fragments, volumes-basic.yaml that ran a subset of tests in the previous test_volumes. The tests passed,
http://pulpito.front.sepia.ceph.com/rraja-2020-10-07_20:15:09-fs-wip-ajarr-shuffle-test-volumes-distro-basic-smithi/

**Review by batrick — CHANGES_REQUESTED** [review]
Suggest you reorganize the yaml fragments like so:

````
tasks/volumes/
  overrides.yaml
  %
  test/
    misc.yaml
    clone.yaml
    snapshots.yaml
    basic.yaml
````

So you can avoid copying the overrides for each yaml fragment.

**Comment by batrick** [comment]
I assume the changes to `test_volumes.py` are just code movement? Anything I should look at in particular?

**Comment by batrick** [comment]
also needs rebased

**Comment by batrick** [comment]
I will avoid merging further test_volumes.py changes so you don't need to rebase again.

**Comment by ajarr** [comment]
> also needs rebased

done

**Comment by ajarr** [comment]
> I will avoid merging further test_volumes.py changes so you don't need to rebase again.

Thanks! Rebase was tedious.

**Comment by ajarr** [comment]
> I assume the changes to `test_volumes.py` are just code movement? Anything I should look at in particular?

Yes. It's just code movement.

**Comment by ajarr** [comment]
> Suggest you reorganize the yaml fragments like so:
> 
> ```
> tasks/volumes/
>   overrides.yaml
>   %
>   test/
>     misc.yaml
>     clone.yaml
>     snapshots.yaml
>     basic.yaml
> ```
> 
> So you can avoid copying the overrides for each yaml fragment.

Done. Thanks!

**Review by rishabh-d-dave — APPROVED** [review]
Looks good good to me.

**Comment by ajarr** [comment]
https://pulpito.ceph.com/rraja-2020-10-12_11:17:10-fs-wip-ajarr-shuffle-test-volumes-2-distro-basic-smithi/

**Comment by ajarr** [comment]
> https://pulpito.ceph.com/rraja-2020-10-12_11:17:10-fs-wip-ajarr-shuffle-test-volumes-2-distro-basic-smithi/

@batrick the tests passed.

**Review by batrick — APPROVED** [review]

**Comment by batrick** [comment]
Great work!

**Pull request merged**
