### PR TITLE
build: fix compiling warnings

### PR DESCRIPTION
**Pull request by yangdongsheng**
Please check the commit message of each commit for the detail.

### CODE REVIEW

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#preparing-and-sending-patches

**Comment by yangdongsheng** [comment]
@tchalkov Okey, done.

**Comment by yangdongsheng** [comment]
Hi @tchaikov Please help to take a look. thanx

**Comment by tchaikov** [comment]
lgtm

**Comment by yangdongsheng** [comment]
Hi @tchaikov I found https://github.com/ceph/ceph/pull/8193 have addressed the unused-variable warning which I was trying to fix. Then there was a conflict to merge this branch. 

Now I have remove that commit and it's green now.

**Comment by tchaikov** [comment]
thanks for resolving the conflict!

**Pull request merged**
