### PR TITLE
add basic ceph-ansible tests

### PR DESCRIPTION
**Pull request by vasukulkarni**
basic ceph ansible tests for smoke suite

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@andrewschoen sure, this are just initial tests for the PR, we are going to add more.

**Comment by andrewschoen** [comment]
jenkins test this please

**Comment by tchaikov** [comment]
@andrewschoen and @vasukulkarni are we pending on some tests or it's good to merge this?

**Comment by vasukulkarni** [comment]
@tchaikov somehow lost track on this, going to revisit this and verify again.

**Comment by tchaikov** [comment]
@vasukulkarni thanks!

**Comment by vasukulkarni** [comment]
Other PR has added new tests and updated the task, closing.

**Pull request closed without merging**
