### PR TITLE
doc/dev: add dpdkstack doc

### PR DESCRIPTION
**Pull request by fengchunsong**
Add the description of DPDKStack development, debugging, optimization and plan.

Fixes: https://tracker.ceph.com/issues/53432
Signed-off-by: Chunsong Feng <fengchunsong@huawei.com>
Reviewed-by: luo rixin <luorixin@huawei.com>
Reviewed-by: Han Fengzhe  <hanfengzhe@hisilicon.com>

### CODE REVIEW

**Comment by fengchunsong** [comment]
@tchaikov @liu-chunmei @cyx1231st please help to review,thanks.

**Comment by fengchunsong** [comment]
@tchaikov please help to review,thanks.

**Comment by fengchunsong** [comment]
@neha-ojha please help to review, thanks

**Comment by fengchunsong** [comment]
@yuyuyu101 @tchaikov  please help to review,thanks

**Comment by fengchunsong** [comment]
@tchaikov please help to review,thanks

**Review by yuyuyu101 — APPROVED** [review]

**Comment by tchaikov** [comment]
@fengchunsong sorry for the latency, this PR just fell off my radar.

**Review by tchaikov — APPROVED** [review]
i will come up with a formatting change.

**Comment by tchaikov** [comment]
jenkins test signed

**Comment by yushu20171007** [comment]
@fengchunsong Thanks for your docment. I could run a single OSD, but there is a problem: in single node, set ms_dpdk_host_ipv4_addr of all OSDs to the same value, unable to communicate between OSDs. Is it configuration wrong?
```
[osd]
ms_type=async+dpdk
ms_async_op_threads=1
ms_dpdk_gateway_ipv4_addr=10.0.30.1
ms_dpdk_netmask_ipv4_addr=255.255.255.0
ms_dpdk_hugepages=/mnt/huge
ms_dpdk_hw_flow_control=false
ms_dpdk_lro=false
ms_dpdk_enable_tso=false
ms_dpdk_hw_queue_weight=1
ms_dpdk_memory_channel=2
ms_dpdk_debug_allow_loopback = true
ms_dpdk_coremask=0x0f

[osd.2]
ms_dpdk_host_ipv4_addr=10.0.30.111
public_addr=10.0.30.111
cluster_addr=10.0.30.111
ms_dpdk_port_id=0
ms_dpdk_devs_allowlist=--pci-whitelist=0000:19:02.0

[osd.3]
ms_dpdk_host_ipv4_addr=10.0.30.111
public_addr=10.0.30.111
cluster_addr=10.0.30.111
ms_dpdk_port_id=0
ms_dpdk_devs_allowlist=--pci-whitelist=0000:19:02.1

[osd.4]
ms_dpdk_host_ipv4_addr=10.0.30.111
public_addr=10.0.30.111
cluster_addr=10.0.30.111
ms_dpdk_port_id=0
ms_dpdk_devs_allowlist=--pci-whitelist=0000:19:02.2
```

**Comment by fengchunsong** [comment]
sorry for late reply.
The DPDK cannot use the same IP address. The MAC address of each VF is different. Multiple MAC addresses correspond to the same IP address. As a result, ARP entries may be disordered. Therefore, each OSD uses an independent VF and different IP addresses are configured.

**Pull request merged**
