### PR TITLE
Update .organizationmap

### PR DESCRIPTION
**Pull request by scienceluo**
The list of contributors to ZTE looks better if it is in alphabetical order.

Signed-off-by: Luo Kexue luo.kexue@zte.com.cn

### CODE REVIEW

**Comment by xiexingguo** [comment]
retest this please

**Comment by joscollin** [comment]
Jenkins retest this please

**Comment by xiexingguo** [comment]
retest this please

again with no lock :-(

**Comment by joscollin** [comment]
@xiexingguo It's failing all the time :-(

**Comment by xiexingguo** [comment]
> It's failing all the time :-(

yeah, the test scripts are not very stable(and maybe buggy)

**Comment by scienceluo** [comment]
retest this please

**Comment by scienceluo** [comment]
retest this please.

**Comment by scienceluo** [comment]
retest this please.

**Pull request merged**
