### PR TITLE
cmake: Remove duplicate SQLite module

### PR DESCRIPTION
**Pull request by soumyakoduri**
This PR is to remove duplicate SQLite cmake module (FindSQLITE3.cmake)

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
@soumyakoduri can you verify that dbstore still builds okay with this change? since `WITH_RADOSGW_DBSTORE` is OFF by default, the jenkins CI isn't verifying that

**Comment by soumyakoduri** [comment]
> @soumyakoduri can you verify that dbstore still builds okay with this change? since `WITH_RADOSGW_DBSTORE` is OFF by default, the jenkins CI isn't verifying that

Done. With this and the change https://github.com/ceph/ceph/pull/42574 applied, the dbstore build succeeds.

**Review by batrick — APPROVED** [review]

**Comment by guits** [comment]
@tchaikov is there anything else needed to get this one merged?

**Comment by tchaikov** [comment]
@guits i am still investigating my batch at https://pulpito.ceph.com/kchai-2021-08-04_05:19:17-rados-wip-kefu-testing-2021-08-04-1022-distro-basic-smithi/.

**Comment by guits** [comment]
@soumyakoduri @tchaikov thanks!

**Pull request merged**
