### PR TITLE
IoCtxImpl: delete C_WatchCB2 when free LingerOp

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang <haomai@xsky.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
@dillaman Hmm, do you mean delete WatchCB in rados_watch and rados_watch2? I guess it couldn't, because this cb will be used later. The main problem is we need to distinguish whether we need to delete  WatchContext when delete LingerOp, it maybe a simple boolean to indicate?

**Comment by dillaman** [comment]
Yeah, I was thinking a boolean to indict ctx2 should be deleted for the C API.

**Comment by yuyuyu101** [comment]
@dillaman target to Jewel?

**Comment by yuyuyu101** [comment]
@dillaman ping

**Comment by dillaman** [comment]
Sorry -- I was out-of-town for the past week.  Still catching up with reviews.

**Pull request merged**
