### PR TITLE
qa/rados: don't pass --max_attr_len to ceph_test_rados unconditionally

### PR DESCRIPTION
**Pull request by rzarzynski**
Fixes: https://tracker.ceph.com/issues/66321

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by athanatos** [comment]
That yaml line should be added to the seastore tests before merge.

**Review by athanatos — APPROVED** [review]

**Comment by rzarzynski** [comment]
Just to the record:

```
$ git show --name-only  45943555ea170e630218eb1ae107b606ba06f0a7
commit 45943555ea170e630218eb1ae107b606ba06f0a7
Author: Xuehan Xu <xuxuehan@qianxin.com>
Date:   Mon Mar 11 16:41:21 2024 +0800

    qa/suites/crimson-rados(-experimental): set max-attr-len to 8192 for crimson thrash
    tests
    
    Signed-off-by: Xuehan Xu <xuxuehan@qianxin.com>

qa/suites/crimson-rados-experimental/seastore/basic/tasks/readwrite.yaml
qa/suites/crimson-rados/thrash/workloads/small-objects-balanced.yaml
qa/suites/crimson-rados/thrash/workloads/small-objects-localized.yaml
qa/suites/crimson-rados/thrash/workloads/small-objects.yaml
qa/tasks/rados.py
```

**Review by xxhdx1985126 — APPROVED** [review]

**Comment by rzarzynski** [comment]
Note from bug scrub: I doubt we need a QA run over this but we'll get free one as the commit has been appended to the EC partial reads PR.

**Comment by ljflores** [comment]
@rzarzynski the thrash-old-clients tests were suffering from this bug. I scheduled a small subset of tests with your fix applied so we can get clear results:

Before: https://pulpito.ceph.com/lflores-2024-06-10_23:03:46-rados:thrash-old-clients-main-distro-default-smithi/
After: https://pulpito.ceph.com/lflores-2024-06-12_21:58:53-rados:thrash-old-clients-main-distro-default-smithi/

**Comment by ljflores** [comment]
> @rzarzynski the thrash-old-clients tests were suffering from this bug. I scheduled a small subset of tests with your fix applied so we can get clear results:
> 
> Before: https://pulpito.ceph.com/lflores-2024-06-10_23:03:46-rados:thrash-old-clients-main-distro-default-smithi/ After: https://pulpito.ceph.com/lflores-2024-06-12_21:58:53-rados:thrash-old-clients-main-distro-default-smithi/
> 
> After should be green so feel free to use these results to decide on merging your PR.

Failures unrelated, tracked by:
- https://tracker.ceph.com/issues/65824

**Pull request merged**
