### PR TITLE
test: support for OpenSUSE

### PR DESCRIPTION
**Pull request by ldachary**

### CODE REVIEW

**Comment by dachary** [comment]
@osynge ping ?

**Comment by osynge** [comment]
Pong

Will be back on line soon

Owen

**Comment by smithfarm** [comment]
@dachary: please reassign this pull request to me.

**Comment by dachary** [comment]
@smithfarm ping ?

**Comment by smithfarm** [comment]
@dachary: 8bf9383 is already in master -- see https://github.com/SUSE/ceph/commit/bdac3dc3fb189688af52f60b0b34339dd8fea251

Shouldn't it be removed from this pull request, then?

**Comment by smithfarm** [comment]
@dachary: The first patch, 8bf9383, is already in master: https://github.com/ceph/ceph/commit/bdac3dc3fb189688af52f60b0b34339dd8fea251

In that case, shouldn't it be dropped from this pull request?

**Comment by dachary** [comment]
@smithfarm hum, you're right, this somehow is a duplicate. Sorry for the noise !

**Pull request closed without merging**
