### PR TITLE
qa: add upgrade test for volume upgrade from legacy

### PR DESCRIPTION
**Pull request by batrick**
This tests that volumes created using the ceph_volume_client.py library
continue to be accessible/function via the Nautilus/Octopus ceph-mgr
volumes plugin.

Fixes: https://tracker.ceph.com/issues/42723
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
http://pulpito.ceph.com/pdonnell-2020-02-28_23:48:03-fs:upgrade:volumes-master-distro-basic-smithi/

**Comment by batrick** [comment]
Change caused: http://pulpito.ceph.com/pdonnell-2020-02-29_02:51:43-fs-wip-pdonnell-testing-20200229.001503-distro-basic-smithi/4810719/

Fix was:

````
$ git diff
diff --git a/qa/tasks/cephfs/fuse_mount.py b/qa/tasks/cephfs/fuse_mount.py
index cebbc78b0f9..d1242ef80f1 100644
--- a/qa/tasks/cephfs/fuse_mount.py
+++ b/qa/tasks/cephfs/fuse_mount.py
@@ -78,6 +78,7 @@ class FuseMount(CephFSMount):
             self.mountpoint,
         ]

+        cwd = self.test_dir
         if self.client_config.get('valgrind') is not None:
             run_cmd = misc.get_valgrind_args(
                 self.test_dir,
@@ -85,6 +86,7 @@ class FuseMount(CephFSMount):
                 run_cmd,
                 self.client_config.get('valgrind'),
             )
+            cwd = None # misc.get_valgrind_args chdir for us

         run_cmd.extend(fuse_cmd)

@@ -116,7 +118,7 @@ class FuseMount(CephFSMount):

         proc = self.client_remote.run(
             args=run_cmd,
-            cwd=self.test_dir,
+            cwd=cwd,
             logger=log.getChild('ceph-fuse.{id}'.format(id=self.client_id)),
             stdin=run.PIPE,
             wait=False,
````

Tests in flight:

http://pulpito.ceph.com/pdonnell-2020-03-03_04:28:46-fs:upgrade-master-distro-basic-smithi/

http://pulpito.ceph.com/pdonnell-2020-03-03_04:29:22-fs:verify-master-distro-basic-smithi/

**Comment by batrick** [comment]
@ajarr @vshankar please review today.

**Comment by vshankar** [comment]
> @ajarr @vshankar please review today.

ack -- on it today

**Comment by batrick** [comment]
Thanks guys!

**Pull request merged**
