### PR TITLE
reef: mgr/dashboard: get object bucket policies for a bucket

### PR DESCRIPTION
**Pull request by Pegonzal**
backport tracker: https://tracker.ceph.com/issues/63426

---

backport of https://github.com/ceph/ceph/pull/54048
parent tracker: https://tracker.ceph.com/issues/63221

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Review by avanthakkar — APPROVED** [review]

**Comment by avanthakkar** [comment]
jenkins test make check

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
unrleated make check
```
apt-get error

 Unable to correct problems, you have held broken packages.
```

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by Pegonzal** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test make check

**Pull request merged**
