### PR TITLE
client: fix fuse client can't write data due to don't have Fw capability

### PR DESCRIPTION
**Pull request by yunfeiguan**
A file's wnat caps be pAsxXsxFsxcrwb if we open a file with O_RDWR flag
and the want caps are also recorded on MDS side.The MDS will grant the
caps to client according the want and the lock state machine.But if kill
session happen in mds due to the bad network the caps of all files will
be cleared. Whereafter the network back to normal the session will be
recreated but the wanted cap of all files will be lost.So, the client can’t
acquire the caps it needed and will waiting all the time.

Fixes: http://tracker.ceph.com/issues/36072
Signed-off-by: Guan yunfei <yunfei.guan@xtaotech.com>

### CODE REVIEW

**Comment by ukernel** [comment]
why commit 6c7f7f9ad37 isn't enough

**Comment by yunfeiguan** [comment]
@ukernel I applied this patch, it can't work because the OPEN meta request can't be sent to mds.But after changing the condition if (in->is_any_caps() &&((wanted & CEPH_CAP_ANY_WR) == 0 || in->auth_cap)) to if (in->is_any_caps() &&((wanted & CEPH_CAP_ANY_WR) == 0)) it works well.So i want to know why need to judge auth_cap and can we delete it.

**Comment by yunfeiguan** [comment]
@ukernel Is caps_mds_wanted() function possible get an old wanted? If no getattr or other similar  meta request send to mds, the wanted caps recorded in client is old wanted, is it right?Thus the _renew_caps will not be sent to mds.

**Comment by ukernel** [comment]
stale session's caps should be removed by Client::_closed_mds_session(). does client receive close/reject message from the mds.

**Comment by yunfeiguan** [comment]
ok, but the cap->wanted may be updated in check_caps, and this also lead the wanted of client and mds inconsistency.

**Comment by ukernel** [comment]
check_caps can't update removed caps.

**Comment by yunfeiguan** [comment]
sorry, you are right. But should we delete the **in->auth_cap** condition in 
 if (in->is_any_caps() &&
      ((wanted & CEPH_CAP_ANY_WR) == 0 || in->auth_cap)) {
    check_caps(in, CHECK_CAPS_NODELAY);
    return 0;
  }
this may lead a endless loops because the check_caps do nothing since we has removed caps.

**Comment by yunfeiguan** [comment]
Sometimes，the client will send a getattr to mds and bring caps back.If the other client occurs getattr may trigger check_caps.So we can't guarantee client cap wanted is null because send_cap may happen,right？

**Comment by ukernel** [comment]
If caps' wanted is not null, mds should see the 'wanted'

**Comment by yunfeiguan** [comment]
ok, should we remove the in->auth_cap condition in
if (in->is_any_caps() &&
((wanted & CEPH_CAP_ANY_WR) == 0 || in->auth_cap)) {
check_caps(in, CHECK_CAPS_NODELAY);
return 0;
}
In my case(hot-standby mds),the check_caps will return directly since we has removed cap，so we can't send OPEN MetaRequest to mds which will lead a endless loop.

**Comment by ukernel** [comment]
Sorry, I don't understand. why check_caps() return directly after some caps get removed. If in->auth_cap is not null, the inode should have at least one valid cap.

**Comment by yunfeiguan** [comment]
@ukernel the in->auth_caps is NULL after do remove_caps,but it will be given a new value in add_update_cap(for example getattr will trigger it).But what we need is mds_wanted has right value instead inode have one valid cap.So when (mds_wanted & need) != need we should open the file again whatever the inode auth_cap is empty or not, right?

**Comment by ukernel** [comment]
mds_wanted is calculated by checking caps. If auth_cap is newly added, auth_cap->wanted should be zero.

**Comment by yunfeiguan** [comment]
@ukernel sorry, you are right,commit 6c7f7f9 can really solve my issue, close this pr please.

**Pull request closed without merging**
