### PR TITLE
Upadate manual add url tracker when you commit

### PR DESCRIPTION
**Pull request by lastnod**
add url tracker when you contribute
 
Fixies: #12075 
http://tracker.ceph.com/issues/12075

### CODE REVIEW

**Comment by dachary** [comment]
Could you please squash the three commits into a single one ? Also make sure the commit message follows the conventions suggested in the documentation.

**Comment by theanalyst** [comment]
Also the commit message itself has a typo `s/Upadate/Update`

**Comment by theanalyst** [comment]
scratch that.. that was just the PR title .. sorry for the noise

**Comment by dachary** [comment]
@lastnod feel free to re-open after you've squashed the commits

**Pull request closed without merging**
