### PR TITLE
DNM: jewel: rbd-mirror: clean up ImageReplayer before stopping state machine

### PR DESCRIPTION
**Pull request by dillaman**
http://tracker.ceph.com/issues/16512

### CODE REVIEW

**Comment by dachary** [comment]
conflicts with https://github.com/ceph/ceph/pull/10678

**Comment by dachary** [comment]
@dillaman could you please rebase ? https://github.com/ceph/ceph/pull/10678 has been merged, hence the conflicts.

**Comment by dillaman** [comment]
@dachary rebased

**Comment by dachary** [comment]
Compilation problem
<pre>
CXX      test/rbd_mirror/image_sync/unittest_rbd_mirror-test_mock_SyncPointPruneRequest.o
test/rbd_mirror/image_sync/test_mock_ImageCopyRequest.cc:632:7: error: redefinition of ‘class rbd::mirror::image_sync::TestMockImageSyncImageCopyRequest_EmptySnapSeqs_Test’
 TEST_F(TestMockImageSyncImageCopyRequest, EmptySnapSeqs) {
       ^
test/rbd_mirror/image_sync/test_mock_ImageCopyRequest.cc:610:7: error: previous definition of ‘class 
</pre>

**Comment by dillaman** [comment]
@dachary odd -- rebase left in commit 6a29975ca8089b0fa623c9bf51032c9e6390846f which was already included in commit 9a6bad3bd7eaa733042c0a23aaf48be4fa6f84ce. re-pushed.

**Comment by dachary** [comment]
Hey jenkins, test this please ! (bluefs crash)

**Comment by dachary** [comment]
Conflict with https://github.com/ceph/ceph/pull/10684, wait for it to be merged

**Comment by dachary** [comment]
Included in https://github.com/ceph/ceph/pull/10684

**Pull request closed without merging**
