### PR TITLE
qa/cephfs: update xfstests-dev deps for RHEL 8

### PR DESCRIPTION
**Pull request by rishabh-d-dave**
Also, this PR makes a minor change to xfstests_dev.py.

Fixes: https://tracker.ceph.com/issues/43964

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by rishabh-d-dave** [comment]
I [triggered ACLs tests](http://pulpito.ceph.com/rishabh-2020-02-20_07:22:01-fs-wip-rishabh-dummy-test-distro-basic-smithi/) using a different branch close to master, but tests weren't triggered on a RHEL 8 machine. @batrick Has teuthology configuartion been changed recently to avoid triggering tests for RHEL 8? Looks like we support RHEL 8 as per master - https://github.com/ceph/ceph/tree/master/qa/distros/supported.

**Comment by rishabh-d-dave** [comment]
The following command launched a test against Ubuntu 18.04 instead of RHEL 8 -

```
$ teuthology-suite -v -m smithi -c wip-rishabh-fs-xfstests-deps-rhel8 -s fs -p 50 --filter acls-fuse-client -d rhel -D 8.1
2020-02-20 12:49:39,335.335 INFO:teuthology.suite:Using random seed=6517
2020-02-20 12:49:39,336.336 INFO:teuthology.suite.run:kernel sha1: distro
2020-02-20 12:49:39,582.582 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:49:39,583.583 INFO:teuthology.suite.run:ceph sha1: a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:49:39,583.583 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro centos: arch=x86_64, release=centos/7, pkg_type=rpm
2020-02-20 12:49:39,584.584 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F8%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:49:39,795.795 INFO:teuthology.suite.run:ceph version: 15.1.0-786.ga1e9802 
2020-02-20 12:49:40,049.049 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/teuthology master -> a023d65375f0f80a93b5617ab0e9527aa394127f
2020-02-20 12:49:40,049.049 INFO:teuthology.suite.run:teuthology branch: master a023d65375f0f80a93b5617ab0e9527aa394127f
2020-02-20 12:49:40,282.282 DEBUG:teuthology.repo_utils:git ls-remote git://git.ceph.com/ceph-ci.git wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:49:40,510.510 DEBUG:teuthology.repo_utils:git ls-remote git://git.ceph.com/ceph-ci.git wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:49:40,510.510 INFO:teuthology.suite.run:ceph-ci branch: wip-rishabh-fs-xfstests-deps-rhel8 a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:49:40,514.514 DEBUG:teuthology.repo_utils:Setting repo remote to git://git.ceph.com/ceph-ci.git
2020-02-20 12:49:40,523.523 INFO:teuthology.repo_utils:Fetching wip-rishabh-fs-xfstests-deps-rhel8 from origin
2020-02-20 12:49:40,887.887 INFO:teuthology.repo_utils:Resetting repo at /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8 to branch origin/wip-rishabh-fs-xfstests-deps-rhel8
2020-02-20 12:49:41,014.014 DEBUG:teuthology.suite.run:Suite fs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/fs
2020-02-20 12:49:41,142.142 INFO:teuthology.suite.run:Suite fs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/fs generated 569 jobs (not yet filtered)
2020-02-20 12:49:41,170.170 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro ubuntu: arch=x86_64, release=ubuntu/14.04, pkg_type=deb
2020-02-20 12:49:41,170.170 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=ubuntu%2F18.04%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
Job scheduled with name rishabh-2020-02-20_12:49:39-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784174
2020-02-20 12:49:42,323.323 INFO:teuthology.suite.run:Scheduling fs/basic_functional/{begin.yaml clusters/1-mds-4-client-coloc.yaml conf/{client.yaml mds.yaml mon.yaml osd.yaml} mount/fuse.yaml objectstore/bluestore-bitmap.yaml overrides/{frag_enable.yaml no_client_pidfile.yaml whitelist_health.yaml whitelist_wrongly_marked_down.yaml} supported-random-distros$/{ubuntu_latest.yaml} tasks/acls-fuse-client.yaml}
Job scheduled with name rishabh-2020-02-20_12:49:39-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784175
2020-02-20 12:49:43,370.370 INFO:teuthology.suite.run:Scheduling fs/basic_functional/{begin.yaml clusters/1-mds-4-client-coloc.yaml conf/{client.yaml mds.yaml mon.yaml osd.yaml} mount/fuse.yaml objectstore/bluestore-ec-root.yaml overrides/{frag_enable.yaml no_client_pidfile.yaml whitelist_health.yaml whitelist_wrongly_marked_down.yaml} supported-random-distros$/{ubuntu_latest.yaml} tasks/acls-fuse-client.yaml}
Job scheduled with name rishabh-2020-02-20_12:49:39-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784176
2020-02-20 12:49:44,304.304 INFO:teuthology.suite.run:Suite fs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/fs scheduled 2 jobs.
2020-02-20 12:49:44,305.305 INFO:teuthology.suite.run:567/569 jobs were filtered out.
Job scheduled with name rishabh-2020-02-20_12:49:39-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784177
2020-02-20 12:49:45,136.136 INFO:teuthology.suite.run:Test results viewable at http://pulpito.front.sepia.ceph.com:80/rishabh-2020-02-20_12:49:39-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/
```
```
$ teuthology-suite -v -m smithi -c wip-rishabh-fs-xfstests-deps-rhel8 -s fs -p 50 --filter acls-fuse-client -d rhel -D 8
2020-02-20 12:50:04,229.229 INFO:teuthology.suite:Using random seed=2309
2020-02-20 12:50:04,230.230 INFO:teuthology.suite.run:kernel sha1: distro
2020-02-20 12:50:04,539.539 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:50:04,539.539 INFO:teuthology.suite.run:ceph sha1: a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:50:04,539.539 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro centos: arch=x86_64, release=centos/7, pkg_type=rpm
2020-02-20 12:50:04,540.540 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F8%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:50:04,758.758 INFO:teuthology.suite.run:ceph version: 15.1.0-786.ga1e9802
2020-02-20 12:50:05,036.036 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/teuthology master -> a023d65375f0f80a93b5617ab0e9527aa394127f
2020-02-20 12:50:05,037.037 INFO:teuthology.suite.run:teuthology branch: master a023d65375f0f80a93b5617ab0e9527aa394127f
2020-02-20 12:50:05,242.242 DEBUG:teuthology.repo_utils:git ls-remote git://git.ceph.com/ceph-ci.git wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:50:05,444.444 DEBUG:teuthology.repo_utils:git ls-remote git://git.ceph.com/ceph-ci.git wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:50:05,444.444 INFO:teuthology.suite.run:ceph-ci branch: wip-rishabh-fs-xfstests-deps-rhel8 a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 12:50:05,446.446 INFO:teuthology.repo_utils:/home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8 was just updated; assuming it is current
2020-02-20 12:50:05,447.447 INFO:teuthology.repo_utils:Resetting repo at /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8 to branch origin/wip-rishabh-fs-xfstests-deps-rhel8
2020-02-20 12:50:05,548.548 DEBUG:teuthology.suite.run:Suite fs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/fs
2020-02-20 12:50:05,687.687 INFO:teuthology.suite.run:Suite fs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/fs generated 569 jobs (not yet filtered)
2020-02-20 12:50:05,714.714 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro ubuntu: arch=x86_64, release=ubuntu/14.04, pkg_type=deb
2020-02-20 12:50:05,715.715 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=ubuntu%2F18.04%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
Job scheduled with name rishabh-2020-02-20_12:50:04-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784178
2020-02-20 12:50:06,737.737 INFO:teuthology.suite.run:Scheduling fs/basic_functional/{begin.yaml clusters/1-mds-4-client-coloc.yaml conf/{client.yaml mds.yaml mon.yaml osd.yaml} mount/fuse.yaml objectstore/bluestore-bitmap.yaml overrides/{frag_enable.yaml no_client_pidfile.yaml whitelist_health.yaml whitelist_wrongly_marked_down.yaml} supported-random-distros$/{ubuntu_latest.yaml} tasks/acls-fuse-client.yaml}
Job scheduled with name rishabh-2020-02-20_12:50:04-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784179
2020-02-20 12:50:07,564.564 INFO:teuthology.suite.run:Scheduling fs/basic_functional/{begin.yaml clusters/1-mds-4-client-coloc.yaml conf/{client.yaml mds.yaml mon.yaml osd.yaml} mount/fuse.yaml objectstore/bluestore-ec-root.yaml overrides/{frag_enable.yaml no_client_pidfile.yaml whitelist_health.yaml whitelist_wrongly_marked_down.yaml} supported-random-distros$/{ubuntu_latest.yaml} tasks/acls-fuse-client.yaml}
Job scheduled with name rishabh-2020-02-20_12:50:04-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784180
2020-02-20 12:50:08,461.461 INFO:teuthology.suite.run:Suite fs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/fs scheduled 2 jobs.
2020-02-20 12:50:08,461.461 INFO:teuthology.suite.run:567/569 jobs were filtered out.
Job scheduled with name rishabh-2020-02-20_12:50:04-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784181
2020-02-20 12:50:09,312.312 INFO:teuthology.suite.run:Test results viewable at http://pulpito.front.sepia.ceph.com:80/rishabh-2020-02-20_12:50:04-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/
```

I suppose this must be an issue with some configuration file in qa/suites.

Looks like an issue with teuthology since, the configuration in qa/suites looks OK - https://github.com/rishabh-d-dave/ceph/blob/fs-xfstests-deps-rhel8/qa/distros/all/rhel_8.0.yaml

**Comment by rishabh-d-dave** [comment]
It was quite the opposite for kclient tests, I passed distro and distro versin as RHEL and 8 respectively and I got tests for all possible distros.

```
(venv-teuth) rishabh@teuthology:~$ teuthology-suite -v -m smithi -c wip-rishabh-fs-xfstests-deps-rhel8 -s kcephfs -p 50 --filter acls-kernel-client -d rhel -D 8
2020-02-20 13:39:42,349.349 INFO:teuthology.suite:Using random seed=355
2020-02-20 13:39:42,350.350 INFO:teuthology.suite.run:kernel sha1: distro
2020-02-20 13:39:42,645.645 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/ceph-ci wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:42,645.645 INFO:teuthology.suite.run:ceph sha1: a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:42,645.645 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro centos: arch=x86_64, release=centos/7, pkg_type=rpm
2020-02-20 13:39:42,646.646 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F8%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:42,865.865 INFO:teuthology.suite.run:ceph version: 15.1.0-786.ga1e9802
2020-02-20 13:39:43,131.131 DEBUG:teuthology.repo_utils:git ls-remote https://github.com/ceph/teuthology master -> a023d65375f0f80a93b5617ab0e9527aa394127f
2020-02-20 13:39:43,132.132 INFO:teuthology.suite.run:teuthology branch: master a023d65375f0f80a93b5617ab0e9527aa394127f
2020-02-20 13:39:43,330.330 DEBUG:teuthology.repo_utils:git ls-remote git://git.ceph.com/ceph-ci.git wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:43,531.531 DEBUG:teuthology.repo_utils:git ls-remote git://git.ceph.com/ceph-ci.git wip-rishabh-fs-xfstests-deps-rhel8 -> a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:43,532.532 INFO:teuthology.suite.run:ceph-ci branch: wip-rishabh-fs-xfstests-deps-rhel8 a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:43,535.535 INFO:teuthology.repo_utils:/home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8 was just updated; assuming it is current
2020-02-20 13:39:43,536.536 INFO:teuthology.repo_utils:Resetting repo at /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8 to branch origin/wip-rishabh-fs-xfstests-deps-rhel8
2020-02-20 13:39:43,640.640 DEBUG:teuthology.suite.run:Suite kcephfs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/kcephfs
2020-02-20 13:39:43,823.823 INFO:teuthology.suite.run:Suite kcephfs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/kcephfs generated 765 jobs (not yet filtered)
2020-02-20 13:39:43,889.889 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro centos: arch=x86_64, release=centos/7, pkg_type=rpm
2020-02-20 13:39:43,890.890 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F8%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:44,089.089 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro ubuntu: arch=x86_64, release=ubuntu/14.04, pkg_type=deb
2020-02-20 13:39:44,089.089 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=ubuntu%2F18.04%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
2020-02-20 13:39:44,274.274 DEBUG:teuthology.suite.util:Defaults for machine_type smithi distro centos: arch=x86_64, release=centos/7, pkg_type=rpm
2020-02-20 13:39:44,274.274 DEBUG:teuthology.packaging:Querying https://shaman.ceph.com/api/search?status=ready&project=ceph&flavor=default&distros=centos%2F8%2Fx86_64&sha1=a1e98024700a75b73cc03463f32b3eb14f88ce7e
Job scheduled with name rishabh-2020-02-20_13:39:42-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784414
2020-02-20 13:39:45,875.875 INFO:teuthology.suite.run:Scheduling kcephfs/cephfs/{begin.yaml clusters/1-mds-1-client.yaml conf/{client.yaml mds.yaml mon.yaml osd.yaml} inline/no.yaml kclient/{mount.yaml overrides/{distro/stock/{k-stock.yaml rhel_8.yaml} ms-die-on-skipped.yaml}} objectstore-ec/bluestore-bitmap.yaml overrides/{frag_enable.yaml log-config.yaml osd-asserts.yaml whitelist_health.yaml whitelist_wrongly_marked_down.yaml} tasks/acls-kernel-client.yaml}
Job scheduled with name rishabh-2020-02-20_13:39:42-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784415
2020-02-20 13:39:46,808.808 INFO:teuthology.suite.run:Scheduling kcephfs/cephfs/{begin.yaml clusters/1-mds-1-client.yaml conf/{client.yaml mds.yaml mon.yaml osd.yaml} inline/no.yaml kclient/{mount.yaml overrides/{distro/testing/{flavor/ubuntu_latest.yaml k-testing.yaml} ms-die-on-skipped.yaml}} objectstore-ec/filestore-xfs.yaml overrides/{frag_enable.yaml log-config.yaml osd-asserts.yaml whitelist_health.yaml whitelist_wrongly_marked_down.yaml} tasks/acls-kernel-client.yaml}
(snipping output)


Job scheduled with name rishabh-2020-02-20_13:39:42-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784443
2020-02-20 13:40:11,403.403 INFO:teuthology.suite.run:Scheduling kcephfs/cephfs/{begin.yaml clusters/1-mds-1-client.yaml conf/{client.yaml mds.yaml mon.yaml osd.yaml} inline/yes.yaml kclient/{mount.yaml overrides/{distro/testing/{flavor/centos_latest.yaml k-testing.yaml} ms-die-on-skipped.yaml}} objectstore-ec/bluestore-comp-ec-root.yaml overrides/{frag_enable.yaml log-config.yaml osd-asserts.yaml whitelist_health.yaml whitelist_wrongly_marked_down.yaml} tasks/acls-kernel-client.yaml}
Job scheduled with name rishabh-2020-02-20_13:39:42-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784444
2020-02-20 13:40:12,196.196 INFO:teuthology.suite.run:Suite kcephfs in /home/rishabh/src/git.ceph.com_ceph-c_wip-rishabh-fs-xfstests-deps-rhel8/qa/suites/kcephfs scheduled 30 jobs.
2020-02-20 13:40:12,196.196 INFO:teuthology.suite.run:735/765 jobs were filtered out.
Job scheduled with name rishabh-2020-02-20_13:39:42-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi and ID 4784445
2020-02-20 13:40:13,064.064 INFO:teuthology.suite.run:Test results viewable at http://pulpito.front.sepia.ceph.com:80/rishabh-2020-02-20_13:39:42-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/
```

**Comment by rishabh-d-dave** [comment]
Link to tests -
http://pulpito.ceph.com/rishabh-2020-02-20_12:48:09-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/
http://pulpito.ceph.com/rishabh-2020-02-20_12:49:39-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/
http://pulpito.ceph.com/rishabh-2020-02-20_12:50:04-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/
http://pulpito.ceph.com/rishabh-2020-02-20_13:39:42-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/

**Comment by rishabh-d-dave** [comment]
Also, I tried building xfstests-dev from source on RHEL 8.1 VM; it was successful

`make` terminating successfully -
```
    [CC]    splice-test
    [CC]    fiemap-tester
    [CC]    t_stripealign
    [CC]    open_by_handle
    [CC]    fssum
Building log-writes
    [CC]    replay-log
Building perf
Building m4
Building common
Building tests
```

`make install` terminateing successfully -
```
ut 350.out 293.out 492.out 051.out 414.out 063.out 362.out 387.out 194.out 076.out 284.out 281.out 299.out 474.out 166.out 461.out 445.out 307.out 007.out 448.out 368.out 486.out 223.out 132.out 179.out 023.out 459.out 032.out 277.out 468.out 180.out 398.out 366.out 190.out 280.out 484.out 016.out 091.out 046.out 374.out 285.out 127.out 359.out 501.out 155.out 431.out 288.out 331.out 047.out 231.out 513.out 371.out 213.out 113.out 031.out 435.out 182.out 272.out 078.out 430.out 454.out 210.out 449.out 327.out 330.out 110.out 493.out 230.out 083.out 130.out 073.out 370.out 503.out 030.out 203.out 354.out 355.out 386.out 055.out 334.out 245.out 422.out /var/lib/xfstests/tests/xfs
../install-sh -o root -g root -m 755 -d /var/lib/xfstests/tests
./install-sh -o root -g root -m 755 -d /var/lib/xfstests
./install-sh -o root -g root -m 755 check /var/lib/xfstests
./install-sh -o root -g root -m 644 randomize.awk /var/lib/xfstests

```

**Comment by batrick** [comment]
> I [triggered ACLs tests](http://pulpito.ceph.com/rishabh-2020-02-20_07:22:01-fs-wip-rishabh-dummy-test-distro-basic-smithi/) using a different branch close to master, but tests weren't triggered on a RHEL 8 machine. @batrick Has teuthology configuartion been changed recently to avoid triggering tests for RHEL 8? Looks like we support RHEL 8 as per master - https://github.com/ceph/ceph/tree/master/qa/distros/supported.

See `qa/suites/fs/basic_functional/supported-random-distros$` which indicates a random distribution (the `$` in the directory name). You need to `--filter=rhel_8` if you want to only test rhel8.

**Comment by rishabh-d-dave** [comment]
> > I [triggered ACLs tests](http://pulpito.ceph.com/rishabh-2020-02-20_07:22:01-fs-wip-rishabh-dummy-test-distro-basic-smithi/) using a different branch close to master, but tests weren't triggered on a RHEL 8 machine. @batrick Has teuthology configuartion been changed recently to avoid triggering tests for RHEL 8? Looks like we support RHEL 8 as per master - https://github.com/ceph/ceph/tree/master/qa/distros/supported.
> 
> See `qa/suites/fs/basic_functional/supported-random-distros$` which indicates a random distribution (the `$` in the directory name). You need to `--filter=rhel_8` if you want to only test rhel8. Edit: and you may need to run `teuthology-suite` more than once so that rhel8 is actually randomly selected.

Is is possible to pass 2 filters? I already use ``--filter acls-fuse-client``.

**Comment by rishabh-d-dave** [comment]
http://pulpito.ceph.com/rishabh-2020-02-20_17:56:51-kcephfs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/
http://pulpito.ceph.com/rishabh-2020-02-20_18:36:30-fs-wip-rishabh-fs-xfstests-deps-rhel8-distro-basic-smithi/

**Comment by rishabh-d-dave** [comment]
@batrick Tests for RHEL 8 passed.

**Pull request merged**
