### PR TITLE
Wip cephfs snap1

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by liewegas** [comment]
several failures from the fs suite.  not sure if the baseline is clean?
ubuntu@teuthology:/var/lib/teuthworker/archive/sage-2015-01-23_06:29:48-fs-wip-cephfs-snap1-distro-basic-multi

**Comment by gregsfortytwo** [comment]
Baseline isn't quite clean. The ones that look old to me are: 718950, 718945, 718918, 718939

718964, 718953, 718923, 718942, 718934, and 718915 are failed osd dump commands? Check them out, but probably nothing interesting to us.

New or unrecognized are 718952 and 718920 (filelock_interrupt.py) and the two hangs.

**Comment by liewegas** [comment]
> 718964, 718953, 718923, 718942, 718934, and 718915 are failed osd dump commands? Check them out, but probably nothing
> interesting to us.

malformed test...

tasks:
- chef: null
- clock.check: null
- mds_thrash: null
- install: null
- ceph: null
- ceph-fuse: null
- workunit:
    clients:
      all:
      - fs/misc/trivial_sync.sh

**Comment by liewegas** [comment]
oh, i scheduled this with sam's suite.py change applied, and it has a bug.  ignore these!

**Comment by ukernel** [comment]
http://pulpito.ceph.com/compare/?branch=wip-cephfs-snap1&suite=fs. the only failure is fsync_tester

**Comment by liewegas** [comment]
yay!

**Pull request merged**
