### PR TITLE
Refrain from versioning and packaging EC testing plugins

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/14756

### CODE REVIEW

**Comment by ktdreyer** [comment]
LGTM - @branto1 care to review?

**Comment by cbodley** [comment]
the cmake build is versioning these libraries as well. adding @alimaredia

**Comment by smithfarm** [comment]
If these libraries (plugins?) are used only by "make check", do they need to be packaged at all? Though this patch eliminates the RPMLINT error, it (RPMLINT) still does not like them (these libraries).

In `ceph.spec.in` they are picked up by this line:

```
%{_libdir}/ceph/erasure-code/libec_*.so*
```

**Comment by branto1** [comment]
@dachary: You appeared to have written most of the ec code. Would you care to review this?

**Comment by dachary** [comment]
@smithfarm last I checked there was no way to separate the plugins used for tests and the others. This annoyance will hopefully go away once the cmake switch is complete.

**Comment by dachary** [comment]
@branto1 this looks good to merge (it aligns the link instructions with what is found in src/erasure-code). However, as @smithfarm points out, there may be more to it.

**Comment by smithfarm** [comment]
@dachary Since these objects are only used in "make check", does it make sense to package them at all? The Fascist build policy[1] is forcing me to include them in some package. I'm not sure what to do. . . Maybe we could put them in librados2-devel (and go back to versioning them), or delete them as part of the "make install" recipe?

[1]https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch09s05s07.html

**Comment by dachary** [comment]
@smithfarm if you manage to not package them at all, it would be perfectly fine. They are only used for make check.

**Comment by smithfarm** [comment]
Automake has a `check_` prefix which ensures that the target is built only for "make check" and not installed, but so far I have not found a way to use it on these plugins.

**Comment by smithfarm** [comment]
I think I found how to use `check_LTLIBRARIES` with the erasure code tests, but `unittest_erasure_code_plugin` and `unittest_erasure_code_plugin_jerasure` are failing - needs more investigation.

**Comment by dachary** [comment]
@smithfarm last time I tried, there was no way to make it work. But it's probably worth re-visiting, thanks for doing this :)

**Comment by smithfarm** [comment]
@dachary I could not get `check_LTLIBRARIES` to work, so I took the easy way out. What do you think?

**Comment by smithfarm** [comment]
Debian build is untested.

**Comment by dachary** [comment]
@smithfarm explicitly listing the plugins in the packaging files is a source of error and increase the maintenance cost. Shipping too many plugins has not inconvenienced anyone nor created problems. I vote for not explicitly listing the plugins to be packaged.

**Comment by smithfarm** [comment]
@dachary Good idea. Done.

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

after a confirmation that the gitbuilders are happy with it.

**Comment by smithfarm** [comment]
On second thought, putting an `%exclude` list after `%{_libdir}/ceph/erasure-code/libec_*.so*` will very likely trigger https://bugs.launchpad.net/rpm/+bug/633753

**Comment by ktdreyer** [comment]
If you want to use `%exclude`, I'm fine with it. At Red Hat, Firefly is the last version that we support downstream on RHEL 6.

In general when I see `%exclude` in RPM .spec files I typically think that it is masking some problem with the build system's `make install` that we should fix, but it sounds like that's only going to be feasible after a switch to cmake is complete.

**Comment by ktdreyer** [comment]
Let's merge this as-is without `%exclude` for now.

**Comment by ktdreyer** [comment]
When this has passed the gitbuilders... `Reviewed-by: Ken Dreyer <kdreyer@redhat.com>`

**Comment by smithfarm** [comment]
@ktdreyer No, in this case I don't want to use `%exclude`. Thanks!

**Comment by branto1** [comment]
This might be fixable with autotools (needs more testing, though):

https://github.com/ceph/ceph/pull/7755

**Comment by smithfarm** [comment]
@branto1 Already tried that approach here: https://github.com/SUSE/ceph/commit/081bf1b69078f68f3eae8ffe2b26b5b37db7dc6f

It didn't work for me - YMMV?

**Comment by branto1** [comment]
@smithfarm: Hmm, weird, in what way did it not work? It built just fine in koji (I did not explicitly whitelist the libec_ libraries but if you examine the ceph rpm, none of the check_LTLIBRARIES is being built):

http://koji.fedoraproject.org/koji/taskinfo?taskID=13102763

**Comment by smithfarm** [comment]
@branto1 Do the Koji builds do "make check"? In OBS it built as well, but "run-make-check.sh" did not pass. You can also try cherry-picking 19391b7 into your PR #7755 and see what the make check bot says.

**Comment by smithfarm** [comment]
@branto1 I don't remember exactly - I believe the EC checks failed because they couldn't find the plugins. My working hypothesis was that `check_LTLIBRARIES` installs the plugins somewhere else.

**Comment by branto1** [comment]
@smithfarm: Nope, it won't run the make check unless there is the %check phase that tells it to do so (which is off by default). I created that PR to see what jenkins has to say about the patch. At first [1] it failed because of the 'Argument list too long' bug so I've just cherry-picked the Kefu's patch to see if that helps pass the jenkins. The second time it failed because of the wrong dir. The current approach that fixes the location of the check libs seems to work just fine (I did not fully test the packaging part, yet), see the jenkins output:

https://jenkins.ceph.com/job/ceph-pull-requests/1994/console

**Comment by branto1** [comment]
There was some progress on this (the other PR) but the build still fails (although with a different error and only one test instead of four that failed previously). However, in the meantime, we can probably merge this (I don't deal with the versioning there anyway) and I will try to fix this in auto-tools in the other PR. You can consider this

`Reviewed-by: Boris Ranto <branto@redhat.com>`

**Pull request merged**
