### PR TITLE
pacific: cephadm: September batch 1

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Backport of #42535, #42682, #42252, #42293, #42816, #42589, #42590, #42592, #42690, #42405, #42699, #42824, #42833, #42857

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
@dsavineau We will also require https://github.com/ceph/ceph-ansible/pull/6833 in pacific as well

**Comment by sebastian-philipp** [comment]
https://pulpito.ceph.com/swagner-2021-09-07_10:07:51-rados:cephadm-wip-swagner2-testing-2021-09-07-1019-pacific-distro-basic-smithi/

```
Hosts page
  when Orchestrator is available
    1) should force enter host into maintenance


0 passing (1s)
1 failing

1) Hosts page
     when Orchestrator is available
       should force enter host into maintenance:
   TypeError: Cannot read properties of undefined (reading 'forEach')
    at Context.eval (https://172.21.15.119:8443/__cypress/tests?p=cypress/integration/orchestrator/01-hosts-force-maintenance.e2e-spec.ts:>
```

**Comment by sebastian-philipp** [comment]
@nizamial09 Do you think this is related?

**Comment by nizamial09** [comment]
@sebastian-philipp Its a failure tracked using https://tracker.ceph.com/issues/51728. I am working on moving these tests out of teuthology since its more error prone over there: https://github.com/ceph/ceph/pull/42821

**Comment by sebastian-philipp** [comment]
@nizamial09 are you ok, if we merge this PR anyway?

**Comment by nizamial09** [comment]
@sebastian-philipp Yup I am okay.

**Review by nizamial09 — APPROVED** [review]

**Review by mgfritch — APPROVED** [review]

**Pull request merged**
