### PR TITLE
build: Versioning on FreeBSD needs a different map and symver

### PR DESCRIPTION
**Pull request by wjwithagen**
I found a permutation that will at least allow me to build the tree again, without changes to needed libraries during linking of executables
The MAP file is rather crude, but it seems that lld is less liberal with the way matching and the ordering of matching is done.
https://bugs.llvm.org/show_bug.cgi?id=40176
and links in this report

LLVM lld complains:
>>> ld.lld: error: undefined symbol: rados_aio_get_return_value
>>> referenced by cls_journal_client.cc:29 (/home/jenkins/workspace/ceph-master/src/cls/journal/cls_journal_client.cc:29)
>>>               cls_journal_client.cc.o:(cls::journal::client::(anonymous namespace)::C_AioExec::rados_callback(void*, void*)) in archive ../../../lib/libcls_journal_client.a
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [src/test/cls_journal/CMakeFiles/ceph_test_cls_journal.dir/build.make:129: bin/ceph_test_cls_journal] Error 1
gmake[2]: Leaving directory '/home/jenkins/workspace/ceph-master/build'
gmake[1]: *** [CMakeFiles/Makefile2:11020: src/test/cls_journal/CMakeFiles/ceph_test_cls_journal.dir/all] Error 2

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by dillaman** [comment]
@wjwithagen Any idea why including that random library fixes your issue? I don't see other cls_xyz tests pulling in that file and ```rados_aio_get_return_value``` should be exposed by ```librados```

**Comment by tchaikov** [comment]
i agree with Jason that we should not pull in rados_test_stub for this link issue. i am proposing #26580 as an alternative fix.

**Comment by wjwithagen** [comment]
@dillaman 
It was not a random lib, it is the lib where the missing function is actually declared. 
So when I looked thru most CMake files I did see quite a few places where this lib was included.
And yes, that sort of looks a bit ad-hoc at most places. But then that is quite often with tests.
So I assumed it was either an oversight or a picky loader that showed on FreeBSD.

**Comment by wjwithagen** [comment]
@tchaikov @dillaman 
I'm now with the next jenkins run also a lot of:
```
ld.lld: error: undefined symbol: rados_read
 referenced by scratchtool.c:223 (/home/jenkins/workspace/ceph-master/src/tools/scratchtool.c:223)
               CMakeFiles/ceph_scratchtool.dir/scratchtool.c.o:(testrados)

ld.lld: error: undefined symbol: rados_stat
 referenced by scratchtool.c:248 (/home/jenkins/workspace/ceph-master/src/tools/scratchtool.c:248)
               CMakeFiles/ceph_scratchtool.dir/scratchtool.c.o:(testrados)

ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [src/tools/CMakeFiles/ceph_scratchtool.dir/build.make:110: bin/ceph_scratchtool] Error 1
gmake[2]: Leaving directory '/home/jenkins/workspace/ceph-master/build'
gmake[1]: *** [CMakeFiles/Makefile2:6471: src/tools/CMakeFiles/ceph_scratchtool.dir/all] Error 2
```

So probably more reorganising is going on..../getting commited that the linker at this end does not really like. And I've tried with this PR and  #26580. (I would not expect either to fix it, but just to make sure)

**Comment by dillaman** [comment]
My guess is that your linker doesn't support the new symbol versioning exports and since the symbols are hidden by default they aren't visible in the shared library. Previously there was a bug (since Luminous and the switch the cmake) where *every* public and private symbol was exported by librados. 

We just need to know the magic words to use for your compiler/linker to change the symbol visibility to public for the API methods.

**Comment by wjwithagen** [comment]
@dillaman 
I was thinking along the same lines, and looked for it:
```
 nm ../../lib/librados.so.2.0.0 | grep rados_ioctx_snap_lookup
0000000000092bc0 t _rados_ioctx_snap_lookup
0000000000092bc0 t rados_ioctx_snap_lookup
```

Now type t is:
    `A local text symbol.`

So yes, looks a lot like you describe. Now the linker is called `ld.lld`, and stems from the LLVM project.
https://www.freebsd.org/cgi/man.cgi?ld(1) 
And the question is what did they call the option....

**Comment by wjwithagen** [comment]
@dillaman 
What do I need to do for the time being to reintroduce to old behaviour.
That will allow me to continue testing master, and not get to far behind on CI with master-code.

**Comment by dillaman** [comment]
@wjwithagen You can try to locally revert this change [1] to see if it helps in your environment.

[1] https://github.com/ceph/ceph/commit/7bf6b5ee1208a359826c74ab033e6bbbfc65969f#diff-f9953bfcd8b3d47a9298c11283efca57L88

**Comment by wjwithagen** [comment]
I wonder if Clang actually tells the world is `__GNUC__ => 4`??
```
echo 'main(){echo __GNUC__}' | cc -E -
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 346 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
main(){echo 4}
```
Right, I'll give it a shot.

**Comment by tchaikov** [comment]
it does:
```
$ clang -dM -E -x c /dev/null | grep -i gnu
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4
```

**Comment by wjwithagen** [comment]
@tchaikov Great minds think alike.... ;-)

**Comment by wjwithagen** [comment]
@dillaman 
doesn't seem to work, all refences are still unknown...
But clearing out all in `build` and starting fresh

**Comment by dillaman** [comment]
@wjwithagen I wasn't holding out too much hope that it would start working since ```nm``` showed the symbol as exported. Perhaps it's just a left-to-right library dependency order issue (i.e. ```radostest-cxx``` should be moved before ```librados``` since it depends on it)?

**Comment by wjwithagen** [comment]
@dillaman 
https://lld.llvm.org/NewLLD.html#design
According this reference, that I this afternoon `lld` keeps keeps that it already encountered for future references. And thus can `backward` fill in missing parts.  (freely summarised)
But it is quoted under: Efficient archive handeling, so millage may vary.
I'll try and variate to see if it helps.

**Comment by wjwithagen** [comment]
@dillaman 
All things I tried every time give me a librados.so with:
```
> nm librados.so | grep rados_aio_get_return_value
0000000000095b30 t _rados_aio_get_return_value
0000000000095b30 t rados_aio_get_return_value
> nm librados.so | grep rados_create
0000000000087430 t _ZL16rados_create_cctPKcP18CephInitParameters
0000000000087250 t _rados_create
00000000000874e0 t _rados_create2
000000000009c490 t _rados_create_read_op
0000000000087770 t _rados_create_with_context
000000000009aab0 t _rados_create_write_op
0000000000087250 t rados_create
00000000000874e0 t rados_create2
000000000009c490 t rados_create_read_op
0000000000087770 t rados_create_with_context
000000000009aab0 t rados_create_write_op
```

Meaning that these are local and not available for linking... (At least that is what I get from reading up)
Here they default/public available:
```
> nm librados_test_stub.a | grep rados_create
0000000000000760 T rados_create
00000000000008c0 T rados_create_with_context
```

Using another tool, objdump:
```
> objdump -t librados_test_stub.a | grep rados_create
0000000000000760 g     F .text  0000000000000026 rados_create
00000000000008c0 g     F .text  0000000000000089 rados_create_with_context
> objdump -t librados.so | grep rados_create
0000000000087430 l     F .text  00000000000000a6              _ZL16rados_create_cctPKcP18CephInitParameters
0000000000087250 l     F .text  00000000000001df              _rados_create
00000000000874e0 l     F .text  000000000000028d              _rados_create2
000000000009c490 l     F .text  00000000000000a4              _rados_create_read_op
0000000000087770 l     F .text  0000000000000085              _rados_create_with_context
000000000009aab0 l     F .text  00000000000000a4              _rados_create_write_op
00000000000874e0 l     F .text  000000000000028d              rados_create2
0000000000087250 l     F .text  00000000000001df              rados_create
000000000009c490 l     F .text  00000000000000a4              rados_create_read_op
0000000000087770 l     F .text  0000000000000085              rados_create_with_context
000000000009aab0 l     F .text  00000000000000a4              rados_create_write_op
```
l = local
g = global

confirming what seems the problem.

**Comment by wjwithagen** [comment]
mmm, tried a lot of variations.
But did not get any where.
Also posted a question on the FreeBSD toolchain ML

**Comment by tchaikov** [comment]
@wjwithagen have you considered using https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html ?

**Comment by wjwithagen** [comment]
@tchaikov 
Nope, did not know about its existance. But I'll look into it.
Asking FreeBSD MLs did not deliver much, other than more questions. 

For the time I'm excluding the problem linkings from the build. So I can get back to sort of running a 
CI buildable master. So that I do not get way behind on even more incompatability problems.

**Comment by tchaikov** [comment]
@wjwithagen i see. i wonder it might be a more portable approach. let me know if any findings. i will try to take a look at it also once i have more bandwidth.

**Comment by wjwithagen** [comment]
@tchaikov 
I'm sort of understanding how the versioning is done. The saem ASM mnemonic seems te be supported by the clang tools, so that could work.
Right now I'm looking at what is actually in the library, and how it the definition structured.
And what is the "executable" objectcode expecting to be available.
I'm using `objdump` and `nm` for that.
For now it looks that `librados.so` has the definitions but the are "local", like
```
objdump -t build/lib/librados.so | grep conf_get
0000000000088b10 l     F .text  000000000000012b              _rados_conf_get
0000000000088b10 l     F .text  000000000000012b              rados_conf_get
00000000000ec5f0 g     F .text  000000000000017b              _ZN8librados7v14_2_05Rados8conf_getEPKcRNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE
```
So looks like all stuff is in there but the linker does not resolve the 'l' flag types.
(Note that normal the last line has probably also the libversion indicator. But this was from an attempt to excluded the libcode as it was done for Apple. I thought/hoped that that would be the same for FreeBSD, but it does not help....
Once I have a clearer picture, I'll also ask feedback from the toolchain FreeBSD ML.

**Comment by wjwithagen** [comment]
@dillaman @tchaikov 
I found a permutation that will atleast allow me to build the tree again, without changes to needed libraries during linking of executables
The MAP file is rather crude, but it seems that `lld` is less liberal with the way matching and the ordering of matching is done. 
    https://bugs.llvm.org/show_bug.cgi?id=40176
    and links in this report
So this is a working map:
```
LIBRADOS_14.2.0 {
         global: *;
};
```
I understand that this is way to permisive, but for now it'll get me going again.

It still requires this change:
```
diff --git a/src/librados/librados_c.cc b/src/librados/librados_c.cc
index b8883a82e3..be971c5278 100644
--- a/src/librados/librados_c.cc
+++ b/src/librados/librados_c.cc
@@ -44,7 +44,7 @@
 #define LIBRADOS_C_API_BASE(fn)               \
   asm(".symver _" #fn "_base, " #fn "@")
 #define LIBRADOS_C_API_BASE_DEFAULT(fn)       \
-  asm(".symver _" #fn ", " #fn "@@")
+  asm(".symver _" #fn ", " #fn "@")
 #define LIBRADOS_C_API_DEFAULT(fn, ver)       \
   asm(".symver _" #fn ", " #fn "@@LIBRADOS_" #ver)
```
Which is sort of suggested by:
    https://sourceware.org/binutils/docs/ld/VERSION.html
But then again I can find almost nothing about the exact grammar for map-files, and the exact relation to the `symver` processing

**Comment by wjwithagen** [comment]
Compilation working is shown in:
  http://cephdev.digiware.nl:8180/jenkins/job/ceph-master/3096/console
Not all tests succeed, but that is likely due to *msgr*  and other changes that also need fixing.

**Comment by wjwithagen** [comment]
Closing for: https://github.com/ceph/ceph/pull/26801
Start using binutils ld

**Pull request closed without merging**
