### PR TITLE
Build: create a proper WITH_BLUESTORE option

### PR DESCRIPTION
**Pull request by asomers**
Using Bluestore is not the same thing as having libaio, especially on
non-Linux platforms.

Signed-off-by: Alan Somers <asomers@gmail.com>

### CODE REVIEW

**Comment by wjwithagen** [comment]
@asomers 
Hi Alan,

There is sort of a (unspoken) convention that the `WITH_*` options are Cmake options that translate into 
`HAVE_*` defines in the `C{++}` code.
So you might want the create a `HAVE_BLUESTORE` and use that in the .c/.h files.

**Comment by asomers** [comment]
@wjwithagen I'm not sure that convention is relevant here.  I count 44 `WITH_*` variables, but only 9 corresponding `HAVE_*` variables.  All 9 are for stuff like whether a certain library is available (`HAVE_RDMA`, `HAVE_LZ4`, etc).  Bluestore isn't an external library.  It's a configurable feature, like `WITH_RADOSGW` or `WITH_ASAN`, neither of which have `HAVE_*` variables.  So I don't think I should add a `HAVE_BLUESTORE`.

**Comment by asomers** [comment]
Rebased to resolve a conflict.

**Comment by wjwithagen** [comment]
@tchaikov 
Hi Kefu, could you take a look at this PR 
and if needed run some of the BlueStore QA on it?
Then we can merge this one and #18202

**Comment by tchaikov** [comment]
> Using Bluestore is not the same thing as having libaio, especially on non-Linux platforms.

@asomers could you expand on this a little bit? does this imply that you will enable bluestore on FreeBSD where libaio is not available?

**Comment by liewegas** [comment]
BTW longer term I think what is really needed is a portable BlockDevice implementation for *BSD that uses worker thread(s) instead of libaio.  I don't think it would particularly difficult to implement (although the performance may not be the best).

**Comment by wjwithagen** [comment]
@liewegas 
The magic word was: "longer term" :) 
I've already tested Alan's AIO code for BlueStore and it looks like it is operational.
And these are the steps leading up to getting this in.
Still have to go through all tests to reenable all the BlueStore tests I disabled.

I don't have BlockDev usage clear, perhaps Alan has. So could very well be beneficial to put that on the ToDo list.

**Comment by asomers** [comment]
@tchaikov I have indeed enabled Bluestore on FreeBSD.  If you're really curious, you can see my branch here: https://github.com/asomers/ceph/tree/bluestore_fbsd .  The key thing to remember is that there are basically two different AIO interfaces in the Unix world.  POSIX AIO is the standard, implemented by almost all OSes.  Libaio is nonstandard and is implemented only on Linux.  Linux's implementation of POSIX AIO sucks, so Linux programmers tend to forget that it exists and they go straight to libaio.  That's why FreeBSD can implement Bluestore despite not having Libaio.

OTOH, it should also be possible to build Ceph without Bluestore on a system that happens to have libaio installed.  That's a second reason for this PR.

P.S. The biggest problem with POSIX AIO is that the standard doesn't specify a high-performance way to get completion notification.  The POSIX people considered that to be beyond their remit.  Most of the BSDs do it with kqueue(2), but that is nonstandard.  I think this deficiency is part of the reason why the Linux folks wrote their own AIO interface.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2017-10-20_15:10:22-rados-wip-kefu-testing-2017-10-20-1713-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2017-10-21_00:57:41-rados-wip-kefu-testing-2017-10-20-1713-distro-basic-mira/

**Pull request merged**
