### PR TITLE
ceph-volume: Fix error calculating lv size

### PR DESCRIPTION
**Pull request by jmolmo**
fixes: https://tracker.ceph.com/issues/48383

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

- [ x ] References tracker ticket

### CODE REVIEW

**Comment by jmolmo** [comment]
After creating a new logical volume  providing a certain size, the "extens" of the logical volume are calculated in base to the size of the volume group just created. Depending of the lv size, and the vg extend size .... the result can be bigger (1 Mb) than the real space available ... then we are getting the error:

```
> /bin/podman:stderr Running command: /usr/sbin/lvcreate --yes -l 57234 -n osd-block-124ea5a7-cfe6-4db6-bf84-c0b32fea5588 ceph-ebbcc39c-ce15-4e0f-95cc-2308ec8fca42
> /bin/podman:stderr  stderr: Volume group "ceph-ebbcc39c-ce15-4e0f-95cc-2308ec8fca42" has insufficient free space (57233 extents): 57234 required.
```

**Review by rishabh-d-dave — APPROVED** [review]

**Comment by rishabh-d-dave** [comment]
@jan--f Would be good to a have test for this, right?

**Comment by rishabh-d-dave** [comment]
@jan--f Since the tracker ticket is marked as duplicate should this PR be marked as DNM until there is a PR for 47758?

**Review by jan--f — CHANGES_REQUESTED** [review]
Sorry I don't think this is the right approach. Tbh I'm not even sure why this works.
I think the bug you reported happens, if LVM for some reason aligns a PV not at 1MB but some other offset. We need to factor this offset into our size calculation. I'll push a PR shortly.

I left a request for additional debug data in https://tracker.ceph.com/issues/47758?issue_count=70&issue_position=7&next_issue_id=47966&prev_issue_id=47831#note-12. This would quickly confirm or reject my approach.

**Comment by prazumovsky** [comment]
any updates on this issue?

**Comment by jan--f** [comment]
> any updates on this issue?

Yes the preferred fix is in #38687. Waiting on a review.

**Comment by jan--f** [comment]
Superseeded by  #38687

**Pull request closed without merging**
