### PR TITLE
mon: enable 'mon osd prime pg temp' by default

### PR DESCRIPTION
**Pull request by rldleblanc**
Signed-off-by: Robert LeBlanc <robert.leblanc@endurance.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I don't think this has been tested in the nightlies at all, and it will need a ton before being enabled by default. Right @athanatos?

**Comment by liewegas** [comment]
my run failed one test with stale pgs; https://github.com/ceph/ceph-qa-suite/pull/858 will make that easier to debug.  i think the best way to get that testing and shake out any rare issues is to merge it, though; it's easy to revert if it causes trouble later.

**Comment by gregsfortytwo** [comment]
It's easier still to enable it in our nightly testing and turn it on for users when we stop seeing issues... ;)

**Comment by liewegas** [comment]
https://github.com/ceph/teuthology/pull/811

**Comment by liewegas** [comment]
No issues so far, and I'd rather it be in the -rc.

**Pull request merged**
