### PR TITLE
mgr/volumes: misc fix and feature enhancements

### PR DESCRIPTION
**Pull request by ajarr**
Fixes: https://tracker.ceph.com/issues/44020
Fixes: https://tracker.ceph.com/issues/43724
Fixes: https://tracker.ceph.com/issues/43629
Fixes: https://tracker.ceph.com/issues/43338
Fixes: https://tracker.ceph.com/issues/43271
Fixes: https://tracker.ceph.com/issues/42951

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ajarr** [comment]
Note to reviewer: I've included commits of Patrick's backport PR https://github.com/ceph/ceph/pull/33116 as the required commits of PR depend on Patrick's PR.

**Comment by ajarr** [comment]
The minor changes had to do to resolve conflicts were, 
https://github.com/ceph/ceph/pull/33122/commits/e85b76ab45c3ae2cd3885c5715e588dd1e04fddf#diff-d513197f6402f5f00e98937a6a32b093R206
https://github.com/ceph/ceph/pull/33122/commits/a8ffb0d00d9d2c2ea7e8806ba16d697e9cc5cc61#diff-29724c965f03adba0d31395b03ac724bR14

https://github.com/ceph/ceph/pull/33122/commits/a8ffb0d00d9d2c2ea7e8806ba16d697e9cc5cc61#diff-29724c965f03adba0d31395b03ac724bR40
https://github.com/ceph/ceph/pull/33122/commits/e85b76ab45c3ae2cd3885c5715e588dd1e04fddf#diff-d513197f6402f5f00e98937a6a32b093R231

**Comment by ajarr** [comment]
building here, https://shaman.ceph.com/builds/ceph/wip-ajarr-mgr-volumes-nautilus/

**Comment by ajarr** [comment]
@vshankar this passed teuthology run,
http://pulpito.ceph.com/rraja-2020-02-11_15:38:34-fs-wip-ajarr-mgr-volumes-features-py2-fix-nautilus-distro-basic-smithi/

**Comment by vshankar** [comment]
> @vshankar this passed teuthology run,
> http://pulpito.ceph.com/rraja-2020-02-11_15:38:34-fs-wip-ajarr-mgr-volumes-features-py2-fix-nautilus-distro-basic-smithi/

OK -- will take a look!

**Comment by batrick** [comment]
https://tracker.ceph.com/issues/44245?next_issue_id=42270#note-6

**Comment by smithfarm** [comment]
NOTE: Added https://tracker.ceph.com/issues/42738 to PR description.

**Pull request merged**
