### PR TITLE
grafana/Makefile: don't push to docker

### PR DESCRIPTION
**Pull request by epuertat**
And upgrade [Grafana to 8.3.5](https://github.com/grafana/grafana/releases/tag/v8.3.5) (fixes 3 Medium CVEs)

Fixes: https://tracker.ceph.com/issues/55155
Signed-off-by: Ernesto Puerta <epuertat@redhat.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by aaSharma14 — APPROVED** [review]

**Review by aaSharma14 — COMMENTED** [review]
@epuertat , I think we can change the grafana version to 8.3.5 in this PR itself as per your suggestion. I tried building with version 8.3.5 locally and it worked fine.

**Comment by epuertat** [comment]
> @epuertat , I think we can change the grafana version to 8.3.5 in this PR itself as per your suggestion. I tried building with version 8.3.5 locally and it worked fine.

Done. Thanks!

**Comment by epuertat** [comment]
jenkins test api

**Comment by epuertat** [comment]
jenkins test api

**Pull request merged**
