### PR TITLE
pacific: include/buffer: include <memory>

### PR DESCRIPTION
**Pull request by tserong**
to address following FTBFS:

/usr/bin/ccache /usr/bin/clang++-13 -DBOOST_ALL_NO_LIB -DBOOST_ASIO_DISABLE_CONCEPTS -DBOOST_ASIO_DISABLE_THREAD_KEYWORD_EXTENSION -DBOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_T$
In file included from /var/ssd/ceph/src/crimson/os/seastore/seastore_types.cc:4:
In file included from /var/ssd/ceph/src/crimson/os/seastore/seastore_types.h:14:
In file included from /var/ssd/ceph/src/include/denc.h:47:
/var/ssd/ceph/src/include/buffer.h:98:37: error: no template named 'unique_ptr' in namespace 'std'; did you mean 'boost::movelib::unique_ptr'?
struct unique_leakable_ptr : public std::unique_ptr<T, ceph::nop_delete<T>> {
                                    ^~~~~~~~~~~~~~~
                                    boost::movelib::unique_ptr
/opt/ceph/include/boost/move/unique_ptr.hpp:354:7: note: 'boost::movelib::unique_ptr' declared here
class unique_ptr
      ^

Fixes: https://tracker.ceph.com/issues/53896
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
(cherry picked from commit 7c381ba985bd1398ef7d145cc00fae9d0db510e3)

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by tserong** [comment]
jenkins test make check

**Comment by tserong** [comment]
make check failure seems unrelated:

```
Header issue in /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_string.h

C{++} Error in /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rgw/test_rgw_string.cc:37:68
```

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
> make check failure seems unrelated:
> 
> ```
> Header issue in /home/jenkins-build/build/workspace/ceph-pull-requests/src/rgw/rgw_string.h
> 
> C{++} Error in /home/jenkins-build/build/workspace/ceph-pull-requests/src/test/rgw/test_rgw_string.cc:37:68
> ```

agreed, but we might need to address it first.

**Comment by tserong** [comment]
> agreed, but we might need to address it first.

Yeah, I'm just not sure where it came from yet. Seems to also be affecting https://github.com/ceph/ceph/pull/47292

**Comment by tserong** [comment]
Alright, let's try this fix for boost 1.75 builds. Even though pacific still embeds 1.73, it looks like the `make check` build here uses system boost, which is 1.75.

**Comment by tchaikov** [comment]
@tserong hi Tim, you might need to backport 0d9eec3c4feff30ab55601533bccf9ba6e568b9f as well.

**Review by tchaikov — APPROVED** [review]

**Comment by tserong** [comment]
Thanks @tchaikov, added. I'll check back again tomorrow. I'm also running a local build here on openSUSE with the embedded boost 1.73, just in case.

**Comment by tserong** [comment]
My local openSUSE builds went fine, and `make check` worked here, so that part is all good.

Now, what's up with the API tests? There's a whole lotta `ImportError: cannot import name 'OSDMethod' from 'ceph.deployment.drive_group' (/usr/lib/python3/dist-packages/ceph/deployment/drive_group.py)` in the mgr logs...

**Comment by tserong** [comment]
That particular api tests failure has been mentioned in a few other PRs, e.g. https://github.com/ceph/ceph/pull/43597#issuecomment-1154095935 with the suspicion that in the CI, some version of ceph's python-common was installed to site packages, rather than using the version from the current source tree...?

**Comment by tserong** [comment]
jenkins test api

**Comment by tchaikov** [comment]
seems I could help in that area. Will take a look tonight.

**Comment by tserong** [comment]
Huh. I guess the api test failure is intermittent... :-/

**Comment by tchaikov** [comment]
@tserong in case you are interested, i think i root-caused the intermittent test failure. see https://github.com/ceph/ceph/pull/45133#issuecomment-1200333747

**Comment by tserong** [comment]
> @tserong in case you are interested, i think i root-caused the intermittent test failure. see [#45133 (comment)](https://github.com/ceph/ceph/pull/45133#issuecomment-1200333747)

Nice work, thanks for letting me know

**Pull request merged**
