### PR TITLE
kraken: rbd: refuse to use an ec pool that doesn't support overwrites

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/19336

### CODE REVIEW

**Comment by smithfarm** [comment]
```
[       OK ] TestLibRBD.TestIOToSnapshot (5 ms)
[ RUN      ] TestLibRBD.TestClone
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/run-rbd-unit-tests.sh: line 9: 26968 Segmentation fault      (core dumped) unittest_librbd
```

**Comment by smithfarm** [comment]
Jenkins re-test this please

**Comment by smithfarm** [comment]
Segfault in unittest_librbd  is reproducible.

**Comment by smithfarm** [comment]
@trociny This PR causes `unittest_librbd` to segfault - can you take a look?

**Comment by trociny** [comment]
@smithfarm You also need c35d307c6

**Comment by smithfarm** [comment]
@trociny That did the trick - thanks!!!

**Comment by smithfarm** [comment]
@trociny @dillaman This passed an rbd suite in http://tracker.ceph.com/issues/19009#note-66

Please review.

**Pull request merged**
