### PR TITLE
mailmap: update organization info

### PR DESCRIPTION
**Pull request by Liuchang0812**
Signed-off-by: liuchang0812 <liuchang0812@gmail.com>

### CODE REVIEW

**Comment by Liuchang0812** [comment]
@dachary review it please, thanks

**Comment by theanalyst** [comment]
needs a rebase

**Comment by Liuchang0812** [comment]
rebased and repushed

2017-04-25 16:32 GMT+08:00 Abhishek L <notifications@github.com>:

**Comment by theanalyst** [comment]
@dachary would this require a peoplemap change as well?

**Comment by dachary** [comment]
@theanalyst it's fine as it is

**Comment by theanalyst** [comment]
ack, merging

**Pull request merged**
