### PR TITLE
qa/tasks: call super class's setUp()

### PR DESCRIPTION
**Pull request by tchaikov**
to address the regression introduced by
87292811215f6ded9a784d3216a910faaef648e2

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
yeah, would have saved some typing if we can use python3.

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by callithea** [comment]
jenkins test dashboard backend

**Comment by tchaikov** [comment]
changelog

- add the missing call to more testcases. i missed them in last revision. this revision should address the failure of http://pulpito.ceph.com/kchai-2020-02-15_02:54:06-rados-wip-kefu-testing-2020-02-15-0003-distro-basic-smithi/4765194/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2020-02-15_08:08:06-rados-wip-kefu-testing-2020-02-15-1240-distro-basic-smithi/

failure fixed by #33347

**Pull request merged**
