### PR TITLE
tests: fix race condition testing auto scrub

### PR DESCRIPTION
**Pull request by dachary**
When testing auto scrub, waiting 20 seconds for the scrub to complete is
sometimes not enough and creates false negatives.

Split wait_for_scrub out of the repair helper so that it can be used to
wait for the scrub to happen instead of using a timer.

The scrub timestamp is obtained after removing the object, therefore
there is a chance for the scrub to be finished already. But since auto
scrub is scheduled every 5 seconds, it will only make the test wait an
extra 5 seconds and not hang forever.

http://tracker.ceph.com/issues/13592

Signed-off-by: Xinze Chi <xinze@xsky.com>
Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by XinzeChi** [comment]
@dachary , I am confuse that why the repair complete whenever the **get_last_scrub_stamp** function reports a timestamp different from the one stored before starting the repair. Becase the stamp is modified in PG::scrub_finish()->PG::scrub_clear_state()->PG::_update_calc_stats(). And In PG::scrub_finish(), pg just call the 
```
    queue_peering_event(
      CephPeeringEvtRef(
	new CephPeeringEvt(
	  get_osdmap()->get_epoch(),
	  get_osdmap()->get_epoch(),
	  DoRecovery())));
```
so maybe we get the modified stamp but the repair do not complete (the probability is very low. because the repair process is very fast and osd report the modify stamp is much more slow ).

Other look good to me.

**Comment by dachary** [comment]
@XinzeChi I think you're right. The scrub is indeed finished but for the purpose of auto repair we wait to wait until recovery is finished. Otherwise the file may not be present yet. I think we should
<pre>
    wait_for_clean || return 1
</pre>
right after calling ```wait_for_scrub``` so we know recovery is complete. What do you think ?

**Comment by XinzeChi** [comment]
@dachary,  lgtm

**Comment by dachary** [comment]
<pre>
loic@fold:~/software/ceph/ceph/src$ for i in $(seq 1 10) ; do echo -n . ; test/osd/osd-scrub-repair.sh TEST_auto_repair_erasure_coded > /tmp/1 2>&1 || break ; done ; echo 
..........
loic@fold:~/software/ceph/ceph/src$ echo $?
0
</pre>

**Comment by dzafman** [comment]
@dachary @XinzeChi We are moving repair out of recovery, so this will have to change at that time.

**Pull request merged**
