### PR TITLE
qa/tests: Remove ubuntu 14.04 ceph-deploy tests

### PR DESCRIPTION
**Pull request by vasukulkarni**
mgr changes that dont work on 14.04 but work on 16.04

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
Is 14.04 actually dead yet? What functionality doesn't work? I'm not sure it's appropriate to just ditch it.

**Comment by vasukulkarni** [comment]
@gregsfortytwo Its removing this test only from ceph-deploy suite not from all, ceph-mgr doesn't work on 14.04 and it is due to sysvinit issue and works with 16.04 systemd,  you can see here all 14.04 failures

http://pulpito.ceph.com/teuthology-2017-05-15_03:59:02-ceph-deploy-master-distro-basic-vps/

**Comment by gregsfortytwo** [comment]
That sounds like a larger issue we missed in our other test suites and something we need to fix, rather than something we hide. (Unless we decided to nix 14.04 support, which I guess is possible but I haven't heard that.)

**Comment by dmick** [comment]
but....14.04 uses upstart?....and surely we still support it?

**Comment by vasukulkarni** [comment]
yeah sorry that was my confusion, but those i believe are not working, I will file a tracker for the issue but would like to disable ubu 14.04 until its fixed

**Comment by vasukulkarni** [comment]
http://tracker.ceph.com/issues/19994

**Comment by vasukulkarni** [comment]
The issue has been fixed and tracker in resolved state, so closing.

**Pull request closed without merging**
