### PR TITLE
mgr/dashboard: Add Api module

### PR DESCRIPTION
**Pull request by tspmelo**
Moved all the api related services into the new module.

mgr/dashboard: Move services provision to service module
Few services were being declared in the shared module.

### CODE REVIEW

**Comment by LenzGr** [comment]
@tspmelo please rebase your changes

**Comment by tspmelo** [comment]
@LenzGr done.

**Comment by tspmelo** [comment]
jenkins retest this please

**Comment by tspmelo** [comment]
jenkins retest this please

**Pull request merged**
