### PR TITLE
Fix --dry-run for many ceph-objectstore-tool operations

### PR DESCRIPTION
**Pull request by dzafman**
Includes adding missing tests for xattr and omap
Add testing of --dry-run for most operations
Minor cleanup of rados command output

### CODE REVIEW

**Comment by tchaikov** [comment]
aside from some nits, lgtm.

**Comment by dzafman** [comment]
Made some python improvements to test code based on @tchaikov comments.

**Comment by tchaikov** [comment]
lgtm.

**Comment by dzafman** [comment]
I believe that the sage-2015-11-17_05:47:51-rados-wip-sage-testing---basic-multi run is a sufficient test.  A bunch of test never ran but all the failures were unrelated to this change.  The rados output changes would be the only thing that could cause a problem by conceivably breaking a test that depends on or checks the output.

**Pull request merged**
