### PR TITLE
qa/distros: add RHEL 8.3 and use RHEL 8.3 as default

### PR DESCRIPTION
**Pull request by rakeshgm**
Signed-off-by: rakeshgm <rakeshgm@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by batrick — APPROVED** [review]
\o/

**Comment by batrick** [comment]
@djgalloway any chance we can also get centos 8.3 images setup soon?

**Comment by yuriw** [comment]
test: http://pulpito.front.sepia.ceph.com/yuriw-2020-11-17_17:25:41-rgw-nautilus-distro-basic-smithi/

(`teuthology-suite -v --ceph-repo $CEPH_REPO --suite-repo $CEPH_REPO  -c $CEPH_BRANCH -m $MACHINE_NAME -s rgw -k $DISTRO -p 80 -e $CEPH_QA_MAIL --suite-branch rhel_8_distros -l 7 -t $TEUTH --force-priority --subset 1/1000 -n 7`)

**Comment by djgalloway** [comment]
RHEL 8.3 is available in Sepia

**Review by yuriw — APPROVED** [review]

**Comment by yuriw** [comment]
RHEL 8.3 job passed !

**Pull request merged**
