### PR TITLE
[DNM] debian reverts

### PR DESCRIPTION
**Pull request by tchaikov**
these commits were merged by mistake.

very sorry for this.

### CODE REVIEW

**Comment by tchaikov** [comment]
@mattbenjamin is rebasing his change against master. removing the the revert of  74ec4f9.

**Comment by tchaikov** [comment]
the master before revert is being tested at http://pulpito.ceph.com/kchai-2016-06-29_10:07:50-rados-master---basic-smithi/

**Comment by tchaikov** [comment]
maybe we can keep them, and fix the failures if any. only 1 failure is due to the packaging/cmake in the above rados qa run, and it is fixed by #10025.

**Comment by liewegas** [comment]
I've lost track of the status of this stuff.. not sure if this should merge or not or when?

**Comment by tchaikov** [comment]
i'd recommend not merge. let's fix the failures instead. more fixes in #10059

**Pull request closed without merging**
