### PR TITLE
jewel: tests: [  FAILED  ] TestLibRBD.ImagePollIO in upgrade:client-upgrade-kraken-distro-basic-smithi

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/18669

### CODE REVIEW

**Comment by smithfarm** [comment]
Note: this is a backport of #13076 - it is currently missing the second commit, hence DNM.

**Comment by smithfarm** [comment]
DNM can be removed if/when Jenkins passes

**Comment by smithfarm** [comment]
**Do not merge until v10.2.7 tag is added - this PR is for v10.2.8**

@dillaman This PR was included in the rbd run at http://tracker.ceph.com/issues/19538#note-11 - all tests passed except for one dead job due to an assert in ceph-objectstore-tool. The assert in `rbd/thrash/{base/install.yaml clusters/{fixed-2.yaml openstack.yaml} fs/xfs.yaml msgr-failures/few.yaml thrashers/cache.yaml workloads/rbd_fsx_nbd.yaml}` appears to be reproducible:

```
2017-04-09T01:48:49.750 INFO:teuthology.orchestra.run.smithi051:Running: 'sudo adjust-ulimits ceph-objectstore-tool --data-path /var/lib/ceph/osd/ceph-2 --journal-path /var/lib/ceph/osd/ceph-2/journal --log-file=/var/log/ceph/objectstore_tool.\\$pid.log --op export --pgid 0.7 --file /home/ubuntu/cephtest/ceph.data/exp.0.7.2'
2017-04-09T01:48:49.850 INFO:teuthology.orchestra.run.smithi051.stderr:osd/PG.cc: In function 'static int PG::peek_map_epoch(ObjectStore*, spg_t, epoch_t*, ceph::bufferlist*)' thread 7f052ae89980 time 2017-04-09 01:48:49.853858
2017-04-09T01:48:49.850 INFO:teuthology.orchestra.run.smithi051.stderr:osd/PG.cc: 2967: FAILED assert(values.size() == 2)
```

Do you think this PR is OK to merge after the v10.2.7 tag is added?

**Comment by dillaman** [comment]
@smithfarm :+1:

**Comment by smithfarm** [comment]
@jdurgin Sorry - could you click on the review, then I'll merge.

**Comment by smithfarm** [comment]
Sorry, I meant to ask @dillaman to click on the review.

**Pull request merged**
