### PR TITLE
mgr/dashboard: check .badge instead of text for expected label

### PR DESCRIPTION
**Pull request by nizamial09**
e2e got broke after this PR: https://github.com/ceph/ceph/pull/39229

Fixes: https://tracker.ceph.com/issues/49205
Signed-off-by: Nizamudeen A <nia@redhat.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Review by tchaikov — COMMENTED** [review]
@nizamial09 could you revise the commit message like
```
mgr/dashboard: check .badge instead of text for expected label

this change fixes a regression introduced by
8c5e31ec1a13bc53394eb2cb6880d74db169fac4 which broke the 01-hosts.e2e-spec.ts test
driven by test_dashboard_e2e.sh

Fixes: https://tracker.ceph.com/issues/49205
Signed-off-by: Nizamudeen A <nia@redhat.com>
```
?

**Comment by tchaikov** [comment]
being tested at https://pulpito.ceph.com/kchai-2021-02-09_04:07:10-rados:cephadm:dashboard-wip-kefu-testing-2021-02-09-1043-distro-basic-smithi/

**Comment by nizamial09** [comment]
@tchaikov Update the commit message and title.

**Review by epuertat — APPROVED** [review]
Thanks for the quick fix @nizamial09 !

**Review by aaSharma14 — APPROVED** [review]

**Comment by tchaikov** [comment]
@nizamial09 could you please rerun the failed test to verify the fix? i tried to run it twice. but both runs timed out. see my another comment in this PR.

**Comment by nizamial09** [comment]
@tchaikov I've been trying for getting the e2e done locally but I couldn't do it succefully since this requires an orchestrator e2e to be run.

**Review by avanthakkar — APPROVED** [review]

**Comment by nizamial09** [comment]
@tchaikov @epuertat Made a slight change to the PR and verified locally that the tests are passing. 
```
Hosts page
    when Orchestrator is available
      ✓ should edit host labels (8584ms)
```

**Review by tchaikov — APPROVED** [review]

**Pull request merged**
