### PR TITLE
rgw: adding documentation for AssumeRoleWithWebIdentity.

### PR DESCRIPTION
**Pull request by pritha-srivastava**
Signed-off-by: Pritha Srivastava <prsrivas@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by pritha-srivastava** [comment]
@mattbenjamin : Do I need to add the part that explains how to bring up Keycloak server and use one of its applications as an example to show how to obtain the web token to be used with AssumeRoleWithIdentity call?

**Comment by pritha-srivastava** [comment]
@mattbenjamin : I have added a page for integration with keycloak as well.

**Comment by mattbenjamin** [comment]
hi pritha;  I just had time to do a very quick scan, but my high-level impression is that it would be good to strengthen the coverage of STS and its mechanisms in general, make sure all the components that radosgw performs, and to some degree that the clients perform, are clear--in the latter case, so we can demonstrate how to use STS end-to-end.  STS coverage should be fuller than STS Lite?

**Comment by pritha-srivastava** [comment]
> hi pritha; I just had time to do a very quick scan, but my high-level impression is that it would be good to strengthen the coverage of STS and its mechanisms in general, make sure all the components that radosgw performs, and to some degree that the clients perform, are clear--in the latter case, so we can demonstrate how to use STS end-to-end. STS coverage should be fuller than STS Lite?

Ok, do suggest that STS lite should only talk about Keystone? And that I should move out all APIs under STS?

**Comment by pritha-srivastava** [comment]
> hi pritha; I just had time to do a very quick scan, but my high-level impression is that it would be good to strengthen the coverage of STS and its mechanisms in general, make sure all the components that radosgw performs, and to some degree that the clients perform, are clear--in the latter case, so we can demonstrate how to use STS end-to-end. STS coverage should be fuller than STS Lite?

Matt, can you please explain this comment?

**Comment by mattbenjamin** [comment]
Hi  Pritha,

Trying again.  I think there should be an STS.rst, that contains a good overview of what STS is, as well as links to Amazon upstream doc.  It should cover each of the different components, especially the ones we actually implement in RGW, but also client components and some simple examples of using them.  It should cover AssumeRole in general, the WebIdentity and SAML (not implemented) variants.  It should contain information on related APIs, such as policy that requires use of a temporary credential (i.e, STS) to auth (which I think you added, yes)?  It should contain a link to STSLite.rst, which should now just contain the STSLite-specific content.  My understanding is that STSLite isn't just for Keystone auth (anymore), but can in my understanding also be used to get temporary credentials with the other initial auth types--e.g., ordinary S3 auth w/AWSv4 signing, Keystone, and also LDAP.

**Comment by zdover23** [comment]
Commenting here for bookkeeping purposes.

Matt, I'll create a ticket for STS.rst and start compiling it.

**Comment by pritha-srivastava** [comment]
> Hi Pritha,
> 
> Trying again. I think there should be an STS.rst, that contains a good overview of what STS is, as well as links to Amazon upstream doc. It should cover each of the different components, especially the ones we actually implement in RGW, but also client components and some simple examples of using them. It should cover AssumeRole in general, the WebIdentity and SAML (not implemented) variants. It should contain information on related APIs, such as policy that requires use of a temporary credential (i.e, STS) to auth (which I think you added, yes)? It should contain a link to STSLite.rst, which should now just contain the STSLite-specific content. My understanding is that STSLite isn't just for Keystone auth (anymore), but can in my understanding also be used to get temporary credentials with the other initial auth types--e.g., ordinary S3 auth w/AWSv4 signing, Keystone, and also LDAP.

Thanks Matt. I understand this better. I'll attempt to make incorporate all your comments.

**Comment by pritha-srivastava** [comment]
@mattbenjamin : Matt, can you please re-review.

**Pull request merged**
