### PR TITLE
Wip pipefd leak

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by majianpeng** [comment]
Looks good for me.

**Comment by dachary** [comment]
@ukernel could you please rebase & repush to assert the timeout on make check on ubuntu is not a false negative ?

**Comment by dachary** [comment]
@ukernel definitely a false negative then. Sorry for the noise.

**Comment by ukernel** [comment]
@liewegas  how to add qa for this?

**Comment by liewegas** [comment]
@ukernel it just needs to go through a teuthology run before merge

**Pull request merged**
