### PR TITLE
[DNM CHANGES REQUESTED] nautilus: mds: reduce memory usage of open file table prefetch

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: https://tracker.ceph.com/issues/47609

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-09-28-0941-nautilus](https://trello.com/c/olfwXhZP/1023-wip-yuri4-testing-2020-09-28-0941-nautilus)

**Review by batrick — CHANGES_REQUESTED** [review]
Zheng, this PR looks to be the cause for these failures:

https://pulpito.ceph.com/yuriw-2020-10-05_22:19:12-fs-wip-yuri4-testing-2020-10-05-1246-nautilus-distro-basic-smithi/

scrape pastebin is: https://pastebin.com/Gc1d1pzZ

Can you take a look?

**Comment by ukernel** [comment]
Fixed

**Comment by ukernel** [comment]
Fixed

**Comment by yuriw** [comment]
[wip-yuri7-testing-2020-10-26-0802-nautilus](https://trello.com/c/aTkrbBpe/1046-wip-yuri7-testing-2020-10-26-0802-nautilus)

**Comment by yuriw** [comment]
[wip-yuri-testing-2020-12-15-0933-nautilus](https://trello.com/c/SHHE99CY/1088-wip-yuri-testing-2020-12-15-0933-nautilus)

**Comment by yuriw** [comment]
@ukernel I can't schedule run for this PR, can you take a look pls ?
**http://hastebin.com/oqaqawubaw**

**Comment by dvanders** [comment]
Sorry to ping, is this one stalled?

**Comment by smithfarm** [comment]
Marking DNM in the meanwhile.

**Comment by batrick** [comment]
Nautilus is EOL. We are also hearing reports this may cause issues in Octopus on the mailing list. Suggest we don't proceed further on this.

**Comment by batrick** [comment]
> > Nautilus is EOL. We are also hearing reports this may cause issues in Octopus on the mailing list. Suggest we don't proceed further on this.
> 
> @batrick No worries. Do you have a link for those issues in octopus, so we can follow up?

See "CephFS kclient gets stuck when getattr() on a certain file" on ceph-devel (not dev@ceph.io).

**Pull request closed without merging**
