### PR TITLE
hammer: mon: implement reweight-by-utilization feature

### PR DESCRIPTION
**Pull request by liewegas**
http://tracker.ceph.com/issues/15055

### CODE REVIEW

**Comment by tchaikov** [comment]
@liewegas could you cherry-pick #8024 after it gets merged ?

**Comment by dachary** [comment]
Pull requests of origin: https://github.com/ceph/ceph/pull/7890

**Comment by liewegas** [comment]
needs https://github.com/ceph/ceph/pull/8088 too

**Comment by liewegas** [comment]
should be ready to go

**Comment by dachary** [comment]
It passed the hammer upgrade suite ( http://tracker.ceph.com/issues/14692#note-52 ) and the rados suite http://tracker.ceph.com/issues/14692#note-51).

**Pull request merged**
