### PR TITLE
mgr/restful: A couple of restful fixes

### PR DESCRIPTION
**Pull request by b-ranto**
This fixes a couple of bugs in the ceph-mgr restful module.

### CODE REVIEW

**Comment by jcsp** [comment]
This PR seems like a good time to add some kind of test coverage for the modifying operations

**Comment by jcsp** [comment]
@b-ranto ping

**Comment by b-ranto** [comment]
There already are some tests for the modifying operations. However, we did not test pg_num/pgp_num updates. I have added that to the workunit testing the restful module in the latest commit.

**Comment by jcsp** [comment]
I'm a bit concerned that those tests are only going as far as checking the HTTP response from submitting a request: for example the bug behind the "restful: Set the value of the argument" fix would not be caught by this.  Something like https://github.com/ceph/calamari/blob/master/tests/test_pool_management.py#L196 would be nice.

These tests would fit nicely in qa/tasks/mgr where there is more of a framework for tests written in python.

I don't want to hold up these patches any longer, but if we're maintaining this module on an ongoing basis then I would like to see more complete tests to come with future PRs.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2017-11-28_10:23:40-rados-wip-kefu-testing-2017-11-28-1542-distro-basic-mira/

failures tracked/fixed by

- http://tracker.ceph.com/issues/22093
- http://tracker.ceph.com/issues/22043
- #19225

**Comment by tserlin** [comment]
Is there a backport for Luminous?

**Comment by tchaikov** [comment]
@tserlin #21871

**Pull request merged**
