### PR TITLE
os/bluestore: get rid off resulting lba alignment in allocators

### PR DESCRIPTION
**Pull request by ifed01**
Fixes: https://tracker.ceph.com/issues/63618
Fixes: https://tracker.ceph.com/issues/62815

Signed-off-by: Igor Fedotov <igor.fedotov@croit.io>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by YiteGu** [comment]
We no longer need 64k alignment, but could we still keep 4k alignment for every time alloc?

**Comment by markhpc** [comment]
> We no longer need 64k alignment, but could we still keep 4k alignment for every time alloc?

I had a similar thought when we were talking about this a couple of weeks ago.  I'm not sure why we want to go completely unaligned.  @ifed01 any chance you could describe your thinking here?  I never quite understood the rationale during our discussion.

**Comment by ifed01** [comment]
> > We no longer need 64k alignment, but could we still keep 4k alignment for every time alloc?
> 
> I had a similar thought when we were talking about this a couple of weeks ago. I'm not sure why we want to go completely unaligned. @ifed01 any chance you could describe your thinking here? I never quite understood the rationale during our discussion.

https://tracker.ceph.com/issues/62815 should be able to provide some clue. Here is a brief overview:
When bluefs asks for 64K continuous blob the previous implementation attempted to locate such a chunk with an LBA aligned to 64K. But avl allocator tracks free chunks in buckets depending of their sizes. I.e. there is a bucket where all 64K chunks are kept. And in this bucket they're ordered by their LBAs only. Hence to find 64K aligned chunk one has to sequentially iterate through a potentially long list of chunks which are still 64K length but doesn't match the alignment requirement. Hence the performance impact.  And actually there is no real need for that LBA's alignment requirement for now - hence the suggestion to get rid of it

**Comment by YiteGu** [comment]
@markhpc @aclamk  Can we accelerate the review of this modification? I want to use it as soon as possible.

**Review by aclamk — APPROVED** [review]

**Comment by ljflores** [comment]
@YiteGu it has been put in a test batch; Shaman builds were failing yesterday, but we're having better luck today. Will get it tested ASAP.

**Comment by ljflores** [comment]
jenkins test api

**Comment by ifed01** [comment]
jenkins test make check

**Comment by ifed01** [comment]
jenkins test windows

**Comment by YiteGu** [comment]
> @YiteGu it has been put in a test batch; Shaman builds were failing yesterday, but we're having better luck today. Will get it tested ASAP.

thx, @ljflores BTW, I already backport to 16.2.14 and build by self. 
@ifed01 The fact proves that this patch  is very effective.

**Comment by ljflores** [comment]
Rados approved https://tracker.ceph.com/projects/rados/wiki/MAIN#httpstrellocomcwK3QrkV21901-wip-yuri-testing-2023-12-06-1240

**Pull request merged**
