### PR TITLE
hammer: Add units to rados bench output and clean up formatting

### PR DESCRIPTION
**Pull request by badone**
I've massaged some cherry-picks and added an additional patch to add units to hammer rados bench output and fix various formatting issues that are fixed in master.

Needed for some downstream bugs.

http://tracker.ceph.com/issues/15717

### CODE REVIEW

**Comment by dachary** [comment]
@badone could you please amend the commit of 8aeb016acf8e8dbea4f2e3ab432966156ffb16ee to explain why this must be done for hammer and not in master ?

**Comment by badone** [comment]
@dachary Not sure I understand. 8aeb016 is already in master, see https://github.com/ceph/ceph/commit/069d95eaf49cadaa9a8fa1fa186455944a50ec7d

**Comment by dachary** [comment]
@badone could you then amend the commit message of 8aeb016 to reference 069d95e and explain why it was not a good idea to cherry-pick -x it ?

**Comment by badone** [comment]
@dachary like that?

**Comment by dachary** [comment]
@badone yeah :-)

**Pull request merged**
