### PR TITLE
pacific: qa/import-legacy: install python3 package for nautilus ceph

### PR DESCRIPTION
**Pull request by lxbsz**
The 'volume_client' script will use the python3 and will import
the'ceph_volume_client' volume, we need to install the python3
packages when installing the nautilus ceph.

Or it will fail to generate the keyring contents for the
'client.vol_data_isolated', and then when authenticating from mon
the mon will only receive a corrupt payload.

Fixes: https://tracker.ceph.com/issues/57083
Signed-off-by: Xiubo Li <xiubli@redhat.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by lxbsz** [comment]
Haven't run the qa test yet.

**Comment by kotreshhr** [comment]
> Haven't run the qa test yet.

Looks good, please run qa test and share the result.

**Comment by lxbsz** [comment]
[Teuthology test passed](https://pulpito.ceph.com/xiubli-2022-08-11_02:27:09-fs:upgrade:volumes:import-legacy-wip-57083-pacific-20220810-2021-distro-default-smithi/)

**Comment by lxbsz** [comment]
jenkins test make check

**Comment by lxbsz** [comment]
> @lxbsz this is ready for merge but filing make check

Rebased it.

**Comment by lxbsz** [comment]
Rebased it.

**Comment by tchaikov** [comment]
jenkins test make check

**Comment by tchaikov** [comment]
jenkins test api

**Comment by yuriw** [comment]
jenkins test make check

**Comment by ljflores** [comment]
jenkins test make check

**Review by kotreshhr — APPROVED** [review]
lgtm

**Pull request merged**
