### PR TITLE
quincy: mgr/dashboard: refactor dashboard cephadm e2e tests 

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/57828

---

backport of https://github.com/ceph/ceph/pull/48163
parent tracker: https://tracker.ceph.com/issues/57386

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/main/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test make check

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Comment by nizamial09** [comment]
jenkins test dashboard

**Review by aaSharma14 — APPROVED** [review]

**Comment by nizamial09** [comment]
QA RUN: [Passed](https://pulpito.ceph.com/nizamial09-2022-10-13_17:42:03-rados:dashboard-wip-nia-testing-2022-10-12-1238-quincy-distro-default-smithi/) :heavy_check_mark:

**Pull request merged**
