### PR TITLE
luminous: MDSMonitor: cleanup and protect fsmap access

### PR DESCRIPTION
**Pull request by batrick**
http://tracker.ceph.com/issues/23792

### CODE REVIEW

**Comment by smithfarm** [comment]
```
In file included from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MDSMonitor.h:26:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MDSMonitor.cc:19:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/PaxosFSMap.h: In member function ‘virtual void MDSMonitor::update_from_paxos(bool*)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/PaxosFSMap.h:58:9: error: ‘FSMap PaxosFSMap::fsmap’ is private
   FSMap fsmap; /* the current epoch */
         ^
```

**Comment by smithfarm** [comment]
Also, the commit message is missing a "Conflicts" section.

**Comment by batrick** [comment]
Trying again...

**Comment by smithfarm** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MDSMonitor.cc: In member function ‘bool MDSMonitor::preprocess_command(MonOpRequestRef)’:
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MDSMonitor.cc:988:66: error: passing ‘const std::map<int, std::shared_ptr<Filesystem> >’ as ‘this’ argument discards qualifiers [-fpermissive]
       mdsmapp = &(fsmapp->filesystems[fsmapp->legacy_client_fscid]->mds_map);
                                                                  ^
In file included from /usr/include/c++/5/map:61:0,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/build/boost/include/boost/regex/v4/regex_workaround.hpp:37,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/build/boost/include/boost/regex/v4/regex.hpp:32,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/build/boost/include/boost/regex.hpp:31,
                 from /home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MDSMonitor.cc:17:
/usr/include/c++/5/bits/stl_map.h:474:7: note:   in call to ‘std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type& std::map<_Key, _Tp, _Compare, _Alloc>::operator[](const key_type&) [with _Key = int; _Tp = std::shared_ptr<Filesystem>; _Compare = std::less<int>; _Alloc = std::allocator<std::pair<const int, std::shared_ptr<Filesystem> > >; std::map<_Key, _Tp, _Compare, _Alloc>::mapped_type = std::shared_ptr<Filesystem>; std::map<_Key, _Tp, _Compare, _Alloc>::key_type = int]’
       operator[](const key_type& __k)
       ^
/home/jenkins-build/build/workspace/ceph-pull-requests/src/mon/MDSMonitor.cc:1004:36: error: ‘p’ was not declared in this scope
     ss << "dumped fsmap epoch " << p->get_epoch();
                                    ^
src/mon/CMakeFiles/mon.dir/build.make:206: recipe for target 'src/mon/CMakeFiles/mon.dir/MDSMonitor.cc.o' failed
make[3]: *** [src/mon/CMakeFiles/mon.dir/MDSMonitor.cc.o] Error 1
```

**Comment by batrick** [comment]
@smithfarm yup I'm still banging way at the compile errors. I'll let you know when i'm done.

**Comment by smithfarm** [comment]
@batrick Sorry - didn't realize you were about to re-push. Have gotten into the habit of copying relevant information from the Jenkins logs into comments because the Jenkins logs are so short-lived.

**Comment by batrick** [comment]
understandable, thanks

**Comment by batrick** [comment]
(I think it's finally green now!)

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-05-07-1626-luminous](https://trello.com/c/opsXSPzu/305-wip-yuri-testing-2018-05-07-1626-luminous)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
