### PR TITLE
ceph-volume: support zapping by osd-id for RAW OSDs

### PR DESCRIPTION
**Pull request by guits**
Currently it is only possible to zap by osd-id for LVM-based OSDs.

This commit introduces the required changes in order to support zapping by osd-id for RAW-based OSDs.

Fixes: https://tracker.ceph.com/issues/68576

### CODE REVIEW

**Comment by guits** [comment]
jenkins ceph-volume unit tests

**Comment by guits** [comment]
jenkins ceph-volume unit tests

**Comment by guits** [comment]
jenkins test api

**Comment by guits** [comment]
jenkins test make check arm64

**Review by asm0deuz — APPROVED** [review]
LGTM

**Comment by guits** [comment]
jenkins ceph-volume unit tests

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2024-10-22_20:36:30-orch:cephadm-wip-guits-squid-2024-10-22-1533-squid-distro-default-smithi/

**Comment by guits** [comment]
https://pulpito.ceph.com/gabrioux-2024-10-22_20:43:59-orch:cephadm-wip-guits-main-2024-10-22-1532-distro-default-smithi/

**Comment by guits** [comment]
jenkins test make check

**Comment by guits** [comment]
jenkins test ceph-volume unit tests

**Comment by guits** [comment]
jenkins ceph-volume unit tests

**Comment by guits** [comment]
jenkins test make check arm64

**Comment by sergiuiacob1** [comment]
Hello! Was the bug mentioned here
https://www.spinics.net/lists/ceph-users/msg88227.html
fixed in later ceph versions?

**Comment by FredNass** [comment]
@sergiuiacob1 Not yet. It's being investigated [here](https://tracker.ceph.com/issues/73107).

**Pull request merged**
