### PR TITLE
common: Remove redundant includes - 4

### PR DESCRIPTION
**Pull request by joscollin**
Fixes: http://tracker.ceph.com/issues/19883 (Partially)

Signed-off-by: Jos Collin <jcollin@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
ready for merge

http://pulpito.ceph.com/yuriw-2017-05-26_19:34:44-rados-wip-yuri-testing_2017_5_27-distro-basic-smithi/

http://pulpito.ceph.com/yuriw-2017-05-29_22:24:45-rados-wip-yuri-testing_2017_5_27---basic-smithi/

**Comment by liewegas** [comment]
@wjwithagen this and #15267 test out fine.  should we continue to merge these or is there some check we should do first to avoid breakage?

**Comment by wjwithagen** [comment]
@liewegas @joscollin @yuriw 
From visual inspection I certainly have the feeling that this PR is going to break FreeBSD building.
I do see some includes that I have added because FreeBSD needed.
And for the ones that were compatible with Linux I chose to just add them, and not `#ifdef` them for FreeBSD. THings that spring to my mind are some of the includes with the DNS files, and removing pthread is probably also a bad idea. 

BUT I really need to test this.  So I'll have to make some diffs, and apply to a testdir, and see what comes of it. That might take me a few days to figure out what the minimal set is that FreeBSD needs to keep. 

Note that I like the cleanup from a software maintenance point , but I would not expect any measurable decrease in build time. Even more soe if you're using ccache.

**Comment by joscollin** [comment]
@liewegas @wjwithagen @yuriw  pthread is included via `#include "include/Context.h"`and that's the reason it doesn't report error for me and in the Jenkins too. So as @wjwithagen said, this needs testing in FreeBSD to make sure if there is something to be reverted.

**Comment by wjwithagen** [comment]
@joscollin @liewegas 
Like I thought, reorg is a bit too agresive for FreeBSD.
```
In file included from /home/jenkins/workspace/ceph-master/src/common/dns_resolve.h:17:
/usr/include/resolv.h:157:3: error: field has incomplete type 'struct sockaddr_in'
                nsaddr_list[MAXNS];     /*%< address of name server */
                ^
/usr/include/resolv.h:156:9: note: forward declaration of 'sockaddr_in'
        struct sockaddr_in
               ^
/usr/include/resolv.h:196:21: error: field has incomplete type 'struct sockaddr_in'
        struct sockaddr_in      sin;
                                ^
/usr/include/resolv.h:156:9: note: forward declaration of 'sockaddr_in'
        struct sockaddr_in
               ^
2 errors generated.
```
So this set I need to figure out.

**Comment by joscollin** [comment]
@wjwithagen  Fixed, please check in FreeBSD now and let me know. Thank you for the testing.

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by joscollin** [comment]
Jenkins Retest this please

**Comment by joscollin** [comment]
@liewegas You can add your testing label now.

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2017-06-16_00:46:50-rados-wip-sage-testing-distro-basic-smithi/

**Pull request merged**
