### PR TITLE
mgr/dashboard: remove 'config-opt: read' perm. from system roles.

### PR DESCRIPTION
**Pull request by alfonsomthd**
Fixes: https://tracker.ceph.com/issues/44237
Signed-off-by: Alfonso Martínez <almartin@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
jenkins test dashboard backend

**Comment by alfonsomthd** [comment]
jenkins test make check

**Comment by callithea** [comment]
- [pkg build](https://shaman.ceph.com/builds/ceph/wip-laura-testing-33690/)
- [QA run](http://pulpito.ceph.com/laura-2020-03-03_21:47:48-rados:dashboard-wip-laura-testing-33690-distro-basic-smithi/) [WIP]

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2020-03-04_09:24:42-rados-wip-kefu-testing-2020-03-04-1337-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2020-03-04_12:08:06-rados-wip-kefu-testing-2020-03-04-1337-distro-basic-smithi/

**Pull request merged**
