### PR TITLE
qa/tests: Run tests on active mgr role

### PR DESCRIPTION
**Pull request by vasukulkarni**
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
http://pulpito.ceph.com/vasu-2017-10-26_22:57:43-ceph-ansible-master-distro-basic-ovh/

**Comment by tchaikov** [comment]
could you prefix the title of your commit message with the subcomponent your are changing ? see https://github.com/ceph/ceph/blob/master/SubmittingPatches.rst#3-describe-your-changes

@vasukulkarni would you please elaborated a little bit why we need to run these tests on active mgr?

**Comment by vasukulkarni** [comment]
@tchaikov sure will fix the commit message as per guidelines,  In my cluster I have 2 mgr nodes, what I have seen during early testing is the workunit rest.yaml would fail randomly and it happened whenever it ran on mgr which was not active. 

Recently it has started failing so I tried to run on the mgr.y (mgr.x is stoped so that mgr.y becomes active) but that didn't work

Current runs are failing, maybe you can suggest what to fix here ?
http://pulpito.ceph.com/teuthology-2017-10-26_05:15:02-ceph-ansible-luminous-distro-basic-vps/

**Comment by tchaikov** [comment]
@vasukulkarni i will take a look early tomorrow.

**Comment by vasukulkarni** [comment]
@tchaikov np, thanks!

**Comment by tchaikov** [comment]
@vasukulkarni 

```
2017-10-26T09:42:15.148 INFO:teuthology.orchestra.run.vpm023.stdout:TASK [ceph-mgr : disable ceph mgr enabled modules] *****************************
2017-10-26T09:42:15.148 INFO:teuthology.orchestra.run.vpm023.stdout:task path: /home/ubuntu/ceph-ansible/roles/ceph-mgr/tasks/main.yml:23
2017-10-26T09:42:17.238 INFO:teuthology.orchestra.run.vpm023.stdout:changed: [vpm081.front.sepia.ceph.com -> vpm023.front.sepia.ceph.com] => (item=restful) => {
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:    "changed": true,
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:    "cmd": [
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:        "ceph",
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:        "--cluster",
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:        "ceph",
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:        "mgr",
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:        "module",
2017-10-26T09:42:17.239 INFO:teuthology.orchestra.run.vpm023.stdout:        "disable",
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:        "restful"
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:    ],
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:    "delta": "0:00:01.028090",
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:    "end": "2017-10-26 09:42:17.149058",
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:    "item": "restful",
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:    "rc": 0,
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:    "start": "2017-10-26 09:42:16.120968"
2017-10-26T09:42:17.240 INFO:teuthology.orchestra.run.vpm023.stdout:}
....
2017-10-26T09:48:15.275 INFO:teuthology.orchestra.run.vpm023:Running: "sudo TESTDIR=/home/ubuntu/cephtest bash -c 'ceph restful create-key admin'"
2017-10-26T09:48:15.795 INFO:teuthology.orchestra.run.vpm023.stderr:no valid command found; 10 closest matches:
2017-10-26T09:48:15.795 INFO:teuthology.orchestra.run.vpm023.stderr:osd count-metadata <property>
2017-10-26T09:48:15.795 INFO:teuthology.orchestra.run.vpm023.stderr:osd versions
2017-10-26T09:48:15.795 INFO:teuthology.orchestra.run.vpm023.stderr:osd find <osdname (id|osd.id)>
2017-10-26T09:48:15.795 INFO:teuthology.orchestra.run.vpm023.stderr:osd metadata {<osdname (id|osd.id)>}
2017-10-26T09:48:15.795 INFO:teuthology.orchestra.run.vpm023.stderr:osd getmaxosd
2017-10-26T09:48:15.796 INFO:teuthology.orchestra.run.vpm023.stderr:osd ls-tree {<int[0-]>} {<name>}
2017-10-26T09:48:15.796 INFO:teuthology.orchestra.run.vpm023.stderr:osd getmap {<int[0-]>}
2017-10-26T09:48:15.796 INFO:teuthology.orchestra.run.vpm023.stderr:osd getcrushmap {<int[0-]>}
2017-10-26T09:48:15.796 INFO:teuthology.orchestra.run.vpm023.stderr:osd tree {<int[0-]>} {up|down|in|out|destroyed [up|down|in|out|destroyed...]}
2017-10-26T09:48:15.796 INFO:teuthology.orchestra.run.vpm023.stderr:osd ls {<int[0-]>}
2017-10-26T09:48:15.796 INFO:teuthology.orchestra.run.vpm023.stderr:Error EINVAL: invalid command
```

so, we disabled all mgr plugins, but only enabled "status" after that. that's why `'ceph restful create-key admin'` failed.

see https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mgr/tasks/main.yml and https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mgr/defaults/main.yml#L6

i posted #18634 to address this issue.

**Comment by tchaikov** [comment]
closing in favor of #18634

**Pull request closed without merging**
