### PR TITLE
ceph-disk: fixes various race conditions

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/12787
http://tracker.ceph.com/issues/13000
http://tracker.ceph.com/issues/13153
http://tracker.ceph.com/issues/13154
http://tracker.ceph.com/issues/13157
http://tracker.ceph.com/issues/13160
http://tracker.ceph.com/issues/13174
http://tracker.ceph.com/issues/13180

### CODE REVIEW

**Comment by dachary** [comment]
@joejulian I successfully ran the ceph-disk-test.py suite on CentOS 7 with this series and I believe it addresses all know issues. It would be great if you could review it. I fully expect there are a few details to fix but I'm also convinced we now have something stable :-)

**Comment by dachary** [comment]
Running tests.

**Comment by liewegas** [comment]
push a ceph.git wip branch and run teh ceph-deploy suite a few times?  it pretty reliably fails one of the dmcrypt+centos7 tests.

**Comment by dachary** [comment]
@liewegas I will do that

**Comment by dachary** [comment]
It looks like the ceph-deploy issues with dmcrypt remain despit this series of fixes. The series of tests I ran ( http://tracker.ceph.com/issues/13000#note-9 ) went otherwise well. I think this pull request is ready for review.

**Pull request merged**
