### PR TITLE
osd/PGLog: set acceptable rollback_info_trimmed_to for pg of replicated pool

### PR DESCRIPTION
**Pull request by LiumxNL**
Signed-off-by: Mingxin Liu <mingxin@xsky.com>

### CODE REVIEW

**Comment by LiumxNL** [comment]
@tchaikov @athanatos pls take a look, thx!

**Review by tchaikov — APPROVED** [review]

**Comment by markhpc** [comment]
+ @neha-ojha

**Review by tchaikov — CHANGES_REQUESTED** [review]
https://pulpito.ceph.com/kchai-2021-07-22_12:07:24-rados-wip-kefu-testing-2021-07-22-1810-distro-basic-smithi/6286911/

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2021-07-24_05:22:39-rados-wip-kefu-testing-2021-07-24-1158-distro-basic-smithi/6289632/

**Review by tchaikov — APPROVED** [review]

**Comment by tchaikov** [comment]
https://pulpito.ceph.com/kchai-2021-07-26_06:38:14-rados-wip-kefu-testing-2021-07-26-1205-distro-basic-smithi/

**Comment by tchaikov** [comment]
@athanatos @neha-ojha could you please help review this changeset at your convenience?

**Review by athanatos — APPROVED** [review]
I think this is right.  ReplicatedBackend always passes at_version to log_operation, so we should be trimming to last_update on every operation.

**Pull request merged**
