### PR TITLE
jewel: install-deps.sh: update g++ symlink also

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins re-test this please

**Comment by tchaikov** [comment]
the docs build failure is addressed by https://github.com/ceph/ceph-build/pull/942

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
should port this change to luminous branch.

**Pull request merged**
