### PR TITLE
rbd-mirror: optionally support active/active replication

### PR DESCRIPTION
**Pull request by dillaman**

### CODE REVIEW

**Comment by dillaman** [comment]
Branch currently incorporates four different PRs that need to be merged (#21831, #21804, #21817, #21823) to prevent sporadic unrelated test failures

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2018-05-09_12:36:34-rbd-wip-rbd-mirror-policy-distro-basic-smithi/
http://pulpito.ceph.com/jdillaman-2018-05-09_14:24:56-rbd-wip-rbd-mirror-policy-distro-basic-smithi/
http://pulpito.ceph.com/jdillaman-2018-05-09_15:07:04-rbd-wip-rbd-mirror-policy-distro-basic-smithi/
http://pulpito.ceph.com/jdillaman-2018-05-09_15:41:34-rbd-wip-rbd-mirror-policy-distro-basic-smithi/

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
retest this please

**Comment by dillaman** [comment]
... all [DNM] commits from other PRs have been merged into master, so removing the [DNM] prefix from this PR.

**Comment by dillaman** [comment]
Crazy -- I ran it through the suite 5 times w/o a single failure and you run it one and get 7 core dumps. I'll take a look.

**Comment by dillaman** [comment]
http://pulpito.ceph.com/jdillaman-2018-05-14_11:57:05-rbd-wip-rbd-mirror-policy-distro-basic-smithi/

**Comment by dillaman** [comment]
Yesterday's run (fsx failures unrelated to changes in this PR but fixes will be included in next test run):
http://pulpito.ceph.com/jdillaman-2018-05-14_16:40:45-rbd-wip-rbd-mirror-policy-distro-basic-smithi/

**Comment by dillaman** [comment]
Run for latest fixes: http://pulpito.ceph.com/jdillaman-2018-05-15_20:29:57-rbd-wip-rbd-mirror-policy-distro-basic-smithi/

2535466: cluster unresponsive
2535439: unrelated bug where image sync attempts to unprotect an in-use snapshot (investigating)
2535457: unrelated bug from local image id collision (http://tracker.ceph.com/issues/24139)

**Comment by trociny** [comment]
Playing with this, it looks really cool! 

One observation though (I think not related to this PR but rather how the policy currently works). If I remove images from the pool that are replaying by the same instance there is no any shuffling and you can end up with one completely idle instance. When adding new images it will add them evenly to the instances, so you still will have that previously idle instance underloaded. It looks like the same thing happens when stopping an instance: the policy will try to distribute its images evenly among  other instances, not taking into account how each instance is currently loaded.
So you can end up with image distribution like below:
```
% for i in 0 1 2 3; do ceph --admin-daemon /tmp/tmp.rbd_mirror/rbd-mirror.cluster1-client.mirror.$i.asok help |grep  -c 'status mirror/'; done
7
3
10
2
```
It looks like the only way to reshuffle them evenly is to restart instances. I suppose this is not what users will expect from "simple" policy -- I think they will want even distribution not depending on the history.

**Comment by dillaman** [comment]
Thanks -- I opened http://tracker.ceph.com/issues/24161

**Comment by vshankar** [comment]
LGTM

**Comment by trociny** [comment]
@dillaman There was a case [1] when an rbd-mirror daemon failed to stop after kill signal send:
```
2018-05-17T18:13:19.300 INFO:tasks.workunit.cluster1.client.mirror.smithi029.stderr:+ awk -v pid=27840 $2 == pid {print; exit 1}
2018-05-17T18:13:19.327 INFO:tasks.workunit.cluster1.client.mirror.smithi029.stdout:ubuntu     27840  0.3  0.0 3906404 27384 ?       Ssl  18:11   0:00 rbd-mirror --cluster cluster1 --id mirror.3 --rbd-mirror-delete-retry-interval=5 --rbd-mirror-image-state-check-interval=5 --rbd-mirror-journal-poll-age=1 --rbd-mirror-pool-replayers-refresh-interval=5 --debug-rbd=30 --debug-journaler=30 --debug-rbd_mirror=30 --daemonize=true
2018-05-17T18:13:19.327 INFO:tasks.workunit.cluster1.client.mirror.smithi029.stdout:cluster1 status
2018-05-17T18:13:19.327 INFO:tasks.workunit.cluster1.client.mirror.smithi029.stderr:+ cleanup 1
```
In its log [2] there is a message about the termiantion signal and shutdown started but apparently got stuck.
```
2018-05-17 18:12:16.123 7ff53f3c7700 -1 received  signal: Terminated from /bin/sh -ex /home/ubuntu/cephtest/clone.cluster1.client.mirror/qa/workunits/rbd/rbd_mirror.sh  (PID: 14325) UID: 1000
```

Probably can be investigated an addressed as a separate PR and we can proceed with merging this PR anyway?

[1] http://qa-proxy.ceph.com/teuthology/trociny-2018-05-17_15:20:11-rbd-wip-mgolub-testing-distro-basic-smithi/2544216/teuthology.log
[2] /ceph/teuthology-archive/trociny-2018-05-17_15:20:11-rbd-wip-mgolub-testing-distro-basic-smithi/2544216/remote/smithi029/log/cluster1-client.mirror.3.27775.log.gz

**Comment by trociny** [comment]
> Can you open a tracker ticket for it?

http://tracker.ceph.com/issues/24169

**Pull request merged**
