### PR TITLE
win32: support building windows client on RHEL

### PR DESCRIPTION
**Pull request by ktdreyer**
Prior to this change, we could only cross-compile Ceph on Ubuntu and SUSE Linux. Add support for cross-compiling on RHEL also.

### CODE REVIEW

**Review by bigjust — APPROVED** [review]

**Review by petrutlucian94 — CHANGES_REQUESTED** [review]
Overall looks good, however the windows job fails:

```
+ timeout 30s ssh -i **** -o UserKnownHostsFile=/home/jenkins-build/build/workspace/ceph-windows-pull-requests/known_hosts administrator@192.168.122.147 powershell.exe Start-Service -Name ceph-rbd
Start-Service : Service 'ceph-rbd (ceph-rbd)' cannot be started due to the following error: Cannot start service 
ceph-rbd on computer '.'.
At line:1 char:1
+ Start-Service -Name ceph-rbd
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],  
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

I'll need to check the ceph-rbd service failure, it might be just a missing dependency (e.g. ``-lssp``).

**Comment by ktdreyer** [comment]
> $mingwTargetLibDir/libssp*.dll

Thank you! I've copied your suggestion and re-pushed. (I should have tried running the Windows tests earlier...)

**Comment by petrutlucian94** [comment]
jenkins test api

**Review by petrutlucian94 — APPROVED** [review]
Thanks for updating the PR, the windows tests are passing now.

A side note about the windows test job: it's mostly running unit tests but we're working on extending the test coverage. We have a few PRs that enable functional tests such as the libcephfs and librados ones [1][2]. We're planning on porting librbd tests and also add some new ones that exercise rbd-wnbd and ceph-dokan.

We've updated the windows test job to collect various artifacts such as:

* individual test logs [3]
* aggregated test results [4] (we're running the tests in parallel, streaming the results using the subunit format and them aggregating the results)
* html result summaries [5] - I see that this one isn't rendered correctly unless you download the artifact archive
* crash dumps (optional)
* executables and debug symbols (optional, can be requested through jenkins params)

BTW, I assume you're mostly interested in building/packaging ceph for Windows. Just so that we don't end up doing the same work, we're planning on adding Windows Clustered Shared Volume support (through SCSI Persistent Reservations).

[1] https://github.com/ceph/ceph/pull/48053
[2] https://github.com/ceph/ceph/pull/48127
[3] https://jenkins.ceph.com/job/ceph-windows-pull-requests/14402/artifact/artifacts/test_results/
[4] https://jenkins.ceph.com/job/ceph-windows-pull-requests/14402/artifact/artifacts/test_results/test_results.txt
[5] https://jenkins.ceph.com/job/ceph-windows-pull-requests/14402/artifact/artifacts/test_results/test_results.html

**Comment by petrutlucian94** [comment]
jenkins test api

**Pull request merged**
