### PR TITLE
rados test: Consolidate output of err_t and add test case

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
@tchaikov I moved this change to its own pull request.

**Comment by dzafman** [comment]
In fact the test case happens to not be impacted by the rados part of the fix.  The test only creates "missing" shards so the output is the same.

**Comment by tchaikov** [comment]
`Reviewed-by: Kefu Chai <kchai@redhat.com>` once your test is green.

**Comment by dzafman** [comment]
Combined this single commit into #9613 in order to also keep improving the test case.

**Pull request closed without merging**
