### PR TITLE
tiering: aggressively flushing at (user specified) idle time

### PR DESCRIPTION
**Pull request by LiumxNL**
This was thrown out several months ago, seems buried in bunch of pull requests. In many use cases, the user traffic is high in only some fixed time, for example, work hour. In those cases, it is desirable that the flushing job for cache tiering could be scheduled at the idle time, and do as much as possible, to reduce the bandwidth contention with user traffic. This patch implements aggressively flushing for cache tiering at user specified time.

Signed-off-by: Mingxin Liu <mingxin.liu@kylin-cloud.com>
Reviewed-by: Li Wang <wang.li@kylin-cloud.com>
Reviewed-by: Yunchuan Wen <yunchuan.wen@kylin-cloud.com>
Suggested-by: Xinze Chi <xmdxcxz@gmail.com>

### CODE REVIEW

**Comment by dragonylffly** [comment]
@liewegas Would you please take a look at it, we implemented this several months ago, your comments are appreciated

**Comment by liewegas** [comment]
A few minor comments, but this looks pretty good to me, thanks!

**Comment by liewegas** [comment]
We need to make sure this gets covered in the teuthology tests.  Since they can run at any time of day simply setting this config option in the test config doesn't really help.  Ideas?  Maybe a mode that randomly switches between high and low modes every few minutes?

**Comment by liewegas** [comment]
@LiumxNL @dragonylffly ping

**Comment by wwformat** [comment]
@liewegas 
Hi, I already rebase it and add a test case.

**Comment by liewegas** [comment]
@wwformat Ah, thanks.  But we also need to make sure this gets good coverage in the teuthology rados suite by modifying tasks/thrashosds.py to turn this on and off.  I would suggest having it change the time period every so often to switch into/out of fast flushing mode.. either by (randomly) setting an interval that includes the current time or one that starts a few (~30) seconds in the future.  Thanks!

**Comment by LiumxNL** [comment]
@liewegas  
Hi. The test case has updated. it contains two parts, one is to test when schedule time is coming(the start time is random in a range), agent can flush all dirty objects into base pool. the second is to test when agent is in schedule flush interval, all new dirty objects will be flushed into base pool soon. thanks!

**Comment by liewegas** [comment]
@LiumxNL I see the workunit test, but we *also* need coverage from teuthology (which is where most of the real stress testing happens).  See ceph-qa-suite.git/tasks/thrashosds.py and my previous comment.  Thanks!

**Comment by jack-changtao** [comment]
@LiumxNL  @liewegas 

I  have some question about this PR.

if we just don't want to flushing at some specific time, or don't want to flush too much  to reduce the bandwidth contention with user traffic, why not just increase the cache_target_dirty_ratio and cache_target_dirty_high_ratio param?

if we wan't to schedule flush work at some specific time and aggresively do it, By decreasing  cache_target_dirty_ratio and cache_target_dirty_high_ratio param using cron service of linux, we can do this at all.

I think this way is more simple and directly. Thanks！

**Comment by liewegas** [comment]
I'm inclined to agree.  If we can do this with a simple external tool, or eventually roll this into a management layer (like calamari) instead, that simplifies the rados code.

**Pull request closed without merging**
