### PR TITLE
jewel: essential backports for OpenStack Manila

### PR DESCRIPTION
**Pull request by ajarr**
ceph_volume_client: allow read-only authorization for volumes 
Fixes: http://tracker.ceph.com/issues/15999

pybind: ceph_volume_client authentication metadata
Fixes: http://tracker.ceph.com/issues/16830

ceph_volume_client: add versioning
Fixes: http://tracker.ceph.com/issues/16831

### CODE REVIEW

**Comment by ajarr** [comment]
tested by https://github.com/ceph/ceph-qa-suite/pull/1100

**Comment by ajarr** [comment]
@jcsp , I've added read-only volume patch here. So this PR, https://github.com/ceph/ceph/pull/9558
,which also wanted to backport read-only volume feature, needs to abandoned?

**Comment by ajarr** [comment]
There were a few tasks/cephfs PRs that were merged in master between PR for testing
read-only and testing authentication metadata. I've not added those here.

* https://github.com/ceph/ceph-qa-suite/pull/1013
* https://github.com/ceph/ceph-qa-suite/pull/1018, backport PR https://github.com/ceph/ceph-qa-suite/pull/1075
* https://github.com/ceph/ceph-qa-suite/pull/1045
* https://github.com/ceph/ceph-qa-suite/pull/1064

Of the above, maybe we need to add patches from
the below PRs in this PR request?
* https://github.com/ceph/ceph-qa-suite/pull/1013
* https://github.com/ceph/ceph-qa-suite/pull/1064

**Comment by jcsp** [comment]
Test failed on missing fsync http://qa-proxy.ceph.com/teuthology/jspray-2016-07-29_05:06:54-fs:recovery-wip-manila-backports-jewel-distro-basic-mira/339326/teuthology.log

Cherry picked 4356b8fb to the instance of wip-manila-backports-jewel built for testing and will retest.  @ajarr can you cherry-pick that commit to this PR too please?

**Comment by jcsp** [comment]
Passing with the extra 4356b8f commit here: http://pulpito.ceph.com/jspray-2016-08-01_19:41:23-fs:recovery-wip-manila-backports-jewel-distro-basic-mira/

**Pull request merged**
