### PR TITLE
test/librbd: decouple ceph_test_librbd_api from libceph-common

### PR DESCRIPTION
**Pull request by tchaikov**
Fixes: http://tracker.ceph.com/issues/20175
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
```
(gdb) info address ceph::buffer::list::list
Symbol "ceph::buffer::list::list()" is a function at address 0x555555610070.
(gdb) info shared
0x00007ffff768f9d0  0x00007ffff7a18da6  Yes         /var/ceph/ceph/build/lib/librbd.so.1
0x00007ffff725caf0  0x00007ffff739f32f  Yes         /var/ceph/ceph/build/lib/librados.so.2
0x00007ffff6edaab0  0x00007ffff6ee7811  Yes         /lib/x86_64-linux-gnu/libpthread.so.0
0x00007ffff6be0230  0x00007ffff6c885c9  Yes (*)     /usr/lib/x86_64-linux-gnu/libstdc++.so.6
0x00007ffff693fac0  0x00007ffff694ffe5  Yes (*)     /lib/x86_64-linux-gnu/libgcc_s.so.1
0x00007ffff65bd910  0x00007ffff66e7403  Yes         /lib/x86_64-linux-gnu/libc.so.6
0x00007fffed5cd4c0  0x00007fffedd3b7df  Yes         /var/ceph/ceph/build/lib/libceph-common.so.0
(gdb) bt
#0  ceph::buffer::list::list (this=0x5555559dcd98) at ./include/rbd/../rados/buffer.h:378
#1  0x00007fffed5f34f4 in Message::Message (this=0x5555559dccd0, t=17, version=1, compat_version=0) at /var/ceph/ceph/src/msg/Message.h:289
#2  0x00007fffed5f3ba7 in PaxosServiceMessage::PaxosServiceMessage (this=0x5555559dccd0, type=17, v=0, enc_version=1, compat_enc_version=0)
    at /var/ceph/ceph/src/messages/PaxosServiceMessage.h:24
#3  0x00007fffed6ff738 in MAuth::MAuth (this=0x5555559dccd0) at /var/ceph/ceph/src/messages/MAuth.h:27
#4  0x00007fffed6fcc0e in MonConnection::start (this=0x5555559de738, epoch=0, entity_name=..., auth_supported=...) at /var/ceph/ceph/src/mon/MonClient.cc:1189
#5  0x00007fffed6f5c5b in MonClient::_reopen_session (this=0x5555558f21d8, rank=-1) at /var/ceph/ceph/src/mon/MonClient.cc:614
#6  0x00007fffed6f44c4 in MonClient::authenticate (this=0x5555558f21d8, timeout=300) at /var/ceph/ceph/src/mon/MonClient.cc:453
#7  0x00007ffff72dc75e in librados::RadosClient::connect (this=0x5555558f2190) at /var/ceph/ceph/src/librados/RadosClient.cc:298
#8  0x00007ffff7265aa9 in librados::Rados::connect (this=0x7fffffffdf28) at /var/ceph/ceph/src/librados/librados.cc:2271
#9  0x000055555563afba in connect_cluster_pp[abi:cxx11](librados::Rados&) (cluster=...) at test/librados/test.cc:273
#10 0x000055555559acde in main (argc=<optimized out>, argv=<optimized out>) at test/librbd/test_main.cc:38
```

in short, `libceph-common.so.0` is using the symbols offered by the executable itself! and this causes segfault, because the `buffer::list` changed its layout in luminous: we added `_mempool` to it recently.

**Comment by dillaman** [comment]
Nit: typo in first commit subject line: ```standarnd```

**Comment by tchaikov** [comment]
changelog

- fixed the typo

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
@dillaman did the test pass? or is there anything else i can do ?

**Comment by smithfarm** [comment]
Backport to kraken is non-trivial.

**Comment by dillaman** [comment]
@smithfarm I'll post a kraken PR tonight

**Comment by yuriw** [comment]
@smithfarm can this be backported to hammer?  We need it for client-upgrades https://github.com/ceph/ceph/pull/17981

**Comment by dillaman** [comment]
@yuriw I can tackle it today

**Pull request merged**
