### PR TITLE
erasure-code: Remove duplicate of isa-l files

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
There are two copies of isa-l. While one is a git submodule the other
was a static copy from an older version. This change helps with removing
the duplicate and maintain a single copy.

Signed-off-by: Ganesh Mahalingam <ganesh.mahalingam@intel.com>

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
@dachary your thoughts on this patch will be much appreciated.

**Comment by dachary** [comment]
For the record:

<pre>
144/173 Test   #2: erasure-decode-non-regression.sh ........   Passed  538.24 sec
</pre>

**Comment by ganeshmaharaj** [comment]
Thanks @dachary. Have updated the commit msg and pushed a new version of the patch.

**Comment by dachary** [comment]
@ganeshmaharaj you did good, thanks :-)

**Comment by ganeshmaharaj** [comment]
@dachary on a side note. isa-l library has had more releases since the last time ceph/isa-l has had 2 more releases. Would this be a nice change to upgrade the base also or would you prefer to keep it as a seperate patch if we wish to get that as well. Here are the release notes from v2.18 https://github.com/01org/isa-l/blob/7e1a337433a340bc0974ed0f04301bdaca374af6/Release_notes.txt

**Comment by dachary** [comment]
@ganeshmaharaj at first glance I don't see something from the release notes that would benefit Ceph directly. Do you have something specific in mind ?

**Comment by ganeshmaharaj** [comment]
@dachary Nothing pressing that will need us to update right away. maybe performance improvements as mentioned here https://github.com/01org/isa-l/blob/7e1a337433a340bc0974ed0f04301bdaca374af6/Release_notes.txt#L53-L77 but I will need to test it before i can say in confidence that the upgrade will help.  Let me do that and if it is worth it, will do a seperate PR for it.

**Comment by tsg-** [comment]
@dachary ISA-L 2.18 add compression enhancements related to avx512 that should be useful for bluestore block compression.

Also @ganeshmaharaj, let's add new avx512 related files from the ISA-L EC sources and then merge this.  I have some pending changes that I will push to your branch and then resubmit this PR?

**Comment by dachary** [comment]
@tsg- that's a compelling argument :-) Would you mind doing the upgrade as another pull request ? The implications are beyond the scope of EC and will need review from other parties.

**Comment by tsg-** [comment]
@dachary make sense - we'll handle v2.18 upgrade as a separate PR.  I will only add the missing files from v2.16 to this PR and resubmit - these files are related to avx512 improvements that were part of v2.16 (already the version the ISA-L git submodule is at) and offer upto 200% improvements in EC performance.  Is that OK?

**Comment by dachary** [comment]
Ok, I'll take a look to better undrestand why they are needed.

**Pull request merged**
