### PR TITLE
crimson/os/seastore: introduce JournalTrimmer with refactors

### PR DESCRIPTION
**Pull request by cyx1231st**
The refactor direction is to decouple `TransactionManager` and `Cache` from segment/random_block specific logic.

`AsyncCleaner` might also be moved from `TransactionManager` to `ExtentPlacementManager` to extend EPM to manage the heterogeneous device tiers.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
@zhscn Might want to take a look.

**Review by myoungwon — APPROVED** [review]

**Comment by zhscn** [comment]
Currently `AsyncCleaner` inherits both `JournalTrimmer` and `SegmentProvider`, so it's responsible to trim journal (gc_trim_alloc and gc_trim_dirty) and reclaim space (gc_reclaim_space). But other slower devices, like HDD with SegmentManager, should not store metadata, so HDD version "AsyncCleaner" doesn't need to implement JournalTrimmer interface.

So I want to separate the implementation to two parts:

```cpp
struct JournalTrimmer {
 /// interface
};
struct SegmentProvider {
  /// interface
};

template<typename... T>
class TierBase : public T... { // rename AsyncCleaner to TierBase
  // example: check whether has journal instance at compile time
  bool gc_should_run() const {
    if (disable_trim) return false;
    ceph_assert(init_complete);
    // all journal operations and assertions are wrapped by if constexpr
    if constexpr (std::is_base_of_v<JournalTrimmer, TierBase>) {
      return gc_should_reclaim_space()
        || gc_should_trim_dirty()
        || gc_should_trim_alloc();
    } else {
      return gc_should_reclaim_space();
    }
  }
};

using JournalTier = TierBase<JournalTrimmer, SegmentProvider>;
using HDDTier = TierBase<SegmentProvider>;
```

What do you think?

**Comment by cyx1231st** [comment]
Tier interface should not be segment specific, non-segment device can also form a tier. So I think SegmentProvider is not part of the abstracted tier interface. Instead, the `ExtentOolWriter` is the generic component to proceed ool writes from a specific generation, which is already there.

`JournalTrimmer` is currently solely about getting and setting journal head and tails, nothing related to device tiering.

I think the following features are related to a "Tier":
* Commit extent allocations, like `mark_space_used()` and `mark_space_free()`;
* Control or redirect transaction writes in case the tier is full, like `reserve_projected_usage() -> future`;
* Any other tier related managements or controls;

It might need some PRs to rearrange related logics first before defining the tier interfaces (the existing interfaces might not be appropriate to work with device tiers), and this PR is part of the arrangements.

> But other slower devices, like HDD with SegmentManager, should not store metadata, so HDD version "AsyncCleaner" doesn't need to implement JournalTrimmer interface.

I think so, and more precisely, we need to find a way to decouple journal trimming and segment reclaiming implementations. A cold tier is not responsible to do journaling or trimming, but might need to reuse reclaimming.

**Comment by cyx1231st** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
rebased

**Comment by cyx1231st** [comment]
jenkins test make check

**Comment by cyx1231st** [comment]
@athanatos probably worth to take a look.

Decide to merge to unblock https://github.com/ceph/ceph/pull/46725

**Pull request merged**
