### PR TITLE
ceph-disk: reset PYTHONPATH when executing commands

### PR DESCRIPTION
**Pull request by tchaikov**
would be helpful when testing in a py3 only env.

Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
i run into this issue when testing standalone tests: ceph-disk is launched using python2 in a venv env, while it launches ceph cli using the `PYTHONPATH` pointing to a python2 path. this confused the executed python script, as it failed to find the correct python module.

**Comment by wjwithagen** [comment]
@tchaikov 
I have been running into this problem as well.
For the TOX tests it was fixed by options in the tox-config.
I do remember that `PYTHONPATH` caused trouble in regular runs.
So I would like to run this thru FreeBSD-Jenkins, but first I need to fix other breakage with HEAD.

**Comment by alfredodeza** [comment]
Something else is mangling the PYTHONPATH here, not ceph-disk, I initially thought this would be ceph-disk's doing but there is nothing in ceph-disk's source touching it.

Why should we be adding this machinery into ceph-disk if something else is at fault?

We don't see any issues in ceph-volume here, but I am sure now that this is because no tests are run with the scripts that mess up PYTHONPATH

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-02-28_11:49:25-rados-wip-kefu-testing-2018-02-28-1653-distro-basic-smithi/

**Comment by tchaikov** [comment]
the reason i ran into this issue is https://github.com/ceph/ceph/pull/16709/commits/8c768050a59d61866398ca4c549f68663a0e09e9#diff-5e483a2d055861968b99eacaa3688b6fR19 .

the PYTHONPATH in ceph-disk looks sane when running standalone tests with master HEAD. because it is changed to to non-py2 specific path by https://github.com/ceph/ceph/pull/20589/commits/084011d8fae0916d3ec3d270c418a907fdf0d18f#diff-5e483a2d055861968b99eacaa3688b6fR126.

**Comment by tchaikov** [comment]
see #20646

**Pull request closed without merging**
