### PR TITLE
1.Changes to fix incorrect ip being assigned in case of multiple RDMA…

### PR DESCRIPTION
**Pull request by vsjulu**
… ports.

2. remove rdma local and return error instead to avoid issues with using rdma_local incase of multiple ports.

Sigwned-off-by: Subramanyam Varanasi <s.varanasi@ssi.samsung.com>

### CODE REVIEW

**Comment by vsjulu** [comment]
@mattbenjamin - re submitting a new pull request with the XIO changes alone. Changes are same as whatever you previously approved. Decided to split the commits and pull requests for the XIO vs atmomics change.

**Comment by tchaikov** [comment]
@vsjulu could you add a prefix of the title of your commit message? like "xio: "?

**Comment by tchaikov** [comment]
and your "Signed-off-by" has a typo: `Sigwned-off-by`

**Comment by vsjulu** [comment]
@tchaikov  I have updated the commit message.

**Pull request merged**
