### PR TITLE
radosgw-admin: fix segfault when creating pipe

### PR DESCRIPTION
**Pull request by caisan**
Fixing segfault when create sync group pipe.
Related issues https://tracker.ceph.com/issues/46455

Signed-off-by: caisan <caishan1993@foxmail.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Comment by caisan** [comment]
segfault info:
```
 ceph version 16.2.6 (ee28fb57e47e9f88813e24bbf4c14496ca299d31) pacific (stable)
 1: radosgw-admin(+0x1bd8304) [0x56157b5d7304]
 2: /lib64/libpthread.so.0(+0x12c20) [0x7fdbddb2cc20]
 3: gsignal()
 4: abort()
 5: radosgw-admin(+0x111a457) [0x56157ab19457]
 6: (std::_Optional_base<rgw_bucket, false, false>::_M_get()+0x3e) [0x56157ab28674]
 7: (std::optional<rgw_bucket>::operator->()+0x18) [0x56157ab28692]
 8: (rgw_sync_bucket_entities::set_bucket(std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)+0x93) [0x56157af5ccc1]
 9: main()
 10: __libc_start_main()
 11: _start()
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
```

**Comment by caisan** [comment]
@cbodley @yehudasa please review it.

**Comment by caisan** [comment]
jenkins retest this please

**Comment by mattbenjamin** [comment]
@yehudasa any update on when this could be reviewed?

**Pull request closed without merging**
