### PR TITLE
mon/MonCommands: remove obsolete commands 

### PR DESCRIPTION
**Pull request by tchaikov**
## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by batrick** [comment]
I think we planned to keep these indefinitely so that the user gets a proper error message about the command being obsolete?

**Comment by tchaikov** [comment]
@batrick i did some research on the "plan". https://ceph-users.ceph.narkive.com/iUh4e0nj/rfc-deprecating-ceph-tool-commands is what i found. could you help me find the version which claims that we should keep these command forever?

**Comment by batrick** [comment]
Sorry I don't think it was written down somewhere.

It's okay I think to remove any obsolete command that has been obsolete for 2 releases. We should probably start marking newly obsolete commands with the release they should be removed completely. I'm not sure about all of the ones you're obsoleting but the `ceph mds...` commands should be good to remove.

**Comment by tchaikov** [comment]
@batrick thank you, Patrick! just added Sage for his inputs. i checked all the commands being removed in this changeset, all of them have been marked obsolete for more than two releases.

**Review by batrick — APPROVED** [review]

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2021-06-13_08:30:20-rados-wip-kefu-testing-2021-06-13-1215-distro-basic-smithi/
- https://pulpito.ceph.com/kchai-2021-06-13_13:23:30-rados-wip-kefu-testing-2021-06-13-2001-distro-basic-smithi/

**Comment by batrick** [comment]
https://tracker.ceph.com/projects/cephfs/wiki/Master#2021-June-13

**Pull request merged**
