### PR TITLE
os: fix stat of used-space overflow

### PR DESCRIPTION
**Pull request by xiexingguo**
Fixes: #14189
Signed-off-by: xie xingguo <xie.xingguo@zte.com.cn>

### CODE REVIEW

**Comment by liewegas** [comment]
does not compile.. missing ()

**Comment by xiexingguo** [comment]
@liewegas 
Fixed. Well, I do miss the old loic-bot fashion:))

**Comment by liewegas** [comment]
os/memstore/MemStore.cc: In member function ‘int MemStore::_truncate(coll_t, const ghobject_t&, uint64_t)’:
os/memstore/MemStore.cc:1001:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (o->get_size() >= old_size)

**Comment by xiexingguo** [comment]
I am sorry. How about this?

**Comment by xiexingguo** [comment]
Rebased.

**Comment by xiexingguo** [comment]
@tchaikov Indeed. And @liewegas  you may feel free to close this request:)

**Pull request closed without merging**
