### PR TITLE
pacific: test: disable mgr/mirroring for `test_mirroring_init_failure_with_recovery` test

### PR DESCRIPTION
**Pull request by singuliere**
backport tracker: https://tracker.ceph.com/issues/50185

---

backport of https://github.com/ceph/ceph/pull/40465
parent tracker: https://tracker.ceph.com/issues/50020

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
jenkins test api

**Comment by singuliere** [comment]
jenkins test this please

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Review by batrick — APPROVED** [review]

**Pull request merged**
