### PR TITLE
rgw/auth: correcting the error message to indicate

### PR DESCRIPTION
**Pull request by pritha-srivastava**
clearly that a pre-signed URL has expired.

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
dout messages only help if the user is also an admin that can look at rgw debug logs. it would be even better if we could add a Message to the xml Error response using `s->err.message` so clients could see the reason

this auth code doesn't have ready access to the req_state, so we'd have to do something else.. for example, add a special error code ERR_PRESIGNED_URL_EXPIRED to return there, then map that back to EPERM and add a message where we have a req_state

**Comment by pritha-srivastava** [comment]
@cbodley : I can see that you have approved the PR, but you have additional comments, do you want those comments to be addressed as a part of this PR?

**Comment by mattbenjamin** [comment]
(I asked for us to consider this in, iirc, gchat)

**Comment by cbodley** [comment]
> @cbodley : I can see that you have approved the PR, but you have additional comments, do you want those comments to be addressed as a part of this PR?

up to you guys. i approved the PR because it improves existing error messages, and is obviously correct - we could merge it without qa. but if you think the s->err.message changes are important, you can either follow up on that here or as a separate pr

**Comment by mattbenjamin** [comment]
I'd say do it in this one, if it's not difficult, and I don't remember it being?

**Comment by pritha-srivastava** [comment]
> I'd say do it in this one, if it's not difficult, and I don't remember it being?

I'll do it in this PR

**Comment by cbodley** [comment]
jenkins test make check

**Review by cbodley — APPROVED** [review]

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
@pritha-srivastava do you think this is worth backports? if so, would you please create a tracker for it?

**Pull request merged**
