### PR TITLE
Wip cmake vstart

### PR DESCRIPTION
**Pull request by yehudasa**

### CODE REVIEW

**Comment by yehudasa** [comment]
@tchaikov right, CEPH_LIB needs to point at .libs

**Comment by yehudasa** [comment]
@tchaikov need to do a make install at this point. Not sure if everything can be set individually, but it just might be.

**Comment by tchaikov** [comment]
@yehudasa do you want to target this change to master or hammer? i am not sure that this change is involving any feature, so i guess we could apply it to master first?

**Comment by mattbenjamin** [comment]
Thanks for doing this!

**Comment by yehudasa** [comment]
@tchaikov I was aiming at hammer.

**Pull request merged**
