### PR TITLE
mgr/dashboard: Move features to advanced section and expand by default rbd config section

### PR DESCRIPTION
**Pull request by afreen23**
Fixes https://tracker.ceph.com/issues/65207

- Moves "features" section in rbd image create form to "Advanced" section.
- makes rbd configuration section to be expanded by default rather than
  being collapsed as it has only single section. This will improve user experience as it will not
require two clicks.
- updates e2e test

[Screencast from 2024-04-05 17-31-30.webm](https://github.com/ceph/ceph/assets/25664409/1b93e39c-2611-4b85-929f-dc593aa4b1ba)

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [x] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [x] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Review by cloudbehl — APPROVED** [review]
Any screenshots? Changes look good to me.

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by cloudbehl** [comment]
@afreen23 This looks great.

For features can we have proper descriptions[1] of each features, not as part of this PR probably different one. But just saw its not there and we can follow how we did it with RGW create.

[1]. https://docs.ceph.com/en/latest/rbd/rbd-config-ref/#image-features

**Comment by afreen23** [comment]
> @afreen23 This looks great.
> 
> For features can we have proper descriptions[1] of each features, not as part of this PR probably different one. But just saw its not there and we can follow how we did it with RGW create.
> 
> [1]. https://docs.ceph.com/en/latest/rbd/rbd-config-ref/#image-features

The descriptions are present under the tooltips

**Comment by afreen23** [comment]
jenkins make check arm64

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
@nizamial09 updated "rbd config" section to be opened by default as discussed offline.
Screencast is updated!

Thanks!

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
tests for `pools.e2e.spec.ts` failing as the rbd configuration section is by default opened.
Fixed that , so now it will look like:

[Screencast from 2024-04-12 22-00-46.webm](https://github.com/ceph/ceph/assets/25664409/b70c2eb2-d78d-4698-a497-92e5848950fd)

Thanks!

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test api

**Comment by afreen23** [comment]
jenkins test window

**Comment by afreen23** [comment]
jenkins test make check arm 64

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test windows

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test make check arm64

**Comment by afreen23** [comment]
jenkins test dashboard

**Comment by afreen23** [comment]
rgw roles tests are flaky and keep failing:
image

make check arm64 feeling due to:

```
apt-get error

 Unable to locate package ceph-libboost-atomic1.82-dev

[Indication 1](https://jenkins.ceph.com/job/ceph-pull-requests-arm64/55157/consoleFull#60563243fa534114-2506-4c16-be9c-09c932a5aa49)
	
CTest Failure

3 tests failed out of 292

Total Test time (real) = 2426.25 sec

The following tests FAILED:
	 34 - run-rbd-unit-tests-127.sh (Failed)
	 57 - unittest_mempool (Failed)
	266 - unittest-fltree-onode-manager (Failed)
```

**Both unrelated to my PR**

**Pull request merged**
