### PR TITLE
mimic: qa/suites/upgrade/mimic-p2p: allow target version to apply

### PR DESCRIPTION
**Pull request by liewegas**
Was this specifying mimic for a specific reason?

### CODE REVIEW

**Comment by yuriw** [comment]
@liewegas what's the logic for this ?

**Comment by smithfarm** [comment]
@yuriw I think the idea here is that, when v13.2.1 is tagged and packages are built, we will make the following change:

```
 - install.upgrade:
     #exclude_packages: ['ceph-mgr','libcephfs2','libcephfs-devel','libcephfs-dev']
     mon.a:
+      tag: v13.2.1
     mon.b:
+      tag: v13.2.1
```

and "branch: mimic" would interfere with that, so it has to go.

**Comment by yuriw** [comment]
@smithfarm that's great

but will we be able to use `branch: xxx` ?

```
 - install.upgrade:
     mon.a:
+      branch: v13.2.1
     mon.b:
+     branch : v13.2.1
```

**Comment by smithfarm** [comment]
@yuriw: No, that wouldn't work. But `tag: v13.2.1` will work fine.

**Comment by yuriw** [comment]
I misspoke sorry, meant: 

```
 - install.upgrade:
     mon.a:
+      branch: mimic
     mon.b:
+     branch : mimic
```

**Comment by smithfarm** [comment]
@yuriw: I see what you mean now.

> Was this specifying mimic for a specific reason?

@liewegas I think the reason is that we want this suite to test the upgrade from the most recent mimic point to tip-of-mimic. Once the fix for http://tracker.ceph.com/issues/25129 goes in, "branch: mimic" will mean "tip-of-mimic".

**Comment by yuriw** [comment]
@smithfarm 

`Was this specifying mimic for a specific reason?` no, any upgrade going to `-x`
I was under impression that either using `branch: xxx` or omitting this like in `install.upgrade` task will use the tip of the branch and therefor paying attention on what's going on around this area. 

Personally, I feel that being explicit and using `branch: xxx` is better.

**Comment by smithfarm** [comment]
@yuriw I agree with you, but specifying a branch with `--ceph` on the command line is required, and is also "explicit" (it gets translated into "sha1: <tip>"). And "branch: mimic" in its current implementation is not explicit. Hence this PR - I would have approved it.

**Comment by liewegas** [comment]
The problem with putting branch: mimc htere is you can't test code without merging it.  I was trying to verify I fixed a problem with the 13.2.0 release but it would only upgrade to mimic; -c wip-my-fix wouldn't test it.

Every other test suite lets you specify a final version.  I don't think this one should be different.

**Comment by smithfarm** [comment]
Very good point.

**Pull request merged**
