### PR TITLE
test/osd/TestPGLog: Fix confusing description between log and olog.

### PR DESCRIPTION
**Pull request by dheart-joe**
TestPGLog.cc has mistake description, need to fix it.

Fix https://tracker.ceph.com/issues/56709
Signed-off-by: dheart <dheart_joe@163.com>

### CODE REVIEW

**Comment by athanatos** [comment]
Description does seem wrong, but shouldn't it be

```
-      The log entry (1,3) deletes the object x9 but the olog entry
-      (2,3) modifies it : remove it from omissing.
+      The log entry (2,3) deletes the object x9 but the olog entry
+      (1,3) modifies it : remove it from omissing.
```
?

**Comment by dheart-joe** [comment]
yeah.
I have resubmitted,take the time to check.

**Comment by athanatos** [comment]
Squash the two commits together.

**Comment by dheart-joe** [comment]
@athanatos so, sholud I resubmit pr or keep this pr?

**Review by athanatos — APPROVED** [review]
LGTM, marking needs-qa

**Comment by athanatos** [comment]
retest this please

**Comment by tchaikov** [comment]
- https://pulpito.ceph.com/kchai-2022-08-07_05:39:26-rados-wip-kefu-testing-2022-08-07-1123-distro-default-smithi/
- https://pulpito.ceph.com/kchai-2022-08-07_07:44:14-rados-wip-kefu-testing-2022-08-07-1123-distro-default-smithi/

the `sudo yum -y install ceph-radosgw` failures are tracked by https://tracker.ceph.com/issues/57051

**Comment by tchaikov** [comment]
jenkins test make check

**Pull request merged**
