### PR TITLE
rgw: fix extra_data_len handling in PutObj filters

### PR DESCRIPTION
**Pull request by cbodley**
the RGWPutObj_Compress filter relies on a starting offset of 0 to ensure
that we only compress entire objects

for RGWRados::fetch_remote_obj(), we also fetch object metadata. the
replies come back with a 'Rgwx-Embedded-Metadata-Len' header, which
specifies how many bytes of object metadata are at the front of the
request body. when this is present, the offsets passed from
RGWRadosPutObj down to the RGWPutObjDataProcessor filters are offsets
into the http response body, rather than logical offsets into the object
data itself

this commit adds a transformation to RGWRadosPutObj so that only that
logical offset is visible to the RGWPutObjDataProcessor

Fixes: http://tracker.ceph.com/issues/21895

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri4-testing-2017-10-23-2051](https://trello.com/c/MNm7d7Sj/187-wip-yuri4-testing-2017-10-23-2051)

**Comment by cbodley** [comment]
lots of `FAILED assert(uint64_t(ofs) >= extra_data_len)` from [multisite tests](http://qa-proxy.ceph.com/teuthology/yuriw-2017-10-23_22:12:03-rgw-wip-yuri4-testing-2017-10-23-2051-distro-basic-smithi/1766215/teuthology.log)

**Comment by cbodley** [comment]
@yuriw updated to fix those assertions, could you please reschedule?

**Comment by yuriw** [comment]
[wip-yuri-testing-2017-10-25-2239](https://trello.com/c/fggJzPi0/188-wip-yuri-testing-2017-10-25-2239)

**Comment by cbodley** [comment]
@yehudasa this fix compression on sync in multisite - could you please review?

**Comment by yuriw** [comment]
@yehudasa tested and ready for merge

**Pull request merged**
