### PR TITLE
pacific: mon: avoid exception when setting require-osd-release more than 2

### PR DESCRIPTION
**Pull request by RaminNietzsche**
versions up.

Request for additional confirmation instead.

Fixes: https://tracker.ceph.com/issues/58156

Signed-off-by: RaminNietzsche <Ramin.Najarbashi@gmail.com>

## Checklist

- Tracker
  - [x] References tracker ticket https://tracker.ceph.com/issues/58156
- Component impact
  - [ ] Affects Dashboard, opened tracker ticket
  - [ ] Affects Orchestrator, opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests
  - [ ] Includes unit test(s)
  - [ ] Includes integration test(s)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

### CODE REVIEW

**Review by ifed01 — APPROVED** [review]

**Comment by ifed01** [comment]
jenkins test api

**Comment by k0ste** [comment]
https://tracker.ceph.com/issues/59455 - backport issue

**Review by ifed01 — DISMISSED** [review]

**Comment by k0ste** [comment]
Also, seems commit was not cherry-picked correctly

**Comment by ifed01** [comment]
>Also, seems commit was not cherry-picked correctly
Indeed.

@RaminNietzsche - please use |cherry-pick -x " command

**Comment by ljflores** [comment]
Rados suite review: http://pulpito.front.sepia.ceph.com/?branch=wip-yuri5-testing-2023-04-25-0837-pacific

Failures, unrelated:
    1. https://tracker.ceph.com/issues/59192
    2. https://tracker.ceph.com/issues/55347
    3. https://tracker.ceph.com/issues/54071
    4. https://tracker.ceph.com/issues/57386
    5. https://tracker.ceph.com/issues/59529
    6. https://tracker.ceph.com/issues/59530
    7. https://tracker.ceph.com/issues/57255

Details:
    1. cls/test_cls_sdk.sh: Health check failed: 1 pool(s) do not have an application enabled (POOL_APP_NOT_ENABLED) - Ceph - RADOS
    2. SELinux Denials during cephadm/workunits/test_cephadm - Ceph - Orchestrator
    3. rados/cephadm/osds: Invalid command: missing required parameter hostname(<string>) - Ceph - Orchestrator
    4. cephadm/test_dashboard_e2e.sh: Expected to find content: '/^foo$/' within the selector: 'cd-modal .badge' but never did - Ceph - Mgr - Dashboard
    5. mds_upgrade_sequence: overall HEALTH_ERR 1 filesystem with deprecated feature inline_data; 1 filesystem is offline; 1 filesystem is online with fewer MDS than max_mds - Ceph - CephFS
    6. mgr-nfs-upgrade: mds.foofs has 0/2 - Ceph - CephFS
    7. rados/cephadm/mds_upgrade_sequence, pacific : cephadm [ERR] Upgrade: Paused due to UPGRADE_NO_STANDBY_MGR: Upgrade: Need standby mgr daemon - Ceph - Orchestrator

**Comment by k0ste** [comment]
@RaminNietzsche please make a `cherry-pick -x` for backport. Thanks!

**Pull request closed without merging**
