### PR TITLE
mgr/dashboard: fix closing tag in app.component.html

### PR DESCRIPTION
**Pull request by s0nea**
Signed-off-by: Tatjana Dehler <tdehler@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by s0nea** [comment]
jenkins test make check

**Comment by s0nea** [comment]
jenkins test dashboard

**Comment by p-na** [comment]
Does it have any negative effect so that we want or need to backport that fix?

**Comment by s0nea** [comment]
@p-na
> Does it have any negative effect so that we want or need to backport that fix?
There is no issue I'm aware of currently.

**Comment by s0nea** [comment]
jenkins test dashboard

**Comment by LenzGr** [comment]
Thank you! Does this fix require being backported to Nautilus?

**Comment by s0nea** [comment]
@LenzGr 

> Thank you! Does this fix require being backported to Nautilus?

I don't see a reason for backporting the PR but maybe anyone else @ricardoasmarques @tspmelo @Exotelis @epuertat ?

**Pull request merged**
