### PR TITLE
osd/PGLog: Avoid rmissing index value conflicts

### PR DESCRIPTION
**Pull request by cxytt**
missing log: 5124'4491(5115'4489) 1000002101d.00000000:head by client.684196.0:77304
master log:  5141'4491(5115'4490) 10000020c32.00000002:head by client.629257.0:16618
1. osd extending head to 5141'4491, add 10000020c32.00000002:head to rmissing
2. osd merge divergent log, remove 1000002101d.00000000:head from missing & rmissing
Both objects have the same version_t, the rmissing collection is empty

Signed-off-by: Tao Ning <ningtao@sangfor.com.cn>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by cxytt** [comment]
`2019-07-09 22:57:05.878707 7f19b0295700 10 osd.10 pg_epoch: 5165 pg[3.3a( v 5124'4491 lc 5115'4490 (2583'2864,5124'4491] local-lis/les=5130/5136 n=157 ec=137/137 lis/c 5162/5097 les/c/f 5163/5100/0 5164/5164/5160) [9,4,5,1,10] r=4 lpr=5164 pi=[5097,5164)/6 crt=5124'4491 lcod 0'0 unknown m=1] state<Started/Stray>: got info+log from osd.9 3.3a( v 5141'4491 (2583'2864,5141'4491] local-lis/les=5164/5165 n=157 ec=137/137 lis/c 5162/5097 les/c/f 5163/5100/0 5164/5164/5160) log((5115'4490,5141'4491], crt=5141'4491)
2019-07-09 22:57:05.878718 7f19b0295700 10 merge_log log((5115'4490,5141'4491], crt=5141'4491) from osd.9 into log((2583'2864,5124'4491], crt=5124'4491)
2019-07-09 22:57:05.878723 7f19b0295700 10 merge_log extending head to 5141'4491
2019-07-09 22:57:05.879206 7f19b0295700 10 merge_log divergent 5124'4491 (5115'4489) modify   3:5d39f2f3:::1000002101d.00000000:head by client.684196.0:77304 2019-07-09 22:54:56.599995 0 raft_grpupid=3 raft_term=158
2019-07-09 22:57:05.879260 7f19b0295700 10 _merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head prior_version: 5115'4489 first_divergent_update: 5124'4491 last_divergent_update: 5124'4491
2019-07-09 22:57:05.879265 7f19b0295700 10 _merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head has no more recent entries in log
2019-07-09 22:57:05.879267 7f19b0295700 10 _merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head missing, 5124'4491(5115'4489) flags = none adjusting
2019-07-09 22:57:05.879273 7f19b0295700 10 _merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head missing.have is prior_version 5115'4489 removing from missing`

**Comment by cxytt** [comment]
osd.log
`merge_log log((5115'4490,5141'4491], crt=5141'4491) from osd.9 into log((2583'2864,5124'4491], crt=5124'4491)
merge_log extending head to 5141'4491
merge_log divergent 5124'4491 (5115'4489) modify   3:5d39f2f3:::1000002101d.00000000:head by client.684196.0:77304 2019-07-09 22:54:56.599995 0 raft_grpupid=3 raft_term=158
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head prior_version: 5115'4489 first_divergent_update: 5124'4491 last_divergent_update: 5124'4491
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head has no more recent entries in log
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head missing, 5124'4491(5115'4489) flags = none adjusting
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head missing.have is prior_version 5115'4489 removing from missing`

**Comment by cxytt** [comment]
osd.log
merge_log log((5115'4490,5141'4491], crt=5141'4491) from osd.9 into log((2583'2864,5124'4491], crt=5124'4491)
merge_log extending head to 5141'4491
merge_log divergent 5124'4491 (5115'4489) modify   3:5d39f2f3:::1000002101d.00000000:head by client.684196.0:77304 2019-07-09 22:54:56.599995 0 raft_grpupid=3 raft_term=158
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head prior_version: 5115'4489 first_divergent_update: 5124'4491 last_divergent_update: 5124'4491
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head has no more recent entries in log
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head missing, 5124'4491(5115'4489) flags = none adjusting
_merge_object_divergent_entries: hoid 3:5d39f2f3:::1000002101d.00000000:head missing.have is prior_version 5115'4489 removing from missing

**Comment by cxytt** [comment]
reset this please

**Comment by cxytt** [comment]
retest this please

**Comment by cxytt** [comment]
retest this please

**Comment by cxytt** [comment]
retest this please

**Comment by cxytt** [comment]
retest this please

**Comment by neha-ojha** [comment]
@cxytt can you please rebase this?

**Pull request closed without merging**
