### PR TITLE
mimic: ceph-volume: add methods to pass filters to pvs, vgs and lvs commands

### PR DESCRIPTION
**Pull request by jan--f**
Filters can be passed to these commands by using option '-S'.

Signed-off-by: Rishabh Dave <ridave@redhat.com>
(cherry picked from commit a4f2fcefb80df524c472782e8c1d18b3c2d1c1fc)

Backport of #32242

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by rishabh-d-dave** [comment]
@jan--f Wouldn't it better to wait until we can run functional tests?

**Comment by rishabh-d-dave** [comment]
Looks valid -
```
ceph_volume/tests/api/test_lvm.py:3:1: F401 'mock.mock.patch' imported but unused
ERROR: InvocationError for command /home/jenkins-build/build/workspace/ceph-volume-pr/src/ceph-volume/.tox/flake8/bin/flake8 --select=F,E9 ceph_volume (exited with code 1)
```

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
jenkins test ceph-volume tox

**Comment by jan--f** [comment]
Tox failure is a false positive.

**Pull request merged**
