### PR TITLE
nautilus: mds: After restarting an mds, its standy-replay mds remained in the "resolve" state

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/47090

### CODE REVIEW

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
@epuertat Repeated failures in `ceph API tests` check. What to do?

**Comment by epuertat** [comment]
> @epuertat Repeated failures in `ceph API tests` check. What to do?

There was [this tracker](https://tracker.ceph.com/issues/46815) but @Devp00l closed it (in master). Perhaps there's a missing fix in nautilus? I will check it.

**Comment by smithfarm** [comment]
jenkins test api

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-10-05-0922-nautilus](https://trello.com/c/jikOLW3R/1033-wip-yuri3-testing-2020-10-05-0922-nautilus)

**Review by ajarr — APPROVED** [review]

**Pull request merged**
