### PR TITLE
msg: add entity_addr_t types; add new entity_addrvec_t type

### PR DESCRIPTION
**Pull request by liewegas**
This PR does two things:

* Changes entity_addr_t to have a type field, so that a NONE and LEGACY addr are distinct. We also add a MSGR2 type, although it isn't used yet.
* Adds the new entity_addrvec_t type.  Not yet used.

This needs to go through teuthology and to get merged sooner rather than later.  The main source of bugs it surfaces are instances where we create an entity_addr_t and set the fields (family, sockaddr) without setting the type.  I think I fixed them all (grepped for set_family, set_nonce, etc.), but may have missed some.

### CODE REVIEW

**Comment by liewegas** [comment]
ready for review!

**Comment by liewegas** [comment]
@yuyuyu101 can you look?

**Comment by yuyuyu101** [comment]
Good Move

**Comment by yuriw** [comment]
FYI
The following tests FAILED:
	  5 - cephtool-test-mon.sh (Failed)
	 14 - run-tox-ceph-disk (Failed)
	 15 - run-tox-ceph-detect-init (Failed)

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-08-29_22:13:15-rados-wip-yuri-testing2_2016_08_29-distro-basic-smithi/

**Comment by yuriw** [comment]
@liewegas I reclaimed `wip-yuri-testing2`, let me know when this PR needs more testing

**Comment by liewegas** [comment]
Needs to come after #11284

**Comment by liewegas** [comment]
http://pulpito.ceph.com/sage-2016-10-24_00:49:43-upgrade:jewel-x-wip-sage-testing2---basic-smithi/

**Comment by liewegas** [comment]
I think this one's finally ready for merge!  Passes rados and upgrade suites, and the various upgrade feature bit fixes are in place.

We may end up adjusting the feature bit later depending on whether hte kernel support for this happens at the same time as btime and change_attr

**Comment by yuriw** [comment]
cool :+1:

**Comment by tchaikov** [comment]
i am still reviewing it..

**Comment by tchaikov** [comment]
lgtm

**Pull request merged**
