### PR TITLE
mon: Do not display any pools, pgs and objects if there is no osd.

### PR DESCRIPTION
**Pull request by shinobu-x**
In `ceph -s`, there are still pool(s), pgs and object(s) even there is no osd in the cluster, and these osds are no longer in CRUSH Map.

```
osd: 0 osds: 0 up, 0 in

data:
print_summary
    pools:   2 pools, 16 pgs
    objects: 21 objects, 2.19K
    usage:   0 used, 0 / 0 avail
    pgs:     42/63 objects degraded (66.667%)
             16 stale+active+undersized+degraded
```

This is not a bug however makes users confused.

http://tracker.ceph.com/issues/22206

Signed-off-by: Shinobu Kinjo <shinobu@redhat.com>

### CODE REVIEW

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
test this please

**Comment by liewegas** [comment]
The problem the user saw was due to the ceph-mgr daemon not running.

**Pull request closed without merging**
