### PR TITLE
luminous: mgr/restful: fix py got exception when get osd info

### PR DESCRIPTION
**Pull request by b-ranto**
http://tracker.ceph.com/issues/38257

### CODE REVIEW

**Comment by yuriw** [comment]
[wip-yuri6-testing-2019-02-13-1800-luminous](https://trello.com/c/B96YdIDM/538-wip-yuri6-testing-2019-02-13-1800-luminous)

**Comment by tchaikov** [comment]
needs #26421 also.

**Comment by b-ranto** [comment]
The #26421 was merged to master and back-ported, returning the old labels (all but wip-yuri6-testing, that might need an update).

**Comment by yuriw** [comment]
[wip-yuri4-testing-2019-02-27-2159-luminous](https://trello.com/c/rdUQQoLb/550-wip-yuri4-testing-2019-02-27-2159-luminous)

**Pull request merged**
