### PR TITLE
osd: clear pg_stat_queue after stopping pgs

### PR DESCRIPTION
**Pull request by liewegas**
Fixes: #14212
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
passed a wip-sage-testing run

**Comment by tchaikov** [comment]
lgtm. the pg will enqueue its own stat again once it is activated, so the stat is not lost.

**Comment by tchaikov** [comment]
@liewegas shall we backport this fix to infenalis and hammer?

**Comment by liewegas** [comment]
sure..

**Comment by tchaikov** [comment]
okay, updated http://tracker.ceph.com/issues/14212 accordingly.

**Pull request merged**
