### PR TITLE
pacific: rgw: resolve empty ordered bucket listing results w/ CLS filtering *and* bucket index list produces incorrect result when non-ascii entries

### PR DESCRIPTION
**Pull request by dvanders**
backport tracker: https://tracker.ceph.com/issues/52075

---

backport of https://github.com/ceph/ceph/pull/42125 and https://github.com/ceph/ceph/pull/42404 and https://github.com/ceph/ceph/pull/44562
parent trackers: https://tracker.ceph.com/issues/51462 and https://tracker.ceph.com/issues/51429

### CODE REVIEW

**Comment by dvanders** [comment]
To do the backport cleanly I needed the commit from https://github.com/ceph/ceph/pull/44815, which is currently DNM, so I marked this DNM too.

**Comment by dvanders** [comment]
jenkins retest this please

**Comment by dvanders** [comment]
This was missing a fixed bi_list test. Re-qa it please.

**Comment by cfsnyder** [comment]
@dvanders looks like this should also include this follow-up fix: https://github.com/ceph/ceph/pull/42836/commits/fa90bc0b4cdcc72273a750ce207acc3c3b5a6d11

**Review by ivancich — APPROVED** [review]
This looks good. Thank you for undertaking the effort! As mentioned in another comment, adding one more commit would fix some additional bugs and would save us another PR. Thank you for considering!

**Comment by dvanders** [comment]
> This looks good. Thank you for undertaking the effort! As mentioned in another comment, adding one more commit would fix some additional bugs and would save us another PR. Thank you for considering!

Done, I also brought in a dependent logging change to make 5b8af180e2e749a99edd8a2e14011fcff64a42a9 apply cleanly.

**Comment by dvanders** [comment]
jenkins retest this please

**Pull request merged**
