### PR TITLE
ceph-volume: removed the explicit use of sudo

### PR DESCRIPTION
**Pull request by andrewschoen**
This will allow users to run ceph-volume on systems that do
not have sudo installed.

Fixes: http://tracker.ceph.com/issues/22282

Signed-off-by: Andrew Schoen <aschoen@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
jenkins test ceph-volume tox

**Comment by andrewschoen** [comment]
jenkins test ceph-volume all

**Comment by alfredodeza** [comment]
jenkins test ceph-volume all

**Comment by alfredodeza** [comment]
ah of course, there is no `prepare_activate` in ceph-ansible, so those are always going to fail

**Pull request merged**
