### PR TITLE
test/cls_rbd: mask newer feature bits to support upgrade tests

### PR DESCRIPTION
**Pull request by dillaman**
Fixes: http://tracker.ceph.com/issues/21217
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman Don't you think it is a good idea to mask newer feature bits in `get_all_features` client function?

**Comment by trociny** [comment]
@dillaman Recaliing why this function was introduced, it was a  silly question.

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2017-09-06_16:53:24-upgrade:luminous-x-wip-yuri-testing4-2017-09-06-1531-distro-basic-smithi/

@dillaman do you want `rbd` suite tested on this PR as well ?

**Comment by dillaman** [comment]
@yuriw I wouldn't expect any upgrade tests to pass until it is backported to the older release branches.

**Comment by yuriw** [comment]
@dillaman this is upgrade:luminous-x suite I though it should pass

**Comment by dillaman** [comment]
@yuriw yes -- luminous-x should pass

**Comment by yuriw** [comment]
http://pulpito.front.sepia.ceph.com:80/yuriw-2017-09-06_17:10:29-rbd-wip-yuri-testing4-2017-09-06-1531-distro-basic-smithi/

**Pull request merged**
