### PR TITLE
[RFC] mgr/orchestrator: Add unified command line parsing for PlacementSpec

### PR DESCRIPTION
**Pull request by sebastian-philipp**
- [ ] **Depends on #31042**

This makes `ceph orchestrator mon update` less awkward, by no longer requiring a count

A single integer is parsed as a count:

```
ceph orchestrator add foobar 3
>>> PlacementSpec(count=3)
```
A list of names is parsed as host specifications:
```
ceph orchestrator add foobar host1 host2
>>> PlacementSpec(label=[HostSpec(hostname='host1', network='', name=''), HostSpec(hostname='host2', network='', name='')])
```
You can also prefix the hosts with a count as follows:
```
ceph orchestrator add foobar 2 host1 host2
>>> PlacementSpec(label=[HostSpec(hostname='host1', network='', name=''), HostSpec(hostname='host2', network='', name='')], count=2)
```
You can spefify labels using `label:<label>`
```
ceph orchestrator add foobar label:mon
>>> PlacementSpec(label='label:mon')
```
Labels als support a count:
```
ceph orchestrator add foobar 3 label:mon
PlacementSpec(label='label:mon', count=3)
```

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard backend`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by liewegas** [comment]
Yes!  I like this a lot more than all of those awkward arguments.  The only downside I see is that you can't be explicit in a traditional argument style as you could before (e.g., ``--count 3 --label foo``), but I think the string parsing is still unambiguous, so it's better overall!

**Comment by jschmid1** [comment]
that change makes sense imo. I have to agree with sage here that an explicit style (`--par`) is probably something that a user expects to able to use.

**Comment by sebastian-philipp** [comment]
> that change makes sense imo. I have to agree with sage here that an explicit style (`--par`) is probably something that a user expects to able to use.

do you have an idea how make this work, without marking parameters as non-positional?

**Comment by jschmid1** [comment]
> > that change makes sense imo. I have to agree with sage here that an explicit style (`--par`) is probably something that a user expects to able to use.
> 
> do you have an idea how make this work, without marking parameters as non-positional?

With a bit more extensive parsing in the `from_strings` method I guess.. If people want to use the `--` notation it's still passed as one string.

**Comment by sebastian-philipp** [comment]
> > > that change makes sense imo. I have to agree with sage here that an explicit style (`--par`) is probably something that a user expects to able to use.
> > 
> > 
> > do you have an idea how make this work, without marking parameters as non-positional?
> 
> With a bit more extensive parsing in the `from_strings` method I guess.. If people want to use the `--` notation it's still passed as one string.

I'd think that this won't work, as the parameter parsing for `--parameter` is already done in the ceph cli binary.

**Comment by jschmid1** [comment]
> > > > that change makes sense imo. I have to agree with sage here that an explicit style (`--par`) is probably something that a user expects to able to use.
> > > 
> > > 
> > > do you have an idea how make this work, without marking parameters as non-positional?
> > 
> > 
> > With a bit more extensive parsing in the `from_strings` method I guess.. If people want to use the `--` notation it's still passed as one string.
> 
> I'd think that this won't work, as the parameter parsing for `--parameter` is already done in the ceph cli binary.

right.. well then, I'd be ok with dropping the more explicit `--` notation.

**Comment by sebastian-philipp** [comment]
Ok, lets make #31042 a dependency.

**Pull request closed without merging**
