### PR TITLE
pacific: mgr/dashboard: Remove username, password fields from Manager Modules/dashboard,influx

### PR DESCRIPTION
**Pull request by aaSharma14**
backport tracker: https://tracker.ceph.com/issues/50051

---

backport of https://github.com/ceph/ceph/pull/39908
parent tracker: https://tracker.ceph.com/issues/49645

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by tchaikov** [comment]
```
188/214 Test #211: unittest-extmap-manager ...................***Failed    0.90 sec
WARNING: debug mode. Not for benchmarking or production
ERROR 2021-03-30 06:58:50,973 [shard 5] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application

        Start 212: test-seastore-onode-tree-node
189/214 Test #210: unittest-seastore-cache ...................***Failed    1.18 sec
WARNING: debug mode. Not for benchmarking or production
ERROR 2021-03-30 06:58:51,067 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application

        Start 213: unittest-staged-fltree
190/214 Test #212: test-seastore-onode-tree-node .............   Passed    0.24 sec
        Start 214: run-tox-qa
191/214 Test #213: unittest-staged-fltree ....................***Failed    1.14 sec
WARNING: debug mode. Not for benchmarking or production
ERROR 2021-03-30 06:58:52,158 [shard 0] seastar - Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application
```

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins test api

**Comment by aaSharma14** [comment]
jenkins test api

**Review by alfonsomthd — APPROVED** [review]

**Review by nizamial09 — APPROVED** [review]

**Comment by aaSharma14** [comment]
jenkins test api

**Pull request merged**
