### PR TITLE
rgw:add test case for specific bucket sync in multisite.

### PR DESCRIPTION
**Pull request by zhangsw**
This test case is for https://github.com/ceph/ceph/pull/10995
Signed-off-by: Zhang Shaowen <zhangshaowen@cmss.chinamobile.com>

### CODE REVIEW

**Comment by zhangsw** [comment]
@cbodley I create a test case for bucket sync enable and disable in https://github.com/ceph/ceph/pull/10995. I've tested it against that feature but it seems that something is  wrong when re-syncing the bucket. I haven't figured out what's the reason of that. Is there something wrong with my test case?

**Comment by cbodley** [comment]
@zhangsw the test looks right. we'll need to look through the radosgw logs to figure out why the bucket sync didn't trigger

**Comment by zhangsw** [comment]
@cbodley I've tested this several times again and they are all passed. I don't know why it failed yesterday...

**Comment by cbodley** [comment]
@zhangsw that sounds promising. i'll find some time to run this myself, and see if i can reproduce any failures

**Comment by cbodley** [comment]
i did do some testing, and saw it pass in most runs. i did see a failure when i ran with `num_zones = 9`, but it was too much output to get through at the time

**Comment by zhangsw** [comment]
@cbodley I tested it with multi zones and it passed when the number of zone is below 8. When the number increased, I met some failures. I found that some rgws were stopped. According to the logs, the error was caused by bufferlist operation, like 'clear' or 'copy_all'. And other test cases also had the same problem.

**Comment by cbodley** [comment]
this was merged as part of https://github.com/ceph/ceph/pull/15801

**Pull request closed without merging**
