### PR TITLE
luminous: mds: message invalid access

### PR DESCRIPTION
**Pull request by batrick**
Otherwise we have invalid reads. Caught by valgrind.

Fixes: http://tracker.ceph.com/issues/38488
Signed-off-by: Patrick Donnelly <pdonnell@redhat.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by smithfarm** [comment]
@batrick Ideally, the commit message would explain why it can't be cherry-picked.

**Comment by batrick** [comment]
@smithfarm no problem, fixed!

**Comment by yuriw** [comment]
[wip-yuri-testing-2019-03-04-2023-luminous](https://trello.com/c/MFoZe9mq/551-wip-yuri-testing-2019-03-04-2023-luminous)

**Comment by batrick** [comment]
`Reviewed-by: Patrick Donnelly <pdonnell@redhat.com>`

**Pull request merged**
