### PR TITLE
Wip gc optimization

### PR DESCRIPTION
**Pull request by xxhdx1985126**
Before this optimization, the gc procedure is:

1. scan extent infos on disk;
2. travers the lba tree for each of the above extent info to see if it's still live

The above two steps both involves many extent reads. Right now, this optimization works as follows:

1. track segments' space usage with bitmaps
2. when doing gc, check the bitmaps to see if an extent is still live instead of traversing the lba tree

This should spare the extent read efforts involved by the old gc strategy's 2nd step. The perf comparison is shown in the following two graphs: before the optimization, when the space usage hard limit is reached, crimson iops drops to 100s level; after the optimization, crimson defends 1000+ iops. This is a visible performance lift, although not a large one.

Our next step is to utilize the bitmaps to eliminate disk reads involved by the old gc strategy's 1st step. Hopefully, this may give the gc a performance boost:-)

before optimization:
gc_opt_comp

after optimization:
gc_opt

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by xxhdx1985126** [comment]
> Our next step is to utilize the bitmaps to eliminate disk reads involved by the old gc strategy's 1st step

@athanatos @cyx1231st @liu-chunmei @tchaikov 
It seems that to do this, we probably need a ["reverse paddr_t -> laddr_t mapping for gc"](https://github.com/ceph/ceph/blob/cc55af88289505b4f0bd07205ac7e6326642e031/src/crimson/os/seastore/lba_manager/btree/btree_lba_manager.h#L34). I made some [design](https://docs.google.com/document/d/1wIULGMMMV-tMDs8WvWU45NyOHx9pZuvtn9D4CgCTzJM) for this, please take a look.

**Comment by athanatos** [comment]
I'm going to hold off a bit on this one until https://github.com/ceph/ceph/pull/43474 is a bit further along.

**Comment by tchaikov** [comment]
@xuxuehan @cyx1231st @athanatos is this change still relevant ?

**Comment by cyx1231st** [comment]
IIUC it is replaced by the backref tree implementation.

**Comment by xxhdx1985126** [comment]
> IIUC it is replaced by the backref tree implementation.

Yeah, I'm closing this draft.

**Pull request closed without merging**
