### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by POPSuL**
README.md: fix the indent of a command line usage

Spaces replaced with tab

Signed-off-by: Viktor Suprun <popsul1993@gmail.com>

Related pull-request: #3712

### CODE REVIEW

**Comment by tchaikov** [comment]
@POPSuL we are close! now your commit message reads:
```
    Update README.md

    README.md: fix the indent of a command line usage

    Spaces replaced with tab

    Signed-off-by: Viktor Suprun <popsul1993@gmail.com>
```
but the first line is not very informative. could you use the line of `README.md: fix the indent of a command line usage` as the first line, and remove `Update README.md`? like:

```
    README.md: fix the indent of a command line usage

    Spaces replaced with tab

    Signed-off-by: Viktor Suprun <popsul1993@gmail.com>
```

and, instead of creating another pull request, you can update the existing one,  you can simply
```
git push -f your-remote-repo your-local-branch:patch-2
```

so the comment and history of the previous comments and discussions are preserved. =)

thanks.

**Comment by POPSuL** [comment]
@tchaikov forced pushes doesn't work for pull-requests.
For example https://github.com/POPSuL/ceph/commits/patch-2
but this pull-request dosn't have any commits from that branch and automatically closed.
What I can do? I'm just confused.

**Comment by tchaikov** [comment]
@POPSuL sorry, i am confused as well. this is exactly how i amend my own pull requests.

i cloned your branch into my own remote repo on github at https://github.com/tchaikov/ceph/tree/patch-2. and i am able to create a pull request targeting the ceph/master branch. maybe you can rebase your change onto the latest ceph/master and try again? yes, i mean `push -f` again.

if it does not work out. let's create another pull request then. what do you think? thank you.

**Comment by POPSuL** [comment]
@tchaikov I just create a new pull request =)

**Pull request closed without merging**
