### PR TITLE
mgr/orchestrator: Unify `osd create` and `osd add`

### PR DESCRIPTION
**Pull request by sebastian-philipp**
Also:

* Added some more tests
* Better validation of drive Groups
* Simplified `TestWriteCompletion`

Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by jmolmo** [comment]
LGTM

**Comment by sebastian-philipp** [comment]
QA: 

* http://pulpito.ceph.com/swagner-2019-01-29_17:02:23-rados:mgr-wip-swagner-testing-distro-basic-mira/

**Comment by sebastian-philipp** [comment]
jenkins retest this please

**Comment by sebastian-philipp** [comment]
QA

* http://pulpito.ceph.com/swagner-2019-01-30_11:16:56-rados:mgr-wip-swagner-testing-distro-basic-mira/

**Comment by sebastian-philipp** [comment]
Python 2 only:
```
2019-01-30 16:57:26.853 7ff14698e700  0 mgr[test_orchestrator] Completion create_osds, args=(<test_orchestrator.module.TestOrchestrator object at 0x7ff1469a7690>, <orchestrator.DriveGroupSpec object at 0x7ff13eb15610>, ['localhost']), kwargs={} threw an exception:
Traceback (most recent call last):
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/test_orchestrator/module.py", line 159, in wait
    c.execute()
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/test_orchestrator/module.py", line 90, in execute
    self._result = self.execute_cb()
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/test_orchestrator/module.py", line 100, in <lambda>
    return TestWriteCompletion(lambda: f(*args, **kwargs),
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/test_orchestrator/module.py", line 266, in create_osds
    drive_group.validate(all_hosts)
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/orchestrator.py", line 624, in validate
    if not self.hosts(all_hosts):
  File "/home/sebastian/Repos/ceph/src/pybind/mgr/orchestrator.py", line 612, in hosts
    import fnmatch
RuntimeError: cannot unmarshal code objects in restricted execution mode

```

**Comment by sebastian-philipp** [comment]
QA

* http://pulpito.ceph.com/swagner-2019-01-30_22:05:21-rados:mgr-wip-swagner-testing-distro-basic-mira/

**Comment by sebastian-philipp** [comment]
failed again:

```
======================================================================
ERROR: test_osd_create (tasks.mgr.test_orchestrator_cli.TestOrchestratorCli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-swagner-testing/qa/tasks/mgr/test_orchestrator_cli.py", line 58, in test_osd_create
    self._orch_cmd("osd", "create", "-i", "-", stdin=json.dumps(drive_group))
  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-swagner-testing/qa/tasks/mgr/test_orchestrator_cli.py", line 17, in _orch_cmd
    retstr = self.mgr_cluster.mon_manager.raw_cluster_cmd("orchestrator", *args, **kwargs)
TypeError: raw_cluster_cmd() got an unexpected keyword argument 'stdin'
```

**Comment by sebastian-philipp** [comment]
QA

* http://pulpito.ceph.com/swagner-2019-02-01_13:15:01-rados:mgr-wip-swagner-testing-distro-basic-mira/

only partial runs, but successfully went through test_osd_create()

**Comment by sebastian-philipp** [comment]
jenkins retest this please

**Pull request merged**
