### PR TITLE
Client: Add function "get_default_data_pool_name" for java client

### PR DESCRIPTION
**Pull request by taodd**
Fix issue:  http://tracker.ceph.com/issues/20852

Signed-off-by: dongdong tao <tdd21151186@gmail.com>

### CODE REVIEW

**Comment by taodd** [comment]
please find the corresponding PR in cephfs-hadoop
https://github.com/ceph/cephfs-hadoop/pull/36

**Comment by taodd** [comment]
retest this please

**Comment by ukernel** [comment]
I think it's better to update ceph_get_path_pool_name(). if path given to ceph_get_path_pool_name()
points to mount root and mount root has no layout, return the default pool name as workaround. Later we can fix ceph_get_path_pool_name(), make it handle case 'mount on /a/b/c' and non-default layout on  dir /a/b

**Comment by taodd** [comment]
thanks for your advice:
but, this pr is intended to fix the issue exist in cephfs-hadoop.
cephfs-hadoop need a way to get the default data pool name, 
and there is no existed API in ceph client that would give me the default data pool name. 
so i have implemented one.
so, there is nothing wrong with ceph_get_path_pool_name, if we change the behavior of ceph_get_path_pool_name(), would there be some thing unexpected would happen ? like some caller
 may depend on the return value to identify if it's a sub dir or file name or root dir ?

**Comment by ukernel** [comment]
you are right

I checked cephfs-hadoop code, its commit says "default Ceph data pool is selected to store files".

**Pull request merged**
