### PR TITLE
ceph / ceph-dbg steal ceph-objecstore-tool from ceph-test / ceph-test-dbg

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/11806

### CODE REVIEW

**Comment by dachary** [comment]
pushing to gitbuilders

**Comment by ktdreyer** [comment]
assuming gitbuilder succeeds, `Reviewed-by: Ken Dreyer <kdreyer@redhat.com>`

**Comment by dachary** [comment]
waiting on http://pulpito.ceph.com/loic-2015-06-24_16:19:31-upgrade:hammer-wip-11806-hammer---basic-vps/947848/ which failed

**Comment by dachary** [comment]
http://pulpito.ceph.com/loic-2015-06-25_15:49:17-upgrade:hammer-wip-11806-hammer---basic-vps/949226/ failed but only after 
<pre>
2015-06-25T13:07:16.614 INFO:teuthology.orchestra.run.vpm111:Running: u'sudo DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install librbd1-dbg=0.94.2-13-g356bd2c-1precise ceph=0.94.2-13-g356bd2c-1precise ceph-test=0.94.2-13-g356bd2c-1precise ceph-dbg=0.94.2-13-g356bd2c-1precise rbd-fuse=0.94.2-13-g356bd2c-1precise librados2-dbg=0.94.2-13-g356bd2c-1precise ceph-fuse-dbg=0.94.2-13-g356bd2c-1precise libcephfs-jni=0.94.2-13-g356bd2c-1precise libcephfs1-dbg=0.94.2-13-g356bd2c-1precise radosgw=0.94.2-13-g356bd2c-1precise librados2=0.94.2-13-g356bd2c-1precise libcephfs1=0.94.2-13-g356bd2c-1precise ceph-mds=0.94.2-13-g356bd2c-1precise radosgw-dbg=0.94.2-13-g356bd2c-1precise librbd1=0.94.2-13-g356bd2c-1precise python-ceph=0.94.2-13-g356bd2c-1precise ceph-test-dbg=0.94.2-13-g356bd2c-1precise ceph-fuse=0.94.2-13-g356bd2c-1precise ceph-common=0.94.2-13-g356bd2c-1precise libcephfs-java=0.94.2-13-g356bd2c-1precise ceph-common-dbg=0.94.2-13-g356bd2c-1precise ceph-mds-dbg=0.94.2-13-g356bd2c-1precise'
</pre>
completed successfully
<pre>
2015-06-25T13:09:33.909 INFO:teuthology.packaging:The installed version of ceph is 0.94.2-13-g356bd2c-1precise
2015-06-25T13:09:33.909 INFO:teuthology.task.install:The correct ceph version 0.94.2 is installed.

</pre>

**Pull request merged**
