### PR TITLE
rgw: fix deadlock on RGWIndexCompletionManager::stop

### PR DESCRIPTION
**Pull request by yaozongyou**
The lock has been acquired in complete_op_data::stop

Signed-off-by: Yao Zongyou <yaozongyou@vip.qq.com>

### CODE REVIEW

**Comment by yaozongyou** [comment]
core dump backtrace on version 12.2.2:

```bash
Program terminated with signal 6, Aborted.
#0  0x00007fb52240d59b in raise () from /lib64/libpthread.so.0
#0  0x00007fb52240d59b in raise () from /lib64/libpthread.so.0
#1  0x0000556edb3754b6 in reraise_fatal (signum=6) at /path/to/ceph/src/global/signal_handler.cc:74
#2  handle_fatal_signal (signum=6) at /path/to/ceph/src/global/signal_handler.cc:138
#3  <signal handler called>
#4  0x00007fb516ec9277 in raise () from /lib64/libc.so.6
#5  0x00007fb516eca968 in abort () from /lib64/libc.so.6
#6  0x00007fb519cefda0 in lockdep_will_lock (name=<optimized out>, id=<optimized out>, force_backtrace=<optimized out>) at /path/to/ceph/src/common/lockdep.cc:293
#7  0x00007fb5199cdcea in _will_lock (this=0x556eded26c40) at /path/to/ceph/src/common/Mutex.h:56
#8  Mutex::Lock (this=this@entry=0x556eded26c40, no_lockdep=no_lockdep@entry=false) at /path/to/ceph/src/common/Mutex.cc:92
#9  0x0000556edb4bd440 in Locker (m=..., this=<synthetic pointer>) at /path/to/ceph/src/common/Mutex.h:115
#10 stop (this=0x556eded26c40) at /path/to/ceph/src/rgw/rgw_rados.cc:3421
#11 stop (this=0x556eded8b1d0) at /path/to/ceph/src/rgw/rgw_rados.cc:3568
#12 ~RGWIndexCompletionManager (this=0x556eded8b1d0, __in_chrg=<optimized out>) at /path/to/ceph/src/rgw/rgw_rados.cc:3525
#13 RGWRados::finalize (this=this@entry=0x556edd5fc000) at /path/to/ceph/src/rgw/rgw_rados.cc:3756
#14 0x0000556edb4bd6de in RGWStoreManager::close_storage (store=0x556edd5fc000) at /path/to/ceph/src/rgw/rgw_rados.cc:13804
#15 0x0000556edb3ff458 in RGWRealmReloader::reload (this=0x7ffdd09ac3a0) at /path/to/ceph/src/rgw/rgw_realm_reloader.cc:90
#16 0x0000556edb31f469 in Context::complete (this=0x556eddbf86e0, r=<optimized out>) at /path/to/ceph/src/include/Context.h:70
#17 0x00007fb5199f68b4 in SafeTimer::timer_thread (this=0x7ffdd09ac3c0) at /path/to/ceph/src/common/Timer.cc:97
#18 0x00007fb5199f82dd in SafeTimerThread::entry (this=<optimized out>) at /path/to/ceph/src/common/Timer.cc:30
#19 0x00007fb522405e25 in start_thread () from /lib64/libpthread.so.0
#20 0x00007fb516f91bad in clone () from /lib64/libc.so.6
```

**Comment by cbodley** [comment]
thanks @yaozongyou, could you please [create a tracker issue](http://tracker.ceph.com/projects/rgw/issues/new) and add a `Fixes:` line to your commit message? that will help us get this fix backported

**Comment by yaozongyou** [comment]
@cbodley it looks i have no access to [create a tracker issue](http://tracker.ceph.com/projects/rgw/issues/new)
403 You are not authorized to access this page.

**Comment by cbodley** [comment]
strange, okay. i created one at http://tracker.ceph.com/issues/26949

**Comment by yaozongyou** [comment]
add the Fixes: line and repushed

**Comment by cbodley** [comment]
jenkins test make check

**Comment by cbodley** [comment]
http://pulpito.ceph.com/cbodley-2018-09-04_18:33:48-rgw-wip-cbodley-testing-distro-basic-smithi/

**Pull request merged**
