### PR TITLE
build/ops: change WITH_SYSTEMD default to ON

### PR DESCRIPTION
**Pull request by smithfarm**
In a systemd world, it makes more sense to default to "ON" and be explicit when we want to turn it OFF.

### CODE REVIEW

**Comment by smithfarm** [comment]
Strangely enough, the Debian build doesn't seem to be setting this at all.

**Comment by b-ranto** [comment]
I am not exactly sure how the debian build system works but shouldn't we be setting -DWITH_SYSTEMD=OFF in debian build scripts to maintain compatibility, now?

**Comment by smithfarm** [comment]
@b-ranto Good point. Added a commit for that.

**Comment by smithfarm** [comment]
http://pulpito.ceph.com/smithfarm-2018-02-21_22:45:50-rados-wip-smithfarm-testing-distro-basic-smithi/
http://pulpito.ceph.com/smithfarm-2018-02-22_15:48:12-rados-wip-smithfarm-testing-distro-basic-smithi/
http://pulpito.ceph.com/smithfarm-2018-02-27_12:29:57-rados-wip-smithfarm-testing-distro-basic-smithi/

Summary: rados suite passes with one failure in rados/standalone/scrub.yaml - not clear to me why this is failing

**Pull request merged**
