### PR TITLE
MDS is crashed (mds/CDir.cc: 1391: FAILED assert(!is_complete()))

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/11737

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@theanalyst @dachary this has been hanging around for a while, is it blocked on something or just waiting in a queue? :)

**Comment by dachary** [comment]
@gregsfortytwo it is waiting for @theanalyst to schedule a run, which could be anytime now.

**Comment by theanalyst** [comment]
@dachary @gregsfortytwo I had scheduled a run a week back. There are no failures for fs. This patch is ready to merge

**Comment by theanalyst** [comment]
BTW the current status is tracked at http://tracker.ceph.com/issues/11990

**Comment by dachary** [comment]
@theanalyst I see that http://tracker.ceph.com/issues/11990#fs passed and contains this pull request. Since you were the one authoring the backport, the next step is to ask @gregsfortytwo if it is ready to merge. gregsfortytwo decision will be made easier because he can verify the suite passed. If gregsfortytwo decides it is good to merge he can either merge it himself or just write LGTM as a comment and you can merge it.

**Comment by theanalyst** [comment]
@dachary thanks for the info. I'll update the status on all the current pull requests targeting hammer

**Comment by theanalyst** [comment]
@gregsfortytwo this pull request has passed the integration tests targeted against hammer. Ready to merge?

**Comment by gregsfortytwo** [comment]
LGTM.

**Pull request merged**
