### PR TITLE
qa: Tidy up fs/ suite

### PR DESCRIPTION
**Pull request by jcsp**
I noticed that we had picked up btrfs again, and now seems like a good time to sort out the horribly misnamed 'recovery' subsuite too.

This is based on https://github.com/ceph/ceph/pull/14018 because it had some test changes in before.

### CODE REVIEW

**Comment by jcsp** [comment]
retest this please

**Comment by jcsp** [comment]
Once this is reviewed it can either merge after #14018 or have those first four commits dropped.

**Comment by ukernel** [comment]
LGTM

**Comment by yehudasa** [comment]
@jcsp this broke a few suites: rgw, rbd, krbd, hadoop. All of the above have symbolic link pointing at fs/xfs.yaml.

**Comment by yehudasa** [comment]
https://github.com/ceph/ceph/pull/14756

**Pull request merged**
