### PR TITLE
fix FTBFS introduced by d0af316

### PR DESCRIPTION
**Pull request by tchaikov**

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

after gitbuilders are happy and the make check completes.

**Comment by tchaikov** [comment]
@athanatos  8f04ffa fixes a regression which breaks the scrub tests.

**Comment by dachary** [comment]
@tchaikov this should be rebased so 8f04ffab0f445e89aa1ceccc70c0a15171957dd4 is used (already committed in master) instead of (557c3bfe0d18b05d7f39ea920e1ca3e528d80e0e). Right ?

**Comment by tchaikov** [comment]
@dachary 8f04ffa is not in master yet.

**Comment by dachary** [comment]
@tchaikov oh, right. I got confused because https://github.com/ceph/ceph/commit/8f04ffab0f445e89aa1ceccc70c0a15171957dd4 does not show it belongs to a branch (meaning it's an isolated commit) and I interpreted that (wrongly) as meaning it's in the master branch.

**Comment by tchaikov** [comment]
i wish it were in master =)

**Pull request merged**
