### PR TITLE
rgw: do not update all gateway caches upon creation of system obj w/ exclusive flag

### PR DESCRIPTION
**Pull request by ivancich**
When a system object is created exclusively, do not distribute the
cache information to the other rados gateways and instead let them
lazily retrieve the information when they need it.

While using the swift client to explore customer issues, I observed the following behavior. The swift client for an object upload will always precede the upload request with a request to create the container/bucket. Whether or not the bucket already exists, RGW proceeds to try to create the bucket by first creating the index shards, then the bucket object, then the bucket entry point object. At that last step it fails if the bucket already exists due creating the bucket entry point object with the exclusive flag. At that point RGW proceeds to delete the bucket object and the shards. Going back to early in this process, after creation of the bucket object with the exclusive flag, distribute_cache is called to notify all RGWs of the new system object. And it is called again when the unnecessary bucket object is deleted.

Generally speaking, when successfully creating a system object with the exclusive flag it is not necessary to call distribute_cache, as it's unclear whether other RGWs will need that system object in the near-term and it generates additional network traffic.

This commit does not alter the behavior of deleting a system object and its associated call to distribute_cache.

Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>

### CODE REVIEW

**Comment by ivancich** [comment]
This was run through the rgw suite. The only failures noted were valgrind issues with multi-site and with the ceph monitors and some S3 hadoop issues.
pulpito suite: http://pulpito.ceph.com/ivancich-2017-12-07_14:07:14-rgw-wip-rgw-lazy-cache-put-on-excl-create---basic-smithi/
pulpito retest of infrastructure failure: http://pulpito.ceph.com/ivancich-2017-12-07_18:28:02-rgw-wip-rgw-lazy-cache-put-on-excl-create---basic-smithi/1943600

**Comment by mattbenjamin** [comment]
@ivancich this is an astonishingly small change

**Comment by yehudasa** [comment]
@ivancich good insight. Can you add the last paragraph as a comment there?

**Comment by ivancich** [comment]
@yehudasa I added the comment and to be safe rebased on the current master.

**Comment by ivancich** [comment]
@yehudasa Anything else you'd like?

**Comment by ivancich** [comment]
@cbodley This is the PR I mentioned during our meeting.

**Comment by cbodley** [comment]
@ivancich @mattbenjamin think we should backport to jewel/luminous?

**Comment by mattbenjamin** [comment]
@cbodley I vote for at least luminous;  is there any sense in which the new behavior here could be "more correct" in a way that helps...a customer?

**Comment by cbodley** [comment]
added http://tracker.ceph.com/issues/22792 for luminous backport

**Comment by robbat2** [comment]
@ivancich A++ change, i made a luminous backport PR it

**Comment by ivancich** [comment]
@mattbenjamin I would not claim it's "more correct". What ends up being stored on disk would be the same with or without this commit. However, in many cases it will be more efficient, especially with a swift front-end in which every put-object causes a bucket-create.

**Pull request merged**
