### PR TITLE
luminous: Python bindings use iteritems method which is not Python 3 compatible

### PR DESCRIPTION
**Pull request by smithfarm**
http://tracker.ceph.com/issues/24804

### CODE REVIEW

**Comment by jcsp** [comment]
In mimic, we were getting `python-six` as an indirect dependency of `python-bcrypt`, which was in there for the new dashboard.  Since luminous has the old dashboard, it won't get six the same way -- it's possible it will anyway get six via some other dependency, but I don't have an easy way to check.  Maybe we should add it here as a direct dependency anyway.

**Comment by tchaikov** [comment]
@jcsp in luminous
```
 ceph-mgr ==> python-cherrypy3 => python-six
         | => python-openssl  => python-six
         \ => python-pecan => python-six
```

so we are safe at this moment. but i still think it'd be better to list python-six as an explicit dependency

**Comment by smithfarm** [comment]
@jcsp @tchaikov I'll add `python-six` as a dependency. buildtime and runtime, or just runtime?

(I'll either do it as a cherry-pick of e53bb2c5a32e9b458a55fe01b28f23bdf952b6f7 or mention that commit in the commit message.)

**Comment by tchaikov** [comment]
@smithfarm i don't feel strong either way. but i think i've put my opinion in the comment above, and the fix at #22871 applies to luminous also.

**Comment by jcsp** [comment]
Let's do that backport of e53bb2c just so that nobody in the future has to wonder how we're getting it the package.

**Comment by smithfarm** [comment]
@jcsp Done. I decided not to cherry-pick #22950 since it's just a cleanup and, what's more, it depends on other previous cleanups and the Python 3 enablement, none of which have been backported to luminous yet.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-08-03-1639-luminous](https://trello.com/c/qKlRGlZR/364-wip-yuri-testing-2018-08-03-1639-luminous)

**Pull request merged**
