### PR TITLE
Test: objectstore test fails on kvstore and add a test for list_collections

### PR DESCRIPTION
**Pull request by wonzhq**
Signed-off-by: Zhiqiang Wang <zhiqiang.wang@intel.com>

### CODE REVIEW

**Comment by yuyuyu101** [comment]
please add a unittest to test/objectstore/store_test.cc :-)

**Comment by liewegas** [comment]
What is the motivation?  The only real user, the OSD, is the one that creates/uses it..

maybe we should explicitly skip it here so we don't issue a warning? https://github.com/ceph/ceph/blob/master/src/osd/OSD.cc#L2715

**Comment by wonzhq** [comment]
@liewegas list_collections is also called in FileStore::mount(). In that function, ignoring the 'meta' can avoid to build an index for it.

**Comment by wonzhq** [comment]
@yuyuyu101 added the testcase. Also fixed a bug in store_test.cc. With this bug, the testcases in this file fails running on kvstore.

**Comment by yuyuyu101** [comment]
Hmm, I rethink this patch and I'm nervous about the change, because ObjectStore interface shouldn't know the specified "meta" collection. In PG layer, "meta" is a special collection but in ObjectStore layer, it's same as other collections.

"omap" is shadow because it's a intern usage inside FileStore. So shadow "meta" looks like destroy the meaning of list_collections. Filter "meta" should be the job of caller?

**Comment by liewegas** [comment]
Exactly

**Comment by wonzhq** [comment]
Sounds reasonable. But maybe the later 2 commits worth merging? The first one fixes a bug, which the objectstore testcases fail on kvstore. The other one add a testcase for list_collections. I'll repush the later 2 commits and change the PR title.

**Comment by yuyuyu101** [comment]
It looks good to me

**Comment by liewegas** [comment]
I think the -dev fix is already in master now, but git should merge it anyway.  Thanks!

**Comment by liewegas** [comment]
we are about to get rid of collections with arbitrary names.  this test should be redone on top of the wip-recovery-temp branch (if there isn't already a new test there that covers it).

**Pull request closed without merging**
