### PR TITLE
quincy: mgr/dashboard: Landing page v3 

### PR DESCRIPTION
**Pull request by nizamial09**
backport tracker: https://tracker.ceph.com/issues/58743

---

backport of https://github.com/ceph/ceph/pull/50109, https://github.com/ceph/ceph/pull/50214, https://github.com/ceph/ceph/pull/50106
parent tracker: https://tracker.ceph.com/issues/57861

this backport was staged using ceph-backport.sh version 16.0.0.6848
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by nizamial09** [comment]
jenkins test dashboard

**Comment by nizamial09** [comment]
jenkins test dashboard cephadm

**Review by Pegonzal — APPROVED** [review]
Tested it, working perfectly! Thanks @nizamial09

**Comment by nizamial09** [comment]
e2e needs to be adapted: https://tracker.ceph.com/issues/59142

**Pull request merged**
