### PR TITLE
Fix types/casts making clang on 32-Bit working

### PR DESCRIPTION
**Pull request by the78mole**
I fixed a few type bugs that arose when compiling ceph using clang on 32-bit ARM by executing ./make-debs. They get hidden when building on 64-bit platforms due to the larger long type.

I'm not sure if the bugs break the things with GCC, but GGC itself seems to be broken, since it eats up all the VMEM during compile and breaks much earlier (see my Bug-Report). So I was forced to use Clang to get it somehow compiled.

### CODE REVIEW

**Comment by tchaikov** [comment]
@the78mole as the issues addressed by this change also exist in master, could you please target your PR to master instead? if you believe that we should backport it to luminous, i'd recommend you file a tracker ticket, and track the backport process using the tracker.

**Comment by the78mole** [comment]
@tchaikov I would like to build master, but on ARM I'm experiencing problems to build it due to a missing npm dependency (PhantonJS) for the arm plattform. I would need to setup another ceph build environment on i686 to ensure the build a) succeeds b) solves the 32-bit problems...

**Comment by LenzGr** [comment]
@the78mole you can disable the build of the Dashboard (which requires `npm` by setting the CMake config option `WITH_MGR_DASHBOARD_FRONTEND` to `OFF`.

**Comment by the78mole** [comment]
Building master (by executing do_cmake.sh and starting with make) on my ARM system currently encounters the following error (and more similar ones):
```
In file included from /home/daniel/git/ceph/src/krbd.cc:28:
In file included from /home/daniel/git/ceph/src/auth/KeyRing.h:18:
In file included from /home/daniel/git/ceph/src/auth/Auth.h:18:
In file included from /home/daniel/git/ceph/src/auth/Crypto.h:18:
In file included from /home/daniel/git/ceph/src/include/types.h:21:
In file included from /home/daniel/git/ceph/src/include/uuid.h:8:
/home/daniel/git/ceph/src/include/encoding.h:22:10: fatal error: 'string_view' file not found
```
If I use libc++ (from llvm) instead of libstdc++ (GCC), which needs a lot of tweaking, then I get more errors (e.g. that string_view is included as experimental/string_view from boost, which leads to even more problems.

Using a 32-bit chroot also does not work as expected and I would need to setup a full 32-bit linux VM.

Since resolving these issues would take quite some effort and time, I'm currently not able provide a pull request against master.

**Comment by tchaikov** [comment]
@the78mole thanks a lot for trying to build master on arm32.

> If I use libc++ (from llvm) instead of libstdc++ (GCC), that needs a lot of tweaking, then I get more errors (e.g. that string_view is included as experimental/string_view from boost), which leads to even more problems.

strange enough, some of us do build ceph using libc++ with clang.

anyway, can i have your permission to post a PR which re-targets your change to master?

**Comment by the78mole** [comment]
Sure you have my permission to post a PR. Thanks for your support.

**Comment by tchaikov** [comment]
> You say that some of you use libc++ and clang to build. How is the preffered way of configuring the build for that? Maybe you could give me some hints about setting it up.

i use something like

```
CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ cmake .. \
  -DBOOST_J=4 -DENABLE_GIT_VERSION=OFF -DWITH_EMBEDDED=OFF -DWITH_SPDK=OFF
```

to build ceph on MacOS. but please ascertain that your clang does support C++17.

> I would kindly offer myself to test it and write the documentation, since many people running stable Linux distributions lack C++17 support and need an alternative toolchain.

there are ubuntu ppa and DTS repo for ubuntu and RHEL/CentOS respectively offering pre-built GCC-7 and updated toolchain packages, but sadly, neither of them offers arm32 build.

**Comment by tchaikov** [comment]
@the78mole i am closing this PR in favor of #21055. as mentioned above, please feel free to file a tracker ticket if you want to backport this change to luminous.

**Pull request closed without merging**
