### PR TITLE
rgw: update is_truncated in function rgw_read_user_buckets

### PR DESCRIPTION
**Pull request by Liuchang0812**

### CODE REVIEW

**Comment by Liuchang0812** [comment]
@cbodley would you mind taking a look?

**Comment by Liuchang0812** [comment]
OK, I will do it

2017-04-06 0:17 GMT+08:00, Casey Bodley <notifications@github.com>:

**Comment by cbodley** [comment]
passed rgw suite: http://pulpito.ceph.com/cbodley-2017-04-10_19:26:19-rgw-wip-cbodley-testing---basic-mira/

**Comment by Liuchang0812** [comment]
thanks @cbodley

**Pull request merged**
