### PR TITLE
[DNM] mon,mgr: extricate PGmap from monitor

### PR DESCRIPTION
**Pull request by tchaikov**
fork of #15073

### CODE REVIEW

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
retest this please.

**Comment by tchaikov** [comment]
@liewegas i am using this PR to test the "make check" run on jenkins, so i am reopening it.

**Comment by liewegas** [comment]
ah, ok!

**Comment by tchaikov** [comment]
@liewegas could you reset your wip-mgr-stats with this one? i just rebased yours against master.

**Comment by liewegas** [comment]
done

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2017-05-29_07:20:22-rados-wip-mgr-stats-kefu---basic-mira/

**Comment by tchaikov** [comment]
```
/home/jenkins-build/build/workspace/ceph-pull-requests/src/test/mon/misc.sh:244: TEST_mon_features:  return 1
```

could be a regression caused by 12f65a2ca270a7b1ff484d6fab1304faff26d018.

**Comment by tchaikov** [comment]
closing since the "make check" has been green for a while.

**Pull request closed without merging**
