### PR TITLE
nautilus: client: reset requested_max_size if file write is not wanted

### PR DESCRIPTION
**Pull request by smithfarm**
backport tracker: https://tracker.ceph.com/issues/45212

---

backport of https://github.com/ceph/ceph/pull/34274
parent tracker: https://tracker.ceph.com/issues/44801

this backport was staged using ceph-backport.sh version 15.1.1.389
find the latest version at https://github.com/ceph/ceph/blob/master/src/script/ceph-backport.sh

### CODE REVIEW

**Comment by smithfarm** [comment]
```
119/168 Test   #4: smoke.sh ................................***Failed  165.39 sec
```

**Comment by smithfarm** [comment]
jenkins test make check

**Comment by smithfarm** [comment]
```
119/168 Test   #4: smoke.sh ................................***Failed  165.39 sec
```

Second time. Might be related to the PR?

**Comment by ukernel** [comment]
> ```
> 119/168 Test   #4: smoke.sh ................................***Failed  165.39 sec
> ```
> 
> Second time. Might be related to the PR?

I don't think so

**Comment by yuriw** [comment]
[wip-yuri5-testing-2020-04-27-1505-nautilus](https://trello.com/c/nmjAmDhf/885-wip-yuri5-testing-2020-04-27-1505-nautilus)

**Comment by yuriw** [comment]
[wip-yuri2-testing-2020-05-01-1612-nautilus](https://trello.com/c/MGXH8eti/893-wip-yuri2-testing-2020-05-01-1612-nautilus)

**Comment by yuriw** [comment]
[wip-yuri3-testing-2020-05-06-1934-nautilus](https://trello.com/c/MdP7ZRct/899-wip-yuri3-testing-2020-05-06-1934-nautilus)

**Pull request merged**
