### PR TITLE
Revert "luminous: rgw: user stats increased after bucket reshard"

### PR DESCRIPTION
**Pull request by oritwas**
reverting due to regression causing the bucket not to be displayed in user bucket list
Reverts ceph/ceph#19538

### CODE REVIEW

**Comment by theanalyst** [comment]
@oritwas  can you add a signed-off-by, needs admin priveleges to merge otherwise

**Comment by smithfarm** [comment]
Wait, shouldn't this be reverted in master, and then cherry-pick the revert from there?

**Comment by smithfarm** [comment]
Regarding signed-off-by, `git revert -s` works.

**Comment by yuriw** [comment]
[rgw => wip-yuri4-testing-2018-01-25-1744-luminous](https://trello.com/c/qvWoKh2O/243-rgw-wip-yuri4-testing-2018-01-25-1744-luminous)

**Pull request merged**
