### PR TITLE
qa/suites: switch from centos 7.2 to 7.x

### PR DESCRIPTION
**Pull request by liewegas**
In general we don't care with point release we get.

Add a centos_7.3.yaml for cases where we do.

### CODE REVIEW

**Comment by liewegas** [comment]
Yes--I'll merge kraken back into master.

**Comment by smithfarm** [comment]
This new "centos.yaml" which specifies `os_type: centos` but does not specify `os_version` seems to cause trouble when passing e.g. "qa/distros/all/ubuntu_14.04.yaml" as an argument to teuthology-suite. Since the test yaml does not specify os_version, it gets picked up from the yaml provided on the command line, yielding test descriptions that say:

```
os_type: centos
os_version: 14.04
```

**Comment by yuriw** [comment]
https://github.com/ceph/ceph/pull/12768/commits/61e52f55c01ba5f346935a1fb43c0f69297a0c62

**Comment by smithfarm** [comment]
I guess the problem referred to above could be considered a bug in teuthology, so I opened http://tracker.ceph.com/issues/18420

**Comment by vasukulkarni** [comment]
@smithfarm  what you are doing looks like user error, the overrides you are using doesn't apply properly for this suite, there is nothing the cli can do here.

**Comment by smithfarm** [comment]
@vasukulkarni The fact is that the following two yaml fragments currently produce "centos 14.04":

Fragment 1 (in suite yaml)

```
os_type: centos
```

Fragment 2 (on command line)

```
os_type: ubuntu
os_version: "14.04"
```

You can call this user error if you like, but teuthology doesn't *have* to treat it this way.

**Comment by vasukulkarni** [comment]
@smithfarm  I understand, what I am trying to say is the version overrides doesn't apply due to only one distro file here,  one could add ubuntu distro and use filter option just like we do for other suites.

**Comment by vasukulkarni** [comment]
@smithfarm on the other note,  you should use --distro and --distro-version instead from the cli  for os overrides

**Pull request merged**
