### PR TITLE
mgr/BaseMgrModule: use PyInt_Check() to compatible with py2

### PR DESCRIPTION
**Pull request by tchaikov**
in python2, we have both `PyLongObject` and `PyIntObject` for presenting
`long` and `int` types. and in python3, `PyIntObject` is dropped, `int`
is represented using `PyLongObject`. and the related functions like
`PyInt_Check()` and `PyInt_AsLong()` are removed along with
`PyIntObject`.

so we should use different set of functions for converting an `int` python
object to native type in C++. since we don't use `long` for "count" when
calling `MgrModule.set_health_checks()`, in this change, we just define
a macro to unify the difference between python2 and python3.

Signed-off-by: Kefu Chai <kchai@redhat.com>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by tchaikov** [comment]
@sebastian-philipp i am in favor of simplicity and correctness. if we happen to have a PR to address your concern, i am happy to review and merge it.

**Comment by sebastian-philipp** [comment]
> @sebastian-philipp i am in favor of simplicity and correctness.

Yep again, this PR lgtm as it is.

**Comment by votdev** [comment]
WFM

**Comment by tchaikov** [comment]
@liewegas changed and repushed.

**Comment by liewegas** [comment]
Is anything preventing us from flipping the compat code and calling code around?  I agree that would be better long term.

**Comment by tchaikov** [comment]
@liewegas are you suggesting what Sebastian suggested, right? it's just more complicated. the PythonCompat.h macros are using the fact that python3 does not have str and long to simplify the code, if we do the other way around, we'd need to have wrappers with different names.

**Comment by liewegas** [comment]
> @liewegas are you suggesting what Sebastian suggested, right? it's just more complicated. the PythonCompat.h macros are using the fact that python3 does not have str and long to simplify the code, if we do the other way around, we'd need to have wrappers with different names.

Yeah, that was my question, makes sense.

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-23_09:33:33-rados-wip-kefu-testing-2019-08-23-1454-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-25_05:28:04-rados-wip-kefu-testing-2019-08-23-1454-distro-basic-smithi/

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2019-08-25_16:39:25-rados-wip-kefu-testing-2019-08-25-2138-distro-basic-mira/

**Comment by smithfarm** [comment]
I've seen other py3 fixes getting backported to mimic and/or luminous. What about this one?

**Comment by tchaikov** [comment]
thank you @smithfarm ! but the "count" health check was introduced in d0eb22f3ba557b9e98836995c813ea77c5e7c2a5.

```
$ git tag --contains d0eb22f3ba557b9e98836995c813ea77c5e7c2a5 | wc
      0       0       0
```

so i think we are safe this case.

**Pull request merged**
