### PR TITLE
tests: move swift.py task from teuthology to ceph, phase one (master)

### PR DESCRIPTION
**Pull request by smithfarm**
This should add the single file `qa/tasks/swift.py` while preserving its history from the teuthology repo.

Phase one will consist of PRs (identical to this one) for all non-EOL branches, i.e. master, kraken, jewel, and hammer.

Phase two will be a teuthology PR ripping out the file.

### CODE REVIEW

**Comment by smithfarm** [comment]
Can someone check if this looks right? If so, I'll open the other 3 PRs.

**Comment by zmc** [comment]
Github doesn't display things like this properly; how far back does the history go with `git log follow qa/tasks/swift.py` ?

**Comment by smithfarm** [comment]
To this commit:

```
commit 0a6e5d79c0f1fddb229b14b7550d43b29849261b
Author: Tommi Virtanen <tommi.virtanen@dreamhost.com>
Date:   Mon Dec 5 10:07:25 2011 -0800

    Rename "testrados" and "testswift" tasks to not begin with "test".
    
    Anything "test*" looks like a unit test, and shouldn't be used for
    actual code.
```

**Comment by smithfarm** [comment]
We're losing some 2011 commits before that rename :-( Don't know how to preserve those.

**Comment by smithfarm** [comment]
@zmc I had not been including the history for the related files `testswift.py` and `s3tests.py` - that's why all the history was not there. Fixed now: `git blame qa/tasks/swift.py` and `git log --follow qa/tasks/swift.py` both look good.

**Comment by smithfarm** [comment]
Note that I do not have sufficient github privileges to override the failed signed-off-by test (and I don't know of any good way to make it pass on this PR).

**Comment by smithfarm** [comment]
@zmc Thanks for the review.

**Pull request merged**
