### PR TITLE
install-deps: enable copr ceph/grpc

### PR DESCRIPTION
**Pull request by nizamial09**
In dashboard, to generate nvmeof apis in el8 this is needed so that it can download the python3-grpcio packages.
https://copr.fedorainfracloud.org/coprs/ceph/grpc/

Fixes: https://tracker.ceph.com/issues/65184

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "quincy"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

- When filling out the below checklist, you may click boxes directly in the GitHub web UI.  When entering or editing the entire PR message in the GitHub web UI editor, you may also select a checklist item by adding an `x` between the brackets: `[x]`.  Spaces and capitalization matter when checking off items this way.

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by nizamial09** [comment]
ah just saw that its being done in: https://github.com/ceph/ceph/pull/54671/, so probably we can wait for it to merge.

**Comment by epuertat** [comment]
jenkins retest this please

**Comment by cbodley** [comment]
@nizamial09 can you confirm that this is only a build-time dependency? we don't require upstream users to enable this repo, right?

**Comment by cbodley** [comment]
> On containers nothing else is required from users, but now you mention it I guess that RPM/package users will have to configure these (and we'll need to document it). Was that your concern?

yes. i don't think we've required custom repos like this in the past

**Comment by cbodley** [comment]
el9 already provides that package? main and squid won't support el8, so maybe this doesn't matter

**Comment by epuertat** [comment]
@cbodley the (not so) 'funny' thing is that upstream `ceph` containers are [still based on CentOS 8](https://quay.ceph.io/repository/ceph-ci/ceph/manifest/sha256:02f0a191d4d693952654c64f93cc9c0152602c0915251b3c94c2c4e32855c608?tab=packages) (I was shocked when I recently found that). I think that this repo was just a workaround. 

That said, these are weak deps, so CentOS8/RHEL8 users that don't want to use NVMe-oF can simply skip that dependency and install Ceph normally.

**Comment by ktdreyer** [comment]
Yes, I created this [ceph/grpc copr](https://copr.fedorainfracloud.org/coprs/ceph/grpc/) only to limp us along while the upstream Ceph container is still based on el8. This allows us to move forward with nvmeof upstream.

The grpc packages are all present in EPEL 9. In fact this copr has the exact EPEL 9 versions, just ported to el8.

**Pull request merged**
