### PR TITLE
rgw: don't use req_state::bucket_name in TempURL of Swift API.

### PR DESCRIPTION
**Pull request by rzarzynski**

### CODE REVIEW

**Comment by zaitcev** [comment]
Could you please have a look at this and let me know if it works: https://github.com/ceph/ceph/pull/7751

**Comment by rzarzynski** [comment]
Hi Pete. I think there is no reason for making a work duplication. Please take a look on the commit https://github.com/rzarzynski/ceph/commit/8d084b4e48662fd6590253fa477b0f6e4cc410d2.

Matt asked about the ```s->bucket_tenant``` several days ago: https://github.com/rzarzynski/ceph/commit/00669e0b759b34bba9ca468331a3c26ee1bf0911#commitcomment-16153615.

**Comment by yehudasa** [comment]
@zaitcev I'll need your ack for this commit, if you think it's ok

**Comment by yehudasa** [comment]
updated fix merge with PR #7891

**Pull request closed without merging**
