### PR TITLE
rados: add rados bench randseq option

### PR DESCRIPTION
**Pull request by tdeneau**
rados: also fix some inconsistencies with rados bench op_size and obj_size

Signed-off-by: Tom Deneau tom.deneau@amd.com

### CODE REVIEW

**Comment by tdeneau** [comment]
I know it has been a while, but can I get an update on what is preventing this pull request from being integrated?

**Comment by liewegas** [comment]
@tdeneau ping

**Comment by tdeneau** [comment]
OK, thanks for the reminder, will take a look…

**Comment by liewegas** [comment]
@tdeneau closing this; please reopen when you have time to address @tchaikov 's comments.

**Pull request closed without merging**
