### PR TITLE
doc: drop obsolete cache tier options

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://tracker.ceph.com/issues/45514
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@jdurgin Thanks for reviewing. I just found another instance of it - could you take a look at the new commit I just added?

**Comment by smithfarm** [comment]
since

* this is a documentation thing
* it passed "make check"
* I did not find any test under `qa/` that examines the contextual help message

I'll merge this now

**Comment by neha-ojha** [comment]
@smithfarm we'll need to do some test cleanup as well, see http://pulpito.ceph.com/nojha-2020-05-19_00:53:41-rados-wip-revert-34894-distro-basic-smithi/5068087/

**Comment by smithfarm** [comment]
@neha-ojha Sorry about that! https://github.com/ceph/ceph/pull/35139 is open to fix.

**Comment by neha-ojha** [comment]
> @neha-ojha Sorry about that! #35139 is open to fix.

Thanks, let's use https://tracker.ceph.com/issues/45614 to track it.

**Comment by tchaikov** [comment]
> since
> 
> * this is a documentation thing
> * it passed "make check"
> * I did not find any test under `qa/` that examines the contextual help message
> 
> I'll merge this now

i encourage to add the test result before merging a PR. we've been breaking the tests recently.

**Pull request merged**
