### PR TITLE
PGMonitor: acting primary diff with cur_stat, should not set pg to stale.

### PR DESCRIPTION
**Pull request by cxwshawn**
Signed-off-by: Xiaowei Chen <chen.xiaowei@h3c.com>

### CODE REVIEW

**Comment by cxwshawn** [comment]
@tchaikov yeah, if acting_primary changed, then the old primary down should not affect the pg_stat_updates, and exactly last_unstale should not change too, thanks !

**Comment by tchaikov** [comment]
@cxwshawn you are right, it makes sense to me. could you squash these two commit into a single one?

**Comment by cxwshawn** [comment]
@tchaikov sorry for the latency, fixed, please review, thanks.

**Comment by tchaikov** [comment]
lgtm with rados qa run.

**Pull request merged**
