### PR TITLE
nautilus: mgr/telemetry: fix device id splitting when anonymizing serial

### PR DESCRIPTION
**Pull request by yaarith**
backport tracker: https://tracker.ceph.com/issues/47193

----

backport of https://github.com/ceph/ceph/pull/36855
parent tracker: https://tracker.ceph.com/issues/46977

### CODE REVIEW

**Comment by yaarith** [comment]
Conflicts:
`src/pybind/mgr/telemetry/module.py`

In master we use Python 3's f-string formatting to create `anon_devid`:
	`anon_devid = f"{devid.rsplit('_', 1)[0]}_{uuid.uuid1()}"`

The conflict happened since Nautilus still uses Python 2, and `anon_id` is created via string concatenation.
	`anon_devid = devid[:devid.rfind('_')] + '_' + str(uuid.uuid1())`

(added to the commit message)

**Review by bk201 — APPROVED** [review]
LGTM.

Test logs:
- [A vstart cluster](https://gist.githubusercontent.com/bk201/0ffff562d5b26f1318cc389efaafcf14/raw/684381786475693c56c5cdb7223dc2a921663491/gistfile1.txt)
- [A VM cluster](https://gist.githubusercontent.com/bk201/e388f26b4c1e5a5eeab99a6347a3f717/raw/aabc4d835475dfb1dc28f486a67ee214ebc8d65d/gistfile1.txt)

**Comment by smithfarm** [comment]
jenkins test api

**Comment by smithfarm** [comment]
@yaarith Please don't add `nautilus-batch-1` until you have ensured that the PR passed all checks.

**Comment by yaarith** [comment]
Sorry about that, @smithfarm, and thanks for the feedback.

**Comment by yuriw** [comment]
[wip-yuri4-testing-2020-09-23-1206-nautilus](https://trello.com/c/q4ak8B8W/1019-wip-yuri4-testing-2020-09-23-1206-nautilus)

**Pull request merged**
