### PR TITLE
dmclock: update dmclock submodule sha1 to tip of ceph/dmclock.git master

### PR DESCRIPTION
**Pull request by rjfd**
This update will fix the build of Ceph when -DWITH_TESTS=OFF is used.

Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by ivancich** [comment]
@tchaikov With respect to my review, Kefu, what do you think the proper behavior should be w.r.t. building dmclock tests?

**Comment by tchaikov** [comment]
@ivancich 

per 

https://github.com/ceph/ceph/blob/527415b8185104713ec8b58e2395474be7db94d5/src/CMakeLists.txt#L547-L548

so i think this is the expected behavior. IIUC, we are testing `dmclock-tests` and `dmclock-data-struct-tests` as part of dmclock's own CI test. so we don't need to include them in Ceph's `make tests` or `make check`.

**Comment by ivancich** [comment]
@tchaikov Thanks.

**Comment by tchaikov** [comment]
http://pulpito.ceph.com/kchai-2018-09-01_05:34:50-rados-wip-kefu-testing-2018-09-01-1121-distro-basic-mira/

**Pull request merged**
