### PR TITLE
nautilus: mgr/dashboard: dashboard giving 401 unauthorized

### PR DESCRIPTION
**Pull request by LenzGr**
http://tracker.ceph.com/issues/38871

### CODE REVIEW

**Comment by dsielert** [comment]
This change breaks dashboard login for me

**Comment by alitvak69** [comment]
Same here.  The worse for me is I am running it in containers so really need to patch it on every restart.  How do I do that?

**Comment by rjfd** [comment]
@dsielert @alitvak69 can you tell us what is the timezone of the server where the dashboard is running?

**Comment by alitvak69** [comment]
Pacific Day Light Savings (PDT)

**Pull request merged**
