### PR TITLE
pacific: mds: standby-replay only trims cache when it reaches the end of the replay log

### PR DESCRIPTION
**Pull request by batrick**
https://tracker.ceph.com/issues/50254
https://tracker.ceph.com/issues/50632

### CODE REVIEW

**Comment by tchaikov** [comment]
the FTBFS will be addressed once the pacific-saved branch is restored.

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test api

**Comment by batrick** [comment]
jenkins test docs

**Comment by batrick** [comment]
This can cause a regression: https://tracker.ceph.com/issues/50246

**Comment by batrick** [comment]
Waiting for backport: https://github.com/ceph/ceph/pull/40963

**Comment by batrick** [comment]
> Waiting for backport: #40963

done.

**Review by mchangir — APPROVED** [review]
LGTM

**Pull request merged**
