### PR TITLE
tools/rados: append enter print when run rados getxattr

### PR DESCRIPTION
**Pull request by jimmyway**
Signed-off-by: tang.jin <tang.jin@istuary.com>

### CODE REVIEW

**Comment by jimmyway** [comment]
@liupan1111

**Comment by liewegas** [comment]
retest this please

**Comment by liewegas** [comment]
retest this please

**Comment by jimmyway** [comment]
@liewegas  sorry, I don't know how to retest it, could you give me more detail.

**Comment by tchaikov** [comment]
@jimmyway "r3test this please" is a command to jenkins to re-trigger a "make check" run.

**Comment by tchaikov** [comment]
```
RUN_EXPECT_FAIL:  /home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/rados -p trs_pool import /tmp/test_rados_tool.wSQEp804x0/expa
...
	  7 - cephtool-test-rados.sh (Failed)

Testing get-osdmap and set-osdmap
osdmap.epoch mismatch: 63 != 65
But will continue anyway.
osdmap.epoch mismatch: 63 != 65
But will continue anyway.
osdmap.epoch mismatch: 57 != 59
But will continue anyway.
osdmap.epoch mismatch: 57 != 59
But will continue anyway.
osdmap.epoch mismatch: 61 != 63
But will continue anyway.
osdmap.epoch mismatch: 61 != 63
But will continue anyway.
osdmap.epoch mismatch: 59 != 61
But will continue anyway.
osdmap.epoch mismatch: 59 != 61
But will continue anyway.
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/osdmaptool: osdmap file '/tmp/tmp06nIjL'
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/osdmaptool: osdmap file '/tmp/tmpuLuNMj'
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/osdmaptool: osdmap file '/tmp/tmp4S0c_i'
/home/jenkins-build/build/workspace/ceph-pull-requests/build/bin/osdmaptool: osdmap file '/tmp/tmpFYDwbn'
inc-osdmap#62 exported.
Wrote inc-osdmap.63
dry-run: Nothing changed
inc-osdmap#62 exported.
Wrote inc-osdmap.62
TEST FAILED WITH 6 ERRORS
incremental.epoch mismatch: 63 != 62
But will continue anyway.
...
	  3 - ceph_objectstore_tool.py (Failed)
```

**Comment by jimmyway** [comment]
retest this please

**Comment by liewegas** [comment]
It makes this teuth test fail too:
<pre>
2017-04-21T05:51:24.575 INFO:tasks.workunit.client.0.smithi094.stderr:error during benchmark: -2
2017-04-21T05:51:24.576 INFO:tasks.workunit.client.0.smithi094.stderr:error 2: (2) No such file or directory
2017-04-21T05:51:24.577 INFO:tasks.workunit.client.0.smithi094.stdout:RUN_EXPECT_NOSIGNAL:  /usr/bin/rados --pool trs_pool bench 1 seq
2017-04-21T05:51:24.591 INFO:tasks.workunit.client.0.smithi094.stdout:hints = 1
2017-04-21T05:51:24.591 INFO:tasks.workunit.client.0.smithi094.stderr:Must write data before running a read benchmark!
2017-04-21T05:51:24.591 INFO:tasks.workunit.client.0.smithi094.stderr:error during benchmark: -2
2017-04-21T05:51:24.591 INFO:tasks.workunit.client.0.smithi094.stderr:error 2: (2) No such file or directory
2017-04-21T05:51:24.735 INFO:tasks.workunit.client.0.smithi094.stderr:cmp: EOF on fooattrX895QD4
2017-04-21T05:51:24.740 INFO:tasks.workunit:Stopping ['rados/test_rados_tool.sh'] on client.0...
2017-04-21T05:51:24.740 INFO:teuthology.orchestra.run.smithi094:Running: 'rm -rf -- /home/ubuntu/cephtest/workunits.list.client.0 /home/ubuntu/cephtest/clone.client.0'
2017-04-21T05:51:24.921 ERROR:teuthology.run_tasks:Saw exception from tasks.
Traceback (most recent call last):
</pre>
that's qa/workunits/rados/test_rados_tool.sh

**Comment by tchaikov** [comment]
retest this please.

**Pull request closed without merging**
