### PR TITLE
ceph-volume-client: allow setting mode of CephFS volumes

### PR DESCRIPTION
**Pull request by tombarron**
and snapshots and snapshot groups.

OpenStack Manila needs this capability when it is used as a Kubernetes dynamic external storage provider.

Needed-by: https://review.openstack.org/#/c/614332/

Fixes: https://tracker.ceph.com/issues/36651
Signed-off-by: Tom Barron <tpb@dyncloud.net>

### CODE REVIEW

**Comment by ajarr** [comment]
@tombarron LGTM. Would volume group creation also need this?

**Comment by ajarr** [comment]
Thanks, Tom

**Comment by ajarr** [comment]
@batrick , can you please test the latest patchset?

**Comment by batrick** [comment]
retest this please

**Comment by batrick** [comment]
> @batrick , can you please test the latest patchset?

Sure.

**Comment by tombarron** [comment]
Is this ready for merge?

**Comment by batrick** [comment]
Planning to merge this week after verifying test results.

**Comment by tombarron** [comment]
We need to get this back to luminous (via mimic?) and downstream into 3.2.

**Pull request merged**
