### PR TITLE
luminous: crash on DaemonPerfCounters::update

### PR DESCRIPTION
**Pull request by shinobu-x**
http://tracker.ceph.com/issues/21656

### CODE REVIEW

**Comment by shinobu-x** [comment]
@smithfarm Here is conflict message. I picked code from `dc4415f1`

>--- a/src/mgr/PyModules.cc
>+++ b/src/mgr/PyModules.cc
>@@@ -745,7 -760,10 +745,14 @@@ PyObject* PyModules::get_perf_schema_py
>daemon_name << key.first << "." << key.second;
>f.open_object_section(daemon_name.str().c_str());
>   
>++<<<<<<< HEAD
>+for (auto typestr : state->perf_counters.declared_types) {
>++=======
>+Mutex::Locker l(state->lock);
>+for (const auto &ctr_inst_iter : state->perf_counters.instances) {
>+const auto &typestr = ctr_inst_iter.first;
>+ 
>++>>>>>>> dc415f1... mgr: store declared_types in MgrSession

**Comment by shinobu-x** [comment]
@smithfarm I noticed there was another `mutex`.

**Comment by shinobu-x** [comment]
test this please

**Comment by smithfarm** [comment]
@shinobu-x The problem I see here is the commit message implies the cherry-pick was clean, yet in reality there was a conflict. Now, the conflict description is in the PR, but not in the commit message where it belongs.

**Comment by shinobu-x** [comment]
test this please

**Comment by shinobu-x** [comment]
@smithfarm Please check updated commit message.

**Comment by smithfarm** [comment]
@shinobu-x Thanks. What about the conflict in `src/mgr/PyModules.cc` ? Please try:

```
git fetch $CEPH
git rebase $CEPH/luminous
```

where $CEPH is the name of your ceph/ceph.git remote.

**Comment by shinobu-x** [comment]
@smithfarm Something is different from what I saw previously. I will update the PR.
```
--- a/src/mgr/ActivePyModules.cc
+++ b/src/mgr/ActivePyModules.cc
@@@ -603,20 -732,24 +603,31 @@@ PyObject* ActivePyModules::get_perf_sch
    }
  
    PyFormatter f;
 -  f.open_object_section("perf_schema");
 -
 -  // FIXME: this is unsafe, I need to either be inside DaemonStateIndex's
 -  // lock or put a lock on individual DaemonStates
 -  if (!states.empty()) {
 -    for (auto statepair : states) {
 -      std::ostringstream daemon_name;
 +  if (!daemons.empty()) {
 +    for (auto statepair : daemons) {
        auto key = statepair.first;
        auto state = statepair.second;
++<<<<<<< HEAD:src/mgr/ActivePyModules.cc
 +
 +      std::ostringstream daemon_name;
++=======
++>>>>>>> mgr: store declared_types in MgrSession:src/mgr/PyModules.cc
        daemon_name << key.first << "." << key.second;
        f.open_object_section(daemon_name.str().c_str());
  
        Mutex::Locker l(state->lock);
++<<<<<<< HEAD:src/mgr/ActivePyModules.cc
 +      for (auto ctr_inst_iter : state->perf_counters.instances) {
 +        const auto &counter_name = ctr_inst_iter.first;
 +	f.open_object_section(counter_name.c_str());
 +	auto type = state->perf_counters.types[counter_name];
++=======
+       for (const auto &ctr_inst_iter : state->perf_counters.instances) {
+         const auto &typestr = ctr_inst_iter.first;
+ 
+ 	f.open_object_section(typestr.c_str());
+ 	auto type = state->perf_counters.types[typestr];
++>>>>>>> mgr: store declared_types in MgrSession:src/mgr/PyModules.cc
```

**Comment by shinobu-x** [comment]
@smithfarm Please check.

**Comment by smithfarm** [comment]
@shinobu-x The filename `src/mgr/PyModules.cc` in the conflicts section of the commit message is not correct.

**Comment by shinobu-x** [comment]
@smithfarm Please check.

**Comment by smithfarm** [comment]
@shinobu-x The filename in the conflicts section should be `src/mgr/ActivePyModules.cc`

**Comment by shinobu-x** [comment]
@smithfarm Please check.

**Comment by theanalyst** [comment]
Adding to the integration queue, needs approval from @jcsp before merge as it was a non-clean cherry-pick

**Comment by jcsp** [comment]
This commit seems to have ended up with just a minor tweak to a loop variable: the "mgr: store delcared_types in MgrSession" commit was already backported into luminous as 2fea47d9710ec1e388db044065bc42b8046dae22

**Comment by jcsp** [comment]
This was covered in https://github.com/ceph/ceph/pull/18675

**Pull request closed without merging**
