### PR TITLE
mgr/dashboard: Access control database does not restore disabled users correctly

### PR DESCRIPTION
**Pull request by votdev**
Fixes: https://tracker.ceph.com/issues/41205

Signed-off-by: Volker Theile <vtheile@suse.com>

## Checklist
- [x] References tracker ticket
- [ ] Updates documentation if necessary
- [x] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test docs`
- `jenkins render docs`

</details>

### CODE REVIEW

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by s0nea** [comment]
QA test run failed:

- http://pulpito.ceph.com/tdehler-2019-08-15_07:04:09-rados:mgr-wip-tdehler-testing-29614-distro-basic-mira/
- https://tracker.ceph.com/issues/41306

I don't think the issue is related to this PR but needs to be addressed though.

```
2019-08-16T06:13:31.127 INFO:tasks.cephfs_test_runner:======================================================================
2019-08-16T06:13:31.127 INFO:tasks.cephfs_test_runner:FAIL: test_create_get_update_delete_w_tenant (tasks.mgr.dashboard.test_rgw.RgwBucketTest)
2019-08-16T06:13:31.127 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-08-16T06:13:31.127 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2019-08-16T06:13:31.128 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-tdehler-testing-29614/qa/tasks/mgr/dashboard/test_rgw.py", line 250, in test_create_get_update_delete_w_tenant
2019-08-16T06:13:31.128 INFO:tasks.cephfs_test_runner:    self.assertIn('owner', data)
2019-08-16T06:13:31.128 INFO:tasks.cephfs_test_runner:AssertionError: 'owner' not found in u''
2019-08-16T06:13:31.128 INFO:tasks.cephfs_test_runner:
2019-08-16T06:13:31.128 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-08-16T06:13:31.129 INFO:tasks.cephfs_test_runner:Ran 71 tests in 997.305s
2019-08-16T06:13:31.129 INFO:tasks.cephfs_test_runner:
2019-08-16T06:13:31.129 INFO:tasks.cephfs_test_runner:FAILED (failures=1)
2019-08-16T06:13:31.129 INFO:tasks.cephfs_test_runner:
2019-08-16T06:13:31.130 INFO:tasks.cephfs_test_runner:======================================================================
2019-08-16T06:13:31.130 INFO:tasks.cephfs_test_runner:FAIL: test_create_get_update_delete_w_tenant (tasks.mgr.dashboard.test_rgw.RgwBucketTest)
2019-08-16T06:13:31.130 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-08-16T06:13:31.130 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2019-08-16T06:13:31.130 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-tdehler-testing-29614/qa/tasks/mgr/dashboard/test_rgw.py", line 250, in test_create_get_update_delete_w_tenant
2019-08-16T06:13:31.130 INFO:tasks.cephfs_test_runner:    self.assertIn('owner', data)
2019-08-16T06:13:31.131 INFO:tasks.cephfs_test_runner:AssertionError: 'owner' not found in u''
```

**Comment by votdev** [comment]
jenkins test dashboard

**Comment by p-na** [comment]
QA run failed:

http://pulpito.front.sepia.ceph.com/pnawracay-2019-08-20_08:24:06-rados:mgr-wip-pna-votdev-29604-distro-basic-mira/

Related to:

- https://tracker.ceph.com/issues/41306
- https://tracker.ceph.com/issues/41175

Might be caused by https://github.com/ceph/ceph/pull/29118 (thanks @alfonsomthd).

```
2019-08-20T08:49:48.311 INFO:tasks.cephfs_test_runner:
2019-08-20T08:49:48.312 INFO:tasks.cephfs_test_runner:======================================================================
2019-08-20T08:49:48.312 INFO:tasks.cephfs_test_runner:FAIL: test_create_get_update_delete_w_tenant (tasks.mgr.dashboard.test_rgw.RgwBucketTest)
2019-08-20T08:49:48.312 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-08-20T08:49:48.312 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2019-08-20T08:49:48.313 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-pna-votdev-41205/qa/tasks/mgr/dashboard/test_rgw.py", line 250, in test_create_get_update_delete_w_tenant
2019-08-20T08:49:48.313 INFO:tasks.cephfs_test_runner:    self.assertIn('owner', data)
2019-08-20T08:49:48.313 INFO:tasks.cephfs_test_runner:AssertionError: 'owner' not found in u''
2019-08-20T08:49:48.314 INFO:tasks.cephfs_test_runner:
2019-08-20T08:49:48.314 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-08-20T08:49:48.314 INFO:tasks.cephfs_test_runner:Ran 71 tests in 1099.440s
2019-08-20T08:49:48.314 INFO:tasks.cephfs_test_runner:
2019-08-20T08:49:48.314 INFO:tasks.cephfs_test_runner:FAILED (failures=1)
2019-08-20T08:49:48.315 INFO:tasks.cephfs_test_runner:
2019-08-20T08:49:48.315 INFO:tasks.cephfs_test_runner:======================================================================
2019-08-20T08:49:48.315 INFO:tasks.cephfs_test_runner:FAIL: test_create_get_update_delete_w_tenant (tasks.mgr.dashboard.test_rgw.RgwBucketTest)
2019-08-20T08:49:48.315 INFO:tasks.cephfs_test_runner:----------------------------------------------------------------------
2019-08-20T08:49:48.316 INFO:tasks.cephfs_test_runner:Traceback (most recent call last):
2019-08-20T08:49:48.316 INFO:tasks.cephfs_test_runner:  File "/home/teuthworker/src/git.ceph.com_ceph-c_wip-pna-votdev-41205/qa/tasks/mgr/dashboard/test_rgw.py", line 250, in test_create_get_update_delete_w_tenant
2019-08-20T08:49:48.316 INFO:tasks.cephfs_test_runner:    self.assertIn('owner', data)
2019-08-20T08:49:48.316 INFO:tasks.cephfs_test_runner:AssertionError: 'owner' not found in u''
2019-08-20T08:49:48.316 INFO:tasks.cephfs_test_runner:
```

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2019-08-21_12:58:47-rados-wip-kefu-testing-2019-08-21-1445-distro-basic-mira/
- http://pulpito.ceph.com/kchai-2019-08-23_00:12:22-rados-wip-kefu-testing-2019-08-21-1445-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2019-08-23_03:12:13-rados-wip-kefu-testing-2019-08-21-1445-distro-basic-smithi/

**Pull request merged**
