### PR TITLE
Cache Register!

### PR DESCRIPTION
**Pull request by adamemerson**
Provide the ability to examine and delete elements from the cache.

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@adamemerson does this beg the question how to inspect the cache from another node--e.g., a ceph-mgr process?

**Comment by adamemerson** [comment]
@mattbenjamin Begs the question or leaves it to SSH or ansible or other tooling.

**Comment by adamemerson** [comment]
All right. This should be ready to go. My outpouring of wrath at admin_socket made me realize I wasn't using the format parameter right.

**Comment by adamemerson** [comment]
Jenkins, retest this please.

**Comment by adamemerson** [comment]
http://pulpito.ceph.com/aemerson-2018-02-05_23:41:59-rgw-wip-cache-register-distro-basic-smithi/

**Pull request merged**
