### PR TITLE
osd: bug with cache/tiering and snapshot reads

### PR DESCRIPTION
**Pull request by theanalyst**
http://tracker.ceph.com/issues/13693

### CODE REVIEW

**Comment by theanalyst** [comment]
Since the upstream PR (#6261) needed an additional test case in the qa suite, for the backport PR, it may be necessary to add the specific test to the ceph-qa-suite as well

**Comment by dachary** [comment]
<pre>
teuthology-openstack --verbose --key-name myself --key-filename ~/Downloads/myself --verbose --suite rados --ceph-qa-suite-git-url https://github.com/dachary/ceph-qa-suite.git --suite-branch wip-12748-hammer --ceph-git-url https://github.com/ceph/ceph.git --ceph hammer-backports --filter="export-after-evict.yaml" 
</pre>

* *running* http://167.114.233.32:8081/ubuntu-2015-11-21_08:28:17-rados-hammer-backports---basic-openstack/

Using a backport of the test https://github.com/ceph/ceph-qa-suite/pull/720

**Comment by dachary** [comment]
@tchaikov it passes a rados suite and a backport of the matching test (see https://github.com/ceph/ceph/pull/6589#issuecomment-158612759). Does it look good to merge ?

**Comment by tchaikov** [comment]
lgtm!

**Pull request merged**
