### PR TITLE
rgw: update quota is inconsistent at add/del object with compression

### PR DESCRIPTION
**Pull request by fangyuxiangGL**
keep consistent, use accounted size to update quota

Signed-off-by: fang yuxiang fang.yuxiang@eisoo.com

### CODE REVIEW

**Comment by fangyuxiangGL** [comment]
@cbodley 

could u have a look? thanks.

**Comment by cbodley** [comment]
@fangyuxiangGL we'll want to backport this for luminous, could you please create a tracker issue with steps to reproduce?

**Comment by fangyuxiangGL** [comment]
@cbodley done.

**Comment by yuriw** [comment]
[wip-yuri-testing-2018-01-05-1727](https://trello.com/c/x53HxhYO/220-wip-yuri-testing-2018-01-05-1727)

**Pull request merged**
