### PR TITLE
os/bluestore/BlueFS: tune flushing of writes

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by liewegas** [comment]
@rchagam This may help a bit as well...

**Comment by rchagam** [comment]
Tested this patch yesterday - runs into assertion failure in BlueFS.cc
**
 /root/ceph/src/os/bluestore/BlueFS.cc: 1578: FAILED assert(last.unused_tail_length() == zlen)
**
Detailed stack:
[one.txt](https://github.com/ceph/ceph/files/724044/one.txt)

**Comment by liewegas** [comment]
thanks, fixing

**Comment by liewegas** [comment]
@rchagam fixed

**Comment by rchagam** [comment]
@liewegas works!! looking at performance analysis - will send you update later today.

**Comment by rchagam** [comment]
@liewegas tested with rados bench 4k writes (10 min run) - slightly better throughput and latency with tuned write flushes:
bluestore_rtc - 10.116 (ms), 7,590,743 writes
bluestore_rtc + bluefs tuned flush writes -  10.042 (ms), 7,646,524 writes

**Pull request merged**
