### PR TITLE
rbd-replay: handle EOF gracefully

### PR DESCRIPTION
**Pull request by trociny**
Signed-off-by: Mykola Golub <mgolub@mirantis.com>

### CODE REVIEW

**Comment by trociny** [comment]
@dillaman This is a fix for the issue I described in #7259.

I was testing on a small replay file (less than m_min_bytes), and BufferReader::fetch() went to endless loop because it did not check for EOF.

**Comment by dillaman** [comment]
Thx - can you just break if r == 0 instead of creating a new state variable?

**Comment by trociny** [comment]
If I just break, then when BufferReader::fetch() is called the next time (m_bl_it.get_remaining() is still greater than 0 but less than m_min_bytes) we will try to read from the file again. It does not hurt but I thought it would be better to avoid?

**Comment by dillaman** [comment]
Ok -- no problem. Can you do me a big favor and open a tracker ticket? I think this fix should be backported. Thx.

**Comment by trociny** [comment]
Rebased after adding "Fixes: #14452" to the commit log.

**Pull request merged**
