### PR TITLE
configure.ac: check for libboost_random-mt also

### PR DESCRIPTION
**Pull request by tchaikov**
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by dachary** [comment]
What's the reason for that change ?

**Comment by tchaikov** [comment]
@dachary, i am compiling ceph on my mac, see #5460. and it turns out the libboost_random library installed using brew is named libboost_random-mt.* . and apparently, the reason why we have two AC_CHECK_LIB calls is to detect another name of libboost_random.

**Comment by dachary** [comment]
@tchaikov got it. Could you push it to the gitbuilders to confirm all supported platforms are happy with the change ? With this confirmation:

<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by tchaikov** [comment]
thanks Loïc. pushed, and they are happy!

**Pull request merged**
