### PR TITLE
rgw/notify: process_queue() constructs wait tokens when spawning

### PR DESCRIPTION
**Pull request by cbodley**
process_queue() spawns several coroutines, then waits on a tokens_waiter until all of them complete

but spawned coroutines don't start immediately. if we call waiter.async_wait() before any of the coroutine functions get spawned, it will find `pending_tokens == 0` and return immediately

instead of constructing each token inside the spawned coroutine function, construct them outside of spawn and capture them in the lambda to extend their lifetime until the coroutine's completion

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
- `jenkins test rook e2e`
</details>

### CODE REVIEW

**Comment by cbodley** [comment]
@yuvalif this is a potential issue i noticed when investigating https://tracker.ceph.com/issues/67522 / https://github.com/ceph/ceph/pull/59243. i'm not sure we have any evidence that it's misbehaving though

**Comment by yuvalif** [comment]
> @yuvalif this is a potential issue i noticed when investigating https://tracker.ceph.com/issues/67522 / #59243. i'm not sure we have any evidence that it's misbehaving though

if this problem would happen, we would probably see duplicate notifications.
if we don't wait on the results from the `process_entry()` coroutine, we won't know that sending the notification was successfull, and won't delete it from the queue.
the next time we call `process_entries()` we would see the same notifications and try to send them again.
I don't remember seeing that issue in our tests, but there could be places in the tests suite where we do not check for duplicates.

**Review by yuvalif — APPROVED** [review]

**Comment by cbodley** [comment]
@yuvalif seeing consistent rgw/notification failures in the run https://pulpito.ceph.com/cbodley-2024-09-06_12:10:58-rgw-wip-cbodley-testing-distro-default-smithi/ and rerun https://pulpito.ceph.com/cbodley-2024-09-06_15:25:52-rgw-wip-cbodley-testing-distro-default-smithi/:

> FAIL: test notification of filtering metadata, ampq endpoint
FAIL: test that when object is deleted due to lifecycle policy, http endpoint
FAIL: test persistent topic configurations with time_to_live
FAIL: test persistent topic configurations with max_retries and retry_sleep_duration

this pr seems to be the only thing in the batch related to bucket notifications

in contrast, https://pulpito.ceph.com/cbodley-2024-09-05_03:14:36-rgw-pr-56597-distro-default-smithi/ from yesterday only showed the valgrind leaks

**Comment by yuvalif** [comment]
> @yuvalif seeing consistent rgw/notification failures in the run https://pulpito.ceph.com/cbodley-2024-09-06_12:10:58-rgw-wip-cbodley-testing-distro-default-smithi/ and rerun https://pulpito.ceph.com/cbodley-2024-09-06_15:25:52-rgw-wip-cbodley-testing-distro-default-smithi/:
> 
> > FAIL: test notification of filtering metadata, ampq endpoint
> > FAIL: test that when object is deleted due to lifecycle policy, http endpoint
> > FAIL: test persistent topic configurations with time_to_live
> > FAIL: test persistent topic configurations with max_retries and retry_sleep_duration
> 
> this pr seems to be the only thing in the batch related to bucket notifications
> 
> in contrast, https://pulpito.ceph.com/cbodley-2024-09-05_03:14:36-rgw-pr-56597-distro-default-smithi/ from yesterday only showed the valgrind leaks

i get similar failures when running locally as well - will investigate

**Pull request merged**
