### PR TITLE
osd: Decode use_gmt_hitset with a unique version

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
@liewegas Shouldn't we use unique encode versions for different fields?

**Comment by liewegas** [comment]
yes.. this lgtm

**Comment by tchaikov** [comment]
@liewegas @dzafman i am not sure why we can not add two or more fields, say `foo`, `bar` when bumping up the encode version for a struct, if we do not do a release after introducing `foo` and before `bar` ?

**Comment by liewegas** [comment]
@tchaikov yeah fair enough.  i wasn't sure if there was or wasn't a release in between.

**Comment by dzafman** [comment]
@tchaikov @liewegas I am use to seeing 1 field per version bump and it confused me during a rebase because I was adding a field too.

**Pull request merged**
