### PR TITLE
mimic: rgw: resharding fixes

### PR DESCRIPTION
**Pull request by theanalyst**
https://tracker.ceph.com/issues/37554
https://tracker.ceph.com/issues/37447

- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

### CODE REVIEW

**Comment by theanalyst** [comment]
Adding this to the next mimic suite (as we're merging another rados last minute pr), If this passes QE  maybe it can go in?

**Comment by smithfarm** [comment]
> If this passes QE maybe it can go in?

+1 from my side, as long as one of the RGW core devs approves.

**Comment by cbodley** [comment]
:+1: i'd love to see this also, but i'll defer to @ivancich to doublecheck his commits

**Comment by ivancich** [comment]
jenkins test make check

**Comment by theanalyst** [comment]
jenkins seems to be failing with a dashboard frontend build failure triggered by some nodejs thingy

**Comment by theanalyst** [comment]
tested on a vstart cluster, working as expected, New reshards do not create stale instances anymore and older stale instaces are picked up by the admin tool as expected

**Comment by ivancich** [comment]
It looks like Yuri is testing it. So it seems reasonable that if it passes QA it can be merged given the jenkins issue(s).

**Comment by theanalyst** [comment]
jenkins issues will be hopefully fixed by https://github.com/ceph/ceph/pull/26814

**Comment by sebastian-philipp** [comment]
jenkins retest this please

**Comment by yuriw** [comment]
[wip-yuri3-testing-2019-03-05-1606-mimic](https://trello.com/c/4jMXbkqv/552-wip-yuri3-testing-2019-03-05-1606-mimic)

**Pull request merged**
