### PR TITLE
rgw: drop iter in rgw_op.cc

### PR DESCRIPTION
**Pull request by qrGitHub**

### CODE REVIEW

**Comment by qrGitHub** [comment]
Hi @cbodley, can this be merged? Thanks.

**Comment by joscollin** [comment]
@qrGitHub Resolve your conflicts and push again.

**Comment by joscollin** [comment]
@qrGitHub Sorry *the conflicts*

**Comment by qrGitHub** [comment]
Hi @cbodley @joscollin, can this be merged to prevent conflict again? Thanks.

**Pull request merged**
