### PR TITLE
rbd: Fix warning for uninitialized MirrorSnapshotNamespace::state

### PR DESCRIPTION
**Pull request by gbangera**
Fixes: https://tracker.ceph.com/issues/52753
Signed-off-by: Geetika Bangera <gbangera@cs.stonybrook.edu>

## Checklist
- [ ] References tracker ticket
- [ ] Updates documentation if necessary
- [ ] Includes tests for new functionality or reproducer for bug

---

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

### CODE REVIEW

**Comment by ideepika** [comment]
https://shaman.ceph.com/builds/ceph/wip-pr-43396/c13687d94b2c578166d80763d8556763e0717a35/default/283525/

**Comment by ideepika** [comment]
https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/57777//consoleFull

**Comment by ideepika** [comment]
jenkins test make check

**Review by trociny — COMMENTED** [review]
I don't quite understand why the old version produced the warnings.

It is not that I mind much, but the old way seemed prefered in modern Ceph world.

@tchaikov Have you any thoughts about this?

**Comment by ljflores** [comment]
@gbangera @ideepika @idryomov @trociny is this PR still needed?

**Comment by ideepika** [comment]
> @gbangera @ideepika @idryomov @trociny is this PR still needed?

I am not sure if we still  see this warning or not, but since we'd like a different approach rather than using old style, this PR will need changes. I will see if we see this issue again or in latest gcc version or not

**Comment by idryomov** [comment]
Looks like this warning is no longer there with a newer g++:

https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/63582/consoleText

**Pull request closed without merging**
