### PR TITLE
qa/suites/rados/mgr/tasks/dashboard: add MDS_ALL_DOWN to whitelist

### PR DESCRIPTION
**Pull request by rjfd**
Signed-off-by: Ricardo Dias <rdias@suse.com>

### CODE REVIEW

**Comment by rjfd** [comment]
Dashboard QA suite has been failing with a health check error due to `MDS_ALL_DOWN`. By looking at the MDS logs, the MDS are killed and restarted successfully, and therefore I think this health check error should be ignored.

@jcsp is my hypothesis correct, or am I missing something?

**Comment by tchaikov** [comment]
@rjfd i think this health reporting is expected and it is introduced by a recent change at https://github.com/ceph/ceph/commit/0a59560954af3e065f067ffdbb407a97284144c2

**Comment by tchaikov** [comment]
being tested at http://pulpito.ceph.com/kchai-2018-04-20_14:33:42-rados-wip-kefu-testing-2018-04-20-1141-distro-basic-mira/

**Comment by tchaikov** [comment]
seems we need whitelist MDS_ALL_DOWN to more tests.

**Comment by rjfd** [comment]
@tchaikov added another commit that adds `MDS_UP_LESS_THAN_MAX` to the whitelist as well

**Comment by tchaikov** [comment]
retest this please

**Comment by tchaikov** [comment]
- http://pulpito.ceph.com/kchai-2018-04-21_06:05:10-rados-wip-kefu-testing-2018-04-21-0943-distro-basic-smithi/
- http://pulpito.ceph.com/kchai-2018-04-21_11:36:06-rados-wip-kefu-testing-2018-04-21-1717-distro-basic-mira/

we need another PR to whitelist MDS_ALL_DOWN in more tests though.

**Comment by tchaikov** [comment]
@rjfd could you squash these two commits into a single one?

**Comment by rjfd** [comment]
@tchaikov done

**Comment by tchaikov** [comment]
i am adding MDS_ALL_DOWN to all tests in https://github.com/ceph/teuthology/pull/1168 .

**Pull request merged**
